### ISSUE TITLE
What is ROC-smi?

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/ROCm#10]
The README.md has ROC-smi as one of the project that was released as part of 1.1 release. But the link is not working. What is it? Inquiring mind wants to know! :)

**Comment by arodrigx7** [comment]
Hey Brian,

ROC-smi is a tool for system management in ROCm enabled systems. Some of the basic things you can do with it is manage the clocks of your GPUs, view temperatures, etc.

After install the rocm 1.1 binary packages, you can find the tool under /opt/rocm/bin/rocm-smi

Thanks for reminding me that I need to add a small README.md to that project.

**Comment by arodrigx7** [comment]
The repository was still marked as private, thats why the link was broken. I've made it public now.

**Comment by arodrigx7** [comment]
Thanks for the quick issue report btw.
