### ISSUE TITLE
can You please update ROCM to support 5.3+ kernels?

### ISSUE THREAD

**Issue by witeko** [RadeonOpenCompute/ROCm#1001]
ubuntu 18.04 has started to update to 5.3

**Comment by cryptomilk** [comment]
Are you sure that this isn't a bug in Ubuntu?

I'm running

`Linux magrathea 5.4.14-1-default #1 SMP Thu Jan 23 08:54:47 UTC 2020 (fc4ea7a) x86_64 x86_64 x86_64 GNU/Linux`

and it works just fine with ROCm 2.10.0.

**Comment by witeko** [comment]
Im talking about the DKMS driver, its currently restricted to kernels up to 5.0,
Your are probably using the "upstream kernel" driver which doesnt suit me.

**Comment by rkothako** [comment]
We will have ROCm 3.1 which supports 5.3 kernel also.

**Comment by witeko** [comment]
@rkothako thx :)

**Comment by ddobreff** [comment]
> We will have ROCm 3.1 which supports 5.3 kernel also.

Latest LTS kernel is 5.4. Is it going to be supported too?

**Comment by ROCmSupport** [comment]
Thanks for reaching out.
This issue is fixed and not observed with the latest ROCm 4.1.
Hence recommend you to try with the same.
Feel free to open a new issue, for any, for quick resolution.
Thank you.
