### ISSUE TITLE
How to represent NaN compatible with ROCm?

### ISSUE THREAD

**Issue by pbelevich** [RadeonOpenCompute/ROCm#1004]
I tried to use std::nan("") and std::nanf("") but got this:

error:  'nan':  no overloaded function has restriction specifiers that are compatible with the ambient context ...

**Comment by AlexVlx** [comment]
Soft assigning to @b-sumner since this is his area of expertise.

**Comment by b-sumner** [comment]
HIP (and Cuda) provide float nanf(const char *) and double nan(const char *) device functions to create NaNs.

**Comment by pbelevich** [comment]
thanks!
