### ISSUE TITLE
clinfo crashes on upstream kernel 5.5.0

### ISSUE THREAD

**Issue by jcdutton** [RadeonOpenCompute/ROCm#1007]
clinfo hangs when run on kernel 5.5.0
clinfo works fine on kernel 5.4.15

dmesg output below

**Comment by jcdutton** [comment]
[clinfo-bad1.log](https://github.com/RadeonOpenCompute/ROCm/files/4117258/clinfo-bad1.log)

**Comment by jcdutton** [comment]
GPU is a AMD Vega 56

**Comment by JMadgwick** [comment]
The homepage doesn't mention support for those kernels. Maybe try following the instructions for using upstream kernels?

**Comment by pramenku** [comment]
ROCm currently doesn't support kernel 5.5.0

**Comment by seesturm** [comment]
Only the kernel modules shipped with ROCm (rocm-dkms) fail with kernel 5.5. For me, ROCm 3.0 itself is working fine with the kernel modules directly provided by kernel 5.5 (5.5.7) for both OpenCL and HIP.

Maybe this information is useful for someone wanting to use ROCm with kernel 5.5.

**Comment by ROCmSupport** [comment]
Thanks for reaching out.
This issue is fixed and not observed with the latest ROCm 4.1.
Hence recommend you to try with the same.
Feel free to open a new issue, for any, for quick resolution.
Thank you.
