### ISSUE TITLE
Repository not signed

### ISSUE THREAD

**Issue by ohms-law** [RadeonOpenCompute/ROCm#1009]
Hi there,

under Tumbleweed I installed from the 

http://repo.radeon.com/rocm/zyp/2.10.0/

repository.

zypper complained that neither repo nor files are signed.

Do you see a possibility to change that?
Would something like openSUSE Build Service be an alternative?

**Comment by ROCmSupport** [comment]
Thanks @ohms-law 
This issue is fixed and not observed with the latest ROCm 4.1.
Hence recommend you to try with the same.
Feel free to open a new issue, for any, for quick resolution.
Thank you.
