### ISSUE TITLE
Install ROCm on Ubuntu without affecting display

### ISSUE THREAD

**Issue by Ian-Mint** [RadeonOpenCompute/ROCm#1010]
I am running Ubuntu 18.04, and I have tried two different strategies to install ROCm.

[1] following the instructions here: https://github.com/RadeonOpenCompute/ROCm#Ubuntu

This does work, but when I reboot, I am limited to very low resolution.

[2] install rocm with amdgpu-pro following these instructions: https://www.amd.com/en/support/kb/faq/gpu-635

And the installation fails with the error:

nomodeset detected in kernel parameters. amdgpu requires KMS
I have verified that nomodeset is not present in /etc/default/grub

So, is there a good solution to either the first or the second problem?

OS: Ubuntu 18.04.4 LTS | GPU: Radeon HD 8830M / R7 M465X

**Comment by 7allom** [comment]
Hi, I got the same problem as you.
Were you able to solve it?

**Comment by Ian-Mint** [comment]
> Hi, I got the same problem as you. Were you able to solve it?

Nope, sorry @7allom. Maybe re-open the issue and add your details.

**Comment by 7allom** [comment]
> > Hi, I got the same problem as you. Were you able to solve it?
> 
> Nope, sorry @7allom. Maybe re-open the issue and add your details. I'm pretty sure I closed this to after just giving up on ROCm entirely.

Okay thank you.
I am trying now to install now I hope it works
