### ISSUE TITLE
How can I get the code rocm-dkms 1.8 or 1.8.3 Debian?

### ISSUE THREAD

**Issue by nuu9323226** [RadeonOpenCompute/ROCm#1016]
sorry,i have a question.
I need to get the previous version for some reasons, but these files are all deleted on the official Debian repository. I wonder if there is still a chance to download version 1.8 or 1.8.3 Debian
Do you know how to get?
Only the oldest historical version is only retained until 1.9.3
http://repo.radeon.com/rocm/apt/1.9.3/

**Comment by AGenchev** [comment]
I wonder is there a *political* reason Debian to be not supported despite the name "Debian" is cited thousand times in the documentation ?

**Comment by ROCmSupport** [comment]
Hi @nuu9323226 
Thanks for reaching out.
We are not officially supporting debian OS. But you can tweak things on ubuntu debs and sue accordingly.
Thank you.
