### ISSUE TITLE
ROCmInstall.html typos

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/ROCm#1018]
not sure what happened over at https://rocm.github.io/ROCmInstall.html
but it looks like some "|" pipe characters are not there, or rendering anymore

```
	echo 'ADD_EXTRA_GROUPS=1' 		
 sudo tee -a /etc/adduser.conf   
	echo 'EXTRA_GROUPS=video' 		
 sudo tee -a /etc/adduser.conf
```

this doesn't make sense as it's missing the pipe before "sudo"

**Comment by valeriob01** [comment]
On Debian sudo is not installed by default I think. The command should be:

su -c 'tee -a /etc/adduser.conf'

**Comment by seesturm** [comment]
The instructions got broken with [this commit](https://github.com/RadeonOpenCompute/ROCm/commit/f0d15004a0c7fa61c87e014da347c9765f7cdcd9#diff-04c6e90faac2675aa89e2176d2eec7d8) and have not been really fixed since. The last good version (maybe a bit outdated) of README.md is [this](https://github.com/RadeonOpenCompute/ROCm/tree/a899984e4e46f81bf0b5aedb32c538579da4651e).

Wrt Debian: The instructions are actually for Ubuntu. I doubt that ROCm will work on Debian.

**Comment by valeriob01** [comment]
> The instructions got broken with [this commit](https://github.com/RadeonOpenCompute/ROCm/commit/f0d15004a0c7fa61c87e014da347c9765f7cdcd9#diff-04c6e90faac2675aa89e2176d2eec7d8) and have not been really fixed since. The last good version (maybe a bit outdated) of README.md is [this](https://github.com/RadeonOpenCompute/ROCm/tree/a899984e4e46f81bf0b5aedb32c538579da4651e).
> 
> Wrt Debian: The instructions are actually for Ubuntu. I doubt that ROCm will work on Debian.

Obviously it work on Debian I use it all the time. All my machines are Debian with ROCm.

**Comment by valeriob01** [comment]
> > The instructions got broken with [this commit](https://github.com/RadeonOpenCompute/ROCm/commit/f0d15004a0c7fa61c87e014da347c9765f7cdcd9#diff-04c6e90faac2675aa89e2176d2eec7d8) and have not been really fixed since. The last good version (maybe a bit outdated) of README.md is [this](https://github.com/RadeonOpenCompute/ROCm/tree/a899984e4e46f81bf0b5aedb32c538579da4651e).
> > Wrt Debian: The instructions are actually for Ubuntu. I doubt that ROCm will work on Debian.
> 
> Obviously it work on Debian I use it all the time. All my machines are Debian with ROCm.

PS: Just needs to modify the install procedure a bit and it works.

**Comment by jlgreathouse** [comment]
This should be fixed in https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html, which has replaced our rocm.github.io documentation. Thanks!
