### ISSUE TITLE
OpenCL codegen: make use of the GCN VOP3 output modifiers

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1021]
The GCN VOP3 instructions offer an output modifier which is a multiplication by 0.5, 2, or 4 *for free*. OTOH the generated code for OpenCL never uses these output modifiers. This is a pity -- the generated code does not use GCN to its full power.

Please enable OMOD (output modifiers) in the generated code, at least when compiling with -cl-fast-relaxed-math.

**Comment by preda** [comment]
To illustrate, this OpenCL fragment
```
  // double a, b;
  double c = 4 * (a * a + b);
```
Is compiled to
```
	v_fma_f64 v[0:1], v[4:5], v[4:5], v[0:1]
	v_mul_f64 v[0:1], v[0:1], 4.0
```
but the second instruction (v_mul_f64) becomes unnecessary if OMOD were used.

**Comment by b-sumner** [comment]
@preda output modifiers are not compatible with denorms so at a minimum the options would have to include -cl-denorms-are-zero.  However, we have no plans to support denorm flushing for double precision where most users care more about accuracy.

**Comment by preda** [comment]
what about users that request both -cl-fast-relaxed-math and -cl-denorms-are-zero ? I think it's pretty explicit that they are fine with flushed denorms, and that they care more about speed than accuracy.

Anyway, there should be a way to get really high performance GCN code generated, which ideally does not involve writing the GCN instructions by hand.

**Comment by b-sumner** [comment]
Yes, we can consider enabling modifiers with that combination.  I have to admit it's pretty surprising that you're OK with flushing denorms in double precision work.  Why are you using double precision at all if you don't care about accuracy (I do know that precision and accuracy are completely different topics).

**Comment by preda** [comment]
Here is an article discussing denormals: https://blogs.mathworks.com/cleve/2014/07/21/floating-point-denormals-insignificant-but-controversial-2/

In double-precission, denormals come into play for numbers with magnitude under 10^-308. It is possible that in gpuowl's case we commonly work with larger-magnitude values, in which situation the "flush denorms" has no impact on accuracy.

We use double precission because we need as many bits of precission per value as possible, and DP offers more than twice bits of mantissa compared to SP (I think 53 vs. 24). Of course DP is significantly slower than SP, but in our case it still pays offs to use DP.

BTW it may turn out that DP performance is an advantage of AMD GPUs compared to the competition; that's one more reason to push for really well optimized code out of the compiler, able to show what the hardware is capable of.

**Comment by ROCmSupport** [comment]
Hi @preda 
Thanks for reaching out.
Can you please check and update on this with ROCm 4.1.
Feel free to share an update or close this issue, if no more relevant.
Thank you.

**Comment by preda** [comment]
@ROCmSupport I can not try out ROCm 4.1 because it does not recognize my GPU (Radeon VII) anymore with the standard linux kernel (I can use any kernel between 5.4.x and 5.12.x, but apparently none works); this setup was working with earlier ROCm releases and was broken in 4.1. I'm waiting for a new ROCm release that works with the mainline amdgpu driver.

But coming back to the issue here, why do you ask me to re-check -- do you have any indication that this issues may have been fixed?

**Comment by valeriob01** [comment]
@preda I am using kernel 5.4 and it works, not sure if upstream driver ...

**Comment by ROCmSupport** [comment]
Hi @preda 
Many changes went into ROCm 4.x code and found that many issues resolved too, hence I asked.

Thank you.

**Comment by preda** [comment]
@b-sumner did the team enable OMOD with -cl-fast-relaxed-math and -cl-denorms-are-zero? if you confirm that yes (i.e. that some work was done in that direction), I'll check and confirm on 4.1. Otherwise, @ROCmSupport for sure it didn't "fix itself" on ROCm 4.1 simply because there were many changes in ROCm 4.1

**Comment by b-sumner** [comment]
We have a review out for an option to disable IEEE mode that would likely need to be accompanied by -fno-honor-nans to get the desired effect, but it is currently stalled.

**Comment by preda** [comment]
Merge into #1405
