### ISSUE TITLE
This starts to be serious

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1031]
It seems there is lack of quality control on ROCm development.

**Comment by valeriob01** [comment]
> It seems there is lack of quality control on ROCm development.

maybe you can explain your thumbs down where most applications fail to run.
I have been following ROCm from version 1.9, it has been a battle to keep my system running, with multiple downgrades after upgrades.

**Comment by nikAizuddin** [comment]
> where most applications fail to run.

Hi @valeriob01  which applications that you failed to run?

**Comment by valeriob01** [comment]
> > where most applications fail to run.
> 
> Hi @valeriob01 which applications that you failed to run?

gpuowl

**Comment by preda** [comment]
I propose to close this issue, as there is a separate one tracking the concrete case.

I do appreaciate a lot the existence of the communication channel with AMD developers represented by this forum. I think both the internal team as well as us on the outside do wish to make ROCm better, and I imagine they may be operating under various constraints that are not readily visible to us on the outside.

**Comment by valeriob01** [comment]
Moved back to ROCm 2.10 again. Will not try to upgrade again until there is a clear statement that things work.

**Comment by stefan-reich** [comment]
@valeriob01 Why 2.10 exactly? I am curious as to which version you recommend as installation of ROCm 3.1 on my Ryzen 5 2500U has apparently just failed.

**Comment by valeriob01** [comment]
> @valeriob01 Why 2.10 exactly? I am curious as to which version you recommend as installation of ROCm 3.1 on my Ryzen 5 2500U has apparently just failed.

2.10 is the last working version.
Other people have upgraded and moved back again, on different systems than my system, thus there is an evident problem with 3.1

**Comment by stefan-reich** [comment]
I installed 2.10.14 as in #284, but clinfo still segfaults. It didn't compile anything this time, maybe it's still having some 3.1 files around?

**Comment by valeriob01** [comment]
> I installed 2.10.14 as in #284, but clinfo still segfaults. It didn't compile anything this time, maybe it's still having some 3.1 files around?

Rarely I do a rollback, more often I do a fresh install and it works all the times.

**Comment by valeriob01** [comment]
> I propose to close this issue, as there is a separate one tracking the concrete case.
> 
> I do appreaciate a lot the existence of the communication channel with AMD developers represented by this forum. I think both the internal team as well as us on the outside do wish to make ROCm better, and I imagine they may be operating under various constraints that are not readily visible to us on the outside.

apparently pestering here about quality has effects:
https://www.phoronix.com/scan.php?page=news_item&px=AMD-Linux-Hire-Lead-Kernel-Dev

**Comment by jlgreathouse** [comment]
I'm sorry to hear about the issues you had during the upgrade cycle that was going on at the time. Hopefully things have improved in recent releases. If not, I hope that you will submit focused reports on the exact issues so that we can trace them down and fix them. Thank you!

**Comment by valeriob01** [comment]
Since then I moved to Ubuntu and solved the issue.
