### ISSUE TITLE
Status of Merlin Falcon

### ISSUE THREAD

**Issue by ribalda** [RadeonOpenCompute/ROCm#104]
On the website Merlin Falcon status appears as: 

AMD Merlin/Falcon Embedded System is also not currently supported by the public Repo.

Is there a way to get access to the "private repo"/preview?

We (qtec) already have NDA with AMD.

**Comment by gstoner** [comment]
This is supported out of our embedded team

**Comment by ribalda** [comment]
@gstoner  This means that ROCM already supports Merlin Falcon, or that I need to ping the Embedded Team. And where? Thansk!
