### ISSUE TITLE
Minor code generation optimization

### ISSUE THREAD

**Issue by gwoltman** [RadeonOpenCompute/ROCm#1043]
I'm using rocm 2.10

Both
  int  f = (d & 0xFFF00FFF) | (e & 0x000FF000);
and
  int  f = (d & 0xFFF00FFF) + (e & 0x000FF000);

could generate a single V_BFI_B32 instruction rather than these 2 instructions:

	v_and_b32_e32 v3, 0xff000, v4
	v_and_or_b32 v2, v2, s4, v3

**Comment by gwoltman** [comment]
Also, I think

int f = (d & 0xFFF00FFF) | 0x000AB000;

could do a bit-field-insert as well

**Comment by ROCmSupport** [comment]
Thanks @gwoltman for reaching out.
As you tried it on old ROCm version: 2.10, recommend you to try with the latest ROCm 4.1 and file a new issue, if any, for quick response.
Thank you.
