### ISSUE TITLE
How to get GPU utilization in C++ code

### ISSUE THREAD

**Issue by zhangheng408** [RadeonOpenCompute/ROCm#1046]
except by read `/sys/class/drm/card0//device/gpu_busy_percent`.
I wonder whether rocm provided a library like nvml.

**Comment by valeriob01** [comment]
There is the performance API: https://github.com/GPUOpen-Tools/gpu_performance_api

**Comment by eshcherb** [comment]
You can use profiler https://github.com/ROCm-Developer-Tools/rocprofiler
There are a number of derived metrics:
https://github.com/ROCm-Developer-Tools/rocprofiler/blob/amd-master/test/tool/metrics.xml#L76

**Comment by jlgreathouse** [comment]
Hi @zhangheng408 

Thank you for the question, and I apologize for the long delay in getting back to you. Yes, we have an NVML-style library, [rocm-smi-lib](https://github.com/RadeonOpenCompute/rocm_smi_lib).

In particular, if you want to get the `gpu_busy_percent` value, you can use the function [rsmi_dev_busy_percent_get](https://github.com/RadeonOpenCompute/rocm_smi_lib/blob/rocm-3.10.0/include/rocm_smi/rocm_smi.h#L1913).

Thanks!

**Comment by williamfgc** [comment]
As of 2024 [amdsmi](https://github.com/ROCm/amdsmi):

```
Note: This project is a successor to [rocm_smi_lib](https://github.com/RadeonOpenCompute/rocm_smi_lib)

and [esmi_ib_library](https://github.com/amd/esmi_ib_library)
```
