### ISSUE TITLE
Order of registers in commutative instructions

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1053]
I'm looking at the ISA generated for some OpenCL kernel (ROCm 3.1, Vega20), and I see this as a diff between two compilations of slightly different (but equivalent) source code:
```
4122c4122
<       v_add_u32_e32 v7, v7, v8
---
>       v_add_u32_e32 v7, v8, v7
4141c4141
<       v_add_u32_e32 v9, v20, v9
---
>       v_add_u32_e32 v9, v9, v20
4154c4154
<       v_add_u32_e32 v21, v21, v9
---
>       v_add_u32_e32 v21, v9, v21
4179c4179
<       v_add_u32_e32 v13, v28, v13
---
>       v_add_u32_e32 v13, v13, v28
```

As you see, the difference consists only in the order of the two VGPRs into an add. I'd like to know, is there any difference *at all* between e.g. v_add_u32 v0, v0, v1 and v_add_u32_e32 v0, v1, v0 ? If there isn't any, then the compiler could canonicalize them (by chosing a consistent order when the order doesn't matter).

**Comment by arsenm** [comment]
They're equivalent, and there's no real advantage beyond reducing diffs to trying to provide a consistent order based on the register number. It's possible there are bugs where the compiler pointlessly commutes instructions, but in general it's probably not worth the compile time to reorder operands by register number once allocated.

**Comment by ROCmSupport** [comment]
Thanks @preda for reaching out.
As per the update from our dev(@arsenm), I am closing this ticket now.
Feel free to open a new issue, if any, for quick resolution.
Thank you.
