### ISSUE TITLE
Obscure __asm bug:  "A" qualifier does not work

### ISSUE THREAD

**Issue by gwoltman** [RadeonOpenCompute/ROCm#1054]
__asm("v_bfe_u32 %0, %1, %2, 1" : "=v" (b1) : "v" (b2), "A" (i));

where b1 and b2 are variables and "i" is a constant, generates this error:

error: invalid input constraint 'A' in asm

The "A" constraint means a constant in the -16 to 64 range according to https://gcc.gnu.org/onlinedocs/gcc/Machine-Constraints.html#Machine-Constraints

**Comment by arsenm** [comment]
Support for the A modifier added here: https://reviews.llvm.org/rGb087b91c917087bc53d47282a16ee4af78bfe286

A lot of these other constraints GCC apparently has are still missing though.

**Comment by ROCmSupport** [comment]
Thanks @gwoltman for reaching out.
As per the update from our dev(@arsenm), I am closing this ticket now.
Feel free to open a new issue, if any, for quick resolution.
Thank you.
