### ISSUE TITLE
no information on second GPU

### ISSUE THREAD

**Issue by siorenai** [RadeonOpenCompute/ROCm#1057]
Why do these warnings appear and how can I fix it? Thank you.

> WARNING: GPU[1] : Unable to read /sys/class/hwmon/hwmon4/temp1_input
> WARNING: GPU[1] : Unable to read /sys/class/hwmon/hwmon4/power1_average
> WARNING: GPU[1] : Unable to read /sys/class/hwmon/hwmon4/pwm1
> 
> GPU  Temp   AvgPwr  SCLK    MCLK    Fan    Perf  PwrCap  VRAM%  GPU%
> 1            N/A    N/A     N/A     N/A         None%   off   25.0W     N/A        0%

**Comment by ROCmSupport** [comment]
Hi @siorenai 
Thanks for reaching out.
Until there is no hardware issue, this issue is no more observed with ROCm 4.1, I just tried with 4.1 locally and able to detect 2nd GPU also.
Feel free to open a new issue, if any, for quick resolution.
Thank you.
