### ISSUE TITLE
need to install libncurses5 not documented

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1067]
https://github.com/preda/gpuowl/issues/133

**Comment by preda** [comment]
@AMD it seems this libncurses5 issue is affecting a lot of users. A pity to crash for such a petty and frankly unrelated lib.

**Comment by ROCmSupport** [comment]
Hi @valeriob01 
Thanks for reaching out.
This issue is fixed and no more observed now with the latest ROCm 4.1, request you to try with the same.
Thank you.
