### ISSUE TITLE
Is there a schedule for support RHEL/CentOS 8.0?

### ISSUE THREAD

**Issue by codecor-cn** [RadeonOpenCompute/ROCm#1071]

**Comment by akostadinov** [comment]
see #904, hope somebody get that done. RHEL 7 is very old and needs SCL packages which is a nuisance.

**Comment by ROCmSupport** [comment]
H @codecor-cn 
Thanks for reaching out.
ROCm 4.0 and 4.1 supports RHEL 8.2, 8.3 respectively, request you to try for the same.
Thank you.
