### ISSUE TITLE
Rocm compiler -- improper warning

### ISSUE THREAD

**Issue by gwoltman** [RadeonOpenCompute/ROCm#1076]
Using rocm 3.1.

MIDDLE is a passed to the compiler using -D, as in -DMIDDLE=10
I assume the compiler would also barf if I used "#define MIDDLE 10"

Rocm is complaining about valid C code (messages at end of this message):

length = (MIDDLE <= 12 || MIDDLE == 15) ? 1 : 2;
and
if ((MIDDLE >= 6 && MIDDLE <= 8) || (MIDDLE >= 11 && MIDDLE <= 13) ...

It also seems that after warning several times, the compiler aborts.

/tmp/comgr-01e5ad/input/CompileSource:1663:24: warning: use of logical '||' with constant operand
length = (MIDDLE <= 12 || MIDDLE == 15) ? 1 : 2;
                       ^  ~~~~~~~~~~~~
/tmp/comgr-01e5ad/input/CompileSource:1663:24: note: use '|' for a bitwise operation
length = (MIDDLE <= 12 || MIDDLE == 15) ? 1 : 2;
                       ^~
                       |
/tmp/comgr-01e5ad/input/CompileSource:1834:18: warning: use of logical '&&' with constant operand
if ((MIDDLE >= 6 && MIDDLE <= 8) || (MIDDLE >= 11 && MIDDLE <= 13) {
                 ^  ~~~~~~~~~~~
/tmp/comgr-01e5ad/input/CompileSource:1834:18: note: use '&' for a bitwise operation
if ((MIDDLE >= 6 && MIDDLE <= 8) || (MIDDLE >= 11 && MIDDLE <= 13) {
                 ^~
                 &

**Comment by gwoltman** [comment]
Correction:  The compiler aborting after several warnings was something else (mismatched paren).

**Comment by ROCmSupport** [comment]
Thanks @gwoltman for reaching out.
Can you please verify with ROCm 4.0 and share an update asap for moving this ticket to next level in a faster manner.
Thank you.

**Comment by ROCmSupport** [comment]
Closing this as there is no response from the user.
Thank you.
