### ISSUE TITLE
ETA for ROCm + complete OpenCL 1.2 release on Polaris ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#108]
I don't want to be that guy, but....... any idea on when this stack will be available?

Also, interested in using inline GCN ISA with OpenCL on ROCm .

**Comment by gstoner** [comment]
ROCm runs on Polaris today,   OpenCL Developer Preview also does, what your asking is when is the next release.

greg
On Apr 25, 2017, at 1:56 PM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't want to be that guy, but....... any idea on when this stack will be available?

Also, interested in using inline GCN ISA with OpenCL on ROCm .

**Comment by boxerab** [comment]
Thanks, edited.

**Comment by gstoner** [comment]
Inside a week

Greg
On Apr 25, 2017, at 2:02 PM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, edited.

**Comment by boxerab** [comment]
wow, fabulous!
