### ISSUE TITLE
ROCm support for RX5700

### ISSUE THREAD

**Issue by SimoSera** [RadeonOpenCompute/ROCm#1083]
Does now RX 5700 series support ROCm? if not, is there a scheduled release date?

Thanks.

**Comment by huanzhang12** [comment]
No, and unfortunately there is even no official schedule for it. See https://github.com/RadeonOpenCompute/ROCm/issues/887

**Comment by Bengt** [comment]
So basically, ROCm support for the gfx10 instruction set architecture will likely come with the release of a server-oriented compute card using it. That may happen soon or not at all, depending on company and market politics.

**Comment by sqlmap3** [comment]
ROCm support for RX5700xt？

**Comment by ROCmSupport** [comment]
Hi @SimoSera and all,
ROCm does not support Navi series of cards right now. But the support of some Navi cards will come in this year(2021).
Please stay tuned for the updates via our ROCm documentation.
Thank yo.
