### ISSUE TITLE
 whether ROCm Release Notes v3.3.0 can be deployed properly

### ISSUE THREAD

**Issue by jackyin68** [RadeonOpenCompute/ROCm#1085]
Whether AMD ROCm Release Notes v3.3.0 can be deployed in Ubuntu 18.04..04?
Very confused, cost a lot of time, HSA_STATUS_ERROR_OUT_OF_RESOURCES cannot be resolved.
Kindly person can give the answer or give up?

**Comment by MatPoliquin** [comment]
I got the same problem You can role back to 3.1.1 by setting the rocm repo to:
`http://repo.radeon.com/rocm/apt/3.1.1/`
reinstall and reboot

**Comment by jackyin68** [comment]
thanks,ubuntu 18.04 Or ubuntu 18.03

**Comment by MatPoliquin** [comment]
@jackyin68 I use Ubuntu 19.10

**Comment by jackyin68** [comment]
Great, I try again.  many compositions have been tried bot failed.

**Comment by jackyin68** [comment]
@MatPoliquin do your system work well?

**Comment by MatPoliquin** [comment]
@jackyin68 Ubuntu 19.10 with rocm 3.1.1 on a RX580 works ok

**Comment by emerth** [comment]
Check if your user account has R/W on /dev/kfd, and /dev/dri/*.
If not, change the permissions to allow R/W and try again.
Note your udev sysbysytem probably reset the permissions on reboot. For udev, see udev documentation.

**Comment by jackyin68** [comment]
Rx550 does not work

**Comment by mochounan** [comment]
The rx580 video card on Ubuntu 18.04 starts the training interface. The mouse can't click any event, and the training time is 60 times less than that of CPU. Have you ever encountered similar problems?

**Comment by ROCmSupport** [comment]
Thanks @jackyin68 for reaching out.
I will take a look at this request.

**Comment by ROCmSupport** [comment]
Hi @jackyin68 
As this issue is related to 3.3 and as we do not see any issues with ROCm 4.0 and 4.0 supports Ubuntu 20.04.1/18.04.5, I will close this issue.
Feel free to open a new issue if any.
Thank you.
