### ISSUE TITLE
trusty packages disappeared

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/ROCm#109]
Hi - 
I just noticed that the trusty packages disappeared. 

```
$ sudo aptitude update
#...
Ign http://packages.amd.com trusty/main Translation-en_US
Ign http://packages.amd.com trusty/main Translation-en
Err http://packages.amd.com trusty/main amd64 Packages
  404  Not Found
Fetched 72 B in 3s (22 B/s)  
W: Failed to fetch http://packages.amd.com/rocm/apt/debian/dists/trusty/main/binary-amd64/Packages: 404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Couldn't rebuild package cache
```
and indeed, I can see only xenial binaries (tagged 1.5 !!) on the server mentioned above. will trusty not be supported anymore for 1.5 and upwards?

**Comment by jedwards-AMD** [comment]
The trusty code will not be provided for 1.5. I am working to update the repository with the 1.4 binaries in *.gz format.

**Comment by psteinb** [comment]
in other words, if I want to use 1.5, it's xenial then.

**Comment by jedwards-AMD** [comment]
I have uploaded the ROCm 1.4 archives to the following location: http://packages.amd.com/rocm/archive/

The 1.5.0 release is also include.

**Comment by psteinb** [comment]
ok, I ended up updating to xenial. rocm 1.5 is there but has it's issues, which I'll report separately.
