### ISSUE TITLE
What project/repo is the rocm-3.3.0/bin/clang-ocl script in, please?

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#1090]
I wish to submit a pull request for some changes to the clang-ocl script.

But I can't find it in the various github RadeonOpenCompute projects.

What repo do I have to fork to get a copy that I can modify and then submit a pull request?

Thanks!

**Comment by seesturm** [comment]
Repository seems to be https://github.com/RadeonOpenCompute/clang-ocl

**Comment by emerth** [comment]
> Repository seems to be https://github.com/RadeonOpenCompute/clang-ocl

Thanks!
