### ISSUE TITLE
lib/comrg/cmake documentation 

### ISSUE THREAD

**Issue by mrcsguy** [RadeonOpenCompute/ROCm#1093]
Is there documentation on what bc2h.cmake, DeviceLibs.cmake, and opencl_pch.cmake do?

**Comment by ROCmSupport** [comment]
Hi @mrcsguy 
Thanks for reaching out.
I hope this solves your question: [https://github.com/RadeonOpenCompute/ROCm-CompilerSupport](url)
Feel free to reach me for any other information too.
Thank you.

**Comment by ROCmSupport** [comment]
Request you to close this ticket if my response satisfies your need.
Thank you.

**Comment by ROCmSupport** [comment]
Am closing this considering that issue is resolved and no response from user.
Thank you.
