### ISSUE TITLE
Suspected optimizer error

### ISSUE THREAD

**Issue by gwoltman** [RadeonOpenCompute/ROCm#1096]
To enable using OMOD mul:2, I have these asm instructions near the start of my kernel.
    __asm("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 9, 1), 0");
    __asm("s_setreg_imm32_b32 hwreg(HW_REG_MODE, 4, 4), 7");
In looking at disassembly, the optimizer is happily moving floating point ops ahead of these instructions (presumably to hide memory load latency).  

Fortunately, my OMOD instructions are a little further down and I have not been affected by this potential problem.

**Comment by seesturm** [comment]
Did you try using "volatile" qualifier for asm statement?

**Comment by gwoltman** [comment]
I had forgotten that it is my responsibility to put volatile in to prevent this.  Thanks for jogging my memory.

Nonetheless, adding volatile after __asm does not affect the generated code.  Thus, the bug report is still valid.

**Comment by gwoltman** [comment]
BTW, I am using rocm 3.3

**Comment by gwoltman** [comment]
More discussion of this problem here:
https://github.com/RadeonOpenCompute/ROCm/issues/1098
