### ISSUE TITLE
Rocm 3.3 codegen bug

### ISSUE THREAD

**Issue by gwoltman** [RadeonOpenCompute/ROCm#1097]
Rocm generates code with incorrect constant.

Source code:  https://www.dropbox.com/s/dfo1ztg02vrth5y/rocmbug?dl=0
Disassembly:  https://www.dropbox.com/s/xbmynmrvpazos1d/rocmbug.bad?dl=0

Disassembly compiled with the WORKAROUND_ROCM_BUG defined:
https://www.dropbox.com/s/d2f8botaigandak/rocmbug.good?dl=0

In particular the constant S0 = 3.359992142876784201685022306409177725743E-3 in ksinpi is mangled.  In the good disassembly you'll see:
	s_mov_b32 s3, 0xbf6b866a
	s_mov_b32 s2, 0xbca875c
in the bad disassembly you'll see:
	s_mov_b32 s11, 0xbf341b2f
	s_mov_b32 s10, 0x769cf0e0

**Comment by b-sumner** [comment]
The source code does not compile as-is.  Could you provide the complete preprocessed source?

**Comment by preda** [comment]
I want to confirm that I can repro this. Here are detailed repro steps and ISA.

Repro:
1. check out gpuowl at: https://github.com/preda/gpuowl/tree/a39cc1a460bc6f2cac6ab4134088f220bfde4060
and build with scons or make
2. Good case:
```
mkdir good
./gpuowl -prp 95680699 -use TEST_KERNEL,ULTRA_TRIG -dump good
```
Bad case:
```
mkdir bad
./gpuowl -prp 95680699 -use TEST_KERNEL,ULTRA_TRIG,NO_KCOS_ROCM_BUG -dump bad
```

Open the files good/5M_0_gfx906.s and bad/5M_0_gfx906.s and extract the *testKernel* ISA (also attached).

Compare, and see that in the good case the FMA towards the end is done with
```
-0.003359992142876784 (0xbca875c, 0xbf6b866a)
```
while in the bad case it's done with
```
-0.00030679615757712823 (0x769cf0e0, 0xbf341b2f)
```

I did parse the ISA for a while trying to find a way that this constant replacement would be correct, but no matter what it does not work out.

Note that the testKernel provides a very nice isolated case, small and without any OMOD involvement.

[bad.txt](https://github.com/RadeonOpenCompute/ROCm/files/4596483/bad.txt)
[good.txt](https://github.com/RadeonOpenCompute/ROCm/files/4596484/good.txt)

I'll look into extracting a small standalone program if you'd find that useful, but in the meantime the above steps should allow repro and confirmation.

**Comment by b-sumner** [comment]
@preda we can focus on what is important to solving problems faster if we are given the minimum possible instance needed to produce it.  In this case, we don't need or want to pull, build, and run gpuowl.  If there is a minimal OpenCL C source file that we can compile and observe the problem, then that would be best for us.

**Comment by preda** [comment]
I put together a single-file reproducer, attached. Compile with
g++ main.cpp -lOpenCL
run with ./a.out
Observe difference in dump files good_xxx.s and bad_xxx.s

A bit unexpectedly, it does reproduce :)
Please let me know if repro works.
A quick repro check is
```
grep 0xbf6b866a *.s
```
[main.cpp.txt](https://github.com/RadeonOpenCompute/ROCm/files/4602823/main.cpp.txt)

**Comment by gwoltman** [comment]
@b-sumner:

Any progress on this.   Do you need more from us?

**Comment by preda** [comment]
@b-sumner please do provide feedback about what the bug/fix is. (a reference to the fix commit would be great)

**Comment by b-sumner** [comment]
The report is in the system.  I'm afraid I don't any other updates currently.

**Comment by b-sumner** [comment]
I don't see any comment here about the effects of the incorrect/unexpected constant.

The code is compiling with cl-fast-relaxed-math and there may have been some reassociation.  Do you see a problem when not using cl-fast-relaxed-math?

**Comment by preda** [comment]
I did a new review of the generated ISA today, and now I see that the generated code is valid. Indeed when -cl-fast-relaxed-math is used, two constants are multiplied together into a new constant. While this changes a tiny bit the result (and this is most likely the difference we were seeing in gpuowl), it's legal under relaxed math. Feel free to close the issue and sorry for the false alarm.

**Comment by b-sumner** [comment]
Thanks for checking.  I will close this.
