### ISSUE TITLE
rocprof & OpenCL

### ISSUE THREAD

**Issue by 3D-360** [RadeonOpenCompute/ROCm#1100]
We have ported a large project from CUDA to OpenCL, but CUDA is currently about 4x faster on equivalent hardware.  We want to tune the code for OpenCL.  
We used to tune with rcprof on ROCm 2.x, 
but we do not have an OpenCL profiling tool for ROCm 3.3.0.

rcprof used to report OCCUPANCY & register usage for OpenCL.
rocprof has replaced rcprof, and while it can profile ROCm, HIP, HSA, it does NOT profile OpenCL.

The problem is that there is no documentation about configuring rocprof to profile OpenCL.
We can get some diagnostics from rocprof on our code, but nothing on OpenCL. Here is our input.text file with several rocprof profiling features enabled:
```
# Perf counters group 1
pmc : Wavefronts 
# Perf counters group 2
pmc : VALUInsts SALUInsts SFetchInsts FlatVMemInsts LDSInsts
# Perf counters group 3
pmc : GDSInsts VALUUtilization FetchSize
# Perf counters group 4
pmc : WriteSize L2CacheHit
# supported range formats: "3:9", "3:", "3"
range: 1
gpu: 0 
kernel: MedianFilterKernel
```
What flags do we need to profile OpenCL with rocprof in ROCm 3.3.0?
Specifically, we want to monitor occupancy, shared memory & register usage.

**Comment by vvsteg** [comment]
From our experience (https://link.springer.com/chapter/10.1007/978-3-030-43229-4_28) if you use AMD GPUs then porting from CUDA to HIP is much more performance efficient than porting to OpenCL. It might be that porting to HIP would be a lesser and more productive effort that tuning the OpenCL version.

**Comment by 3D-360** [comment]
Thanks for the suggestion, but we have already ported to OpenCL.  

We have given up on rcprof, and we are now evaluating Radeon GPU Profiler.  It can be found at gpuopen.com

**Comment by eshcherb** [comment]
rocprof doesn't support OpenCL which should have internal profiler.

**Comment by EvgeniyPeshkov** [comment]
Hello @3D-360! Maybe I'm late to the party, but I would like to suggest [CLtracer](https://www.cltracer.com/). It supports any GPU on both Linux and Windows

**Comment by ROCmSupport** [comment]
Thanks @3D-360 
Hope you got answers from above.
Am closing this.
Request you to open a new ticket, if you find any.
