### ISSUE TITLE
__builtin_amdgcn_readlane float values?

### ISSUE THREAD

**Issue by WenbinHou** [RadeonOpenCompute/ROCm#1102]
Hi,

I would like to do `v_readlane_b32` on float values. `v_readlane_b32` doesn't really care about the type (as long as it's 32 bit), but `__builtin_amdgcn_readlane` does.

Is there something (or override) like:
```c++
float __builtin_amdgcn_readlane(float src, uint lane);

// Besides uint __builtin_amdgcn_readlane(uint src, uint lane);
```
Or let `llvm.amdgcn.readlane` work on float values?

<br>

I tried this (compile error):
```c++
extern float __llvm_amdgcn_readlane(float src, uint lane) __asm("llvm.amdgcn.readlane");
```

<br>

I also tried a bit with inlining LLVM `bitcast`, but without fortune :(

Thanks a lot!

**Comment by WenbinHou** [comment]
Never mind I'm working on OpenCL or HIP. Both are OK.

**Comment by preda** [comment]
you can use as_uint2(double).x, .y

**Comment by WenbinHou** [comment]
> you can use as_uint2(double).x, .y

Thanks! How about using HIP?

**Comment by arsenm** [comment]
You should never declare intrinsics using asm declarations. You can access this from the source with __builtin_amdgcn_readlane. You could define your own wrapper with as_float(__builtin_amdgcn_readlane(as_uint(x), y))
