### ISSUE TITLE
AMD DeepLearningExamples

### ISSUE THREAD

**Issue by papadako** [RadeonOpenCompute/ROCm#1105]
Hello everyone,

I think it would be rather helpful and important for the DL community and also for AMD and rocm to provide recipes and examples of models over different DL frameworks, including the performance of various AMD cards.

Basically what I have in my mind is something along the lines of what is currently available in https://github.com/NVIDIA/DeepLearningExamples/

Best Panagiotis

**Comment by ROCmSupport** [comment]
Thanks @papadako for reaching out.
I will check this for you and get back asap.
Thank you.

**Comment by ROCmSupport** [comment]
Got an update.
We are in process of making a good collection of models but it’s not at a stage to share. 
We will share once ready but it will take some time.
Please stay tuned.
Thank you.
