### ISSUE TITLE
SYCL program fails to link with ROCm 3.3.0 + Ubuntu 20.04

### ISSUE THREAD

**Issue by c0d3st0rm** [RadeonOpenCompute/ROCm#1108]
First of all, I understand that my setup is wholly unsupported by the ROCm stack (Ubuntu 20.04 + ROCm 3.3.0 including dkms + Intel's DPC++ LLVM compiler). I'm trying to run a sycl-based program using one of Intel's daily DPC++ releases (from https://github.com/intel/llvm/releases), and I can successfully run this application on both the host target (without OpenCL) and on the CPU (with OpenCL) using Intel's compute runtime. However, when it comes to executing it on a Vega 56, the program ends up failing to execute with

```
OpenCL API failed. OpenCL API returns: -17 (CL_LINK_PROGRAM_FAILURE) -17 (CL_LINK_PROGRAM_FAILURE)
```

How can I go about debugging this on the ROCm side of things? Is there a `DEBUG_ENABLE` sort of environment variable?

(the chosen device is a gfx900, so I'm pretty sure it's choosing the Vega as a target)

**Comment by preda** [comment]
You can try the debug environment variables described here:
https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/tree/master/lib/comgr#debug-the-code-object-manager

**Comment by c0d3st0rm** [comment]
```
amd_comgr_do_action:
	  ActionKind: AMD_COMGR_ACTION_LINK_RELOCATABLE_TO_EXECUTABLE
	     IsaName: amdgcn-amd-amdhsa--gfx900
	     Options: ""
	        Path: 
	    Language: AMD_COMGR_LANGUAGE_NONE
COMGR::InProcessDriver::Execute argv: lld "/tmp/comgr-3efff3/input/linked.bc.o" "-shared" "-o" "/tmp/comgr-3efff3/output/a.so"
	ReturnStatus: AMD_COMGR_STATUS_SUCCESS

<comgr output above, dpc++ output below>

OpenCL API failed. OpenCL API returns: -17 (CL_LINK_PROGRAM_FAILURE) -17 (CL_LINK_PROGRAM_FAILURE)
```

Looks like this might be a problem with dpc++ as all comgr calls succeed - could it be further down the pipeline, or is `a.so` the final output?

**Comment by c0d3st0rm** [comment]
So given sycl works fine with other OpenCL runtimes, I'm not sure what is the issue. How would I go about debugging this further?

**Comment by ROCmSupport** [comment]
Hi @c0d3st0rm 
Thanks for reaching out.
Request to try with the latest ROCm 4.0 and share an update asap.
Thank you.

**Comment by ROCmSupport** [comment]
I am closing this as there is no response for more than 2 months.
Feel free to open a new issue, if any.
Thank you.
