### ISSUE TITLE
CU Masking access

### ISSUE THREAD

**Issue by trinayan** [RadeonOpenCompute/ROCm#1110]
What is the intended way to use the CU Masking feature available in ROCM. I can see both the driver, Thunk and runtime have code for CU Masking. Yet is not clear how to use it. The calls to both the APIs in Thunk and ROCR require some sort of queue to pass to it. Its not clear how this queue is created and how to use it from something like HIP . Any userspace example that demonstrates this will be really helpful.Thanks

**Comment by Rmalavally** [comment]
Thank you for your feedback. Have you looked on the documentation website at http://rocmdocs.amd.com? 

Please let us know if you are unable to find the information you need.

AMD ROCm Documentation Team

**Comment by trinayan** [comment]
I have gone through the documentation. I cannot find how to do this in the current docs

**Comment by Rmalavally** [comment]
Thank you for confirming. We have noted your feedback. Please check back, as the documentation is updated on a continuous basis. 

AMD ROCm Documentation Team

**Comment by jlgreathouse** [comment]
This feature is available in HIP as of ROCm 3.6 using the API `hipExtStreamCreateWithCUMask()`. See [this header](https://github.com/ROCm-Developer-Tools/HIP/blob/roc-3.6.x/include/hip/hcc_detail/hip_runtime_api.h#L852) for documentation. We do not plan on adding a similar feature to OpenCL at this time.
