### ISSUE TITLE
Upcoming VII PRO support

### ISSUE THREAD

**Issue by notokcomputerbadcomputer** [RadeonOpenCompute/ROCm#1111]
As VII PRO is launching soon, will it be supported on day one in ROCm? And including all additional features over regular VII?

**Comment by omerferhatt** [comment]
#833 same question asked on Navi based cards. Still waiting.

**Comment by notokcomputerbadcomputer** [comment]
VII PRO has ROCm in product specification sheet, NAVI products don't afaik.

Question is essentially about if these devs have it already and are on track to meet the stated promise, unlike meeting the community demand.

**Comment by preda** [comment]
> As VII PRO is launching soon, will it be supported on day one in ROCm? And including all additional features over regular VII?

What are the additional features over Radeon VII?

**Comment by valeriob01** [comment]
> > As VII PRO is launching soon, will it be supported on day one in ROCm? And including all additional features over regular VII?
> 
> What are the additional features over Radeon VII?

It supports PCIe 4.0, I don't know more.

**Comment by notokcomputerbadcomputer** [comment]
One interesting to me is card to card Infinity Fabric.
ECC memory is a nice to have.
PCIe 4.0, of course.

There is some more in the spec sheet, application/industry specific stuff.

**Comment by ROCmSupport** [comment]
Hi @notokcomputerbadcomputer 
Thanks for reaching out.
As of now, looks like there is no plan to add R7 pro into ROCm support.
Anyway I will try to get the latest information on this and update you asap.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @notokcomputerbadcomputer 
We are supporting Radeon 7 Pro officially for couple of months.
You can try the same with the latest ROCm 4.0 or 4.1
I will make sure that documentation is updated accordingly for ROCm 4.1
Thank you.
