### ISSUE TITLE
Rocm 3.3 reports no image support

### ISSUE THREAD

**Issue by Aceler** [RadeonOpenCompute/ROCm#1114]
Ubuntu 20.04
AMD RX560
rocm 3.3 partially installed (rock-dkms, rocm-opencl, rocm-opencl-dev)

```
$ /opt/rocm-3.3.0/opencl/bin/x86_64/clinfo | grep -i image
  Image support:				 No

```

Previous versions of rocm reported image support, thus Darktable and other graphic-oriented software worked properly, now they are not.

**Comment by justxi** [comment]
I think you have to install the additional package "hsa-ext-rocr-dev".

**Comment by Aceler** [comment]
Yes, that fixed things. 

Please add to documentation.
