### ISSUE TITLE
ROCm support for RX5700xt？

### ISSUE THREAD

**Issue by sqlmap3** [RadeonOpenCompute/ROCm#1115]

**Comment by panospolychronis** [comment]
Not yet. I hope ROCm 3.4 will support Navi10. Check here: https://github.com/RadeonOpenCompute/ROCm/issues/887

**Comment by sqlmap3** [comment]
> Not yet. I hope ROCm 3.4 will support Navi10. Check here: #887

Do you have any more precise information?

**Comment by panospolychronis** [comment]
If you check the code there are some lines referring to gfx1010 (which is Navi10) but there is no support yet. There are no other informations about it.

**Comment by sqlmap3** [comment]
ROCm 3.4 maybe support

**Comment by x32349501** [comment]
Are you sure? I think it's a trend!

**Comment by ridvan5005** [comment]
I guess AMD doesn't want to invest the money he earns in the software. This is how I interpret that it does not offer Navi 10 support in the new update. Because the Navi 10 is a powerful chip and doesn't support it.

**Comment by panospolychronis** [comment]
ROCm 3.5 released without Navi support... pitty...  :(

**Comment by soutzis** [comment]
I doubt we should expect ant Navi10 support anytime before late 2021 - early 2022. I had to buy an Nvidia card instead

**Comment by ekondis** [comment]
I have to report that I'm experimenting with an RX-5500 (gfx1012) card, on rocm 3.5.1 and it seems to work, not only for OpenCL apps but for HIP as well.

**Comment by sqlmap3** [comment]
Elias <notifications@github.com> 于2020年7月13日周一 上午4:56写道：

**Comment by jli113** [comment]
I deeply regret buying this RX5700XT card.

**Comment by soutzis** [comment]
> 
> 
> I deeply regret buying this RX5700XT card.

Returning it and getting an rtx2070 super was the best decision I ever made.

**Comment by xuhuisheng** [comment]
Here are more disscusions about RX 5700XT supporing.
https://github.com/RadeonOpenCompute/ROCm/issues/887

**Comment by ROCmSupport** [comment]
Hi All,
As I mentioned in other threads, we will come up with the support of Navi cards soon, but I can not comment on specific series of cards right now.
I hope you understand my point.
We request you to wait for few more days for official support and keep watching our documentation.
Thank you.
