### ISSUE TITLE
clinfo crashes computer ubuntu 20.04

### ISSUE THREAD

**Issue by Goddard** [RadeonOpenCompute/ROCm#1117]
When running clinfo it crashes the computer, or at the very least visually crashes video.

This is on a 3 agent system.

Threadripper 1950x
RX 580
RX 580

**Comment by notokcomputerbadcomputer** [comment]
You could always try a fresh install WITH recommended distribution AND recommended kernel. You can find those in documentation.

**Comment by Rmalavally** [comment]
Thank you for reaching out. You can find AMD ROCm documentation at:
http://rocmdocs.amd.com

If you are unable to find the instructions you need, please let us know.

AMD ROCm Documentation Team

**Comment by Goddard** [comment]
This repository is for developers correct?
I am merely letting developers know of a bug on a platform I expect will be supported in the future.

Everything works fine when you have 1 GPU, but if you have 2 it crashes video.

**Comment by Rmalavally** [comment]
Thank you for letting the community know. You are right, Ubuntu 20.04 is not supported as yet.

**Comment by ableeker** [comment]
Not sure if this is the same case, but clinfo will crash after installing ROCm. By crash I mean it will cause a 'Segmentation fault (core dump)'. I have to install libtinfo5, or libncurses5 before it will work. Anyway, after some trial and error I have rocm-dev working on my computer with Ubuntu 20.04. Well, the OpenCL part anyway, I haven't tried other parts.

**Comment by Goddard** [comment]
Thanks for letting me know.  Pretty sure I had both of these installed when attempting to get it going, but I can give it a go again.  When I attempted to run things other then clinfo it totally locked up video.  Tensorflow did not want to work at all.

**Comment by alfabuster** [comment]
Version 3.5 for Ubuntu 20.04 change nothing. Same errors like for 3.3...

**Comment by notokcomputerbadcomputer** [comment]
```
The AMD ROCm v3.5.x platform is designed to support the following operating systems:

Ubuntu 16.04.6(Kernel 4.15) and 18.04.4(Kernel 5.3)
CentOS 7.7 (Kernel 3.10-1062) and RHEL 7.8(Kernel 3.10.0-1127)(Using devtoolset-7 runtime support)
SLES 15 SP1
CentOS and RHEL 8.1(Kernel 4.18.0-147)
```

**Comment by alfabuster** [comment]
Yes, I hope 4.0 release will fix Ubuntu 20.04...

**Comment by ROCmSupport** [comment]
Hi @Goddard 
Thanks for reaching us.
I am closing this issue as the latest ROCm 4.0 supports Ubuntu 20.04.x and hope this problem is gone with ROCm 4.0+Ubuntu 20.04.x.
Request you to try the same.
Request you to open a new issue if any, so that we can chase down the problem.
Thank you.

**Comment by ROCmSupport** [comment]
Thanks @Goddard and @alfabuster
We are officially supporting the latest ROCm 20.04 and request you to try the same now.
Ubuntu 20.04 + ROCm 4.0 works perfect and I recommend you to wait you wish to try the latest ROCm 4.1, which is mostly a week away.
Thank you.
