### ISSUE TITLE
ROCm 1.5 issues - Module API sample not working and hipify not available

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/ROCm#112]
Hi,
I tried samples from /opt/rocm/hip/samples and found an issue. I'm reporting here since this is the top level repository.

> ~/dev/hip_samples/0_Intro/module_api$ ./defaultDriver.hip.out 
Memory access fault by GPU node-1 on address (nil). Reason: Page not present or supervisor privilege.
Aborted (core dumped)

Is this expected?

>~/dev/cs344/Problem Sets/Problem Set 1$ hipconvertinplace.sh 
/opt/rocm/bin/hipconvertinplace.sh: line 24: /opt/rocm/bin/hipify-clang: No such file or directory

Is hipify-clang not part of the release? Do I need to build it separately?

**Comment by adityaatluri** [comment]
This is specific to HIP, I recommend moving this issue to 
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/
