### ISSUE TITLE
Can't find libmcwamp.so.3

### ISSUE THREAD

**Issue by codecor-cn** [RadeonOpenCompute/ROCm#1126]
use tensorflow-rocm2.1.1
centos 8.1  rocm3.5
`
import tensorflow as tf
ImportError: libmcwamp.so.3: cannot open shared object file: No such file or directory
`

**Comment by thesleort** [comment]
I was using OpenCL yesterday with ROCm 3.3 and upgraded today to ROCm 3.5. For me I was missing libOpenCL.so. Did a complete reinstall of ROCm 3.5 (removing it and then installing it again) and now everything works again.

My system is Ubuntu 20.04
Threadripper 1900x and Vega 56

**Comment by dagrim** [comment]
Same thing here : 
- using Ubuntu 18.04 bionic
- ROCm 3.5 (all packages installed)
- python 3.8 + tensorflow-rocm

Error upon importing tensorflow : 
ImportError: libmcwamp.so.3: cannot open shared object file: No such file or directory

The files libmcwamp.so.3 and libmcwamp.so don't exist in /opt/rocm (neither anywhere else on the system).

Am I missing a package ?

**Comment by H-Ribeiro** [comment]
> I was using OpenCL yesterday with ROCm 3.3 and upgraded today to ROCm 3.5. For me I was missing libOpenCL.so. Did a complete reinstall of ROCm 3.5 (removing it and then installing it again) and now everything works again.
> 
> My system is Ubuntu 20.04
> Threadripper 1900x and Vega 56

Hi, I have a similar setup.
Are you able to install and use ROCm 3.5 without any special configurations or pre-requirements?

Thanks

**Comment by Reinercas** [comment]
Hi, I have the exact same problem:
`ImportError: libmcwamp.so.3: cannot open shared object file: No such file or directory`

Using:
Ubuntu 20.04
rocm 3.5
tensorflow-rocm 2.2.0rc5

**Comment by scchan** [comment]
That is due to a long overdue change to HIP.  With ROCm 3.5, we are moving to the new HIP implementation which comes with a new runtime.  You'll probably have to update to a newer Tensorflow binary built by ROCm 3.5.  Perhaps @sunway513 could provide some information on that.

**Comment by sunway513** [comment]
Yes, we are working on the whl packages which are build with ROCm3.5 user bit packages. Those will be updated very soon.

**Comment by sunway513** [comment]
Hi @codecor-cn  , we've released the tensorflow-rocm packages built with ROCm3.5 environment.
For details please refer to the following document:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md

**Comment by codecor-cn** [comment]
> Hi @codecor-cn , we've released the tensorflow-rocm packages built with ROCm3.5 environment.
> For details please refer to the following document:
> https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md

when i upgraded to this version, problem libmcwamp.so  not found has gone away, but

**Comment by sunway513** [comment]
@codecor-cn please try to install rocsparse/hipsparse library:
`sudo apt update && sudo apt install rocsparse hipsparse`
You can also try the integrated docker containers for a faster deployment:
https://hub.docker.com/r/rocm/tensorflow

**Comment by codecor-cn** [comment]
> @codecor-cn please try to install rocsparse/hipsparse library:
> `sudo apt update && sudo apt install rocsparse hipsparse`
> You can also try the integrated docker containers for a faster deployment:
> https://hub.docker.com/r/rocm/tensorflow

i use centos 8 not ubuntu but you can still use yum install rocsparse hipsparse.
then another error appeared  "ImportError: librccl.so.1: cannot open shared object file: No such file or directory"
1. need install rccl
git clone git@github.com:ROCmSoftwarePlatform/rccl.git
./install -i
2. not found librocblas.so libMIOpen.so librocfft.so librocrand.so
yum install rocm-libs miopen-hip

it's done

**Comment by codecor-cn** [comment]
thanks every one!
