### ISSUE TITLE
Please provide binaries symlinks in normal PATH

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1128]
Please provide versioned symlinks to `/opt/rocm-V/bin/X` in `/usr/bin/X-V` owned by packages, and also provide a relatrive symlink from `/usr/bin/X` to `/usr/bin/X-V`  managed using `update-alternatives(1)` ( https://manpages.debian.org/buster/dpkg/update-alternatives.1.en.html ) mechanism. https://wiki.debian.org/DebianAlternatives 

It is a real pain to use rocm right now.

**Comment by icarus-sparry** [comment]
We are looking into what is involved with doing this (i.e. no commitment) for 3.7.

**Comment by ROCmSupport** [comment]
Hi @baryluk 
Most likely it will be fixed in 4.3.
I will keep you posted.
Thank you.

**Comment by baryluk** [comment]
No change in ROCm 4.3. Same.

**Comment by ROCmSupport** [comment]
Hi @baryluk 
As we have done many changes in the latest builds w.r.to packaging, can you please verify with 5.0(which is going to be in next few days) and update. Thank you.
