### ISSUE TITLE
`/etc/OpenCL/vendors/amdocl64.icd` doesn't use absolute paths and/or not in a default LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1131]
Something does install `/etc/OpenCL/vendors/amdocl64.icd` but it isn't in any package, so I suspect this is put there by some post-install script, which feels unnecessary.

Also it simply doesn't work because it is only using the name of the .so file without the path:

```
$ cat /etc/OpenCL/vendors/amdocl64.icd 
libamdocl64.so
$
```

So by default `ocl-icd-libopencl1` (providing `/usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0`)  will not be able to find it and simply ignore it.

Tested with `clinfo` version 2.2.18.04.06-1 (https://github.com/Oblomov/clinfo) and `ocl-icd-libopencl1` version 2.2.12-4 ( https://forge.imag.fr/projects/ocl-icd/ ) generic loader. 

```
$ clinfo | egrep -i 'Parallel|HSA'
$
```

Putting absolute path into the icd defintion:

```
$ cat /etc/OpenCL/vendors/amdocl64.icd
/opt/rocm-3.5.0/opencl/lib/libamdocl64.so
$
```

solves it:

```
$ clinfo | egrep -i 'Parallel|HSA'
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Name                                   AMD Accelerated Parallel Processing
  Driver Version                                  3137.0 (HSA1.1,LC)
$
```

**Comment by ableeker** [comment]
I'm by no means an expert, but I think this is the .icd-file is correct, even though it only contains the filename, and not the full path.

`According to OpenCL specifications from Khronos, the ICD Loader looks for files into /etc/OpenCL/vendors/ directory and, for each file whose name ends with .icd, the ICD Loader loads with dlopen(3) the shared library whose name is on the first line of the .icd file.`

`Shared library name in ".icd" files can have its path, or it can be a plain filename. In the latter case, the ICD shared library will be looked for into the standard dynamic loader paths.`

Actually I don't have installed any other OpenCL packages, only "rocm-dev". I haven't installed ocl-libopencl1, or clinfo, I think they're already included. However if I use clinfo, I get this:

`
Platform Name                                   AMD Accelerated Parallel Processing
Platform Name                                   AMD Accelerated Parallel Processing
Driver Version                                  3137.0 (HSA1.1,LC)
Platform Name                                 AMD Accelerated Parallel Processing
Platform Name                                 AMD Accelerated Parallel Processing
Platform Name                                 AMD Accelerated Parallel Processing
`

**Comment by Aceler** [comment]
It seems that the right way to fix that is to add a file to /etc/ld.so.conf.d/ which will contain a path to /opt/rocm-VERSION/opencl/lib/.

And this file should be in rocm-opencl package.

**Comment by Aceler** [comment]
> `libOpenCL.so.1 (libc6,x86-64) => /opt/rocm/opencl/lib/libOpenCL.so.1`
> `libOpenCL.so.1 (libc6,x86-64) => /opt/rocm/lib/libOpenCL.so.1`
> `libOpenCL.so (libc6,x86-64) => /opt/rocm/opencl/lib/libOpenCL.so`
> `libOpenCL.so (libc6,x86-64) => /opt/rocm/lib/libOpenCL.so`
 
BTW, you have rocm installed in /opt/rocm, while baryluk and me have rocm installed in /opt/rocm-3.5.0

**Comment by ableeker** [comment]
This is about ROCm 3.5.0 (version 3137.0), the ROCm file structure for 3.5.0 has been changed to make the files available.

For 3.3.0 I have added a file libopencl.conf to /etc/ld.so.conf.d containing the following path:

`/opt/rocm/opencl/lib/x86_64`

Then I added the path with ldconfig.

Oddly enough some programs still were able to use OpenCL even without this path.

Since 3.3, if you install rocm-dkms, or rocm-dev, it will install ROCm to folder /opt/rocm-3.x.0, but it will also create a symlink /opt/rocm pointing to this folder.

**Comment by baryluk** [comment]
I am just asking to do this so it is easier to install and use ROCm, needing to modify `LD_LIBRARY_PATH` and `PATH` for every user or even modifying it system wide is a pain.

With all paths encoded properly one would not need to mess with this, and it will work out of the box after installing deb packages.

Multiple versions of ROCm installed at the same time can be handled in Debian and Ubuntu using `update-alternatives(1)` mechanism, which will still make it all work out of the box nicely.


In my installation there are hsa files in `/etc/ld.so.conf.d/`, but non of them has `/opt/rocm-3.5.0/opencl/lib/` path, so ld can't actually find it:

```
$ ldconfig -p | grep -i OpenCL
	libOpenCL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libOpenCL.so.1
	libOpenCL.so.1 (libc6) => /lib/i386-linux-gnu/libOpenCL.so.1
	libOpenCL.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libOpenCL.so
	libMesaOpenCL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libMesaOpenCL.so.1
	libMesaOpenCL.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libMesaOpenCL.so
	libBullet3OpenCL_clew.so.2.88 (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew.so.2.88
	libBullet3OpenCL_clew.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew.so
	libBullet3OpenCL_clew-float64.so.2.88 (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew-float64.so.2.88
	libBullet3OpenCL_clew-float64.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew-float64.so
$
```



Adding it and reruning ldconfig makes it work;

```
root$ echo "/opt/rocm-3.5.0/hsa/lib" > /etc/ld.so.conf.d/hsa-rocr-dev.conf
root$ ldconfig
root$
$ ldconfig -p | grep OpenCL
	libamdocl64.so (libc6,x86-64) => /opt/rocm-3.5.0/opencl/lib/libamdocl64.so
	libOpenCL.so.1 (libc6,x86-64) => /opt/rocm-3.5.0/opencl/lib/libOpenCL.so.1
	libOpenCL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libOpenCL.so.1
	libOpenCL.so.1 (libc6) => /lib/i386-linux-gnu/libOpenCL.so.1
	libOpenCL.so (libc6,x86-64) => /opt/rocm-3.5.0/opencl/lib/libOpenCL.so
	libOpenCL.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libOpenCL.so
	libMesaOpenCL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libMesaOpenCL.so.1
	libMesaOpenCL.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libMesaOpenCL.so
	libBullet3OpenCL_clew.so.2.88 (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew.so.2.88
	libBullet3OpenCL_clew.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew.so
	libBullet3OpenCL_clew-float64.so.2.88 (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew-float64.so.2.88
	libBullet3OpenCL_clew-float64.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libBullet3OpenCL_clew-float64.so
```


So, my bug is still valid icd file shoudl either use absolute path (it will work with `dlopen`, and I tested it), or in default LD_LIBRARY_PATH (or in `ld.so.conf.d` directory). But in my installation it isn't.

```
$ dpkg -l | egrep 'rocm|hsa' | grep '^ii' | awk '{print $2, $3; }'
comgr 1.6.0.143-rocm-rel-3.5-30-e24e8c1
hsa-ext-rocr-dev 1.1.30500.0-rocm-rel-3.5-30-def83d8
hsa-rocr-dev 1.1.30500.0-rocm-rel-3.5-30-def83d8
hsakmt-roct 1.0.9-347-gd4b224f
rocm-clang-ocl 0.5.0.51-rocm-rel-3.5-30-74b3b81
rocm-opencl 2.0.20191
rocm-opencl-dev 2.0.20191
rocm-utils 3.5.0-30
rocminfo 1.30500.0
```

PS. The `clinfo` in rocm is a different clinfo that I use, but I use Oblomov's clinfo, because it is in my PATH by default, I know it works fine with Nvidia, Intel and Mesa Clover and pocl OpenCL implementations, and I don't want to loose compatibility. And I didn't want to use clinfo bundled with rocm, because I would suspect it has own hardcoded path and/or uses own location to figure the location of the rocm OpenCL loader, which I shouldn't too use.

**Comment by Aceler** [comment]
Yes, the bug is still a bug. It is just there are several ways to workaround it, and there are certain conditions where it is not appear.

**Comment by baryluk** [comment]
I think one of the solutions (other than using absolute path, or putting rocm in `/usr/local` instead of `/opt`), is to make `rocm-opencl` ship with proper `/etc/ld.so.conf.d/rocm-opencl.conf` file, and call `ldcondig` in post-inst script.

**Comment by ableeker** [comment]
ROCm 3.5.0 creates /etc/ld.so.conf.d/x86_64-libhsakmt.conf, that points to /opt/rocm/lib. This folder contains libOpenCL.so, libOpenCL.so.1, and libOpenCL.so.1.2. These three files are all symlinks to file /opt/rocm/opencl/lib/libOpenCL.so.1.2, which is a real file.

When I check ldconfig, it can see libOpenCL.so.1, which I guess should make OpenCL work. However, I prefer to add libopencl.conf, containing path /opt/rocm/opencl/lib, in order to add libOpenCL.so to the library path as well. I agree that the installation command should have been done this.

**Comment by baryluk** [comment]
Still broken in ROCm 3.8.0

**Comment by baryluk** [comment]
Still broken in ROCm 3.9.0.

I believe I found the issue.

the `postinst` script of the `rocm-opencl3.9.0` uses wrong paths:

```bash
do_ldconfig() {
  if [ -e "/opt/rocm/opencl" ] ; then
    echo /opt/rocm/opencl/lib > /etc/ld.so.conf.d/x86_64-rocm-opencl.conf && ldconfig
  fi
  mkdir -p /etc/OpenCL/vendors && (echo libamdocl64.so > /etc/OpenCL/vendors/amdocl64_30900.icd)
}

INSTALL_PATH=/opt/rocm-3.9.0/opencl
ROCM_LIBPATH=/opt/rocm-3.9.0/lib

case "$1" in
  abort-deconfigure|abort-remove|abort-upgrade)
    echo "$1"
  ;;
  configure)
    mkdir -p ${ROCM_LIBPATH}
    ln -s -f -r ${INSTALL_PATH}/lib/libOpenCL.so ${ROCM_LIBPATH}/libOpenCL.so
    ln -s -f -r ${INSTALL_PATH}/lib/libOpenCL.so.1 ${ROCM_LIBPATH}/libOpenCL.so.1
    ln -s -f -r ${INSTALL_PATH}/lib/libOpenCL.so.1.2 ${ROCM_LIBPATH}/libOpenCL.so.1.2
    do_ldconfig
  ;;

```


As you can see the `do_ldconfig` function uses wrong paths.

**Comment by ROCmSupport** [comment]
Thanks @baryluk for reaching out.
I will check this for you.

**Comment by ROCmSupport** [comment]
Got an update:
Issue is fixed in 4.3 internal code and it will be available soon to public.
Request you to verify with ROCm 4.3 and close accordingly.
Thank you.

**Comment by ROCmSupport** [comment]
Verified with ROCm 4.3 and issue is fixed and no more observed.

taccuser@taccuser-SYS-4028GR-TR2:~$ /opt/rocm/opencl/bin/clinfo | egrep -i 'Parallel|HSA'
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Name:                                 AMD Accelerated Parallel Processing
  Driver version:                                3305.0 (HSA1.1,LC)
  Driver version:                                3305.0 (HSA1.1,LC)

**Comment by baryluk** [comment]
Still broken in ROCm 4.3.

```
root@debian:~# dpkg -l | egrep 'rocm|hsa|comgr'
ii  comgr                                                       2.1.0.40300-52                         amd64        Library to provide support functions
ii  hsa-rocr-dev                                                1.3.0.40300-52                         amd64        AMD Heterogeneous System Architecture HSA - Linux HSA Runtime for Boltzmann (ROCm) platforms
ii  hsakmt-roct                                                 20210520.3.071986.40300-52             amd64        HSAKMT library for AMD KFD support
ii  rocm-opencl                                                 2.0.0.40300-52                         amd64        OpenCL: Open Computing Language on ROCclr
ii  rocminfo                                                    1.0.0.40300-52                         amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool
root@debian:~# 
```
