### ISSUE TITLE
Please move "AMD ROCm Version History" out of the Installation Instruction guide

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1132]
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

has this enormous "AMD ROCm Version History" section which shouldn't be there.

Similarly "Uninstall instructions", "AMD ROCm MultiVersion" and "Getting the ROCm Source Code" should be moved out of this document.

**Comment by jlgreathouse** [comment]
We have moved the version history section into the per-version release notes, but I believe the other sections make sense to leave in the installation guide. Thanks for the feedback!
