### ISSUE TITLE
Installation Guide does reference packages that doesn't exist

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1136]
There are references to `hip` and `hip3.5.0`, such thing doesn't exist.

My guess there is `hip-base` ?

**Comment by ROCmSupport** [comment]
Hi @baryluk 
Thanks for reaching us.
Can you please elaborate your query.

**Comment by baryluk** [comment]
I don't know, that was 6 months ago. There were some weird tables and stuff on the https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

**Comment by Rmalavally** [comment]
You are correct, @baryluk. The ROCm documentation is evolving, and we are constantly updating the content and website. We recommend that you review the documentation/webpages periodically for corrected and updated ROCm content.

 As always, we welcome your constructive and timely feedback.

**Comment by baryluk** [comment]
Going to close it. If I find this issue again, or remember where it was and it is still there, I will reopen or something

**Comment by ROCmSupport** [comment]
Thanks @baryluk for your update.
Request you to file a new ticket anytime in future.
Thank you.
