### ISSUE TITLE
hip-samples provides *.hipref.* files without explaining them

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1138]
I believe `/opt/rocm-3.5.0/hip/samples/0_Intro/square/square.hipref.cpp` is not actually used for anything. And shipping it is confusing. Please remove it.

Even better, make the `0_Intro/square`, be separated into two projects. First one, not using CUDA, but native manually written HIP code and just uses `hipcc`, a second one, that uses CUDA and `hipify+hcc`, and `nvcc`.

**Comment by ROCmSupport** [comment]
Hi @baryluk for reaching out.
square.hipref.cpp is just a reference file and it does nothing.
However I will check with HIP team and get back to you on this.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @baryluk 
Got an update on this:
We can not remove it, as the file is for comparing to show that after you hipify you would get code similar to the hipref.cpp.
