### ISSUE TITLE
hip-samples square example links readme to non-existing page

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1139]
`/opt/rocm-3.5.0/hip/samples/0_Intro/square/README.md`

links to http://gpuopen.com/hip-to-be-squared-an-introductory-hip-tutorial

which doesn't exist.

So this example is impossible to use or understand really.

This is the first example and sample, and already can't progress further, because it doesn't work.

Please include all the relevant information in the README.md without external dependencies, or in the source code comments.

**Comment by ROCmSupport** [comment]
Thanks @baryluk for reaching us out.
I am able to reproduce this issue.
I will work with HIP developer and update the status asap.
Thank you.

**Comment by ROCmSupport** [comment]
Latest update on this:
Changes are ready and will be pushed very soon.
Thank you.

**Comment by ROCmSupport** [comment]
Latest update:
Changes will be part of ROCm 4.3.
Thank you.

**Comment by ROCmSupport** [comment]
Verified this issue with ROCm 4.3(4.3-52) and issue is no more observed.
