### ISSUE TITLE
OpenCL image support on ROCm 1.5 ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#114]
Congrats on the 1.5 release. May I ask if opencl images are supported?

**Comment by gstoner** [comment]
Yes, images are supported now,



On May 3, 2017, at 3:09 PM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


Congrats on the 1.5 release. May I ask if opencl images are supported?

**Comment by boxerab** [comment]
Thanks. I have an OpenCL project that uses the APP SDK. It is built with CMake : cmake has a script
to find the APP SDK install.  Will this work out of the box on Ubuntu 16 with ROCm 1.5 ?

**Comment by boxerab** [comment]
Thanks!
