### ISSUE TITLE
Any binary version planned for Linux OSs?

### ISSUE THREAD

**Issue by xcom169** [RadeonOpenCompute/ROCm#1142]
Hello All!

I know it's much bigger than a simple opencl runtime, but it's crazy it needs 40 GB Ram, and 150 GB HDD to build ROCm. It's very difficult to build the package on a normal PC. 
Can't we just install the binary files ?

**Comment by ableeker** [comment]
I do believe we can. It depends on what you want to do, of course, but I'm using ROCm, but so far I haven't yet felt the need to build ROCm. If you just need the OpenCL part of ROCm, you can install rocm-opencl, or rocm-opencl-dev. If you need more than that, you can install rocm-dkms, or rocm-dev. These are all binary packages.

Won't that do the trick? Do you need to build ROCm from source?

**Comment by xcom169** [comment]
I installed ROCm from rocm-opencl-runtime AUR, but it needed the llvm-amdgpu which is huge to build. 

Do you know any other package for Arch/Manjaro Linux which only contains the opencl runtime binary?

**Comment by xcom169** [comment]
It's a good idea. I think it's possible to convert the .DEB package to Arch Linux (AUR).
I'll consult an AUR package maintainer about this idea. 
Hopefully it can be done easily.
