### ISSUE TITLE
rocm-smi

### ISSUE THREAD

**Issue by florekem** [RadeonOpenCompute/ROCm#1144]
Can't find it in my system, has it been removed? I used it for controlling gpu fan. Is there another way to do it now?

**Comment by ableeker** [comment]
If you install rocm-dkms, or rocm-dev, it's definitely included. Otherwise, I see there's a package called rocm-smi-xxx.deb

**Comment by preda** [comment]
rocm-smi is basically just glorified a python script, that you can check out from:
https://github.com/RadeonOpenCompute/ROC-smi
