### ISSUE TITLE
3.5 release:  OpenCL include and lib folder removed from /opt/rocm, only found in /opt/rocm-3.5.0 folder

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#1147]
On Ubuntu 16.04

It would be helpful to have a stable `/opt/rocm` folder symlinked to latest release. I have a cmake search script for finding rocm opencl, but this is going to break with each new release.

**Comment by bd4** [comment]
Related to #1160 . A workaround seems to be forcing re-install of packages - find which ones are still installed in the old directory with `dpkg -S /opt/rocm-OLVERSION`, then run `apt install --reinstall PKG1 PKG2....`.

**Comment by ROCmSupport** [comment]
Thanks @boxerab and @bd4.
I recommend to try with the latest ROCm 4.0.
Thank you.
