### ISSUE TITLE
Unable to open /dev/kfd read-write: Cannot allocate memory

### ISSUE THREAD

**Issue by TolyProg** [RadeonOpenCompute/ROCm#1148]
My OS is Arch Linux.
My PC is Xeon E5-2689, 32GB of RAM and RX570 8GB.

> $ sudo rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
tolyprog is member of render group
hsa api call failure at: /home/tolyprog/.cache/yay/rocminfo/src/rocminfo-rocm-3.5.0/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

**Comment by kjuanman** [comment]
same issue, I confirm:
$ sudo rocminfo 
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
juan is member of render group
hsa api call failure at: /home/juan/.cache/pacaur/rocminfo/src/rocminfo-rocm-3.5.0/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

My OS is Manjaro, archlinux based
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.0.3
Codename:       Lysia

**Comment by geocarvalho** [comment]
Same issue on my ubuntu 20.04

```
$ rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
george is member of render group
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by xuhuisheng** [comment]
dmesg|grep kfd,
check whether kdf reject because not supporting PCIe Atomics

**Comment by RedScientistOne** [comment]
rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
red is member of video group
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.


> `dmesg|grep kfd`
> check whether kdf reject because not supporting PCIe Atomics

dmesg|grep kfd
[   16.149772] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[   16.151683] kfd kfd: amdgpu: error getting iommu info. is the iommu enabled?
[   16.151688] kfd kfd: amdgpu: Error initializing iommuv2
[   16.151775] kfd kfd: amdgpu: device 1002:130d NOT added due to errors
[   16.699618] kfd kfd: amdgpu: HAINAN  not supported in kfd

**Comment by xuhuisheng** [comment]
kfd not successful adde GPU. but donot know what the HAINAN means.
```
[ 16.151683] kfd kfd: amdgpu: error getting iommu info. is the iommu enabled?
[ 16.151688] kfd kfd: amdgpu: Error initializing iommuv2
[ 16.151775] kfd kfd: amdgpu: device 1002:130d NOT added due to errors
[ 16.699618] kfd kfd: amdgpu: HAINAN not supported in kfd
```

**Comment by geocarvalho** [comment]
```
$ dmesg | grep kfd
[    4.528825] kfd kfd: amdgpu: TOPAZ  not supported in kfd
```

**Comment by xuhuisheng** [comment]
```
$ dmesg|grep kfd
[    5.143681] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    5.148990] kfd kfd: amdgpu: added device 1002:67df
```

**Comment by gfwp** [comment]
> ```
> $ dmesg|grep kfd
> [    5.143681] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
> [    5.148990] kfd kfd: amdgpu: added device 1002:67df
> ```

For me

root@lonovo:/home/gfwp# dmesg | grep kfd
[    1.884198] kfd kfd: Allocated 3969056 bytes on gart
[    1.885377] kfd kfd: added device 1002:15d8


On up to date Debian Bullseye and rocm 3.80

**Comment by Mhowser** [comment]
```
dmesg | grep kfd
[    2.803287] kfd kfd: skipped device 1002:67df, PCI rejects atomics
```
Anything I can do about this?

**Comment by xuhuisheng** [comment]
@Mhowser 
gfx803 cannot run without PCIe atomics. please refer here https://github.com/radeonopencompute/ROCm#supported-cpus

**Comment by Mhowser** [comment]
I have the AMD Athlon x4 880k CPU and the AMD RX580 GPU, so due to my CPU not having PCIe 3.0 capability I cannot use ROCm, correct?

**Comment by xuhuisheng** [comment]
Cannot run ROCm with RX580 without PCIe atomics.
Can use Vega64, Radeon VII, they don't need PCIe atomics.

**Comment by ROCmSupport** [comment]
Yes @Mhowser 
gfx8 needs PCIe atomics support.
gfx9 devices doe not require PCIe atomics. 
As complete support of ROCm works with gfx9 devices like Vega64, MI50(Vega 20), Radeon 7, recommend to use this type of card only.
Thank you.

**Comment by ROCmSupport** [comment]
Hi All,
Hainan and Topaz are very old cards having GFX IP of 7 and below, which are not supported with ROCm.
Thank you.

**Comment by eugene-bright** [comment]
Now you can use `rusticl` mesa backend. `RUSTICL_ENABLE=radeonsi` env variable is still required.
