### ISSUE TITLE
ROCm 3.5.0 leaves Vega 56 stuck in P-state 3

### ISSUE THREAD

**Issue by c0d3st0rm** [RadeonOpenCompute/ROCm#1149]
I'm on Arch Linux, using [`rocm-opencl-runtime`](https://aur.archlinux.org/packages/rocm-opencl-runtime/) as well as [`hip-rocclr`](https://aur.archlinux.org/packages/hip-rocclr/) from the Arch AUR, and after the first run of any OpenCL or HIP related program, ROCm leaves the Vega 56 stuck in P-state 3 at idle. The GPU will happily go up to higher levels, but then when there is no load it ends up sitting at P-state 3:
```bash
$ cat /sys/class/drm/card0/device/pp_dpm_sclk
0: 852Mhz 
1: 991Mhz 
2: 1138Mhz 
3: 1269Mhz *
4: 1312Mhz 
5: 1474Mhz 
6: 1538Mhz 
7: 1590Mhz 
```

This only happens once the ROCm stack is used - I can play games just file and this does not occur, nor does it during normal system usage. It seems to be the exact same issue that @Bengt had here:
- https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/621
- https://github.com/Oblomov/clinfo/issues/43

Restricting the power states with rocm-smi does not help, and the GPU stays in state 3. I've tried both:
```bash
$ sudo rocm-smi --setsclk 0 1 2 3 4 5 6 7


========================ROCm System Management Interface========================
GPU[0]          : Successfully set sclk frequency mask to Level 0 1 2 3 4 5 6 7
==============================End of ROCm SMI Log ==============================
```
and:
```bash
$ sudo rocm-smi --setsclk 0 1 6 7            


========================ROCm System Management Interface========================
GPU[0]          : Successfully set sclk frequency mask to Level 0 1 6 7
==============================End of ROCm SMI Log ==============================
```

However the GPU still stays the same:
```bash
$ cat /sys/class/drm/card0/device/pp_dpm_sclk
0: 852Mhz 
1: 991Mhz 
2: 1138Mhz 
3: 1269Mhz *
4: 1312Mhz 
5: 1474Mhz 
6: 1538Mhz 
7: 1590Mhz 
```

While in state 3 it makes a very high-pitched electrical whine, which makes this completely unsuitable for desktop use (which is what the GPU is in right now). `clpeak` and `HIP-Examples` all run successfully. Nothing useful appears in `dmesg`. I'm on kernel `5.7.2-arch1-1` and mesa `20.1.1-1`. The only way I have found that fixes the issue is rebooting the machine. OpenGL and Vulkan do not seem to trigger this issue.

**Comment by Bengt** [comment]
Hi, @c0d3st0rm! Thanks for filing this issue against this repository, too. Hopefully, someone can find a permanent solution in this context. I noticed that there are lots of OpenGL applications which do not trigger this behavior. Which program are you using to reproduce this issue?

**Comment by c0d3st0rm** [comment]
@Bengt no problem. I can run `clinfo`, which triggers the issue, or HIP-Examples' `test_all.sh`, which also causes this to happen. However, `rocminfo` does not. The [`opencl-amd`](https://aur.archlinux.org/packages/opencl-amd/) driver does not seem to trigger this issue. If you need any more information, please let me know - however I'm unsure where to go from here.

**Comment by Bengt** [comment]
@c0d3st0rm Yes, `clinfo` still triggers this behavior for me, too. I can also confirm that `rocminfo` does not trigger an elevated power state. I have no idea how to investigate this from here, either. Let's hope, someone who does picks this up at some point.

**Comment by c0d3st0rm** [comment]
@Bengt Do you know of anyone else who is also experiencing this issue?

**Comment by Bengt** [comment]
Yes, this issue has been reported against this repository, before by @iszotic:

https://github.com/RadeonOpenCompute/ROCm/issues/857

Folding@Home can also trigger this behaviour:

https://github.com/RadeonOpenCompute/ROCm/issues/1081

**Comment by c0d3st0rm** [comment]
Folding@home, to my knowledge, uses OpenCL, so it might be that this issue applies to anything that seems to touch the OpenCL stack. I'll try Blender with OpenCL later, although I expect it will yield the same results. Luxmark would be an option but it seems that according to issue #1145 it doesn't work? The reporter, @ableeker is also running a Vega GPU - I wonder if this issue affects the render somehow.

**Comment by c0d3st0rm** [comment]
So Blender with OpenCL crashes trying to render the classroom demo - see the thread at https://github.com/rocm-arch/rocm-arch/issues/258. This might deserve a separate issue upstream here, if there isn't one already, however someone will need to verify it on Ubuntu 18.04 or another supported distribution.

**Comment by c0d3st0rm** [comment]
This P-state bug seems to happen with ROCm 3.3.0 as well, on Arch Linux. However, OpenCL does not crash Blender.

**Comment by Disty0** [comment]
With rocm-opencl-runtime 3.5.0-1 from arch4edu repo, my Vega 56 was able to render default blender cube scence but with in 2 mins and 45 seconds. My card coil whines exactly like when i overload her memory and according to rocm-smi VRAM usage changes between %20-95 constantly. My Desktop glitched heavily while rendering but nothing crashed. P-states stayed normal.

**Comment by ROCmSupport** [comment]
Thanks @c0d3st0rm for reaching out.
Not able to reproduce locally with the latest ROCm 4.0.
Request you to file a new issue, if any.
Thank you.

**Comment by Bengt** [comment]
I cannot confirm this issue being fixed. The described behavior still persists for me. I am running Ubuntu 20.10 and ROCm 4.0 on Vega 64s. @ROCmSupport, which combination of hardware and operating system are you running? I would be interested in a combination that works flawlessly.

**Comment by ROCmSupport** [comment]
Hi @Bengt 
Am using Ubuntu 20.04.1 + 2* Vega10 (64cu)

**Comment by Bengt** [comment]
Okay, this leaves only the (Ubuntu 20.10) stock kernel versus the ROCk kernel module (rocm-dkms) as the only difference between our setups. I guess, whatever fixed it will be in the mainline soon.

**Comment by Bengt** [comment]
I upgraded to the [5.10.6 mainline kernel](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.6/) and the behavior is slightly different when I run `clinfo`:

-  The display gets dark for a faction of a second and then correctly lists both devices as per usual.
-  Afterwards only the first GPU enters p-state 3, while the second one goes to p-state -1 (which is a power saving mode as the LED labelled D4021 on the PCB indicates)

When I try to read the p-state from sysfs, the second GPU, the display gets dark for a moment and the GPU then enters p-state 0 for a few seconds, before it goes to p-state -1 (green) again.

    $ cat /sys/class/drm/card0/device/pp_dpm_sclk

This process is reproducible. The second GPU only fires up to p-state 0, when I read its properties and goes back to sleep afterwards.

I have never seen this behavior before. So I guess, the kernel does indeed make a difference and the power management is actively being worked on. Sending the second GPU to sleep seems alright, already. I would however be nice to be able to access sysfs without resetting the display output. Still, the issue brought forward here by @c0d3st0rm with the first GPU not going back to p-state 0 persists.
