### ISSUE TITLE
Corrupted display

### ISSUE THREAD

**Issue by grmat** [RadeonOpenCompute/ROCm#115]
After following the installation instructions with binaries from the repo, I can't use the graphical desktop anymore.

The screen is corrupted and shows content that was shown **before rebooting** (see picture below) like visited websites.

GPU: Hawaii (R9 290X)
OS: Ubuntu 16.04

I can then switch to a virtual terminal, build and run the vector sample without problems.

![corrupted-screen](https://cloud.githubusercontent.com/assets/12658837/25686663/50544672-3070-11e7-839e-7a2a99fa4cc8.jpg)

**Comment by gstoner** [comment]
Can you try ROCm 1.6 here are new install instructions 
https://rocm.github.io/ROCmInstall.html

**Comment by grmat** [comment]
@gstoner freshly installed Ubuntu 16.04 + ROCm 1.6, the problem remains.

Just read that Michael from Phoronix is affected by the same problem:

> when trying ROCm 1.6 with the Radeon R9 290 I was just hitting corrupted screen output when booting the system

https://www.phoronix.com/scan.php?page=article&item=amd-rocm16-nvidia&num=1

**Comment by gstoner** [comment]
There are big changes coming AMDGPU driver in how they are handling display in Linux Kernel 4.15, this is not ROCm compute driver issue.
