### ISSUE TITLE
About GPUs not initialized without display attached

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1150]
A number of users have been complaining about GPUs and OpenCL non initialized if no display is attached to the GPU.
This behavior only happens on some systems, on other systems (like computing RIGs) I have never encountered this bug.
Thus the bug must be system-configuration dependent or package-dependent, but it does not happen on all systems.
Do you have any idea why this happens only on some systems?

**Comment by preda** [comment]
I see (every time) a different variant of this issue: OpenCL is not initialized unless I do a login in the GUI. This is on Ubuntu 19.10 with ROCm. Doing a login through ssh (remotely) does not count.

**Comment by valeriob01** [comment]
I have never seen this error, though I have a display attached on the mainboard integrated graphics. But this does not count I suppose. I can do a test removing that display if necessary.

**Comment by valeriob01** [comment]
btw, I login via ssh not in the main display.

**Comment by c0d3st0rm** [comment]
What GPUs/distro/kernel version?

**Comment by valeriob01** [comment]
Radeon VII, Ubuntu Focal, 5.4

**Comment by ROCmSupport** [comment]
Thanks @valeriob01 for reaching out.
We have not seen this issue any time and most of our machines are without display connected only.
Hence request to file specific issue separately, if you see/find any.
