### ISSUE TITLE
device 0 has unique_id empty

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1151]
On all my systems the device 0 has unique_id empty while device 1, 2, etc. show the actual unique_id.

**Comment by valeriob01** [comment]
I run Ubuntu Focal on those systems.

**Comment by preda** [comment]
Please provide a bit more detail:
- how many GPUs, what GPUs. Does the CPU have an integrated GPU? Maybe provide a listing of /sys/class/drm/ for comparison with the number of GPUs. Also, maybe a comparison of the content of /sys/class/drm/card0/ vs. /sys/class/drm/card1/
I suppose there are no errors reported in dmesg?

What does "rocm-smi --showuniqueid" report?

**Comment by valeriob01** [comment]
No errors in dmesg. 2 GPUs, Radeon VII of course. Details later maybe.

**Comment by valeriob01** [comment]
```
/opt/rocm-3.3.0/bin/rocm-smi --showuniqueid


========================ROCm System Management Interface========================
================================================================================
GPU[1] 		: Unique ID: 592c190172fd5d40
GPU[2] 		: Unique ID: c6f220c172dc76bb
================================================================================
==============================End of ROCm SMI Log ==============================

```

**Comment by valeriob01** [comment]
This is a gpuOwl specific issue.

**Comment by valeriob01** [comment]
https://github.com/preda/gpuowl/pull/170
