### ISSUE TITLE
PyTorch Docker container does not run

### ISSUE THREAD

**Issue by devksingh4** [RadeonOpenCompute/ROCm#1155]
Hello, 
After following these instructions: 
[https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#recommended-install-using-published-pytorch-rocm-docker-image](https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#recommended-install-using-published-pytorch-rocm-docker-image), I run `PYTORCH_TEST_WITH_ROCM=1 python test/run_test.py --verbose` and get `No module named torch`. This is running in the Docker container. 

System: 
AMD Ryzen 5 1600AF
AMD RX 580 8GB 
Ubuntu 18.04.4 LTS - Kernel 5.3.0-59
`rocminfo` shows `ROCk module is loaded`, GPU is shown as Agent 2.

**Comment by rkothako** [comment]
Hi @devksingh4 
Please try with PYTORCH_TEST_WITH_ROCM=1 **python3.6** test/run_test.py --verbose

**Comment by devksingh4** [comment]
That does work! Jupyter Lab doesn't launch in this environment, but I suspect that's another issue, I'll file another bug. 

The documentation should be changed to reflect this, no?

**Comment by Rmalavally** [comment]
The AMD ROCm documentation is updated to reflect this correction at:

https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#building-pytorch-for-rocm

Thank you for reaching out.
