### ISSUE TITLE
Ubuntu / Debian packages do not update /opt/rocm symlink

### ISSUE THREAD

**Issue by Dantali0n** [RadeonOpenCompute/ROCm#1157]
The Debian / Ubuntu packages will not update the `/opt/rocm` symlink when upgrading to a new releases. This leaves everything in a broken state after upgrading.

**Comment by YifeiLuDublin** [comment]
Maybe try uninstall the previous rocm version and reinstall 3.5.1 following the [installation guide](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html)?
This fixed my 3.5.0 and 3.5.1 mix.

**Comment by Dantali0n** [comment]
> Maybe try uninstall the previous rocm version and reinstall 3.5.1 following the [installation guide](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html)?
> This fixed my 3.5.0 and 3.5.1 mix.

Yes that would be a workaround but not a fix, deb packages should be self isolated packages that make all necessary changes. Any dependency or transition required to update from one package to the next should be made by simply upgrading to the newer version of the package.

**Comment by bd4** [comment]
Related to #1160. Having to uninstall first or force re-install on every minor version update is a very unexpected extra requirement for those used to ubuntu/debian systems.

**Comment by ye-luo** [comment]
This caused a lot of pain to reinstall many packages manually via trial and error.

**Comment by ROCmSupport** [comment]
Hi @Dantali0n and others,
ROCm upgrade is not upto mark and so recommend all to go with uninstall and install for now.
Solved most of the issues specific to ROCm Upgrade now, we will share an official note once all checks are done. Please stay tuned for the updates.
Thank you.
