### ISSUE TITLE
Don't ship versioned folders in unversioned Debian packages

### ISSUE THREAD

**Issue by DaDummy** [RadeonOpenCompute/ROCm#1160]
While it is understandable that support for side-by-side installs of different ROCm versions is intended, this is a concept that does not seem to be properly implemented for the ROCm Debian packages.

And since the 3.5.1 release now has shown that mixed versions are getting shipped on the package repository, the symlink-approach for providing a stable path should be dropped as too unreliable to provide any real benefit.

Instead, please either adjust the packaging to install to stable unversioned paths, so things stop breaking on every other update or actually introduce versioned packages (with the version number in their names), support installing multiple of those in parallel, utilize the powerful alternatives system that comes with Debian and Debian-based distributions: https://wiki.debian.org/DebianAlternatives and then provide unversioned meta-packages that depend on the then-current versioned package similar to how e.g. Linux Kernels are distributed.

Breaking user's setups on every single update and now even patch-release is not fun. Please let's find a solution to put an end to that.

**Comment by DaDummy** [comment]
I just realized part of that mixed stated resulted from some packages being released with the **same version**, but **changed contents**.

Come on, guys, you can do better then this :(

**Comment by bd4** [comment]
I just ran into this with the 3.5.1 release. In particular, llvm-amdgpu is still in /opt/rocm-3.5.0 and the new hipcc in /opt/rocm-3.5.1/hip/bin (symlinked to /opt/rocm/bin) can't find it.

I am trying to hack around the broken packages by symlinking `/opt/rocm-3.5.0/llvm` into `/opt/rocm-3.5.1` and various other subdirectories which are now split across the two version directories - lib and include at least.

**Comment by DaDummy** [comment]
As a temporary fix: Try reinstalling llvm-amdgpu:
```bash
sudo apt update
sudo apt reinstall llvm-amdgpu
```

If that package was rebuilt without changing the version number, too, it wasn't automatically updated by apt.

**Comment by bd4** [comment]
Thanks @DaDummy, confirmed that `apt install --reinstall llvm-amdgpu` causes it to move to the correct location.

I ran `dpkg -S /opt/rocm-3.5.0` to find remaining broken packages, and reinstalled those as well:
```
apt install --reinstall rocm-opencl-dev rocm-opencl rocprofiler-dev hsakmt-roct hsakmt-roct-dev llvm-amdgpu
```
Seems to have done the trick, on both an Ubuntu LTS and a debian stable machine.

**Comment by bd4** [comment]
Note that this also affects the docker images in strange ways, if you need to install any packages beyond the default set. In particular I am using 3.5 tag, and it does not include rocprim and rocthrust by default, so I apt install them, but then end up with a mixed install since the repo has moved on to 3.5.1 and all the pre-installed packages are still at 3.5.0.

**Comment by baryluk** [comment]
This is still broken in 3.7

As other have said, only versioned packages should be installed and provide the actual files.

The non versioned packages should be virtual and depend on latest versioned packages.

Multiple versioned packages should be co-installable, and managed via debian alternatives mechanisms. All binaries should have versions in their name, with the symlinks to also provide non-versioned names.

This is easy and works so well.

I mentioned that before in https://github.com/RadeonOpenCompute/ROCm/issues/1134

**Comment by ROCmSupport** [comment]
Thanks all for sharing updates on this.
As, now,  side-by-side install is matured and versioned packages are properly made, request you to validate with the latest ROCm 4.0 and update the same. 
Thank you.

**Comment by ROCmSupport** [comment]
To conclude the issue, we do not have plans to separate versioned and non-versioned packages in different paths/folders.
Versioned packages are working good now with the latest ROCm 4.0 and so request to try the same.
Thank you.

**Comment by baryluk** [comment]
Still broken in 4.0.
