### ISSUE TITLE
ImportError: librccl.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vuquocan1987** [RadeonOpenCompute/ROCm#1161]
Hello, I am trying to install rocm but got the above error when trying to import tensorflow
" ImportError: librccl.so.1: cannot open shared object file: No such file or directory "
My set up is:

ubuntu 20.04
rocm 3.5
tensorflow-rocm 2.2.0
gpu rx580
cpu intel 9100f
( using anaconda, if that matter )

I saw some other guys has same error he fix it with:
`yum install rccl`
I used 
`sudo apt install rccl`
installing was successful but I still got same error.
What should I do?

**Comment by xuhuisheng** [comment]
It's said that rocm cannot support ubuntu-20.04 right now.
https://github.com/RadeonOpenCompute/ROCm/issues/1112

I just install rocm-3.5.1 on ubunt-18.04, with sudo apt install rccl.

Ubuntu 18.04.04
ROCm 3.5.1-34
Python 3.6.10 with anaconda
tensorflow-rocm 2.2.0
cpu I7 4770
gpu RX 580

**Comment by xuhuisheng** [comment]
It seems the `reboot` wont refresh ld cache, we must run `sudo ldconfig`.

**Comment by Bengt** [comment]
I already had an old version of rccl installed:

    $ sudo apt install rccl
    [...]
    rccl is already the newest version (2.10.0-311-g1d2aa4e-rocm-rel-3.3-19).

I tried reinstalling it, anyways:

    $ sudo apt install --reinstall rccl
    [...]
    Reinstallation of rccl is not possible, it cannot be downloaded.

Uninstalling and installing RCCL got me the ROCm 3.8 version:

```
$ sudo apt remove rccl
[...]
Removing rccl (2.10.0-311-g1d2aa4e-rocm-rel-3.3-19) ...
$ sudo apt install rccl
[...]
Preparing to unpack .../rccl_2.7.8.467-rocm-rel-3.8-30-391bbf3_amd64.deb ...
Unpacking rccl (2.7.8.467-rocm-rel-3.8-30-391bbf3) Setting up rccl (2.7.8.467-rocm-rel-3.8-30-391bbf3)
```

So for your convenience:

    sudo apt remove --yes rccl && sudo apt install --yes rccl

**Comment by ROCmSupport** [comment]
Hi @vuquocan1987 
Thanks for reaching out.
As tensorflow needs rccl and other math libraries along with rocm, always recommend to try the below way.
sudo apt install rocm-dkms rocm-libs rccl.

Recommend to try with the latest ROCm 3.10 and all packging/installation issues are resolved.

**Comment by denfromufa** [comment]
Same error with tensorflow-rocm binary wheel/package from PYPI:

ImportError: librccl.so.1: cannot open shared object file: No such file or directory

**Comment by ROCmSupport** [comment]
As this issue is already closed, recommend to open a new issue with all supported details.
Thank you.

**Comment by denfromufa** [comment]
Installing rccl package and adding it to LD_LIBRARY_PATH resolved the issue.
Having RCCL wheel from PYPI would resolve this issue without sudo access.
