### ISSUE TITLE
How to buy AMD GPU ?

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1162]
Can we expect to see the **Radeon Pro VII** on the AMD Shop soon ?

**Comment by Chr0m0s0m3s** [comment]
not the correct place to ask the question

**Comment by valeriob01** [comment]
maybe you can also extend your reply with the correct place?

**Comment by Chr0m0s0m3s** [comment]
correct place to ask the question : https://community.amd.com/community/support-forums/graphics/content

**Comment by valeriob01** [comment]
too late, I have anticipated you, already been there.
