### ISSUE TITLE
Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vuquocan1987** [RadeonOpenCompute/ROCm#1163]
I installed the tensorflow_rocm with rocm stack on my computer, but when I tried to create a model I got such error.

My set up is:

ubuntu 18.04.04
rocm 3.5.1
tensorflow-rocm 2.2.0
gpu rx580
cpu intel 9100f

What is wrong?

**Comment by xuhuisheng** [comment]
it seems that ldconfig cannot find the soft link of hip_hcc,
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/hip/lib
then it run well

Ubuntu 18.04.04
ROCm 3.5.1-34
tensorflow-rocm 2.2.0
Python 3.6.0 with anaconda

Hardware:
cpu I7 4770
gpu RX 580

**Comment by vuquocan1987** [comment]
thank you very much, this does solve my problem. Do you know why though?

**Comment by Chr0m0s0m3s** [comment]
Solves the problem partially but not fully

**Comment by xuhuisheng** [comment]
> 
> 
> thank you very much, this does solve my problem. Do you know why though?

At this moment, I dont know why caused this situation.
The libhip_hcc.so and related files are in the /opt/rocm/hip/lib directory, but even if  I run `sudo ldconfig`, but `tensorflow-rocm` cannot find these `.so` files.

**Comment by papadako** [comment]
I am not sure either. If you delete libhiprtc.so then ldconfig will find libhip_hcc.so.
Check my post https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1019#issuecomment-649432182 about another workaround

> > thank you very much, this does solve my problem. Do you know why though?
> 
> At this moment, I dont know why caused this situation.
> The libhip_hcc.so and related files are in the /opt/rocm/hip/lib directory, but even if I run `sudo ldconfig`, but `tensorflow-rocm` cannot find these `.so` files.

**Comment by ROCmSupport** [comment]
Hi @vuquocan1987 and all,
Thanks for reaching out.
This issue is fixed and no more observed with the recent ROCm release versions.
Recommend to try with 3.10.
Thank you.
