### ISSUE TITLE
amdgpu driver crashes after using OpenCL in Mandelbulber

### ISSUE THREAD

**Issue by clavinet** [RadeonOpenCompute/ROCm#1166]
Please see this issue for reference:
https://github.com/buddhi1980/mandelbulber2/issues/663

When rendering reflective or transparent images using ROCm's OpenCL implementation, the amdgpu Linux kernel driver crashes.
This leaves the desktop unusable - "X is wedged". In my case, I saw heavy graphical artifacts, a crashed KDE session and the desktop left in an unresponsive state.

Multiple users reported this issue with at least these cards:
AMD Radeon RX 580
AMD Radeon RX 570

**Comment by baryluk** [comment]
Works fine for me on AMD Radeon R9 Fury X (FIJI, GFX8), with ROCm 3.8 and ROCm 3.9. I tested Mandelbulber 2.23 appimage from the github.

Looks like it is related to specific GPU and kernel.

Could you try again with most recent kernel you can try, and ROCm 3.9?

**Comment by ROCmSupport** [comment]
Thanks @clavinet 
Not able to reproduce this issue with the latest ROCm 3.10.
Recommend to try with the latest ROCm 3.10.
Thank you.
