### ISSUE TITLE
Installing on Arch Linux

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCm#117]
Has anyone tried installing ROCm (both kernel and userspace) under Arch Linux? Or perhaps someone has had luck installing the kernel and running the userspace tools from an Ubuntu docker?

**Comment by gstoner** [comment]
No we have not tried Arch Linux

Greg
On May 5, 2017, at 7:11 AM, almson <notifications@github.com<mailto:notifications@github.com>> wrote:


Has anyone tried installing ROCm (both kernel and userspace) under Arch Linux? Or perhaps someone has had luck installing the kernel and running the userspace tools from an Ubuntu docker?

**Comment by grmat** [comment]
@almson have you tried building the kernel?
You can take [linux-git](https://aur.archlinux.org/packages/linux-git/) as a template and replace the source with the ROCK repo. Make sure you have amdgpu support for your device enabled in the config if it's a pre-VI GPU.

I have started creating `PKGBUILD`s for roct, rocr and hcc but those are neither complete nor tested.

**Comment by almson** [comment]
@grmat Thank you, I will try it. If you need help testing, I will gladly try your `PKGBUILD`s.

**Comment by grmat** [comment]
@almson thanks for the offer. I'll get back to you when I make progress

**Comment by almson** [comment]
To compile the kernel:

First, clone the `linux-git` repo and check out the commit for linux 4.9.0

    git clone https://aur.archlinux.org/linux-git.git linux-rocm
    cd linux-rocm
    git checkout 63b0d79

Then, edit PKGBUILD and rename `linux-git.preset` to `linux-rocm.preset`

    diff --git a/PKGBUILD b/PKGBUILD
    index ae5e7b0..c135a8f 100644
    --- a/PKGBUILD
    +++ b/PKGBUILD
    @@ -5,16 +5,16 @@
     # Contributor: misc <tastky@gmail.com>
     # Contributor: NextHendrix <cjones12 at sheffield.ac.uk>
 
    -pkgbase=linux-git
    -_srcname=linux
    -pkgver=4.9.r0.g69973b8
    +pkgbase=linux-rocm
    +_srcname=ROCK-Kernel-Driver
    +pkgver=roc.1.5.0.r0.g757f29e928f0
     pkgrel=1
     arch=('i686' 'x86_64')
     url="http://www.kernel.org/"
     license=('GPL2')
     makedepends=('xmlto' 'docbook-xsl' 'kmod' 'inetutils' 'bc' 'git' 'libelf')
     options=('!strip')
    -source=('git+https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'
    +source=('git+https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver.git'
             # the main kernel config files
             'config' 'config.x86_64'
             # standard config files for mkinitcpio ramdisk
    diff --git a/linux-git.preset b/linux-rocm.preset
    similarity index 100%
    rename from linux-git.preset
    rename to linux-rocm.preset

Finally, makepkg

    makepkg -s

**Comment by acxz** [comment]
I know this is a long time ago, but I just want to put this here in case others come across it. The ArchLinux community including me and some other folks have started picking up development on getting the ROCm stack working here: https://github.com/rocm-arch/rocm-arch. Feel free to submit PRs or issues!

**Comment by IndML101** [comment]
Hi,

I'm trying to install rocm on Manjaro (kerne 5.8.6), but it throws an error while installing rocsolver:

fatal error: error in backend: Cannot select: 0x555f6ea3b378: i64 = FrameIndex<0>
In function: _Z11bdsqrKernelI19rocblas_complex_numIdEdPS1_EviiiiPT0_lS4_lT1_iilS5_iilS5_iilPiiS3_S3_S3_S3_S4_l
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 38fffda570a017745da11c40ed8991c3c70a3281)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:342: rocsolver/library/src/CMakeFiles/rocsolver.dir/auxiliary/rocauxiliary_bdsqr.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/gubberex/Downloads/rocsolver/src/build'
make[1]: *** [CMakeFiles/Makefile2:131: rocsolver/library/src/CMakeFiles/rocsolver.dir/all] Error 2
make[1]: Leaving directory '/home/gubberex/Downloads/rocsolver/src/build'
make: *** [Makefile:171: all] Error 2
make: Leaving directory '/home/gubberex/Downloads/rocsolver/src/build'
==> ERROR: A failure occurred in build().
    Aborting...



Any clues?

**Comment by realsushi-official** [comment]
> 
> 
> Hi,
> 
> I'm trying to install rocm on Manjaro (kerne 5.8.6), but it throws an error while installing rocsolver:
> 
> fatal error: error in backend: Cannot select: 0x555f6ea3b378: i64 = FrameIndex<0>
> In function: _Z11bdsqrKernelI19rocblas_complex_numIdEdPS1_EviiiiPT0_lS4_lT1_iilS5_iilS5_iilPiiS3_S3_S3_S3_S4_l
> clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
> clang version 11.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 38fffda570a017745da11c40ed8991c3c70a3281)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /opt/rocm/llvm/bin
> clang-11: note: diagnostic msg: Error generating preprocessed source(s).
> make[2]: *** [rocsolver/library/src/CMakeFiles/rocsolver.dir/build.make:342: rocsolver/library/src/CMakeFiles/rocsolver.dir/auxiliary/rocauxiliary_bdsqr.cpp.o] Error 70
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/home/gubberex/Downloads/rocsolver/src/build'
> make[1]: *** [CMakeFiles/Makefile2:131: rocsolver/library/src/CMakeFiles/rocsolver.dir/all] Error 2
> make[1]: Leaving directory '/home/gubberex/Downloads/rocsolver/src/build'
> make: *** [Makefile:171: all] Error 2
> make: Leaving directory '/home/gubberex/Downloads/rocsolver/src/build'
> ==> ERROR: A failure occurred in build().
> Aborting...
> 
> Any clues?

---
From my understanding, the kernel is not supported because the gcc compiler has to match with rocm package compiler.
I'm not sure you've shared the error actually.
Try changing kernel to 5.6 and check gcc version.

**Comment by ROCmSupport** [comment]
As this ticket is already closed, recommend to open a new ticket for any new issues to get fast response.
Thank you.
