### ISSUE TITLE
ROCm Support for Radeon Pro 5600M

### ISSUE THREAD

**Issue by strategist922** [RadeonOpenCompute/ROCm#1172]
I check the document and repo of ROCm (http://repo.radeon.com/rocm/apt/3.5/pool/main/m/)
It seems only support architecture gfx900 and gfx906 at this moment.

I check the hardware spec. and LLVM doc on https://llvm.org/docs/AMDGPUUsage.html, it shows 
the new Radeon Pro 5600M's architecture should be gfx1011 with 40 CU.

May I know when will ROCm officially support new Radeon Pro 5600M?

Thanks and best regards,

**Comment by ROCmSupport** [comment]
Hi @strategist922 
Thanks for reaching out.
Currently we are not supporting Radeon 5000 series with ROCm.
We have plans to support Radeon 6000 series with ROCm in near future.
Thank you.

**Comment by aliPMPAINT** [comment]
@ROCmSupport wait, there are no plans for Radeon 5000 series, just 6000?

**Comment by ROCmSupport** [comment]
Hi @aliPMPAINT 
Am not commenting about Radeon 5000 future plans because I do not have handy information.
We will definitely share the information in future if any.

**Comment by Umang-Kumar** [comment]
Hey @ROCmSupport do we have that functionality now, cause I've got a Radeon RX5600M GPU and was wondering if I can use ROCM on that..??
