### ISSUE TITLE
rocminfo error Unable to open /dev/kfd read-write Failed to get user name to check for video group membership

### ISSUE THREAD

**Issue by Shreyashwaghe** [RadeonOpenCompute/ROCm#1174]
my system - Linux shreyash-Nitro-AN515-42 4.15.0-99-generic #100~16.04.1-Ubuntu SMP Wed Apr 22 23:56:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
acer nitro 5 ryzen 5 
processor - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx × 8 
graphics - AMD RAVEN (DRM 3.36.0 / 4.15.0-99-generic, LLVM 6.0.0) in all setting-> details
                 amd radeon rx560x real hardware from manufacturer, are these same or not

(base) shreyash@shreyash-Nitro-AN515-42:~$ /opt/rocm/bin/rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
Failed to get user name to check for video group membership
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

(base) shreyash@shreyash-Nitro-AN515-42:~$ groups
shreyash adm cdrom sudo dip video plugdev lpadmin sambashare

**Comment by xuhuisheng** [comment]
try `dmesg | grep kfd`, check info like `[ 5.737933] kfd kfd: skipped device 1002:67df, PCI rejects atomics`, GFX8(like rx580) need both cpu and motherboard support 'PCIe atomics', please refer the offical readme : https://github.com/RadeonOpenCompute/ROCm#supported-cpus

**Comment by ROCmSupport** [comment]
Hi @Shreyashwaghe 
Thanks for reaching out.
Can you please try with the latest ROCm 3.10 and share me an update.
Thank you.

**Comment by Karthikeyan564** [comment]
Hi
I have the same system.
The problem still persists on ROCm v4
`dmesg | grep kfd`
does not give any output.

**Comment by ROCmSupport** [comment]
Hi @Shreyashwaghe 
As per the info @ [https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support](url), Raven is not an official supported hardware. Only OpenCL things might work. 
Thank you.
