### ISSUE TITLE
BlendLuxcore v2.4 failing to build opencl kernal 

### ISSUE THREAD

**Issue by matthewv1998** [RadeonOpenCompute/ROCm#1190]
specs. 2x Vega 56, 3900x, 128gb ram, Ubuntu 20.04.1, rocm 3.5.1. 
in an attempt to diagnose a issue with blendluxcore, i installed rocm and it fails to build the opencl kernals, cycles is able to build kernals and render with my gpus. 
following error the addon spat out. 
OpenCL driver API error (code: -11, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/utils/ocl.cpp, line: 369): CL_BUILD_PROGRAM_FAILURE
it does build the kernal with the AMD PRO drivers. (however there is a issue with normal maps that i was trying to nail down by installing these drivers)

*UPDATE* Blendluxcore v2.3 doesnt compile either and just instantly crashes out

**Comment by ROCmSupport** [comment]
Hi @matthewv1998 
Thanks for reaching out.
Can you please share the below outputs.
_/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo_

Can you please try with the latest ROCm 3.10 and update please?

If the issue still exist, please share the exact steps to reproduce the problem.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @matthewv1998 
Please share an update, else close this issue if no issues.
Thank you.

**Comment by ROCmSupport** [comment]
Closing this ticket as there is no response from user for a long time.
Thank you.
