### ISSUE TITLE
Navi support on ROCm 3.7

### ISSUE THREAD

**Issue by omerferhatt** [RadeonOpenCompute/ROCm#1194]
Is there any unofficial support for Navi cards? Or is there a planned date?

**Comment by omerferhatt** [comment]
People are bored with this question, and now I'm closing it.

**Comment by santoniuk** [comment]
I'm using rocm 3.3 on Fedora for openCL.  RX 5700

**Comment by santoniuk** [comment]
> People are bored with this question, and now I'm closing it.

I'm bored to have card released year ago with no official support. Next one will be Nvidia.))

**Comment by xuhuisheng** [comment]
There is a change to build pytorch for nav10(gfx1010) on rocm3.7, someone who had a rx5700xt could have a test.
https://github.com/ROCmSoftwarePlatform/pytorch/issues/718
