### ISSUE TITLE
Add support for Clearlinux OS

### ISSUE THREAD

**Issue by namm2** [RadeonOpenCompute/ROCm#1197]
Clearlinux OS provides a fast working linux distribution (https://www.phoronix.com/scan.php?page=search&q=Clear%20Linux). Please help to add Clearlinux to be supported to build ROCm.

**Comment by ROCmSupport** [comment]
Hi @namm2 
Thanks for reaching out.
We are not officially supporting Clearlinux OS.
Thank you.
