### ISSUE TITLE
ROCm 1.5 + kernel 4.9 causes  Graphics pipe 100,00% usage

### ISSUE THREAD

**Issue by gsedej** [RadeonOpenCompute/ROCm#120]
I instelled ROCm 1.5 on my ubuntu 16.04, using RX 480.

Whenever I boot kerne l4.9.0-kfd-compute-rocm-rel-1.5-76, my gpu usage is 100%, also the temperature is high! This is making FAN spin fast (and noise)
The "radeontop" says "Graphics pipe 100,00%" but all other "parts" stay around 0%, when not used.
I can use "low" DPM, force gpu at 300MHz, but this makes low performace. When wet to "auto" it jumps to 1300MHz. I cannot change VRAM away from 2000MHz.
(The fan control does work, I can set fan speed in %. Also the auto fan is not 100%)

_(it did work ok with ROCm 1.4 (?) when kernel 4.6-kfd... was used)_

dmesg: http://paste.ubuntu.com/24554269/

**Comment by gstoner** [comment]
We check on this and get back to you

**Comment by gstoner** [comment]
Can i get the spec on the processor and motherboard brand and model number

**Comment by gsedej** [comment]
The CPU is Skylake i7-6700 CPU and the mobo is Z170-HD3P/Z170-HD3P-CF. (other details are visible in dmesg)
The 100% gpu usage is only in this kernel. (I didn't see this issue in 4.6-kfd, and ubuntu mainline kernels: 4.8, 4.9, 4.10). To mention again that radeontop not detecting what is causeng 100% gpu usage, see screenshot
![zaslonska slika 2017-05-11 17-33-57](https://cloud.githubusercontent.com/assets/6927198/25958123/273e6b36-3670-11e7-9bf8-fbffa258785b.png)

**Comment by gsedej** [comment]
The CPU is Skylake i7-6700 CPU and the mobo is Z170-HD3P/Z170-HD3P-CF. (other details are visible in dmesg)
The 100% gpu usage is only in this kernel. (I didn't see this issue in 4.6-kfd, and ubuntu mainline kernels: 4.8, 4.9, 4.10). To mention again that radeontop not detecting what is causeng 100% gpu usage, see screenshot
![zaslonska slika 2017-05-11 17-33-57](https://cloud.githubusercontent.com/assets/6927198/25958123/273e6b36-3670-11e7-9bf8-fbffa258785b.png)

**Comment by gstoner** [comment]
We think we found the issue,  it was in the base linux port in 4.9 base driver update.   I am hoping to have fix of this out my tuesday next week.   We had planned 1.5.1 update with new architecture support ARM and Power

greg
On May 12, 2017, at 8:13 AM, gsedej <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #120<https://github.com/RadeonOpenCompute/ROCm/issues/120>.

**Comment by grmat** [comment]
I can confirm the bug on Hawaii. Trying to run the `vector_copy` hsa sample hangs at `Loading the code object succeeded`. Even `clinfo` with the newly released OpenCL runtime hangs and results in 100% load.

BTW: is it possible to reset the GPU without rebooting?

**Comment by gsedej** [comment]
@gstoner Thanks for repy, looking forward for update! May I ask the use case of rocm + arm (and power) - playstation4 and xobox one?

@grmat 
#1 my gpu load is always 100% after boot (before running any "cl" command)
#2 you can try by "service lightdm stop", go to virtual terminal (ctl + alt + f1) and "rmmod amdgpu" (and all connected), "modprobe amdgpu" and finally "service lightdm start".  I did this in "radeon" times on my hd5670, but I can't test now (middle of work).

**Comment by gstoner** [comment]
Can you guys pull updated driver.

**Comment by grmat** [comment]
@gsedej thanks. For me, it only happens after invoking actual cl stuff. ARM and IBM Power servers might be significant for HPC/Datacenter. The mentioned gaming consoles are x86_64 and not related to computing.

@gstoner there are no new commits yet in ROCK?!

**Comment by gstoner** [comment]
@grmat We are pushing the linux team push out the updates in ROCK.   So the IDLE power issue is fixed with the update.  OpenCL set the clock high when they run, it is historical.   It is some thing we looking at addressing via better power management in conjunction with Compute. 

I am looking forward to finishing our CPU support,  ARM and Power support in source form will be first in 1.5 source code update.    We have work to do on the tool chains next,  HCC code gen support for Power and ARM.

**Comment by gsedej** [comment]
@gstoner the update fixes the GPU IDLE usage. Thanks for solving this!
The memory clock still stays at maximum, but it may be bug also in main kernels.
```
root@x:/sys/class/drm/card0/device# echo "auto" > power_dpm_force_performance_level
root@x:/sys/class/drm/card0/device# cat pp_dpm_sclk
0: 300Mhz *
(...)
7: 1306Mhz 
root@x:/sys/class/drm/card0/device# cat pp_dpm_mclk
0: 300Mhz 
1: 2000Mhz *
root@x:/sys/class/drm/card0/device# echo "low" > power_dpm_force_performance_level
root@x:/sys/class/drm/card0/device# cat pp_dpm_mclk
0: 300Mhz 
1: 2000Mhz *
```
The memory frequency always stays at maximum, but it's not big issue (probably?)
_(the vector_copy is passes for me (all succeeded)_
