### ISSUE TITLE
ROCm 3.7 installation missing libraries for Tensorflow-rocm

### ISSUE THREAD

**Issue by SandboChang** [RadeonOpenCompute/ROCm#1200]
This is a new installation of ROCm 3.7 and ubuntu 20.04.1.
In previous version of ROCm (and ubuntu) I did not have these issues, but now with 3.7 (could have happened with earlier versions as well) I often found missing libraries here and there.

For example, after install ROCm, and also install rocm-libs and tensorflow-rocm (via pip3), I still cannot import tensorflow:

```
>>> import tensorflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: librccl.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: librccl.so.1: cannot open shared object file: No such file or directory

```

Should they already be included in the installation of ROCm/Tensorflow-rocm?

**Comment by papadako** [comment]
I have build tensorflow 2.3 for rocm 3.7. You can find it here
https://139.91.183.23/tensorflow/tensorflow-2.3.0-rocm-3.7-cp38-none-any.whl

**Comment by acai66** [comment]
> I have built tensorflow 2.3 for rocm 3.7. You can find it here
> http://139.91.183.23/tensorflow/tensorflow-2.3.0-rocm-3.7-cp38-none-any.whl

Maybe my cpu is old and it not support some new instructions.
![image](https://user-images.githubusercontent.com/37766207/90992936-4f5d2f80-e5e5-11ea-82c0-0f6199a27f3b.png)

**Comment by xuhuisheng** [comment]
> 
> 
> I have built tensorflow 2.3 for rocm 3.7. You can find it here
> http://139.91.183.23/tensorflow/tensorflow-2.3.0-rocm-3.7-cp38-none-any.whl

Whick branch do you used? Could you show me the build instructions? Thanks.

**Comment by papadako** [comment]
I am using r2.3 from https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.git
The build is for a rather old cpu (i7-5820K CPU) running ubuntu 20.04 (python 3.8)

**Comment by xuhuisheng** [comment]
tensorflow-rocm-2.3.0 had released two hours ago, seems support rocm-3.7.0 officially.
I compiled pytorch with latest update, and pytorch could run mnist with rocm-3.7.0
But I cannot compiled tensorflow-upstream successfully, now

**Comment by gsedej** [comment]
Can someone update instructions to install package "rccl"? 
it's neither mentioned in rocm-tf github: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream
nor in "pypi"
https://pypi.org/project/tensorflow-rocm/
(the latter should also include some links to rocm-tensorflow)

**Comment by xuhuisheng** [comment]
First, you should install rocm-dkms following the offical documents, https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html
Then, you could install rccl and hipsparse, for example, on ubuntu `sudo apt install hipsparse rccl` and update ldconfig `sudo ldconfig`

**Comment by papadako** [comment]
Hi @xuhuisheng 

at least in my case I had to install the rocm 3.7.0 packages instead of the rocm version agnostic meta-packages

**Comment by srinivamd** [comment]
> Can someone update instructions to install package "rccl"?

When installing ROCm, use the rocminstall.py script (available at https://github.com/srinivamd/rocminstaller) simple to use, and installs with no hassle in one step.
`sudo ./rocminstall.py --rev 3.7`
will install all of ROCm 3.7.0 released packages. (Kernel packages `rock-dkms` and rock-dkms-firmware` will be installed only if none are installed already, i.e. it will not overwrite.)
Just run it and forget about ROCm install, just use ROCm~

**Comment by srinivamd** [comment]
If you use `rocminstall.py` from https://github.com/srinivamd/rocminstaller there would NO need to uninstall ROCm to pick up/install a new ROCm release! Simply use `rocminstall.py` to install the new release.
But first, clean/remove all installed ROCm packages to start using `rocminstall.py` installer.

**Comment by baryluk** [comment]
Would it make sense to add `rccl` as a dependency of `rocm-libs`? `rocm-libs` already do have a lot of dependencies for easier install of all libraries.

After `apt install rocm-libs3.8.0 rccl3.8.0` and doing `pip3 install tensorflow-rocm` and then `LD_LIBRARY_PATH=/opt/rocm-3.8.0/lib python3`, I got it working.

**Comment by ROCmSupport** [comment]
Hi All,
Currently rocm-libs meta package has every library including miopen, except rccl.
We have plans to add rccl also as part of rocm-libs and team is working towards it. After that tf works simply on top of rocm-dkms and rocm-libs.

**Comment by ROCmSupport** [comment]
Changes pushed and rccl will be part of rocm-libs from ROCm 4.1 onwards.
Thank you.
