### ISSUE TITLE
Please provide official release builds for Fedora

### ISSUE THREAD

**Issue by rigtorp** [RadeonOpenCompute/ROCm#1202]
It would be great to have official release packages for Fedora in addition to the RHEL packages.

**Comment by rkothako** [comment]
We will keep updating the documentation when we have plans to support any new OS. But at present, we have no plans to support Fedora.

**Comment by francisrichards** [comment]
Thanks for the response rkothako, for what it is worth, I too would greatly benefit from official release packages for Fedora.  Take care.

**Comment by rigtorp** [comment]
@rkothako It should be quite easy to add Fedora builds given that you already provide RHEL builds. Switching the container image from RHEL to Fedora should be enough to produce Fedora builds.

**Comment by cmdrogogov** [comment]
+1 for this.

I've been fighting to try and get this running on FC33 all morning.   It's further complicated by the fact that the ROCm repo packages in 3.9.7 spit out patform_python dependency errors when installing (specifically rocm-smi) , but on the other Fedora DO have some rocm packages in their updates repo, but they are all out of date.

**Comment by francisrichards** [comment]
> +1 for this.
> 
> I've been fighting to try and get this running on FC33 all morning. It's further complicated by the fact that the ROCm repo packages in 3.9.7 spit out patform_python dependency errors when installing (specifically rocm-smi) , but on the other Fedora DO have some rocm packages in their updates repo, but they are all out of date.

For what it's worth this is how I got OpenCL support working on Fedora 32 and 33 with an RX 580 using AMDGPU-Pro  (My use case is Dark Table).  I still use the native amdgpu non-pro for graphics as per the documentation.
https://ask.fedoraproject.org/t/guide-install-amdgpu-pro-opencl-in-fedora-32/7929

**Comment by rigtorp** [comment]
@cmdrogogov I have a hacky way to install the CentOS packages on Fedora 33: https://rigtorp.se/notes/rocm/

**Comment by ROCmSupport** [comment]
Thanks all for the feedback.
But we do not have enough resources to validate and confirm every OS. We have definite plans to support a specific list of OSes only and we are mentioning all supported OSes in rocm docs.
RPM packages might work on other oses but we are not delivering official support at this moment.
Thank you.

**Comment by cmdrogogov** [comment]
@ROCMSupport - 

You should reconsider this, now that CentOS is effectively dead.
