### ISSUE TITLE
unable to open /dev/kfd read-write: Bad address

### ISSUE THREAD

**Issue by MohamedElsaeidy** [RadeonOpenCompute/ROCm#1205]
after Fresh install of ubuntu 20.04 and ROCm 3.7 latest until today. when verifying installing throw 
/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo
the first command dont work even when removed the (base) of conda 
my specs , acer315-42G  Ryzen 5 3500u with Vega 8 , radeon 540x 

<pre>(base) <font color="#4E9A06"><b>mohamed@acer</b></font>:<font color="#3465A4"><b>/dev</b></font>$ cd kfd
bash: cd: kfd: Not a directory
(base) <font color="#4E9A06"><b>mohamed@acer</b></font>:<font color="#3465A4"><b>/dev</b></font>$ groups
mohamed adm cdrom sudo dip video plugdev render lpadmin lxd sambashare
(base) <font color="#4E9A06"><b>mohamed@acer</b></font>:<font color="#3465A4"><b>/dev</b></font>$ ls -la /dev/kfd
crw-rw---- 1 root render 236, 0 Aug 25 21:05 <span style="background-color:#2E3436"><font color="#C4A000"><b>/dev/kfd</b></font></span>
(base) <font color="#4E9A06"><b>mohamed@acer</b></font>:<font color="#3465A4"><b>/dev</b></font>$ /opt/rocm/bin/rocminfo
<font color="#D3D7CF">ROCk module is loaded</font>
<font color="#CC0000">Unable to open /dev/kfd read-write: Bad address</font>
<font color="#D3D7CF">mohamed is member of render group</font>
<font color="#CC0000">hsa api call failure at: /src/rocminfo/rocminfo.cc:1142</font>
<font color="#CC0000">Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.</font>
(base) <font color="#4E9A06"><b>mohamed@acer</b></font>:<font color="#3465A4"><b>/dev</b></font>$ sudo /opt/rocm/bin/rocminfo
<font color="#D3D7CF">ROCk module is loaded</font>
<font color="#CC0000">Unable to open /dev/kfd read-write: Bad address</font>
<font color="#D3D7CF">mohamed is member of render group</font>
<font color="#CC0000">hsa api call failure at: /src/rocminfo/rocminfo.cc:1142</font>
<font color="#CC0000">Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.</font>
(base) <font color="#4E9A06"><b>mohamed@acer</b></font>:<font color="#3465A4"><b>/dev</b></font>$ /opt/rocm/opencl/bin/clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (3182.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 0
</pre>

**Comment by xuhuisheng** [comment]
I am afraid that rocm donot support vega8. Please refer https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support

**Comment by MohamedElsaeidy** [comment]
> I am afraid that rocm donot support vega8. Please refer https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support

> GFX8 GPUs
> "Polaris 11" chips, such as on the AMD Radeon RX 570 and Radeon Pro WX 4100
> "Polaris 12" chips, such as on the AMD Radeon RX 550 and Radeon RX 540

it have the same technology of desktop GPU , doest it mean that ROCm does not support Mobile GPUs?

**Comment by xuhuisheng** [comment]
Offically, there are a few cards can be supported by ROCm. And gfx803 (RX580) need PCIe Atomic support with both CPU and MotherBoard.

You can use `dmesg` to see whether there is error for kfd

```
$ dmesg |grep kfd
[    4.365875] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    4.371066] kfd kfd: amdgpu: added device 1002:67df

```

**Comment by MohamedElsaeidy** [comment]
@xuhuisheng 
<pre>$ dmesg |grep kfd
[    2.978417] <font color="#CC0000"><b>kfd</b></font> <font color="#CC0000"><b>kfd</b></font>: amdgpu: Allocated 3969056 bytes on gart
[    2.979235] <font color="#CC0000"><b>kfd</b></font> <font color="#CC0000"><b>kfd</b></font>: amdgpu: added device 1002:6987
[    3.382581] <font color="#CC0000"><b>kfd</b></font> <font color="#CC0000"><b>kfd</b></font>: amdgpu: Allocated 3969056 bytes on gart
[    3.382998] <font color="#CC0000"><b>kfd</b></font> <font color="#CC0000"><b>kfd</b></font>: amdgpu: added device 1002:15d8
</pre>

**Comment by xuhuisheng** [comment]
From https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/master/src/topology.c
6987 is Polaris12, 15d8 is Raven.And both cards can be added by kfd.
https://github.com/radeonopencompute/rocm said both cards are not ful support or support offically. Need amd to clarify these errors.

**Comment by MohamedElsaeidy** [comment]
@xuhuisheng  do you  think it maybe a case of switchable 2 GPUs , Vega 8 and 540X , also is there somewhere i can add the device details manually so rocm be able to identify it like the topology.c file u mentioned 
my Lexa GPU Notes

```
Architecture Codename: Arctic Islands
Codename: Polaris 12
Old Codename: Treasure
CLRX Version: GCN 1.2
Graphics/Compute: GFX8 (gfx804)
Display Core Engine: 11.2
Unified Video Decoder: 6.3
Video Compression Engine: 3.4
```

**Comment by runvnc** [comment]
I have a DeskMini A300W with Ryzen 5 2400g and Pop!OS 20.04 (almost exactly Ubuntu).  Was looking forward to using this or maybe upgrading to the new 4000 APUs as a sort of "power embedded" platform with good value that might be useful for robotics with OpenCL or HIP.

Spent multiple days trying to figure out similar issues.  After resolving several previous problems such as BIOS settings and other things, currently stuck on "/dev/kfd: Bad address".  Quite possibly just not supported on my motherboard/CPU, but I am not sure because the documentation seems ambiguous.

I have come to the conclusion that trying to use AMD for this type of parallel processing was a mistake.  I'm just going to rent a cheap Nvidia GPU online and probably eventually buy a new computer.  WiGig probably means I don't need the portability of the APU machines anyway.

**Comment by JoseVSeb** [comment]
> I have come to the conclusion that trying to use AMD for this type of parallel processing was a mistake. I'm just going to rent a cheap Nvidia GPU online and probably eventually buy a new computer. WiGig probably means I don't need the portability of the APU machines anyway.

@runvnc  That's not a feasible solution. A software bug should NEVER be bypassed using hardware change; for obvious reasons. Fixing the bug takes a few lines of code (if you're in the development of the said software), changing hardware empties your pocket pretty quick for the solution you propose. And for the most of us; it's once in a decade opportunity to buy new hardware.

**Comment by oberstet** [comment]
here is what I run into:

```
oberstet@oberstet-MS-7A40:~$ /opt/rocm/opencl/bin/clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (3186.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 0
oberstet@oberstet-MS-7A40:~$ /opt/rocm/bin/rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Bad address
oberstet is member of render group
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.
oberstet@oberstet-MS-7A40:~$ dmesg | grep kfd
[    8.954824] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    8.955566] kfd kfd: amdgpu: added device 1002:15dd
oberstet@oberstet-MS-7A40:~$ x86info
x86info v1.31pre  Dave Jones 2001-2011
Feedback to <davej@redhat.com>.

Unknown CPU family: 0x17
Unknown CPU family: 0x17
Unknown CPU family: 0x17
Unknown CPU family: 0x17
Unknown CPU family: 0x17
Unknown CPU family: 0x17
Unknown CPU family: 0x17
Unknown CPU family: 0x17
Found 8 identical CPUs
Extended Family: 8 Extended Model: 1 Family: 15 Model: 17 Stepping: 0
CPU Model (x86info's best guess): 
Processor name string (BIOS programmed): AMD Ryzen 5 2400G with Radeon Vega Graphics    

Monitor/Mwait: min/max line size 64/64, ecx bit 0 support, enumeration extension
SVM: revision 1, 32768 ASIDs, np, lbrVirt, SVMLock, NRIPSave, TscRateMsr, VmcbClean, FlushByAsid, DecodeAssists, PauseFilter, PauseFilterThreshold
Address Size: 48 bits virtual, 48 bits physical
The physical package has 8 of 16 possible cores implemented.
 running at an estimated 3.60GHz
oberstet@oberstet-MS-7A40:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
oberstet@oberstet-MS-7A40:~$ 
```

**Comment by ROCmSupport** [comment]
Hi @MohamedElsaeidy 
Thanks for reaching out.
Vega8 (mobile GPUs) not supported with ROCm at present. Please check [https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support](url)

**Comment by oberstet** [comment]
@ROCmSupport :

* the link you posted is broken
* "not supported with ROCm at present": so when will it? never?
* not supporting APUs for us means: AMD is no alternative to using Nvidia, as we need embedded (Ryzen V1000 vs XYZ)

**Comment by ROCmSupport** [comment]
Sorry for typo.
Please use https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support

**Comment by oberstet** [comment]
yes, thanks, I had been aware of this page. the page reads

> As such, they are not yet officially supported targets for ROCm.

as in "yet": when will it be? if not never, why close this issue? if never, pls say so .. thanks!

> fwiw, my personal view is: not supporting APUs, and the V1000 embedded Ryzen in particular, is a big mistake. because AMD could bring some competition to Nvidia NX. maybe. anyways, just my 2cts

**Comment by MohamedElsaeidy** [comment]
> yes, thanks, I had been aware of this page. the page reads
> 
> > As such, they are not yet officially supported targets for ROCm.
> 
> as in "yet": when will it be? if not never, why close this issue? if never, pls say so .. thanks!
> 
> > fwiw, my personal view is: not supporting APUs, and the V1000 embedded Ryzen in particular, is a big mistake. because AMD could bring some competition to Nvidia NX. maybe. anyways, just my 2cts

in addition it says it supports polaris 12 tech chips which is same one my laptop GPU so it should be working normally with just few implementation on main installing source code i guess

**Comment by konflic** [comment]
On my laptop I have Vega 8 and Radeon 540X Series (POLARIS12) and have the same issue on latest for this message Ubuntu 20.04.1 and got the same error :(

**Comment by ROCmSupport** [comment]
Hi @konflic , @oberstet and @MohamedElsaeidy 
Polaris12 and Vega8 are old cards as of today and we are not supporting them officially today. Not sure about future plans.
AMD is trying to add support for the new cards.

**Comment by oberstet** [comment]
thanks for clarification! I guess I have to look elsewhere. fwiw, I'm talking about this product https://www.amd.com/en/products/embedded-ryzen-v1000-series, which is an APU actively promoted for embedded. with the 3.6 TOPS claimed, it would place itself between Nvidia Nano (472 GOPS)  and Xavier NX (21 TOPS). leaving price and long-term availability (embedded) aside for a moment, it all boils down to software support. for embedded AI use case, the lack of ROCm means: no use ..

**Comment by hapasa** [comment]
I wonder if this issue could be happening also when there are both AMD APU, so Ryzen 5 2400G in my case, as well as discrete AMD RX 550 in the system?   

[    1.069011] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    1.069772] kfd kfd: amdgpu: added device 1002:699f
[    1.357892] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    1.358106] kfd kfd: amdgpu: added device 1002:15dd

(No a laptop in this case, but HP Pavilion Desktop).
Based on reading the installation instructions, RX 550 should be supported.

For what it is worth, PlaidML is working with AMD Pro driver, Ubuntu 20.04.1 with 5.4.0-62-generic linux.

**Comment by tingxingdong** [comment]
If  you run ROCm on an AMD APU + discrete GPU, it is recommend to disable the APU's graphics part in BIOS mode, e.g Chipset->"Integrate Graphics" --> Save and Exit -> reboot.
