### ISSUE TITLE
rocm 3.7 ubuntu package compiled against glibc version

### ISSUE THREAD

**Issue by psychocoderHPC** [RadeonOpenCompute/ROCm#1207]
I am not sure if this is the right repository to report rocm package build issues.

I updated my rocm3.5 to rocm3.7 on Ubuntu 16.04. When running clang I get the following error:

```
$ which clang
/opt/rocm-3.7.0/llvm/bin/clang
$ clang
clang: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by clang)
```

It looks like clang is build against the wrong glibc version because `libm` on Ubuntu 16.04 is not supporting GLIBC 2.27

```
$ strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.4
GLIBC_2.15
GLIBC_2.18
GLIBC_2.23
GLIBC_PRIVATE
```

System:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
```

**Comment by psychocoderHPC** [comment]
I will close this issue, I missed that Ubuntu 16.04 is not supported anymore :-( https://github.com/RadeonOpenCompute/ROCm#list-of-supported-operating-systems

**Comment by ax3l** [comment]
Thank you for documenting this!
Cross-linking docs that need an update: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu

Those still state to add `echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list`a nd have no `bionic` name variant.
But the "xenial" packages now only work on bionic and focal ;)

**Comment by Rmalavally** [comment]
Thank you for your positive feedback about AMD ROCm documentation. 

We are aware of the change from 'xenial' to 'focal' and our documentation will be updated once the changes are implemented. 

AMD ROCm Documentation Team

**Comment by ax3l** [comment]
Thank you for updating this. :sparkles:
