### ISSUE TITLE
'Unable to open /dev/kfd read-write: Operation not permitted' on Pop OS

### ISSUE THREAD

**Issue by Maculele** [RadeonOpenCompute/ROCm#1211]
Hello,

I have installed ROCm on Pop OS, but when I attempt to ~$ rocminfo i get Unable to open /dev/kfd read-write: Operation not permitted and it states that I am a member of render group

I am running Pop!_OS 20.04 LTS

**Comment by xuhuisheng** [comment]
The device /dev/kfd need video or render group, using `ls -l /dev/kfd` to check the device group, and using `groups` to check the current login user group, if not matched, do `sudo usermod -a -G video $LOGNAME`

**Comment by Maculele** [comment]
I am still having no luck. ls -l /dev/kfd gives this message:
> crw-rw----` 1 root render 238, 0 Sep  2 15:45 /dev/kfd

Groups says:  has my user name then   _adm sudo video render libvirt_

And just to be sure I re ran sudo usermod -a -G video $LOGNAME  but it did not help

I also noticed that when I ran '~$ sudo apt upgrade && install'  I got the following message right at the end

Errors were encountered while processing:
 rock-dkms
 rocm-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by krishoza** [comment]
@xuhuisheng could this launch be failing because the owner of the file `/dev/kfd` is root and not the actual user on OS.

**Comment by ROCmSupport** [comment]
Hi @Maculele 
Thanks for reaching out.
Recommend to uninstall ROCm completely and do a fresh and clean install of the latest ROCm 3.10.
Please share an update once done.
Thank you.

**Comment by ROCmSupport** [comment]
POP OS is not officially supported with ROCm.
Anyway, requesting user to try with the latest ROCm 4.0.
Thank you.

**Comment by MOLOjl** [comment]
try this:
```shell
sudo usermod -a -G video $LOGNAME
sudo usermod -a -G render $LOGNAME
sudo reboot
```

**Comment by MOLOjl** [comment]
@ROCmSupport 
you should mention this in your [guide](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#ubuntu-18-04)

**Comment by ROCmSupport** [comment]
Hi @MOLOjl 
We have it already @ https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#setting-permissions-for-groups
Thank you.

**Comment by krishoza** [comment]
> try this:
> 
> ```shell
> sudo usermod -a -G video $LOGNAME
> sudo usermod -a -G render $LOGNAME
> sudo reboot
> ```

@MOLOjl my user was already in the above mentioned group since this is one of prerequisites to install ROCm.

**Comment by luciddream-tsin** [comment]
@MOLOjl  thanks,  the reboot is very important for me!!

**Comment by QazCetelic** [comment]
> Hi @MOLOjl We have it already @ https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#setting-permissions-for-groups Thank you.

@ROCmSupport This link gives a 404.

> > try this:
> > ```shell
> > sudo usermod -a -G video $LOGNAME
> > sudo usermod -a -G render $LOGNAME
> > sudo reboot
> > ```
> 
> @MOLOjl my user was already in the above mentioned group since this is one of prerequisites to install ROCm.

I'm getting the same error, even after adding myself to the group and rebooting.

**Comment by FWDekker** [comment]
@QazCetelic I had the same issue when I was using `podman` instead of `sudo docker`. I resolved the issue by moving the image to the `root` user and launching with `sudo podman`. (You can transfer the image by first exporting with `podman save -o image.tar localhost/rocm/rocm-terminal-latest`, and then importing with `sudo podman load -i image.tar`.) After that, `sudo rocminfo` worked fine. I also got `rocminfo` (without `sudo`) working by running `sudo podman` with the additional option `--group-add 107` (which corresponds to the `render` group; using `--group-add render` didn't work).

**Comment by jiapei100** [comment]
I got the same issue:

1. I have a AMD Radeon RX 580 GPU
```zsh
➜  ~ lspci -nnk | grep -A3 -i vga
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7)
	Subsystem: XFX Pine Group Inc. Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1682:c580]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

2. However, the device is **NOT** even able to be detected.

```
➜  ~ sudo clinfo
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3614.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   
  clCreateContext(NULL, ...) [default]            No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
```

3. And, `lsmod | grep kfd` replied me **NOTHING**
```zsh
➜  ~ lsmod | grep kfd
```

Can anybody please give me a hand?

My system configuration:
```zsh
➜  ~ neofetch
            .-/+oossssoo+/-.               lvision@lvision-DX4860 
        `:+ssssssssssssssssss+:`           ---------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.6 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: MZ-B75-S 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-117-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 15 hours, 30 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2038 (dpkg), 13 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1360x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel i7-3770 (8) @ 3.900GHz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 1360MiB / 32050MiB 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/                              
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

Cheers
