### ISSUE TITLE
E: Unable to locate package cxlactivitylogger

### ISSUE THREAD

**Issue by tugot17** [RadeonOpenCompute/ROCm#1213]
**Platform: Ubuntu 20.04.01 LTS**

**Problem**
I try to install `tensorflow` as described in the official [tutorial](https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#amd-rocm-tensorflow-v2-2-0-beta1-release) `Rocm` seems to be installed properly but I have the problem follwing the steps. 

After command `sudo apt install rocm-libs miopen-hip cxlactivitylogger rccl` I get `E: Unable to locate package cxlactivitylogger`.

What may be the reason or how to fix it?

**Comment by xuhuisheng** [comment]
Please ignore the cxlactivitylogger. I installed tensorflow_rocm success with it.

**Comment by ROCmSupport** [comment]
Hi @tugot17 
Thanks for reaching out.
cxlactivitylogger is no more required and we updated the docs accordingly.
Thank you.
