### ISSUE TITLE
 tensorflow-rocm-enhanced installed, but training uses CPU only

### ISSUE THREAD

**Issue by ffleader1** [RadeonOpenCompute/ROCm#1217]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc1-2368-gc1ffa3658f 2.3.0
- Python version: 3.7.9
- GPU model and memory: Rx 580

The GPU does not get used at all. For example, with ai-benchmark 0.1.2, which can be installed with: `pip install ai-benchmark`

```
from ai_benchmark import AIBenchmark
benchmark = AIBenchmark(use_CPU=False, verbose_level=1)
results = benchmark.run()
```

GPU load 0% during the whole process

```
========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr   SCLK     MCLK    Fan     Perf  PwrCap  VRAM%  GPU%  
0    35.0c  51.191W  1300Mhz  300Mhz  16.86%  auto  152.0W    6%   0%    
================================================================================
==============================End of ROCm SMI Log ==============================
```

**Comment by xuhuisheng** [comment]
I had met errors on tf, when tf met loading so error, then it fail to cpu. please check the output if there is any error or warning logs.

**Comment by ffleader1** [comment]
> I had met errors on tf, when tf met loading so error, then it fail to cpu. please check the output if there is any error or warning logs.

That sounds reasonable, but where can O find the loading logs? I mean all the imports are fine, no err so I am not sure where to look.

**Comment by baryluk** [comment]
I got it working with `tensorflow-rocm`.  I am on AMD Fury X (FIJI, GFX8), 4GB VRAM.

Not sure what is `tensorflow-rocm-enhanced`, as the pypi page doesn't provide much info about it.

Most of the benchmarks in the AIBenchmark are rather short, so it might be hard to see the GPU high often. In my expirience a majority of time is spend in the host waiting for clang and linker to finish building GPU kernels, then they execute in a second or two, but VRAM is usually pretty high (close to 100%). In fact one of the benchmarks in the AIBenchmark loads my system so high that xorg and amdgpu driver crashes.

Could you provide the output of the `benchmark.run()` ?

**Comment by ffleader1** [comment]
Sorry. As soon as I know Tensorflow-DirectML was released one or two week ago, I just wiped that Ubuntu partition from my PC and use Windows for training. I know the speed is basically 1/5 Rocm, but after spending 2 days of pulling my hair out while installing/uninstalling the various version of Ubuntu and Rocm, but still come up short, I decided to go with a solution that "just work". This is just my hobby so I do not mind much.

Anyway, about this problem, as you can see, in your code
```
*  TF Version: 2.3.1
*  Platform: Linux-5.7.0-1-amd64-x86_64-with-glibc2.29
*  CPU: N/A
*  CPU RAM: 126 GB
*  GPU/0: Fiji [Radeon R9 FURY / NANO Series]
*  GPU RAM: 3.7 GB
*  CUDA Version: N/A
*  CUDA Build: N/A
````

You have the GPU line, but I don't. Mine stopped basically at CPU RAM. That's why I am 99% positive that the rocm install process messed up some point and failed to detect my GPU. Running this benchmark on Windows on tensorflow-DirectML does indeed show the GPU.

**Comment by baryluk** [comment]
@ffleader1 Thanks for extra info.

Just for completeness, what CPU and motherboard are you using?

It is good to inspect for example what `/opt/rocm-3.8.0/bin/rocminfo` says, i.e. if it detects everything correctly.

**Comment by ffleader1** [comment]
@baryluk Oh. A R5 3600X with a MSI MPG X570 Gaming plus

**Comment by baryluk** [comment]
@ffleader1 Thanks. That should work then. I guess something with installation process was wrong probably.

**Comment by ROCmSupport** [comment]
Hi @ffleader1 
Can you please try with ROCm 3.10 on the same machine and update.
Request to close this issue, if it works in 3.10.
Thank you.

**Comment by ffleader1** [comment]
> Hi @ffleader1
> Can you please try with ROCm 3.10 on the same machine and update.
> Request to close this issue, if it works in 3.10.
> Thank you.

I did format the OS out of my disks partition so I no longer keep it. This is probably just a single problem on my end, so please close it. Thank you.

**Comment by ROCmSupport** [comment]
Thanks @ffleader1 for the update.
Closing it now.
Thank you.
