### ISSUE TITLE
Test for x86_64 architecture before including platform specific headers in ROCm

### ISSUE THREAD

**Issue by sameershende** [RadeonOpenCompute/ROCm#1222]
amd64 platform is assumed in rocm_bandwidth_test/hsatimer.hpp and it includes a platform specific file without guards to check for the platform: 
#include <x86intrin.h>

It also uses __rtdscp and when an alternative timestamp function is used with guards elsewhere in the code. This check should be performed at other locations where __rtdscp is used. 
In rocm-smi, DEBIAN/control also hardcodes Architecture: amd64 in DEBIAN/control

**Comment by baryluk** [comment]
Just remove the use of `rtdscp`, and use `gettimeofday(2)`, or `clock_gettime(2)` with `CLOCK_MONOTONIC`. Unless it is trying to measure latency of super low values (<500ns), there is no need for rtdscp. As the name suggest the test measures bandwidth.

I didn't test ROCm on non-amd64 arch, but I am definitively going to (aarch64, and possibly power9).

**Comment by ROCmSupport** [comment]
Thanks @sameershende for reaching out.
I will check and get back asap on this issue.
Thank you.

**Comment by rerrabolu** [comment]
All the repo for rocm_bandwidth_test [](https://github.com/RadeonOpenCompute/rocm_bandwidth_test) has an update in this regard.

Implementation has moved away from using __rtdscp timers. You can find the change submitted a while ago - eae85ad52d2eb7c336a9198542a5.

For one or more reasons this change was not picked up by public release of ROCm stack.

**Comment by ROCmSupport** [comment]
Thanks @rerrabolu for the update.
Can you please make sure that new change will be picked up for the next upcoming ROCm release?
Thank you.

**Comment by cfreehill** [comment]
@sameershende Thanks for the feedback.

> In rocm-smi, DEBIAN/control also hardcodes Architecture: amd64 in DEBIAN/control

I had to do some research on this. Mainly, I'm looking at this: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture.  I'm not aware of and don't recall  any CPU architecture specific code in the rocm_smi library code. Therefore, I think "amd64" should be changed to "any". Let me know if you disagree.

**Comment by ROCmSupport** [comment]
Hi @sameershende 
Can you please check this with the latest ROCm 4.1 and update.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @sameershende 
As the changes are merged, request you to check on the latest 4.2 code.
Thank you.

**Comment by ROCmSupport** [comment]
As there is no response for more than a month, considering that issue is fixed.
Am closing this now as the changes are already pushed.
Thank you.
