### ISSUE TITLE
Remove hardcoded values for NBIT and NBITSTR based on checks for x86_64 only in rocminfo

### ISSUE THREAD

**Issue by sameershende** [RadeonOpenCompute/ROCm#1223]
rocminfo source code sets:

x86_64 specific!
## Extend Compiler flags based on Processor architecture
if ( ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64" )
  set ( NBIT 64 )
  set ( NBITSTR "64" )
  set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64  -msse -msse2" )
elseif ( ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86" )
  set ( NBIT 32 )
  set ( NBITSTR "" )
  set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32" )
endif ()

This makes it harder to port the tool to ppc64le which is 64bit but needs something like:

## Extend Compiler flags based on Processor architecture
if ( ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64" )
  set ( NBIT 64 )
  set ( NBITSTR "64" )
  set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64  -msse -msse2" )
elseif ( ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86" )
  set ( NBIT 32 )
  set ( NBITSTR "" )
  set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32" )
elseif ( ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "ppc64le" )
  set ( NBIT 64 )
  set ( NBITSTR "64" )
  set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64 " )
endif ()

Other architectures that are 64 bit wide (aarch64) may also be affected by this code that makes assumptions based on amd64 architecture.

**Comment by ROCmSupport** [comment]
Thanks @sameershende for reaching out.
I will talk to respective component owners and get back asap.
Thank you.

**Comment by ROCmSupport** [comment]
This requirement is already fulfilled and the latest HSA code has all the changes.
Request you to verify with the latest ROCm code.
Thank you.
