### ISSUE TITLE
OpenCL support for CPU?

### ISSUE THREAD

**Issue by BA8F0D39** [RadeonOpenCompute/ROCm#1224]
https://rocmdocs.amd.com/en/latest/Programming_Guides/Opencl-optimization.html?highlight=CPU#using-the-cpu

ROCm says it has OpenCL support for CPU but when I run clinfo on my Ryzen 7 1700X machine there isn't any devices.

So how do I get OpenCL to work on CPU?

**Comment by Rmalavally** [comment]
Thank you for reaching out to us.

We will  investigate the issue and get back to you once we hear from our development team.

AMD ROCm Documentation Team

**Comment by boxerab** [comment]
CPU support means that the library will support Ryzen CPU + AMD GPU. There is no OpenCL runtime for the CPU, so if you don't have a GPU, you will not see any devices.

**Comment by BA8F0D39** [comment]
@boxerab besides OpenCL, what other frameworks does ROCm support on the CPU only? Like does it support OpenMP or HIP? The documentation is very vague on what ROCm exactly provides.

**Comment by boxerab** [comment]
It certainly supports HIP. That is quite well documented. For OpenMP, I am not sure, but I found this:

https://github.com/ROCm-Developer-Tools/aomp

**Comment by ROCmSupport** [comment]
Hi @BA8F0D39 
I am closing this issue as the relevant info for OpenCL support for ROCm is shared.
Recommed to open a new ticket, for any new issues.
Thank you.
