### ISSUE TITLE
Fails to download source for 3.8.x

### ISSUE THREAD

**Issue by gggh000** [RadeonOpenCompute/ROCm#1225]
The following url claims, to download the 3.8.x but it does not work:

https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#getting-the-rocm-source-code
...
Downloading the ROCm Source Code
The following example shows how to use the repo binary to download the ROCm source code. If you choose a directory other than ~/bin/ to install the repo, you must use that chosen directory in the code as shown below:

mkdir -p ~/ROCm/
cd ~/ROCm/
~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-3.8.x
repo sync
...

run from linux terminal failed:
Downloading manifest from https://github.com/RadeonOpenCompute/ROCm.git
fatal: Couldn't find remote ref refs/heads/roc-3.8.x
manifests:
fatal: Couldn't find remote ref refs/heads/roc-3.8.x

fatal: Couldn't find remote ref refs/heads/roc-3.8.x
manifests:
fatal: Couldn't find remote ref refs/heads/roc-3.8.x

**Comment by Rmalavally** [comment]
Thank you for reaching out. 

Refresh the browser and try again.

 If you are unable to find the information you need, please contact us.

AMD ROCm Documentation Team

**Comment by gggh000** [comment]
not sure waht changed as a browser refresh but it is appearing to work. thx.,

**Comment by Rmalavally** [comment]
Thank you for the positive feedback. We are glad it worked!!

AMD ROCm Documentation Team

**Comment by baryluk** [comment]
Works for me. Maybe github was down for a moment?

**Comment by gggh000** [comment]
thx, i think this can be closed.
