### ISSUE TITLE
Does powerplay still work in ROCm 3.8?

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1228]
Before it was possible to undervolt or otherwise tweak the voltage/frequency with powerplay, e.g. by writing to 
/sys/class/drm/card0/device/pp_od_clk_voltage

(to enable PP one had to boot with amdgpu.ppfeaturemask=0xffffffff or similar)

Did ROCm 3.8 change the way PP works? is it still possible to tweak voltage/frequency -- in a different way / how?

**Comment by valeriob01** [comment]
This is how I set frequency, maybe it still works?

```
/opt/rocm-3.3.0/bin/rocm-smi --resetprofile
/opt/rocm-3.3.0/bin/rocm-smi --setsclk 8
/opt/rocm-3.3.0/bin/rocm-smi --setmclk 2
/opt/rocm-3.3.0/bin/rocm-smi --autorespond y --setoverdrive 2
/opt/rocm-3.3.0/bin/rocm-smi --autorespond y --setmemoverdrive 10

```

**Comment by kentrussell** [comment]
PP has been undergoing changes, but it should still be possible to adjust the voltages and frequency. What do you get when you cat the pp_od_clk_voltage file?

**Comment by ROCmSupport** [comment]
Hi @preda 
It should work as the same way you tried.

**Comment by preda** [comment]
Yes, I think everything is fine and it works, it must have been that I forgot to add "amdgpu.ppfeaturemask=0xffffffff" to /etc/default/grub

**Comment by ROCmSupport** [comment]
Thanks @preda for the update.
