### ISSUE TITLE
Debian bullseye and libgcc deps

### ISSUE THREAD

**Issue by gfwp** [RadeonOpenCompute/ROCm#1230]
Hi,

is there a way to circumvent the deps on libgcc-7 and to be able to run at least the rocm-dev version on Bullseye/Sid?

Is an hard world. For the best R support I need testing or Sid. For the best tensorflow  and keras some stable (but way older) Ubuntu. I'd say that keeping an up to date Debian Sid version would give you two birds with a single stone.

Regards

gfwp

**Comment by baryluk** [comment]
Yes, there is a workaround.

Download the deb package for rocm-dev. Unpack it, edit control file, and change / remove dependency on libgcc-7. Then repack using `dpkg-buildpackage`, and install using `dpkg -i`. It did work for me, and I didn't spotted any actual binary having issues.

See https://github.com/RadeonOpenCompute/ROCm/issues/1125

**Comment by rkothako** [comment]
Hi @gfwp 
Can you please close this ticket if the above workaround helps you.
Please share an update. Thank you.
