### ISSUE TITLE
Hardware support URL in README is broken

### ISSUE THREAD

**Issue by doctorcolinsmith** [RadeonOpenCompute/ROCm#1235]
In the README.md, "Hardware and Software Support" section (https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support), the URL at the end for the detailed list of supported hardware is broken.  It just redirects to the main ROCm docs page.

**Comment by Rmalavally** [comment]
Thank you for your feedback. The URL is now corrected. You can access more information about AMD Graphics Processing Units at:

https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units

AMD ROCm Documentation Team

**Comment by rkothako** [comment]
Thanks @doctorcolinsmith 
As the issue is fixed now, we request you to close this ticket.
