### ISSUE TITLE
opencl .so file missing from post 3.5 installs

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#1240]
I am running Ubuntu 18.04.5 with 5.4 kernel. I have had ROCm installed since version 2.
Whenever I upgrade ROCm since 3.5, the opencl .so files remain in my 3.5 folder.
 
So, even with 3.8, I have to keep 3.5 install folder around to be able to use OpenCL.

Is this correct? For a fresh 3.8 install, which library is used for enabling OpenCL ?

**Comment by baryluk** [comment]
Be more specific. What packages you installed, what versions, which distro. Are you using deb files using apt, or rpm / yum?

The library is definitively there:

```
root@debian:~# dpkg -S libamdocl64.so
rocm-opencl3.8.0: /opt/rocm-3.8.0/opencl/lib/libamdocl64.so
root@debian:~#
```

same for clinfo, etc.

**Comment by boxerab** [comment]
@baryluk thanks! I tried your absolute path fix to the icd file, and now I can run regular `clinfo`, not the one on the ROCm directory.

**Comment by boxerab** [comment]
I ended up doing a fresh install, and the problem has disappeared.
