### ISSUE TITLE
Large OpenCL performance regression in 3.8 for RX 470 card

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#1241]
Ubuntu 18 w/ 5.4.0-48 kernel.
RX 470 GPU
Skylake CPU

Under 3.5, my kernels would take 13.8 ms to complete. With latest 3.8 upgrade, 
time increases to 17.8 ms. So, around 30% slower.

**Comment by baryluk** [comment]
Are you using the upstream amdgpu, or the `rocm-dkms` driver?

Could you provide some minimal code example (C/C++ code + embeded kernel)? Smaller the better.

**Comment by boxerab** [comment]
Thanks. Does rocm with with amdgpu ? How can I tell which driver is being used ?

**Comment by baryluk** [comment]
It should work with amdgpu just fine with your kernel. I am using amdgpu with kernel 5.6, but also used it with earlier kernels like yours.

Try:

`sudo modinfo amdgpu | egrep 'filename|vermagic'`
`sudo dkms status`
`sudo dpkg -l rocm-dkms`
`sudo zgrep 'Initialized amdgpu' /var/log/kern.log*`

**Comment by boxerab** [comment]
@baryluk thanks. What happened with my upgrades was strange:

After 3.5, I upgraded with each point release, but the performance of my kernels remained the same. However, 
upgrades 3.6, 3.7 and 3.8 did not install an opencl directory in the release folders, so I continued using the 3.5 directory and the 3.5 .so library.

Finally, I did a fresh install of the OS with 3.8, and then the performance went down.

**Comment by ROCmSupport** [comment]
Hi @boxerab 
Can you please share the code if its opensource and let us know the steps to reproduce the problem too.
Thank you.

**Comment by boxerab** [comment]
@ROCmSupport thanks, unfortunately this is not open source code.

**Comment by ROCmSupport** [comment]
Hi @boxerab 
We need some sample piece of code to verify locally and understand the problem.
Hope you got my point.

**Comment by baryluk** [comment]
@boxerab Without some source code for the kernel that shows these performance issues, there is nothing anybody can do to help you.

**Comment by ROCmSupport** [comment]
Hi @boxerab 
Recommend to close this issue, if you are not able to share execution steps/process to reproduce the problem.
Thank you.

**Comment by boxerab** [comment]
I will at least identify which version of ROCm causes the slowdown.

**Comment by ROCmSupport** [comment]
Hi @boxerab 
Until we validate/verify with the code, we are not in a position to understand and fix the issue.
Hope you got it.
Thank you.
