### ISSUE TITLE
ROCm on Debian Bullseye

### ISSUE THREAD

**Issue by gfwp** [RadeonOpenCompute/ROCm#1243]
Hi folks,

after fixing the deps I got ROCm running on my Debian Bullseye. Tensorflow works. But I have this error with the
rocm-smi tool

WARNING: GPU[0]	: Unable to read /sys/class/drm/card0/device/gpu_busy_percent

Any Idea?

Best regards

Giorgio

**Comment by gfwp** [comment]
Sorry for the duplicate (see below). I cannot erase it.

**Comment by gfwp** [comment]
Actually /opt/rocm/bin/rocm-smi is root:root owned with 444 permissions

**Comment by baryluk** [comment]
You need to provide more details.

1) Version of rocm-smi package
2) Kernel version
3) Do you use rocm-dkms or not (rocm amdgpu custom driver, or the upstream driver)
4) GPU used
5) Exact path and parameters used by your invokation of rocm-smi

I have rocm-smi3.8.0 ( version 1.0.0-204-rocm-rel-3.8-30-g08ebddd ) working on vanilla upstream amdgpu driver. It shows a lot of info just fine. It has no other dependencies other than python and kernel.

It should work just fine from both root and non-root users.

**Comment by ROCmSupport** [comment]
Hi @gfwp 
Thanks for reaching out.
Please help us with more data points as @baryluk mentioned already.
Else request you to close this issue as its open around 50 days.

**Comment by streamhsa** [comment]
Closing this as there is no update from reporter for a long time.
Request reporter to open a new issue, if the same/new occurs.
Thank you.
