### ISSUE TITLE
rocm-smi deb package could Suggests: sudo

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1245]
Very low prio, but just small suggestion.

`rocm-smi` only requires `Depends: python3`, and nothing else (I checked the source and indeed that is true!), and that is awesome.

But setting things require running as root, or the scripts does `execvp` to re-execute using `sudo`.

So I think it would make sense to add this to control file: `Suggests: sudo`  as a non-strong dependency, and it enhanced the script, but is not required in any sense.

**Comment by rkothako** [comment]
Thanks @baryluk 
I am not sure why do we need sudo for rocm-smi.
Can you please elaborate your issue.

**Comment by rkothako** [comment]
sudo is required to set any settings.
Normally we relaunch as sudo if there are any issues. But we can't make it a dependency in the packaging, unfortunately, we just have to run it as sudo if we want to change anything.
Hope this helps.

**Comment by baryluk** [comment]
Just added `Suggests: sudo` to the debian package. It is not a dependency, but a weak dependency. It will not break anything. On Ubuntu, sudo is usually installed by default, but it is not the case on Debian and derivatives for example.

**Comment by rkothako** [comment]
Hi @baryluk 
We do not wish to recommend sudo for any kind of rocm operations. Ideally all functions should work without sudo.
There are/may be some cases where some times, things work with sudo only. In those cases, users definitely try with sudo only.

Anyway I will once again check with component owner and update on this.
Thank you.

**Comment by rkothako** [comment]
For suggests/requires/depends, these need to be packages that might not be installed. Since sudo is always installed, the only way someone would see that we're suggesting sudo is by reading the packaging (and almost no one ever does that). And since any system that doesn't have sudo installed would be broken, it's inclusion in the requires/suggests section would not be any different than the SMI currently is. Plus, it's not required for simple monitoring, it's only needed for changing settings, so there's that side of things as well

**Comment by baryluk** [comment]
@rkothako sudo is not always installed at all. I have a system with no sudo.

Please add `Suggests: sudo`. It is simple as that.

**Comment by kentrussell** [comment]
@baryluk I had not seen "Suggests: sudo" in the wild before, but I see it in a few spots now that you've inspired me to take a look. I honestly hadn't considered that there would be many systems running ROCm where they would not have sudo, but I'll see if we can make that change.

**Comment by kentrussell** [comment]
We have merged this request internally and are tracking it to be resolved in ROCm 4.1

**Comment by ROCmSupport** [comment]
Hi @baryluk 
Issue is fixed with 4.1 code. Can you please check and update asap.
Thank you.

**Comment by baryluk** [comment]
Fixed. Thank you.

**Comment by ROCmSupport** [comment]
Thanks @baryluk for the closure.
