### ISSUE TITLE
No folder opt/rocm/opencl 

### ISSUE THREAD

**Issue by WuerfelDev** [RadeonOpenCompute/ROCm#1250]
I have rocm 3.8 installed but there is no folder opencl. There is however a opencl folder in  /opt/rocm3.5.0
Is there a link missing or did something go wrong with my 3.8 version?

**Comment by xuhuisheng** [comment]
AMD said there is mutiple versions installation issue after ROCm-3.3,  just likes your described path mislink.
They suggest us uninstall old version ROCm before install new version.

**Comment by pramenku** [comment]
Please clean uninstall older driver and fresh install.
