### ISSUE TITLE
Any plans to support Radeon Pro W5000 series?

### ISSUE THREAD

**Issue by nikAizuddin** [RadeonOpenCompute/ROCm#1251]
I can't see any Radeon Pro W5000 series in Section [Hardware and Software Support](https://github.com/RadeonOpenCompute/ROCm/tree/0bcae510a3521e135b121e1e01d1e3abe30c1a24#hardware-and-software-support). Is there any plan to support these GPUs?

**Comment by rkothako** [comment]
Hi @nikAizuddin,
We still don’t have definitive plans for supporting NAVI series of Hardware in this year.

Though its not supported officially, you can still give a try.

**Comment by rkothako** [comment]
Hi @nikAizuddin, Request to close this ticket as per above comments.
Thank you.

**Comment by nikAizuddin** [comment]
> We will inform once we add support for NAVI series of cards.

Will this include Radeon Pro W5000 series? Or only RX6000 and later?

**Comment by rkothako** [comment]
Hi @nikAizuddin 
When we start supporting NAVI series of cards, we will clearly mention all supported cards/series too(based on support and availability of cards by that time).
