### ISSUE TITLE
Can't add repository key of rocm in ubuntu 20.04

### ISSUE THREAD

**Issue by AtulPremNarayan** [RadeonOpenCompute/ROCm#1254]
hello rocm team 
plz help, the terminal is showning 

`wget -q -O - http://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
gpg: invalid key resource URL '/tmp/apt-key-gpghome.KMH3OusvRn/home:manuelschneid3r.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 7
gpg:       skipped new keys: 7
`

**Comment by xuhuisheng** [comment]
try `wget -q -O - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -`

**Comment by AtulPremNarayan** [comment]
> try `wget -q -O - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -`

thanks, 
but its still same

**Comment by ableeker** [comment]
That first wget should work, it uses the new location of the ROCm key. As a matter of fact, it does work on my computer. The error doesn't seem to point to an issue with the ROCm key, but to other keys. People have mentioned that the manuelschneid3r may have expired. That one may have to be updated. I wonder if the ROCm key hasn't been added after all. What does 'apt-key list' show? If it's showing the ROCm key, it most likely has added the key successfully, and it may be complaining about other keys.

**Comment by rkothako** [comment]
Hi @AtulPremNarayan 
Request you to close this issue, if not reproduced.
Thank you.

**Comment by streamhsa** [comment]
Closing this issue as there is no response from reporter for a long time.
Request @AtulPremNarayan to open a new issue if there is still a problem.
