### ISSUE TITLE
GCN disassembler tools

### ISSUE THREAD

**Issue by lscat11** [RadeonOpenCompute/ROCm#1258]
Hi, recently I wanted to disassemble a kernel binary file *.co into assembly code *.s. I have tried the tools listed in [https://rocmdocs.amd.com/en/latest/Programming_Guides/gcn-assembler.html](https://rocmdocs.amd.com/en/latest/Programming_Guides/gcn-assembler.html), but it seems that these tools could not generate a complete assembly code file. So, does ROCm provide such a disassembler tool?

**Comment by seesturm** [comment]
Don't know such a tool. llvm-objdump can show disassembly, but cannot produce source file for (re-)assembly.

Only known method for producing *.s files known to me is setting environment variables before running OpenCL/HIP application according to #726 
```
export KMDUMPISA=1
export AMD_OCL_BUILD_OPTIONS_APPEND="-save-temps -g"
```
