### ISSUE TITLE
Support Ubuntu 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by Bengt** [RadeonOpenCompute/ROCm#1263]
ROCm has supported Ubuntu 20.04 since release 3.8 (See: <https://github.com/RadeonOpenCompute/ROCm/issues/1074>). ROCm surely aims to extend support to the most relevant versions operating system versions. Hence, the next regular Ubuntu release is the next logical step towards this goal. Ubuntu 20.10 is due to be released tomorrow (See: [Release Notes](https://discourse.ubuntu.com/t/groovy-gorilla-release-notes/15533)). Now is a good time to start the effort to add it to the supported operating system versions.

**Comment by Bengt** [comment]
Here is a user falsely expecting that there is support for Ubuntu 20.10: https://github.com/RadeonOpenCompute/ROCm/issues/1188#issuecomment-699754544

**Comment by xuhuisheng** [comment]
I tested rocm-3.8 on ubuntu-20.10 with upstream kernel 5.8 /dev/kfd, worked fine.

**Comment by Bengt** [comment]
Thanks for that information, @xuhuisheng. So supporting Ubuntu 20.10 should not be too much effort.

**Comment by xuhuisheng** [comment]
> Here is a user falsely expecting that there is support for Ubuntu 20.10: [#1188 (comment)](https://github.com/RadeonOpenCompute/ROCm/issues/1188#issuecomment-699754544)

@Bengt I have to clarify myself, that I know the ubuntu-20.10 is not supported by ROCm officially. Just want to try ROCm on kernel-5.8, seems it could work properly.  I can run small examples like mnist on tensorflow-rocm / pytorch.

AMD said that the upstream kernel driver after kernel-5.6 could use 15/16 system memory, so it is good news to use ROCm on ubuntu-20.10 with kernel-5.8 built in kernel driver. Then we neednot install rocm-dkms manually.

And sources could be compiled successly only with small modifies, because of the gcc10.  Ubuntu-20.04.2 maybe released early next year. So I think it wont be a big problem for future upgrades.

**Comment by Ruedii** [comment]
There was a single change to the instructions needed regarding the addition of a "render" group in Ubuntu 20.10 

It would be ideal to list the Ubuntu versions separately in the distro listing.  Even if the packages are the same, this would provide quick ways to create patched packages for patches.  This would also open the doorway for sharing package trees for Ubuntu, Debian and other Debian Derivatives.

**Comment by YifeiLuDublin** [comment]
Ubuntu 20.04 was offcially supported on ROCm 3.7 in Sepetember, 5 months after the Ubuntu 20.04 release. So considering none LTS Ubuntus only have 9 months support, it will be very resource consuming for AMD to do so.

**Comment by Bengt** [comment]
@YifeiLuDublin Thanks, for raising the point, that it can be laborious to support many operating system versions. As it turns out, there is but very little effort necessary to support Ubuntu 20.10 since 20.04 is supported already and the differences are only minor. On the flip side, supporting regular Ubuntu releases like 20.10 might actually save some effort, because it makes the step towards supporting LTS releases smaller. Supporting LTS versions has been an issue in the past. For example, supporting Ubuntu 20.04 LTS was delayed by 4 months. See https://github.com/RadeonOpenCompute/ROCm/issues/1074#issuecomment-716169937

**Comment by rkothako** [comment]
Hi @YifeiLuDublin, @xuhuisheng , @Bengt , @Ruedii 
ROCm officially supports LTS versions of Ubuntu only.
All other versions(other than LTS) might work with ROCm but there will not be any official support.
Hope this clarifies.

**Comment by xuhuisheng** [comment]
@rkothako I understand that the offcial supporting will cost much.
Will we provide a unoffical supporting page, like this version is not supported offically, but it may run successfully on yourself risk. In other word, could AMD allow community driven version. Just like, there is no supporting on ROCm-3.9.0 with gfx803. Could I provide community version for gfx803?

**Comment by baryluk** [comment]
@xuhuisheng It is up to you. You can compile rocm from sources, or use packages for 20.04 for example. It doesn't take much to make them work. If you want to provide something like unofficial PPA for Ubuntu 20.04 you can.

**Comment by Bengt** [comment]
@rkothako You sound like you are associated with AMD. Are you speaking on their behalf? Otherwise, please quote them.

@xuhuisheng Please stay on topic. GFX803 is discussed before: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/479

@baryluk Yes, I can confirm that using 20.04 packages works. I have recently upgraded my workstation to Ubuntu 20.10 and can run Tensorflow-ROCm on the included 5.8 Kernel without any issues so far. I followed to the official installation instructions aside from skipping rocm-dkms.

**Comment by rkothako** [comment]
Hi @Bengt, Yes, I am sharing the information from AMD side.

**Comment by Bengt** [comment]
@rkothako Alright then, you denying support for Ubuntu 20.10 (on AMD's behalf) settles the issue I was having with ROCm. I am sorry to hear that there will be no support, since there is obviously demand for it and supporting 20.10 should take very little effort from AMD's side. Anyways, thanks for the clarification. I think we can close this issue and quote your statement here, if and when the request arises again.

Personally, I will continue using ROCm under the regular releases of Ubuntu. I will however have a hard time recommending using ROCm in the future. Using an unsupported operating system version is nothing I can recommend friends and colleagues and since I will no longer use the supported long term release of Ubuntu, I will no longer be able to vouch ROCm it working fine. I am very sorry about that, because I think ROCm is awesome and would like to spread its use whenever I get the chance.
