### ISSUE TITLE
monitor turn off after start tensorflow training

### ISSUE THREAD

**Issue by mrmoein** [RadeonOpenCompute/ROCm#1270]
hello 
when i try train my model , screen turn off and get no signal and monitor go to sleep mode

ryzen 5 2600
rx 580
ubuntu 20.04
kernel 5.4

Is there a log file?
idk what to do!

**Comment by xuhuisheng** [comment]
ROCm-3.7.0+ may halt the gfx803 gpu. Could you have a try with ROCm-3.5.1?
Please refer: https://github.com/RadeonOpenCompute/ROCm/issues/1265

**Comment by mrmoein** [comment]
> ROCm-3.7.0+ may halt the gfx803 gpu. Could you have a try with ROCm-3.5.1?
> Please refer: #1265

i think 3.8
fresh install in ubuntu

**Comment by mrmoein** [comment]
> ROCm-3.7.0+ may halt the gfx803 gpu. Could you have a try with ROCm-3.5.1?
> Please refer: #1265

i downgrade to 3.5.1 (reinstall os and fresh install everything) but problem still exist :(

**Comment by rkothako** [comment]
Hi @mrmoein 
Thanks for the issue. Looks like its an environmental issue.
Can you please share detailed steps to reproduce the issue.
Thank you.

**Comment by mrmoein** [comment]
@rkothako 
i am new in linux (one year experince) and machine learning (just started), Maybe I am installing wrong

### my installing steps:

this is my fresh install (kernel changed):
> System:    Host: moein-pc Kernel: 5.8.0-25-generic x86_64 bits: 64 Desktop: Cinnamon 4.6.7 Distro: Linux Mint 20 Ulyana 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME B450M-A v: Rev X.0x serial: <superuser/root required> 
           UEFI: American Megatrends v: 2203 date: 07/28/2020 
CPU:       Topology: 6-Core model: AMD Ryzen 5 2600 bits: 64 type: MT MCP L2 cache: 3072 KiB 
           Speed: 1559 MHz min/max: 1550/3400 MHz Core speeds (MHz): 1: 1540 2: 1556 3: 1546 4: 1546 5: 1553 6: 1553 7: 1554 
           8: 1547 9: 1544 10: 1549 11: 1545 12: 1547 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] driver: amdgpu 
           v: kernel 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.38.0 5.8.0-25-generic LLVM 10.0.0) v: 4.6 Mesa 20.0.8 
Audio:     Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.8.0-25-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp7s0 state: up speed: 100 Mbps duplex: full mac: 0c:9d:92:c7:30:53 
Drives:    Local Storage: total: 2.05 TiB used: 270.44 GiB (12.9%) 
           ID-1: /dev/sda vendor: Western Digital model: WD20EZRZ-22Z5HB0 size: 1.82 TiB 
           ID-2: /dev/sdb vendor: Silicon Power model: SPCC Solid State Disk size: 238.47 GiB 
Partition: ID-1: / size: 58.04 GiB used: 15.27 GiB (26.3%) fs: ext4 dev: /dev/sdb5 
           ID-2: /home size: 537.81 GiB used: 255.14 GiB (47.4%) fs: ext4 dev: /dev/sda4 
Sensors:   System Temperatures: cpu: 32.8 C mobo: N/A gpu: amdgpu temp: 36 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 1202 
Info:      Processes: 337 Uptime: 2h 33m Memory: 15.63 GiB used: 2.29 GiB (14.7%) Shell: bash inxi: 3.0.38 

note: same problem in ubuntu 20.04 with kernel 5.4

i install rocm from this guid => [https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu)

> /opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo

seems fine and work
also `rocm-smi` work but some python errors display befor results

i make a virtual environment with pycharm and follow this 3 steps from this link:
[https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#amd-rocm-tensorflow-v2-2-0-beta1-release](https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#amd-rocm-tensorflow-v2-2-0-beta1-release)

after install tensorflow i run this script:

> import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

and the result is => Num GPUs Available:  1

after that i run this commend:
`cd ~ && git clone -b cnn_tf_v1.15_compatible https://github.com/tensorflow/benchmarks.git
python ~/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model=resnet50`
and after few seconds (when training start) screen turn off
same problem when i train my model

i try ssh to my pc from another one and run again the script:
> import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

but this time i receive => Num GPUs Available:  0

**Comment by rkothako** [comment]
Thanks @mrmoein 
Issue is not reproducible with gfx9 devices. Looks like specific to gfx8 devices.

**Comment by mrmoein** [comment]
i still can't fix the problem! where is the log file? is it exist?

**Comment by ROCmSupport** [comment]
Hi @mrmoein 
Is the issue observed only with ROCm? 
For me, looks like, issue is specific to your config.
Because with and without ROCm, we are not able to reproduce this issue here.

**Comment by mrmoein** [comment]
> Hi @mrmoein
> Is the issue observed only with ROCm?
> For me, looks like, issue is specific to your config.
> Because with and without ROCm, we are not able to reproduce this issue here.

hello, two time when i play "Left for dead" in middle of game this problem happend too. i think when turn vsinc off the game use 100% of my gpu and this happened!

but when i start tensorflow it happens all time.

i check my gpu temperature but it is ok.

**Comment by ROCmSupport** [comment]
Thanks @mrmoein for additional information.
So it means, its not ROCm issue.
