### ISSUE TITLE
Big Navi support

### ISSUE THREAD

**Issue by HaromKutya** [RadeonOpenCompute/ROCm#1271]
Hi!

The new RX 6000 lineup was officially unveiled yesterday, but the event was solely about gaming. I can fully understand that, because the majority of people who will buy the new cards are gamers.

However, the question remains: Will the new cards get official ROCm support? It would be great, especially with their 16 gigs of VRAM.
This is also an important question, because for me (and presumably for most people who actively use ROCm) this will be the basis of deciding if I want to buy an RX 6000 series card, or not.

Thanks.

**Comment by xuhuisheng** [comment]
Duplicate of #1180

**Comment by rkothako** [comment]
Similar to [https://github.com/RadeonOpenCompute/ROCm/issues/1251]

**Comment by rkothako** [comment]
Request you to close the ticket if the answer is reasonable.
Thank you.

**Comment by HaromKutya** [comment]
Yes, thank you for the information.
Closing the ticket now.
