### ISSUE TITLE
ROCm 3.9 - release

### ISSUE THREAD

**Issue by kulichbulich** [RadeonOpenCompute/ROCm#1272]
After update to latest ROCm 3.9, Tensorflow-rocm stop working with this error:
aqlprofile API table load failed: HSA_STATUS_ERROR
After this I try to uninstall all version of ROCm and install only ROCm 3.9, I have strange problems with ROCm 3.9
1. Problem
I cannot run /opt/rocm/bin/rocminfo this file is missing in directories: /opt/rocm-3.9.0 and /opt/rocm
This is strange when package rocminfo was installed

2. Problem
I have error: libroctracer64.so.1: cannot open shared object file: No such file or directory
This is strange when package roctracer-dev was installed. This file is missing in directories: /opt/rocm-3.9.0 and /opt/rocm

I am doing something wrong?

GPU:
RX-Vega 64
My system:
Linux kulich-PC-GPU 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Packages:
rccl/Ubuntu 16.04,now 2.7.8.482-rocm-rel-3.9-17-44fcde7 amd64 [installed]
rccl3.9.0/Ubuntu 16.04 2.7.8.482-rocm-rel-3.9-17-44fcde7 amd64
resiprocate-turn-server/bionic 1:1.11.0~beta5-1 amd64
resiprocate-turn-server-psql/bionic 1:1.11.0~beta5-1 amd64
rocalution/Ubuntu 16.04 1.10.0.0-rocm-rel-3.9-17-fefccf1 amd64
rocalution3.9.0/Ubuntu 16.04 1.10.0.0-rocm-rel-3.9-17-fefccf1 amd64
rocblas/Ubuntu 16.04 2.30.0.0-91e553c amd64
rocblas3.9.0/Ubuntu 16.04 2.30.0.0-91e553c amd64
rocfft/Ubuntu 16.04 1.0.7.941-rocm-rel-3.9-17-e97ebb4 amd64
rocfft3.9.0/Ubuntu 16.04 1.0.7.941-rocm-rel-3.9-17-e97ebb4 amd64
rock-dkms/Ubuntu 16.04,now 1:3.9-17 all [installed,automatic]
rock-dkms-firmware/Ubuntu 16.04,now 1:3.9-17 all [installed,automatic]
rockdodger/bionic 1.0.2-2 amd64
rocksndiamonds/bionic 4.0.1.0+dfsg-1 amd64
rocm-bandwidth-test/Ubuntu 16.04 1.4.0.23-rocm-rel-3.9-17-gaefd848 amd64
rocm-bandwidth-test3.9.0/Ubuntu 16.04 1.4.0.23-rocm-rel-3.9-17-gaefd848 amd64
rocm-clang-ocl/Ubuntu 16.04,now 0.5.0.64-rocm-rel-3.9-17-50fb51a amd64 [installed,automatic]
rocm-clang-ocl3.9.0/Ubuntu 16.04 0.5.0.64-rocm-rel-3.9-17-50fb51a amd64
rocm-cmake/Ubuntu 16.04,now 0.3.0.153-rocm-rel-3.9-17-1d1caa5 amd64 [installed,automatic]
rocm-cmake3.9.0/Ubuntu 16.04 0.3.0.153-rocm-rel-3.9-17-1d1caa5 amd64
rocm-dbgapi/Ubuntu 16.04,now 0.36.0-rocm-rel-3.9-17 amd64 [installed,automatic]
rocm-dbgapi3.9.0/Ubuntu 16.04 0.36.0-rocm-rel-3.9-17 amd64
rocm-debug-agent/Ubuntu 16.04 2.0.1-rocm-rel-3.9-17 amd64
rocm-debug-agent3.9.0/Ubuntu 16.04 2.0.1-rocm-rel-3.9-17 amd64
rocm-dev/Ubuntu 16.04,now 3.9.0.30900-17 amd64 [installed]
rocm-dev3.9.0/Ubuntu 16.04 3.9.0.30900-17 amd64
rocm-device-libs/Ubuntu 16.04,now 1.0.0.637-rocm-rel-3.9-17-db8c0c3 amd64 [installed]
rocm-device-libs3.9.0/Ubuntu 16.04 1.0.0.637-rocm-rel-3.9-17-db8c0c3 amd64
rocm-dkms/Ubuntu 16.04,now 3.9.0.30900-17 amd64 [installed]
rocm-gdb/Ubuntu 16.04,now 9.2-rocm-rel-3.9-17 amd64 [installed,automatic]
rocm-gdb3.9.0/Ubuntu 16.04 9.2-rocm-rel-3.9-17 amd64
rocm-libs/Ubuntu 16.04 3.9.0.30900-17 amd64
rocm-libs3.9.0/Ubuntu 16.04 3.9.0.30900-17 amd64
rocm-opencl/Ubuntu 16.04,now 3.6Beta-14-g0c40e05-rocm-rel-3.9-17 amd64 [installed,automatic]
rocm-opencl-dev/Ubuntu 16.04,now 3.6Beta-14-g0c40e05-rocm-rel-3.9-17 amd64 [installed,automatic]
rocm-opencl-dev3.9.0/Ubuntu 16.04 3.6Beta-14-g0c40e05-rocm-rel-3.9-17 amd64
rocm-opencl3.9.0/Ubuntu 16.04 3.6Beta-14-g0c40e05-rocm-rel-3.9-17 amd64
rocm-smi/Ubuntu 16.04,now 1.0.0-206-rocm-rel-3.9-17-ge39c0e2 amd64 [installed]
rocm-smi-lib64/Ubuntu 16.04,now 2.7.0.5-rocm-rel-3.9-17-8f9f943 amd64 [installed,automatic]
rocm-smi-lib643.9.0/Ubuntu 16.04 2.7.0.5-rocm-rel-3.9-17-8f9f943 amd64
rocm-smi3.9.0/Ubuntu 16.04 1.0.0-206-rocm-rel-3.9-17-ge39c0e2 amd64
rocm-utils/Ubuntu 16.04,now 3.9.0.30900-17 amd64 [installed]
rocm-utils3.9.0/Ubuntu 16.04 3.9.0.30900-17 amd64
rocm-validation-suite/Ubuntu 16.04 0.0.30900 amd64
rocm-validation-suite3.9.0/Ubuntu 16.04 0.0.30900 amd64
rocminfo/Ubuntu 16.04,now 1.30900.0 amd64 [installed]
rocminfo3.9.0/Ubuntu 16.04 1.30900.0 amd64
rocprim/Ubuntu 16.04 2.10.5.0-rocm-rel-3.9-17-fa69a09 amd64
rocprim3.9.0/Ubuntu 16.04 2.10.5.0-rocm-rel-3.9-17-fa69a09 amd64
rocprofiler-dev/Ubuntu 16.04,now 1.0.0 amd64 [installed,automatic]
rocprofiler-dev3.9.0/Ubuntu 16.04 1.0.0 amd64
rocrand/Ubuntu 16.04 2.10.5.0-rocm-rel-3.9-17-0728d21 amd64
rocrand3.9.0/Ubuntu 16.04 2.10.5.0-rocm-rel-3.9-17-0728d21 amd64
rocs/bionic 4:17.12.3-0ubuntu1 amd64
rocsolver/Ubuntu 16.04 3.9.0.0-c2cd214 amd64
rocsolver3.9.0/Ubuntu 16.04 3.9.0.0-c2cd214 amd64
rocsparse/Ubuntu 16.04,now 1.17.6.0-rocm-rel-3.9-17-a422ef5 amd64 [installed]
rocsparse3.9.0/Ubuntu 16.04 1.17.6.0-rocm-rel-3.9-17-a422ef5 amd64
rocthrust/Ubuntu 16.04 2.10.5.0-rocm-rel-3.9-17-a26200a amd64
rocthrust3.9.0/Ubuntu 16.04 2.10.5.0-rocm-rel-3.9-17-a26200a amd64
roctracer-dev/Ubuntu 16.04,now 1.0.0 amd64 [installed]
roctracer-dev3.9.0/Ubuntu 16.04 1.0.0 amd64

**Comment by pramenku** [comment]
It might be possible roctarcer-dev and rocm-utils was not clean uninstalled. Might be thunk also not clean uninstalled.

Double check all package has been removed after uninstallation.  dpkg -l | grep -i rocm or <packagename>

**Comment by kulichbulich** [comment]
Thank you, very much. Tensorflow is running now and I am also solving issue with OpenCL. Problem was in installation (not all package was uninstall cleanly). You can close this issue.

**Comment by streamhsa** [comment]
Thanks for confirming. Closing the ticket.
