### ISSUE TITLE
Getting segfaults on fresh Ubuntu 20.04.1 install

### ISSUE THREAD

**Issue by Autofire** [RadeonOpenCompute/ROCm#1279]
Hello! I'm pretty new to ROCm, so I'm sorry if I've missed anything obvious, but...

I've been trying to get ROCm set up on a laptop which happens to have an AMD card. It _might_ be too old, but I'm not totally sure yet. After the segfaults I've been getting, I'm not too hopeful, but I thought I'd ask.

For some background, this is a fresh install of Ubuntu 20.04.1, which I set up using [wubiuefi](https://github.com/hakuna-m/wubiuefi). I have done almost nothing to the system except follow the instructions for [installing ROCm](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu).

[This is the output I'm getting from the rocminfo and clinfo.](https://gist.github.com/Autofire/0dfd012710b9029fa869553009dce2d3) At the end, I also have the results of trying to build and run [this ROCm program](https://github.com/ROCm-Developer-Tools/HIP-Examples/tree/master/vectorAdd):

```
daniel@ubuntu:~/HIP-Examples/vectorAdd$ make
/opt/rocm/hip/bin/hipcc -g   -c -o vectoradd_hip.o vectoradd_hip.cpp
/opt/rocm/hip/bin/hipcc vectoradd_hip.o -o vectoradd_hip.exe
./vectoradd_hip.exe
 System minor 0
 System major 4238752
 agent prop name 
hip Device prop succeeded 
make: *** [Makefile:30: test] Segmentation fault (core dumped)
```

It's not just this program; all of the examples in that repo are also throwing segfaults. Am I missing some driver (this wouldn't surprise me)? Or is my hardware incompatible?

If it helps, [here is the info on the graphics card that the AMD Radeon Pro Settings comes up with.](https://gist.github.com/Autofire/168aacfdfc6bf7a2449b112a913445c9)

**Comment by rkothako** [comment]
Hi @Autofire 
Thanks for reaching us.

Looks like you have installed ROCm on a non-supported card and so clinfo and rocminfo are not detecting GPUs as showing @ https://gist.github.com/Autofire/0dfd012710b9029fa869553009dce2d3

Can you please share some information on your hardware used (or) take a look once at supported hardware for ROCm @ https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support

**Comment by rkothako** [comment]
Hi @Autofire , request you to close this ticket, if the above comment is reasonable.
Thank you.

**Comment by Autofire** [comment]
Ahh ok, thank you! I figured as much, but I wasn't sure. Some of the docs seemed to suggest that the card _could potentially_ work, so I wasn't entirely sure.
