### ISSUE TITLE
Whats the current status on APU ssupport ?

### ISSUE THREAD

**Issue by Coderx7** [RadeonOpenCompute/ROCm#1280]
The last information concerning APUs belong to rocm 2.1, and seems not to have been updated eversince. 
Has anything changed in this reagard?
can we expect the support for APUs as well?

**Comment by rkothako** [comment]
Hi @Coderx7 
Thanks for reaching us.
I will get more information and will update you soon on this.

**Comment by rkothako** [comment]
Hi @Coderx7 
As of now, its the same for APUs.
We will inform once we have an update in future.

**Comment by beatboxa** [comment]
@Coderx7  There is a derived project you may want to check out:

https://bruhnspace.com/en/bruhnspace-rocm-for-amd-apus/

**Comment by Coderx7** [comment]
@beatboxa thanks a lot. its really appreciate. its a very neat project. 👍

**Comment by rkothako** [comment]
Hi @Coderx7 
I request you close this ticket if the above answers are reasonable.
Thank you.
