### ISSUE TITLE
Ubuntu 20.04.1 + ROCm 3.9.0 + Davinci Resolve = BROKEN

### ISSUE THREAD

**Issue by paranoidfactoid** [RadeonOpenCompute/ROCm#1281]
Hardware: x399 TR 1950x. VEGA FE. 

OS: Ubuntu 20.04.1 

With AMDGPU-PRO 20.40 it all works. Davinci, blender, etc. Except the display driver is slow and incompatible with OBS and Natron.

With standard X11 AMD drivers and ROCm 3.9.0, blender works but Davinci Resolve doesn't. Can't display video in the preview and edit windows. Or in Fusion. Or the Color tab. Essentially useless. 

Is this a known problem? Seems like ROCm hasn't worked properly with Resolve since ROCm-2.2.

**Comment by rkothako** [comment]
Thank you for reaching out.
Request you to kindly paste or attach the logs of  following commands :

1) /opt/rocm/bin/rocminfo
2) /opt/rocm/bin/rocminfo
3)/opt/rocm/bin/rocm-smi

**Comment by beatboxa** [comment]
@paranoidfactoid rocm 3.3 worked as well.  See my thread here:

[https://github.com/RadeonOpenCompute/ROCm/issues/768](url)

**Comment by BloodyIron** [comment]
3.9.1 causes clinfo and DaVinci Resolve to throw the same errors:

dlerror: libhsakmt.so.1: cannot open shared object file: No such file or directory

Is this software actually tested before being rolled out? The repo doesn't even let me forcefully roll back to an earlier version :/ we really need the repos to have earlier versions of ROCm for when bugs like this come up.

Ubuntu 20.04 btw

**Comment by KristijanZic** [comment]
I've tested Davinci Resolve 16, DaVinci Resolve 17 and Natron on a fresh Ubuntu 20.04 installation on a Threadripper 1900x + Vega 64 machine with ROCm driver. Nothing worked.

Is amd even testing this driver?? What is wrong with them? It all works fine on any shitty Nvidia gpu but you buy a flagship AMD GPU mostly because you want to support their efforts and then nothing works because of their drivers.

Please, someone from AMD answer us. Do you even test ROCm with supported GPUs against the commonly used software like DaVinci Resolve??

I've been writing bug reports for years already and nothing changed.

**Comment by beatboxa** [comment]
@paranoidfactoid which version of DaVinci Resolve did you test?  (16.x or 17.0-beta)?

@KristijanZic I agree.  AMD has been doing a very poor job here.  Here is my perspective.  In short, I have lost patience & faith that this ROCm team knows what it is doing, given all of the re-architectures, regressions, bugs, lack of communication, and slow progress.

- https://github.com/RadeonOpenCompute/ROCm/issues/768#issuecomment-726784192

**Comment by BloodyIron** [comment]
Is there a repo we can use to go back to earlier versions, such as say ROCm 3.8? It's really stupid their repo removes old versions. Also, is there a better way to actually get the dev's attention?

**Comment by beatboxa** [comment]
@BloodyIron  Yes.  See my linked thread above for instructions for specifying the repo.  Here it is again (it's the second post in this thread):
- https://github.com/RadeonOpenCompute/ROCm/issues/768

Alternatively, in some cases, you can also do the "multiversion" install to specify your version, depending on the package components.  In this scenario, you could append "dev<version>" onto the package name.  For example:  rocm-dev3.8 (as opposed to rocm).

**Comment by BloodyIron** [comment]
@beatboxa  thanks! I'll have to try to roll back, hopefully there's a 3.8 option or something like that. I'm looking to get a 6800 XT when they roll out, so I'd prefer to stay as current (and functional) as possible. Any tips for RDNA 2 would be appreciated!

**Comment by BloodyIron** [comment]
Following @beatboxa 's steps on reverting to ROCm v3.3 I can now get Davinci Resolve 16 running! This is on Ubuntu 20.04 btw.

I'm now just going to not upgrade ROCm until I somehow see a need.

**Comment by paranoidfactoid** [comment]
Remember to test for video in Fusion and try to use the pen tool on the canvas in the color tab. Also, render a large dnxhr file and see if it crashes.

**Comment by beatboxa** [comment]
@BloodyIron Glad it worked!

Heads up though:  Davinci Resolve 17 beta came out earlier this week.  Unfortunately, the new version of Resolve does not work with any ROCm version, including 3.3.

**Comment by BloodyIron** [comment]
Yeah I'm also planning to just stick with DaVinci Resolve 16 for now.

**Comment by KristijanZic** [comment]
> Unfortunately, the new version of Resolve does not work with any ROCm version, including 3.3.
But nothing works with ROCm or AMDGPU-PRO. Resolve doesn't work, Natron crashes on launch even Blender drags it's ass in cycles. I remember when they were showing my GPU rendering 8K composition with millions of polygons in less than 8 seconds and I can't render a 1080p composition wiht less than 100 polygons in less than 120 seconds per frame in Cycles. Ridiculous.

**Comment by baryluk** [comment]
> 3.9.1 causes clinfo and DaVinci Resolve to throw the same errors:
> 
> dlerror: libhsakmt.so.1: cannot open shared object file: No such file or directory
> 
> Is this software actually tested before being rolled out? The repo doesn't even let me forcefully roll back to an earlier version :/ we really need the repos to have earlier versions of ROCm for when bugs like this come up.
> 
> Ubuntu 20.04 btw

This suggests you don't have all packages installed. Unfortunately a lot of deb packages of ROCm do have wrong dependencies, so not all of them are always installed correctly.

Please provide output of:

`dpkg -l | egrep 'roc[mtrc]|hsa'`

and

`/opt/rocm-3.9.0/bin/rocminfo`

**Comment by baryluk** [comment]
> @BloodyIron Glad it worked!
> 
> Heads up though: Davinci Resolve 17 beta came out earlier this week. Unfortunately, the new version of Resolve does not work with any ROCm version, including 3.3.

@beatboxa

Davinci Resolve 17 beta works for me with ROCm 3.9 just fine.

I needed to disable the pocl  (i.e. uninstall `pocl-opencl-icd` package, or comment it out in `/etc/OpenCL/vendors/pocl.icd` ), because otherwise it crashes in pocl. It is not an ROCm issue, but pocl bug.

**Comment by paranoidfactoid** [comment]
Resolve 17 is an early beta. A more important question here is: does removing pocl-opencl-icd allow Resolve 16.2.x to run? And properly. Because just checking it gets through the splash screen isn't good enough. Do viewports work? Does Fusion work? How about the pen tool and other crucial mask tools? I'll remove AMDGPU-Pro and see if removing pocl actually does anything here for 16.2.x. If it starts, I'll check the rest of it. Because AMDGPU-Pro has its own set of problems, not least of which it isn't spinning up the fan on my VEGA FE card, leading to auto system shutdowns under GPU load.

**Comment by paranoidfactoid** [comment]
What's going on with the repo? Suffice it to say, I followed instructions. 

foo@bukowski:~/Desktop$ sudo apt install rocm-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  comgr gcc-7-base hip-base hip-doc hip-rocclr hip-samples hsa-rocr-dev
  hsakmt-roct hsakmt-roct-dev libasan4 libcilkrts5 libdrm-dev libelf-dev
  libgcc-7-dev libstdc++-7-dev libubsan0 llvm-amdgpu mesa-common-dev
  openmp-extras rock-dkms rock-dkms-firmware rocm-clang-ocl rocm-cmake
  rocm-dbgapi rocm-dev rocm-device-libs rocm-gdb rocm-opencl rocm-opencl-dev
  rocm-smi rocm-smi-lib64 rocm-utils rocminfo rocprofiler-dev roctracer-dev
Suggested packages:
  libstdc++-7-doc
The following NEW packages will be installed:
  comgr gcc-7-base hip-base hip-doc hip-rocclr hip-samples hsa-rocr-dev
  hsakmt-roct hsakmt-roct-dev libasan4 libcilkrts5 libdrm-dev libelf-dev
  libgcc-7-dev libstdc++-7-dev libubsan0 llvm-amdgpu mesa-common-dev
  openmp-extras rock-dkms rock-dkms-firmware rocm-clang-ocl rocm-cmake
  rocm-dbgapi rocm-dev rocm-device-libs rocm-dkms rocm-gdb rocm-opencl
  rocm-opencl-dev rocm-smi rocm-smi-lib64 rocm-utils rocminfo rocprofiler-dev
  roctracer-dev
0 upgraded, 36 newly installed, 0 to remove and 0 not upgraded.
Need to get 633 MB/638 MB of archives.
After this operation, 721 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://repo.radeon.com/rocm/apt/debian xenial/main amd64 rock-dkms-firmware all 1:3.9-19
  404  Not Found [IP: 13.82.220.49 443]
Err:2 https://repo.radeon.com/rocm/apt/debian xenial/main amd64 rock-dkms all 1:3.9-19
  404  Not Found [IP: 13.82.220.49 443]

...

E: Failed to fetch https://repo.radeon.com/rocm/apt/debian/pool/main/r/rocm-utils/rocm-utils_3.9.1.30901-19_amd64.deb  404  Not Found [IP: 13.82.220.49 443]
E: Failed to fetch https://repo.radeon.com/rocm/apt/debian/pool/main/r/rocprofiler-dev/rocprofiler-dev_1.0.0_amd64.deb  File has unexpected size (253996 != 254002). Mirror sync in progress? [IP: 13.82.220.49 443]
   Hashes of expected file:
    - SHA256:90c1b51b2174cb46bf4c319f0c478316707407606b4a83594ffec40f9f4c6dd2
    - SHA1:10d623591e8ee52dc3a73a84f316d41ef0866214 [weak]
    - MD5Sum:550a17049af7b2a9df815b187d8fb3b7 [weak]
    - Filesize:254002 [weak]

**Comment by baryluk** [comment]
@paranoidfactoid They had a temporary issue with the repo.

Please do `sudo rm -rf /var/lib/apt/lists/*; sudo apt update`, and try again.

**Comment by baryluk** [comment]
@paranoidfactoid I never used Davinci Resolve before really, so I can't test it in depth. But I can try doing some simple things.

**Comment by boxerab** [comment]
Does ROCm 3.3 work with Ubuntu 20 ? If so, how do I install this old version ?
I need to return to an older version of ROCm as I see a large
OpenCL performance degradation with current 3.9

**Comment by ROCmSupport** [comment]
Hi @boxerab 
We started supporting Ubuntu 20.04 from recent releases only and so we can not give guarantee of Ubuntu 20.04 support for ROCm 3.3.
But it might work, you can give a try.
You can uninstall present ROCm completely like clean uninstallation and then install ROCm 3.3 from the path: **http://repo.radeon.com/rocm/apt/3.3/**

**Comment by BloodyIron** [comment]
And what about every version after 3.3 @ROCmSupport ?

**Comment by baryluk** [comment]
@BloodyIron please open separate issue about this. This thread is about Davinci Resolve specifically.

You can find information about supported versions in the readme and on the installation instruction website.

**Comment by BloodyIron** [comment]
Yes and I just asked about the literal subject line which talks about a newer version of ROCm than 3.3 and DaVinci Resolve...

**Comment by beatboxa** [comment]
@baryluk just to confirm:  you are running Davinci Resolve 17 + Ubuntu 20.04 + ROCm 3.9, with the only modifications being uninstallation of pocl-opencl-icd?  Because I did not install or have this component.

**Comment by KristijanZic** [comment]
@baryluk Can you also tell us which model of gpu card are you using?

**Comment by BloodyIron** [comment]
Does ROCm 3.3 work with the AMD 6800 series? Hoping I can stay on Ubuntu 20.04, ROCm 3.3 and stock Linux kernel (yes, this is on topic).

**Comment by baryluk** [comment]
@beatboxa @KristijanZic  I used Debian Testing, Linux 5.7.6, AMD Radeon R9 Fury X (FIJI, GFX8), and ROCm 3.9 with Davinci Resolve 17.

**Comment by beatboxa** [comment]
@baryluk and it is functional?  As in previews load and render live, editing and effects works, etc, all specifically using the GPU and not falling back to CPU for rendering?

**Comment by paranoidfactoid** [comment]
Davinci Resolve 16.2 is definitely NOT functional with ROCm 3.9.

**Comment by KristijanZic** [comment]
Just to let you guys all know: 
You can't even install AMDGPU-PRO 20.45 on Ubuntu 20.04. No matter which kernel you try on. It's totally broken.

AMDGPU-PRO 20.40 will install only up to 5.4.0-54-generic kernel and Ubuntu 20.04 is on 5.4.0-56-generic kernel. 
And even if you install it on older kernel it still gives you terrible screen tearing under Wayland, and half apps that need OpenCL don't even launch under X11 with AMDGPU-PRO 20.40.

ROCm is also broken hahaha.

So thank you all for throwing your money at AMD, you are all effectively *****d!

**Comment by ROCmSupport** [comment]
Hi @KristijanZic 
We are working on ROCm installation issue on 5.4.0-56, and fix will be ready soon.

**Comment by paranoidfactoid** [comment]
@ROCmSupport:

Will Davinci Resolve work? How about Blender, which has a known issue posted at the AMD download site.

**Comment by baryluk** [comment]
So, I just downloded Davinci Resolve 16, and downloaded a tutorial project from the BlackMagicStudio training subsite.

And there are issues.

Playback and video previews in cut and edit modes, break constantly, sometimes it works, sometimes it doesn't. Usually doesn't. I sometimes can get video without audio to work, or sometimes to get audio without video to work. Sometimes neither (but timeline is playing). Never both.

I the log file I see these things very often:

```
[0x7f90a3c80700] | DVIP                 | ERROR | 2020-12-09 01:46:34,809 | Failed to register OpenGL object for OpenCL interop: CL_MEM_OBJECT_ALLOCATION_FAILURE.
[0x7f90a3c80700] | DVIP                 | ERROR | 2020-12-09 01:46:34,809 | Failed to register GLIO compute interop mapper.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:34,809 | Failed to get texture for Handle1, job was aborted.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:37,544 | Failed to get texture for Handle1, job was aborted.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:37,551 | Failed to get texture for Handle1, job was aborted.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:37,559 | Failed to get texture for Handle1, job was aborted.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:40,925 | Failed to get texture for Handle1, job was aborted.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:40,932 | Failed to get texture for Handle1, job was aborted.
[0x7f91abb0d680] | UI.GLIO              | WARN  | 2020-12-09 01:46:40,939 | Failed to get texture for Handle1, job was aborted.
```

In dmesg I see things like this:

```
[22132.715735] Evicting PASID 0x8002 queues
[22132.739515] Restoring PASID 0x8002 queues
[22133.955470] Evicting PASID 0x8002 queues
[22133.979487] Restoring PASID 0x8002 queues
[22134.335795] Evicting PASID 0x8002 queues
[22134.347480] Restoring PASID 0x8002 queues
```

from time to time.

This is Debian testing, with ROCm 3.10 upstream amdgpu, Linux 5.9.9, and AMD Radeon R9 Fury X (FIJI, GFX8). Also Mesa 20.2.2.

It feels maybe it would be higher chance of working with AMDGPU-PRO? It looks like it requirest OpenGL and OpenCL interop.

**Comment by paranoidfactoid** [comment]
@baryluk

In fact, amdgpu-pro 20.45 doesn't work either. But if you downgrade your kernel to the previous 5.4.0-54 you can still use amdgpu-pro 20.40. If you can find it. And that does actually work with Resolve 16.2.

Even Blender is borked with 20.45.

**Comment by KristijanZic** [comment]
> @baryluk
> 
> In fact, amdgpu-pro 20.45 doesn't work either. But if you downgrade your kernel to the previous 5.4.0-54 you can still use amdgpu-pro 20.40. If you can find it. And that does actually work with Resolve 16.2. This is with Ubuntu 20.04.
> 
> Even Blender is borked with 20.45.

Actually it doesn't, Fairlight timeline views don't render (it's just black). So you can't do any audio engineering and mixing, just cutting in the Edit pane.

**Comment by KristijanZic** [comment]
> We are working on ROCm installation issue on 5.4.0-56, and fix will be ready soon.

It has been almost two months without a single change, I hope you are working hard!!!

**Comment by ROCmSupport** [comment]
Hi All,

As per the latest information and clarity provided in our Documentation that ROCm does not support GUI applications officially.

Docs also updated accordingly @ [https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support](url)

_Hardware and Software Support
ROCm is focused on using AMD GPUs to accelerate computational tasks such as machine learning, engineering workloads, and scientific computing. In order to focus our development efforts on these domains of interest, ROCm supports a targeted set of hardware configurations which are detailed further in this section._
**Note: The AMD ROCm™ open software platform is a compute stack for headless system deployments. GUI-based software applications are currently not supported.**

**Comment by beatboxa** [comment]
@KristijanZic @ROCmSupport 

And 3 months later:
"We have been working on the fix.  But we failed, so we decided to give up and change the scope of ROCm instead.  We'll call this change a 'clarification.'  Sorry it took 3 months for us to attempt to change history by telling you that we never supported graphical applications with our graphics cards in the first place, even though we clearly did."

So I am assuming @ROCmSupport will also close all threads related to Blender, Darktable, etc. as well.  I will link to @ROCmSupport's comment here so that those users can also be made aware that their applications are not supported.

**Comment by paranoidfactoid** [comment]
What does this mean for AMDGPU Pro, considering they've merged ROCm into
the pro driver line?

Are you guys saying AMD GPUs will no longer support GUI computational apps
like Blender and Davinci Resolve on Linux going forward?

Because that's bonkers. I might as well throw away my VEGA FE card now and
buy NVIDIA as soon as possible.

**Comment by BloodyIron** [comment]
When I initially set up ROCm to be used with my AMD GPU it was because it could offer me the ability to use OpenCL while also using the AMDGPU driver (NON PRO). This way I could get actually good gaming performance, and OpenCL acceleration for applications that leverage it. The whole point of supporting an application-agnostic API such as OpenCL is so that you don't have to support each and every application that can interface with it.

The fact that AMD clearly seems to be unwilling to support "GUI applications" that leverage OpenCL demonstrates to me that the implementation of the OpenCL API with ROCm is non-standard and inherently flawed. If the OpenCL API were implemented correctly, then it _would not matter_ whether I'm using a GUI tool with it or not.

This is looking to be yet another reason for me to switch to nVidia. Not only the fact that ROCm has been an utter nightmare to deal with (on a product I've paid for), but the sudden wilful negligence that is "ROCm does not support GUI applications officially".

AMD, you are going to lose customers by not actually supporting ROCm in the way that your users bought your cards for.

**Comment by johnbridgman** [comment]
This is an internal misunderstanding - I'm trying to get the messaging fixed and tickets re-opened.

**Comment by paranoidfactoid** [comment]
This call never got reopened, did it!

**Comment by BloodyIron** [comment]
Yeah what's going on?

**Comment by paranoidfactoid** [comment]
1345 is still closed too.

https://github.com/RadeonOpenCompute/ROCm/issues/1345#issuecomment-788373240

**Comment by KristijanZic** [comment]
How did the internal alignment go? Should we be worried again?

**Comment by ROCmSupport** [comment]
We are going to rephrase the text about GUI apps in our rocm documentation.
We have come up with some plans to handle GUI apps in a way.
But I am marking this as duplicate of #1345 and hence not reopening for now.
All progress can be seen at #1345 
Thank you.
