### ISSUE TITLE
SUSE 15.2 with Upstream Kernel?

### ISSUE THREAD

**Issue by ManOrs88** [RadeonOpenCompute/ROCm#1283]
Hello,

in the documentation there is no "Using ROCm with Upstream Kernel Drivers" for SUSE 15.2,
why is that so? the included kernel is newer than the one in Red Hat 8, which has the aforementioned documentation section

Kind Regards,
m

**Comment by rkothako** [comment]
Thanks @ManOrs88 for reaching us.
We will share an update on this soon.

**Comment by ManOrs88** [comment]
thanks!
