### ISSUE TITLE
ROCm v3.9.1 rocminfo fails to find libhsakmt.so.1

### ISSUE THREAD

**Issue by elliottbinder** [RadeonOpenCompute/ROCm#1284]
GPU: Radeon RX Vega (VEGA10, DRM 3.40.0, 5.4.0-53-generic, LLVM 10.0.0)
OS: Ubuntu 20.04.1 LTS

I just upgraded to v3.9.1 from v3.9. `rocm-smi` seems to work fine but `rocminfo` cannot find `libhsakmt.so.1`.

Checking the install directories, I see that file (ultimately linked to `libhsakmt.so.1.0.30900`) in the `lib` directory of v3.9.0, but it's missing from the v3.9.1 directory.

Creating a symbolic link via
`sudo ln -s /opt/rocm-3.9.0/lib/libhsakmt.so.1 /opt/rocm/lib/`
allows `rocminfo` to run, although I'm not sure this won't break other things.

Any idea as to why `libhsakmt.so.1` is missing from v3.9.1?

**Comment by dawjdh** [comment]
This solved it for me `sudo apt reinstall hsakmt-roct`

**Comment by elliottbinder** [comment]
Same here. Thanks!
