### ISSUE TITLE
Install on CentOS 8, ROCm thinks it is Redhat, demands a Redhat subscription.

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#1287]
Using instructions at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#centos-rhel

I am already running EPEL and the recommended kernel. 

So I added a /etc/yum.repos.d/rocm.repo file containing this:

```
[ROCm]
    name=ROCm
    baseurl=https://repo.radeon.com/rocm/centos8/rpm
    enabled=1
    gpgcheck=1
    gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key

```

Install ROCm:

```
[root@localhost ~]# yum install rocm-dkms
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Warning: failed loading '/etc/yum.repos.d/rocm.repo', skipping.
Last metadata expiration check: 0:08:21 ago on Thu 12 Nov 2020 06:26:18 PM MST.
No match for argument: rocm-dkms
Error: Unable to find a match: rocm-dkms


```

So, the instructions say CentOS does not need this Redhat subscription nonsense, but the installation thinks it cannot load the ROCm repo because the machine does not have a Redhat subscription.

It's a catch 22.

Ubuntu does work, but of late Ubuntu is moving a bit too fast for my taste. I'd like to use something more conservative, like CentOS.

**Comment by rkothako** [comment]
Hi @emerth 
Thanks for reaching out.

Its strange that CentOS is looking for RHEL subscription.
Can you please share the output of **cat /etc/os-release**

**Comment by emerth** [comment]
Hi tkothoka,

Hanging my head in shame I must report this is a PEBKAC issue. I had to remove the subscription-manager, this got rid of the expectation to be registered with Redhat. IDK why that was there in the first place. 

`yum --disablerepo=\* remove subscription-manager`

**Comment by emerth** [comment]
One small thing I should add, for the edicfication of other ppl like me.

Copy/paste the rocm.repo file contents from the ROCm Github install instructions put 3 or 4 leading spaces in front of the lines in the [ROCm] section:

```
[ROCm]
    name=ROCm
    baseurl=https://repo.radeon.com/rocm/centos8/rpm
    enabled=1
    gpgcheck=1
    gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key

```
... and yum does not like those spaces at all. It has to be without any leading spaces, then yum will load the ROCm repo:

```
[ROCm]
name=ROCm
baseurl=https://repo.radeon.com/rocm/centos8/rpm
enabled=1
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key

```

**Comment by rkothako** [comment]
Thanks @emerth
I have already fixed the spacing issue.
