### ISSUE TITLE
ROCM Library for Windows and DirectML

### ISSUE THREAD

**Issue by YuriyTigiev** [RadeonOpenCompute/ROCm#1291]
Will be ROCM library porting on windows?
For AMD cards exist only one library DirectML which works with tensorflow for Windows. But this library is very old :(

**Comment by rkothako** [comment]
Hi @YuriyTigiev 
Thanks for reaching out.
We will inform once we plans to support full ROCm for windows.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @YuriyTigiev 
Request to close this ticket now.
