### ISSUE TITLE
AMD GPU drivers for Ubuntu

### ISSUE THREAD

**Issue by YuriyTigiev** [RadeonOpenCompute/ROCm#1292]
Should I install the latest AMD drivers befor install ROCm ?

If yes, then which options I should use if I have a one or multiple cards?
https://amdgpu-install.readthedocs.io/en/latest/install-installing.html

**Comment by xuhuisheng** [comment]
Neednot install amdgpu-pro driver before ROCm.
ROCm provider a module named rock-dkms, this is the driver for GCN GPU.

And this is another way, that using upstream kernel driver.
That means if we plugin in a GCN GPU on ubuntu-18.04 or ubuntu-20.04, the built-in driver can be used as well as rock-dkms. we have to install only rocm-devs and rocm-libs to enable ROCm.

But AMD said upstream driver could only using 3/8 memory of GPU, which rock-dkms could use 15/16 memory of GPU.
https://github.com/radeonopencompute/ROCm#rocm-support-in-upstream-linux-kernels
Current not lts version of ubuntu is 20.10, using kernel-5.8, so I think upstream driver is as well as rock-dkms.

**Comment by rkothako** [comment]
Thanks @YuriyTigiev and @xuhuisheng 
Request to close this ticket if the above answers are reasonable.

**Comment by ROCmSupport** [comment]
Hi @YuriyTigiev, Can you please close this ticket now.
Thank you.
