### ISSUE TITLE
Release .tar.gz binaries for any distro

### ISSUE THREAD

**Issue by 0x0f0f0f** [RadeonOpenCompute/ROCm#1295]
Me and other distros users are having trouble building the stack. Having to build a custom clang and a custom LLVM is quite time intensive. Could you please release a tarball with the binaries?

**Comment by jpsamaroo** [comment]
To add to this, it would be ideal if such a tarball had binaries linked against LLVM statically. This would be necessary for languages/projects that package their own LLVM (Julia in my case), since multiple dynamically-loaded libLLVMs conflict with each other.

**Comment by baryluk** [comment]
@jpsamaroo I really doubt you will be able to load multiple versions of LLVM at the same time into single process. I could be wrong tho.

I also just feel linking entire LLVM statically might be an overkill, even if this LLVM only supports amdgcn targets. It is a very big library.

As of tarballs. You can build things yourself from git. Technically. I still struggle to make it work.

**Comment by ROCmSupport** [comment]
Thanks @0x0f0f0f for reaching out.
We will check and get back to you asap.

**Comment by searlmc1** [comment]
Hi @baryluk ,

You mentioned that you have troubles building from git. Can you expand on what problems you are having?

Thanks

**Comment by 0x0f0f0f** [comment]
I think that a "git pipeline"/github actions is what @baryluk meant. A travis CI/github actions build pipeline would really help understanding how to build, replicating a standard build locally and mostly, giving us downloadable binary archives. 

If talking about cloned git repositories, is not very clear to understand how to build for ROCm newcomers like me. My ROCm dir is 9.9GBs.... 
Which ROCm packages do depend on each other? Each package has it's own README format, some packages lack an INSTALL file with instructions, some packages require configuration steps that are not explained in the README. It's also not very clear which custom forks of LLVM/clang should be used to build. Is aomp even needed at all when building ROCm?

I really think that apart from distro agnostic binaries, a "global" build script letting you choose which components of ROCm you need, and doing the dirty building job on its own would be very helpful.

**Comment by baryluk** [comment]
@searlmc1 I tried building ROCm 3.8 few weeks ago. It was very hard to figure out all the repos that are required (only the required ones, not all the "extras"), order in which to build them, and flags to pass, especially if one wants to build a relocatable installation (i.e. not in /opt/rocm), especially without root. I managed to figure this out eventually after a lot of trail and error, but still one of the crucial components was failing cmake configuration, despite me trying all the possible cmake flags (I tried like 20 different path flags) and options to point it into the correct directory. After few days of fighting with cmake, I gave up. I believe it was `HIP` that was failing cmake. All the other things like `rocm-cmake`, (ROCm's) `llvm-project`, `ROCT-Thunk-Interface`, `ROCm-Device-Libs`, `ROCR-Runtime`, `ROCm-CompilerSupport`, `ROCclr` (ROCm-OpenCL-Runtime), compiled in that order, built fine. But then `HIP` was a failure. It probably was possible to fix it, but I just don't know cmake enough to make it work.

I don't want a script, I want a documentation that explains the process, a graph of dependencies what requires what. I find scripts to be too ridgid, have hard coded paths, be not adaptable, pull non-required dependencies from who knows where, and break on various distros or future versions. Documentation how to build a MINIMAL build, would be better.

See https://github.com/RadeonOpenCompute/ROCm/issues/1188

**Comment by 0x0f0f0f** [comment]
@searlmc1 is on point!

**Comment by saitam757** [comment]
@ROCmSupport: Better than releasing tar.bz binaries would be using a build system. A viable way would be e.g. the [OpenSUSE Build System](https://openbuildservice.org/) where distribution packages not only for OpenSUSE but several other distributions could be build (ubuntu, fedora, ...).

**Comment by baryluk** [comment]
> @ROCmSupport: Better than releasing tar.bz binaries would be using a build system. A viable way would be e.g. the [OpenSUSE Build System](https://openbuildservice.org/) where distribution packages not only for OpenSUSE but several other distributions could be build (ubuntu, fedora, ...).

It is impossible for AMD to support all distributions and releases.

The best is to provide the build instructions (in up to date text), and distros and people can pick it up from there easily to support everything. Not scripts or build system.

It is just my opinion.

**Comment by saitam757** [comment]
@baryluk I admit, a build system would be the nicest thing to have. But up to date information and correct use of Cmake would be great. I tried building the stuff for Solus and I gave up.

**Comment by rkothako** [comment]
Hi @saitam757 and @baryluk 
We are working internally to update the docs with proper build instructions.
We will get back asap, please stay tuned.

**Comment by ROCmSupport** [comment]
Hi All,
We need some more time to get the proper build instructions and documentation updated.
Will keep you posted.
Thank you.

**Comment by ROCmSupport** [comment]
Hi All,
Reg: "Releasing ROCm in the form of .tar.bz" --> We do not plan to do such releases
Reg: Building ROCm from source with proper instructions --> Please track #1188 ticket.
Thank you.
