### ISSUE TITLE
ROCm 4.0... where?

### ISSUE THREAD

**Issue by BloodyIron** [RadeonOpenCompute/ROCm#1297]
2 Days ago AMD announced what appears to be the release of ROCm 4.0 : https://ir.amd.com/news-events/press-releases/detail/981/amd-announces-worlds-fastest-hpc-accelerator-for

And yet, I cannot find anywhere it is actually released (publicly?).

It seems they've announced releasing it but haven't released it. LOL. I really hope it fixes all the junk we've been seeing with DaVinci Resolve (and Ubuntu 20.04/other) so we don't have to sit on just 3.3 or earlier.

Anyone know what's up? Anyone had a chance to try ROCm 4.0 + DaVinci Resolve? (v16 or v17 beta)

**Comment by xuhuisheng** [comment]
I think itis more likely an announcement in advance, not the ROCm-4.0 public releasing notice.
ROCm-2.0 released at Dec. 18, 2018.
ROCm-3.0 released at Dec. 17, 2019.

Most likely ROCm-4.0 will release at later of Dec.
And ROCm-3.10 should release before, I guess.

**Comment by ROCmSupport** [comment]
Thanks @BloodyIron 
Yes, ROCm 3.10 is going to be released very soon as per the plans.
4.0 will be most likely available in the year end as per the current plans.
Please stay tuned.

**Comment by ROCmSupport** [comment]
Hi @BloodyIron,
Request to you close this ticket if you got the answers.
Thank you.

**Comment by BloodyIron** [comment]
Wait why is this the first thread I've seen @ROCmSupport in? There's plenty of others, like the Ubuntu 20.04 and DaVinci Resolve thread where I haven't seen you at all :/

**Comment by akostadinov** [comment]
Tell your marketing guys that it is making your customers angry to see something announced as if it is available but it is not so in fact. If they just have said ROCm instead os specifying version, that wouldn't bother anybody and not make AMD look bad. This is no iphone to queue for it one day in prior.

**Comment by alwzying** [comment]
> Hi @BloodyIron,
> Request to you close this ticket if you got the answers.
> Thank you.

Will 4.0 support 5700?

**Comment by KristijanZic** [comment]
Does 4.0 work well with DaVinci Resolve?

**Comment by ROCmSupport** [comment]
Thanks @KristijanZic for the suggestion.
I will pass the same information to QA.

**Comment by Spacefish** [comment]
> Thanks @KristijanZic for the suggestion.
> I will pass the same information to QA.
Will it Support RDNA / RDNA2 with DNN Worklfows? This would be really great to get some people started with the ROCm Stack as the cards are widely availiable. 
People who work with a RDNA consumer card today, might ### with a large cluster tommorow. If they already know the software stack, they will be more likely to choose AMD!

**Comment by hesenp** [comment]
big navi support please. otherwise I don't see how AMD Could have potential in data center market.

**Comment by boberfly** [comment]
While this is happening, the default ROCm repository for Ubuntu 20.04 here is completely broken & won't install things like rocm-dkms and my machine rebooted into a mesa software driver...

**Comment by Spacefish** [comment]
> While this is happening, the default ROCm repository for Ubuntu 20.04 here is completely broken & won't install things like rocm-dkms and my machine rebooted into a mesa software driver... On the Vega FE here though.

Had the same issue.. The kernel in 20.04 isn´t supported by the "pro" out of tree drivers (amdgpu works fine though). the installer which should install the dkms package fails, but a blacklist entry for the amdgpu module is added..

Delete the blacklist file in /etc/modprobe.d  not sure whether it´s in the "blacklist" or there is a seperate file, just grep for "amdgpu" in that folder. and remove the entry in the file.

You can load the blacklisted module manually via "sudo modprobe amdgpu", this will end you current Gui session though and you have to re-login.

**Comment by boberfly** [comment]
@Spacefish cheers I discovered this blacklist looking around, all good. I see that the DKMS module isn't compiling, probably just needs an ignore flag set as it's a compiler nitpick error by the looks of it. I'd copy-paste here but it looks like the log was purged when I uninstalled it.

**Comment by ROCmSupport** [comment]
Hi @Spacefish and @boberfly 
Its also know that ROCm is broken on 5.4.0-56 kernel and it works perfect with 5.4.0-54 kernel.
As Ubuntu recently pushed some security patches on 1Dec, all machines are having 5.4.0-56 kernel now and the installation issue observed.
We are already working on this fix. Until then, recommend to try on working kernels like 5.4.0-54 or HWE kernels.
Thank you.

**Comment by ROCmSupport** [comment]
Hi All,
Fix for 5.4.0-56 kernel is ready.
I recommend to do a fresh/clean install of ROCm 3.10 now and proceed.
Thank you.

**Comment by ROCmSupport** [comment]
Regarding actual title of this issue: ROCm 4.0 validation is in progress and will be available very soon, like in next 10 days.
Stay tuned.
Thank you.

**Comment by BloodyIron** [comment]
@ROCmSupport will ROCm 4.0 have DaVinci Resolve support out of the box and be of higher code quality than we've seen in the last two years? I'm hoping yes, because having to switch back and forth between versions of ROCm, and limiting the ability to upgrade versions of Ubuntu, really is not how this ecosystem should work.

**Comment by beatboxa** [comment]
@BloodyIron I was also hoping the answer was "yes"; but unfortunately, the answer appears to be "no."

- https://github.com/RadeonOpenCompute/ROCm/issues/1345
