### ISSUE TITLE
Rocm 3.9 version inconsistent between PyTorch with ROCm docker and Ubuntu

### ISSUE THREAD

**Issue by mathmax12** [RadeonOpenCompute/ROCm#1299]
Hi 
1. After installed Rocm 3.9.1, I found it only works with an old version of pytorch_rocm docker (rocm3.7_ubuntu18.04_py3.6_pytorch)
For the new one, e.g. [rocm3.9_ubuntu18.04_py3.6_pytorch_1.7.0](https://hub.docker.com/r/rocm/pytorch/tags) and rocm3.9_ubuntu18.04_py3.6_pytorch, it wouldn't work and show:
`/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")`

2. When use the command to check the version of the rocm. `apt show rocm-libs -a`
outside of the pytorch_rocm docker:
```
Version: 3.9.1.30901-19
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices, Inc.
```
Inside of the pytorch_rocm docker:
```
Package: rocm-libs
Version: 3.9.0.30900-17
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices, Inc.
```

Before I have a rocm 3.9.0 installed on my Ubuntu. Then I uninstalled it and reinstalled recom3.9.1.
**Why inside of the docker it insist to use the 3.9.0, which already removed?
Does "hipErrorNoBinaryForGpu: Coudn't find binary for current devices" issue related to this?**

Please help. 
Thanks.

**Comment by xuhuisheng** [comment]
Which GPU do you used?
ROCm-3.9 crashed with gfx803. But gfx900, gfx906 should be ok.

**Comment by mathmax12** [comment]
Hi @xuhuisheng 
Thanks for the quick reply.
I am using rx580 on ubuntu 18.04.
I read your thread https://github.com/RadeonOpenCompute/ROCm/issues/1269
That issue should have solved in the current rocm3.9.1, right?

**Comment by xuhuisheng** [comment]
@mathmax12 AMD said the ROCm-3.9.1 didnot changed any codes, just resolved the config problem for RPM. I am afraid we still need compile rocSPARSE by ourselves. or using ROCm-3.5.1.

**Comment by ROCmSupport** [comment]
Hi @mathmax12 
Thanks for reaching out.
3.9.1 has no code change and it has fix for compatibility issue with certain drivers for RPM based packages. 3.9 and 3.9.1 are completely same w.r.to debs. As we have not generated new dockers for 3.9.1 and the latest dockers are available on 3.9 only, you will find/see 3.9 only inside docker.
Hope this helps.
Thank you.

**Comment by mathmax12** [comment]
@ROCmSupport 
Thanks.  
I got the issue above with the latest docker
`/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")`

Is this problem fixed or I have to use xuhuisheng's solution for a workaround?

**Comment by rkothako** [comment]
Hi @mathmax12 
You can proceed with a workaround for time-being.
It will be fixed in 3.10.

**Comment by ROCmSupport** [comment]
Hi @mathmax12 
Recommend to proceed with workaround for now.

**Comment by ROCmSupport** [comment]
Hi @mathmax12 
As the main issue(as per title) is not an issue any more, recommend to close.
Thank you.
