### ISSUE TITLE
sudo apt-get install rocm opencl-rocm does not work

### ISSUE THREAD

**Issue by zhaojunfan** [RadeonOpenCompute/ROCm#130]
Linux 16.04.02, AMD W9100 graphic card.
I follow the readme.md in ROCm project, on branch roc-1.5.0 .
I try to install opencl, but failed.
1. wget -qO - http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
2. sudo sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
3. sudo apt-get update
4. sudo apt-get install rocm opencl-rocm
5. sudo apt-get install rocm opencl-rocm-dev

both 4 and 5 failed, can get the package.
I want to know why?

**Comment by gstoner** [comment]
You only need to do 4 or 5


Greg
On Jun 16, 2017, at 4:38 AM, zhaojunfan <notifications@github.com<mailto:notifications@github.com>> wrote:


Linux 16.04.02, AMD W9100 graphic card.
I follow the readme.md in ROCm project, on branch roc-1.5.0 .
I try to install opencl, but failed.

  1.  wget -qO - http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
  2.  sudo sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
  3.  sudo apt-get update
  4.  sudo apt-get install rocm opencl-rocm
  5.  sudo apt-get install rocm opencl-rocm-dev

both 4 and 5 failed, can get the package.
I want to know why?

**Comment by zhaojunfan** [comment]
I did step 4, get the output like this:
mcw@mcw-All-Series-Invalid-entry-length-16-Fixed-up-to-11:~/fzj$ sudo apt-get install rocm opencl-rocm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package opencl-rocm

I did step 5, get the output like this;
mcw@mcw-All-Series-Invalid-entry-length-16-Fixed-up-to-11:~/fzj$ sudo apt-get install rocm opencl-rocm-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package opencl-rocm-dev

**Comment by briansp2020** [comment]
Proper command is
sudo apt-get install **rocm-opencl-dev**

**Comment by gstoner** [comment]
ROCm 1.6 is out now also we built new set of getting started instructions https://github.com/ROCm/ROCm.github.io/blob/master/ROCmInstall.md
