### ISSUE TITLE
linux kernel notice

### ISSUE THREAD

**Issue by clzstc123** [RadeonOpenCompute/ROCm#1307]
ubuntu 20.04
linux-image-5.4.0-54-generic        rocm-dkms,it's work
linux-image-5.4.0-57-generic        rocm-dkms,it does't work

**Comment by ROCmSupport** [comment]
Hi @clzstc123 
Thanks for reaching out.
ROCm is working with 5.4.0-42 and 5.4.0-54 kernels. Not sure about 5.4.0-56, need to check.
Whats the output you are getting?
Request you to share more details for better understanding of the problem.

**Comment by ddobreff** [comment]
`diff --git a/amd/amdgpu/amdgpu_bios.c b/amd/amdgpu/amdgpu_bios.c
index 50dff69..b1172d9 100644
--- a/amd/amdgpu/amdgpu_bios.c
+++ b/amd/amdgpu/amdgpu_bios.c
@@ -192,30 +192,35 @@ static bool amdgpu_read_bios_from_rom(struct amdgpu_device *adev)

 static bool amdgpu_read_platform_bios(struct amdgpu_device *adev)
 {
-       uint8_t __iomem *bios;
-       size_t size;
+       phys_addr_t rom = adev->pdev->rom;
+       size_t romlen = adev->pdev->romlen;
+       void __iomem *bios;

        adev->bios = NULL;

-       bios = pci_platform_rom(adev->pdev, &size);
-       if (!bios) {
+       if (!rom || romlen == 0)
                return false;
-       }

-       adev->bios = kzalloc(size, GFP_KERNEL);
-       if (adev->bios == NULL)
+       adev->bios = kzalloc(romlen, GFP_KERNEL);
+       if (!adev->bios)
                return false;

-       memcpy_fromio(adev->bios, bios, size);
+       bios = ioremap(rom, romlen);
+       if (!bios)
+               goto free_bios;

-       if (!check_atom_bios(adev->bios, size)) {
-               kfree(adev->bios);
-               return false;
-       }
+       memcpy_fromio(adev->bios, bios, romlen);
+       iounmap(bios);

-       adev->bios_size = size;
+       if (!check_atom_bios(adev->bios, romlen))
+               goto free_bios;
+
+       adev->bios_size = romlen;

        return true;
+free_bios:
+       kfree(adev->bios);
+       return false;
 }

 #ifdef CONFIG_ACPI
`
This should fix the compile error for 5.4.0-56+

**Comment by ROCmSupport** [comment]
Thanks @ddobreff for the workaround.
Hi @clzstc123, can you please give a try as above and update.
Thank you.

**Comment by ye-luo** [comment]
encountered 5.4.0-56 issue when trying to install 3.10. @ROCmSupport could you roll out 3.10.1 to get this issue fixed?

**Comment by ROCmSupport** [comment]
Hi @clzstc123 and @ye-luo 
I, myself, saw this issue, I mean able to reproduce this problem locally with 5.4.0-56. I am working with Kernel team for the fix.
I will update once the fix is available.

**Comment by Dantali0n** [comment]
Here is the dkms crash dump [rock-dkms-firmware.0.txt](https://github.com/RadeonOpenCompute/ROCm/files/5627656/rock-dkms-firmware.0.txt)

**Comment by ROCmSupport** [comment]
Yes @Dantali0n
I found the same crash and our kernel team is working on it.
Thank you.

**Comment by clzstc123** [comment]
> Hi @clzstc123 and @ye-luo 
> I, myself, saw this issue, I mean able to reproduce this problem locally with 5.4.0-56. I am working with Kernel team for the fix.
> I will update once the fix is available.

sadly, ubuntu update to 5.4.0-57.
![IMG_20201203_232631.jpg](https://user-images.githubusercontent.com/5130377/101051068-06dbe780-35c0-11eb-8f32-34d7e57a9299.jpg)

**Comment by darsnack** [comment]
Just leaving a note that this same issue cropped up with 4.15.0-126 on Ubuntu 18.04 LTS. The diff above worked to fix it though.

**Comment by ROCmSupport** [comment]
Thanks @darsnack for trying a new kernel for time-being.

**Comment by ROCmSupport** [comment]
Hi All,
Until the fix is available, we recommend to install ROCm on 5.4.0-54 kernel or hwe kernels.
Thank you.

**Comment by ROCmSupport** [comment]
Hi All,
Fix for 5.4.0-56 is ready and pushed too. Updated Documentation accordingly.
Request to try the new packages.

**_Note: AMD ROCm v3.10 fails to install on Ubuntu kernel v5.4.0-56. To resolve the installation issue, new packages for 'rock-dkms' and 'rock-dkms-firmware' are created and replaced. It is recommended to perform a clean and fresh installation with the new packages._**

Thank you.

**Comment by josarv** [comment]
@ROCmSupport  So let me get this straight, is it fixed now? Will installing it on a fresh Ubuntu w/ kernel v5.4.0-56 result in failure or not? Where do we get the new packages?

**Comment by ROCmSupport** [comment]
Hi @josarv 
The kernel packages which have fix, are kept in the same 3.10 repo location.
You can uninstall any existing ROCm and do a fresh & clean install of 3.10 and it works now.

**Comment by josarv** [comment]
@ROCmSupport  I am sorry for the spam, but it still is not perfectly clear to me (i need sleep). I have performed a clean fresh Ubuntu 20.04 installation (ships with 5.4.0-56) without anything else driver related. Will following [these](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html) instructions here, result in a failure, or am I good to go and install as per usual following the link?

**Comment by ROCmSupport** [comment]
Hi @josarv 
Yon can use the same repo as we have not changed the repo.
We have kept packages with fix into the same repo, I mean we replaced old kernel packages with new set of packages in the same space and so same instructions should work perfect.
Thank you.

**Comment by heuripedes** [comment]
> Hi All,
> Until the fix is available, we recommend to install ROCm on 5.4.0-54 kernel or hwe kernels.
> Thank you.

20.04's hwe is 5.8 which doesn't work either

**Comment by ROCmSupport** [comment]
Hi @heuripedes 
Request you to wait for ROCm 4.1.
Thanks.

**Comment by ChrisAi89** [comment]
> Hi @heuripedes
> Request you to wait for ROCm 4.1.
> Thanks.

Is there already an approximate date of release? I try to get my Radeon RX570 to work on a 5.8.0-44 kernel with ROCM 4.0, but for already well described reasons this task remains unaccomplished. Using older kernels with ROCM 3.5 caused unforeseen system instability and I really do not want to switch, for several reasons, the brand of my GPU.

**Comment by ROCmSupport** [comment]
Hi @ChrisAi89 
It will be released anytime in this month. Please stay tuned.
Thank you.

**Comment by xuhuisheng** [comment]
@ChrisAi89 
If you can downgrade linux kernel to 5.4.0, rocm-dkms from ROCm-4.0 can install successfully.

But since RX570, aka gfx803, had been removed from offcial support. It will be some issues when you use it on ROCm-4.0. Please refer here : https://github.com/xuhuisheng/rocm-build/tree/develop/gfx803
