### ISSUE TITLE
ROCm 3.5.1 - Radeon RX 570 GPU bandwidth too low

### ISSUE THREAD

**Issue by borgarpa** [RadeonOpenCompute/ROCm#1309]
System specs:

- Ubuntu: 20.04.1
- ROCm: 3.5.1
- GPU: Radeon RX 570 8 Gb
- CPU: AMD Ryzen 5 1600X Six-Core Processor
- TensorFlow version: tensorflow-rocm==2.2.0

Hi, I switched recently to ROCm 3.5.1 due to Radeon RX 570 being incompatible with ROCm 3.9 (#1265 , #1269 ,  [#2187](https://github.com/ROCm-Developer-Tools/HIP/issues/2187)). 

The thing is when I run a CNN benchmark, bandwidth seems to be very low. The test I run is the following: `python3 tf_cnn_benchmarks.py --num_gpus=1 --batch_size=8 --model=resnet50` from [tf_cnn_benchmarks.py](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py). The full log message is as follows: 
[rocm_benchmark.txt](https://github.com/RadeonOpenCompute/ROCm/files/5615294/rocm_benchmark.txt)
As you can see in the 13th line, `coreClock: 1.268GHz coreCount: 32 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: -1B/s`, bandwidth is ridiculously small.

Besides, when I run the `rocm-bandwidth-test` command I get the following:
```
........
          RocmBandwidthTest Version: 2.3.11

          Launch Command is: rocm-bandwidth-test (rocm_bandwidth -a + rocm_bandwidth -A)


          Device: 0,  AMD Ryzen 5 1600X Six-Core Processor
          Device: 1,  Ellesmere [Radeon RX 470/480/570/570X/580/580X/590],  1f:0.0

          Inter-Device Access

          D/D       0         1         

          0         1         0  <--    

          1         1         1         


          Inter-Device Numa Distance

          D/D       0         1         

          0         0         N/A <--   

          1         20        0         


          Unidirectional copy peak bandwidth GB/s

          D/D       0           1           

          0         N/A         11.238147   

          1         7.108366    25.104243   


          Bdirectional copy peak bandwidth GB/s

          D/D       0           1           

          0         N/A         14.147676   

          1         14.147676   N/A
```

Is it normal that during the Inter-Device Access test, value from device 0 to 1 is 0? Furthermore, during the Inter-Device Numa Distance test, distance from device 0 to 1 appears to be N/A. I marked these results with an arrow.

Also, when running `rocm-smi` I get a bunch of sysntax warnings:
```
/opt/rocm/bin/rocm-smi:816: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if clocktype is 'freq':
/opt/rocm/bin/rocm-smi:901: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if component is 'driver':
/opt/rocm/bin/rocm-smi:923: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (retiredType is 'all' or \
/opt/rocm/bin/rocm-smi:924: SyntaxWarning: "is" with a literal. Did you mean "=="?
  retiredType is 'retired' and pgType is 'R' or \
/opt/rocm/bin/rocm-smi:924: SyntaxWarning: "is" with a literal. Did you mean "=="?
  retiredType is 'retired' and pgType is 'R' or \
/opt/rocm/bin/rocm-smi:925: SyntaxWarning: "is" with a literal. Did you mean "=="?
  retiredType is 'pending' and pgType is 'P' or \
/opt/rocm/bin/rocm-smi:925: SyntaxWarning: "is" with a literal. Did you mean "=="?
  retiredType is 'pending' and pgType is 'P' or \
/opt/rocm/bin/rocm-smi:926: SyntaxWarning: "is" with a literal. Did you mean "=="?
  retiredType is 'unreservable' and pgType is 'F'):
/opt/rocm/bin/rocm-smi:926: SyntaxWarning: "is" with a literal. Did you mean "=="?
  retiredType is 'unreservable' and pgType is 'F'):
/opt/rocm/bin/rocm-smi:1501: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if component is 'driver':
/opt/rocm/bin/rocm-smi:1938: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ptype is 'R':
/opt/rocm/bin/rocm-smi:1940: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif ptype is 'P':
/opt/rocm/bin/rocm-smi:2395: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if clkType is 'sclk':
/opt/rocm/bin/rocm-smi:2397: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif clkType is 'mclk':


========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr   SCLK     MCLK     Fan     Perf  PwrCap  VRAM%  GPU%  
0    34.0c  41.028W  1233Mhz  1000Mhz  23.92%  auto  120.0W   93%   0%    
================================================================================
==============================End of ROCm SMI Log ==============================
```

If you need more info, I got the following results after running:
```
/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo
```
[rocm_clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/5615300/rocm_clinfo.txt)
[rocm_rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/5615301/rocm_rocminfo.txt)

**Comment by ROCmSupport** [comment]
Thanks @borgarpa for reaching out.
I will update you on this soon.
Thank you.

**Comment by borgarpa** [comment]
@ROCmSupport  I missinformed you! It is a Radeon RX 570 GPU, not a RX 580

**Comment by ROCmSupport** [comment]
Thanks @borgarpa 
As ROCm 3.10 released  days ago, can you please try and update.
Thank you.

**Comment by borgarpa** [comment]
> Thanks @borgarpa 
> As ROCm 3.10 released  days ago, can you please try and update.
> Thank you.

Ok! I will try that. 

What should I do in order to completely erase ROCm from the system and install it from scratch? 

Besides, will I be able to use, for instance, TensorFlow 2.2 with ROCm 3.10? 

Thanks

**Comment by ROCmSupport** [comment]
Hi @borgarpa 
Please uninstall ROCm using "sudo apt autoremove rocm-dkms" 
Make sure that all packages are removed under /opt/rocm-xxx.
Recommend to check sudo dpkg -l | grep hsa . Replace hsa with hip, llvm, rocm, rock and make sure that all packages are removed as like: **sudo apt purge <pkg>**. Recommend to do the same for all other additional packages also if you installed anything explicitly.

Once you make sure that its clean, now try to install ROCm 3.10.
You can use TF on 3.10.
I hope this helps.

**Comment by borgarpa** [comment]
> Hi @borgarpa 
> Please uninstall ROCm using "sudo apt autoremove rocm-dkms" 
> Make sure that all packages are removed under /opt/rocm-xxx.
> Recommend to check sudo dpkg -l | grep hsa . Replace hsa with hip, llvm, rocm, rock and make sure that all packages are removed as like: **sudo apt purge <pkg>**. Recommend to do the same for all other additional packages also if you installed anything explicitly.
> 
> Once you make sure that its clean, now try to install ROCm 3.10.
> You can use TF on 3.10.
> I hope this helps.

Thank you! 

Regarding TF, does that mean there is backwards compatibility for TF versions?

**Comment by borgarpa** [comment]
@ROCmSupport So, I installed ROCm 3.10, but I encountered this issue: #1315 #1307 . I had the to remove ROCm from the system again. Hence, the issue boils down to ROCm 3.5.1 again, a version that supports gfx803 and has no installation issues.

Besides, following ROCm removal recommended command `sudo apt autoremove rocm-opencl rocm-dkms rocm-dev rocm-utils && sudo reboot` has messed my AMD GPU drivers. 
After uninstalling ROCm and running `sudo lshw -c video` and `lsmod | grep amd` I get the following respectively:
```
  *-display UNCLAIMED       
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:1f:00.0
       version: ef
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list
       configuration: latency=0
       resources: memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:fe800000-fe83ffff memory:c0000-dffff
```
and
```
edac_mce_amd           32768  0
gpio_amdpt             20480  0
gpio_generic           20480  1 gpio_amdpt```

Therefore, what is going on? Why is bandwidth so low?

**Comment by ROCmSupport** [comment]
Hi @borgarpa 
Its not recommended to have both amdgpu-pro driver and ROCm in the same machine.
At a time only one environment is recommended to have. Otherwise system will be messed up.

**Comment by Djip007** [comment]
> Hi @borgarpa
> Please uninstall ROCm using "sudo apt autoremove rocm-dkms"
> Make sure that all packages are removed under /opt/rocm-xxx.
> Recommend to check sudo dpkg -l | grep hsa . Replace hsa with hip, llvm, rocm, rock and make sure that all packages are removed as like: **sudo apt purge **. Recommend to do the same for all other additional packages also if you installed anything explicitly.
> 
> Once you make sure that its clean, now try to install ROCm 3.10.
> You can use TF on 3.10.
> I hope this helps.

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1196
=> we need to wait a little to use it with TF ;)

**Comment by ROCmSupport** [comment]
AMD ROCm dropped supporting gfx8 officially from ROCm 4.0 as per https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support.
Hence closing this issue.
Thank you.

**Comment by VegetaDTX** [comment]
> AMD ROCm dropped supporting gfx8 officially from ROCm 4.0 as per https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support.
> Hence closing this issue.
> Thank you.

Where can I find the most recent version of AMD ROCm that supports GFX8 cards?
