### ISSUE TITLE
Is OpenGL supported on ROCm 1.5

### ISSUE THREAD

**Issue by zhaojunfan** [RadeonOpenCompute/ROCm#131]
I want to know if OpenGL is supported on ROCm 1.5.0

**Comment by grmat** [comment]
No.

But all the GPUs supported by ROCm are also supported by mesa, which provides OpenGL 4.5.

**Comment by gsedej** [comment]
You can use `oibaf ppa` to get the lastest mesa opengl drivers. I am not 100% sure what gl driver is in use, but you are limited with the current ROCm kernel driver  `4.9.0-kfd-compute-rocm-rel-1.5-99`.
I have ubuntu 16.04, ROCm 1.5, and oibaf ppa is "installed" (installed before ROCm) and I can play new steam games. This is my glxinfo:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD POLARIS10 (DRM 3.13.0 / 4.9.0-kfd-compute-rocm-rel-1.5-99, LLVM 4.0.1) (0x67df)
    Version: 17.2.0
    Accelerated: yes
    Video memory: 7315MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
```

**Comment by gstoner** [comment]
It is via the MesaGL stack,  we support OpenGL over EGL in headless config and also GL with X11 when you have head.
