### ISSUE TITLE
no AMD hosts both Debian and RPM repositories for the ROCm v3.10.x packages.

### ISSUE THREAD

**Issue by arpu** [RadeonOpenCompute/ROCm#1313]
Hey,

where are this packages? 

https://repo.radeon.com/rocm/centos8/ there is 3..9.1 but no 3.10

**Comment by xuhuisheng** [comment]
3.10.0 didnot release, yet.
And will be released soon. I guess.

**Comment by arpu** [comment]
https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html

i come from the officieall rocm doc side

**Comment by xuhuisheng** [comment]
OK. The documentations always go ahead of final releasing of whole ROCm.
I am watching the ROCm-3.10.0 tag of https://github.com/RadeonOpenCompute/ROCm/releases for the final step.

**Comment by Djip007** [comment]
https://repo.radeon.com/rocm/centos8/3.10/
repos now update ;)...
