### ISSUE TITLE
Why is the AMD Tobago chipset not supports ROCm?

### ISSUE THREAD

**Issue by orrburgel** [RadeonOpenCompute/ROCm#1317]
I wonder, Both the Hawaii chip (supported) and the Tobago (not supported) chipsets use the same OpenCL versions (2.0) but ROCm is not supported on the Tobago chipset

They even share the same Compute (GFX7), Vulkan, OpenGL, DirectX versions as shown below:

https://www.techpowerup.com/gpu-specs/amd-hawaii.g738
https://www.techpowerup.com/gpu-specs/amd-tobago.g777

**Is that something with the actual chips inside the GPU that is missing on Tobago or is it something that may or may not get support in the future?**

Also, I've found this link that indicates that the AMDGPU-PRO driver does have support for those GPU's that I think are using Tobago:
AMD Radeon™ R7 240/250/250X/260/260X/350 AMD FirePro™ W600
https://www.dell.com/support/article/en-il/sln311165/installing-and-configuring-amdgpu-pro-in-ubuntu-16-04-linux?lang=en

I have the AMD Radeon (TM) R7 360 Series which uses Tobago...
Which technically not on the list but I believe it shares the same Tobago chip with those GPU's mentioned above,

Thank all the people who will answer,
Best regards

**Comment by ROCmSupport** [comment]
Hi @orrburgel 
As per the current rocm docs, Hawaii is not fully supported. Am pasting the info here.
We have plans to update the docs about gfx7. Let me talk to docs team to have this change asap.
We are not guaranteed for gfx7 for now, might/might not work.

_The following list of GPUs are enabled in the ROCm software, though full support is not guaranteed:
        GFX7 GPUs
        "Hawaii" chips, such as the AMD Radeon R9 390X and FirePro W9100_

**Comment by jlgreathouse** [comment]
Hi @orrburgel 

As my colleague @ROCmSupport mentions, even Hawaii is only experimentally enabled in the ROCm software stack. Hawaii was used by our team to do initial AMD-internal work porting of the ROCm software stack from the integrated GPUs in APUs to discrete GPUs over a PCIe bus. We eventually made some changes public that would (hopefully) allow ROCm to run on Hawaii dGPUs.

Whether GPUs are supported in ROCm can be quite complicated. See the discussion in [this old thread](https://github.com/RadeonOpenCompute/ROCm/issues/451#issuecomment-422836032) for instance. I cannot publicly describe what things may or may not prevent Tobago from running ROCm (e.g., missing hardware support, missing firmware support, missing software support).

At this time, AMD has not announced any public plans to bring up the Tobago GPU on the ROCm software stack. As described in that linked conversation, the amdgpu-pro stack and the ROCm stack are quite different, and use the GPUs in very different ways. Support for a GPU in the amdgpu-pro stack does not imply support for that GPU in ROCm.

**Comment by owlshrimp** [comment]
> Hi @orrburgel As per the current rocm docs, Hawaii is not fully supported. Am pasting the info here. We have plans to update the docs about gfx7. Let me talk to docs team to have this change asap. We are not guaranteed for gfx7 for now, might/might not work.
> 
> _The following list of GPUs are enabled in the ROCm software, though full support is not guaranteed: GFX7 GPUs "Hawaii" chips, such as the AMD Radeon R9 390X and FirePro W9100_

It's not just "not fully supported." Hawaii cards like the W9100 have been completely broken since ROCm 2.0 and people have been reporting this since at least 2019: https://github.com/ROCm/ROCm/issues/871

Drop the facade and release an official list of what you have actually tested and verified works with the latest ROCm, and which you also actually intend to support. Include how long you intend to support it. That is the standard of a mature and production-capable compute stack. Without this bare minimum, people will continue to be averse to investing in the AMD ecosystem.

**Comment by owlshrimp** [comment]
> Hi @orrburgel
> 
> As my colleague [@ROCmSupport](https://github.com/ROCmSupport) mentions, even Hawaii is only experimentally enabled in the ROCm software stack. Hawaii was used by our team to do initial AMD-internal work porting of the ROCm software stack from the integrated GPUs in APUs to discrete GPUs over a PCIe bus. We eventually made some changes public that would (hopefully) allow ROCm to run on Hawaii dGPUs.

Hawaii has been completely broken in ROCm since ROCm 2.0. See https://github.com/ROCm/ROCm/issues/871 from 2019.

It's dead.
