### ISSUE TITLE
Please remove Recommends: gcc-multilib, g++-multilib from openmp-extras package

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1319]
ROCm 3.10

```
$ apt-cache show openmp-extras3.10.0 | grep Recommends
Recommends: gcc, g++, gcc-multilib, g++-multilib
$
```

This is unnecessary. And AFAIK doesn't enhance the package in anyway.

Use instead:

```
Suggests: gcc, g++
```

that is without `gcc-multilib` (which does for example conflict with `gcc-10-i686-linux-gnu` for cross-compiling), and downgrade to `Suggests`.

There is nothing in this package that interact with GCC in anyway, nor is GCC interacting with anything in this package.

**Comment by ROCmSupport** [comment]
Thanks @baryluk for reaching out.
I am working with OMP team on this, will keep you posted.
Thank you.

**Comment by ROCmSupport** [comment]
Update on this:
Fix is ready and will be pushed soon. Most likely it will be part of ROCm 4.1.
Thank you.

**Comment by baryluk** [comment]
Thank you for addressing even small issues like that!

It is appreciated.
