### ISSUE TITLE
ROCm 3.10 missing dependency on libtinfo.so.5

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1324]
ROCm 3.10, on Ubuntu 20.04, Linux kernel 5.9.12.

I installed rocm-opencl3.10.0, set up groups (video & render), set up kfd rights, set up LD_LIBRARY_PATH:
export LD_LIBRARY_PATH=/opt/rocm-3.10.0/opencl/lib

Now when I run

```
~$ /usr/bin/clinfo 
dlerror: libtinfo.so.5: cannot open shared object file: No such file or directory

~$ /opt/rocm-3.10.0/opencl/bin/clinfo 
dlerror: libtinfo.so.5: cannot open shared object file: No such file or directory
ERROR: clGetPlatformIDs(-1001)
```

I tried to install manually on ubuntu libtinfo-dev, but that installed /usr/lib/x86_64-linux-gnu/libtinfo.so.6 and did not fix the problem.

Unless I'm doing something wrong, this seems a serious issue, affecting one of the supported OSes (Ubuntu 20.04). I'd like to have at least a workaround.

**Comment by baryluk** [comment]
I belive the culprit, might be this file:

`/opt/rocm-3.10.0/opencl/lib/libamdocl64.so`:

It dynamically links to this file (I do have tinfo installed on my system, more on that later):

```
root@debian:~# ldd /opt/rocm-3.10.0/opencl/lib/libamdocl64.so
	linux-vdso.so.1 (0x00007ffe85fba000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feb112a6000)
	libamd_comgr.so.1 => /opt/rocm-3.10.0/opencl/bin/../lib/../../lib/libamd_comgr.so.1 (0x00007feb0a76f000)
	libhsa-runtime64.so.1 => /opt/rocm-3.10.0/opencl/bin/../lib/../../lib/libhsa-runtime64.so.1 (0x00007feb0a35a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007feb0a34f000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feb0a180000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feb0a03c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feb0a022000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feb0a000000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feb09e3b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007feb1161a000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007feb09e0d000)
	libhsakmt.so.1 => /opt/rocm-3.10.0/opencl/bin/../lib/../../lib/libhsakmt.so.1 (0x00007feb09be4000)
	libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007feb09bc9000)
	libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007feb09bb9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007feb09b9c000)
root@debian:~# 
```

This file is indeed in `rocm-opencl` / `rocm-opencl3.10.0` package:

```
root@debian:~# dpkg -S /opt/rocm-3.10.0/opencl/lib/libamdocl64.so
rocm-opencl: /opt/rocm-3.10.0/opencl/lib/libamdocl64.so
root@debian:~# 
```

However this package doesn't depend directly on libtinfo5:

```
root@debian:~# apt-cache show rocm-opencl | grep Depends
Depends: libelf-dev, comgr, hsa-rocr-dev
root@debian:~# 
```

I also checked transitive dependencies, and they don't provide or depend on `libtinfo5` either.

Fix would be to add `Depends: libtinfo5` to `rocm-opencl*` package.

@preda As a workaround in the mean time please do `sudo apt update; sudo apt install libtinfo5; sudo ldconfig;` this should help.

**Comment by ROCmSupport** [comment]
@preda, 
   Thank you for reaching out.  As @baryluk suggested could you kindly install libtinfo5 for the time being.
   We shall check this.

**Comment by preda** [comment]
Thank you, indeed "apt install libtinfo5" fixes the problem, and clinfo works.

**Comment by ROCmSupport** [comment]
Thanks @preda 
Anyway we are working with dev to map this dependency package as part OpenCL.
It will be part of one of the future releases(but not in 4.0 as 4.0 is on the way for release soon).
