### ISSUE TITLE
Rocm 3.10: OpenCL 2.0 device side enqueue not working on gfx906 and gfx803

### ISSUE THREAD

**Issue by Moading** [RadeonOpenCompute/ROCm#1326]
Hi,
due to the recent increase in activity of AMD emplyees on this site (which makes me really happy), I want to bring attention to an unresolved issue I reported about two years ago: device side enqueue, an OpenCL 2.0 feature is not working on any of the AMD GPUs I have tested.

I have reported the issue here #540 and #701. There is also a test program in #540 that demonstrates the problem.

Can someone please try to reproduce the problem, it should be a matter of a few minutes. I have tested this on ROCm 3.10 shortly after it was released. I had to roll back to an earliev version due to other problems. Therefore, I can not post any more information about the system, I simply do not have the resources to keep one machine in a broken state to debug ROCm. What I can tell however is that there are no beginner problems like no pcie atomics or wrong user group. I am using rocm-dkms if that matters.

Greetings!

**Comment by ROCmSupport** [comment]
Thanks @Moading for the appreciations and support.
We are looking into it and will get back asap.
Meanwhile can you please share details of below.
_/opt/rocm/opencl/bin/clinfo
/opt/rocm/bin/rocminfo_

Thank you.

**Comment by Moading** [comment]
@ROCmSupport Thanks for the fast reply. As I wrote above, I can not provide the details you requested because I have downgraded ROCm to 2.10. Could you please simply run the demonstrator program I attached to #540? Here is the link;

[bug.tar.gz](https://github.com/RadeonOpenCompute/ROCm/files/2386903/bug.tar.gz)

You have to delete lines 26 to 30 if you have only one GPU installed.

**Comment by ROCmSupport** [comment]
Thanks @Moading 
Code is working good in my machine with Vega64.
I got below output.

taccuser@taccuser-X399-DESIGNARE-EX:~/bug$ ./a.out
prob: a clGetDeviceIDs -1
ncpus: 0 ngpus: 1
testing GPU 0
a
b
c
passed
done

**Comment by Moading** [comment]
Thanks @ROCmSupport for testing, this is great news for me! I have to wait for a production run to finish and then I will try on my hardware. Could you please share which distribution and kernel you are using? I will report here in a few days...

**Comment by ROCmSupport** [comment]
Hi @Moading 
I am using Ubuntu 20.04.1 + 5.4.0-56 kernel (tried on a rock-dkms which has fix for this specific kernel).
Fixed rock-dkms package will be available in 3.10 repo in a day. You can try it.
Thank you.

**Comment by Moading** [comment]
Hi @ROCmSupport,
Today I have tested the latest ROCm version on my system and the test program hangs. The call to clFinish never returns.
I am using ubuntu 18.04.5 with kernel 5.4.0-58. Please find attached some commonly requestd output. What could be wrong with my setup?

$ dkms status 
amdgpu, 3.10-29, 5.4.0-58-generic, x86_64: installed
$ uname -a
Linux g6 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/5696828/rocminfo.txt)
[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/5696829/clinfo.txt)
[dmesg.txt](https://github.com/RadeonOpenCompute/ROCm/files/5696830/dmesg.txt)

Is it worth trying ubuntu 20.04.1? Or maybe it is just a BIOS setting?

Greetings

**Comment by ROCmSupport** [comment]
Hi @Moading 
Looks like some BIOS setting is required. Can you please use the latest BIOS.

I tried the same code on my Radeon7 (gfx906) only and successfully ran the program.

Environment: Radeon VII, Ubuntu 18.04.5 (5.4.0-58), 3.10-29
$ dkms status
amdgpu, 3.10-29, 5.4.0-58-generic, x86_64: installed

taccuser@taccuser-All-Series:~$ ./a.out
prob: a clGetDeviceIDs -1
ncpus: 0 ngpus: 1
testing GPU 0
a
b
c
passed
done

**Comment by Moading** [comment]
Hi @ROCmSupport,

thanks a lot for testing on a Radeon VII, this means the only difference between our systems is the mainboard and the CPU. Is it possible for you to share the output of dmesg and clinfo so that I could try to find the difference between our systems?

Is there any chance you could run the test program on a gfx803?

Greetings!

**Comment by ROCmSupport** [comment]
I dont have gfx803 with me.

Please find dmesg and clinfo logs.
[clinfo-R7.log](https://github.com/RadeonOpenCompute/ROCm/files/5701821/clinfo-R7.log)
[dmesg.log](https://github.com/RadeonOpenCompute/ROCm/files/5701823/dmesg.log)

**Comment by Moading** [comment]
hi @ROCmSupport,

Thanks for your logs! The only difference I can find is in dmesg. I t seems that on my system, BAR 0 and 2 are reassigned. Might this be relevant? The board is running the latest BIOS. Your board and CPU seem to be of the same generation as mine. I will play around a bit but I have no idea where to look.

[    2.647927] amdgpu 0000:04:00.0: BAR 2: releasing [mem 0x383ff0000000-0x383ff01fffff 64bit pref]
[    2.647928] amdgpu 0000:04:00.0: BAR 0: releasing [mem 0x383fe0000000-0x383fefffffff 64bit pref]
[    2.647953] amdgpu 0000:04:00.0: BAR 0: assigned [mem 0x380000000000-0x3803ffffffff 64bit pref]
[    2.647959] amdgpu 0000:04:00.0: BAR 2: assigned [mem 0x380400000000-0x3804001fffff 64bit pref]

Greetings

**Comment by Moading** [comment]
Dear @ROCmSupport, There is progres! I have tried a new installation of ubuntu 20.04.1 on the same mainboard (supermicro X10SRA-F) but no luck. Then i played around with the PCI BIOS settings and I found a working setup for Radeon VII. It turns out, that the test program works when "Above 4G encoding" is disabled. I was assuming that "Above 4G encoding" should be enabled in general so it might be worth investigating.

The behavior of gfx803 is more imortant to me because I'm using these GPUs for my production systems. Here is what I found:
1. I start the test program in one shell and it gets stuck in the clFinish call.
2. I start the test program in a second shell and the pogram in the first shell continues and reports correct results. The second test program is now stuck in the call to clFinish. The first program in the first shell is now stuck in the clFinish call for the second GPU.
3. I hit strg+c in the second shell and the first program completes with correct results.

This means that it is basically working but the call to clFinish gets stuck somehow. Executing a second instance of the program in parallel somehow gets things going. I am using a Radeon Pro Duo which contains a PCIe switch and two GPUs. If someone could fix this bug it would be fantastic and really usefull for me.

While performing the steps above, there is some output in dmesg:

[ 1192.244280] pcieport 0000:00:01.0: AER: Uncorrected (Non-Fatal) error received: 0000:02:08.0
[ 1192.244289] pcieport 0000:02:08.0: AER: PCIe Bus Error: severity=Uncorrected (Non-Fatal), type=Transaction Layer, (Requester ID)
[ 1192.248990] pcieport 0000:02:08.0: AER:   device [10b5:8747] error status/mask=00100000/00400000
[ 1192.251353] pcieport 0000:02:08.0: AER:    [20] UnsupReq               (First)
[ 1192.253691] pcieport 0000:02:08.0: AER:   TLP Header: 40000001 0300000f f0002014 02000000
[ 1192.256030] pcieport 0000:02:08.0: AER: Device recovery failed
[ 1204.006968] [drm] SQ instruction intr detected: se_id 1, sh_id 0, cu_id 1, simd_id 2, wave_id 0, vm_id 9 trap false, sq_ed_info.source SQ_EDC_INFO_SOURCE_INVALID: No EDC error has occurred.
[ 1204.513241] pcieport 0000:00:01.0: AER: Uncorrected (Non-Fatal) error received: 0000:02:08.0
[ 1204.513250] pcieport 0000:02:08.0: AER: PCIe Bus Error: severity=Uncorrected (Non-Fatal), type=Transaction Layer, (Requester ID)
[ 1204.517975] pcieport 0000:02:08.0: AER:   device [10b5:8747] error status/mask=00100000/00400000
[ 1204.520346] pcieport 0000:02:08.0: AER:    [20] UnsupReq               (First)
[ 1204.522683] pcieport 0000:02:08.0: AER:   TLP Header: 40000001 0300000f f0002014 02000000
[ 1204.525036] pcieport 0000:02:08.0: AER: Device recovery failed
[ 1204.541747] pcieport 0000:00:01.0: AER: Uncorrected (Non-Fatal) error received: 0000:02:10.0
[ 1204.541753] pcieport 0000:02:10.0: AER: PCIe Bus Error: severity=Uncorrected (Non-Fatal), type=Transaction Layer, (Requester ID)
[ 1204.543991] pcieport 0000:02:10.0: AER:   device [10b5:8747] error status/mask=00100000/00400000
[ 1204.545140] pcieport 0000:02:10.0: AER:    [20] UnsupReq               (First)
[ 1204.546259] pcieport 0000:02:10.0: AER:   TLP Header: 40000001 0400000f d0002020 02000000
[ 1204.547380] pcieport 0000:02:10.0: AER: Device recovery failed
[ 1207.486517] [drm] SQ instruction intr detected: se_id 1, sh_id 0, cu_id 7, simd_id 0, wave_id 0, vm_id 8 trap false, sq_ed_info.source SQ_EDC_INFO_SOURCE_INVALID: No EDC error has occurred.
 

I will now investigate if this bug applies also to gfx906

**Comment by Moading** [comment]
Dear @ROCmSupport,

I am observing the same behavior for gfx906, when "above 4G encoding is enabled":
1. start program in first shell, the program gets stuck in the clFinish call
2. start program in a second shell, program gets stuck in clFinish call, but the program in the first shell completes with correct results.

This bug need fixing, as it occurs on a flagship GPU on server hardware. Please let me kow if you need any further information. When the fix is found for gfx906, please also fix it for gfx803, I have been complaining about this for years!

Greetings!

**Comment by ROCmSupport** [comment]
Thanks @Moading for more updates.
I am assigning this issue to our OpenCL developers and please stay tuned for the updates.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @Moading 
Got update on this issue:

One requirement to run test_device_execution on ROCm is that SBIOS places the GPU's doorbell physical address to 44bit address space. if the system places it to 46bit address space, then the system doesn't support running test_device_execution on ROCm. Looks like your SBIOS shows the similar output and so device_enqueue is not supported on your system.

For example:

69:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega (rev 05)
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Vega
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr+ Stepping- SERR+ FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 32 bytes
        Interrupt: pin A routed to IRQ 30
        NUMA node: 0
        Region 0: Memory at 38b800000000 (64-bit, prefetchable) [size=8G]
        Region 2: Memory at 38ba40000000 (64-bit, prefetchable) [size=2M]
        Region 5: Memory at c6000000 (32-bit, non-prefetchable) [size=512K]
        Expansion ROM at <ignored> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

**Comment by ROCmSupport** [comment]
Please check and update.
Thank you.

**Comment by seesturm** [comment]
Out of couriosity I've also tried the test program. Seems to work for my system.
```prob: a clGetDeviceIDs -1
ncpus: 0 ngpus: 2
testing GPU 0
a
b
c
passed
done

testing GPU 1
a
b
c
passed
done
```
Relevant lspci output indicates that "44 bit" addresses are assigned
```
0d:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c3) (prog-if 00 [VGA controller])
        Subsystem: Micro-Star International Co., Ltd. [MSI] Vega 10 XL/XT [Radeon RX Vega 56/64]
        Flags: bus master, fast devsel, latency 0, IRQ 102, NUMA node 0
        Memory at 10000000000 (64-bit, prefetchable) [size=8G]
        Memory at 10200000000 (64-bit, prefetchable) [size=2M]
        I/O ports at 1000 [size=256]
        Memory at e1c00000 (32-bit, non-prefetchable) [size=512K]
        Expansion ROM at e1c80000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
44:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c3) (prog-if 00 [VGA controller])
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] RX Vega64
        Flags: bus master, fast devsel, latency 0, IRQ 103, NUMA node 1
        Memory at 48000000000 (64-bit, prefetchable) [size=8G]
        Memory at 47f00000000 (64-bit, prefetchable) [size=2M]
        I/O ports at 3000 [size=256]
        Memory at 8fc00000 (32-bit, non-prefetchable) [size=512K]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
```
Not sure if addresses are assigned by BIOS or Linux kernel. I'm using vanilla 5.8.16 without dkms. Apparently on startup addresses below 4GB are assigned - and get reassigned.
```
[    5.280233] amdgpu 0000:0d:00.0: BAR 2: releasing [mem 0xe0000000-0xe01fffff 64bit pref]
[    5.280234] amdgpu 0000:0d:00.0: BAR 0: releasing [mem 0xd0000000-0xdfffffff 64bit pref]
[    5.280250] pcieport 0000:0c:00.0: BAR 15: releasing [mem 0xd0000000-0xe01fffff 64bit pref]
[    5.280252] pcieport 0000:0b:00.0: BAR 15: releasing [mem 0xd0000000-0xe01fffff 64bit pref]
[    5.280253] pcieport 0000:00:03.1: BAR 15: releasing [mem 0xd0000000-0xe01fffff 64bit pref]
[    5.280261] pcieport 0000:00:03.1: BAR 15: assigned [mem 0x10000000000-0x102ffffffff 64bit pref]
[    5.280262] pcieport 0000:0b:00.0: BAR 15: assigned [mem 0x10000000000-0x102ffffffff 64bit pref]
[    5.280263] pcieport 0000:0c:00.0: BAR 15: assigned [mem 0x10000000000-0x102ffffffff 64bit pref]
[    5.280265] amdgpu 0000:0d:00.0: BAR 0: assigned [mem 0x10000000000-0x101ffffffff 64bit pref]
[    5.280271] amdgpu 0000:0d:00.0: BAR 2: assigned [mem 0x10200000000-0x102001fffff 64bit pref]
[    5.280277] pcieport 0000:00:03.1: PCI bridge to [bus 0b-0d]
[    5.280279] pcieport 0000:00:03.1:   bridge window [io  0x1000-0x1fff]
[    5.280281] pcieport 0000:00:03.1:   bridge window [mem 0xe1c00000-0xe1dfffff]
[    5.280282] pcieport 0000:00:03.1:   bridge window [mem 0x10000000000-0x102ffffffff 64bit pref]
[    5.280285] pcieport 0000:0b:00.0: PCI bridge to [bus 0c-0d]
[    5.280286] pcieport 0000:0b:00.0:   bridge window [io  0x1000-0x1fff]
[    5.280289] pcieport 0000:0b:00.0:   bridge window [mem 0xe1c00000-0xe1cfffff]
[    5.280291] pcieport 0000:0b:00.0:   bridge window [mem 0x10000000000-0x102ffffffff 64bit pref]
[    5.280295] pcieport 0000:0c:00.0: PCI bridge to [bus 0d]
[    5.280296] pcieport 0000:0c:00.0:   bridge window [io  0x1000-0x1fff]
[    5.280299] pcieport 0000:0c:00.0:   bridge window [mem 0xe1c00000-0xe1cfffff]
[    5.280302] pcieport 0000:0c:00.0:   bridge window [mem 0x10000000000-0x102ffffffff 64bit pref]
```

**Comment by ROCmSupport** [comment]
Thanks @seesturm for the output on your machine.
It works on 44-bit address space and so you got proper output.
Thank you.

**Comment by Moading** [comment]
@ROCmSupport thanks for the information. This should be added to the documentation.
