### ISSUE TITLE
rocm 3.10 hip missing

### ISSUE THREAD

**Issue by Dan-RAI** [RadeonOpenCompute/ROCm#1332]
fresh install of rocm 3.10 on ubuntu 18 via apt

rocm-dkms installed via apt. 

No HIP got installed !

How do I get HIP ? Do we have now to compile by ourselves ?

**Comment by Dan-RAI** [comment]
Managed to get hip, but now:

an't exec "/opt/rocm-3.10.0/llvm/bin/clang++": No such file or directory at /opt/rocm-3.10.0/hip/bin/hipconfig line 141.
Use of uninitialized value $HIP_CLANG_VERSION in pattern match (m//) at /opt/rocm-3.10.0/hip/bin/hipconfig line 142.
Use of uninitialized value $HIP_CLANG_VERSION in concatenation (.) or string at /opt/rocm-3.10.0/hip/bin/hipconfig line 145.
Can't exec "/opt/rocm-3.10.0/llvm/bin/clang++": No such file or directory at /opt/rocm-3.10.0/hip/bin/hipconfig line 141.
Use of uninitialized value $HIP_CLANG_VERSION in pattern match (m//) at /opt/rocm-3.10.0/hip/bin/hipconfig line 142.
Use of uninitialized value $HIP_CLANG_VERSION in concatenation (.) or string at /opt/rocm-3.10.0/hip/bin/hipconfig line 145.
Can't exec "/opt/rocm-3.10.0/llvm/bin/clang++": No such file or directory at /opt/rocm-3.10.0/hip/bin/hipconfig line 141.
Use of uninitialized value $HIP_CLANG_VERSION in pattern match (m//) at /opt/rocm-3.10.0/hip/bin/hipconfig line 142.
Use of uninitialized value $HIP_CLANG_VERSION in concatenation (.) or string at /opt/rocm-3.10.0/hip/bin/hipconfig line 145.
Can't exec "/opt/rocm-3.10.0/llvm/bin/clang++": No such file or directory at /opt/rocm-3.10.0/hip/bin/hipconfig line 141.
Use of uninitialized value $HIP_CLANG_VERSION in pattern match (m//) at /opt/rocm-3.10.0/hip/bin/hipconfig line 142.
Use of uninitialized value $HIP_CLANG_VERSION in concatenation (.) or string at /opt/rocm-3.10.0/hip/bin/hipconfig line 145.
Can't exec "/opt/rocm-3.10.0/llvm/bin/clang": No such file or directory at /opt/rocm/bin/hipcc line 203.
Use of uninitialized value $HIP_CLANG_VERSION in pattern match (m//) at /opt/rocm/bin/hipcc line 204.
Use of uninitialized value $HIP_CLANG_VERSION in concatenation (.) or string at /opt/rocm/bin/hipcc line 208.
Use of uninitialized value $HIP_CLANG_VERSION in concatenation (.) or string at /opt/rocm/bin/hipcc line 846.
HIP version: 3.10.20465-f9876b8d
Can't exec "/opt/rocm-3.10.0/llvm/bin/clang": No such file or directory at /opt/rocm/bin/hipcc line 895.
failed to execute: No such file or directory

**Comment by ROCmSupport** [comment]
Hi @Dan-RAI 
Thanks for reaching out.
Looks like ROCm installation did not go well.
Can you please share the procedure you followed in step-by-step manner.

I tried on 2 different machines(18.04.5, 20.04.1) and installation went well in both machines.

**Comment by Dan-RAI** [comment]
ok, got hipcc running now:

hipcc --version
HIP version: 3.10.20465-f9876b8d
clang version 12.0.0 (/src/external/llvm-project/clang 60f39e2924d51c1e8606f2135f95e9047fb1da5d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-3.10.0/llvm/bin

There was still a hip and llvm residual which had to be removed by hand before re-installing rocm.
