### ISSUE TITLE
pytorch support?

### ISSUE THREAD

**Issue by christofer-f** [RadeonOpenCompute/ROCm#1334]
Hi!

I am using pytorch. 

Could you provide me with a youtube link where you successfully run GPU accelerated pytorch on RADEON hardware? 

Br,
Christofer

**Comment by xuhuisheng** [comment]
```
True
Devices:1
[_CudaDeviceProperties(name='Device 67df', major=8, minor=0, total_memory=8192MB, multi_processor_count=36)]
tensor(4., device='cuda:0', grad_fn=<SumBackward0>)

```

Sorry for no yourube video.
You could compile pytorch by yourself or use docker. there is no offically release.

* compile : https://github.com/acai66/Pytorch_ROCm_whl
* docker : https://hub.docker.com/r/rocm/pytorch

**Comment by christofer-f** [comment]
Thx for the reply! 
I use pytorch-lightning btw. It's much better than TF   :-)

And now when Radeon GPUs are getting competitive. 
I wanted to see if this could be a viable option.
