### ISSUE TITLE
When will the 5700xt be supported?

### ISSUE THREAD

**Issue by TravisCao** [RadeonOpenCompute/ROCm#1338]

**Comment by aliPMPAINT** [comment]
Yes, I'm tired of months of trying to get it run on RX 5500M, when will you eventually have support for RDNA and RDNA 2 architecture? What preventing it?

**Comment by ROCmSupport** [comment]
Hi @TravisCao
Thanks for reaching out.
We got requests for Navi hardware to be added to POR for next year.
We will share updates, if any, via our ROCm documentation.
Thank you.
