### ISSUE TITLE
Lab analysis of Bristol ridge

### ISSUE THREAD

**Issue by trinayan** [RadeonOpenCompute/ROCm#134]
I was wondering if there is any update on the lab testings of HP 15t V1M95AV containing the new bristol ridge APU's. Are there any know issues with the latest rocm drivers for that device? Also is the functionality to control cpu,gpu,memory frequencies exposed to the user on this platform using something like rocm-smi?

**Comment by gstoner** [comment]
ROCm SMI does not work on the APUs. currently, it use different interface then the dGPU's.   

I was just notified by the president of HSA Foundation he has three of these laptop working with ROCm 1.6
