### ISSUE TITLE
ROCm support for gfx1011

### ISSUE THREAD

**Issue by amrragab8080** [RadeonOpenCompute/ROCm#1341]
The Amazon G4ad instance have AMD Radeon V520 GPUs with device name ```gfx1011``` unfortunately many of the ROCm utils do not have binaries supporting ```gfx1011``` 
```
2020-12-17 23:03:23.004276: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libamdhip64.so
/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Fatal Python error: Aborted
```
docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video rocm/tensorflow

But I do see the output from ```rocminfo```
```
*******                  
Agent 2                  
*******                  
  Name:                    gfx1011                            
  Uuid:                    GPU-XX                             
  Marketing Name:          Device 7362                        
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 29538(0x7362)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1150                               
  BDFID:                   240                                
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   2 
```

**Comment by ROCmSupport** [comment]
Hi @amrragab8080 
Thanks for reaching out.
We are not officially supporting Navi series of cards at present.
We have plans to support in 2021 and we will update accordingly.
Thank you.

**Comment by lingfanyu** [comment]
I also tried installing ROCm on Amazon G4ad instance following [this guide](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html).

The installation looks successful. However, `/opt/rocm/bin/rocminfo` returns:
> ROCk module is NOT loaded, possibly no GPU devices
Unable to open /dev/kfd read-write: No such file or directory
ubuntu is member of video group
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

and `/opt/rocm/bin/rocm-smi` returns:
> ERROR:root:ROCm SMI returned 8 (the expected value is 0)

I hope to see the official support AMD Radeon V520 GPUs and AWS G4ad instance soon!

**Comment by dsahni** [comment]
Hi @ROCmSupport , do you have any estimates on when ROCm support for AWS G4ad will be available?

**Comment by ROCmSupport** [comment]
Hi @dsahni 
Internal testing is happening and so can not comment on exact estimates right now.

**Comment by monkeyhippies** [comment]
Hello @ROCmSupport do you have nay update on support for AWS G4ad instances?? Thank you
