### ISSUE TITLE
Which ROCm version is compatible with Ubuntu 20.04.01 + Rx 6800 

### ISSUE THREAD

**Issue by jhb115** [RadeonOpenCompute/ROCm#1344]
Hi, I would like to know which version of ROCm is compatible with Ubuntu 20.04.01 + Rx 6800.

**Comment by jhb115** [comment]
Hmm... I see that Rx 6800 is not one of the gpus officially supported by ROCm. Is there any timeline or schedule when this ROCm will also support on Rx 6800? 

Is there any bypassing/unofficial way to run pytorch on Rx 6800?

**Comment by lorisgir** [comment]
[This](https://github.com/RadeonOpenCompute/ROCm/issues/1180#issuecomment-746164720) is all we know regarding RDNA2 support

**Comment by johnbridgman** [comment]
> Hi, I would like to know which version of ROCm is compatible with Ubuntu 20.04.01 + Rx 6800.

None at the moment, unfortunately. 

The 20.45 packaged drivers include an OpenCL implementation based on the lower levels of the ROCm stack (kernel code up through language runtimes) but HIP and library support still require additional work.

**Comment by jhb115** [comment]
Thank you for the reply. That's quite unfortunate to hear. Really hope ROCm version compatible with the AMD 6000 series gpus comes out in the near future....
