### ISSUE TITLE
Flags used for building ROCm packages for Ubuntu/CentOS?

### ISSUE THREAD

**Issue by darjankrijan** [RadeonOpenCompute/ROCm#1348]
As I can't find source packages on http://repo.radeon.com/rocm, could you disclose which flags you use for building ROCm packages for Ubuntu/CentOS.

Given the hardware requirements being essentially AMD Zen and newer or Intel Haswell and newer, I'd expect something like
```-march=haswell``` or ```-march=core-avx2``` which are both compatible with AMD Zen.
Most importantly the ```-march``` flag as well as the ```-O``` optimization level used for the repo packages would be of interest.
Any more flags that are used would be appreciated as well.

I'd propose to the package maintainers for Arch Linux over at https://github.com/rocm-arch/rocm-arch to use these flags to be in line with the upstream built packages so they achieve comparable CPU features and performance.

**Comment by ROCmSupport** [comment]
Thanks @darjankrijan for reaching out.
Will reach respective team and help you out

**Comment by ROCmSupport** [comment]
Hi @darjankrijan 
We can not fulfill this requirement as we are not owning/making rocm on arch, hence I cannot comment on "seeking all the flags for building rocm-arch".
Hope it clarifies.
Thank you.

**Comment by darjankrijan** [comment]
Uhm, I asked about flags used for building rocm for Ubuntu/CentOS (AMD provides repositories for these) so these can be synchronized with the community build for Arch Linux.
