### ISSUE TITLE
No GFX10xx / Navi Support? 

### ISSUE THREAD

**Issue by hesenp** [RadeonOpenCompute/ROCm#1349]
Hey folks! Congrats on releasing ROCm 4.0 . I'm surprised to find that there's no updated support for GFX10xx/Navi series of consumer graphics card. Do I read this correctly? 

I'm surprised that this is happening. Can anyone please clarify if there exists plans to support these consumer grade graphics card in the near future? This sounds like a dramatic failure in AMD's product management on not aligning ROCm 4.0 support with hottest consumer product release.  

I might consider selling my 5700xt if there's no immediate support any time soon.

**Comment by ROCmSupport** [comment]
Hi @hesenp 
Thanks for reaching us out.
We are currently not supporting Navi at present.
But we have plans to support in future. Please stay tuned for the updates.
Thank you.

**Comment by aliPMPAINT** [comment]
@ROCmSupport , could you please explicitly state what Navi series we're talking about? RX 5000s and RX 6000s or just RX 6000s? Like both RDNA and RDNA 2 architecture, or just RDNA 2?

**Comment by Wk20017** [comment]
@ROCmSupport 十分期待ROCm对rx5000系列的支持！希望尽快发布新版本！

**Comment by xuhuisheng** [comment]
@hesenp @aliPMPAINT  @Wk20017 
Here is a good news, that vdrhtc said he can run pytorch on RX 5500.
https://github.com/RadeonOpenCompute/ROCm/issues/1306#issuecomment-751230911

**Comment by Wk20017** [comment]
> @hesenp @aliPMPAINT @Wk20017
> Here is a good news, vdrhtc said he run pytorch successfully on RX 5500.
> [#1306 (comment)](https://github.com/RadeonOpenCompute/ROCm/issues/1306#issuecomment-751230911)

Thanks！My GPU is rx5700. I had looked for your comments and i found my GPU‘s version has not been supported perfectly, and i will wait for the next 4.1 version.

**Comment by ROCmSupport** [comment]
Hi @aliPMPAINT  @Wk20017 
I can not comment right now on specific Navi variant.
Please stay tuned or the updates.
Thank you.

**Comment by TheBubblePopped** [comment]
I returned mine.
