### ISSUE TITLE
rvs/man/rvs.1 should be installed in share/man/man1/ instead

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1359]
I believe this file

`/opt/rocm-4.0.0/rvs/man/rvs.1`

should be installed here instead:

`/opt/rocm-4.0.0/share/man/man1/rvs.1`

(And `/opt/rocm-4.0.0/rvs/man` directory removed).

`rocm-validation-suite4.0.0` 3.10.40000  on Debian / Ubuntu.

Regards,
Witold

**Comment by ROCmSupport** [comment]
Hi @baryluk ,
 
    Thank you for bringing this issue to our light. Request you to kindly let us know what is the problem you are facing for which you are giving this solution.

**Comment by baryluk** [comment]
It is just a general packaging complain. When one sets up the paths in `/etc/manpath.config` or using `MANPATH` variable, it is better to set one canonical path, than two or three. It is more user friendly and more standards friendly.

**Comment by ROCmSupport** [comment]
Go an update:
RVS team is going to incorporate the changes.
We will let you know once the changes are pushed, please stay tuned for the updates.
Thank you

**Comment by baryluk** [comment]
Thanks. Appreciated.

**Comment by ROCmSupport** [comment]
Hi @baryluk 
Good news. Issue is fixed and the changed are merged into ROCm 4.2 code.
Have verified internally and issue is fixed.

master@test:/opt/rocm-4.2.0/share/man/man1$ ls
rocgdb.1  rvs.1
