### ISSUE TITLE
How to figure out the CPUStr e.g. "gfx1010" at runtime with HIP functions?

### ISSUE THREAD

**Issue by fwinter** [RadeonOpenCompute/ROCm#1362]
My application uses LLVM's AMDGPU backend to generate GPU kernels at runtime. In order to instantiate the correct TargetMachine I'd need to have the "CPUString" like "gfx908", "gfx1010", etc.

The HIP functions hipDeviceComputeCapability and hipDeviceGetName get me close but not really there without some educated guessing. Compute capability is returned as major=10, minor=1. How do I arrive from that to the correct CPU string "gfx1010"? It can't be "gfx${major}${minor}0" since that wouldn't work for "gfx908". This needs to work for any card.

If this is currently not possible can I suggest adding those features?

**Comment by ROCmSupport** [comment]
@fwinter ,
You may check the [HIP programming interface](https://github.com/RadeonOpenCompute/ROCm/blob/master/HIP_Programming_Guide_v4.0.pdf) for specific HIP API

You may also get the same information using any shell. For eg :
      `/opt/rocm/bin/rocminfo | less | grep gfx`
  Which shall give you the output like following 
   
```
  Name:                    gfx900
      Name:                    amdgcn-amd-amdhsa--gfx900:xnack-

```  

This can be encapsulated in any string & pass to your host code which you are using to write the kernel.

Hope this helps.

**Comment by ROCmSupport** [comment]
@fwinter ,

  you can use API :  `hipGetDeviceProperties`

```
     hipGetDeviceProperties(&props, deviceId);
    std::cout<<"gcnArchName: "<<props.gcnArchName<<std::endl;
```

gives me desired output 

`gcnArchName: gfx906`

Hope this solves your query
