### ISSUE TITLE
Ubuntu 20.04.1 ROCm v4.x Blender - Memory access fault by GPU node-1

### ISSUE THREAD

**Issue by Baszczer** [RadeonOpenCompute/ROCm#1363]
Ubuntu 20.04.1
RX 5700 XT
Ryzen 3900X

When I try to bake Blender crashes, output from terminal:

Cycles: compiling OpenCL program base...
Cycles: compiling OpenCL program bake...
Kernel compilation of base finished in 0.49s.
Kernel compilation of bake finished in 44.12s.
Cycles: compiling OpenCL program background...
Kernel compilation of background finished in 9.34s.
Split kernel error: failed to load kernel_path_init
Memory access fault by GPU node-1 (Agent handle: 0x7f715f786c00) on address 0x7f706aade000. Reason: Page not present or supervisor privilege.
./apps.sh: line 38:  3244 Aborted                 (core dumped) /home/karol/port_apps/blender-2.83.10-linux64/blender

**Comment by ROCmSupport** [comment]
@Baszczer, 
    I appears you are facing a graphics issue. This repository is for Compute ( Machine learning / AI ) part. 
    I would request you to kindly post the problem to the right forum.

**Comment by Baszczer** [comment]
> @Baszczer,
> I appears you are facing a graphics issue. This repository is for Compute ( Machine learning / AI ) part.
> I would request you to kindly post the problem to the right forum.

Could you be so kind and would you point me to the right forum? I'm lost.

**Comment by ms178** [comment]
@Baszczer For AMD-related Kernel issues I'd suggest to file a bug over at: https://gitlab.freedesktop.org/drm/amd/-/issues/

**Comment by Baszczer** [comment]
> @Baszczer For AMD-related Kernel issues I'd suggest to file a bug over at: https://gitlab.freedesktop.org/drm/amd/-/issues/

Thank you

**Comment by clicks** [comment]
@ROCmSupport
I'm suffering from the same problem as @Baszczer  with the rocm opencl implementation in Blender. From your answer it seems like rocm is only geared towards computational tasks. But the latest amdgpu drivers deprecated all OpenCL backends and will only support the rocm/rocr backend. Hence rocm seems to be the way for OpenCL on AMD GPUs.

Can you tell me which project/department/repo will be offering an OpenCL implementation for graphical tasks?

**Comment by ROCmSupport** [comment]
Hi @clicks 
Though ROCm is mainly focused for compute, it also supports Graphics also, but medium priority.
So, in the same lanes, ROCm supports Blender, but its broken at present. Our developers are working on the fix. Please stay tuned for the updates.
Thank you.

**Comment by Baszczer** [comment]
> @ROCmSupport
> I'm suffering from the same problem as @Baszczer with the rocm opencl implementation in Blender. From your answer it seems like rocm is only geared towards computational tasks. But the latest amdgpu drivers deprecated all OpenCL backends and will only support the rocm/rocr backend. Hence rocm seems to be the way for OpenCL on AMD GPUs.
> 
> Can you tell me which project/department/repo will be offering an OpenCL implementation for graphical tasks?

Hi, I got the info from AMD:
"The issue has been reproduced and a fix has been identified and will be in implemented in 21.Q2 driver that will be released soon.
Thank you for your patience"

**Comment by ROCmSupport** [comment]
Hi @clicks 
The latest amdgpu drivers still support OpenCL backends and you can still use it.
