### ISSUE TITLE
OpenCL ICD?

### ISSUE THREAD

**Issue by yaxxie** [RadeonOpenCompute/ROCm#1369]
Does the ROCM distributions provide an OpenCL ICD file? If so, which component is it bundled with?
If not, is it possible to produce/provide one?

**Comment by xuhuisheng** [comment]
I am not familiar with OpenCL. Maybe this is what you find?
https://github.com/RadeonOpenCompute/ROCm/blob/master/default.xml#L30

**Comment by ROCmSupport** [comment]
Thanks @yaxxie for reaching us.
Hope you got the answer from previous comments.
Please let me know if you need more information.
Thank you.

**Comment by seesturm** [comment]
Not exactly sure what the issue reporter is asking but I'd say the ICD (Installable Client Driver) is in file _/opt/rocm-4.0.0/opencl/lib/libamdocl64.so_ which is part of the _rocm-opencl_ package.

**Comment by yaxxie** [comment]
I took a look at what some .icd files contain it seems to just contain an SO name -- what I was trying to get at was if the distribution could automatically set this up upon installation so that use doesn't need to put a .icd file containing the so-name into /etc/OpenCL/vendors/ (I'm also not sure how mine appears to work correctly because I didn't put the rocm installation on library path but it seems like openCL apps are automatically finding the rocm openCL)

**Comment by ROCmSupport** [comment]
Hi @yaxxie 
I did not get your point completely.
In my case, when I install ROCm or OpenCL/ROCm, icd file will be mapped/created automatically as part of installation under /etc/OpenCL/vendors and things work perfect.
I never set anything manually and the things happened automatically for me.
Hope its clear.
Please let me know if you need more information. Else you/I can close this issue.
Thank you.

**Comment by yaxxie** [comment]
Thanks if it is meant to be created automatically then I guess I'll just try yo figure out why that didn't happen in my case

**Comment by ROCmSupport** [comment]
Yes, it meant to be created automatically.
Request to try on a fresh OS once and you will come to know.

Thank you.

**Comment by ROCmSupport** [comment]
Hi @yaxxie 
Hope your issue is resolved, request you to close this ticket.
Thank you.

**Comment by yaxxie** [comment]
I had this issue.

Another user mentioned same issue in another thread.

https://github.com/RadeonOpenCompute/ROCm/issues/567#issuecomment-756179833

Workaround is easy, so you can close at your discretion.

**Comment by ROCmSupport** [comment]
Thanks @yaxxie 
I am closing this as per the information shared by us.
