### ISSUE TITLE
Does ROCm support concurrent kernel execution with OpenCL?

### ISSUE THREAD

**Issue by WyldeCat** [RadeonOpenCompute/ROCm#1370]
Let's suppose there are multiple command queues with single device.
If multiple cl_kernel with very small global work item size are enqueued to each queues, are they executed concurrently?

I'm using RX 5700 XT, ubuntu 20.04 and ROCm 3.10.0.

**Comment by ROCmSupport** [comment]
Hi @WyldeCat 
Thanks for reaching out.
**Yes, ROCm supports concurrent kernel execution with OpenCL** but not with all hardware.
I will get more information on supported hardware.

But I can not comment on RX5700 XT as we are not officially supporting them right now.

**Comment by WyldeCat** [comment]
Thanks @ROCmSupport 
please let me know if RX6900 xt supports concurrent kernel execution.

**Comment by ROCmSupport** [comment]
Hi @WyldeCat 
Got an update from OpenCL developer in below way.

_I think all ASICs supported by ROCM support concurrent execution. As long as there's no barrier to mandate a wait, cp would run kernels concurrently as long as hw resources are available._

Regarding RX6900, we are not supporting this hardware right now and so can not talk on this.

**Comment by ROCmSupport** [comment]
Please let me know if you need any more information, otherwise I am going to close this issue.
Thank you.
