### ISSUE TITLE
ROCm 4.0.0 unable to detect AMD RTX 580 Gpu

### ISSUE THREAD

**Issue by SyedMuzzu** [RadeonOpenCompute/ROCm#1373]
Hello ! 
I have successfully installed rocm on Ubuntu 20.04(kernel 5.6 oem). However, rocminfo or clinfo do not detect the gpu. 

lspci | grep VGA :

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 6000 (rev 09)
0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)

/opt/rocm/opencl/bin/clinfo

Number of platforms: 1
  Platform Profile: FULL_PROFILE
  Platform Version: OpenCL 2.1 AMD-APP (3188.4)
  Platform Name: AMD Accelerated Parallel Processing
  Platform Vendor: Advanced Micro Devices, Inc.
  Platform Extensions: cl_khr_icd cl_amd_event_callback cl_amd_offline_devices

  Platform Name: AMD Accelerated Parallel Processing
Number of devices: 0      

In the HSA agents, it just displays a single agent and is unable to recognize the gpu.

==========        
HSA Agents              
==========              
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz

ROCm supports PCIe 2.0 and I have made necessary changes from the TB3 <->TB2 (Thunderbolt ) and the laptop recognizes the gpu but rocm is unable to. So is this  a PCIe problem or AMD drivers problem.

Can someone help me here ?

**Comment by xuhuisheng** [comment]
rx580 required PCIe atomics. You can check whether there is related info from **dmesg | grep kfd**

Furthermore ROCm drop gfx580 official support now.
https://github.com/RadeonOpenCompute/ROCm/issues/1353

**Comment by ROCmSupport** [comment]
Hi @SyedMuzzu for reaching us out.
We are not officially supporting gfx8 devices anymore. But some things might work.
As mentioned above, gfx8 based devices need PCIe atomics. So you should have a CPU which supports PCIe atomics.
