### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by kev009** [RadeonOpenCompute/ROCm#138]
Hi,

 I run a core engineering group at one of the largest CDNs.  We use FreeBSD for a variety of reasons and find it offers a pleasant long term development experience with stable APIs and KPIs over Linux, while meeting a variety of other complex demands.  We are experimenting with ML in addition to other GPU workloads such as transcoding.  Will AMD support ROCm on FreeBSD?  A lot of the effort to do so is already done:  https://github.com/freebsddesktop.  Nvidia offers a driver as an interesting data point.

**Comment by gstoner** [comment]
The FreeBSD Comunity has shown interest in this, right now we have few more Linux distro to finish out REHL and SUSE first in next few quarters for existing customers before we could entertain this.   
 
But I know our Business Development team would love to talk to you about the opportunity.    

 One thing our driver stack is a bit more complex than a standard graphics driver, there is the KFD and Thunk + ROCr, modified TTM interface. But weight now is all the components that sit on the stack that would need to be ported and tested as well.  HCC, OpenCL, HIP, Math Libraries and applications

**Comment by gstoner** [comment]
We may see some activity here now.   I know more soon

**Comment by kev009** [comment]
@gstoner thanks, I will try to come in through sales.  We've lost our past contacts with AMD but the modern EPYC and Radeon look like prime contenders for our workloads.

**Comment by yaxen** [comment]
@gstoner Any updates about FreeBSD support?

**Comment by SairesArt** [comment]
+1 for some BSD love

**Comment by ocert** [comment]
+1 as well. Any news? Regards.

**Comment by dchmelik** [comment]
I'd also love to see FreeBSD Unix ROCm (and ROCm for any main/other strictly Unix[-like] (i.e., non-systemd, etc.) OSes, like *BSD (three classic) & OpenSolaris/IllumOS Unixes, Slackware GNU/Linux.  I know ROCm builds on a newer non-systemd GNU/Linux.)  My only AMDGPU-pro option had been OSes I questioned were worth extreme emotional pain of systemd, and many other issues, just for newer Radeon.  Of course, my first choice would be FreeBSD & Slackware w/ROCm,  but eventually, Unix[-like] variety would be good.

**Comment by inf3rno** [comment]
Any update on this?

**Comment by pbpjackd** [comment]
> We may see some activity here now. I know more soon

Did this thread continue elsewhere or is there simply no news on that topic ?

**Comment by ROCmSupport** [comment]
This is a closed thread and so i request/recommend to file a new issue, if any. Thank you.

**Comment by inf3rno** [comment]
> > We may see some activity here now. I know more soon
> 
> Did this thread continue elsewhere or is there simply no news on that topic ?

Idk. It would have been nice to have at least ROCm support, if we don't have CUDA. It is still better than CPU...

**Comment by rajhlinux** [comment]
Also would like to use ROCm on FreeBSD... Need it for machine learning on AMD GPUs.

**Comment by pavelica** [comment]
I'm also interested in Freebsd support.

**Comment by elliejs** [comment]
I've gotten a sizeable chunk of this to build, but without the kernel driver FreeBSD support still seems like more than a few patches to makefiles here and there. Adding another name to the pile requesting FreeBSD support.
