### ISSUE TITLE
Radeon repository URL issue (ROCm 1.6)

### ISSUE THREAD

**Issue by ekondis** [RadeonOpenCompute/ROCm#139]
According to the documentation the repository URL is not correct. For instance, the GPG key in the wget command should be available at:

`http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key`

However, the actual URL seems to be:

`http://repo.radeon.com/rocm/apt/debian/debian/rocm.gpg.key`

So, one has to add the "debian/" suffix to all URLs for the commands to work.

**Comment by jedwards-AMD** [comment]
A symbolic link was causing an extra level of indirection. This has been corrected. The correct URL is:

 http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key

**Comment by ekondis** [comment]
Yes, it seems to be correct now.
