### ISSUE TITLE
Native support for ROCm in Hadoop Yarn

### ISSUE THREAD

**Issue by elukey** [RadeonOpenCompute/ROCm#1391]
Hi everybody,

In the Hadoop 3.x ecosystem there seems to be space for a native non-Nvidia GPU support, see:

https://issues.apache.org/jira/browse/YARN-10225
https://issues.apache.org/jira/browse/YARN-8891

From Hadoop 3.3.0 (still not released) it will be possible to create custom jars to support various devices, like new GPUs, something that for the moment is limited to Nvidia cards. I think that it would be great to have an official Hadoop plugin maintained by ROCm devs, that eventually may end up in Hadoop's main repo?

Hadoop users can still target ROCm GPUs via solutions like https://github.com/criteo/tf-yarn, but the Yarn scheduler will still be unware of GPUs as resources, so not really a fine grained solution. I'd be happy to help in case needed, this seems to be a very interesting project to reduce the monopoly from Nvidia :)

Thanks in advance!

**Comment by ROCmSupport** [comment]
Thanks @elukey for reaching us.
I will get some information on this and update you asap.

**Comment by elukey** [comment]
Hi @ROCmSupport, any news? :)

**Comment by ROCmSupport** [comment]
Hi @elukey 
We are going to discuss on this today, I hope I will share an update on this soon.
Thank you.

**Comment by elukey** [comment]
@ROCmSupport gentle ping :)

**Comment by ROCmSupport** [comment]
Thanks @elukey for the ping.
As per out last discussion, this will be seen as a P2 item. Anyway I am going to get some update by today/tomorrow, will reach you asap.
Thank you.

**Comment by elukey** [comment]
@ROCmSupport any news :)
