### ISSUE TITLE
ROCm on Mac

### ISSUE THREAD

**Issue by poodarchu** [RadeonOpenCompute/ROCm#1392]
When will ROCm support macOS with intel/AMD CPU + AMD GPU?

**Comment by ROCmSupport** [comment]
Thanks @for reaching us.
AFAIK, we do not support MAC's or MacOS. No plans to do so.
Anyways, I will talk to BU team and get more information on this.
Thank you.

**Comment by Photonico** [comment]
> Thanks @for reaching us.
> AFAIK, we do not support MAC's or MacOS.
> Anyways, I will talk to BU team and get more information on this.
> Thank you.

Hi,
Did the talking have any result？ 
Thx

**Comment by ROCmSupport** [comment]
Hi @Photonico 
We do not have plans to support MacOS as per the current information.
Thank you.
