### ISSUE TITLE
Device::callbackQueue aborting with status: 0x100f

### ISSUE THREAD

**Issue by zjin-lcf** [RadeonOpenCompute/ROCm#1393]
Can you please explain the meaning of the status ?

:0:rocdevice.cpp            :2303: 768423197593 us: Device::callbackQueue aborting with status: 0x100f

Thanks

**Comment by ROCmSupport** [comment]
Hi @zjin-lcf for reaching out.
Looks like **specific kernel is broken and calculation is aborted**.

Can you please share the exact steps to reproduce the problem.

**Comment by ROCmSupport** [comment]
Hi @zjin-lcf 
Please update us to move this issue to next level.
Else request you to close this ticket, if you are not seeing/required anymore.
Thank you.

**Comment by zjin-lcf** [comment]
Thank you.
