### ISSUE TITLE
Versionless RPM repositories not pointing to current release

### ISSUE THREAD

**Issue by pjgeorg** [RadeonOpenCompute/ROCm#1408]
Both https://repo.radeon.com/rocm/yum/rpm/ and https://repo.radeon.com/rocm/centos8/rpm/ point to version 4.0.0. However the current release is 4.0.1.

Users probably expect the versionless repository link to always point to the current release. This is actually not the first time this happened. The same happened with previous micro (x.x.1) releases. For major and minor releases the versionless repo has always been updated.

**Comment by ROCmSupport** [comment]
Hi @pjgeorg 
Thanks for reaching out.
**Actually this is not an issue, is the new process.**
We do not wish to change/update repos with every point release as point release is with some specific changes and we do not expect all users to try for the same and its not required too. 

https://repo.radeon.com/rocm/yum/rpm/ --> Refers to the major release only
https://repo.radeon.com/rocm/yum/4.0.x/ --> Refers to the point releases
So when you wish to try with the latest point release, I recommend to check for https://repo.radeon.com/rocm/yum/ space and look for the latest point release. Map accordingly and you are able to install it.
Hope it helps.
Feel free me reach for any other query.
Thank you.

**Comment by pjgeorg** [comment]
Thanks for your reply.

This actually makes no sense to me as users of https://repo.radeon.com/rocm/yum/rpm/ will be hit by unexpected major releases anyway. Hence users who do not want the version to be changed should rely on specifiying a particular version, e.g. https://repo.radeon.com/rocm/yum/4.0.0/
With your new process using https://repo.radeon.com/rocm/yum/rpm/ is now neither suitable for users that want to always have the current version nor for users who want to install a particular version.
I honestly can't think of any user who wants to get major release updates automatically but no point release updates.

Anyway it's the new process, fine for me. At least I now know what to do and what to expect.
However you should probably update https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#centos-rhel to reflect this new process.

**Comment by ROCmSupport** [comment]
Thanks @pjgeorg for the feedback.
The concept of point releases are redefined now.
These point releases are only special builds, generated only in case of any specific issue/changes. So major release builds will serve all f the things mostly.
Anyways, I will make sure to update this point in our docs.
Thank you much.

**Comment by ROCmSupport** [comment]
Docs updated with this information now.
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

ROCm Repositories
    For major releases - https://repo.radeon.com/rocm/yum/rpm/
    For point releases - https://repo.radeon.com/rocm/yum/4.3.x/
