### ISSUE TITLE
Incomplete installation downgrading rocm from 4 to 3.9.1?

### ISSUE THREAD

**Issue by staticdev** [RadeonOpenCompute/ROCm#1409]
I tried deleting the folder /opt/rocm-4.0.1 and then installing rocm-3.9.1 (since I realized it does not support Radeon RX580 anymore). But when I try to run tensorflow I get:

```
ImportError: libamdhip64.so.4: cannot open shared object file: No such file or directory
```

Is there a way to fix that?

**Comment by ROCmSupport** [comment]
Hi @staticdev 
Hope your issue resolved.
Thank you.
