### ISSUE TITLE
About AMD Vega ISA Architecture Manual?

### ISSUE THREAD

**Issue by oscarbg** [RadeonOpenCompute/ROCm#141]
Hi don't know if it's correct place to ask but wanting to see new Vega ISA  (GFX9 ISA) manual similar to the last one "AMD GCN3 ISA Architecture Manual" detailing Polaris/Fiji ISA..
Should be coming soon, at least possibly shortly after Siggraph Radeon Vega reveal?
thanks..

**Comment by gstoner** [comment]
They have it I need to talk to the architecture group again about releasing the docuement.
