### ISSUE TITLE
apt repo does not exist for 3.10.0

### ISSUE THREAD

**Issue by staticdev** [RadeonOpenCompute/ROCm#1410]
Since you dropped support for many boards from 4.0.0 on, it would be very nice if you added the apt repo for 3.10.0 that is missing:

https://repo.radeon.com/rocm/apt/3.10.0

**Comment by ROCmSupport** [comment]
Thanks @staticdev for reaching out.
Request you to use https://repo.radeon.com/rocm/apt/3.10/ for 3.10 space.
Thank you.
