### ISSUE TITLE
Ubuntu 20.04 clean installation ... (Not working).

### ISSUE THREAD

**Issue by incardon** [RadeonOpenCompute/ROCm#1414]
I open this ticket hoping could help me and somebody in the same situation. Trying to install RocM 4.0 on ubuntu 20.04 (Clean) simply it does not works. 
I have AMD Ryzen 5 on Asus B350M + RX Vega 64 on Ubuntu 20.04. (According to documentation this configuration should be more than supported)

I followed exactly

https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu

The first problem is that kernel 5.8 is not supported and rocm-dkms does not work. This is documented, it is unfortunately not documented how to work around.

The way I did is to install kernel 5.4.0-67 with

`sudo apt install linux-image-5.4.0-67-generic linux-headers-5.4.0-67-generic`

I force to install amdgpu for the kernel 5.4.0-67 with

`sudo dkms install amdgpu/4.0-23 -k 5.4.0-67-generic`

I rebooted selected 5.4.0-67 and tried

/opt/rocm/bin/rocminfo

The result:
`ROCk module is NOT loaded, possibly no GPU devices
Unable to open /dev/kfd read-write: No such file or directory
i-bird is not member of "video" group, the default DRM access group. Users must be a member of the "video" group or another DRM access group in order for ROCm applications to run successfully.
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.`

in dmsg i found

`dmesg | grep amdgpu
[    2.338814] amdgpu: Unknown symbol amd_iommu_bind_pasid (err -2)
[    2.339078] amdgpu: Unknown symbol amd_iommu_set_invalidate_ctx_cb (err -2)
[    2.339244] amdgpu: Unknown symbol amd_iommu_free_device (err -2)
[    2.339758] amdgpu: Unknown symbol amd_iommu_unbind_pasid (err -2)
[    2.339781] amdgpu: Unknown symbol amd_iommu_init_device (err -2)
[    2.339976] amdgpu: Unknown symbol amd_iommu_set_invalid_ppr_cb (err -2)
`
while /dev/kfd does not exist.

Does anyone have an idea of what is going on ?

**Comment by ROCmSupport** [comment]
Thanks @incardon for reaching out.
As mentioned in rocm documentation, ROCm 4.0 does not work with 5.8 kernel.
Within 2 days, ROCm 4.1 is going to be released and then you can try ROCm 4.1 with 5.8 kernel, should work.
Thank you.

**Comment by ROCmSupport** [comment]
Meanwhile if you wish to try with ROCm 4., follow the below way.

You can install linux-5.4 or 5.6 kernel and uninstall linux-5.8 manually. Reboot and re-install rocm-dkms.
Like this:
_sudo apt install linux-image-5.4.0-67-generic linux-modules-extra-5.4.0-67-generic linux-headers-5.4.0-67-generic_
_sudo apt remove linux-image-5.8.0-44-generic linux-modules-extra-5.8.0-44-generic linux-headers-5.8.0-44-generic_

Hope this helps and clarifies.
Thank you.

**Comment by incardon** [comment]
Thanks. For the fast answer. Installing linux-modules-extra-5.4.0-67-generic, removing 5.8 using the instruction above and reinstalling dkms made it works. To assemble a set of instruction for ROCM 4.0

`sudo apt install linux-image-5.4.0-67-generic linux-modules-extra-5.4.0-67-generic linux-headers-5.4.0-67-generic
sudo apt remove linux-image-5.8.0-44-generic linux-modules-extra-5.8.0-44-generic linux-headers-5.8.0-44-generic rocm-dkms
sudo apt autoremove
sudo reboot
sudo apt install rockm-dkms rockm-dev`

**Comment by ROCmSupport** [comment]
Thanks for the confirmation @incardon 
Thank you.
