### ISSUE TITLE
Centos 7.9 based on kernel 5.4 shows no message about amdkfd 

### ISSUE THREAD

**Issue by Biu-G** [RadeonOpenCompute/ROCm#1415]
my amdgpu module boots greatly, while there isn't any message about amdkfd in dmesg. Which leads to rocminfo shows "Unable to open /dev/kfd read-write: No such file or directory". Don't know how to continue.

**Comment by Biu-G** [comment]
Linux localhost.localdomain 5.4.105-1.el7.elrepo.x86_64 #1 SMP Thu Mar 11 08:28:06 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ROCmSupport** [comment]
Hi @Biu-G 
Thanks for reaching out.
As per our ROCm documentation, ROCm 4.0 validated and supports 3.10.0-x kernel officially.
Request you to follow our docs: [https://github.com/RadeonOpenCompute/ROCm#list-of-supported-operating-systems](url)
Hope it clarifies.
Thank you.

**Comment by ROCmSupport** [comment]
ROCm 4.1 is going to be released very soon and request you to try with ROCm 4.1 once.
Thank you.
