### ISSUE TITLE
Is that possible to install ROCm on AWS EC2 instance

### ISSUE THREAD

**Issue by lanking520** [RadeonOpenCompute/ROCm#1417]
Hi, 

question as title, is that possible to use ROCm on EC2 instance like g4ad? If so, which OS image should I pick that works the best? And just follow the normal instructions?

**Comment by ROCmSupport** [comment]
Hi @lanking520 
ROCm with AWS support is coming soon on specific variant of cards. Pease stay tuned for the updates.
Thank you.
