### ISSUE TITLE
Ask add hipFFT to ROCm-4.1 default.xml

### ISSUE THREAD

**Issue by xuhuisheng** [RadeonOpenCompute/ROCm#1428]
There is one component - hipFFT, missing in default.xml.
Please add hipFFT to default.xml, so we can download related sources using repo.
Thank you.

https://github.com/RadeonOpenCompute/ROCm/pull/1427

**Comment by ROCmSupport** [comment]
Thanks @xuhuisheng for reaching out.
I will check this for you and get an update soon.
Thank you.

**Comment by xuhuisheng** [comment]
PR had merged. Close issue.

**Comment by ROCmSupport** [comment]
I worked with Packaging team on this and asked them to merge hipFFT also.
They did it. Thanks for confirming that.
Thank you.
