### ISSUE TITLE
rocm-smi --showmemvendor fails

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1434]
On both my computers it shows "Unable to get GPU memory vendor." ...

**Comment by ROCmSupport** [comment]
Hi @valeriob01 
Thanks for reaching out.
Can you please share the details of asic, os, kernel and all other information for better understanding.
Thank you.

**Comment by ROCmSupport** [comment]
I tried on MI25 card and not seeing the problem.


======================= ROCm System Management Interface =======================
================================ Memory Vendor =================================
GPU[0]          : GPU memory vendor: samsung
================================================================================
============================= End of ROCm SMI Log ==============================

**Comment by valeriob01** [comment]
This is Radeon VII, Ubuntu 20.04, kernel 5.4.0-70-generic
https://github.com/preda/gpuowl/discussions/221

**Comment by ROCmSupport** [comment]
Looks like you are using very very old ROCm version.
We are currently with ROCm 4.1 and issue is not reproduced anymore.
Recommend to try with the latest ROCm 4.1.
Thank you.
