### ISSUE TITLE
reduced number of registers per thread in ROCm 4.1

### ISSUE THREAD

**Issue by DTolm** [RadeonOpenCompute/ROCm#1442]
from https://github.com/RadeonOpenCompute/ROCm/issues/1380

ROCm 4.0 had an issue - hipDeviceAttributeMaxThreadsPerBlock was reporting 1024 even when the ROCm was configured with 256 max threads. It seems that in ROCm 4.1 it was also increased to 1024, but this reduced the number of registers a thread can use before spilling to global memory (https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html). 

Some of my kernels at VkFFT experience a drop in performance from this, so I wanted to ask if it is possible to provide the exact value of registers per thread I need at compile-time to avoid the spilling in HIPRTC? launch_bounds doesn't seem to have any impact in HIPRTC.

Thank you!
Best regards,
Dmitrii

**Comment by ROCmSupport** [comment]
Thanks @DTolm for reaching out.
I will check with HIP team and share an update on this.
Thank you.

**Comment by yxsamliu** [comment]
launch bounds should work with hipRTC. I tried it with a simple test https://github.com/ROCm-Developer-Tools/HIP/blob/main/tests/src/hiprtc/saxpy.cpp by adding `__launch_bounds__(256)` at line 49 before `__global__`. I dumped the code object generated by hipRTC and saw .max_flat_workgroup_size changed from 1024 to 256.

You may use env var 

export AMD_COMGR_EMIT_VERBOSE_LOGS=1
export AMD_COMGR_REDIRECT_LOGS=stderr
export AMD_COMGR_SAVE_TEMPS=1

to dump the code objects (a.so files) and use `/opt/rocm/llvm/bin/llvm-readobj -elf-output-style=GNU -notes filename` to check .max_flat_workgroup_size for a specific kernel.

**Comment by DTolm** [comment]
I have checked the generated code with provided variables (big thanks for them actually) and it seems you are correct. Then performance drops happen due to some other reason. I will keep looking and will open another issue if I find something. Thank you!
