### ISSUE TITLE
rocm-smi 4.1 returns error

### ISSUE THREAD

**Issue by perestoronin** [RadeonOpenCompute/ROCm#1446]
```
python3 /opt/rocm/bin/rocm_smi.py
Failed to get "domain" properity from properties files for kfd node 1.
rsmi_init() failed
Exception caught: rsmi_init.
ERROR:root:ROCm SMI returned 8 (the expected value is 0)
```

but rocminfo work perfect

**Comment by ROCmSupport** [comment]
Hi @perestoronin 
Thanks for reaching out.
In my case, rocm-smi shows information properly.
Can you please share us with below information.
Asic, OS, Kernel, ROCm# version and dmesg output.

**Comment by perestoronin** [comment]
```Linux ws 5.4.110-gentoo-rt54 #1 SMP PREEMPT_RT Thu Apr 8 02:08:48 MSK 2021 x86_64 AMD Phenom(tm) II X6 1100T Processor AuthenticAMD GNU/Linux
```
```
rocminfo | wgetpaste Your raw paste can be seen here: https://gist.github.com/raw/37969bd15b49c281c4d3535e9791876a
```

```
python /opt/rocm-4.1.0/bin/rocm_smi.py
Failed to get "domain" properity from properties files for kfd node 1.
rsmi_init() failed
Exception caught: rsmi_init.
ERROR:root:ROCm SMI returned 8 (the expected value is 0)
```
```
dmesg | wgetpaste
Your raw paste can be seen here: https://gist.github.com/raw/800e51601e1aa6ccc0326abb44736890
```
```
cat /sys/class/kfd/kfd/topology/nodes/1/properties | wgetpaste
Your raw paste can be seen here: https://gist.github.com/raw/eaa36a7bcac19abc5711ecf8cb692e0a
cat /sys/class/kfd/kfd/topology/nodes/1/properties | wgetpaste
Your raw paste can be seen here: https://gist.github.com/raw/eaa36a7bcac19abc5711ecf8cb692e0a
```

**Comment by ROCmSupport** [comment]
Thanks for more information @perestoronin 
I looked at the device properties and found that "domain" property is missed and so its throwing error.

But in my case, "domain 0" and so no issue observed.
Working more to gather more information.

**Comment by perestoronin** [comment]
I investigate, that domain introduced since kernel version 5.8.

@ROCmSupport  what version of kernel compiance with rocm 4.1.1 ?

**Comment by perestoronin** [comment]
/opt/rocm/bin # python rocm_smi.py 
GPU  Temp   AvgPwr  SCLK    MCLK    Fan    Perf  PwrCap  VRAM%  GPU%  
0    39.0c  7.0W    852Mhz  167Mhz  14.9%  auto  220.0W    1%   6%    

/opt/rocm/bin # uname -a
Linux 5.10.28-gentoo-rt36 #1 SMP PREEMPT_RT x86_64 AMD Phenom(tm) II X6 1100T

Аfter update kernel from deprecated 5.4 to actual for rocm-4.1.1 kernel-5.10 issue is resolved.

**Comment by ROCmSupport** [comment]
Thanks for upgrading kernel and closing this issue.
Thank you.
