### ISSUE TITLE
ROCm-1.6: hsa runtime init fails

### ISSUE THREAD

**Issue by oheid** [RadeonOpenCompute/ROCm#145]
The latest ROCm-1.6 kernel exits `./vector_copy` at `hsa_init()` with error code 1008. The problem seems to be a failing ioctl call:
```
strace ./vector_copy
...
brk(0x18c6000)                          = 0x18c6000
brk(NULL)                               = 0x18c6000
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x4b, 0x1d, 0x10), 0x7ffdfef45e30) = -1 EINVAL (Invalid argument)
close(3)                                = 0
fstat(1, {st_mode=S_IFREG|0664, st_size=116960, ...}) = 0
write(1, "Initializing the hsa runtime fai"..., 43Initializing the hsa runtime failed: 1008.
) = 43
exit_group(1)                           = ?
+++ exited with 1 +++
```
With ROCm-1.5 kernel (and everything else identical) that ioctl call succeeds:
```
...
brk(0x1c16000)                          = 0x1c16000
brk(NULL)                               = 0x1c16000
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x4b, 0x1d, 0x10), 0x7ffc45762420) = 0
open("/sys/module/amdgpu/parameters/vm_size", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(4, "128\n", 4096)                  = 4
close(4)                                = 0
...
+++ exited with 0 +++
```
Any ideas?

**Comment by jedwards-AMD** [comment]
For 1.6 check to see if the /dev/kfd file exists, and has the correct permissions, crw-rw-rw- 1 root root. If the defice doesn't exist, you will need to examine dmesg to see if you can find a problem with loading the kfd driver: 'sudo dmesg | grep kfd".

**Comment by gstoner** [comment]
So your still trying Fedora 25  on Bristol Ridge (A12-9800) + ASUS Prime X370-Pro motherboard?

**Comment by oheid** [comment]
Thanks for the fast replies!
I am quite sure /dev/kfd existed but let me check again. The system (see above) is a Ryzen 1700x on an Asus C6H board.
Re. Bristol ridge: I gave up for the time being. Did you test it in your lab?
Next I plan to plug that A12 into an Asus C6H board - Do I have to run it headless (no dGPU)?

**Comment by jedwards-AMD** [comment]
On your Ryzen system, do you have a GPU?

**Comment by oheid** [comment]
Re. /dev/kfd:
`ls -l /dev/kfd 
crw-rw-rw-. 1 root root 244, 0 Jul  3 17:47 /dev/kfd
`
The kernel modules seem to be present too:
```
lsmod | grep amd
amdkfd                212992  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               2461696  2
kvm_amd              2179072  0
ttm                   102400  1 amdgpu
kvm                   585728  1 kvm_amd
drm_kms_helper        155648  1 amdgpu
drm                   360448  5 amdgpu,ttm,drm_kms_helper
gpio_amdpt             16384  0
gpio_generic           16384  1 gpio_amdpt
i2c_algo_bit           16384  2 igb,amdgpu
```

**Comment by gstoner** [comment]
You need a gpu

Get Outlook for iOS<https://aka.ms/o0ukef>



On Mon, Jul 3, 2017 at 10:38 AM -0500, "oheid" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the fast replies!
I am quite sure /dev/kfd existed but let me check again. The system (see above) is a Ryzen 1700x on an Asus C6H board.
Re. Bristol ridge: I gave up for the time being. Did you test it in your lab?
Next I plan to plug that A12 into an Asus C6H board - Do I have to run it headless (no dGPU)?

**Comment by oheid** [comment]
Yes: A R9 480 GPU. It works nicely on ROCm-1.5. Both my machines (same hardware) behave the same, so I don't think its a hardware fault.

**Comment by gstoner** [comment]
The APu do not support an external gpu currently with the driver

Get Outlook for iOS<https://aka.ms/o0ukef>



On Mon, Jul 3, 2017 at 10:38 AM -0500, "oheid" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the fast replies!
I am quite sure /dev/kfd existed but let me check again. The system (see above) is a Ryzen 1700x on an Asus C6H board.
Re. Bristol ridge: I gave up for the time being. Did you test it in your lab?
Next I plan to plug that A12 into an Asus C6H board - Do I have to run it headless (no dGPU)?

**Comment by oheid** [comment]
In consequence I have to use Bristol ridge in a headless system, right?
The Prime x370 board has a DP output (this is why I bought it) but the BIOS seems to have a problem with IOMMU, whereas the C6H has no graphics port but IOMMU support seems to work.

**Comment by gstoner** [comment]
We have other with rx480 working.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Mon, Jul 3, 2017 at 10:57 AM -0500, "oheid" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes: A R9 480 GPU. It works nicely on ROCm-1.5. Both my machines (same hardware) behave the same, so I don't think its a hardware fault.

**Comment by oheid** [comment]
To make sure we understand each other: I have three systems, all under Fedora 25:

- 2x Asus C6H boards with Ryzen 1700x and R9 480. ROCK-1.5 works on both Ryzen+ RX480 systems, but not ROCK-1.6.
- 1x Asus Prime X370, which was intended for Bristol ridge but there are problems with IOMMU (obviously)

**Comment by oheid** [comment]
tingxingdong is right: libhsakmt.so needs to be updated together with the kernel.
