### ISSUE TITLE
Rocm 4.1 libamd_comgr.so.1 missing

### ISSUE THREAD

**Issue by Dantali0n** [RadeonOpenCompute/ROCm#1451]
OpenCL fails for 4.1.0 due to clinfo being entirely missing. Similarly, libamd_comgr.so.1 is now missing from the install.

**Comment by Dantali0n** [comment]
`Reinstallation of rocm-opencl is not possible, it cannot be downloaded.`

**Comment by Dantali0n** [comment]
Packages for rocm-opencl, and rocm-opencl-dev still report version 3.6 on Ubuntu Xenial based systems, fucking slow clap well done!

```
rocm-opencl/now 3.6Beta-17-g875c1f8-rocm-rel-4.0-23 amd64 [installed,local]
  OpenCL: Open Computing Language on ROCclr

rocm-opencl-dev/now 3.6Beta-17-g875c1f8-rocm-rel-4.0-23 amd64 [installed,local]
  OpenCL: Open Computing Language on ROCclr
```

**Comment by ROCmSupport** [comment]
Thanks @Dantali0n for reaching out.
Can you please share the exact steps you followed, to reproduce the problem.
And also share kernel version, ROCm version, OS, clinfo and rocminfo outputs.
Thank you.

**Comment by Dantali0n** [comment]
Steps:

```
sudo apt update
sudo apt upgrade
```

Kernel: 5.4.0
OS: Ubuntu 18.04
ROCm version: 4.1.0 (Partial your opencl packages for 4.1.0 are MISSSING!!!)
clinfo: not installed missing due to broken update!
rocminfo: error can not open shared library, missing

**Comment by ROCmSupport** [comment]
Thanks @Dantali0n for the steps.
Upgrade does not work now and so we recommend to not to upgrade.
Request you to uninstall old rocm and install new rocm, which works well.
Thank you.

**Comment by Dantali0n** [comment]
> Thanks @Dantali0n for the steps.
> Upgrade does not work now and so we recommend to not to upgrade.
> Request you to uninstall old rocm and install new rocm, which works well.
> Thank you.

This is bonkers, you can't just say we are incapable of properly making .deb packages so everyone using ROCm can't use `apt upgrade` anymore. Fix your packages properly!

**Comment by ROCmSupport** [comment]
Hi @Dantali0n 
We are stabilizing the upgrade process and it will be available very soon.
Until then recommend to do a clean uninstall and install.
Thank you.
