### ISSUE TITLE
ROCm 4.1.1 + PyTorch 1.8.1 + Ubuntu 20.04.2 Installation fails

### ISSUE THREAD

**Issue by snackfart** [RadeonOpenCompute/ROCm#1454]
Hardware:
RX 480, 8GB

Software/OS:
Kernel: 5.4.0-71-generic
Ubuntu 20.04.2

Hello,

i installed ROCm 4.1.1 successfully, but the pyTorch Installation fails when following the official guide (last step):
![image](https://user-images.githubusercontent.com/33380141/114738967-c1d37900-9d48-11eb-9a9f-dc7a915fbd68.png)

console input:
`pip3 install ninja && pip3 install 'git+https://github.com/pytorch/vision.git@v0.9.1'`

output:
```
Requirement already satisfied: ninja in /home/buran/.local/lib/python3.8/site-packages (1.10.0.post2)
Collecting git+https://github.com/pytorch/vision.git@v0.9.1
  Cloning https://github.com/pytorch/vision.git (to revision v0.9.1) to /tmp/pip-req-build-h7owh6u3
  Running command git clone -q https://github.com/pytorch/vision.git /tmp/pip-req-build-h7owh6u3
  Running command git checkout -q 8fb5838ca916fd4ace080dae0357e7c307037bef
    ERROR: Command errored out with exit status -6:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h7owh6u3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h7owh6u3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-h7owh6u3/pip-egg-info
         cwd: /tmp/pip-req-build-h7owh6u3/
    Complete output (1 lines):
    /data/jenkins_workspace/centos_pipeline_job_4.0/rocm-rel-4.0/rocm-4.0-26-20210119/7.7/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
    ----------------------------------------
ERROR: Command errored out with exit status -6: python setup.py egg_info Check the logs for full command output.
```

What am i doing wrong?

Thanks

**Comment by unexploredtest** [comment]
Check this:
https://github.com/xuhuisheng/rocm-build/tree/master/gfx803

**Comment by snackfart** [comment]
> Check this:
> https://github.com/xuhuisheng/rocm-build/tree/master/gfx803

Checked it still the same error.

**Comment by sunway513** [comment]
@pruthvistony can you help here?

**Comment by pruthvistony** [comment]
RX 480 is Polaris GPU. This GPU is NOT supported by ROCm

**Comment by snackfart** [comment]
> RX 480 is Polaris GPU.
> ROCm is not build and released for this GPU, you can try building from source but operation is not guaranteed.

Correct me if i´m wrong, but werent there versions of ROCm for Polaris 10? Also where is the difference between Polaris 10 and 11?

**Comment by xuhuisheng** [comment]
We can use ROCm-3.5.1 with gfx803 - Polaris - RX480,RX580, etc.
Here is a documents for ROCm-3.5 <https://github.com/boriswinner/RX580-rocM-tensorflow-ubuntu20.4-guide>

BTW, tensorflow_rocm-2.4.2 still can run successfully on ROCm-4.1 and gfx803, don't need to compile by ourselves.

**Comment by snackfart** [comment]
> We can use ROCm-3.5.1 with gfx803 - Polaris - RX480,RX580, etc.
> Here is a documents for ROCm-3.5 https://github.com/boriswinner/RX580-rocM-tensorflow-ubuntu20.4-guide
> 
> BTW, tensorflow_rocm-2.4.2 still can run successfully on ROCm-4.1 and gfx803, don't need to compile by ourselves.

Thanks for your help, will try.
Need pyTorch unfortunately.

**Comment by snackfart** [comment]
fyi solution:
https://github.com/xuhuisheng/rocm-build/issues/8
