### ISSUE TITLE
personal opinon: Unless mac and windows is supported, this ROCm project will never be as popular as CUDA

### ISSUE THREAD

**Issue by duwangthefirst** [RadeonOpenCompute/ROCm#1455]
personal opinon: Unless mac and windows is supported, this ROCm project will never be as popular as CUDA.

If One is willing to build a ubuntu server, nvidia gpu is obviously a better choice for CUDA comes with a lot of learning resource.

However latest MacOS  device only provide AMD gpus, so why doesn't ROCm support MacOS ? More developer will be attracted once this feature comes true.

**Comment by Degerz** [comment]
> However latest MacOS device only provide AMD gpus, so why doesn't ROCm support MacOS ?

AMD GPUs won't be included or supported anymore on future Mac systems ...

**Comment by AGenchev** [comment]
@duwangthefirst most of us use Linux, but yes, users want painless experience, which still does not happen. Nvidia has a CUDA version working on every card and APU (Jetsons) they make, ROCm works only on few selected cards even the newest (6800) are not supported...
The excuse for Vega 10 APUs is that MB manufacturers messed with BIOS and did not properly adjust certain tables, but if AMD gave them reference MB BIOS, they wouldn't mess, so this is vague... AMD could make **x86** Jetson equivalents but they didn't see the niche where Nvidia sells their previous-gen (12nm) stuff.

**Comment by ROCmSupport** [comment]
Hi @duwangthefirst 
Thanks for reaching out.
We do not have plans to support mac and windows as of now.
We will share via our docs, once we have plans in future.
Thank you.

**Comment by AGenchev** [comment]
@duwangthefirst: There is a new development on Microsoft side if you want to go this route - they are enabling TensorFlow over DirectX acceleration for any GPU - be it AMD, Intel, Nv. For me it is bad idea - they should implement it over Vulkan or OpenCL to be portable to Linux, but they're playing their ****!# game.

**Comment by ROCmSupport** [comment]
Hi @gwc4github 
ROCm + Linux is the highlighted combination.
If you change Linux to Mac in the PS section, ROCm will be disabled, so its confirm that ROCm+MacOS is not a supported combination right now.
You can check this image too.
![image](https://user-images.githubusercontent.com/74597123/120588892-9c641100-c455-11eb-84d4-fe4ed2473d91.png)

**Comment by daoxian** [comment]
> Hi @duwangthefirst
> Thanks for reaching out.
> We do not have plans to support mac and windows as of now.
> We will share via our docs, once we have plans in future.
> Thank you.

Lazy boys who are losing the AI competition...
