### ISSUE TITLE
"broken packages" failure on "Option 3: Install using minimal ROCm docker file" in the Rocmdocs site

### ISSUE THREAD

**Issue by AGenchev** [RadeonOpenCompute/ROCm#1457]
I'm performing step 3 of the manual: https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#pytorch
and during command "`sudo docker build .`"
I get:
```
The following packages have unmet dependencies:
 rocm-dev : Depends: rocm-gdb but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ROCmSupport** [comment]
Thanks @AGenchev for reaching out.
I am able to reproduce the problem.
I will share an update very soon.
Thank you.

**Comment by ROCmSupport** [comment]
Assigned to dev for modification of steps in the documentation.
I will update you once I receive.

**Comment by ROCmSupport** [comment]
Got update:
Stpes updated @ https://rocmdocs.amd.com/en/latest/Deep_learning/Deep-learning.html#pytorch 
Please review and update. Thank you.

**Comment by ROCmSupport** [comment]
Issue resolved by updating the docs.
This ticket can be closed now.
Thank you.
