### ISSUE TITLE
Need Rocm install instruction on Arch/Manajaro

### ISSUE THREAD

**Issue by k1ag3n** [RadeonOpenCompute/ROCm#1458]
Now i try build whole rocm framework via AUR Now i success to install rocm (except rccl !!!!) So I can't install tensorflow-rocm and can't dev any nueral or AI

**Comment by ROCmSupport** [comment]
Hi @k1ag3n 
Thanks for reaching out.
We do not support ROCm-on-Arch officially.
But I browsed and found some doc related to it, you can give a try: [https://github.com/rocm-arch/rocm-arch](url)
Hope it helps.
Thank you.
