### ISSUE TITLE
Support Ubuntu 21.04 (Hirsute Hippo)

### ISSUE THREAD

**Issue by Bengt** [RadeonOpenCompute/ROCm#1460]
The version [21.04 (Hirsute Hippo) of Ubuntu is now current](https://lists.ubuntu.com/archives/ubuntu-announce/2021-April/000268.html) and should therefore be supported.

**Comment by Bengt** [comment]
... but it won't:

> ROCm officially supports LTS versions of Ubuntu only.
> All other versions(other than LTS) might work with ROCm but there will not be any official support.

Source: https://github.com/RadeonOpenCompute/ROCm/issues/1263#issuecomment-720264016

**Comment by ROCmSupport** [comment]
Thanks @Bengt for reaching out.
Yes, ROCm officially supports LTS versions of Ubuntu only.
Thank you.

**Comment by Bengt** [comment]
Thanks, @ROCmSupport for confirming the status quo of the support. I hope this issue helps others in searching for this information.

**Comment by Dan-RAI** [comment]
Did someone manage to get it running under 21.04 ? 

I tried using the Kernel drivers and rocm-dev + rock-dkms-firmware only and had some initial success. However, after another update and reboot it is not working anymore, and so far I did not succeed in getting it back into working order:

[    1.426118] [drm] amdgpu kernel modesetting enabled.
[    1.427051] amdgpu: Ignoring ACPI CRAT on non-APU system
[    1.427342] amdgpu: Topology: Add CPU node
[    1.427536] amdgpu 0000:2f:00.0: amdgpu: Trusted Memory Zone (TMZ) feature not supported
[    1.427548] amdgpu 0000:2f:00.0: amdgpu: Fatal error during GPU init
[    1.428245] amdgpu: probe of 0000:2f:00.0 failed with error -12

**Comment by Dan-RAI** [comment]
Ok, I found the problem:

SR-IOV support needs to be disabled in BIOS. 

After this the Kernel amdgpu driver works together with rocm-dev under Ubuntu 21.04

**Comment by erkinalp** [comment]
Precompiled packages fail due to dependency on missing Python 3.8.

**Comment by Bengt** [comment]
@erkinalp That sounds interesting. Please file a new issue about that.

**Comment by erkinalp** [comment]
@Bengt That issue is specific to 21.04, which is unsupported.

**Comment by Bengt** [comment]
Still, a documentation of the issue you are having would be nice to have for debugging and discussing workarounds. So, in any case, please provide details either here or in a separate issue.

**Comment by xuhuisheng** [comment]
@erkinalp
Which package report python3.8 error? I think I can try investigating.

**Comment by erkinalp** [comment]
@xuhuisheng `rocm-gdb` depends on `libpython3.8`, which does not exist on 21.04. The earliest Python 3 version available on Ubuntu 21.04 is Python 3.9.

**Comment by Dan-RAI** [comment]
just compile and install python3.8 by hand ...

**Comment by erkinalp** [comment]
I would rather port `rocm-gdb` to Python 3.9 instead. Because Python 3.8 will is not going to exist in 22.04 anyway.

**Comment by xuhuisheng** [comment]
The rocm-gdb is not a key component. Actually we can run pytorch / tensorflow without it. But the rocm-devs contains a dependency to rocm-gdb.
It didn't provide a cmakefiles.txt, so I didn't know how to create a deb package from source.
Should we build the source codes with configure/make, and make deb manually?

**Comment by almereyda** [comment]
@Dan-RAI Could you offer more details of your installation procedure? I'm wondering, because I'm not sure if you used a packaged ROCm ([4.2 for Docker](https://www.amd.com/en/technologies/infinity-hub/pytorch)), or compiled it by yourself (at a specific version tag?) to omit the `apt` warning:

```shell
$ apt install rocm-dkms
...
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 rocm-gdb : Hängt ab von: libpython3.8 ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```

Above, you also spoke about `rocm-dev`, yet that also depends on `rocm-gdb`.

Eventually it is possible to work around `apt` altogether, by building and running Python3.8 and ROCm (4.2 for Docker) completely from source?
