### ISSUE TITLE
/data/jenkins_workspace/centos_pipeline_job_4.0/rocm-rel-4.0/rocm-4.0-26-20210119/7.7/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")

### ISSUE THREAD

**Issue by X-ailsa** [RadeonOpenCompute/ROCm#1471]

**Comment by xuhuisheng** [comment]
I suggest to check if there is a gfx03 - RX580 issue.
https://github.com/xuhuisheng/rocm-build/tree/master/gfx803

Please execute `/opt/rocm/bin/rocminfo` to confirm GPU ASIC. Only a few GPU are supported by ROCm.

**Comment by X-ailsa** [comment]
GPU: Radeon RX 580 Series
The version of pytorch installed on my computer: torch==1.8.1+rocm4.0.1
Thank you very much. I tried the solution you provided, but I couldn't find the file: torch-1.8.0a0+56b43f4-cp38-cp38-linux_x86_64.whl

**Comment by xuhuisheng** [comment]
@X-ailsa
You need compile pytorch from source by yourself.
Or you can try this : https://github.com/xuhuisheng/rocm-gfx803

**Comment by ROCmSupport** [comment]
Thanks @X-ailsa 
Thanks for reaching out.
As we are NOT officially supporting gfx8 devices with ROCm anymore, I will close this issue.
@xuhuisheng, Thanks for your help.
Feel free to open a new issue, if any, in future.
