### ISSUE TITLE
Is the separate compilation possible for hip?

### ISSUE THREAD

**Issue by brad-mengchi** [RadeonOpenCompute/ROCm#1473]
Hi all,

I did not find it in the HIP programming guide but is the separate compilation possible for hip?

And is that possible for link-time optimization?

For example, we have a function file a.c and main file main.c:
--a.c
extern __device__ foo() {
...
}

---a.h
extern __device__ foo();

--main.c
#include "a.h"

__global__ kernel() {
...
fool();
...
}

I tried to compile:
>hipcc -flto -c a.c -o a.o
>hipcc -c main -o main.o
>hipcc a.o main.o -o main

The command line will give me "lld: error: undefined hidden symbol:foo()".
P.S.: I compiled llvm to use for hipcc and compile the LLVMgold.so to use lto.

**Comment by scchan** [comment]
You have to add the -fgpu-rdc flag if a kernel calls a device function in a difference source file.

**Comment by brad-mengchi** [comment]
HI @scchan! Thanks for your answer. So we can compile the device function file with -fgpu-rdc -c and then at link time, which option do we need to use to link up the relocatable device code?

**Comment by brad-mengchi** [comment]
Oh I found the solution for the link option. Thanks @scchan !
https://github.com/ROCm-Developer-Tools/HIP/issues/2203
