### ISSUE TITLE
Official support to Kernel 5.10

### ISSUE THREAD

**Issue by staticdev** [RadeonOpenCompute/ROCm#1474]
ROCm is always updated with latest graphics cards (also phased out not so old ones like RX 580). It would be very nice to keep the pace with the kernel. Latest versions of Ubuntu/Debian and all other Linux are coming with kernel 5.10. 

Kernel 5.4 is now very outdated. Shouldn't ROCm 4.2 officially support the new ones instead?

**Comment by ROCmSupport** [comment]
Hi @staticdev 
Thanks for reaching out.
Agree with your point.
Let me get some information from the team and share you soon.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @staticdev 
We started validating the latest kernels like 5.8+ and we will update the docs with the same in the future releases.
Thank you.
