### ISSUE TITLE
A clean install of rocm-opencl on debian unstable does not work because of missing libtinfo5

### ISSUE THREAD

**Issue by dreifachstein** [RadeonOpenCompute/ROCm#1477]
libamd_comgr.so depends on libtinfo.so.5 but the package "comgr" does not list "libtinfo5" as a dependency.

**Comment by ROCmSupport** [comment]
Thanks @dreifachstein for reaching out.
We are already aware of this issue and team is working on the fix.
I will share an update once is merged into release branch.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @dreifachstein 
Good news, the fix is integrated into 4.5 and so request to check with 4.5.
We verified locally and issue is no more noe.
Thank you.
