### ISSUE TITLE
ROCm 1.6 --> hipconfig: why nvcc?

### ISSUE THREAD

**Issue by ptsant** [RadeonOpenCompute/ROCm#148]
I installed ROCm 1.6: 
```
apt-get install rocm rocm-opencl rocm-opencl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  hcc hip_base hip_doc hip_hcc hip_samples libunwind-dev rocm-dev rocm-device-libs rocm-smi rocm-utils
The following NEW packages will be installed:
  hcc hip_base hip_doc hip_hcc hip_samples libunwind-dev rocm rocm-dev rocm-device-libs rocm-opencl rocm-opencl-dev  rocm-smi rocm-utils

```
Unfortunately, it appears that hipconfig wants to use nvcc:
```
HIP version  : 1.2.17263

== hipconfig
HIP_PATH     : /opt/rocm
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/include -I/usr/local/cuda/include

== nvcc
Can't exec "nvcc": No such file or directory at /opt/rocm/bin/hipconfig line 143.

=== Environment Variables
PATH=/opt/rocm/bin:/opt/rocm/bin:/opt/rocm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

Am I doing something wrong? Shouldn't it default to hcc? I have an RX480 with Ryzen CPU.

Note: I haven't yet rebooted to the kfd kernel, but I don't see how that would change things.

**Comment by gstoner** [comment]
NVCC config is only used when you use Clang based HIPIFY tool.  you can use the perl script instead

**Comment by bensander** [comment]
Typically this means that your rocm driver did not detect an amd gpu - if this happens hipconfig defaults to nvcc.  Can you verify your machine meets the platform requirement ( see rocm.tithub.io) and try the troubleshooting steps described there?

**Comment by jlgreathouse** [comment]
Please open a separate ticket if you are running into issues. Piggybacking on an existing ticket means we might not get around to answering you. :)

In addition, you may want to look through a few of the recent tickets where people had installation troubles (like #508 and #511) for examples of troubleshooting steps.
