### ISSUE TITLE
OpenCL freezes on second GPU

### ISSUE THREAD

**Issue by ivanmlerner** [RadeonOpenCompute/ROCm#1480]
Hello, I have two RX5500 and opencl seems to hang/freeze when using the second motherboard slot.
Even clinfo freezes when getting information from the second gpu. I have swapped the cards and the issue remains. Both cards are detected properly by opencl, both are run by the processor in this motherboard, and the power supply has plenty of power for both cards. I am running arch linux and I know the distribution and cards are not officially supported, but I'd greatly appreciate some help with this issue.

**Comment by preda** [comment]
If you do a "sudo dmesg" after the freeze, do you see anything interesting towards the end of it?

**Comment by ivanmlerner** [comment]
I do, here is the output:

[dmesg_output.txt](https://github.com/RadeonOpenCompute/ROCm/files/6542190/dmesg_output.txt)

**Comment by ThomasA** [comment]
I am experiencing issues that sound very similar to this on 2 Instinct MI100 GPUs.

**Comment by ROCmSupport** [comment]
Hi @ivanmlerner 
Thanks for reaching out.
We are not officially supporting Navi series of cards right now and also arch linux. So can not share official help.
But have few suggestions.
Can you please pull out card first card(so called working card) and try to boot with one card only(card in second slot) and update.
Thank you.

**Comment by ivanmlerner** [comment]
Hello, I understand, thanks a lot to try and help help me.
I did as instructed and the computer booted properly. OpenCL was also working normally without any output to dmesg.

**Comment by ROCmSupport** [comment]
Thanks.
So request you to do the below experiments for better understating of the problem.
1. Keeping one card in first slot only --> clinfo output and dmesg
2. Keeping one card in second slot only --> You already shared info that it working. clinfo output and dmesg needed
3. Keeping one card in first slot and one card in second slot --> clinfo output and dmesg

Thank you.

**Comment by ivanmlerner** [comment]
Hello, I did as instructed and here are the outputs:

[dmesg_output_both.txt](https://github.com/RadeonOpenCompute/ROCm/files/6587616/dmesg_output_both.txt)
[clinfo_output_both.txt](https://github.com/RadeonOpenCompute/ROCm/files/6587615/clinfo_output_both.txt)
[dmesg_output_first_only.txt](https://github.com/RadeonOpenCompute/ROCm/files/6587617/dmesg_output_first_only.txt)
[clinfo_output_first_only.txt](https://github.com/RadeonOpenCompute/ROCm/files/6587618/clinfo_output_first_only.txt)
[dmesg_output_second_only.txt](https://github.com/RadeonOpenCompute/ROCm/files/6587619/dmesg_output_second_only.txt)
[clinfo_output_second_only.txt](https://github.com/RadeonOpenCompute/ROCm/files/6587620/clinfo_output_second_only.txt)

**Comment by ROCmSupport** [comment]
Hi @ivanmlerner 
No useful information captured from dmesg in all cases.
But in 2 GPU case, IO_PAGE_FAULTs observed and I dont think its related to ROCm. Anyway, I am trying to get more information.
clinfo outputs are similar in all cases and clinfo output is not complete, means clinfo did not run completely(Might be due to the non-support of ROCm right now).

**Comment by ROCmSupport** [comment]
More update:
I can confirm that issue is caused by amdgpu, I decoded and found further that's the module that threw it. 
But as the issue is related to amdgpu/ROCm, I can not help further as we are not supporting this card officially.
Hope you got it.
Thank you.

**Comment by ivanmlerner** [comment]
Thanks a lot for the effort, I do get it. 
Does that mean I need to look for amdgpu support or just wait until the card becomes supported?

**Comment by ROCmSupport** [comment]
Hi @ivanmlerner 
Its your call, I can not comment on this :).

**Comment by ivanmlerner** [comment]
Hello, I have managed to get it to work. Disabling IOMMU in the BIOS solved the issue.

**Comment by ekondis** [comment]
> Hello, I have managed to get it to work. Disabling IOMMU in the BIOS solved the issue.

I faced the same problem (see [issue 1429](https://github.com/RadeonOpenCompute/ROCm/issues/1429)), with different GPU configuration, but the workaround actually worked! Thank you, @ivanmlerner!
