### ISSUE TITLE
How to report `rocm.github.io` typos?

### ISSUE THREAD

**Issue by raxbits** [RadeonOpenCompute/ROCm#149]
Hi,

How can we report typos on the rocm.github.io website since the repo is hidden? 

Thanks.

**Comment by gstoner** [comment]
Report them here https://github.com/ROCm/ROCm.github.io

On Jul 4, 2017, at 9:18 PM, Ramin Ranjbar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

How can we report typos on the rocm.github.io<http://rocm.github.io> website since the repo is hidden?

Thanks.

**Comment by raxbits** [comment]
Thanks
