### ISSUE TITLE
ROCm dose not detect my GPU ( AMD Radeon R7 M265)

### ISSUE THREAD

**Issue by BahramianArmin** [RadeonOpenCompute/ROCm#1492]
enter in terminal 'rocm-smi' and says No AMD GPUs specified
-->rocm-smi

======================= ROCm System Management Interface =======================
WARNING: No AMD GPUs specified
================================= Concise Info =================================
GPU  Temp  AvgPwr  SCLK  MCLK  Fan  Perf  PwrCap  VRAM%  GPU%  
================================================================================
============================= End of ROCm SMI Log ==============================

so what should i do ???
thanks for your OPPONION!

**Comment by ROCmSupport** [comment]
Thanks @BahramianArmin for reaching us out.
Can you please share the output of "lspci -nn | grep AMD/ATI" command.
Thank you.

**Comment by BahramianArmin** [comment]
lspci -nn | grep AMD/ATI
05:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Opal XT [Radeon R7 M265/M365X/M465] [1002:6604]

**Comment by ROCmSupport** [comment]
Thanks @BahramianArmin 
Opal XT is not a ROCm supported card and so ROCm does not work with specific hardware.
Thank you.
