### ISSUE TITLE
GPU Peer-to-Peer (ROCm 4.2 with upstream amdgpu in kernel 5.13-X)

### ISSUE THREAD

**Issue by FilipVaverka** [RadeonOpenCompute/ROCm#1495]
ROCm 4.2 reports P2P as available for my machine with RX Vega 64 and Radeon VII in it. `rocm-bandwidth-test` therefore tries to measure the bandwidth between the GPUs, which causes immediate display corruption due to page faults and following GPU reset (see system log below).

Is P2P supposed to function in this configuration? Is any special configuration necessary to make it work?

While I hope P2P is (or can be) supported in this configuration, ROCm probably should avoid advertising it in situations where it can render the machine unusable.

> Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x0000000000048000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x00000000004d0000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x0000000000958000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x0000000000de0000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x0000000001268000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x00000000016f0000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000000048000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x00000000004d0000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000000958000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000000de0000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000001268000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x0000000001b78000 src_id:247 ring:3 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x00000000016f0000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000001b78000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000002000000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000002488000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma1] address:0x0000000002910000 src_id:247 ring:2 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Jun 19 14:47:52 Machine kernel: amdgpu 0000:10:00.0: amdgpu: [sdma0] address:0x0000000002000000 src_id:247 ring:3 vmid:8 pasid:32786, for process rocm-bandwidth- pid 4905 thread rocm-bandwidth- pid 4905
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: [mmhub0] no-retry page fault (src_id:0 ring:157 vmid:0 pasid:0, for process  pid 0 thread  pid 0)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:   in page starting at address 0x0000000000664000 from IH client 0x12 (VMC)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x0000013B
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          Faulty UTCL2 client ID: MP0 (0x0)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          MORE_FAULTS: 0x1
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          WALKER_ERROR: 0x5
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          PERMISSION_FAULTS: 0x3
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          MAPPING_ERROR: 0x1
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          RW: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: [mmhub0] no-retry page fault (src_id:0 ring:157 vmid:0 pasid:0, for process  pid 0 thread  pid 0)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:   in page starting at address 0x0000000000664000 from IH client 0x12 (VMC)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          Faulty UTCL2 client ID: MP0 (0x0)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          MORE_FAULTS: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          WALKER_ERROR: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          PERMISSION_FAULTS: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          MAPPING_ERROR: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          RW: 0x0
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:221 vmid:0 pasid:0, for process  pid 0 thread  pid 0)
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:   in page starting at address 0x0000000000480000 from IH client 0x1b (UTCL2)
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x000009BA
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          Faulty UTCL2 client ID: CPF (0x4)
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          MORE_FAULTS: 0x0
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          WALKER_ERROR: 0x5
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          PERMISSION_FAULTS: 0xb
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          MAPPING_ERROR: 0x1
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu:          RW: 0x0
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: wait for kiq fence error: 0.
Jun 19 14:48:03 Machine kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring page1 timeout, signaled seq=48225, emitted seq=48227
Jun 19 14:48:03 Machine kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
Jun 19 14:48:03 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: GPU reset begin!
Jun 19 14:48:03 Machine kernel: amdgpu 0000:0d:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Jun 19 14:48:03 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: BACO reset
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: GPU reset succeeded, trying to resume
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring gfx uses VM inv eng 0 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 5 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 6 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 7 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 8 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 9 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 10 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring kiq_2.1.0 uses VM inv eng 11 on hub 0
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring sdma0 uses VM inv eng 0 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring page0 uses VM inv eng 1 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring sdma1 uses VM inv eng 4 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring page1 uses VM inv eng 5 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring uvd_0 uses VM inv eng 6 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring uvd_enc_0.0 uses VM inv eng 7 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring uvd_enc_0.1 uses VM inv eng 8 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring vce0 uses VM inv eng 9 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring vce1 uses VM inv eng 10 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: ring vce2 uses VM inv eng 11 on hub 1
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: recover vram bo from shadow start
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: recover vram bo from shadow done
Jun 19 14:48:04 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: GPU reset(1) succeeded!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jun 19 14:48:04 Machine kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!

**Comment by ROCmSupport** [comment]
Thanks @FilipVaverka for reaching out.
Let me take a look at this.

**Comment by ROCmSupport** [comment]
Hi @FilipVaverka 
Can you please share below logs for better understanding of the problem.

# Collect cosole log from following run
<shell-prompt> rocminfo

# Collect cosole log from following run
<shell-prompt> rocm-bandwidth-test  -t

**Comment by FilipVaverka** [comment]
Here are requested logs:
- [rocminfo_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6789730/rocminfo_log.txt)
- [rocm_bandwidth_test_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6789731/rocm_bandwidth_test_log.txt)
- [clinfo_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6789733/clinfo_log.txt)

**Comment by ROCmSupport** [comment]
Thanks for the logs.
I have shared to developer. Thank you.

**Comment by seesturm** [comment]
https://github.com/ROCm-Developer-Tools/HIP/issues/2214 is related to this.

**Comment by ROCmSupport** [comment]
Hi @FilipVaverka 
Looking at the logs of RBT I don't see a reason as to why RBT run should fail. 
One thing to try is to run RBT in node-to-node scheme for following scenarios:

    RBT -s 0 -d 1
    RBT -s 0 -d 2
    RBT -s 1 -d 2
    RBT -s 1 -d 1
    RBT -s 2 -d 2

If my hunch is correct, one of the intra-device runs should fail (RBT -s 1 -d 1 or RBT -s 2 -d 2). Please update ticket with your observations including logs.
Thank you.

**Comment by FilipVaverka** [comment]
Neither of intra-device runs fail. It is Device-to-Device communication that causes issues:
- [rbt_s_2_d_1_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6799189/rbt_s_2_d_1_log.txt) - while this run causes bunch of SDMA messages in the system log [rbt_s_2_d_1_sys_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6799242/rbt_s_2_d_1_sys_log.txt)
- [rbt_s_1_d_2_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6799196/rbt_s_1_d_2_log.txt) - causes similar messages, but also causes range of error in system log and restarts the GPU on which graphics environment is running. [rbt_s_1_d_2_sys_log.txt](https://github.com/RadeonOpenCompute/ROCm/files/6799262/rbt_s_1_d_2_sys_log.txt) (here I first ran 2->1 and then 1->2 with errors)

**Comment by FilipVaverka** [comment]
So I swapped my RX Vega 64 for RX 6900 XT. The good news is this new configuration can successfully run through RBT! However I still see load of AMDGPU messages:

> Aug 20 20:13:56 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: SDMA gets an Register Write SRBM_WRITE command in non-privilege command buffer
Aug 20 20:13:56 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: [sdma0] address:0x0000000000048000 src_id:247 ring:2 vmid:8 pasid:32795, for process rocm-bandwidth- pid 6692 thread rocm-bandwidth- pid 6692

However, there are no page fault errors (I assume) which I did get with RX Vega 64 (and which I suspect led to GPU reset):

> Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: in page starting at address 0x0000000000664000 from IH client 0x12 (VMC)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: Faulty UTCL2 client ID: MP0 (0x0)
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: MORE_FAULTS: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: WALKER_ERROR: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: PERMISSION_FAULTS: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: MAPPING_ERROR: 0x0
Jun 19 14:47:52 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: RW: 0x0
Jun 19 14:47:53 Machine kernel: amdgpu 0000:0d:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:221 vmid:0 pasid:0, for process pid 0 thread pid 0)

While there are number of differences between RX Vega 64 and RX 6900 XT... is it possible that there are issues with asymemtric P2P, where one GPU has different amount of VRAM? Former configuration had 8GB Vega and 16GB R7, whereas now both GPUs have 16GB of VRAM.

I don't think we should mark this as resolved yet as this is not solution, rather observation.

**Comment by seesturm** [comment]
To my best knowledge the P2P patches did not make it into the upstream kernel yet. If you want to use P2P either rocm-dkms or manual patching of kernel is needed.
I've modified the patch for kernel 5.10.5. It can be downloaded here: [p2p-5.10.5-github.diff.txt](https://github.com/ROCm-Developer-Tools/HIP/files/5792508/p2p-5.10.5-github.diff.txt). You could try to modify for your kernel.

**Comment by FilipVaverka** [comment]
I'm running 5.13.8 right now. Is there any way to track this kind of differences between ROCm-dkms and upstream? I would like to keep track of things that are (not) supposed to work in upstream and also when to expect them to land.

**Comment by ROCmSupport** [comment]
Hi @FilipVaverka 
As ROCm 4.5 released recently a couple of days ago, can you please verify with ROCm 4.5 and update here.
Thank you.

**Comment by FilipVaverka** [comment]
Yes, the issue is still present with **ROCm 4.5** and kernel **5.14.14-1-default** (from OpenSUSE distribution). `RBT -a -v` still fails in Device-to-Device P2P transfers:

> rocm-bandwidth-test -a -v

          RocmBandwidthTest Version: 2.6.0

          Launch Command is: rocm-bandwidth-test -a -v


          Device: 0,  AMD Ryzen 9 3950X 16-Core Processor
          Device: 1,  AMD Radeon VII,  GPU-9f50716172fd5d40,  0d:0.0
          Device: 2,  AMD Radeon RX 6900 XT,  GPU-XX,  10:0.0

          Inter-Device Access

          D/D       0         1         2         

          0         1         1         1         

          1         1         1         1         

          2         1         1         1         


          Data Path Validation

          D/D       0           1           2           

          0         N/A         PASS        PASS        

          1         PASS        PASS        FAIL        

          2         PASS        FAIL        PASS

**Comment by rerrabolu** [comment]
Hi @FilipVaverka going by the comments, if I am reading them correctly, your system has amdgpu module built on upstream branch (not the dkms branch used by ROCm releases). Could you confirm this including the branch name used by you.

As @seesturm noted support for P2P is not yet part of non-dkms branches. There are discussions underway to enable P2P on upstream branch. I don't have a date yet as to when this will be part of it. 

Lastly on your system, do you have P2P issues if you were to load the amdgpu module built from the dkms branch i.e. one from ROCm release. Please let me know .

**Comment by FilipVaverka** [comment]
Yes, I'm running latest kernel distributed with OpenSUSE Tumbleweed. Which right now is:

> Linux 5.15.12-1-default #1 SMP Wed Dec 29 14:50:16 UTC 2021 (375fcb8) x86_64 x86_64 x86_64 GNU/Linux

I haven't tested DKMS at all as it seems to support only rather old kernels and I don't know how it would interact with kernel that already has amdgpu built into it. If its possible to use DKMS with kernel I'm running right now, I could try it out.

**Comment by rerrabolu** [comment]
@FilipVaverka thanks for confirming the setup you are using (5.15.12-1 with builtin amdgpu module). This explains why you are not able to do P2P. As indicated by @seesturm P2P support is absent in amdgpu code base that is part of upstream.

If you really wish to try/test P2P my suggestion would be step down to kernels supported by ROCm release. I would say the procedure to remove builtin modules is same as any other. Let us know if you have any surprises.

I will pass on you original observation of GPU reset so that on setups such as your system does not advertise P2P being enabled.

**Comment by FilipVaverka** [comment]
Here: [lspci_vv.txt](https://github.com/RadeonOpenCompute/ROCm/files/7840974/lspci_vv.txt). Both devices are reporting BAR 0 as 16GB and BAR 2 as 256MB, I believe.

**Comment by rerrabolu** [comment]
@FilipVaverka thanks for providing the lspci logs. I see that both devices report BAR-0 as having 16 GB.

- Device @ 0d:00.0 - Region 0: Memory at 7800000000 (64-bit, prefetchable) [size=16G]
- Device @ 10:00.0 - Region 0: Memory at 7000000000 (64-bit, prefetchable) [size=16G]

One question I have is where did you get these GPU's. Were these purchased in the open market or provided by AMD in some partnership program. The reason I ask is vBIOSes supporting large BAR is not common unless the devices are targeted for ROCm platforms.

**Comment by FilipVaverka** [comment]
Both GPUs are bought from local retailer the 6900XT has original vBIOS, while I had to flash Radeon VII bios as it didn't support UEFI out of the box (I believe the new vBIOS was from official AMD site).
I thought the gaming GPUs have to support resizable BAR since AMD introduced Smart Memory Access (I believe its Windows equivalent to resizable BAR on Linux).

**Comment by rerrabolu** [comment]
Thanks for the update. Your experience (GPU reset) was compounded because the vBIOS was reporting large BAR giving false green signal.

Amdgpu modules, ones based on upstream branches, should consult large BAR status only when other elements of P2P support are in place. This will avoid experiences such as yours.

**Comment by FilipVaverka** [comment]
I should just clarify that the GPU reset issue disappeared when I swapped RX Vega 64 for 6900XT.
I opened the issue with RX Vega 64 + Radeon VII and later swapped the Vega out.
Either way, thanks for some insight its very appreciated. Hopefully P2P support makes its way into upstream rather sooner than later.

**Comment by ROCmSupport** [comment]
Thanks for the suggestions and help @rerrabolu 
I am closing this now. Thank you.
