### ISSUE TITLE
Stress utility for MI100 Accelerator

### ISSUE THREAD

**Issue by question12345** [RadeonOpenCompute/ROCm#1497]
Hello 

Is there any utility I can use on centos 7.9 to stress test a MI100 accelerator?

thanks

**Comment by preda** [comment]
you could try gpuowl https://github.com/preda/gpuowl

**Comment by ROCmSupport** [comment]
Thanks @question12345 for reaching us.
Let me take a look.

**Comment by ROCmSupport** [comment]
I recommend to use/run using rocm-validation-suite and pick **rvs stress tests**.
Steps to do:
1. Install rocm using **sudo apt install rocm-dkms**
2. Install rvs(rocm-validation-suite) using **sudo apt install rvs**
3. cd /opt/rocm/rvs && sudo cp -rf /opt/rocm/rvs/testscripts/* /opt/rocm/rvs/
4. Run the script, for examples, take stress module: **sudo ./rvs-stress-long.sh**

Hope this helps.
Thank you.
