### ISSUE TITLE
setting GRUB_DEFAULT 

### ISSUE THREAD

**Issue by newling** [RadeonOpenCompute/ROCm#150]
This part of the README install instructions is not super-clear, I don't know what `GRUB_DEFAULT` should be set to.

> If using grub2 as your bootloader, you can edit the `GRUB_DEFAULT` variable in the following file:
> ```
> sudo vi /etc/default/grub
> sudo update-grub
> ```

**Comment by gstoner** [comment]
I have been working on new getting started instructions

https://rocm.github.io/ROCmInstall.html

Install or update ROCm

sudo apt-get update
sudo apt-get install rocm rocm-opencl-dev


Then, make the ROCm kernel your default kernel. If using grub2 as your bootloader, you can edit the GRUB_DEFAULT variable in the following file:

sudo nano /etc/default/grub


set the GRUB_Default Edit: GRUB_DEFAULT=”Advanced options for Ubuntu>Ubuntu, with Linux 4.9.0-kfd-compute-rocm-rel-1.6-77”

sudo update-grub



On Jul 5, 2017, at 7:24 AM, James Newling <notifications@github.com<mailto:notifications@github.com>> wrote:


This part of the README install instructions is not super-clear, I don't know what GRUB_DEFAULT should be set to.

If using grub2 as your bootloader, you can edit the GRUB_DEFAULT variable in the following file:

sudo vi /etc/default/grub
sudo update-grub
