### ISSUE TITLE
FR: OpenCL global memory single-pass read or write: bypass the L1 cache

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1500]
In OpenCL, when accessing global memory, I see two distinct cases: in one case, a large region of data is sequentially read once, or sequentially wrote once. In another case, a smaller block of data is accessed repeteadly.

In the first case (let's call it "single pass sequential"), going through the L1 cache provides no speed benefit AFAIK, but it does pollute the L1 cache with data that is not going to be accessed again. So, it would be useful to have a way to indicate this access pattern for an OpenCL buffer, and the compiler would skip the L1 cache in that case -- hopefully resulting in both faster access and better use of L1 (by avoiding evicting other cached data).

Maybe a mecanism already exist for achieving this?

**Comment by ROCmSupport** [comment]
Thanks @preda for reaching out.
I have assigned to compiler team to have a look.
Thank you.

**Comment by b-sumner** [comment]
@preda AMD is not in control of the OpenCL specification, although it does participate in the working group.  So if you want to raise issues with them, I would try an issue at https://github.com/KhronosGroup/OpenCL-Docs .

Also, FWIW, clang does __builtin_nontemporal_load and __builtin_nontemporal_store if you want to go nonstandard and nonportable.

**Comment by preda** [comment]
@b-sumner thank you for pointing to the LLVM nontemporal load/store builtins, I wasn't aware of them.

About OpenCL, I may consider raising issues there, though I'm not too optimistic about results.
