### ISSUE TITLE
ROCm 4.2.0 and update to centos-8.4.2105 system panic when GPU or DKMS accessed

### ISSUE THREAD

**Issue by bigtrak** [RadeonOpenCompute/ROCm#1504]
We have been running ROCm 4.2.0 on our centos-8.3 system.   Early this month, through the normal yum update chain, centos-8.4 was installed on our system.

Everything worked great until we tried to use the GPU -- the kernel crashes, and the GPU appears unresponsive.  The
centos-8.3 kernel version was  4.18.0-240.22.1, and the centos-8.4 version is 4.18.0-305.3.1

Debugging this, I noticed that the ROCm tools (rocminfo, clinfo)  would be unable to map some memory pages, which
is likely why it couldn't access the gpu
          amdgpu: init_user_pages: Failed to get user pages: -1

Further examination revealed that accessing DKMS, just to find it's status, was crashing the machine
          dkms status
          <system crashes>

I rebooted with the prior kernel, to verify that the GPU was working correctly.   With the older kernel, both rocminfo and
clinfo worked correctly, and 'dkms status'  showed
            amdgpu, 4.2-21.el7, 4.18.0-240.22.1.el8_3.x86_64, x86_64: installed (original_module exists)

We also ran some of our GPU binaries, and they worked correctly and did not crash the system either.

Initially we installed rocm-4.1, following the instructions at that time.  rocm-4.2 was installed via yum update,
as were the kernels and os update.   I believe the new kernel to be the first updated kernel after rocm-4.2
was installed, that is what a rough browse of the dnf logs shows w/out actual analysis of packages and
timestamps.

Is centos-8.4 supported by ROCm?  Does it require a re-install or ???

**Comment by ROCmSupport** [comment]
Hi @bigtrak 
Thanks for reaching out.
I certainly understood your problem, I am happy to help you.

ROCm does not support CentOS 8.4 right now and so the specific kernel does not work with ROCm and hence crashes and etc.
As you did **yum update**, it tried to OS upgrade/update along with rocm upgrade from 4.1 to 4.2, which is true.
But as we do not support CentOS 8.4 officially yet, things might/do not work, which is expected.
ROCm currently supports CentOS 8.3.
Hope this helps.
Thank you.
