### ISSUE TITLE
AMD CPUs don't have other acceleration solutions on Windows?

### ISSUE THREAD

**Issue by gp1322719830** [RadeonOpenCompute/ROCm#1513]
Our test environment is the Win10 test platform:
CPU: Ryzen 7 5800X 8-core 16 threads (Zen3 architecture)
GPU: Radeon RX 5500 XT (rDNA Architecture)

**Comment by ROCmSupport** [comment]
Hi @gp1322719830 
Thanks for reaching out.
Currently, ROCm is a Linux based solution.
Going forward AMD may decide to support other different OS/distributions based on our clients requirements and management Policies.
Thank you.

**Comment by gp1322719830** [comment]
> Hi @gp1322719830
> Thanks for reaching out.
> Currently, ROCm is a Linux based solution.
> Going forward AMD may decide to support other different OS/distributions based on our clients requirements and management Policies.
> Thank you.

Is there a deep learning accelerator in Windows？

**Comment by gp1322719830** [comment]
Is there a deep learning acceleration solution for Windows right now?
