### ISSUE TITLE
ROCm for Windows

### ISSUE THREAD

**Issue by wormwang** [RadeonOpenCompute/ROCm#1517]
CUDA support Windows
When ROCm support Windows and WSLg?

**Comment by ROCmSupport** [comment]
Hi @wormwang 
Thanks for reaching out.
"ROCm" is a Linux based solution. We do not have ROCm solution for Windows right now.
Going forward AMD may decide to support other different OS/distributions based on our clients requirements and management Policies.
Thank you.
