### ISSUE TITLE
What are the deep learning acceleration solutions for AMD CPUs

### ISSUE THREAD

**Issue by gp1322719830** [RadeonOpenCompute/ROCm#1519]

**Comment by ROCmSupport** [comment]
Thanks @gp1322719830 for reaching out.
Let me take a look and help you with the needed information.
Thank you.

**Comment by gp1322719830** [comment]
> Thanks @gp1322719830 for reaching out.
> Let me take a look and help you with the needed information.
> Thank you.

Hello, my dear, is there any progress？

**Comment by ROCmSupport** [comment]
Hi @gp1322719830, have gotten update on this.

On the CPU side, we have ZenDNN CPU inference accelerator library. You can get more info at: https://developer.amd.com/zendnn/ Please contact us (ZenDNN) on the email provided there for any updates / questions on ZenDNN. 
Request you to not to log issues / questions against CPUs in this space.
Hope this helps.
Thank you.
