### ISSUE TITLE
Repo Unreachable

### ISSUE THREAD

**Issue by raxbits** [RadeonOpenCompute/ROCm#152]
Hi, 

http://repo.radeon.com/rocm  ---> Unreachable 

Fails:
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add - 

Is it under maintenance by any chance? 

Thanks

**Comment by jedwards-AMD** [comment]
The repo.radeon.com URL is not accessible inside the AMD corporate network. If you are an AMD employee, you need to use the internal alias.

**Comment by nevion** [comment]
@raxbits does this mean you're working for AMD/interning or some other academic based deal?

**Comment by raxbits** [comment]
@nevion 

Both, kind of :)
