### ISSUE TITLE
Wavelet calculation support in ROCm

### ISSUE THREAD

**Issue by sampie** [RadeonOpenCompute/ROCm#1520]
I am wondering if ROCm is a good platform for doing scientific calculations, particularly for wavelet calculations. Does ROCm have a math library for calculating Mexican hat wavelet transforms? I could not find good documentation answering this question.

**Comment by ROCmSupport** [comment]
Thanks @sampie for reaching out.
I will check this for you and get back asap.
Thank you.

**Comment by malcolmroberts** [comment]
Hi, @sampie.  There isn't an official ROCm package for discrete wavelet transform.  For running on AMD GPUs, you can either try an OpenCL DWT, or try using the hipify tool on a CUDA-based DWT library.  This would all be third-party, so you'd have to reach out to the developers of those libraries for support.
