### ISSUE TITLE
Docker pulls the ROSM mirror and reports an error

### ISSUE THREAD

**Issue by gp1322719830** [RadeonOpenCompute/ROCm#1522]
Docker pulls the ROSM mirror to report the following error：
docker: unknown server OS: .

**Comment by ROCmSupport** [comment]
Hi @gp1322719830 
Thanks for reaching out.
For better understanding of problem, can you please share the steps you followed.
Please share all steps to reproduce the problem.
Thank you.

**Comment by gp1322719830** [comment]
> Hi @gp1322719830
> Thanks for reaching out.
> For better understanding of problem, can you please share the steps you followed.
> Please share all steps to reproduce the problem.
> Thank you.

sudo docker pull rocm/tensorflow:latest

**Comment by gp1322719830** [comment]
> Hi @gp1322719830
> Thanks for reaching out.
> For better understanding of problem, can you please share the steps you followed.
> Please share all steps to reproduce the problem.
> Thank you.

sudo docker pull rocm/tensorflow:latest
sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow:latest 

error:
docker: unknown server OS: .

**Comment by rkothako** [comment]
Hi @gp1322719830 
I am not able to reproduce this problem.
I have a Ubuntu 20.04.2 machine with Vega10 card in it.
I just did _sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow:latest_ and docker image was pulled.

**Digest: sha256:dcd14d6f1c3328eb90a0c1dd71b1693e6a98b68b6597617b88c0af3acabea91d
Status: Downloaded newer image for rocm/tensorflow:latest
root@2baf14b37d2a:/root#**

Looks like its the problem with your machine and I guess issue is specific to this kernel. Can you please try on a different machine and a different kernel and update.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @gp1322719830
I am not able to reproduce this problem.
I have a Ubuntu 20.04.2 machine with Vega10 card in it.
I just did sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow:latest and docker image was pulled.

Digest: sha256:dcd14d6f1c3328eb90a0c1dd71b1693e6a98b68b6597617b88c0af3acabea91d
Status: Downloaded newer image for rocm/tensorflow:latest
root@2baf14b37d2a:/root#

Looks like its the problem with your machine and I guess issue is specific to this kernel. Can you please try on a different machine and a different kernel and update.
Thank you.

**Comment by gp1322719830** [comment]
Solved,thanks!
