### ISSUE TITLE
ROCm RDNA2 support

### ISSUE THREAD

**Issue by cnergyone** [RadeonOpenCompute/ROCm#1524]
Issue: ROCm doesn't work on RDNA2 GPUs like 6900 XT.
Why: 6900 XT is good platform to run PyTorch and Tensorflow
Expected: Be able to use ROCm versions of PyTorch and TensforFlow on Ubuntu 20 and up

**Comment by ROCmSupport** [comment]
Hi @cnergyone 
Thanks for reaching out.
We are working on enabling some series of Navi cards into ROCm(internal validation is ongoing), but it will take little more time.
Please stay tuned for updates through our documentation.
Thank you.
