### ISSUE TITLE
ERROR："hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

### ISSUE THREAD

**Issue by gp1322719830** [RadeonOpenCompute/ROCm#1525]
ERROR："hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

DEVICE
**********************************
Name:                            gfx1012                            
Uuid:                              GPU-XX                             
Marketing Name:          Navi 14 [Radeon RX 5500/5500M / Pro 5500M]
Vendor Name:               AMD       
Feature:                         KERNEL_DISPATCH                    
Profile:                           BASE_PROFILE                       
Float Round Mode:       NEAR                               
Max Queue Number:    128(0x80)                          
Queue Min Size:           4096(0x1000)                       
Queue Max Size:          131072(0x20000)                    
Queue Type:                 MULTI                              
Node:                             1                                  
Device Type:                 GPU                     
**********************************

**Comment by ROCmSupport** [comment]
Hi @gp1322719830 
Thanks for reaching out.
We are not supporting Navi14 with ROCm now and so things can not work.
Please stay tuned at our documentation for all updates.
Thank you.
