### ISSUE TITLE
documentation for aarch64

### ISSUE THREAD

**Issue by aep** [RadeonOpenCompute/ROCm#1529]
there's various bugs around aarch64, so it seems supported, but it isnt documented.

going through https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html
using ubuntu, since this is required by the CPU vendor (NXP)

however, the repos are only for x86_64, so no packages can be installed from this

i'm assuming this means aarch64 requires a from source build?

**Comment by ROCmSupport** [comment]
Hi @aep 
Thanks for reaching out.
ROCm supports x86(x86_64) architecture officially. We do not have official support for aarch64.
Thank you.
