### ISSUE TITLE
Installation Problems on openSUSE Tumbleweed.

### ISSUE THREAD

**Issue by Photonico** [RadeonOpenCompute/ROCm#1534]
Hi,

My PC has AMD CPU(Ryzen 5900X) and an AMD graphic card(RX6800XT) (Of course, I'm a super AMD fan), so I want to use my GPU to do some scientific computation. The operating system is openSUSE Tumbleweed(20210726). I want the minimal installation of ROCm on my PC.

I add the repository resource via: `sudo zypper addrepo --no-gpgcheck http://repo.radeon.com/rocm/zyp/zypper/ rocm`
But I don't know which are the necessary packages for the ROCm.
And I find that:

Some packages can be installed directly.
`rock-dkms`
`rocm-gdb`: requires me to install python36 (My OS has python38 installed)
`rocminfo`
`rocm-opencl`
`rocm-opencl-devel`
`rocm-device-libs`
`hsakmt-roct`
`hipify-clang`
...

Some packages cannot be installed with dependencies problems.
`rocm-dkms` 
`rocm-dev`
`rccl`
`rocm-libs`
`hip-samples`
...

I'm new to computational science, could you tell me the minimal installation of ROCm environment requires me to install which packages from the [official repo](http://repo.radeon.com/rocm/zyp/zypper/)?
I just want to use [tensorflow-rocm](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream) and [CuPy-ROCm](https://pypi.org/project/cupy-rocm-4-0/).

I would appreciate it if you can respond to me.

**Comment by leofang** [comment]
Taking the discussion from cupy/cupy#5559 to here, as this is largely a ROCm issue instead of a CuPy issue. 

@Photonico reported that following the standard ROCm installation guide for SUSE-based distros would result in `libffi` not found. Maybe @ROCmSupport could share insight on whether this is a known issue for openSUSE Tumbleweed?

cc: @amathews-amd (for vis)

**Comment by ROCmSupport** [comment]
Hi @Photonico 
Thanks for reaching out.
Let me check this for you.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @Photonico 
When I go through the description of the ticket, I came to know that you are using Suse Tumbleweed.

2 points I wish to highlight here.
ROCm supports the latest SLES SP2 and it does not support any other variants of OpenSUSE currently.
And also RX6800XT is not a supported card with ROCm right now.

Anyhow, I will try to help you as much as I can.
Installation steps you followed are not proper and so recommend to use the one @ [https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#sles-15-service-pack-2](url)

Hope this solves your problem.
Thank you.
