### ISSUE TITLE
ROCm 4.3 question on GFX10 series gpu

### ISSUE THREAD

**Issue by Photonico** [RadeonOpenCompute/ROCm#1539]
Hi,

I have two computers, both have AMD graphic cards: RX6800XT, 5500M.
Does the coming ROCm 4.3 support these GPUs?

Sincerely,

**Comment by ROCmSupport** [comment]
Hi @Photonico 
Thanks for reaching out.
I have understood the problem and here to help you.

**Comment by ROCmSupport** [comment]
Hi @Photonico 
ROCm 4.3 does not support both of these cards(RX6800XT(Navi21), 5500M(Navi14)).
But the good news is that AMD started validating some set of Navi cards internally and ROCm support with them will come soon, not sure about the exact timelines, but tentatively before this year end. Please stay tuned for the updates.
Thank you.

**Comment by Photonico** [comment]
Thanks for your reply.
Could you make a prediction: AMD 6800XT ROCm vs RTX A5000 with CUDA on scientific computation.
It's very important for me. Thanks a lot.

**Comment by Photonico** [comment]
> Hi @Photonico
> ROCm 4.3 does not support both of these cards(RX6800XT(Navi21), 5500M(Navi14)).
> But the good news is that AMD started validating some set of Navi cards internally and ROCm support with them will come soon, not sure about the exact timelines, but tentatively before this year end. Please stay tuned for the updates.
> Thank you.

Hi, @ROCmSupport 
Thanks for your reply.
Could you make a prediction: AMD 6800XT ROCm vs RTX A5000 with CUDA on scientific computation.
It's very important for me. 
Thanks a lot.

**Comment by ROCmSupport** [comment]
Hi @Photonico 
I can not comment on this.
Thank you.

**Comment by tzislam** [comment]
Is there any progress in supporting AMD 6800XT with Rocm?

**Comment by ROCmSupport** [comment]
@tzislam 
AMD 6800 XT is also supported from ROCm 5.0 onwards, You can try now.
Thank you.
