### ISSUE TITLE
About to take the plunge

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#154]
I am about to install ROCm on my system, to run my OpenCL app. 
Just wanted to run this by you guys before I click install:

Hardware:

i7 6700 CPU
ASUS Z170-K MoBo
750W power supply
2X Saphire RX 470 GPUs : one card in 16x PCI slot, and one card in 4x PCI slot

Software:
Currently runs windows 10 - I want to dual bool to XUbuntu 16.04.2 
So, NOT a headless system.

Can anyone see any issues with this setup ? 

Thanks!

**Comment by briansp2020** [comment]
Only one GPU will work on that mother board.
See https://github.com/RadeonOpenCompute/ROCm/issues/46#issuecomment-264081299

**Comment by boxerab** [comment]
Thanks, Brian. I am happy to just one card - hopefully I don't have to actually remove the second card for this to work ?

**Comment by boxerab** [comment]
Can I just disable the x4 slot in the bios ?

**Comment by boxerab** [comment]
Also, can you please verify that non-headless OS will be fine ?

**Comment by gstoner** [comment]
That is perfect.

Greg
On Jul 7, 2017, at 11:39 AM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, can you please verify that non-headless OS will be fine ?

**Comment by boxerab** [comment]
Thanks, Greg. So, to confirm, I will only be able to use the card in the x16 slot.
Do I have to mess with the bios or remove the second card for this to work?

**Comment by ekondis** [comment]
Personally, I'm using the 1st GPU on a similar configuration without problems. I had experienced problems in the past with ROCm versions prior to 1.4 where I had to remove the 2nd GPU.

**Comment by boxerab** [comment]
Thanks, Elias. Glad to hear that.

**Comment by boxerab** [comment]
Thanks everyone for all of your help! Opencl seems to be working fine for single card.
Closing.
