### ISSUE TITLE
ROCM 4.3 apt installation issue 

### ISSUE THREAD

**Issue by ianferreira** [RadeonOpenCompute/ROCm#1543]
uname -a
5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsmod | grep amdgpu 
amdgpu               6283264  16
iommu_v2               20480  1 amdgpu
amdttm                 69632  1 amdgpu
amd_sched              36864  1 amdgpu
amdkcl                 24576  3 amd_sched,amdttm,amdgpu
drm_kms_helper        217088  1 amdgpu
drm                   552960  9 drm_kms_helper,amd_sched,amdttm,amdgpu,amdkcl
i2c_algo_bit           16384  2 igb,amdgpu

sudo apt install rocm-dkms 

yields

Extracting templates from packages: 100% 
(Reading database ... 170507 files and directories currently installed.)
Preparing to unpack .../rock-dkms-firmware_1%3a4.3-52_all.deb ...
Unpacking rock-dkms-firmware (1:4.3-52) ...
dpkg: error processing archive /var/cache/apt/archives/rock-dkms-firmware_1%3a4.
3-52_all.deb (--unpack):
 trying to overwrite '/usr/share/doc/amdgpu-dkms-firmware/LICENSE', which is als
o in package amdgpu-dkms-firmware 1:5.11.5.26-1271047
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/rock-dkms-firmware_1%3a4.3-52_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ianferreira** [comment]
work around seems to be to remove the firmware, presumably installed by the amdgpu-pro driver and re-run above

sudo apt remove amdgpu-dkms-firmware 1:5.11.5.26-1271047

followed by

sudo apt install rocm-dkms

**Comment by ROCmSupport** [comment]
Thanks @ianferreira for reaching out.
Looks like you have amdgpu driver components in your system already.
We can not install rocm on top of amdgpu-pro driver which is not recommended.
So recommendation is to install rocm on a clean system(should not have previous amdgpu/rocm drivers).
Hope this helps.
Thank you.

**Comment by FCLC** [comment]
For anyone else that may come across this, I had the same issue. 
After a broken ROCm uninstall, I used amdgpu-pro to regain graphics. 

then trying to reinstall ROCm, ran into the above issue- looks like it's marked in small font here: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#deploying-rocm
