### ISSUE TITLE
ROCm 4.2/4.3 with older kernels 4.12/4.15

### ISSUE THREAD

**Issue by vvsteg** [RadeonOpenCompute/ROCm#1546]
We have installed ROCm 4.2 successfully on the test machine with Ubuntu 16.04.6 LTS and the 4.15.0-47-generic kernel. Radeon VII works well for HIP-enabled applications (LAMMPS).

Please let me know should I expect ROCm 4.2/4.3 to work under SLES SP1 with the 4.12.14-195-default kernel that is used on the nodes of our MI50 equipped cluster? Linux upgrade is not an easy task and we would prefer not to upgrade SLES if it is possible.

**Comment by ROCmSupport** [comment]
Hi @vvsteg 
Thanks for reaching out.
We do not support old OS versions like Ubuntu 16.04.x and old kernels like 4.x officially now.
Officially supported OS versions are [https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems](url)
Anything other than these oses and kernels might work with ROCm 4.3(or 4.2) but not sure. Official support can not be claimed on these.
As per my experience, most of the times, things might work on old kernels/oses also, So recommend to give a try.
Thank you.

**Comment by ROCmSupport** [comment]
Closing this issue as the resolution provided in the last comment.
Thank you.
