### ISSUE TITLE
ROCM support for Navi (GFX10)

### ISSUE THREAD

**Issue by ianferreira** [RadeonOpenCompute/ROCm#1547]
Given https://github.com/RadeonOpenCompute/ROCm/issues/1465 I was hoping 4.3 would support Navi. Seems like some libraries  do support (rocRand) whiles others dont.  What is the latest targeting data from Navi support? @ROCmSupport

**Comment by ROCmSupport** [comment]
Hi @ianferreira 
Thanks for reaching out.
Navi support will come soon, expected before eoy 2021.
Thank you.

**Comment by kvnptl** [comment]
Still waiting for Navi 10 (RDNA 1) RX 56xx support...

**Comment by ianferreira** [comment]
> Still waiting for Navi 10 (RDNA 1) RX 56xx support...

Seems ROCM 5 support Navi 20 , haven't tried Navi 10. Have you tried the 21.50 driver?

**Comment by kvnptl** [comment]
> > Still waiting for Navi 10 (RDNA 1) RX 56xx support...
> 
> Seems ROCM 5 support Navi 20 , haven't tried Navi 10. Have you tried the 21.50 driver?

I have RX 5600 (Navi 10, RDNA 1). Although I tried ROCm 5 but I didn't work.

**Comment by RainingStars7** [comment]
> 

I have a RX5600M. So have this card got supported? I am trying to install rocm on it these days but I haven't make it.
