### ISSUE TITLE
Would you pls check whether float_as_int  is supported or not in Rocm v4.3

### ISSUE THREAD

**Issue by cyberspicecai** [RadeonOpenCompute/ROCm#1554]
when I use /opt/rocm-4.3.0/bin/hipconvertinplace-perl.sh to convert the source code, I got unsupported device function "float_as_int" and unsupported device function "int_as_float" warning.
But the file:///C:/Users/Administrator/Downloads/AMD_HIP_Supported_CUDA_API_Reference_Guide_v4.3.pdf list this function in HIP-Supported CUDA API.
Thanks.

**Comment by cyberspicecai** [comment]
when I use  /opt/rocm-4.3.0/bin/hipconvertinplace-perl.sh to convert the source code, I got unsupported device function "float_as_int" and  unsupported device function "int_as_float" warning. 
But the file:///C:/Users/Administrator/Downloads/AMD_HIP_Supported_CUDA_API_Reference_Guide_v4.3.pdf list this function in HIP-Supported CUDA API.
Thanks.

**Comment by Rmalavally** [comment]
Thank you for reaching out. For the ROCm v4.3.0 release, the latest scripts for hipification are available at: 

https://github.com/ROCm-Developer-Tools/HIPIFY/tree/master/bin

**Note:** The device functions int_as_float and float_as_int are unsupported; the supported are __int_as_float and __float_as_int.

AMD ROCm Documentation Team

**Comment by cyberspicecai** [comment]
> Thank you for reaching out. For the ROCm v4.3.0 release, the latest scripts for hipification are available at:
> 
> https://github.com/ROCm-Developer-Tools/HIPIFY/tree/master/bin
> 
> **Note:** The device functions int_as_float and float_as_int are unsupported; the supported are __int_as_float and __float_as_int.
> 
> AMD ROCm Documentation Team
Thanks your reply.  But I check the URL  you provide and find that the hipconvertinplace-perl.sh update date is 4 years ago. Am I right?

**Comment by ROCmSupport** [comment]
Hi @cyberspicecai 
The hipconvertinplace-perl.sh is just a wrapper around hipify-perl. See https://github.com/ROCm-Developer-Tools/HIPIFY/blob/master/bin/hipconvertinplace-perl.sh#L18. hipify-perl is constantly being updated. Last update was 5 days back.
Hope it helps.
Thank you.

**Comment by ROCmSupport** [comment]
Feel free to close the issue, if the resolution is provided.
Thank you.

**Comment by cyberspicecai** [comment]
thanks for your reply and your kindness.
