### ISSUE TITLE
Darktable opencl stops working with rocm 4.3.0 on supported GPUs

### ISSUE THREAD

**Issue by minfaer** [RadeonOpenCompute/ROCm#1557]
Hi,
I am opening this issue because #1553 got closed. I am experiencing the exact same thing on Vega/gfx900 which is on the official support list. This happens in CentOS 7 (and Fedora 34) just like #1553 reported for Ubuntu 20.04 LTS. ROCm 4.2 worked fine.

[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/7006122/clinfo.txt)
[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/7006123/rocminfo.txt)
[dt-cltest.txt](https://github.com/RadeonOpenCompute/ROCm/files/7006124/dt-cltest.txt)

**Comment by ROCmSupport** [comment]
Thanks @minfaer for reaching out.
Can you please share the exact steps to reproduce the problem?
Thank you.

**Comment by minfaer** [comment]
Sure

0. Uninstall all ROCm 4.2 packages if installed before
1. install rocm-dev (to have a complete install) from the ROCm 4.3 repository
2. run `darktable-cltest`

**Comment by minfaer** [comment]
This was fixed in ROCm 4.3.1 for me. I will thus close this issue. Thank You for looking into this!

**Comment by ROCmSupport** [comment]
Thanks @minfaer for confirming that issue is fixed with 4.3.1 and closed it.
Thank you.
