### ISSUE TITLE
opencl install question

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#156]
Can I install both `rocm-opencl` and `rocm-opencl-dev` packages, or do I only need one of them ?

Also, how do I "make the ROCm kernel your default kernel."  ?

**Comment by jedwards-AMD** [comment]
If you want to develop OpenCL applications, you need to install rocm-opencl-dev. If you only want the runtime, just install rocm-opencl. The rocm-opencl-dev package requires rocm-opencl.

**Comment by boxerab** [comment]
Thanks! I figured out how to set rocm kernel in grub, but I do get errors about PCI devices on booting.
Yet, I did try the vector_copy sample, and it works without error. Is there a way of running clinfo on my cards ?

**Comment by jedwards-AMD** [comment]
If you have rocm-opencl-dev install, clinfo should be in the /opt/rocm/opencl/bin/x86_64 directory. You should be able to run it.

**Comment by boxerab** [comment]
thank you. Install was pretty smooth. 

On boot, I get an ACPI error, and also:

`Invalid PCI ROM signature: expected ... got 0xffff`

**Comment by boxerab** [comment]
One thing about building vector_copy : I needed to run make as sudo.

**Comment by boxerab** [comment]
Awesome, clinfo works fine. Only sees one card, but that is fine with me for now.

**Comment by boxerab** [comment]
The following might be added to opencl install instructions :

Set an environment variable that points to the installation directory for OpenCL:
`export OPENCL_ROOT=/opt/rocm/opencl`

**Comment by boxerab** [comment]
Do I need to set `OPENCL_INCLUDE_ROOT` and `OPENCL_LIBRARY_ROOT`  ?

**Comment by jedwards-AMD** [comment]
Yes, the packaging has a permissions issue with that directory. We are going to replace vector_copy in the future, so we haven't bother fixing this problem. I am sorry for the inconvenience.

**Comment by boxerab** [comment]
No worries. As I said, install was very smooth, so looking forward to testing my app out.

**Comment by jedwards-AMD** [comment]
Yes, the packaging for the vector_copy sample has a permissions issue. We are going to replace vector_copy in the future, so we haven't bother fixing this problem. I am sorry for the inconvenience.

**Comment by jedwards-AMD** [comment]
The environment variables OPENCL_ROOT, OPENCL_INCLUDE_ROOT and OPENCL_LIBRARY_ROOT are all vestiges of the old AMD APPSDK. The installation of the rocm-opencl packages do not explicitly set them.

**Comment by boxerab** [comment]
I see. I have a cmake script that detects the opencl sdk. I will add some code to detect rocm. 
How do you recommend approaching this ?

Here is an example of such a cmake find file:


https://github.com/Kitware/VisCL/blob/master/CMake/FindOpenCL.cmake

**Comment by boxerab** [comment]
Perhaps we can add these changes upstream.

**Comment by jedwards-AMD** [comment]
Actually we are in the process of adding package management to all of the ROCm associated components, including the ROCr runtime, HIP, HCC, and the higher level libraries. We want to do the same for OpenCL as well. I will create a ticket for this, and hopefully we can get it in by next release.

**Comment by boxerab** [comment]
Sounds great. So, how would that work for my cmake project ? How would I detect rocm opencl  with this new management ?

**Comment by boxerab** [comment]
In the mean time, what can I set for OPENCL_INCLUDE_DIR and OPENCL_LIBRARY ?

**Comment by jedwards-AMD** [comment]
You would be able to use the find_package() CMake call for any of the ROCm packages. You would still have to set the CMAKE_MODULE_PATH, but only to the value /opt/rocm. All the package management information would exist in subdirectories that automatically searched by find_package. See the CMake documentation for more information on how this would work.

**Comment by jedwards-AMD** [comment]
All the OpenCL header files are in /opt/rocm/opencl/include (this includes the CL subdirectory). All the OpenCL libraries are in /opt/rocm/opencl/lib/x86_64.

**Comment by boxerab** [comment]
find_package support would be really nice - hope you're able to get this in soon.
In the meantime will hard-code those directories you mentioned. Thanks!

**Comment by boxerab** [comment]
Note: 

set  `OPENCL_INCLUDE_DIR` to `/opt/rocm/opencl/include`
and
`OPENCL_LIBRARY` to  `/opt/rocm/opencl/lib/x86_64/libamdocl64.so`

**Comment by boxerab** [comment]
I have quite a few different kernels that share common functionality, so I use the  `-I` include directive to include these common *.cl files. It looks like the current opencl compiler ignores `-I`.  This makes
it hard for me to get my kernels running.

Can someone please confirm that this is the case, and perhaps open an internal ticket for this ?

Thanks!

**Comment by boxerab** [comment]
Correction: include directive is working fine.  It seems the compiler doesn't like the `inline` keyword on 
kernel methods.  Please ignore comment above.

**Comment by nevion** [comment]
@boxerab you mean like #77 ?

**Comment by boxerab** [comment]
Yes, that was exactly the error I was getting!  This is code that was working fine on windows.

**Comment by gstoner** [comment]
Remember OpenCL C language is based on C99, so it uses the C99 semantics (which are different than the c89 or c++ semantics) for the inline keyword.  For C99 “static inline” is the proper declaration for functions that should be inlined in the current translation unit.

**Comment by boxerab** [comment]
OK, thanks Greg. Since this is OpenCL, is the inline keyword even necessary ?

**Comment by boxerab** [comment]
Does it help the compiler in any way ?

**Comment by boxerab** [comment]
Getting back to my code, I make heavy use of OpenCL events. Right now, I can compile all of my kernels, but it looks like events are not working. I will be digging in to this issue, but has anyone tested kernels with events under rocm ?

**Comment by boxerab** [comment]
I will close this - install issues have been resolved. Thanks to everyone for their help!

**Comment by nevion** [comment]
@boxerab  by the way on the inline keyword for performance/inlining in general, yes I've observed it to change things on gcc and even the old fglrx/amd app sdk, which was particularly sensitive to it for register usage IIRC.  I don't know how much difference inlining makes on ROCm but prior experiences tell me it will have an effect, even with optimizations on.

**Comment by boxerab** [comment]
Thanks. At first I just removed the `inline`, but in the end I switched to `static inline`.
Perhaps it is just me being superstitious :) but I don't want to mess with my current performance,
which is very high on RX 470 on windows.
