### ISSUE TITLE
torch.nn.Conv1d calculation is slow

### ISSUE THREAD

**Issue by Saber-f** [RadeonOpenCompute/ROCm#1565]
ROCm 4.0.1
in_channels = 1, out_channels = 64, kernel_size = 32, stride = 2.
The calculation speed of the forward pass is very slow when out_channels < 16 .
The calculation speed of the backward pass is very slow when out_channels < 32.
When I increase out_channels, the speed increases by about 60 times.
Nvidia does not have this problem.

**Comment by ROCmSupport** [comment]
Hi @Saber-f 
Thanks for reaching out.
Can you please share the following.
1. Exact steps to reproduce the problem to replicate locally here
2. Details of OS, Asic, any other additional information
3. Output of /opt/rocm/bin/rocminfo and /opt/rocm/opencl/bin/clinfo
4. Can you please try with the latest ROCm 4.3.1 release and share an update on this.

Thank you.

**Comment by Flock1** [comment]
Hi. I wanted to know if RX 6700 is compatible with ROCm.

**Comment by ROCmSupport** [comment]
Hi @Flock1 
This is to inform that RX 6700 is not compatible with ROCm. Thank you.

**Comment by ROCmSupport** [comment]
Hi @Saber-f 
Any update on execution steps please, so that we will work as per the steps and provide an update asap.
Thank you.

**Comment by Flock1** [comment]
@ROCmSupport, is there any plan to add RX 6700 to the compatibility list? I have that GPU and I want to use it for deep learning.

**Comment by ROCmSupport** [comment]
Hi @Flock1 
I do not have data at present. Request you to keep checking @ https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support

**Comment by ROCmSupport** [comment]
I am closing this as there is no update on execution steps for the last 15 days.
Request to open a new issue, if any, with all steps, for quick resolutions.
Thank you.
