### ISSUE TITLE
Clarify default installation path

### ISSUE THREAD

**Issue by bgoglin** [RadeonOpenCompute/ROCm#1568]
Hello
Can you clarify the documentation of the default install path? https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html talks about /opt/rocm and also about /opt/rocm-<version>/. All platforms I have access to use the latter. Some RPMs from your download area too.
Is /opt/rocm supposed to be a symlink to one of the /opt/rocm-<version>/ installations? Is one of your packages supposed to create that symlink? Or do you have 2 install strategies, one for single version under /opt/rocm, and one for multiversions under /opt/rocm-<version> but no /opt/rocm?
I am asking this because I'd the hwloc configure scripts to automatically look for ROCm SMI lib/headers under /opt/rocm but I couldn't find a single platform where it would work :/
Thanks

**Comment by ROCmSupport** [comment]
Thanks @bgoglin for reaching out.
I will check this for you and get back with an update asap.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @bgoglin 
Please find the responses here.

1. /opt/rocm is a soft link path to the actual installed rocm like /opt/rocm-4.3.1.
2. rocm-dev package creates that soft-link post installation.
3. At a time, only one way of installation is recommended, whether its single rocm(non-versioned rocm packages) or multi-rocm(versioned rocm packages).
Its not recommended to install single and multi rocm versions together, which makes installation breakages.

Eg: rocm-dev is non-versioned package for single rocm use, whereas rocm-dev4.3.1 is a multi-version package.
We can check whether we have installed single rocm or mutli-rocm using dpkg checks, eg: “dpkg -l | grep -i rocm-dev”.
If it prints “rocm-dev”, it means its a implies single rocm package. Else, if it prints “rocm-dev4.3.1”, it means its a versioned package.

Note: Two single rocm packages can not exist. At a time, only one single rocm version can be installed.
Two multi-version packages can co-exist but /opt/rocm softlink will point to latest installed multi-versioned rocm.

Hope this helps.
Thank you.

**Comment by bgoglin** [comment]
Thanks!
