### ISSUE TITLE
rocSOLVER Enhancements - presume you meant no longer 

### ISSUE THREAD

**Issue by whosystem** [RadeonOpenCompute/ROCm#1571]
rocSOLVER
Enhancements

Linear solvers for general non-square systems:

GELS now supports underdetermined and transposed cases

Inverse of triangular matrices

TRTRI (with batched and strided_batched versions)

Out-of-place general matrix inversion

GETRI_OUTOFPLACE (with batched and strided_batched versions)

Argument names for the benchmark client now match argument names from the public API

Fixed Issues

Known issues with Thin-SVD. The problem was identified in the test specification, not in the thin-SVD implementation or the rocBLAS gemm_batched routines.

Benchmark client **no** longer crashes as a result of leading dimension or stride arguments not being provided on the command line.

**Comment by doctorcolinsmith** [comment]
@whosystem Thanks for catching the error!  We'll get that fixed.

**Comment by Rmalavally** [comment]
Thank you for the feedback. The fixed defect for rocSOLVER is corrected in the Release notes document for ROCm v4.3.

AMD ROCm Documentation Team

**Comment by ROCmSupport** [comment]
Hi @whosystem 
Thanks for reaching out.
Issue is fixed now. Please check the documentation for the updated information.
Feel free to open a new issue, if any, for quick resolutions.
Thank you.
