### ISSUE TITLE
Cards not detected by opencl

### ISSUE THREAD

**Issue by ivanmlerner** [RadeonOpenCompute/ROCm#1573]
Hello, I am running arch linux with two RX5500, and while they were detected previously, now they are not.
I know this system is not supported, but I'd greatly appreciate some help debugging this issue.

[dmesg.txt](https://github.com/RadeonOpenCompute/ROCm/files/7179268/dmesg.txt)

**Comment by aoolmay** [comment]
There's no help for NAVI. NAVI is said to be officially supported soon, maybe next release, this year, whatever. We're stuck waiting, bro.

**Comment by ROCmSupport** [comment]
Hi @ivanmlerner 
Thanks for reaching out.
ROCm does not support Navi officially yet. Please stay tuned for the updates in future.
Thank you.
