### ISSUE TITLE
ROCm on ARM

### ISSUE THREAD

**Issue by Sturmflut** [RadeonOpenCompute/ROCm#1577]
We are extending our ARM testbed and will get some nodes with an Ampere Q80 ARM CPU and two MI100 GPUs to match the NVIDIA ARM HPC Development Kits (Ampere Q80 ARM CPU and A100 GPUs) we are also getting. We know ROCm isn't officially supported on ARM yet (although ARM support has been announced at least back in 2016 and 2017), but it's worth the try.

What is the current status on ARM? Are there source RPMs available for the packages offered at https://repo.radeon.com/rocm/yum/rpm/ ? That would make it easier to try to build all the software.

**Comment by ROCmSupport** [comment]
Hi @Sturmflut 
Thanks for reaching out.
We are not supporting ROCm on ARM right now.
We do not create src content for the packages available. I will discuss once again with BU team and share some update on this.

**Comment by Bigsmart408** [comment]
Is arm supported now?

**Comment by geerlingguy** [comment]
@Bigsmart408 - No; see https://github.com/ROCm/ROCm/issues/3960
