### ISSUE TITLE
ROCm OpenCL: kernel hangs with read_imageui() call 

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#158]
So, having some difficulties getting my kernels to run.

My program flow works like this:

1. map an opencl image, and create map completion event `MAP_COMPLETION_EVENT`
1. also unmap the same image, but the unmap call waits on user event `USER_EVENT`, and creates an unmap completion event `UNMAP_COMPLETION_EVENT`
1. when I receive the `MAP_COMPLETION_EVENT` event, copy data to mapped pointer and then set `USER_EVENT`
1. this will trigger the actual unmap, which will then set `UNMAP_COMPLETION_EVENT`
1. the kernel that uses the above image is enqueued but waits for `UNMAP_COMPLETION_EVENT`

I verified that I get as far as step 4 (the image is indeed unmapped and sends the event) but the kernel never actually runs.

What is best way of trouble shooting this ?

Also, I do enqueue a large number of kernels, but they will not run until they get their `UNMAP_COMPLETION_EVENT` events.

**Comment by boxerab** [comment]
I realize it is a lot of work, but if someone could port all of the APP SDK examples to ROCm, it would be great. Then I could try some simple kernels with opencl images to isolate the problem.  T

**Comment by gstoner** [comment]
The old SDK is being Phased out. The Apps team is working on new SDK you can find it here   https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases 

Note app like Mixbench already work as well.

**Comment by boxerab** [comment]
Great, can't wait to try this out. Any ballpark ETA for the full release ?

**Comment by boxerab** [comment]
So, I got my kernels to run, but I had to remove one critical line

`read_imageui(......)`

Otherwise, runtime will hang. So, there seems to be a problem with reading OpenCL images.

Also, performance was low : about **5 X slower** than windows version (where I also remove the `read_imageui` call.

**Comment by boxerab** [comment]
I realize these are not fully released drivers, and image support is relatively new.

**Comment by boxerab** [comment]
So, I have a reproducer for the kernel hang. I just modified the HelloWorld program.
Who is the best person to email this code to ?

**Comment by nevion** [comment]
@boxerab I'd say just attach it to a [gist](https://gist.github.com/) if it's a single file.  Hopefully image calls get fixed soon along with the events - I get mixed results using images over plain old buffers but they definitely help in some cases.  Events though, I use those very heavily but I haven't tested on ROCm yet - are you only have problems with mapping events on images or any buffer type or event type?

**Comment by boxerab** [comment]
In my reproducer, I don't use any events at all. Nor do I map. I only enqueue the kernel, then call clFinish. And the clFinish never returns.

Since this is some of my production code, prefer to email directly to someone at AMD.

**Comment by boxerab** [comment]
I use images quite heavily, and very happy with perf on windows.

**Comment by nevion** [comment]
@boxerab I understand... and I'm often in that situation but I take it it's too complicated to boil down to the minimum?  It could speed up efforts on the other side...

**Comment by gstoner** [comment]
I am going to have one my of staff contact you.   One thing be careful of out of bounds reference.   We now shutdown applications upon out of bounds. reference.



From Outlook for iOS<https://aka.ms/o0ukef>
____________

**Comment by boxerab** [comment]
Yes. I have done a lot of boiling :) so it is pretty simple code. Nothing that earth-shattering, but still would like to send it directly to company.

**Comment by nevion** [comment]
I guess what I meant with images vs buffers is I usually cache things to a local tile (I actually forget it's normal not to do this it's so common a technique in my arsonal), and then even blending it's competitive and more flexible with different oeprations.

**Comment by boxerab** [comment]
Thanks, Greg. I do have bounds checking in the kernel. The problem goes away if I don't read from the input image, and I am pretty sure the location is always in bounds, but I will double check.

**Comment by boxerab** [comment]
@nevion can you elaborate ? caching to local tile ?

**Comment by nevion** [comment]
@boxerab basically i[tem 4, step 1 - shared memory here](https://www.evl.uic.edu/sjames/cs525/final.html)

**Comment by boxerab** [comment]
Yes, so even if I always pass in (0,0) as the source location when reading, I still get this problem.

**Comment by boxerab** [comment]
OK, got it. In my case, this is a YBR colour transform, so no need for local mem.

**Comment by nevion** [comment]
Hm.  Perhaps related but I've done it before for [fast, high quality debayering of images here](https://github.com/nevion/cldemosaic)

**Comment by boxerab** [comment]
:) I forked your project a while back. Thanks for sharing this. Would like to play around with it at some point, just too many other things going on.

**Comment by gstoner** [comment]
We we be releasing 1.6.1 which will have an OpenCL runtime update.   Note images are still being worked on we have not Shipped our final 1.0 release yet for OpenCL on ROCm

**Comment by boxerab** [comment]
Great, looking forward to 1.6.1  Perhaps my problem is already fixed :)

**Comment by boxerab** [comment]
Are you guys still interested in a reproducer for this ?

**Comment by gstoner** [comment]
Yes.  so we can have unit test to make sure we fix and never show up again.

**Comment by boxerab** [comment]
Sounds good - would you mind sending me a contact email @ AMD so I can send it over ?

**Comment by boxerab** [comment]
Great, just say the word and I will make it available :)

**Comment by boxerab** [comment]
Sent. Thanks!

**Comment by gstoner** [comment]
It has been integrated into our OpenCL Test Framework.

**Comment by boxerab** [comment]
Great. Is this fixed in 1.6.1 ?

**Comment by gstoner** [comment]
We found the issue in the compiler, it did not make the ROCm 1.6.1 drop, but we get it into ROCm 1.6.2   -O1 did to work.

**Comment by boxerab** [comment]
Good to hear this, thanks !  Can I test 1.6.2 ?

**Comment by gstoner** [comment]
We are working on it now, next Monday or Tuesday is the target.

Greg
On Jul 25, 2017, at 1:04 PM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


Good to hear this, thanks ! Can I test 1.6.2 ?

**Comment by boxerab** [comment]
Fantastic, thanks!

**Comment by boxerab** [comment]
I upgraded to 1.6.1, disabled the problem read_imageui call that was causing the hang, and ran my kernels on both Ubuntu 16 with ROCm and Windows 10 with latest Catalyst driver.

Total time on ROCm was slightly slower than Catalyst, but CPU load was significantly lower - 65 % vs. 90.
Of course, the compilers are different, gcc vs msvc, but this looks promising.

Nice work, folks!

**Comment by boxerab** [comment]
So, is 1.6.2 out yet?

**Comment by boxerab** [comment]
Can't wait to try 1.6.2 ...... any ETA on when this will be available?

**Comment by boxerab** [comment]
Thanks. Is this fix available with apt update ? Because I just updated and the issue is still there, unfortunately. I did see the rocm updates.

**Comment by gstoner** [comment]
We released 1.6.2 this week.  It might not have made to the cut off, let me check.      I have another release coming in next week.

**Comment by boxerab** [comment]
Thanks. I didn't see an update for opencl, perhaps it wasn't tagged for
release.

On Aug 9, 2017 8:29 PM, "Gregory Stoner" <notifications@github.com> wrote:

We released 1.6.2 this week. It might not have made to the cut off, let me
check. I have another release coming in next week.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RadeonOpenCompute/ROCm/issues/158#issuecomment-321417384>,
or mute the thread

**Comment by boxerab** [comment]
Any update on this? I am happy to build it myself, but there isn't enough information on the opencl runtime github site to show how to do this.

**Comment by nevion** [comment]
@boxerab share your desire to learn how to build that runtime and where to even change the code.  It's an opensource mystery.

**Comment by gstoner** [comment]
We updating the build process to simplify it.   Remember we still in development on opencl on rocm

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boxerab** [comment]
Is this fixed in 1.6.3 ?

**Comment by gstoner** [comment]
It will come out in 1.6.4

**Comment by briansp2020** [comment]
When is your target release date for 1.6.4? Do you plant to test it with Ubuntu 16.04.3?

**Comment by boxerab** [comment]
Yes, also would like to know ETA for 1.6.4 .

**Comment by boxerab** [comment]
So, it looks like the latest release fixes this issue. Yay!!!!

**Comment by boxerab** [comment]
oh, false alarm, still broken .

**Comment by gstoner** [comment]
I am working getting OpenCL update out the door.

**Comment by boxerab** [comment]
Thanks! I am hoping I can complete my port to ROCm once this bug is fixed.

**Comment by boxerab** [comment]
Looking for ward to this fix. Any ETA on when it will drop ?  Thanks.

**Comment by boxerab** [comment]
Hurray!!! Finally fixed in 1.6.4 release.  Thank you!!!
