### ISSUE TITLE
ROCm installation for RX550

### ISSUE THREAD

**Issue by basileus93** [RadeonOpenCompute/ROCm#1581]
Hi,

I installed ROCm following the instructions here: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu .
I am using Ubuntu 18.04.5 and I downgraded the kernel to 5.4.0.71 to have the same reported in the instructions.
ROCm 4.3 fails with the problem reported in this issue: https://github.com/RadeonOpenCompute/ROCm/issues/1302
ROCm 4.1 fails with the following error
`ERROR: rocprofiler_iterate_info(), Translate(), ImportMetrics: bad block name 'GRBM', GPU device_id(699f) is not supported`
`/usr/bin/rocprof: line 358:  2582 Aborted                 (core dumped) /opt/rocm-4.1.0/rocprofiler/tool/ctrl`

I am trying to analyze an RX 550.
Could you please report which package versions (Ubuntu, kernel, ROCm, amdgpu) should be used for this GPU?

**Comment by xuhuisheng** [comment]
Try this:
<https://github.com/boriswinner/RX580-rocM-tensorflow-ubuntu20.4-guide>

**Comment by basileus93** [comment]
I tried that (same ubuntu, kernel and rocm versions). I am still getting: 
`>>> Run: `
`ERROR: rocprofiler_open(), Translate(), ImportMetrics: bad block name 'GRBM', GPU device_id(699f) is not supported`
/`opt/rocm/bin/rocprof: line 275:  4824 Aborted                 (core dumped) "./main.x"`

It seems that the counters are not supported for this GPU. The command `rocprof --stats` works fine.

**Comment by ROCmSupport** [comment]
Thanks @basileus93 for reaching out.
We do not support RX550 officially with ROCm and request to look at supported cards @ https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support
Hope this helps.
Thank you.
