### ISSUE TITLE
5700/5700 XT

### ISSUE THREAD

**Issue by Atelis** [RadeonOpenCompute/ROCm#1592]
compatibility on navi cards?

**Comment by ROCmSupport** [comment]
Hi @Atelis 
Thanks for reaching out.
As ROCm + Navi brought lot of critical issues in different areas/layers in the stack, hence things got delayed.
AMD is panning to enable official ROCm support on some set of Navi cards(but not all), most likely, with ROCm 5.0. 
Please stay tuned for the updates.
Thank you.

**Comment by esistgut** [comment]
@ROCmSupport can you tell us which Navi cards are going to be supported?

**Comment by ROCmSupport** [comment]
Hi @esistgut 
I can not comment right now until official announcement is driven from AMD/ROCm.
Thank you.
