### ISSUE TITLE
4.5 source download failed

### ISSUE THREAD

**Issue by gggh000** [RadeonOpenCompute/ROCm#1596]
cd ~/ROCm-4.5 ; ~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-4.5.x ; ~/bin/repo sync
-
fatal: Couldn't find remote ref refs/heads/roc-4.5.x
fatal: Couldn't find remote ref refs/heads/roc-4.5.x
manifests: sleeping 4.0 seconds before retrying
Downloading manifest from https://github.com/RadeonOpenCompute/ROCm.git
fatal: cannot obtain manifest https://github.com/RadeonOpenCompute/ROCm.git
fatal: error parsing manifest /root/ROCm-4.5/.repo/manifest.xml: [Errno 2] No such file or directory: '/root/ROCm-4.5/.repo/manifest.xml'
total 12

**Comment by zhang2amd** [comment]
The release branch and tag are added.

**Comment by ROCmSupport** [comment]
Hi @gggh000 
This issue is fixed now and hence closed.
Feel free to file a new issue, if any, for quick resolutions.
Thank you.
