### ISSUE TITLE
rocm 1.1.1 removed rocm-smi

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/ROCm#16]
I recently updated to rocm 1.1.1 under ubuntu 14.04.x. I saw that rocm-smi was remove during the update. I saw that I can install it via aptitude but I get a version that carries 1.0.0 in it's name. 

I was wondering how to proceed? Further, I love nvidia-smi in order to see if a process really runs on the dGPU, AFAIK I cannot do this with rocm-smi. What other methods are there to monitor app execution on the dGPU?

**Comment by jedwards-AMD** [comment]
The rocm-smi 1.0.0 version is the latest smi version, so you have the latest installed. It should be part of the default installation; the dependency list will be modified to includes it.

**Comment by psteinb** [comment]
Thanks for your reply, @jedwards-AMD. What about my other question in the original issue post?

**Comment by arodrigx7** [comment]
Hey @psteinb 

Do you mean the feature to list <pid> <process> name for all processes that have a gpu context allocated?

**Comment by psteinb** [comment]
well, in principle yes. I just need a command line tool where I see which processes uses the device. of course, some more statistics like GPU occupancy and memory use would help as well.

**Comment by arodrigx7** [comment]
These features are part of the plan. It should be available in one of the future ROCm releases.

**Comment by psteinb** [comment]
thanks @arodrigx7 for the update. I'd wish that these kind of things would be visible in a roadmap file in this repo, with this it would be easier for stakeholders to judge where rocm is potentially evolving. just as an idea.
 
other projects do something along those lines as well: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/resources/roadmap.md
