### ISSUE TITLE
Build ROCm on other OS

### ISSUE THREAD

**Issue by mariolpantunes** [RadeonOpenCompute/ROCm#1600]
Is there any way to compile and install the ROCm library on another OS?
I use Slackware, and there is no support for this OS.

**Comment by xuhuisheng** [comment]
How about install docker on other OS. Then run an ubuntu:20.04 image on docker, we could install rocm-dev and rocm-libs in docker.
And rock-dkms should be included in upstream linux kernel, I guess.

**Comment by ROCmSupport** [comment]
Hi @mariolpantunes 
Thanks for reaching out.
ROCm supports the mentioned OSes @ [https://github.com/RadeonOpenCompute/ROCm#supported-operating-environments](url)
All other OSes are not officially supported.
Thank you.

**Comment by dchmelik** [comment]
Oh, come on!  If one can package.deb & .rpm, then oldest GNU/Linux package type. txz--for Slackware (and about as large OS family)--is even easier than those.  Recent years you can can compile ROCm using Slackware's largest/quasi-official build script repository: [Linux Questions: (official) Slackware forum: AMD ROCm support ](http://www.linuxquestions.org/questions/slackware-14/amd-rocm-support-4175733461/).
