### ISSUE TITLE
Please add hipamd to default.xml

### ISSUE THREAD

**Issue by xuhuisheng** [RadeonOpenCompute/ROCm#1606]
Please add hipamd to default.xml, as HIP separated to HIP and hipamd.

There is the related PR, please review.  link #1605

**Comment by zhang2amd** [comment]
I have added the missing hipamd project. Thanks for your PR.

**Comment by xuhuisheng** [comment]
@zhang2amd 
Thank you for adding hipamd.
Now, I can go on updating my building documents.
:smile:

**Comment by ROCmSupport** [comment]
Thanks @zhang2amd for fixing this issue.
