### ISSUE TITLE
Standard installation of ROCm 4.5 leaves linker unable to find shared objects

### ISSUE THREAD

**Issue by PMunkes** [RadeonOpenCompute/ROCm#1607]
Following the installation guide [https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html) using the `amdgpu-install --usecase=hiplibsdk,rocm` method leaves the system unable to run Tensorflow-rocm. This is due to several necessary libraries being missing from locations in the LD_LIBRARY_PATH. Prepending a manually extended LD_LIBRARY_PATH fixes this and enables training on the GPU:
`$ LD_LIBRARY_PATH="/opt/rocm/rocblas/lib/:/opt/rocm/rccl/lib/:/opt/rocm/hsa/lib/:/opt/rocm/hip/lib/:/opt/rocm/miopen/lib/:/opt/rocm/hipfft/lib/:/opt/rocm/rocrand/lib/::$LD_LIBRARY_PATH" python3 mlp\ classifier.py`

OpenCL is unaffected by this.

OS: Ubuntu 20.4.3
CPU: Ryzen9 5900X
GPU: AMD Radeon RX6800

**Comment by xuhuisheng** [comment]
`export LD_LIBRARY_PATH=/opt/rocm/lib` should satisfied.
The reason is tensorflow-rocm build with `/opt/rocm-4.3.1`, the current version ROCm is `/opt/rocm-4.5.0`

**Comment by PMunkes** [comment]
It works, but this should probably be added to the documentation.

**Comment by ROCmSupport** [comment]
Hi @PMunkes 
Thanks for reaching out.
Good to know that exporting library path solves the issue.
I will work with Documentation team on these changes.
Thank you.

**Comment by ROCmSupport** [comment]
Docs updated with this information now.
[https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#post-install-actions](url)

**Comment by PMunkes** [comment]
Thanks.
