### ISSUE TITLE
Install ROCm packages without root permission

### ISSUE THREAD

**Issue by ye-luo** [RadeonOpenCompute/ROCm#1610]
It seems that amdgpu-dkms is the only piece needs to root to install.
All the rest ROCM components can be installed without root.
In the rocm user-guide, both the installer and package manager methods need root. It will be nice to allow me manually install ROCm without root in a preferred location.

**Comment by Rmalavally** [comment]
You must have root privileges to install ROCm or the driver because multiple steps during installation require root privileges. 
 
We do not support the ability to install ROCm at a location of your choice at this time. A solution may be provided in a future release.

AMD ROCm Documentation

**Comment by ROCmSupport** [comment]
Hi @ye-luo 
Thanks for reaching out.
As the integration of amdgpu and ROCm happened, so called Unified driver, amdgpu needs root privileges as it needs to access kernel components. ROCm userpsace does not need root access and so we can install them without root access.
So for simplification, we recommend to install ROCm+amdgpu using sudo.

You can install ROCm userspace alone using "sudo amdgpu-install --no-dkms --usecase=rocm"
Installing ROCm in a preferred location is not possible now, all ROCm components will go to /opt/rocm as usual.
Hope this helps.
Thank you.
