### ISSUE TITLE
Support Ubuntu 22.04

### ISSUE THREAD

**Issue by erkinalp** [RadeonOpenCompute/ROCm#1612]

**Comment by ROCmSupport** [comment]
Hi @erkinalp 
Thanks for reaching out.
As ROCm supports LTS versions of Ubuntu always and once 22.04 is out, we will support it officially.
Thank you.

**Comment by erkinalp** [comment]
20 days to Ubuntu release and Python dependencies are still not updated.

**Comment by erkinalp** [comment]
@ROCmSupport Can we reopen this, as Ubuntu's code freeze has happened?

**Comment by ROCmSupport** [comment]
Hi @erkinalp 
We will be supporting 22.04 officially, once we get GA build.

**Comment by Bengt** [comment]
@ROCmSupport By "GA" you most likely mean "General Availability". In the case of Ubuntu LTS, this is the release version of 22.04, set to be published on April 21st, 2022. ... Are you saying that AMD will have day-1-support for the next LTS version of Ubuntu?!

**Comment by keryell** [comment]
It would be good to have some preview support already so people can test right now, otherwise it is likely that there will be some bugs when people upgrade their machine with Ubuntu 22.04 final release.

**Comment by AbelVM** [comment]
> Hi @erkinalp Thanks for reaching out. As ROCm supports LTS versions of Ubuntu always and once 22.04 is out, we will support it officially. Thank you.

Ok, you didn't @ROCmSupport. Regardless the release notes, there is no way to install ROCm stack on Ubuntu 22.4.x. And i'ts being like 4 months since Ubuntu 22.04 release now :disappointed:

**Comment by keryell** [comment]
I will soon upgrade the machines of my team at AMD to Ubuntu 22.10 so I do not care about this issue anymore. :-(
@saadrahim It is kind of sad to have to use GPU from my competitors because we do not deliver our software up to the last mile. :-(
