### ISSUE TITLE
rock-dkms package disappeared from the repo

### ISSUE THREAD

**Issue by MathiasMagnus** [RadeonOpenCompute/ROCm#1614]
Hi! I wanted to install ROCm recently on some cluster machines but install fails due to a missing package.
```
$ sudo apt-add-repository 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ ubuntu main'
...
$ sudo apt install rocm-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rocm-dkms : Depends: rock-dkms but it is not installable
E: Unable to correct problems, you have held broken packages.
$ apt search rocm-dkms
Sorting... Done
Full Text Search... Done
rocm-dkms/Ubuntu 4.5.0.40500-56 amd64
  Radeon Open Compute (ROCm) Runtime software stack

$ apt search rock-dkms
Sorting... Done
Full Text Search... Done
```
Browsing through `https://repo.radeon.com/rocm/apt/` I saw that neither the `debian` (latest?) nor `4.5` folders have the `rock-dkms` package in them. `4.3.1` does. I installed the runtime in a docker container just Yesterday and it worked.

**Comment by ex-rzr** [comment]
I seems that they are replaced with `amdgpu-dkms` and `amdgpu-dkms-firmware`. At least that what the new install script (`sudo amdgpu-install --usecase=hiplibsdk,rocm`) installs.

**Comment by dkgaraujo** [comment]
Also facing the same issue as original poster, using Ubuntu 20.04.3 LTS.

**Comment by ROCmSupport** [comment]
Hi @MathiasMagnus 
Thanks for reaching out.
Installation procedure got changed from ROCm 4.5 and request to follow the new steps documented @ [https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html](url)
There will not be rock-dkms anymore and its replaced by amdgpu-dkms.
Thank you.

**Comment by erkinalp** [comment]
@ROCmSupport your link is formatted incorrectly

**Comment by ROCmSupport** [comment]
Hi @erkinalp,
Link is correct only. But request to copy and paste in browser window instead of clicking directly.
Thank you.

**Comment by keith24** [comment]
I've been googling for a while and still can't figure out how to install rocm on a stock ubuntu machine.  

These packages don't exist:  

```
$ sudo apt install amdgpu-dkms amdgpu-dkms-firmware
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package amdgpu-dkms
E: Unable to locate package amdgpu-dkms-firmware
```

There's no information in [the docs](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu) on how to install `rock-dkms` or get past this error.  

Why was this closed?  There's no solution.

**Comment by ROCmSupport** [comment]
rock-dkms is no more now and its amdgpu-dkms now.
Request to follow the installation procedure @ https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#rocm-installation-guide-v4-5

Thank you.

**Comment by cdm-work** [comment]
Late to this discussion, but this doesn't help with RPMs that still require `rock-dkms`:
```
$ rpm -qRp rocm-dkms-4.5.2.40502-sles152.164.x86_64.rpm
warning: rocm-dkms-4.5.2.40502-sles152.164.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 1a693c5c: NOKEY
/bin/sh
/bin/sh
/bin/sh
/bin/sh
rock-dkms
rocm-core
rocm-dev
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```
That RPM was downloaded from [https://repo.radeon.com/rocm/zyp/4.5.2/](https://repo.radeon.com/rocm/zyp/4.5.2/).

I'm trying to set up an automated install, and the fact that `rock-dkms` is required but cannot be found is breaking unattended installation.  I'm working with SLES systems.

**Comment by Two-Worlds** [comment]
We get that, but fails as signature has now expired.
