### ISSUE TITLE
Support for Centos 7.9 Kernel version 3.10.0-1160

### ISSUE THREAD

**Issue by orensg1** [RadeonOpenCompute/ROCm#1615]
I have recently upgraded a Centos 7.9 machine to the latest kernel version: 3.10.0-1160
Unfortunately ROCm upgrade has failed.
According to:  https://github.com/RadeonOpenCompute/ROCm 
Only CentOS 7.9 kernel 3.10.0-1127 is supported by ROCm
Are there any plans to support kernel version 3.10.0-1160?
Are there any alternatives to downgrading the kernel version?

**Comment by ROCmSupport** [comment]
Hi @orensg1, Thanks for reaching out.
I certainly understood the problem.
Yes, we validated 3.10.0-1127 with CentOS 7.9 and hence official support is given.
We started validating 3.10.0-1160 with our internal builds and things are pretty good. So next ROCm release will have official 3.10.0-1160 support.
Hope its clear.
Thank you.

**Comment by orensg1** [comment]
Great, thank you.
