### ISSUE TITLE
Question: What does ROCm stand for?

### ISSUE THREAD

**Issue by jakub-homola** [RadeonOpenCompute/ROCm#1628]
What does the ROCm acronym stand for? I have seen "Radeon Open Compute ecosysteM", "Radeon Open Compute platforM", "Radeon Open eCosysteM", "Radeon Open CoMpute", but could not find anything on any official site.

Can you please clarify what it is supposed to stand for, and add it to the documentation?

**Comment by ROCmSupport** [comment]
Its mainly **Radeon Open Compute platforM**
Good point. I never worried about this information, anyhow its good to highlight in our documentation clearly.
I will reach docs team for this addition. Thank you.

**Comment by cgmb** [comment]
@ROCmSupport, I was under the impression that ROCm stood for "**R**adeon **O**pen E**c**osyste**m**". Maybe send me a message at Cordell.Bloor@amd.com and we can sort out the confusion.

**Comment by ROCmSupport** [comment]
Hi @cgmb and all,
We are coming up with a conclusion on this topic soon, please wait for sometime. We will come with proper documentation update.
Thank you.

**Comment by ROCmSupport** [comment]
Hi All,
Please find the answer here.

ROCm is a brand name for ROCm™ open software platform (for software) or the ROCm™ open platform ecosystem (includes hardware like FPGAs or other CPU architectures).

_Note, ROCm no longer functions as an acronym._ 

Hope this helps. Thank you.

**Comment by erkinalp** [comment]
Radeon Open Compute module 😹

**Comment by Tiffany-00** [comment]
I have the true and best answer. Greg Stoner shared with me that it stands Radeon Open Compute Platform, so ROCp, but they concatenated all the letters before m and made ROCm. ROCm sounded better and was an easier mnemonic to remember and they were inspired by the AC/DC posters in their cubes.

**Comment by jnordenswan** [comment]
Uppercase "ROC" with lowercase "m" is what I see.

**Comment by dmitry-v-vlasov** [comment]
After my payment for an an ASUS ROG laptop with APU and even with a supported GPU (with sources compilation in Manjaro) I can suggest some versions of this abbreviation (Thank You for your sarcastic talent, ChatGPT): 
1. Really Ordinary Computing mediocrity
2. Ridiculously Overpriced Computer module
3. Recklessly Overheating Crappy machine
4. Randomly Overrated Calculator manufacturer
5. Rarely Operating, Constantly malfunctioning
6. Recent Overestimated Computer mishap
7. Retrograde Online Crashing masquerade
8. Run-of-the-mill Overhyped Contraption mess
9. Rapidly Obsoleted Contrived malfunction
10. Rotten Oranges: Cursed machinery
11. Really Outdated Computing Module
12. Ridiculously Overpriced Consumer Magic
13. Randomly Overheating Calculation Machine
14. Really Ordinary Crashing Mishap
15. Remote Online Catastrophic Mayhem
16. Regularly Overrated Computing Mumbo-jumbo
17. Ruined Oversized Confusing Mess
18. Rather Oddly Configured Computer Monstrosity
19. Reliably Overcomplicated Chaos Machine
20. Recurring Outlandish Computing nightMare
