### ISSUE TITLE
ROCm in 6900xt not recognized

### ISSUE THREAD

**Issue by EduMio** [RadeonOpenCompute/ROCm#1631]
Hello. I am trying to run my pytorch model with the ROCm with my 6900xt. I installed the ROCm 4.5 correctly, it works perfectly with tensorflow. So I moved on and downloaded with docker pull rocm/pytorch:latest, but it wont recognize my GPU. The command I am using is `sudo docker run -it -v $HOME:/data --privileged --rm --device=/dev/kfd --device=/dev/dri --group-add video rocm/pytorch:latest` it gives me the following error:
![image](https://user-images.githubusercontent.com/55565758/143923202-05496d18-7a5a-48cb-9bfe-34946c0bd3fb.png)

**Comment by ROCmSupport** [comment]
Hi @EduMio 
Thanks for reaching out.
Navi series of cards are not officially supported right now with ROCm 4.5 and so some things do not work definitely. We can not comment/work on this issue until its supported officially.
Please stay tuned for more updates through our documentation. Thank you.

**Comment by Djip007** [comment]
container rocm/pytorch:latest is build with rocm 4.3.1... not 4.5... may be try to rebuild pytorch with rocm 4.5.x

**Comment by EduMio** [comment]
I wish I could, but in the official page (
https://hub.docker.com/r/rocm/pytorch/tags) I did not find a 4.5.x version
of it. I tried with the rocm/pytorch:latest but to no avail. I guess we
just have to wait for the 4.5.x version.

**Comment by Djip007** [comment]
yesterday: rocm4.5.2_ubuntu18.04_py3.8_pytorch_1.10.0
=> pytorch + rocm4.5.2... did'nt test... but good news no?

**Comment by EduMio** [comment]
That is good news for sure, I am going to test that on my VM and see how it
goes. Thank you for sharing the info!

**Comment by Djip007** [comment]
yesterday: rocm4.5.2_ubuntu18.04_py3.8_pytorch_1.10.0
=> pytorch + rocm4.5.2... did'nt test... but good news no?

**Comment by Djip007** [comment]
Au cas ou (et pas du tout testé...) je suis tombé la dessus:
https://download.pytorch.org/whl/nightly/rocm4.5.2/torch_nightly.html

ca voudrait dire que il y a plus que les versions qui sont mis sur la page d'accueil de pytorch.. https://pytorch.org/get-started/locally/

**Comment by EduMio** [comment]
Thank you very much! I am going to try it in some weeks and might post some
testing feedbacks in my machine
