### ISSUE TITLE
Lower vddc for seri 6000

### ISSUE THREAD

**Issue by phucvinh52** [RadeonOpenCompute/ROCm#1635]
Hi team,
I have a problem when use voltoffset for 6600xt.
I set VDDC_OFFSET: -150 (or -200 or -400) but when I cat file `/sys/class/drm/card1device/hwmon/hwmon*/in0_input` seem it stable min at 737(mV).
Could i set lower vddc for my gpu.
Thanks

**Comment by ROCmSupport** [comment]
Hi @phucvinh52 
Thanks for reaching out.
We are not supporting Navi23 with ROCm, so can not comment on this.
Thank you.

**Comment by masahi** [comment]
> We are not supporting Navi23 with ROCm

Do you mean "currently", or navi23 support will never come even in future release? I've seen that RDNA2 cards would get support soon.

**Comment by ROCmSupport** [comment]
Hi @masahi 
I am not sure about future plans right now.
If we have some support plans in future, we will update via our documentation. Thank you.
