### ISSUE TITLE
rocm sdk like nvhpc sdk

### ISSUE THREAD

**Issue by zjin-lcf** [RadeonOpenCompute/ROCm#1639]
Could people install ROCM packages (debugger, profiler, HIP compiler, etc) like the way people install Nvidia HPC SDK ?  Users don't necessarily need root permission to install the SDK. 

Not sure whether people might ask similar questions before. Thanks.

**Comment by ROCmSupport** [comment]
Hi @zjin-lcf 
Thanks for reaching out.
We do not have it right now.
But we are actually working on similar thing here at ROCm and will share once we are ready with it.
Please stay tuned for updates through our documentation.
Thank you.

**Comment by zjin-lcf** [comment]
People really despair of, suffer from, and struggle with the installation. Please let people know once you are ready.  Thanks.
