### ISSUE TITLE
Installing rocm on trusty

### ISSUE THREAD

**Issue by kredlapa** [RadeonOpenCompute/ROCm#164]
**On Ubuntu 14.04.2 64 bit,** 
While trying to build opencl on rocm1.6 from the below
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime
when i try to install rocm using the steps mentioned in the github link, rocm is not getting installed, console says rocm depends on rocm-dev but its not going to be installed.

**Comment by gstoner** [comment]
Currently, we have moved to supporting 16.04 only with ROCm 1.6
