### ISSUE TITLE
Get UUID from HIP API level device

### ISSUE THREAD

**Issue by bertwesarg** [RadeonOpenCompute/ROCm#1642]
Is there a way, to get the UUID of a device from the HIP API? I can see the UUID of devices with `rocm-smi --showuniqueid` and also with `rocminfo`. But I would like to relate them, without considering `HIP_VISIBLE_DEVICES`.

**Comment by bertwesarg** [comment]
FYI, CUDA provides the UUID in the `struct cudaDeviceProp::uuid` member.

**Comment by ROCmSupport** [comment]
Hi @bertwesarg 
Thanks for reaching out.
I will get information from HIP team and will update you asap.
Thank you.

**Comment by JBlaschke** [comment]
Are there any updates on this, I would also be interested

**Comment by bertwesarg** [comment]
They implemented it and promised us to get a beta release. But nothing in our hands yet.

**Comment by ROCmSupport** [comment]
Hi @bertwesarg 
Our HIP team implemented it, changes are ready, will be merged into our internal builds soon and thus it will be part of Release branch.
As per the discussion with HIP team, this will be part of ROCm 5.2 release and request to wait for the same.
Thank you.

**Comment by bertwesarg** [comment]
That is good news. Thanks for the update. A preview build, so that we can test the feature is still desirable. I will talk to my AMD contact again.

**Comment by bertwesarg** [comment]
Dear all,

`hipDeviceGetUUID` returns a 16 byte UUID, but ROCM SMI only a 8 byte (`uint64_t`) unique ID. Are they the same? And if so, how to match these?

Thanks.

**Comment by TimourPaltashev** [comment]
Hi Bert, 
Below the comment from developers:
HIP makes use of ROC Runtime to query the UUID. As per ROCr API spec (See https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/83b46ab91086e10edbc6100d5e55cac11c9b5d7a/src/inc/hsa_ext_amd.h#L291-L300), the UUID it returns is of the form "GPU-<16-digit-hex-string>". HIP returns the 16-digit hex string.

As far as how ROCr converts the 8 byte value returned by ROCm SMI to a 16 byte value see https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/1594b0778a4d9a7c7065190489aa8be901e66c34/src/core/runtime/amd_gpu_agent.cpp#L993-L1011 for the implementation.

Regards,
Maneesh

**Comment by bertwesarg** [comment]
Thanks, this matches my assumption.

**Comment by bertwesarg** [comment]
closed as solved
