### ISSUE TITLE
will rocm support centos 9 and rhel 9?

### ISSUE THREAD

**Issue by siyy123** [RadeonOpenCompute/ROCm#1646]

**Comment by ROCmSupport** [comment]
Hi @siyy123 
Thanks for reaching out.
ROCm supports RHEL/CentOS 9 versions also in future as per the planned timelines. 
Please stay tuned for updates via our documentation.
Thank you.

**Comment by klausbu** [comment]
What is the planned timeline for adding ROCm support for RHEL 9?

It`s impossible to develop/adapt/optimize software to make use of my AMD hardware for my engineering projects.

**Comment by klausbu** [comment]
Here it is finally, RHEL 9 support with ROCm 5.3 - thank you
