### ISSUE TITLE
unable to install with amdgpu-install in centos 8 stream

### ISSUE THREAD

**Issue by siyy123** [RadeonOpenCompute/ROCm#1647]
I cannot install amdgpu driver with amdgpu-install in centos 8 stream. the installer shows it fails to download the amdgpu repository.
I find that the amdgpu repo definition file has been using an environment variable amdgpudistro, which the installer can not properly define in centos 8 stream.

**Comment by ROCmSupport** [comment]
Hi @siyy123 
Thanks for reaching out.
Can you please share the exact steps(step by step) to reproduce the problem, so that I will try locally here and will update with the resolution. Thank you.
