### ISSUE TITLE
[Question] Typical power sensor update intervals and accuracy

### ISSUE THREAD

**Issue by lukalt** [RadeonOpenCompute/ROCm#1649]
For a thesis, I am currently evaluating on-board power monitoring facilities of different CPUs and GPUs in the field of scientific computing.
In the documentation of the SMI, I found out that many power and energy metrics as well  as information on the respective accuracy and update interval are exposed through the sysfs interface and can be updated by the GPU during runtime (c.f. https://rocmdocs.amd.com/en/latest/ROCm_System_Managment/ROCm-System-Managment.html). Unfortunately, I do not have a supported GPU available to investigate this.
Are there any further information on details of the power sensors available? Specifically, I am interested in typical values for update_interval, power[1-*]_average_interval, and power[1-*]_accuracy for an exemplary device. Thanks in advance!

**Comment by ROCmSupport** [comment]
Thanks for reaching out.
I understood your query. Let me assign to SMI team for help.
Thank you.

**Comment by bill-shuzhou-liu** [comment]
The driver can read at 1ms intervals. If multiple calls come within 1ms then previous cached value is returned.

**Comment by lukalt** [comment]
Okay, thank you!
