### ISSUE TITLE
[Debian official packaging] How is ROCm LLVM fork still needed?

### ISSUE THREAD

**Issue by Maxzor** [RadeonOpenCompute/ROCm#1650]
Hello,
Posting across github organisations:
https://github.com/ROCm-Developer-Tools/HIP/issues/2449

**Comment by ROCmSupport** [comment]
Thanks @Maxzor for reaching us out.
As this issue is already addressed/updated @ https://github.com/ROCm-Developer-Tools/HIP/issues/2449, I am closing this thread here. Please check/see the progress @ https://github.com/ROCm-Developer-Tools/HIP/issues/2449
Thank you.
