### ISSUE TITLE
Not having a dedicated wikipedia page for ROCm is bad

### ISSUE THREAD

**Issue by Maxzor** [RadeonOpenCompute/ROCm#1652]
https://en.wikipedia.org/wiki/GPUOpen#Radeon_Open_Compute_(ROCm)
NVidia Cuda and Intel OneAPI have their obviously.

P.S. There is an overall blatant lack of entry & medium level documentation about the stack, about what each component does, and how the components interact with one another. Specifically talking about the device driver, the system runtime and low-level libraries, such as the roct-thunk, the rocr-runtime, hipamd and hipcc compiler, the common language runtime...

I don't understand how an AMD executive in charge of the ROCm stack cannot realize that throwing a few hundred k$ towards good documentation is an urgent matter in the race for GPU APIs.

At least there is no wall-of-text. I mean, come on. https://i.imgur.com/Mel05t9.png

**Comment by Maxzor** [comment]
This is not my job, so I made a skeleton and turned it into a game: fix the inaccuracies and mistakes, inspired by [Cunningham's Law](https://meta.wikimedia.org/wiki/Cunningham%27s_Law) :smile: .

https://en.wikipedia.org/wiki/Rocm

**Comment by ROCmSupport** [comment]
Thanks @Maxzor for making this point.
We have much documentation defined at different places but can not comment on wiki part.
Let me talk to my management/ business unit team and get some update asap.
Thank you.

**Comment by keryell** [comment]
@Maxzor thank you for doing this.
The problem with Wikipedia is that AMD cannot contribute massively to this page without creating a conflict of interest. https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest
So external contributors are welcome. :-)

**Comment by kentrussell** [comment]
Closing thanks to the great work of the open-source community. https://en.wikipedia.org/wiki/ROCm is still being updated.
