### ISSUE TITLE
Can't install rock/rocm on Linux kernel 5.13.0-27-generic

### ISSUE THREAD

**Issue by bpickrel** [RadeonOpenCompute/ROCm#1658]
I just tried to install rocm on a brand new computer with freshly installed OS (Ubuntu 20.04.3), and encountered repeated failures including the the following:

```bpickrel@home-tower:~$ sudo apt-get install amdgpu-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
amdgpu-dkms is already the newest version (1:5.11.32.40502-1350682).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up amdgpu-dkms (1:5.11.32.40502-1350682) ...
Removing old amdgpu-5.11.32-1350682 DKMS files...

------------------------------
Deleting module version: 5.11.32-1350682
completely from the DKMS tree.
------------------------------
Done.
Loading new amdgpu-5.11.32-1350682 DKMS files...
Building for 5.13.0-27-generic
Building for architecture x86_64
Building initial module for 5.13.0-27-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/amdgpu-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.13.0-27-generic (x86_64)
Consult /var/lib/dkms/amdgpu/5.11.32-1350682/build/make.log for more information.
dpkg: error processing package amdgpu-dkms (--configure):
 installed amdgpu-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 amdgpu-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The installation process for ver 4.5 apparently does not support the default linux kernel 5.13.0-27-generic.  (Apparently the previous version rocm 4.3 does not have this issue.)

**Comment by ramcherukuri** [comment]
From 4.5 installation steps changed for DKMS, here you can find the details. 
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#installer-script-method

**Comment by srinivamd** [comment]
> The installation process for ver 4.5 apparently does not support the default linux kernel 5.13.0-27-generic. (Apparently the previous version rocm 4.3 does not have this issue.)

Yes, Ubuntu 20.04 updated HWE kernel to 5.13 which will be supported in the next ROCm release.

**Comment by bpickrel** [comment]
Why do the instructions at [https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#confirm-you-have-a-supported-linux-distribution-version](url) not make that clear? The  ["System Requirements"](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#confirm-you-have-a-supported-linux-distribution-version) paragraph states that Ubuntu 20.04.3 is supported.

**Comment by Weaverzhu** [comment]
```c
In file included from /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:34:
 /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_topology.h:229:11: error: conflicting types for ‘amd_iommu_pc_get_max_banks’
   229 | extern u8 amd_iommu_pc_get_max_banks(u16 devid);
       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:31:
 ./include/linux/amd-iommu.h:201:4: note: previous declaration of ‘amd_iommu_pc_get_max_banks’ was here
   201 | u8 amd_iommu_pc_get_max_banks(unsigned int idx);
       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:34:
 /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_topology.h:230:11: error: conflicting types for ‘amd_iommu_pc_get_max_counters’
   230 | extern u8 amd_iommu_pc_get_max_counters(u16 devid);
       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:31:
 ./include/linux/amd-iommu.h:202:4: note: previous declaration of ‘amd_iommu_pc_get_max_counters’ was here
   202 | u8 amd_iommu_pc_get_max_counters(unsigned int idx);
       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:347:11: error: conflicting types for ‘amd_iommu_pc_get_max_banks’
   347 | extern u8 amd_iommu_pc_get_max_banks(u16 devid);
       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:31:
 ./include/linux/amd-iommu.h:201:4: note: previous declaration of ‘amd_iommu_pc_get_max_banks’ was here
   201 | u8 amd_iommu_pc_get_max_banks(unsigned int idx);
       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:348:11: error: conflicting types for ‘amd_iommu_pc_get_max_counters’
   348 | extern u8 amd_iommu_pc_get_max_counters(u16 devid);
       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 In file included from /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.c:31:
 ./include/linux/amd-iommu.h:202:4: note: previous declaration of ‘amd_iommu_pc_get_max_counters’ was here
   202 | u8 amd_iommu_pc_get_max_counters(unsigned int idx);
       |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/amdgpu/5.11.32-1350682/build/amd/amdgpu/../amdkfd/kfd_iommu.o] Error 1
```

looks like it's triggered by a compliation error.

**Comment by ptd006** [comment]
Same issue on a freshly upgrade'd (to 5.13.0-27) Ubuntu 20.04.3.

**Comment by bpickrel** [comment]
A couple of other bits of info:  Ubuntu version 20 changed kernel versions from 11 to 13 this past August, which may have been the genesis of this error; but whichever kernel is still designated Ubuntu version 20.04.3; 

I was finally able to install (not build) ROCm by using the contents of the Docker file at [RadeonOpenCompute](https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/dev/Dockerfile-ubuntu-20.04-complete) as a guide.  Most of the commands need to have "sudo" prefixed in order to run them from the command line.

**Comment by jrbyrnes** [comment]
I ran into this issue on a fresh upgrade to (5.13.0-27) on Ubuntu release
as well. To resolve, I rolled back the kernel to 5.11 with the HWE tools.

Rollback, download (linux-headers-5.11.0-46-generic,
linux-image-5.11.0-46-generic, linux-modules-5.11.0-46-generic,
linux-modules-extra-5.11.0-46-generic, linux-tools-5.11.0-46-generic,
linux-hwe-5.11-tools-common) from here
<https://packages.ubuntu.com/source/focal-updates/linux-hwe-5.11>. Install
with sudo dpkg -i *.deb.

Purge 5.13

sudo apt-get autopurge 'linux-image-5.13.0-*-generic' \
'linux-image-unsigned-5.13.0-*-generic' 'linux-modules-5.13.0-*-generic' \
'linux-hwe-5.13-headers-5.13.0-*' linux-generic-hwe-20.04

After this, I was able to install ROCm using amdgpu-install and run. Also,
I was able to build from source.

**Comment by Weaverzhu** [comment]
My workaround is to uninstall kernel 5.13 and I found it work in 5.11.

**Comment by wertysas** [comment]
I also had to downgrade to the 5.11 kernel which solved the problem.

**Comment by ROCmSupport** [comment]
Hi @bpickrel and all,
Thanks for reaching out.

We are aware of the issue and team is coming up with a fix/workaround. We have an internal issue already filed for this.
As Ubuntu recently pushed 5.13 kernel, and as ROCm is not built/validated on 5.13.0-27, this problem happened. 
Meanwhile I request everyone to roll back to 5.11 kernel which is an approved kernel by ROCm.
I will keep you posted. 
Thank you.

**Comment by ROCmSupport** [comment]
Good news is that, 5.0 internal builds are ready with fix/workaround incorporated. I have verified too and things are working good.
Please stay tuned for 5.0 builds(will be released very soon) having the resolution for this issue.
Thank you.

**Comment by ptd006** [comment]
Great news, thanks for the update :)

I am only a lazy amateur running a rig that I update-upgrade-vacuum every 6 weeks or so.  I know occasionally all magic breaks but it'd really be great to keep up with LTS updates in future :)

**Comment by ptd006** [comment]
Thanks, now working fine with 5.13.0-28

**Comment by ROCmSupport** [comment]
Thanks for the confirmation.
I am closing this thread as the fix is validated. Thank you.
