### ISSUE TITLE
Unable to open /dev/kfd read-write: Cannot allocate memory

### ISSUE THREAD

**Issue by JBBIntel** [RadeonOpenCompute/ROCm#1663]
I have installed rocm on Ubuntu 20.04. I tried rocminfo, and got

amdgpu:~/amd$ sudo /opt/rocm-4.5.2/bin/rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Cannot allocate memory
jbberry is member of render group

Additional info;
jbberry@ortce-amdgpu:~/amd$ dkms status
amdgpu, 5.11.32-1350682, 5.4.0-97-generic, x86_64: installed

jbberry@ortce-amdgpu:~/amd$ uname -r
5.4.0-97-generic

**Comment by JBBIntel** [comment]
Works for clinfo, but 0 devices;
jbberry@ortce-amdgpu:~/amd$ sudo /opt/rocm-4.5.2/opencl/bin/clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.2 AMD-APP (3361.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               0
jbberry@ortce-amdgpu:~/amd$

**Comment by srinivamd** [comment]
> I have installed rocm on Ubuntu 20.04. I tried rocminfo, and got
> 
> amdgpu:~/amd$ sudo /opt/rocm-4.5.2/bin/rocminfo ROCk module is loaded Unable to open /dev/kfd read-write: Cannot allocate memory jbberry is member of render group
> 
> Additional info; jbberry@ortce-amdgpu:~/amd$ dkms status amdgpu, 5.11.32-1350682, 5.4.0-97-generic, x86_64: installed
> 
> jbberry@ortce-amdgpu:~/amd$ uname -r 5.4.0-97-generic

The booted kernel is 5.4.0-97 but the amdgpu dkms is installed on 5.11.32 kernel. It means, you have booted up kernel without amdgpu dkms installed.

**Comment by JBBIntel** [comment]
Thanks for the quick response! But I'm not sure I understand. Are you saying I need to re-install rocm, so it will select the amdgpu for the correct kernel? Or use a different version of Ubuntu? Or what?

**Comment by ROCmSupport** [comment]
Thanks @JBBIntel for reaching out.
I certainly understood the problem.
I recommend to try with at least 5.8/5.9 kernels and above versions.
5.4 is very old kernel and it might not work due to compatibility issues. We have not tested too. So recommend to try with the latest kernels like 5.11 and etc(atleast 5.8/5.9 are minimum requirement).

Meanwhile can you please share the below information.
1. output of dmesg command
2. GPU details of your machine.
Thank you.

**Comment by JBBIntel** [comment]
There are no kdf messages in dmesg. The GPU is an MI100.
I am a bit puzzled by your suggestion. I initially tried to install this on Ubuntu 21.10, which uses the 5.13 kernel. However, that installation failed. I noticed that the install page says the supported Ubuntu versions are 18.04 and 20.04.  I therefore backed off to Ubuntu 20.04, which uses the 5.4 kernel. Are you suggesting I should return to 21.04? Or somehow get a different version of 20.04, with a higher kernel version?

**Comment by JBBIntel** [comment]
FYI, I figured out what you meant. I was able to upgrade the kernel in Ubuntu 20.04 using the instructions here;
https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Server

In particular, since my machine is a server, I did this;

 sudo apt install --install-recommends linux-generic-hwe-20.04 

and then rebooted. After that, install worked fine.
