### ISSUE TITLE
Official AMDVBFlash tool for Linux

### ISSUE THREAD

**Issue by Umio-Yasuno** [RadeonOpenCompute/ROCm#1671]
The AMDVBFlash tool is mentioned as a known issues in ROCm v5.0, but currently it is not officially released for Linux.

https://github.com/RadeonOpenCompute/ROCm/tree/roc-5.0.x#incorrect-dgpu-behavior-when-using-amdvbflash-tool

Do you have any plans to officially release the AMDVBFlash for Linux in the future?

**Comment by ROCmSupport** [comment]
Hi @Umio-Yasuno 
Thanks for reaching out.
I will check with product team and keep you posted. Thank you.

**Comment by Umio-Yasuno** [comment]
Still VBIOS flashing on Linux requires binary tools distributed on Github.  

https://github.com/stylesuxx/amdvbflash
https://github.com/Strunzdesign/amdvbflash
