### ISSUE TITLE
ROCm 5.0 bare metal with 6800xt/6900xt

### ISSUE THREAD

**Issue by aoolmay** [RadeonOpenCompute/ROCm#1672]
Hello,
My workstations still run 4.5.2 within docker compute environment, which is a compromise from bare metal, which i couldn't get to work at the time. I'm tight on time for experimenting and hesitating to run 5.0 just yet without community confirmation.
How's the ROCm 5.0 bare metal experience with 6800xt/6900xt now? Any hick ups?
Regards

**Comment by aoolmay** [comment]
I've just spotted fresh tensorflow-rocm package, version 2.8.0, in pip. Works on bare metal with 6800xt, installed the driver with "rocm,hip,opencl" and simple pip install tensorflow-rocm. I've yet to test 6900xt, should be a breeze.
Just an update before closing issue.

**Comment by aoolmay** [comment]
@ROCmSupport Thank you for clarification, if it wasn't for 4.5 i'd jump off MAD ship. Trajectory of 5.0 just gave me peace of mind.

You explicitly mention 6800XT, should i expect 6900XT to work? I'm fine with it running just OpenCL, but a clear pointer would save me time on experimenting.

Also with understanding and acknowledging of unofficial support status, will 6850XT/6950XT be similar enough to 6800XT/6900XT to be viable upgrades for next purchases in terms or ROCm use?

**Comment by ROCmSupport** [comment]
Hi @aoolmay 
I can not comment on future plans. Request to keep track of our documentation.
Thank you.

**Comment by ffleader1** [comment]
> I've just spotted fresh tensorflow-rocm package, version 2.8.0, in pip. Works on bare metal with 6800xt, installed the driver with "rocm,hip,opencl" and simple pip install tensorflow-rocm. I've yet to test 6900xt, should be a breeze. Just an update before closing issue.

Hey can you shred light on the Rx 6800. Afaik it is Navi 21 also, so it should be simple too. I just want a quick confirmation before purchasing. Thank you.

**Comment by aoolmay** [comment]
ROCm 5.0.2 + tensorflow-rocm works well with 6800XTs and lately 6900XT as well if that's your focus. OpenCL works great. I gave up on experimenting with out of spec software setups, so just do everything as per manual.

Hybrid, but off the shelf water+air cooled cards run days on ridiculous overclocks, which nets +25% performance on some workloads. Mind you i have my workstations in separate room that's air conditioned to 16 degrees Celsius 24/7. Might want to pay a little extra and get one with the highest boost ceiling, if time to completion means money to you it'll pay off in spades.

Poor performance on small parallel workloads though. GPU time doesn't get divided equally, so there's some uncertainty there to work around.

**Comment by SturtKoh** [comment]
I've tested ROCM5.1.3 with 6900XT, 6950XT, Radeon PRO W6800 cards.
6950XT is better than 6900XT.
Installation was so simple!

**Comment by aoolmay** [comment]
@SturtKoh Did you have the opportunity to test multi task capability of W6800?

From my testing 6800XT and 6900XT can't handle any two or more tasks efficiently. Compute resources are divided extremely unevenly and this leads to unpredictability. Navi cards ( both gaming and workstation versions ) didn't have problems with running multiple tasks at all, i'd run 20 models on WX7100 without problems. I'm wondering if W6800 would solve my multi tasking problem.
