### ISSUE TITLE
ROCm 5.0 indicates not supported for rx6800 XT GPU on Ubuntu 20.04

### ISSUE THREAD

**Issue by jasondrusso** [RadeonOpenCompute/ROCm#1676]
Installed ROCm 5.0 along with Radeon 21.50 drivers and getting error 'hipErrorNoBinaryForGpu: Unable to find code object for all current devices' when testing with Tensorflow.

Steps:

1. Removed all older gpu drivers and ROCm 4.5 from system & restarted.
2. Download installer script for AMD 21.50 drivers and ROCm 5.0 tools per guide: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html
3. Ran amdgpu-install --usecase=graphics,rocm,hip
4. Installed rccl library: apt-get rccl
5. Added user to 'video' & 'render' groups
6. Set LD_LIBRARY_PATH=/opt/rocm/lib/:/opt/rocm/rocblas/lib/:/opt/rocm/rccl/lib/:/opt/rocm/hsa/lib/:/opt/rocm/hip/lib/:/opt/rocm/miopen/lib/:/opt/rocm/hipfft/lib/:/opt/rocm/rocrand/lib/

In python console, run:

1. import tensorflow as tf
2. sess = tf.compat.v1.Session()

Result:

2022-02-13 14:06:45.471445: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libamdhip64.so
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

See for reference:
https://github.com/RadeonOpenCompute/ROCm/issues/1617

I'm testing this on an older project using python 3.7 and Tensorflow 1.15.

See for reference: https://github.com/RadeonOpenCompute/ROCm/issues/1617

**Comment by Djip007** [comment]
Did you use one of this releases; https://pypi.org/project/tensorflow-rocm/#history
There is no tensorflow 1.15 release after May,2021... so no release that can work with rocm 5.0
I don't think other release that 2.7.1 or 2.8.0 can work this day with last rocm.

**Comment by jasondrusso** [comment]
Thanks for the update. I tested this new version of tensorflow-rocm and that seems to work. Very exciting!

**Comment by ROCmSupport** [comment]
Thanks @jasondrusso for reaching out.
TF1.15 is very old and it does not support with Navi21 cards. Navi21+the latest TF 2.7/2.8 works. Request to test the same.
Thank you.

**Comment by jasondrusso** [comment]
Yes, I can verify that it works with Tensorflow as early as 2.3, using tensorflow-rocm 2.8 package.
