### ISSUE TITLE
how to build rocm from source file

### ISSUE THREAD

**Issue by wangzy0327** [RadeonOpenCompute/ROCm#1678]
how to build rocm from source file

**Comment by xuhuisheng** [comment]
Here is my building scripts:
<https://github.com/xuhuisheng/rocm-build>

**Comment by wangzy0327** [comment]
> Here is my building scripts: https://github.com/xuhuisheng/rocm-build

OK,Thx,I will try it.

**Comment by ROCmSupport** [comment]
Hi @wangzy0327 
Thanks for reaching out. We are working on this request already, request to track #1188.
Meanwhile you can try as per above comments also. Thank you.
