### ISSUE TITLE
ROCm 1.6 can run width Juno arm r1 & r2 developemnt board and AMD R9 FURY X card?

### ISSUE THREAD

**Issue by zhaojunfan** [RadeonOpenCompute/ROCm#168]

**Comment by zhaojunfan** [comment]
I get the information the ROCm 1.6 support arm, I want to know if I have Juno ARM R1 & R2 development board and AMD R9 FURY C card, then I can  run opengl demos?

**Comment by gstoner** [comment]
We do not have Juno board, the base driver today supports ARM AArch64 and a kernel driver support can be built up to the ROCr driver API.   We still working on User Land Language runtimes.
