### ISSUE TITLE
How can I compile Pytorch from source and make it run with ROCm 5.0?

### ISSUE THREAD

**Issue by EduMio** [RadeonOpenCompute/ROCm#1681]
Good morning everyone, I am trying to build pytorch from source and make it run with my ROCm 5.0, but I cant seem to find a guide anywhere. I am using Ubuntu 20.04 with kernel 5.11 and a 6900xt. I installed the ROCm with the amdgpu-install script with the usecase=rocm. What I should do from here?

**Comment by Rmalavally** [comment]
Thank you for reaching out. Please refer to our Deep Learning Guide v5.0 at the following website for documentation on building PyTorch from the source:

https://docs.amd.com/bundle/AMD-Deep-Learning-Guide-v5.0/page/Introduction_to_Machine_Learning_and_Deep_Learning.html

Let us know of any questions or missing information. 

ROCm Documentation Team

**Comment by Nixola** [comment]
Hi, the linked page doesn't exist anymore.

**Comment by Rmalavally** [comment]
@Nixola Our apologies for the inconvenience. 

Please test the link below and let us know if you cannot access the Deep Learning Guide for ROCm v5.0. 

https://docs.amd.com/bundle/ROCm-Deep-Learning-Guide-v5.0/page/Introduction_to_Deep_Learning_Guide.html

**Comment by wojtess** [comment]
This is same link - it dosent work
![image](https://github.com/user-attachments/assets/039a441c-e632-478c-a157-2a05cca579fe)
