### ISSUE TITLE
Feature request: list all supported AMD video cards.

### ISSUE THREAD

**Issue by procedural** [RadeonOpenCompute/ROCm#1683]
When I buy any recent NVIDIA video card, I know it supports CUDA.

When I see people open issues here saying their AMD video card can't initialize ROCm stack, the usual response from AMD employees is "we don't support that video card".

I can find mentions of *some* supported AMD video cards in some obscure AMD PDFs on the Internet, but

would've been nice to just have a list of all AMD video cards that are currently supported.

Thanks.

**Comment by Umio-Yasuno** [comment]
I agree.  
In my opinion, it would be helpful to indicate the support status in some groups: *the software tools (e.g. for debug), the OpenCL/HIP runtime, the HPC libraries, the machine learning libraries*, etc.  
This prevents the issue from focusing on one ROCm repository.
It also makes it easier to provide appropriate support and report problems.

**Comment by nlnjnj** [comment]
I agree too.

I only find a list from here:
https://docs.amd.com/bundle/ROCm_Installation_Guidev5.0/page/Prerequisite_Actions.html

But for RDNA GPUs, do 6800xt and 6900xt support by this release?

**Comment by SolitaryDragon** [comment]
I agree, almost every Nvidia GPU available on the market today supports CUDA without looking at the support list.  But when I wanted to buy a new laptop (with AMD CPU and GPU) I was surprised to find that the latest RX 6000M or 6000S series GPUs do not support ROCm technology. I also see why people on the web are talking about older AMD GPUs. It's incomprehensible that the latest GPUs can't use ROCm.

**Comment by sampie** [comment]
I agree. I think it has been clearly stated that ROCM will come with RDNA2 support (https://github.com/RadeonOpenCompute/ROCm/issues/1180). It was also said to happen already in 2021. 6000 series GPUs are RDNA2 right?

**Comment by procedural** [comment]
Please stay on topic of this issue, this issue is about an official *list* of *all* supported AMD video cards and feature levels, as was suggested by @Umio-Yasuno, not about some particular video cards you want to know about. Open another issue if you want to know which ones or if all RDNA2 video cards are supported, though this issue is not about that. Thanks! 🙂

**Comment by FCLC** [comment]
I've been attempting to create something analogous to this in #1617 

It's doesnt currently include pre-RDNA cards, but I'd gladly welcome contributions from others to track

A: What cards are supported in the latest version
B: What was the last version of ROCm to support a given card
C: What card has no support in any version whatsoever

**Comment by ROCmSupport** [comment]
Hi @procedural 
Thanks for reaching out.
You are looking for the information of listing each and every card that supports ROCm?
Our docs have this information right? This needs to be matured or do you wish to see the list in a different way?
Please share your thoughts.

**Comment by procedural** [comment]
> You are looking for the information of listing each and every card that supports ROCm?

Yes, a list of all AMD cards AMD officially supports for latest versions of ROCm. Such a list can be updated if support for some AMD cards or ROCm versions is dropped.

> Our docs have this information right? This needs to be matured or do you wish to see the list in a different way?

This repository doesn't have a direct link to such a list, @nlnjnj found one, but it already conflicts with the links from https://docs.amd.com for ROCm v5.0 and ROCm v5.0.1 which point to https://docs.amd.com/bundle/AMD_ROCm_Release_Notes_v4.5/page/Hardware_and_Software_Support.html that doesn't state that RDNA cards are supported, even though https://docs.amd.com/bundle/ROCm_Installation_Guidev5.0/page/Prerequisite_Actions.html states they are.

This is all confusing. Just have a single list of currently supported AMD video cards and link it to this repository's readme. Thanks.

**Comment by kingcrimsontianyu** [comment]
Team green has set a great example: https://developer.nvidia.com/cuda-gpus

**Comment by ROCmSupport** [comment]
> > You are looking for the information of listing each and every card that supports ROCm?
> 
> Yes, a list of all AMD cards AMD officially supports for latest versions of ROCm. Such a list can be updated if support for some AMD cards or ROCm versions is dropped.
> 
> > Our docs have this information right? This needs to be matured or do you wish to see the list in a different way?
> 
> This repository doesn't have a direct link to such a list, @nlnjnj found one, but it already conflicts with the links from https://docs.amd.com for ROCm v5.0 and ROCm v5.0.1 which point to https://docs.amd.com/bundle/AMD_ROCm_Release_Notes_v4.5/page/Hardware_and_Software_Support.html that doesn't state that RDNA cards are supported, even though https://docs.amd.com/bundle/ROCm_Installation_Guidev5.0/page/Prerequisite_Actions.html states they are.
> 
> This is all confusing. Just have a single list of currently supported AMD video cards and link it to this repository's readme. Thanks.

Hi @procedural 
I have updated the same to our documentation team, request to wait for sometime.
Thank you.

**Comment by Rmalavally** [comment]
Thank you for reaching out, @procedural. This issue is fixed. Could you please access https://docs.amd.com, and click the link in the Support Documentation box. 

As always, we look forward to your feedback for improvement.

Sincerely,
AMD ROCm Documentation Team

**Comment by procedural** [comment]
So the new link is
https://docs.amd.com/bundle/Hardware_and_Software_Reference_Guide/page/Hardware_and_Software_Support.html
, correct?

**Comment by Rmalavally** [comment]
That is correct.

**Comment by procedural** [comment]
Thanks, the issue can be closed then.

It would also be nice to add the link to this repository's readme directly, to track it if it will change in future.
