### ISSUE TITLE
Rename rocm-> rocm-amdgpu-pro in README.md

### ISSUE THREAD

**Issue by jh2li** [RadeonOpenCompute/ROCm#169]
There is no package named rocm anymore. Please update README.md.
sudo apt-get install rocm rocm-opencl-dev
To
sudo apt-get install rocm-amdgpu-pro rocm-amdgpu-pro-opencl-dev

**Comment by gstoner** [comment]
This is not CORRECT,   ROCm is the correct driver package to install from ROCm repo at the instructions 

ROCm driver is driver for the server market.   The AMDGPUpro recently added rocm functionality for only OpenCL support based on there packages.  The current ROCm packages are at https://rocm.github.io/ROCmLinuxpackages.html  should be run on the ROCm driver using these instructions  https://rocm.github.io/ROCmInstall.html
