### ISSUE TITLE
Plans for Arch Linux ?

### ISSUE THREAD

**Issue by EduMio** [RadeonOpenCompute/ROCm#1691]
There are any development plans for official support for the Arch Linux distribution? Right now there is a [package](https://github.com/rocm-arch/rocm-arch) in the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) for installing, but is not the same as the official support and requires building from source.

**Comment by sofiageo** [comment]
@EduMio 

I'm not sure if you know but until an official support is available, there is also package [opencl-amd](https://aur.archlinux.org/packages/opencl-amd) for OpenCL / HIP Runtimes and [opencl-amd-dev](https://aur.archlinux.org/packages/opencl-amd-dev) for ROCm SDK which is based on the Ubuntu releases. It's not exactly the same and it's unofficial.

**Comment by EduMio** [comment]
Well that is interesting indeed. Does it work with the 6900xt, pytorch and tensorflow? I just need the stack for machine leaning framework.

**Comment by EduMio** [comment]
I see, I am going to try that in some near future, thank you

**Comment by ROCmSupport** [comment]
Hi @EduMio 
Thanks for reaching out.
ROCm does not support ArchLinux officially and no current plans as of now.
Request to keep track of our documentation for the updates in future.
Thank you.
