### ISSUE TITLE
Odd glitch on Ubuntu

### ISSUE THREAD

**Issue by DillFrescott** [RadeonOpenCompute/ROCm#1692]
I am experiencing a very odd glitch. So far I've tested this with focal, xenial, and also jammy, where it happens on all 3 fresh installs.

When I try to run any program that takes advantage of rocm 4.3, the program just gets stuck.

I've left it overnight to see if it would resume but it did not.

But the most odd thing about it is that for some reason my gpu, (RX Vega 56) becomes extra "sensitive" I wanna say...

For example, while the program is stuck, just moving or clicking the mouse shoots the gpu usage to 100%, and as soon as I pkill python it doesn't do it anymore.

I've been tinkering with this for days and I have no idea why it's doing this.

Any help at all would be appreciated.

**Comment by ROCmSupport** [comment]
Hi @DillFrescott 
Thanks for reaching out.
Can you please share the exact steps you followed so that I will try to replicate here.
Thank you.

**Comment by DillFrescott** [comment]
Ok let me think.

I installed a fresh copy of Ubuntu 20.

It comes with python already installed. I installed rocm pytorch 4.3 using pip.

I try to run any program that takes advantage of the gpu, and the cursor just gets stuck, and the GPU Tachometer on the side just kind of flashes.

The GPU itself is fine, I use it to play games on Windows all the time at max settings.

For some odd reason it doesnt want to cooperate with rocm...

I dont think im doing anything out of the ordinary to cause issues.

**Comment by DillFrescott** [comment]
@ROCmSupport Is there an easy way to install an even newer version of rocm pytorch? One newer than 4.3?

**Comment by ROCmSupport** [comment]
Hi @DillFrescott 
Thanks for more data points. 
I am not able to reproduce your issue locally. I recommend to share dmesg output for more udnerstanding.
And also I suggest you to install the latest ROCm 5.0 + the latest pytorch docker: _rocm/pytorch:latest_
Thank you.

**Comment by DillFrescott** [comment]
Okay

**Comment by DillFrescott** [comment]
@ROCmSupport I would like to install rocm 5 + pytorch in a conda environment. Is that possible without using docker? If so, is there a way to do it that doesn't involve building things from scratch?

**Comment by DillFrescott** [comment]
@ROCmSupport Gotcha. Thank you for the info!

**Comment by DillFrescott** [comment]
@ROCmSupport Can the rocm docker be run on a windows host?

**Comment by ROCmSupport** [comment]
Hi @DillFrescott 

ROCm dockers(not only rocm, any linux dockers) can not be running on Windows host.
Containers are using the underlying operating system resources and drivers, so Windows containers can run on Windows only, and Linux containers can run on Linux only.

_But there is some other way like below, if you wish to:_
Docker for Windows allows you to simulate running Linux containers on Windows, but under the hood a Linux VM is created, so still Linux containers are running on Linux, and Windows containers are running on Windows.

Hope this information helps.
Thank you.

Bonus: Read [this very nice article](https://engineering.docker.com/2019/06/docker-hearts-wsl-2/) about running Linux docker containers on Windows.

**Comment by DillFrescott** [comment]
Oh cool! Thank you for the response! <3

**Comment by ROCmSupport** [comment]
Hi @DillFrescott 
I hope I have shared all of the requested information. Feel free to file a new issues, if any, for quick resolutions.
Thank you.
