### ISSUE TITLE
kernel with debug symbols?

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/ROCm#17]
Hi, I wanted to some performance analysis on my machine that comes with the ROCm kernel. For systemtap and perf, kernel side debug symbols would be nice. Are you guys considereing to ship a `kernel-devel` package as well?

**Comment by arodrigx7** [comment]
Hey Peter,

This is something we've discussed, and we'll eventually get around to it. But it isn't a high priority at the moment.

If debug symbols are required, the source is available for users to build in any configuration desired.

**Comment by psteinb** [comment]
very good, then I know that it's on the agenda.
