### ISSUE TITLE
Describe what ROCm is in the README.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [RadeonOpenCompute/ROCm#170]
The current REAME is a wall-of-text, and (sorry to say!) it looks a lot like some content-less advertisement.

Content-less stuff in the README:
- "Optimized" - everything is optimized
- "Ultra-scale"  - marketing speak - what does it mean exactly?  Do you mean distributed, or just that AMD hardware is fast?  Use common terminology.
- "Using our knowledge of the HSA Standards" - what are the HSA standards?
- "Open Heterogeneous Computing Platform" - is this an AMD technology?  What is it?

https://rocm.github.io/ is much better.  Maybe the README should just link to that web page.

**Comment by gstoner** [comment]
Thank I built ROCm.github.io.  I want to replace the readme with this https://rocm.github.io/ROCmInstall.html
