### ISSUE TITLE
Feature request: list all supported AMD video cards.

### ISSUE THREAD

**Issue by NeilduToit13** [RadeonOpenCompute/ROCm#1700]
Per this recent issue: https://github.com/RadeonOpenCompute/ROCm/issues/1683

It "would've been nice to just have a list of all AMD video cards that are currently supported."
This issue was closed after the following link was posted: https://docs.amd.com/bundle/Hardware_and_Software_Reference_Guide/page/Hardware_and_Software_Support.html

I do not understand why this resulted in the issue being closed given that the provided link does not include a _list of all supported AMD video cards_. What is provides is a short list of categories of video cards with one or maybe two examples of each. I don't know what a "Polaris 12" is, and a Google search doesn't reveal a list of "Polaris 12" chips either.

I've spend three days now going through the confusing tangle of documentation on supported hardware and I'm still coming up short. I am going to be buying a new PC tomorrow, I am going to be using it for GPU programming, and I would love to support the open source ROCm instead of Nvidea's proprietary software. But I'm finding it literally impossible to find a card I can buy that I know will support ROCm. Is ROCm intended to be used by consumers at all? Or is this just a data warehouse technology?

**Comment by ROCmSupport** [comment]
Hi @NeilduToit13 
Thanks for reaching out.
What I understood is you are looking for each supported card name with 2 examples(with marketing names).
Let me talk to our documentation team on this.
Thank you.

**Comment by Rmalavally** [comment]
Hi @NeilduToit13 Please refer to our release notes document for each release. The latest ROCm release v5.0.2 has a list of supported GPUs as of this release. 

Let us know if you cannot find the information you need, and we will work with the BU to provide more details.

AMD ROCm Documentation Team

**Comment by ye-luo** [comment]
> The latest ROCm release v5.0.2 has a list of supported GPUs as of this release.

@Rmalavally Prove it. Provide a link if you think it is in the v5.0.2 documentation. 

I didn't have the luck to find such info in the v5.0.2 doc. Instead, v5.0.0 doc does carry a list of GPUs.
Look at https://docs.amd.com/bundle/ROCm_Release_Notes_v5.0/page/About_This_Document.html
![Screenshot from 2022-03-07 16-56-29](https://user-images.githubusercontent.com/1454251/157132382-b6b50935-7273-4a12-8de5-13b7e22682ef.png)
There is no mention of Vega 10.

Look at this
https://docs.amd.com/bundle/Hardware_and_Software_Reference_Guide/page/Hardware_and_Software_Support.html
![Screenshot from 2022-03-07 16-56-57](https://user-images.githubusercontent.com/1454251/157132287-d3e98b16-6e96-45b0-9644-192c518a6160.png)
shown updated today. Still list Vega 10.

Clean this up!

**Comment by Rmalavally** [comment]
@ye-luo Thank you for your note. I meant the ROCm Installation Guide v5.0.2. My mistake. 

https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.0.2/page/Prerequisite_Actions.html

ROCm v5.0.2 is a point/patch release, so the Release Notes document consists of specific fixed defects or known issues. If a release has an accompanying Installation Guide, we recommend you refer to this document for details on supported GPUs and other installation-related details.

As always, you can reach out to the ROCm Documentation team if you need more information.

AMD Documentation Team

**Comment by ROCmSupport** [comment]
I hope @ye-luo is looking for all list of supported cards(with marketing names) for every Asic family.
@Rmalavally can you please check whether its possible to share this information in our docs.

**Comment by NeilduToit13** [comment]
Based on the last link shared, it does look like I'm in the wrong place. None of those cards appear to be consumer-grade cards. So I guess you can close the issue.
