### ISSUE TITLE
Are Vega10 cards no longer operational with 5.0+?

### ISSUE THREAD

**Issue by wreckdump** [RadeonOpenCompute/ROCm#1702]
I am confused about the EOL for Vega10 cards. Does this mean that Vega10 cards are no longer usable, as in no longer are detected by the ROCm driver stack and the runtime components, under ROCm 5.0+? Or is it just that there won't be any updates yet they are still usable (running HIP and OpenCL codes)? Could you please clarify this? Thanks.

**Comment by ramin-raeisi** [comment]
I am a fan of this question as I have a RX Vega 56(Vega 10) and wonder if it is supported or not, however I have segmentation faults with ROCm v4.5.2 and can not run any sample

**Comment by perestoronin** [comment]
Please provide full cases to test, I have Vega Frontier cards, and can approve on decline issue with Vega's on rocm 5.0.2 in linux environment.

**Comment by ramin-raeisi** [comment]
@perestoronin Could you please tell me which GPU are you exactly using successfully with ROCm 5.0.2? And also please tell me about the kernel version you have installed dkms driver into

**Comment by perestoronin** [comment]
`Linux 5.16.15`
```
GPU[0]          : Card series:          Vega 10 XTX [Radeon Vega Frontier Edition]
GPU[0]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]          : Card SKU:             D05011
```

**Comment by perestoronin** [comment]
I use successful rocm from version old 2.0 (Vega 56) in past to 5.0.2 now with, but now I have only Vega Frontier cards, and plan migrate to Vega 20 and Instinct cards and sell Vega Frontier cards after obtain new cards.

**Comment by wreckdump** [comment]
@perestoronin So, with Vega Frontier you can run your HIP or OpenCL code under ROCm version 5.0.2?

**Comment by perestoronin** [comment]
> @perestoronin So, with Vega Frontier you can run your HIP or OpenCL code under ROCm version 5.0.2?

yes, self-compiled ethminer and hashcat works with rocm

**Comment by wreckdump** [comment]
> > @perestoronin So, with Vega Frontier you can run your HIP or OpenCL code under ROCm version 5.0.2?
> 
> yes, self-compiled ethminer and hashcat works with rocm

Version 5.0.2, yes?

**Comment by perestoronin** [comment]
> > > @perestoronin So, with Vega Frontier you can run your HIP or OpenCL code under ROCm version 5.0.2?
> > 
> > 
> > yes, self-compiled ethminer and hashcat works with rocm
> 
> Version 5.0.2, yes?

yes, except rocm-smi from rocm-smi-libs, for Vega card I use old rocm-smi 4.0.0 with libs from 5.0.2  rocm-smi-lib, other packages (all self compiled) from rocm 5.0.2 sources.

**Comment by wreckdump** [comment]
> > > > @perestoronin So, with Vega Frontier you can run your HIP or OpenCL code under ROCm version 5.0.2?
> > > 
> > > 
> > > yes, self-compiled ethminer and hashcat works with rocm
> > 
> > 
> > Version 5.0.2, yes?
> 
> yes, except rocm-smi from rocm-smi-libs, for Vega card I use old rocm-smi 4.0.0 with libs from 5.0.2 rocm-smi-lib, other packages (all self compiled) from rocm 5.0.2 sources.

Thank you for the clarification!

**Comment by ramin-raeisi** [comment]
I have a Radeon RX Vega 56(Vega 10) and can confirm it is working properly in the 5th version. I am using HIP.

**Comment by rajhlinux** [comment]
What about V320 Cards, any support for these or which ROCm use to support it?
