### ISSUE TITLE
The Link in ROCM Tuning guide is crash right now

### ISSUE THREAD

**Issue by chichunchen** [RadeonOpenCompute/ROCm#1710]
https://github.com/RadeonOpenCompute/ROCm/blob/master/AMD%20Instinct%E2%84%A2High%20Performance%20Computing%20and%20Tuning%20Guide.pdf is now broke and I found this this from https://rocmdocs.amd.com/en/latest/Tuning_Documentation/Tuning_Guide.html#.

**Comment by Rmalavally** [comment]
@chichunchen Thank you for reaching out. The ROCm documentation portal has moved to https://docs.amd.com. The link to the Tuning Guide is 
https://docs.amd.com/bundle/AMD-Instinct-MI100-High-Performance-Computing-and-Tuning-Guide/page/Overview.html

The new portal enables you to access release and category-specific ROCm content. As always, we look forward to your feedback. 

AMD ROCm Documentation Team

**Comment by chichunchen** [comment]
Thanks for your prompt reply! I can find what I need now.
