### ISSUE TITLE
Repository does not have a Release file 

### ISSUE THREAD

**Issue by Bengt** [RadeonOpenCompute/ROCm#1736]
Since today, I get the following error:

```
$ sudo apt update
[...]
Ign:9 http://repo.radeon.com/rocm/apt/debian xenial InRelease
Err:10 http://repo.radeon.com/rocm/apt/debian xenial Release
  404  Not Found [IP: 13.82.220.49 80]
Reading package lists... Done
E: The repository 'http://repo.radeon.com/rocm/apt/debian xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Bengt** [comment]
Switching to HTTPS does not work.

**Comment by Bengt** [comment]
I had to deactivate the AMD repository to make my other updates work.

**Comment by Bengt** [comment]
This issue causes security vulnerabilities of running outdated and potentially dangerous software versions of other packages.

**Comment by xuhuisheng** [comment]
try this:
`deb [arh=amd64] https://repo.radeon.com/rocm/apt/debian ubuntu release`

**Comment by Bengt** [comment]
Thanks for the idea, however, your line is slightly incorrect. For me, this worked:

    echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian ubuntu main' | \
        sudo tee /etc/apt/sources.list.d/rocm.list

I also had to add the new public key to my keyring:

    wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -

**Comment by Bengt** [comment]
Thanks for helping me, @xuhuisheng. This resolves the issue for me. I will therefore close it.

**Comment by tvandraren** [comment]
> Thanks for the idea, however, your line is slightly incorrect. For me, this worked:
> 
> ```
> echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian ubuntu main' | \
>     sudo tee /etc/apt/sources.list.d/rocm.list
> ```
> 
> I also had to add the new public key to my keyring:
> 
> ```
> wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
> ```

thanks for your response. I have no idea what I'm doing here and this helped.

**Comment by skipdashu** [comment]
ditto on not knowing what I'm doing but replacing "ubuntu" with "focal" on the "echo" line seems to have resolved it for me.

**Comment by srohit0** [comment]
The command didn't work on Ubuntu 18.04.5 LTS

`wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -`
-k or -r can be used together with -O only if outputting to a regular file.
gpg: no valid OpenPGP data found.
