### ISSUE TITLE
if ROCm source code can be cross compiled?

### ISSUE THREAD

**Issue by zhaojunfan** [RadeonOpenCompute/ROCm#174]
I want to know if the rocm source code can be cross compiled?  On x86_64 platform, I want to compile arm target?

**Comment by gstoner** [comment]
We have he the ability for HCC to be standalone compiler which can build built as cross compiler if you put ARM code generator int the platform.

Greg
On Aug 1, 2017, at 1:14 AM, zhaojunfan <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to know if the rocm source code can be cross compiled? On x86_64 platform, I want to compile arm target?
