### ISSUE TITLE
UBUNTU 20.04, ROCM 5 rocminfo fails after install for regular user and sudo

### ISSUE THREAD

**Issue by mwibral** [RadeonOpenCompute/ROCm#1741]
I installed ROCm 5 as per:

https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#rocm-installation-guide-v5-0
I added my user to the video and render groups.
After installation rocminfo fails, both for the regular user as well as when using sudo:

$/opt/rocm/bin/rocminfo 
ROCk module is loaded
hsa api call failure at: /long_pathname_so_that_rpms_can_package_the_debug_info/src/rocminfo/rocminfo.cc:1140
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

clinfo also does not find a device:
~$clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3423.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback 

  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               0

However, rocm-smi finds both GPUs:
~$/opt/rocm/bin/rocm-smi

 
```
 ======================= ROCm System Management Interface =======================
 ================================= Concise Info =================================
 GPU  Temp   AvgPwr   SCLK     MCLK     Fan     Perf  PwrCap  VRAM%  GPU%  
 0    33.0c  3.0W     852Mhz   167Mhz   15.69%  auto  170.0W    0%   0%    
 1    55.0c  18.132W  1219Mhz  1500Mhz  20.0%   auto  25.0W    64%   0%    
 ================================================================================
 ============================= End of ROCm SMI Log ==============================

```
Devices in the machine are:
~$lspci | grep VGA
19:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon PRO WX 9100]
65:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lexa XT [Radeon PRO WX 2100]

Both models should be supported. Any idea what to check next?

**Comment by aoolmay** [comment]
I have the same issue, can't run wx5100/wx7100 cards in the same system with 6800/6900xt cards, same symptoms.
I have enough workstations to segregate and run those older cards with older ROCm, but it's definitely an undisclosed limitation.

**Comment by mwibral** [comment]
Hi all,
these two cards ran together without problems using Ubuntu 18.04 and some older ROCm (some 3.X version). I could compute with both of them, and they are still both in the list of supported devices, aren't they? Since when did this change?

**Comment by mwibral** [comment]
Since there is not much development here, let me revive the thread my a question:
Is it conceivable that I get problems if there are multiple users on the system and one of them is running an X-server (on the WX2100)?

**Comment by mwibral** [comment]
> I have the same issue, can't run wx5100/wx7100 cards in the same system with 6800/6900xt cards, same symptoms. I have enough workstations to segregate and run those older cards with older ROCm, but it's definitely an undisclosed limitation.

So, the WX2100 (Lexa XT) will not run anymore in ROCM 5? Is this documented somewhere?

**Comment by mwibral** [comment]
@aoolmay  Thanks a lot. That would explain why in the old installation those two cards worked together well. I will try if removing the Lexa card solves the issue. If so, I will close the issue and open a new one asking for release specific compatibility lists.

**Comment by aoolmay** [comment]
@mwibral Comprehensive compatibility lists are a hard ask. You can just switch version branches and find for yourself, like so : https://github.com/RadeonOpenCompute/ROCm/tree/roc-3.3.0#Hardware-and-Software-Support
WX cards seem to have "supported, but not guaranteed" status, WX2100 is not explicitly mentioned, but if you see WX4100/wx5100 your WX2100 has a good chance.

**Comment by mwibral** [comment]
Thanks, I see.
