### ISSUE TITLE
Can anybody confirm ROCm works with Radeon 6950XT?

### ISSUE THREAD

**Issue by aoolmay** [RadeonOpenCompute/ROCm#1749]
I'm expecting it to work, just looking for confirmation.
Regards

**Comment by xfyucg** [comment]
It is a gfx1030 GPU, should be officially supported like Radeon Pro V620 and Radeon 6800 Workstation.
https://docs.amd.com/bundle/Hardware_and_Software_Reference_Guide/page/Hardware_and_Software_Support.html
