### ISSUE TITLE
1 Petaflop !

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#175]
http://wccftech.com/amd-manages-to-pack-a-1-petaflop-super-computer-in-a-rack-with-project-47/

**Comment by gstoner** [comment]
yep..  it was fun to work on

**Comment by nevion** [comment]
@gstoner any slides detailing system architecture and device/network topology?  Does the mellanox card have localized access to GPU memory?  Curious to see how you guys are trying to answer nvlink besides more pcie lines.

**Comment by gstoner** [comment]
NVLINK  is great for P2P but HOST I/O performance you are blocked by the PLX switch.    4 GPU into 1 x16 is not idea state.    Also EPYC supports 256b packet on PCIe for P2P..  You have 128 lanes of PCIe exposed on an EPYC.    Rember you need to talk across PCIe to work with Mellonox NIC today.

**Comment by nevion** [comment]
Certainly, I'm looking at it in terms of P2P capabilities as well as host IO capabilities.  By system architecture, I mean something like ![this](https://www.microway.com/wp-content/uploads/NumberSmasher_1U_Tesla_GPU_Server_with_NVLink_Block_Diagram.png)

Is it an 8-GPU system with a mellanox card in there? If so, Is there a single root complex in this system's architecture to multiplex host/device IO to the mellanox or something else? A diagram like that would be the best answer though.

**Comment by psteinb** [comment]
30 GFlops/Watt?! is that number correct? What an achievement if so.

that would double the efficiency of the the top1 in the 
[green500.org](https://www.top500.org/green500/lists/2017/06/).

**Comment by oscarbg** [comment]
"Also EPYC supports 256b packet on PCIe for P2P.."
so threadripper will also?

**Comment by gstoner** [comment]
Yep….

Greg
On Aug 2, 2017, at 12:15 PM, Oscar Barenys <notifications@github.com<mailto:notifications@github.com>> wrote:


"Also EPYC supports 256b packet on PCIe for P2P.."
so threadripper will also?
