### ISSUE TITLE
What is limit on the maximum number of VGPR (vector registers) for one work-item in MI100?

### ISSUE THREAD

**Issue by vasslavich** [RadeonOpenCompute/ROCm#1784]
Hello, does anyone know if there is some kind of limit on the maximum number of VGPR for a single work-item in MI100?
Thanks!

**Comment by b-sumner** [comment]
The ISA can't encode more than 256.  And since there is a physical limit, the number a wave/warp can get depends on the size of the work-group.  For example, with a work group size of 1024, you can have at most 64 registers per work-item.

**Comment by vasslavich** [comment]
@b-sumner , thank you very much!
