### ISSUE TITLE
What is the functionality of si58_mc.bin

### ISSUE THREAD

**Issue by FalconBsp** [RadeonOpenCompute/ROCm#179]
With Git hub pre-build OCL bins , Luxmark  works with out si58_mc.bin from /lib/amdgpu/firmware.

I tried to build libOenCL.so and libamdocl64.so  from  open source.  But Luxmark failed to run and gave IOMMU fault. When i copy si58_mc.bin to amdgpu firmware and ran initramfs , Luxmark runs without any issue.

Can you explain how this firmware bin fixing the issue?

**Comment by gstoner** [comment]
What GPU are you using?...  This firmware should only be loaded for GFX6 hardware.

**Comment by gstoner** [comment]
This firmware is only used for Tahiti, Pitcarin, Cape Verde, Oland, and Hainan It should never be used with ROCm. since these device are not supported by ROCm

**Comment by rdemaria** [comment]
Will ROCm ever support Tahiti hardware, like the AMD 280X?

**Comment by simonlui** [comment]
+1 to GFX6 hardware support. Is there any technical hardware limitations for Southern Islands support, considering it is under amdgpu Linux driver but in limited support right now? I suppose we'll have to see more upstreaming before that happens, right?
