### ISSUE TITLE
hsa-rocr depends on missing hsakmt-roct package

### ISSUE THREAD

**Issue by JoniSt** [RadeonOpenCompute/ROCm#1802]
Hi,

The `hsa-rocr` DEB package that ships in the 5.2.3 apt repository lists `hsakmt-roct` as one of its dependencies; however, the latter package doesn't exist in the 5.2.3 repo. (The last repo that contains it is 4.3.1)

This seems a little broken to me. Is the dependency list of `hsa-rocr` wrong, maybe?

Thanks,
Jonathan

**Comment by saadrahim** [comment]
@frepaul will be able to comment on this issue.

**Comment by frepaul** [comment]
@JoniSt . We are take care of this in our next release. 

Thanks for reporting.

**Comment by frepaul** [comment]
Wanted to clarify one more detail here. Since we were transitioning hsakmt-roct to hsakmt-roct-dev, currently hsakmt-roct-dev provides both and hence installation of hsa-rocr should not have any issues.

**Comment by JoniSt** [comment]
Oh, I just checked again and you're right, that is indeed the case! I'm not sure why exactly APT insists on installing the missing hsakmt-roct package on my system... When I install hsakmt-roct-dev manually before the rest of the packages, it works just fine.

Thank you very much!

I'll leave it up to you if you want to close this issue immediately or after the next release.

**Comment by kentrussell** [comment]
Closing as fixed
