### ISSUE TITLE
Future of ROCm - desktop support?

### ISSUE THREAD

**Issue by gsedej** [RadeonOpenCompute/ROCm#181]
Hello,

the intended use of ROCm is trough SSH to powerful multi GPU machine (server). This makes ROCm desktop users a "second-tier". Breaking desktop usage of ROCm, would mean, one would need to develop ROCm-accelerated software on server trough SSH, which is not ideal (e.g. no root access, inability to install additional developer tools, not able/hard to use graphical IDE, etc... )

Will ROCm continue supporting all desktop features (display, 3d accel, video accel, ...) in the future?

**Comment by gstoner** [comment]
ROCm started as server focused product, but we will support X11/OpenGL/EGL in the base driver.   We use this for development as well.

**Comment by gsedej** [comment]
Thank you for reply and enabling ROCm desktop usage!
