### ISSUE TITLE
hip version of nvCOMP

### ISSUE THREAD

**Issue by Moading** [RadeonOpenCompute/ROCm#1824]
Hi,
is there a hip version of nvCOMP?
[https://developer.nvidia.com/nvcomp](https://developer.nvidia.com/nvcomp)
Greetings!

**Comment by saadrahim** [comment]
There is no hip version of nvCOMP.

**Comment by Moading** [comment]
OK, I should improve my question: Are there any plans to create a hip equivalent to cuCOMP?
There are hip equivalents of other libraries:
cuRAND -> hipRAND
cuSOLVER -> rocSOLVER
cuSPARSE -> rocSPARSE
cuBLAS -> rocBLAS

**Comment by saadrahim** [comment]
There is no update I can provide on nvCOMP. You may assume there is no port imminent. If there was one, a github repository would be publicly available.
