### ISSUE TITLE
Any suggestion for Install ROCm on aarch64,Ubuntu ?

### ISSUE THREAD

**Issue by aoxipo** [RadeonOpenCompute/ROCm#1831]
hello , I want to install ROCm. but I can't find anything about how to install on the aarch64 architecture.
here is my os and gpu infor.
![%VS$A6V)60F72K{F7H 65{8](https://user-images.githubusercontent.com/32930325/195297710-286b7f90-4991-4b23-a078-28d47159d6d7.png)

**Comment by saadrahim** [comment]
ROCm does not support ARM. I am not aware of any path you can take to enable ROCM on aarch64.
