### ISSUE TITLE
ARM AArch64: kernel can't be boot

### ISSUE THREAD

**Issue by lintcoder** [RadeonOpenCompute/ROCm#184]
I have been trying to build ROCK-Kernel-Driver on my ubunu16.04-arm64 server, here are my steps:
1. make defconfig
2. make
3. sudo make modules_install
4. sudo make install

On the 4th step, there is some message like 'W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.' , 
and when I restart the operating system and select the new kernel, it gets stuck,  and the system can't be started. Output of the terminal is as follows:

Loading Linux 4.9.0 ...
Loading initial ramdisk ...
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...

please tell me how can I fix it? @gstoner

**Comment by gstoner** [comment]
The current most driver is using Kernel 4.11.   

Greg

**Comment by lintcoder** [comment]
I use Kernel 4.11 on branch roc-1.6.1 instead, while it still doesn't work, output of the terminal is as follows:
Loading Linux 4.11.0 ...
Loading initial ramdisk ...
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
@gstoner

**Comment by gstoner** [comment]
What CPU are you using ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lintcoder** [comment]
I am building it on my qemu virtual machine

**Comment by gstoner** [comment]
The PCIe Atomics are not passing through the qemu virtual machine

**Comment by Uditkr** [comment]
Did you manage to get fix for this

**Comment by ericdraken** [comment]
Yes, any success?
