### ISSUE TITLE
Images from the ROCm Installation Guide v5.3 should be readable

### ISSUE THREAD

**Issue by keryell** [RadeonOpenCompute/ROCm#1847]
I have tried to read the manual to install ROCm on my Ubuntu 22.04 machine but unfortunately the images from https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.3 are unreadable with a resolution which is too low to have the text readable on them.
There is the same on the PDF which can be generated by that web site.

**Comment by Rmalavally** [comment]
@keryell Thank you for your feedback. We are aware of this issue and hope to have it resolved soon. 

ROCm Documentation Team

**Comment by samjwu** [comment]
ROCm Documentation has migrated to https://rocm.docs.amd.com/

Installation guides for 

5.3.0: https://rocm.docs.amd.com/en/docs-5.3.0/deploy/linux/installer/install.html
5.3.2: https://rocm.docs.amd.com/en/docs-5.3.2/deploy/linux/installer/install.html
5.3.3: https://rocm.docs.amd.com/en/docs-5.3.3/deploy/linux/installer/install.html
