### ISSUE TITLE
Rocm support for Radeon RX 7000 Series (7900XT and 7900XTX)

### ISSUE THREAD

**Issue by SharoonSaxena** [RadeonOpenCompute/ROCm#1874]
I am done building a Deep learning build except for GPU. I have same thoughts on Nvidia GPUs as Linus Torvalds a decade ago.

I wish to know if ROCm will support the upcoming Radeon RX 7900XTX, or when it is expected to be supported, if at all.

**Comment by aoolmay** [comment]
Urgently need ETA on RDNA3 inclusion too!

**Comment by powderluv** [comment]
While you wait for an official ROCM release, if you have specific workloads like stable diffusion it is worth trying http://shark.sd that uses the AMD vulkan path and is available on both linux and windows and supports 100s of models (https://github.com/nod-ai/SHARK/tree/main/tank) . Also in the past I have been able to build / test ROCM on newer hardware  from the public sources.

**Comment by aoolmay** [comment]
I know about some half measures, i bought my first RDNA2 card anticipating support, i waited more than half a year gimping around on PlaidML, OpenCL implementation of Keras , eventually ended up on 4 RDNA2 workstations.

Can't afford to wait this time around, got commercial work cut out for next months and i already have to rent RTXs from the cloud. At this point it's whatever gets the job done faster.

**Comment by SharoonSaxena** [comment]
Well, I am not buying a $1000 GPU for gaming, strictly for Science purposes. I guess half-measures are not going to cut it.
