### ISSUE TITLE
ROCm 1.6 with AMDGPU-PRO?

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#188]
Hello AMD folk. Thanks for the ROCm 1.6 release, it looks great!

I'm running this system:
-------------------------
Ryzen R7 1700
RX Vega 64
X370 board (Asus Crosshair Hero VI)
Installed Ubuntu 16.04.3 server with defaults.
Bumped the kernel up to 4.12.9 from http://kernel.ubuntu.com/~kernel-ppa/mainline.
Installed ROCm 1.6 from AMD repos.
Boot into ROCm kernel 4.11.0-kfd-compute-rocm-rel-1.6-148.
Installed ubuntu-desktop metapackage
Reboot into X running atop  ROCm kernel 4.11.0-kfd-compute-rocm-rel-1.6-148.

Results:
--------
I can compile and run C++AMP style code via hcc, which is what I really want it to do. 
System loads/runs Ubuntu's GUI using the Ubuntu default AMD driver.
So, this is good.

Modules loaded:

> lsmod | grep radeon
> lsmod | grep amd
edac_mce_amd           28672  0
amdkfd                212992  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               2523136  2
ttm                    94208  1 amdgpu
drm_kms_helper        143360  1 amdgpu
drm                   344064  5 amdgpu,ttm,drm_kms_helper
i2c_algo_bit           16384  2 igb,amdgpu
gpio_amdpt             16384  0
gpio_generic           16384  1 gpio_amdpt

Problem:
----------
I've downloaded, un-tarred, and tried installing amdgpu-pro-17.30-465504.tar.xz, but the module build step fails complaining kernel version unsupported. This is both for the ROCm kernel and for Ubuntu's 4.12.9 kernel.

Questions:
-----------
1) Can I get amdgpu-pro-17.30-465504 running on this system alongside amdkfd from ROCm1.6?

2) amdgpu-pro-17.30-465504.tar.xz says it can install ROCm 1.5, however afaik ROCm 1.5 does not support RX Vega 64?

3) What kernel will AMDGPU-PRO run on? All the instructions  I can google essentially say: use Ubuntu 16.04, then "download, untar, install, add self to video group, reboot". This is fairly information-free. If AMDGPU-PRO only runs on Ubuntu 16.04 kernel version 4.4 then this is not much use for a Ryzen box.

4) A bit off topic: in Windows 7 & latest driver as of yesterday, the AMD control panel does not show me an HBCC enable/disable option. Any idea about that?

Any help or advice much appreciated!

**Comment by AirSquirrels** [comment]
As far as I am aware, amdgpu-pro is a completely seperate set of drivers and compilers and is not meant to work alongside ROCm. ROCm should be a replacement for amdgpu-pro

**Comment by gstoner** [comment]
Airquirrels is correct the Base ROCm driver is separate from the AMDGPUpro project.  With Vega10 we did bring ROCm capability in base Driver,  remember they operate at much slower release cadence.  That Code base was  ROCm 1.5 based and only supported OpenCL in the first version.    We have been working with the team to bring broader capabilities to that driver.    

One thing we have RHEL/Centos 7.3 support now running on ROCm, and now working SUSE support to broaden our distro support for the ROCm Server Computing driver.

**Comment by gstoner** [comment]
Just as FYI, One thing we saw recently on  Ubuntu 16.04.3 you need to manually install the firmware after you loaded the kernel on one customer. 

On HBCC, i have no idea,   I only use POSIX based OS these days.

**Comment by gstoner** [comment]
We have been working with core Linux driver team to bring DKMS support to ROCm so you can use standard Linux kernel.  But more importantly now we hit capability and quality milesstones, we are working on getting all our updated base driver components upstream so we just use standard AMDGPU driver and layer our userland on it.  We should have the core in by 4.15 or 4.16    We really want ROCm distributed as a core capability in a Linux Distro just like AMDGPU driver.    

Here we need your help to get focal with Ubuntu and ask them to support ROCm.    We are working hard to bring Commercial Class GPU Computing to market via open source.

**Comment by boxerab** [comment]
Awesome! How can we help with this ?

**Comment by emerth** [comment]
@gstoner @AirSquirrels Thanks very much for explaining. I was confused about the relation between amdgpu and ROCm.

**Comment by gstoner** [comment]
There are two pure  Opensource drivers 
- AMDGPU  which base Linux kernel + X11/MesaGL Graphics Stack 
- ROCm which is focused on enterprise server computing, it leverages the AMDGPU driver as it's base driver,  we also support MesaGL in headless and with a head configs ( with X11).   There are number of server computing features in ROCM like LargeBAR support for P2P and P2P RDMA to NIC via Infiniband and ROCE Ethernet cards. Plus lot more. 

RIght now ROCm is more capable then AMDGPUpro for Compute. 

The closed source Linux drivers 
- AMDGPUpro  use the same  Userland,  OpenGL, and OpenCL as the Windows driver on GFX8 and older GPU's called ORCA.  For Vega10 OpenGL is same user-land - ORCA,  Vulkan is new user-land as windows call PAL.    It has also been optimized for Workstation applications as well.

**Comment by toxicbytes** [comment]
i just edited the install file amdgpu-pro-install to force install as ubuntu. I am using Elementary OS based on Ubuntu 16.04 .
