### ISSUE TITLE
hipcc.bin not present after rocm/5.4.x installation

### ISSUE THREAD

**Issue by xinye83** [RadeonOpenCompute/ROCm#1885]
I tried to install rocm/5.4.0 and rocm/5.4.1 in a SLES 15 SP4 docker container with the following command and `hipcc.bin` is not present
```
amdgpu-install -y --usecase=rocm,hiplibsdk --no-dkms
```

The release note says they are available thought:
https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4/page/Deprecations_and_Warnings.html
https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4.1/page/Deprecations_and_Warnings.html

Please update the documentation to reflect the desired bahaviour.

**Comment by Rmalavally** [comment]
Thank you for the feedback. The release notes documents for ROCm v5.4 and ROCm v5.4.1 have the following text:

HIP Deprecation
The hipcc and hipconfig Perl scripts are deprecated. The compiled binaries are now available as hipcc.bin and hipconfig.bin.

NOTE:

There is no functional difference between the Perl scripts and their compiled binary counterpart. No user action is required. Users can switch to hipcc.bin and hipconfig.bin. The hipcc/hipconfig soft link will be assimilated to point from hipcc/hipconfig to the respective compiled binaries as the default option.

https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4/page/Deprecations_and_Warnings.html

https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4.1/page/Deprecations_and_Warnings.html

Please let us know if you need additional information. 

ROCm Documentation Team

**Comment by Rmalavally** [comment]
@xinye83 

Our Development team has indicated that this issue will be fixed in a future release. We have updated our documentation with more details at,

https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4/page/Deprecations_and_Warnings.html
https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4.1/page/Deprecations_and_Warnings.html

Thank you for your feedback.
ROCm Documentation Team

**Comment by xinye83** [comment]
Thanks for the updates!
