### ISSUE TITLE
MSI 970A- G46 (AMD) Motherboard - ROCm - Question on Why PCIe Gen2 x1 lanes to not work -Work Around Found

### ISSUE THREAD

**Issue by Angel996** [RadeonOpenCompute/ROCm#192]
Hello.

I am trying to use ROCm platform with amdgpu-pro-17.30.465504 drivers on my mining rig with 4 AMD GPUs (RX 470/480/570, mixed), motherboard MSI 970A- G46 (AMD), as remedy for lowered hashrate when mining with ETHash algorithm (the DAG issue). 

ROCm does seem to solve this issue (by adding `amdgpu.vm_fragment_size=9` to grub), however, my rig does not boot with 4 GPUs as usual, it only boots with 3 GPUs. I tried moving GPUs around the slots, it seems the problem is not the GPU count, but a certain PCIE 1x slot that causes ROCm to fail, but I'm not sure about this. After removing the 4th GPU the system gets all unstable and I have to reboot it several times (also using nomodeset option) to get it back to working state. If I choose previous kernel (4.4.0-62-generic) in grub menu, motherboard boots fine with 4 GPUs and works as intended.

The error msg I see in boot log with ROCm kernel and 4 GPUs looks something like this:

`AMD-Vi: Completion-Wait loop timed out` (lots of these messages)
`AMD-Vi: Event logged [IOTLB_INV_TIMEOUT] device=06:00.0 address=0x00000000798e0840` (these messages repeating for a while, then motherboard hangs dead exactly at this msg)

PCIE device #6 is actually the 4th GPU I am trying to add to that 1x slot.

Tried both BIOS and UEFI mode. All GPUs have vbios modded. I have 3 rigs with identical motherboards, and they all have this same issue. Tried moving GPUs around, same problem.

**Comment by AirSquirrels** [comment]
Is the 1x slot perhaps PCIe 2.0? ROCm requires PCIe 3.0 due to the use of PCIe atomics

**Comment by gstoner** [comment]
It depends on the system



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Angel996** [comment]
AirSquirrels, there are two 16x and two 1x slots. Only one 1x solt is causing problems.

**Comment by gstoner** [comment]
Ok is this an AMD® FX, Phenom II system? 
 
Is it this motherboard? 

https://www.msi.com/Motherboard/970A-G46.html#hero-specification
CPU • 64bit AMD® FX, Phenom II X6/X4/X3/X2, Athlon II X4/X3/X2 and Sempron CPU in AM3 / AM3+ package.Please refer to CPU Support for compatible CPU; the above description is for reference only.Hyper Transport Bus
--

If so one issue I am not PCIe Gen3 slot on the motherboard 
• 2 PCI Express 2.0 x16 slots 
• 2 PCI Express 2.0 x1 slots
• 2 PCI slots, support 3.3V/ 5V PCI bus Interface.

Currently, for multi-gpu testing, we use Xeon E5, Intel core i7 Extreme Editions, AMD EPYC and Threadripper processor.    We have 4 and 8 GPU system we load at standard config for testing.

**Comment by gstoner** [comment]
One thing the configs i sent out for ROCm driver for Polaris will not work with amdgpu-pro-17.30.465504 this is using a different the historical OpenCL driver Foundation.  The same foundation we had on old Catalyst Linux drivers.  Compiler + Userland System Runtime ( ORCA).    Also, the ROCm packages will not work on this driver since they did not enable the correct capabilities in the base driver for GFX 8 based devices.  



ROCm system runtime needs a CPU that supports PCIe atomics to operate user-mode queues properly.

**Comment by Angel996** [comment]
It's not really the issue of not working at all. It's just that 4th GPU is not working. When I boot the motherboard with 3 GPUs, the slots are still PCIE 2.0 and CPU is still AMD AM3. How come it all works with 3 GPUs and adding 4th GPU messes it up? There must be a fix for this.

**Comment by Angel996** [comment]
FOUND A FIX!

adding `amd_iommu=on iommu=pt` to GRUB_CMDLINE_LINUX seems to fix the problem. I was able to boot with 4 GPUs fine, no any of the mentioned err messages appeared.

**Comment by gstoner** [comment]
What processor are you ussing?

**Comment by Angel996** [comment]
CPU is Athlon II X2 245.

**Comment by gstoner** [comment]
@Angel996  Your running ROCm 1.6.3 from our repo?

**Comment by Angel996** [comment]
I got it from `http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key`

**Comment by fxkamd** [comment]
Please don't install amdgpu-pro and ROCm at the same time. Depending on the order in which you install them, you may get very different results. ROCm installs a complete kernel. amdgpu-pro compiles just the kernel module on the target machine against the running kernel with DKMS.

Parts of ROCm are included in amdgpu-pro, but only supported on Vega10.

Looks like you're trying to run ROCm on Polaris10 GPUs. So just don't install amdgpu-pro.

To see what's going on on your system, I'd need to see a complete kernel log and the output from lspci -vv as root.

**Comment by Angel996** [comment]
I had Ubuntu general kernel installed. Then I installed amdGpu. Then I installed ROCm kernel. I did not reinstall amdgpu AFTER installing ROCm kernel.

I have an update. I had to shut down my rigs today. So, after a few hours I turned them on, and I had the same error again. One rig started ok, the other two started spurting out `AMD-Vi: Completion-Wait loop timed out` messages again and hanging on boot. All I could do is try to reboot them several times, so finally, I got them to boot normally, also using booting with `nomodeset` flag and rebooting afterwards.

So, I guess the complete fix is not found yet.

**Comment by fxkamd** [comment]
DKMS may try to compile the amdgpu-pro kernel module against the ROCm kernel. Your configuration is complicated and unusual enough as it is (with multiple mismatched GPUs). Let's not make it worse by adding unnecessary variables.

Still waiting to see kernel logs and lspci -vv. Without that I can't give you any more help.

**Comment by Angel996** [comment]
I'm sorry, I seem to have overlooked the request for logs. Attached them now. Thanks for your help.

[logs.zip](https://github.com/RadeonOpenCompute/ROCm/files/1279081/logs.zip)

**Comment by fxkamd** [comment]
Your main board doesn't support PCIe atomics, and the KFD initialization is failing. That means, whatever you're testing isn't actually using ROCm. You're probably just using the older non-ROCm OpenCL from the amdgpu-pro driver. As it is, your system can't support ROCm. You'll need a mainboard with PCIe v3 support. The relevant log messages are below:

[    9.331640] kfd kfd: skipped device 1002:67df, PCI rejects atomics
[    9.331845] [drm] Initialized amdgpu 3.18.0 20150101 for 0000:01:00.0 on minor 0
...
[   10.940075] kfd kfd: skipped device 1002:67df, PCI rejects atomics
[   10.941977] [drm] Initialized amdgpu 3.18.0 20150101 for 0000:02:00.0 on minor 1
...
[   12.572303] kfd kfd: skipped device 1002:67df, PCI rejects atomics
[   12.574191] [drm] Initialized amdgpu 3.18.0 20150101 for 0000:04:00.0 on minor 2
...
[   14.268456] kfd kfd: skipped device 1002:67df, PCI rejects atomics
[   14.270339] [drm] Initialized amdgpu 3.18.0 20150101 for 0000:07:00.0 on minor 3
...

**Comment by Angel996** [comment]
Ok, but `amdgpu.vm_fragment_size=9` fixed the low hashrate problem with mining. If I remove it, hashrate drops about 20%. Does that mean, it's being done simply by amdgpu itself and it has no relation to ROCm?

**Comment by fxkamd** [comment]
Yes, the fragment size is an amdgpu parameter. It affects all clients running on amdgpu, including OpenGL and the amdgpu-pro OpenCL. I'm not sure if the fragment size fix is already included in the latest amdgpu-pro release.

**Comment by fxkamd** [comment]
DKMS rebuilds the amdgpu kernel module for every new kernel you install. So after you install ROCm it will compile amdgpu from the amdgpu-Pro driver and replace the one from the ROCm kernel.
