### ISSUE TITLE
Migrate content from release notes on docs.amd.com to GitHub

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#1924]
Note: this is a development task.

In order to ensure the accuracy of this GitHub repository, release notes from docs.amd.com for all ROCm releases 5.0 to 5.4 to the file https://github.com/RadeonOpenCompute/ROCm/blob/develop/CHANGELOG.md.

A few specific instructions for the migration. Content for the math libraries should be copied from GitHub repositories via scripts. A prewritten script will be provided upon request by email.

OS and GPU support information should not be copied into the CHANGELOG.

**Comment by Naraenda** [comment]
@saadrahim Few questions:
- This should be a pure GFM file right?
- Should the math libraries changes be grouped per library or per ROCm release?
- Do we want a neater, more interactive version (foldouts, reference links) with Myst for use in the webview? I can generate this easily with how the script is setup.

We can discuss during the meeting.

**Comment by saadrahim** [comment]
> @saadrahim Few questions:
> 
> * This should be a pure GFM file right?
Yes, must be pure GFM
> * Should the math libraries changes be grouped per library or per ROCm release?
Everything should be grouped per ROCm release.
> * Do we want a neater, more interactive version (foldouts, reference links) with Myst for use in the webview? I can generate this easily with how the script is setup.
use valid GFM html and other GitHub recommended techniques.
> 
> We can discuss during the meeting.

**Comment by Naraenda** [comment]
@saadrahim 

- Is it possible to get the source-text of the release notes on docs.amd.com? Maybe it's already in Markdown. That would make everything a lot easier for me.

- There is a lot of duplication in the deprecation notes between the releases on docs.amd.com. Should we group these by major/minor releases? Or keep them on a per-patch basis (there will be _a lot_ of text)?

**Release Notes:** (Proposed)
- ROCm 5.4.x
  - HIPCC Deprecation
  - Patch Notes
    - ROCm 5.4.3
    - ROCm 5.4.2
    - ROCm 5.4.1
    - ROCm 5.4.0
 - ROCm 5.3.x
   - HIPCC Deprecation
   - Patch Notes
     - ROCm 5.3.3
     - ROCm 5.3.2
     - ...

**Release Notes:** (Current)
- ROCm 5.4.3
  - HIPCC Deprecation
- ROCm 5.4.2
  - HIPCC Deprecation
- ROCm 5.4.1
  - HIPCC Deprecation
- ROCm 5.4.0
  - HIPCC Deprecation
- ROCm 5.3.3
  - HIPCC Deprecation
- ...

I think having things grouped by major/minor version first allows people to get the most important things first and the patch specific changes can be read without going through all the boilerplate of all the shared items.

**Comment by Rmalavally** [comment]
I am happy to provide the release notes' source files, which are not in Markdown. 

The replication of deprecation content is intended; they are, sometimes, a reminder/warning to our users for upcoming and actual deprecations in a release.

**Comment by Naraenda** [comment]
@Rmalavally 
> I am happy to provide the release notes' source files, which are not in Markdown.

Awesome, feel free to contact me via email: `nara <at> streamhpc <dot> com`

> The replication of deprecation content is intended; they are, sometimes, a reminder/warning to our users for upcoming and actual deprecations in a release.

That makes sense. Will keep the same ordering then.

**Comment by Rmalavally** [comment]
Can you access Sharepoint or Confluence yet?

**Comment by Naraenda** [comment]
Not yet, but no ETA yet so it could take a while. I'll probably just convert everything manually then.

**Comment by Rmalavally** [comment]
Please let me know when you have access, and I can share the source files with you.
