### ISSUE TITLE
Math Libraries Landing pages

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#1925]
Based on the content at https://github.com/RadeonOpenCompute/ROCm/blob/develop/docs/reference/gpu_libraries/blas.md

Please complete landing pages for all files in https://github.com/RadeonOpenCompute/ROCm/tree/develop/docs/reference/gpu_libraries

**Comment by MathiasMagnus** [comment]
@saadrahim I believe we can close this. All library types have landing pages.
