### ISSUE TITLE
Rocm kernel etherten not working on ASUS am1m-a mobo

### ISSUE THREAD

**Issue by kusayuzayushko** [RadeonOpenCompute/ROCm#193]
For some reason, with default Ubuntu kernel it's ok, but when i boot with 4.11.0-kfd-compute-rocm kernel, lan not working.
This is 2 kernels diff http://paste.ubuntu.com/25449195/
Any ideas how i can fix it?

**Comment by gstoner** [comment]
THis APU processor is not supported by the base Linux Driver used by the ROCm software stack.   it not fixable since it is missing core HW capabilities needed.

**Comment by kusayuzayushko** [comment]
Could you please give an advice what can i do to make ROCm work with my mobo? I'm not familiar with Linux kernel stuff, but i really want to try... something. Maybe it is possible to find one of Ubuntu patches (because on Ubuntu lan is working ok) or build ROCm with default Ubuntu kernel?
Thank you.
