### ISSUE TITLE
Latest ROCm Release

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#194]
It would be helpful to post on this issue whenever there is a new release (minor or major), for those of us who want to stay on the bleeding edge of ROCm :)

**Comment by gstoner** [comment]
We are looking at 1.6.4 release,  in the next three weeks.    We looking at 2.0 release in the Fall but we can not talk about the features yet

**Comment by boxerab** [comment]
Great, thanks.

**Comment by rhlug** [comment]
Status update on 1.6.4?
