### ISSUE TITLE
Enable a linter for rst files

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#1947]

**Comment by aaronmondal** [comment]
Nix can be pretty helpful in such cases. For instance we use markdownlint [here](https://github.com/eomii/rules_ll/blob/main/pre-commit-hooks.nix#L83-L89) and use a github action that reuses the installation by caching [here](https://github.com/eomii/rules_ll/blob/main/.github/workflows/pre-commit.yml). All pre-commit hooks together are ~700 megabytes, or ~7% of the free cache limit per Github repo (i.e. its free :laughing:). Without caching these hooks take ~2 min to run. With caching this becomes ~45 seconds.
