### ISSUE TITLE
Formatting for some tables looks odd

### ISSUE THREAD

**Issue by arghdos** [RadeonOpenCompute/ROCm#1955]
![image](https://user-images.githubusercontent.com/6463881/225644616-3d6ac409-5e5a-46c6-9a7a-11f45069ea59.png)

Was discussing with @AlexVlx

Mainly this seems to result from putting the table header in a single column (so you get fixed width + wrap).  Not clear what the best solution is here, perhaps splitting it to be e.g., "Table 1" in the top row (to keep it from wrapping / looking out of place), and put a 'caption' below in some other format?

**Comment by Naraenda** [comment]
I propose using [list tables](https://myst-parser.readthedocs.io/en/latest/syntax/tables.html#list-tables). It will be more readable in source which will make authoring and reviewing easier. I will create a PR that implements this.

**Comment by AlexVlx** [comment]
> I propose using [captions with directives](https://myst-parser.readthedocs.io/en/latest/syntax/tables.html#table-with-captions) with [list tables](https://myst-parser.readthedocs.io/en/latest/syntax/tables.html#list-tables). It will be more readable in source which will make authoring and reviewing easier. I will create a PR that implements this.

It's debatable if it's more readable as now you have a list that only gains special meaning due to meta-information, whereas e.g. a pipe table is unambiguously, visually, a table. .md source should still be readable. Also, GH doesn't render that since it's not part of GFM, AFAIR.
