### ISSUE TITLE
Empty section headers

### ISSUE THREAD

**Issue by arghdos** [RadeonOpenCompute/ROCm#1958]
![image](https://user-images.githubusercontent.com/6463881/225649315-0fb9fa53-b308-4a93-a865-c7dd60741627.png)
![image](https://user-images.githubusercontent.com/6463881/225649355-ba3fe0e3-c909-4672-9816-c4d92a7aa381.png)

Some section headers in the sidebar do not own any content themselves.  These should probably have a bit of content, even just a sentence or two introducing the topic (or link to the first sub-header).  Release notes also functions like this right now, but I imagine that's a short-term issue.

@saadrahim

**Comment by saadrahim** [comment]
This is already planned. We will reference this when fixing the empty headers.

**Comment by samjwu** [comment]
#2073
#2073
#2073

**Comment by samjwu** [comment]
Empty pages removed in https://github.com/RadeonOpenCompute/ROCm/pull/2078

Will be added back later:
#2073
#2074 
#2075 
#2076 
#2077
