### ISSUE TITLE
ROCm 1.6-148: Vega FE power usage relativly high after Ubuntu 16.04 boot

### ISSUE THREAD

**Issue by csuji** [RadeonOpenCompute/ROCm#196]
I noticed via a wattmeter that after booting into X server and  i3 window manager my PC power usage is about 95 watt. GPU temperature is about 70-80 degrees Celsius. After executing clinfo (nothing else) power usage drops to ~ 70 watt and temperature to  ~ 50C.
Is it possible to monitor what the GPU is doing? It seems that current radeontop  does not work (only shows 0%).

**Comment by gstoner** [comment]
in \opt\rocm\bin you find ROCm-SMI you can see your temp and power level.  When we run headless 

This is on MI25 card,  
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  3   6860   24.0c    7.0W     852Mhz   167Mhz   0.0%     auto      0%       N/A      
  1   6860   23.0c    4.0W     852Mhz   167Mhz   0.0%     auto      0%       N/A      
  4   6860   26.0c    5.0W     852Mhz   167Mhz   0.0%     auto      0%       N/A      
  2   6860   25.0c    4.0W     852Mhz   167Mhz   0.0%     auto      0%       N/A      
GPU[0] 		: PowerPlay not enabled - Cannot get supported clocks
GPU[0] 		: PowerPlay not enabled - Cannot get supported clocks
  0   2000   N/A      N/A      N/A      N/A      None%              N/A      N/A      
================================================================================
====================           End of ROCm SMI Log          ====================

**Comment by csuji** [comment]
Ok, thank you! Tried this today after switching my computer on. While temperature was around 50 from the start, power consumption is about 20W and after I execute clinfo drops to 4W.
Could it be that the card is not fully initialized by the driver after booting?

====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   6863   53.0c    **20.0W**    852Mhz   945Mhz   13.73%   auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
chris@beastieboys:~$ clinfo
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (2450.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx900
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 
  Driver Version                                  1.1 (HSA,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
..........

====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   6863   52.0c    **4.0W**     852Mhz   945Mhz   13.73%   auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================

**Comment by gstoner** [comment]
Can you check the Airflow in your system, looks like you need more CFM across the chip.

**Comment by csuji** [comment]
Increased the front chassis fan to full speed from silent mode (which sits a little bit below the horizontal Vega card) and managed to get temps down to a minimum of 45C. Looking at
http://www.tomshardware.com/reviews/amd-radeon-vega-frontier-edition-16gb,5128-11.html
45C seems near the minimum of Vega FE in idle mode? 
Problem with higher power consumption after boot remains:
```====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   6863   51.0c    27.0W    852Mhz   945Mhz   20.0%    auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
chris@beastieboys:~$ clinfo > /dev/null 2>&1
chris@beastieboys:~$ sudo /opt/rocm/bin/rocm-smi 
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   6863   47.0c    7.0W     852Mhz   945Mhz   13.73%   auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
```

**Comment by csuji** [comment]
I noticed that compared to your MI25 cards my MCLK does not go down to 167Mhz but stays at 945Mhz. Could that be a reason for the higher temp?

**Comment by csuji** [comment]
When doing hipCaffe cifar10 example temps go up to 95C:
Could it be that CPU throttling is not working correctly?
 ```
./examples/cifar10/train_full.sh
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   6863   94.0c    195.0W   1528Mhz  945Mhz   40.0%    auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================


```

**Comment by gstoner** [comment]
HIPinfo runs a kernel.  I need to dump the voltage cuves on the VBIOS.   

Greg

**Comment by csuji** [comment]
Ok, I have now installed fancontrol package (https://wiki.archlinux.org/index.php/Fan_speed_control)  to manually control fan speed with following /etc/fancontrol config:
```
# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=5
DEVPATH=hwmon0=devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0
DEVNAME=hwmon0=amdgpu
FCTEMPS=hwmon0/pwm1=hwmon0/temp1_input
FCFANS= hwmon0/pwm1=hwmon0/fan1_input
MINTEMP=hwmon0/pwm1=25
MAXTEMP=hwmon0/pwm1=90
MINSTART=hwmon0/pwm1=20
MINSTOP=hwmon0/pwm1=5
```
with that I get max. temps of 77C when testing with ./examples/cifar10/train_full.sh (max. 81% fan speed) and during idle about 39C:
```
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   6863   39.0c    5.0W     852Mhz   945Mhz   27.84%   auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
```
Idle temp. would be probably lower when MCLK scales like GPU frequency or this only possible on MI25 cards?

**Comment by gstoner** [comment]
This is much better 

Greg
