### ISSUE TITLE
vector_copy example failed with "elf_begin failed: invalid command"

### ISSUE THREAD

**Issue by beasterio** [RadeonOpenCompute/ROCm#197]
Hi.
I have installed rocm 1.6 and trying vector_copy test but it failed:
beasterio@beasterio-pc:~/test$ ./vector_copy 
Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent succeeded.
Querying the agent name succeeded.
The agent name is gfx803.
Querying the agent maximum queue size succeeded.
The maximum queue size is 131072.
Creating the queue succeeded.
"Obtaining machine model" succeeded.
"Getting agent profile" succeeded.
Create the program succeeded.
Adding the brig module to the program succeeded.
Query the agents isa succeeded.
elf_begin failed: invalid command

Finalizing the program failed.

in test it uses vector_copy_base.brig, so maybe its not valid.

HelloWorld example works fine. I tried also HIP examples and they are ok too.
Ubuntu 16.04, video - Radeon rx 480.

**Comment by gstoner** [comment]
We removing this test,  and moving to use HIPinfo instead,  we been slowing working on removing this backend from ROCm.

Greg
On Sep 5, 2017, at 4:25 AM, Konstantin Zverev <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi.
I have installed rocm 1.6 and trying vector_copy test but it failed:
beasterio@beasterio-pc:~/test$ ./vector_copy
Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent succeeded.
Querying the agent name succeeded.
The agent name is gfx803.
Querying the agent maximum queue size succeeded.
The maximum queue size is 131072.
Creating the queue succeeded.
"Obtaining machine model" succeeded.
"Getting agent profile" succeeded.
Create the program succeeded.
Adding the brig module to the program succeeded.
Query the agents isa succeeded.
elf_begin failed: invalid command

Finalizing the program failed.

in test it uses vector_copy_base.brig, so maybe its not valid.

HelloWorld example works fine. I tried also HIP examples and they are ok too.
Ubuntu 16.04, video - Radeon rx 480.

**Comment by jedwards-AMD** [comment]
The test is being removed, but the error you are receiving indicates the brig file you are loading and parsing with libelf is either corrupted or in a format not compatible with the version of libelf you are using. The vector_copy code, brig files and hsail have not been modified in a long time. I suggest trying another simple sample, like hipInfo, to see if your system setup is correct. As Greg indicated above, vector_copy is out of support.

**Comment by RaymonSHan** [comment]
I meet the same message in my RX580 with ubuntu 16.4
and I try hipInfo and some others samples, there are all OKed.
