### ISSUE TITLE
Suggested formatting change to develop/docs/reference/rocmcc/rocmcc.md

### ISSUE THREAD

**Issue by searlmc1** [RadeonOpenCompute/ROCm#1992]
On https://github.com/RadeonOpenCompute/ROCm/blob/develop/docs/reference/rocmcc/rocmcc.md , it would look better if Table 1 spanned both columns. Similar for Table 2. 

See
![image](https://user-images.githubusercontent.com/24464306/227614322-e44183cd-602a-41db-8e12-ff6728d78d05.png)

**Comment by saadrahim** [comment]
https://rocmdocs.amd.com/projects/alpha/en/develop/reference/rocmcc/rocmcc.html
Please check the latest render. I believe your concerns are addressed.

**Comment by Naraenda** [comment]
This is fixed in #1984
