### ISSUE TITLE
Which is better for AMD HW Clover or ROCm

### ISSUE THREAD

**Issue by ballsystemlord** [RadeonOpenCompute/ROCm#200]
Hello,
I am trying to experiment with my GPU to see how well OpenCL works and to get some experience. Then, if all goes well I think I'll upgrade because I have a project I'd like to do that needs a HPC solution.
I realize that this may not be a black and white answer. My current card is and AMD 7770.
I also asked on the mesa mailing list and was directed to reddit but reddit has very few specifics.
Thanks

**Comment by gstoner** [comment]
For that GPU your only choice is Clover.
