### ISSUE TITLE
Convert MIGraphX Documentation

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#2001]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX

**Comment by samjwu** [comment]
closed by https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1727

**Comment by samjwu** [comment]
merged in https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1748
