### ISSUE TITLE
Is dkms for kernel 6.1^ in the roadmap

### ISSUE THREAD

**Issue by alfonsocv12** [RadeonOpenCompute/ROCm#2013]
I'm not sure if this is an official AMD project. My question is simple is there a 6.1^ dkms version in the roadmap, if it is can I help with something I'm not an expert on GPUs but I want to have a server running and I use vanilla Debian so this could come in handy for me

**Comment by xuhuisheng** [comment]
1. Yes, here is the official AMD project.
2. Actually the dkms sources always commit to the linux kernel with amdgpu driver. So we can use upstream dkms from linux kernel. The difference is linux release version may stay an old version of kernel, so related dkms is an old version, so amdgpu driver cannot support new AMD gpu card.

But 6.1 is a quite new version, so I guess the built-in version of amdgpu and dkms from 6.1 may support at least RDNA2, likes RX6800.

**Comment by alfonsocv12** [comment]
So I can just install dkms from my mirror and run

`sudo amdgpu-install --usecase=hiplibsdk,rocm --no-dkms`

And I should be able to use my GPU with pytorch?

**Comment by xuhuisheng** [comment]
@alfonsocv12 
The installation script is OK.

And before test pytorch, I suggest you test your gpu with `/opt/rocm/bin/rocminfo` to see which isa version of your card, likes gfx1030. And make sure pytorch-rocm can support this card.

Good luck.

**Comment by alfonsocv12** [comment]
I have done this, `$ rocminfo` outputs 

```batch
ISA INFO:
    ISA 1
        Name:                 amdgcn-amd-amdhsa-gfx1030
```

**Comment by alfonsocv12** [comment]
Thanks a lot @xuhuisheng its working now 🥳

```
>>>import torch
>>>torch.cuda.is_available()
True
```

I'm going to make a medium post on the topic for people trying to get a similar setup

**Comment by YellowRoseCx** [comment]
I believe a proper AMDGPU DKMS compiles on Linux OEM kernel 6.1.0 with ROCm 5.6.0 now
