### ISSUE TITLE
When do the rocm 5.5.0 release? 

### ISSUE THREAD

**Issue by PennyFranklin** [RadeonOpenCompute/ROCm#2038]
I can't wait to use my 7900xtx to run stable diffusion under rocm, rather than directml on win11, which is a bad experience.

**Comment by KylinC** [comment]
I can't wait, too

**Comment by PennyFranklin** [comment]
> 我也等不及了

刚刚忒特看到了，w7900专业卡有了，ROCm支持近在眼前

**Comment by Roachomg** [comment]
争取5.6上windows
waiting 'Rocm for windows' on version 5.6

**Comment by xuhuisheng** [comment]
> 争取5.6上windows waiting 'Rocm for windows' on version 5.6

I am afraid ROCm-5.6 already enter internal test steps, and there is no sign to show windows official supporting.

**Comment by Roachomg** [comment]
> I am afraid ROCm-5.6 already enter internal test steps, and there is no sign to show windows official supporting.
Acknowledged,thanks for reply!

**Comment by PennyFranklin** [comment]
> > 争取5.6上windows waiting 'Rocm for windows' on version 5.6
> 
> I am afraid ROCm-5.6 already enter internal test steps, and there is no sign to show windows official supporting.

Pro w7900卡发布了，和7900xtx一个核心，那按道理来说我这个7900xtx很快就能适配ROCm了吧

**Comment by xuhuisheng** [comment]
> > > 争取5.6上windows waiting 'Rocm for windows' on version 5.6
> > 
> > 
> > I am afraid ROCm-5.6 already enter internal test steps, and there is no sign to show windows official supporting.
> 
> Pro w7900卡发布了，和7900xtx一个核心，那按道理来说我这个7900xtx很快就能适配ROCm了吧

首先ROCm-5.5大概率能支持gfx11 - 7xxx系列。参考miopen对应ROCm-5.5的issue <https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1925>

但是ROCm-5.5已经测试了4个月了，还没发布。之前也有ROCm-4.4只做内部发布，最终没有公开发布的例子，所以不敢说ROCm-5.5会不会公开发布出来。

主要是现在ROCm-5.6都进测试阶段了，也有可能一个月后ROCm-5.6直接发布出来了。到时候ROCm-5.6倒是肯定能支持gfx11。

**Comment by KylinC** [comment]
只能用来打游戏了，大概

**Comment by Enferlain** [comment]
rocm for windows soon copium

**Comment by trougnouf** [comment]
I couldn't care less about Windows but 7900 XTX ROCm support is very much looked forward to.

**Comment by trougnouf** [comment]
> 1 guy on linux vs millions on windows omegalol

Playing with stable diffusion maybe, but not many people are doing actual ML development on Windows.

**Comment by wszgrcy** [comment]
https://gist.github.com/In-line/c1225f05d5164a4be9b39de68e99ee2b 
but amd delete image. the torrent now no speed .......

**Comment by PennyFranklin** [comment]
> > > > 争取5.6上windows waiting 'Rocm for windows' on version 5.6
> > > 
> > > 
> > > I am afraid ROCm-5.6 already enter internal test steps, and there is no sign to show windows official supporting.
> > 
> > Pro w7900卡发布了，和7900xtx一个核心，那按道理来说我这个7900xtx很快就能适配ROCm了吧
> 
> 首先ROCm-5.5大概率能支持gfx11 - 7xxx系列。参考miopen对应ROCm-5.5的issue <https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1925>
> 
> 但是ROCm-5.5已经测试了4个月了，还没发布。之前也有ROCm-4.4只做内部发布，最终没有公开发布的例子，所以不敢说ROCm-5.5会不会公开发布出来。
> 
> 主要是现在ROCm-5.6都进测试阶段了，也有可能一个月后ROCm-5.6直接发布出来了。到时候ROCm-5.6倒是肯定能支持gfx11。

刚刚看B站直播有up主说AMD官宣win上ROCm了，既然上那肯定是一家人整整齐齐了，我已经不急了

**Comment by GeneralAwareness** [comment]
Coming from Nvidia, I take it AMD sells a new line up of cards then put on their clown outfit to Bozo us to death like this?

**Comment by sirus20x6** [comment]
I'm also in need of 7000 support on linux. This release is months behind schedule.

**Comment by aoolmay** [comment]
Rocm for the last two generations seems to be including, working but unofficial, gaming cards support with the release of workstation analogs.
AMD has only just announced W7800 and W7900 workstation cards. Press release mentions second half of year, still a couple months away.

Can't wait myself, but not buying into 7900 too early, might even wait for 7950 altoghether.

**Comment by PiotrKlimczak** [comment]
There is already 5.5rc5 in the wild as docker container. Got it working fully with PyTorch on my 7900xt.

**Comment by sirus20x6** [comment]
> There is already 5.5rc5 in the wild as docker container. Got it working fully with PyTorch on my 7900xt.

but have you gotten it to work outside of docker?

**Comment by PiotrKlimczak** [comment]
Nope.

**Comment by GeneralAwareness** [comment]
We need to get it out from under docker as docker does give a performance hit, as the numbers I was seeing on a 7900XTX I had test were barely more than a 3060ti at about 5.25it/s for 768x768 in SD.

**Comment by PiotrKlimczak** [comment]
Interesting. TBC I am running Linux. 
Afaik docker gives no performance penalty as it runs directly on host kernel with no hardware emulation.
The only difference with docker vs host is that docker runs its own libs on top of standard kernel and does that with its own isolated up stack and usually cpu/ram quotas.

**Comment by GeneralAwareness** [comment]
Which is an extra layer and that is a performance hit.  I despise docker so can't wait for it.  One thing he couldn't get to work was the sdp optimization as he added it and the results were exactly the same so his numbers are looking good for no xformers or the pytorch2 optimization.

**Comment by PiotrKlimczak** [comment]
Regadless, got it working natively on Ubuntu 20.
Reason for that was that Docker umages from rocm repo were also Ubuntu 20.

1. Install ubuntu 20.04
2. Install AMDGPU PRO driver from AMD
3. Restart ubuntu to pick up new driver
4. Install Anaconda from the net
5. $ conda create -n anaconda38 python=3.8
6. $ conda activate anaconda38
7. $ export HIP_VISIBLE_DEVICES=0
8. $ export PYTORCH_ROCM_ARCH="gfx1100"
9. pull "rocm/composable_kernel:ck_ub20.04_rocm5.5_rc5" docker image and start it (unfortunately not avaialble anymore as they keep deleting them)
10. Copy /opt/rocm* from docker image to your local /opt
11. Install PyTorch 2.0.0 as per https://github.com/pytorch/pytorch#from-source to youor conda 

Above is was inspired by https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/9591

**Comment by PiotrKlimczak** [comment]
Works also on Ubuntu 22 with conda but required quite few hacks so don't recommend trying until official build available.

**Comment by PennyFranklin** [comment]
> Works also on Ubuntu 22 with conda but required quite few hacks so don't recommend trying until official build available.

thanks a lot, and actually I use ubuntu 22, so I'll wait or even wait for the Windows  release

**Comment by GeneralAwareness** [comment]
After seeing how everything runs smoother, and faster on Linux, I am ditching Windows for AI stuff.

**Comment by sirus20x6** [comment]
I check back 3 times a day to see if I can use the gpu I paid $1,000 for. still the answer is no.

**Comment by PennyFranklin** [comment]
i paid for almost 1300 dollars : ( GPU's price was very crazy at China months ago. and enen so i can't enjoy the functions after a long time wait... i consider i would buy NVIDIA card for the next time

**Comment by radudiaconu0** [comment]
https://github.com/RadeonOpenCompute/ROCm/pull/2094

no windows suport nice nice very nice.

**Comment by radudiaconu0** [comment]
We don't even have Rx 7900xtx support ik this release. Cool

**Comment by sucaiji** [comment]
Amd, fuck you! I've been waiting for almost half a year, why doesn't version 5.5 still support 7900XT/7900XTX?

**Comment by radudiaconu0** [comment]
@sucaiji and they deleted some days ago docs for windows with no explanation

**Comment by cguentherTUChemnitz** [comment]
> When do the rocm 5.5.0 release?

The answer is:
4 hours ago: https://github.com/RadeonOpenCompute/ROCm/releases/tag/rocm-5.5.0

**Comment by PiotrKlimczak** [comment]
Let's wait for official community builds. I am pretty sure 7900 cards will work as they were in latest rc builds. I mean why wouldn't they.

**Comment by GeneralAwareness** [comment]
> Let's wait for official community builds. I am pretty sure 7900 cards will work as they were in latest rc builds even if not explicitly mentioned in release notes. I mean why wouldn't they. Also they do mention some gfx11 changes which would be for 7900 cards too.

Oh, the irony in that.  Being serious here.

**Comment by aoolmay** [comment]
@GeneralAwareness That's laughable indeed. This kind of messaging from community had me wasted 100s of hours when i was begging my journey years ago. This is just short of encouraging prematurely buying cards that are not fit for purpose and being forced to run some degraded performance software.

**Comment by PennyFranklin** [comment]
> ROCm 5.5.0 was released yesterday. I am closing this thread as a result. 
> 
> These forums have not been actively moderated in the past. Please watch your language. We are trying to keep a welcoming environment for everyone. I do not want to have to take any action against participants but may do so in the future.
> 
> As you may be aware, AMD has source code for Windows available in the many public repositories that constitute ROCm. However, full ROCm functionality has not been announced on Windows yet. Please await a public announcement with the understanding that no timeline is available now.  Only the HIP runtime is bundled with the drivers on Windows at present.
> 
> In addition, the milestones publicly shared in this repository are not final. Features may be transferred to a different milestone at any time.
> 

but I tried and couldn't  update rocm in the ubuntu22.04.2 by 'sudo  apt upgrade' code or 'sudo apt install rocm-dev' code

**Comment by sirus20x6** [comment]
> > ROCm 5.5.0 was released yesterday. I am closing this thread as a result.
> > These forums have not been actively moderated in the past. Please watch your language. We are trying to keep a welcoming environment for everyone. I do not want to have to take any action against participants but may do so in the future.
> > As you may be aware, AMD has source code for Windows available in the many public repositories that constitute ROCm. However, full ROCm functionality has not been announced on Windows yet. Please await a public announcement with the understanding that no timeline is available now.  Only the HIP runtime is bundled with the drivers on Windows at present.
> > In addition, the milestones publicly shared in this repository are not final. Features may be transferred to a different milestone at any time.
> 
> but I tried and couldn't update rocm in the ubuntu22.04.2 by 'sudo apt upgrade' code or 'sudo apt install rocm-dev' code

Just because ROCM 5.5 is released doesn't mean that ubuntu is going to pick up the package and put it in apt any time soon. Your best bet is to try compiling from source, in other words this git repository.

**Comment by PennyFranklin** [comment]
emmm，so how about open the terminal under the 'opt' file and key the code 'git clone....... (rocm)'?

**Comment by xuhuisheng** [comment]
@PennyFranklin 
You can follow the offical installation document.
<https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.5/page/Introduction_to_ROCm_Installation_Guide_for_Linux.html>

**Comment by PiotrKlimczak** [comment]
Or just pull docker image https://hub.docker.com/r/rocm/composable_kernel/tags and copy it from there. 
Getting it working on Ubuntu 22 requires few lib hacks but it works.

**Comment by selroc** [comment]
> > > ROCm 5.5.0 was released yesterday. I am closing this thread as a result.
> > > These forums have not been actively moderated in the past. Please watch your language. We are trying to keep a welcoming environment for everyone. I do not want to have to take any action against participants but may do so in the future.
> > > As you may be aware, AMD has source code for Windows available in the many public repositories that constitute ROCm. However, full ROCm functionality has not been announced on Windows yet. Please await a public announcement with the understanding that no timeline is available now.  Only the HIP runtime is bundled with the drivers on Windows at present.
> > > In addition, the milestones publicly shared in this repository are not final. Features may be transferred to a different milestone at any time.
> > 
> > 
> > but I tried and couldn't update rocm in the ubuntu22.04.2 by 'sudo apt upgrade' code or 'sudo apt install rocm-dev' code
> 
> Just because ROCM 5.5 is released doesn't mean that ubuntu is going to pick up the package and put it in apt any time soon. Your best bet is to try compiling from source, in other words this git repository.

This is not necessary to compile from source. You just have to change a line in /etc/apt/sources.list.d/rocm.list file, and you will pick the version you want.
