### ISSUE TITLE
Obtain CU physical ID from HIP kernel?

### ISSUE THREAD

**Issue by Huangxt57** [RadeonOpenCompute/ROCm#2059]
Is there any approach for programmers to obtain the CU's physical ID like the way in CUDA:
```cpp
__device__ uint get_smid(void) {
   uint ret;
   asm("mov.u32 %0, %smid;" : "=r"(ret) );
}
```

**Comment by xfyucg** [comment]
```
__device__ uint get_smid(void) {
     uint cu_id;
     
     // for gfx9
     asm volatile ("s_getreg_b32 %0, hwreg(HW_REG_HW_ID, 8, 4)" : "=s"(cu_id));
     
     // for gfx10, gfx11
     asm volatile ("s_getreg_b32 %0, hwreg(HW_REG_HW_ID1, 10, 4)" : "=s"(cu_id));
     
     return cu_id;
}
```

**Comment by Huangxt57** [comment]
It works! Thanks very much!

**Comment by Huangxt57** [comment]
> ```
> __device__ uint get_smid(void) {
>      uint cu_id;
>      
>      // for gfx9
>      asm volatile ("s_getreg_b32 %0, hwreg(HW_REG_HW_ID, 8, 4)" : "=s"(cu_id));
>      
>      // for gfx10, gfx11
>      asm volatile ("s_getreg_b32 %0, hwreg(HW_REG_HW_ID1, 10, 4)" : "=s"(cu_id));
>      
>      return cu_id;
> }
> ```

BTW, I'm wondering how the bit starter offset and the bit width determined? I only find one docs describing the `hwreg` semantics but no register format for each `hwreg` ID. Thank you.

**Comment by xfyucg** [comment]
For gfx11,
https://www.amd.com/system/files/TechDocs/rdna3-shader-instruction-set-architecture-feb-2023_0.pdf
3.4.8. Hardware Internal Registers
or
https://elixir.bootlin.com/linux/latest/source/drivers/gpu/drm/amd/include/asic_reg/gc/gc_11_0_0_sh_mask.h#L41544

For gfx9,
https://elixir.bootlin.com/linux/latest/source/drivers/gpu/drm/amd/include/asic_reg/gc/gc_9_0_sh_mask.h#L28475

You may need SE_ID and SA_ID to calculate the global CU_ID/WGP_ID.

**Comment by b-sumner** [comment]
It's a bad idea to use inline asm unless absolutely necessary.  It's not necessary here.  See, e.g. https://github.com/ROCm-Developer-Tools/hipamd/blob/develop/include/hip/amd_detail/amd_device_functions.h#L957

**Comment by Huangxt57** [comment]
I can obtain the CU ID from the built-in device intrinsic function `__smid()` now, but all the CTA returns 0 in the following code:
```cpp
__global__ void get_cu_id(uint32_t *ids) {
  uint32_t cu_id;
  if (threadIdx.x == 0) {
    // asm volatile("s_getreg_b32 %0, hwreg(HW_REG_HW_ID1, 10, 4)" : "=s"(cu_id));
    cu_id = __smid();
    ids[blockIdx.x] = cu_id;
  }
}

get_cu_id<<<num_cta, warpSize, 0, stream>>>(cu_id_d);
```

All the elements in `cu_id_d` are 0, does it make sense?

Note that if I use the inline asm, the return values indicate that the CTAs are dispatched to each CU in a round-robin fashion:
```
CTA 0, CU ID: 0
CTA 1, CU ID: 1
CTA 2, CU ID: 2
CTA 3, CU ID: 3
CTA 4, CU ID: 0
CTA 5, CU ID: 1
CTA 6, CU ID: 2
CTA 7, CU ID: 3
```

**Comment by b-sumner** [comment]
Unfortunately __smid is broken, and should be fixed in an upcoming release.  But note how it doesn't use any inline asm to do its job.  I hope you're aware that the result from SMID or any ID query can change over time.

**Comment by b-sumner** [comment]
No comment.  I recommend using __builtin_amdgcn_s_getreg to read such registers.

**Comment by Huangxt57** [comment]
Thanks for your reply.
