### ISSUE TITLE
-save-temps assembly dump issue w. binary encoding for 64-bit instructions

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#206]
On AMDGPU-pro 17.30, RX Vega 64, Linux.
Passing -save-temps when compiling the OpenCL kernel dumps assembly in a file like _0_gfx900.s, e.g.
```
flat_load_dwordx4 v[19:22], v[2:3]                   // 00000000C0EC: DC5C0000 DC5C0000
flat_load_dwordx4 v[35:38], v[10:11]                 // 00000000C0F4: DC5C0000 DC5C0000
```
In the comment is the address and the binary encoding of the instruction. For 64 bits instructions, the binary encoding is wrong, being one word written twice (DC5C0000 DC5C0000) instead of the correct encoding.

**Comment by gstoner** [comment]
@preda Do you see the same issue on 1.6.3 compiler,  I am checking this out

**Comment by preda** [comment]
I'm on Linux 17.04 thus I don't have ROCm 1.6.3 (that's why I still use AMDGPU-pro)...

**Comment by preda** [comment]
This is still ON in ROCm 1.6-180. (Ubuntu 16.04, R9-Nano).

**Comment by dfukalov** [comment]
Hi @preda whould you please provide example kernel an compilation switches (e.g. dumped .cl file) ?

**Comment by preda** [comment]
Please have a look at the attached ISA here for an example:
https://github.com/RadeonOpenCompute/ROCm/issues/241

Compile any kernel that contains any 64-bit instructions. Dump with -save-temps=folder/
This is 100% reproducible and affects every kernel and dump.

**Comment by dfukalov** [comment]
https://github.com/RadeonOpenCompute/llvm/commit/21d31c0bdc85ec696a15e2b5366edd054b3906d5
fixes the issue
