### ISSUE TITLE
Difference between rock-kernel-driver and linux kernel

### ISSUE THREAD

**Issue by lintcoder** [RadeonOpenCompute/ROCm#207]
I am trying to build rock-kernel-driver on branch roc-1.6.3, and I want to know if the modification of the rock-kernel-driver bases on linux kernel tree, and all the modified files involved are only in directory drivers/gpu/drm/amd/amdkfd?  @gstoner

**Comment by fxkamd** [comment]
There are modifications in other parts of the kernel as well. Mostly in amdgpu (and radeon, though that's just to keep it compiling).
