### ISSUE TITLE
ROCM not working at all on fresh Ubuntu 22.04 with rx570

### ISSUE THREAD

**Issue by ColdSpirit0** [RadeonOpenCompute/ROCm#2071]
Hi! I spent multiple days in trying to install ROCm on my Mint 21, based on Ubuntu 22, but got zero result.

I tried to install different versions with different ways; tried to install even ROCm 4.3.1, which should work on my GPU, but no; with dkms and without; downgraded kernels min to 5.14.0. It was no success for me to install ROCm 3.5.1, because it not building, and also old kernel not loading. I tried to install legacy opencl, but it not installing.

Today I installed fresh Ubuntu 22.04 to check it is just my OS or really ROCm not working. I installed ROCm 5.4.3 and it gave me same results - just no GPU agent in rocminfo and no devices in clinfo. 

GPU: XFX rx570 8gb
Ubuntu clinfo & rocminfo output: [info.log](https://github.com/RadeonOpenCompute/ROCm/files/11297349/info.log)

**Comment by xuhuisheng** [comment]
As we know, RX570 aka gfx803 was the only card which need PCIe atomic feature.
So you can check it with `dmesg | grep kfd`, if there is something like `[skip](kfd: skipped device 1002:7300, PCI rejects atomics)`, it said your cpu or motherboard cannot support PCIe atomic feature, so gfx803 cannot run properly.

**Comment by ColdSpirit0** [comment]
@xuhuisheng oh thank you! I had to read [manual](https://docs.amd.com/bundle/Hardware_and_Software_Reference_Guide/page/Hardware_and_Software_Support.html) much carefully... I spent so much time to get it to work, but now it clear for me. 

I have this line in dmesg:
`[    3.091074] kfd kfd: amdgpu: skipped device 1002:67df, PCI rejects atomics 730<0`

I can use this GPU on Windows with DirectML, maybe similar workaround existing on Linux?

**Comment by xuhuisheng** [comment]
@ColdSpirit0 
The AMD dont want to reply for gfx803 PCIe atomic question.

Even RDNA1 and RDNA2 can upgrade firmware to remove PCIe atomic requirement.

I am afraid gfx803 had been abandoned.

**Comment by ColdSpirit0** [comment]
Thank you again @xuhuisheng . Hope AMD will make the fix someday.
