### ISSUE TITLE
Fix EULA link

### ISSUE THREAD

**Issue by samjwu** [RadeonOpenCompute/ROCm#2072]
Broken link: https://www.amd.com/en/support/gpu-pro-eula

Affected Files:
`release/licensing.md`
`deploy/linux/install_overview.md`

**Comment by Rmalavally** [comment]
@samjwu I don't see installing_linux in 'understand'. Have you renamed it and moved it to https://github.com/RadeonOpenCompute/ROCm/tree/develop/docs/deploy/linux? 

Please confirm.

**Comment by samjwu** [comment]
Yes, it was moved to https://github.com/RadeonOpenCompute/ROCm/blob/develop/docs/deploy/linux/install_overview.md. I have updated the issue description.

**Comment by Rmalavally** [comment]
Perfect. Thanks so much!

**Comment by Rmalavally** [comment]
I fixed both md files. Could you please review and merge the PR? Thanks so much.

**Comment by samjwu** [comment]
https://github.com/RadeonOpenCompute/ROCm/pull/2105
