### ISSUE TITLE
AMDGPU-pro 17.30 OpenCL: spurious warning about "-I ."

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#209]
On Ubuntu 17.04, AMDGPU-pro 17.30 (--compute), RX Vega 64, OpenCL.
If the kernel includes a file from the current directory, like:
#include "foo.h"

Passing "-I." as argument to clBuildProgram() generates the warning:
warning: argument unused during compilation: '-I .'

But not passing that argument produces:
#include "foo.h"
         ^~~~~~~~~~~
1 error generated.
OpenCL compilation log (error -11):
Error: Failed to compile opencl source (from CL to LLVM IR).

I guess the warning shouldn't be generated if the "-I ." is actually needed, or otherwise consider the current directory by default for #include "".

**Comment by gstoner** [comment]
Can you check the new ROCm 1.6.4  just to see if the this fixes your compiler issue, until 17.40 comes out

**Comment by preda** [comment]
Can I check ROCm 1.6.4 on Ubuntu 17.04 or 17.10? (these are the only OSes I have installed)

**Comment by gstoner** [comment]
we had others who have installed it.

**Comment by gstoner** [comment]
Have you looked at new 17.40 Linux beta this is using old compiler

**Comment by gstoner** [comment]
http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-Pro-Beta-Mining-Driver-for-Linux-Release-Notes.aspx

**Comment by preda** [comment]
I tried an install of ROCm as per https://rocm.github.io/ROCmInstall.html on Ubuntu 17.10 and it doesn't boot. I'll be looking into AMDGPU-pro 17.40 next.

**Comment by gstoner** [comment]
I should say only 17.04 has it been tested

**Comment by preda** [comment]
So, should I try the binary ROCm 1.6.4 on Ubuntu 17.04 and it should work?

Alternativelly, I would attempt a build from source, but I didn't find documentation for that.

**Comment by preda** [comment]
After all, I did re-install my Ubuntu to move down to 16.04... (not very user-friendly, to force the OS)
And thus, I was able to experience ROCm first-hand!

The issue (-I . warning) seems fixed.

**Comment by gstoner** [comment]
Preda,   We very clear in our instruction what we support which is 16.04 LTS not 17.x release if you follow the instructions,  again we focus on LTS because ROCm really is for headless servers.
