### ISSUE TITLE
Remove all references to RadeonOpenCompute

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#2131]
Please replace the string with ROCm.

**Comment by MathiasMagnus** [comment]
I searched the ROCm repo for this string, used the search feature on the PR generated website, but there is no trace of this string outside GitHub links. I found that the spellchecker has it as [an entry](https://github.com/RadeonOpenCompute/rocm-docs-core/blob/bdfd921367bbe366ab525a7bfac091c01e2b56b3/.wordlist.txt#L199). @saadrahim Would removing that be a good resolution of this issue while also making sure it won't come back?
