### ISSUE TITLE
Status of Bristol Ridge Support

### ISSUE THREAD

**Issue by tstellar** [RadeonOpenCompute/ROCm#214]
What is the status of ROCm on Bristol Ridge APUs.  Are there any commercial motherboards that are known to work with Bristol Ridge and ROCm?

**Comment by gstoner** [comment]
It was reported HP Bristol Ridge APU Enabled system run ROCm 1.6.3 .   I am asking for exact model number.

**Comment by gstoner** [comment]
HP Pavilion - 15z Touch Laptop
Product number: V1M95AV
