### ISSUE TITLE
Missing cl_amd_device_attribute_query

### ISSUE THREAD

**Issue by CNugteren** [RadeonOpenCompute/ROCm#215]
A user of the CLBlast library [reported full output](https://github.com/CNugteren/CLBlast/issues/186#issuecomment-328012892) of running `/opt/rocm/opencl/bin/x86_64/clinfo` on a Fiji device with ROCm 1.6.

However, although it displays a value for  `CL_DEVICE_BOARD_NAME_AMD` which is part of the [AMD extension cl_amd_device_attribute_query](https://www.khronos.org/registry/OpenCL/extensions/amd/cl_amd_device_attribute_query.txt)), it does not list this extension when querying for the supported extensions.

Is `cl_amd_device_attribute_query` not officially supported by ROCm devices? How to reliably query for the `CL_DEVICE_BOARD_NAME_AMD` attribute?

**Comment by gstoner** [comment]
We have this in a newer version of OpenCL that runs on ROCm,  OpenCL is still in beta testing on ROCm.  We looking to see if can be enabled in the next release it not it be in the  November release

**Comment by CNugteren** [comment]
Any update? Can you confirm whether it is enabled in the 1.7 version?

**Comment by CNugteren** [comment]
@gstoner Any update? Can you confirm that this is available in the latest release?

**Comment by gstoner** [comment]
It should be in ROCm 1.7 https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blame/ac32bfefcac66667614ce392d2b196c52ac14beb/runtime/device/rocm/rocsettings.cpp#L106

**Comment by CNugteren** [comment]
OK, thanks. I'll ask the users of CLBlast to try ROCm 1.7 or newer.
