### ISSUE TITLE
AMD Media Framework on ROCm ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#218]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/4

Currently AMF is windows only. But, I think ROCm would be a perfect platform for accelerated
video encoding.

**Comment by boxerab** [comment]
Looking at the code, it looks like it is heavily dependent on windows SDK, so I guess not likely to happen.

**Comment by boxerab** [comment]
Green team has invested heavily in support for video, btw.

**Comment by gstoner** [comment]
Thank you for the info,  but they also have much larger team, we have to focus on the core and build out,   This great area the community could invest into

**Comment by boxerab** [comment]
Thanks, @gstoner, I will look into starting a port to Linux.

**Comment by boxerab** [comment]
It looks like the AMF team is working on this, but no ETA for when it might be available.
