### ISSUE TITLE
OpenCL rapid packed math support for Vega

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#219]
Any time frame for when this will be available ?

**Comment by jamilbk** [comment]
I'm curious about this too. But we should already be able to utilize the RPM instructions from the Vega ISA using inline GCN assembly, no?

**Comment by oscarbg** [comment]
+1

**Comment by gstoner** [comment]
It will be in ROCm 1.6.4 for OpenCL.  HIP and HCC support it today

**Comment by gstoner** [comment]
I just ran Mixbench this week on MI25,  not he has a couple of issue in his code.    But MI25 is hitting Float 16 22.5 TFLOPS at peak.  Float 32 11.2 at peak 

He @ekondis has few spot where is need to clean up  like so we can build mixbench. 

- mix_kernels_ocl.cpp:28:25: error: conflicting declaration ‘typedef short int cl_half2 [2]’
- /opt/rocm/opencl/include/CL/cl_platform.h:869:2: note: previous declaration as ‘typedef union cl_half2 cl_half2’

**Comment by boxerab** [comment]
Sounds good. Can you please update us on ETA for 1.6.4 ?

**Comment by gstoner** [comment]
When I am happy with it, right now looks like next week.

**Comment by boxerab** [comment]
OK, thanks for the update. Looking forward to it.

**Comment by gstoner** [comment]
@boxerab @ekondis Hey we loaded a new version of ROCm 1.6.4 at repo.radeon.com can you test it.

**Comment by boxerab** [comment]
Cool! I tested it - all functionality looks good. In particular, OpenCL image support looks complete.

Very happy with this release. Unfortunately, performance for my application is still almost twice as slow as windows version. I understand that this is still beta release..... I will open a separate issue for this.

**Comment by boxerab** [comment]
Will CodeXL work with ROCm ?

**Comment by boxerab** [comment]
What's the best way of troubleshooting performance difference between windows and ROCm drivers for OpenCL ?

**Comment by nevion** [comment]
@boxerab I asked this question a short while ago.  See #186 , it's now https://github.com/GPUOpen-Tools/RCP - but it is also included in the ubuntu install as  /opt/rocm/bin/rocm-profiler per @chesik-amd 's comment

**Comment by gstoner** [comment]
Yes use RCP to get the data, then you process it on CodeXL

**Comment by gstoner** [comment]
Remember we decided to build out fully open source compiler we are now working on addressing key shortcomings of the historical AMDGPU LLVM compiler code generator.    
- Improved Scheduler
- Put in place a New ILP scheduler.
- Scalarization/uniformity improvements 
- Better load/store vectorization.  – this is a Longer project
- Improved Peephole optimization for SDWA ( just went in trunk) 
- We have more work on loop unrolling and optimizations 
- Function call support 

We are also working on new foundation for perf counter and tracing support, plus went back to address the debugger.

**Comment by ekondis** [comment]
@gstoner I've removed the type redefinition in mixbench so it compiles flawlessly on the new ROCm release.

**Comment by gstoner** [comment]
Perfect.   both Alt and RO now work

**Comment by jamilbk** [comment]
@boxerab FYI looks like [PlaidML](https://github.com/plaidml/plaidml/issues/29) will be the first ML framework to support this :thumbsup:

**Comment by boxerab** [comment]
@jamilbk my question was regarding driver support for packed math. Once support is there, then anyone 
can use this, including PlaidML.

**Comment by tugrul512bit** [comment]
So this will boost performance as if passing from 486 to pentium? Cool.
