### ISSUE TITLE
OpenCL 2.0 Pipes ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#220]
Does ROCm have a pipe implementation? Or an ETA for when it will be implemented ?

Thanks!

**Comment by gstoner** [comment]
PIPE and DeviceEnqueue are not implemented,  In Nov we have. OpenCL 2.1 support with both features

On Sep 30, 2017, at 7:53 AM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


Does ROCm have a pipe implementation? Or an ETA for when it will be implemented ?

Thanks!

**Comment by boxerab** [comment]
Great, looking forward to 2.1 support.  I'm curious about how pipes are going to be implemented. 
I have a large kernel with two complex pieces that could be separated by pipes into two different kernels.
But, I need to understand the overhead involved in using pipes over regular buffers.

Could I use a pipe in the inner loop of a kernel, and get decent performance? 

Actually, I want to use two pipes : kernel 1 writes a byte to pipe1, and then waits for kernel 2 to process 
the byte and send another back in pipe 2.

If the kernels are running concurrently, and the bytes are cached rather than written to global memory,
I am hoping that performance could be good.

**Comment by ekondis** [comment]
@gstoner It's great to hear that OpenCL 2.1 will be supported! Does this imply also SPIR-V kernel consumption?

@boxerab This sounds having very tightly dependent kernels. I wouldn't expect this configuration to exhibit high performance.

**Comment by nevion** [comment]
@ekondis Tightly dependent kernels is the raison d'etre of pipes!  Cuts  host communication out of the loop and allows for multi-stage kernels which allows them to optimize away re-reading of global memory/inputs as the phases of the kernel change... kind of difficult to explain because some of this are higher level changes you may not immediately expect with the tool but it's really interesting what it enables if it works right.

**Comment by boxerab** [comment]
Thanks guys. So, yes, my question can be rephrased as: can two tightly coupled kernels use pipes to communicate and still get good performance?  My feeling is that is won't be possible, but hoping to be surprised!

**Comment by gstoner** [comment]
The current pipes spec is not optimal. There are strong opinion in my team it should have been left out of the 2.0 spec until they invested more time to get it correct. FPGA venders needed it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nevion** [comment]
@gstoner Is there anything you can identify as what was lacking or what should've been left out?  It is clear it came out need to unify altera's and xillinx's proprietary pipes implementation (and the ubiquity of pipes in general on that arch) but I've never heard from the GPU side why those same concepts and framework didn't translate well to GPU land.

**Comment by oscarbg** [comment]
@gstoner so you know if Windows OpenCL driver will get OpenCL 2.1 support in Nov too?
I say because preview drivers from new 17.40 branch are avaiable for Windows Insider and seems OpenCL 2.0 still?

**Comment by gstoner** [comment]
17.40 will not support OpenCl 2.1

**Comment by oscarbg** [comment]
thanks.. then what branch we are talking about? 17.50 by end of year? or Windows will has no plans for 2.1 this year?

**Comment by gstoner** [comment]
@boxerab Pipes did not make it into the OpenCL release for 1.7 I working with the Dev to get it back on track few other projects sidetracked this feature

**Comment by oscarbg** [comment]
and OpenCL 2.0 feature: enqueue_kernel? it's in 1.7?

**Comment by boxerab** [comment]
@gstoner thanks for the update. Looking forward to 1.7

**Comment by oscarbg** [comment]
@boxerab seeing you closed the issue is full OpenCL 2.0 done on ROCM driver right now?
sorry for asking again but OpenCL 2.0 enqueue_kernel is also done?

**Comment by boxerab** [comment]
Just got tired of waiting :) Will re-open.

**Comment by jlgreathouse** [comment]
Hi @boxerab 

Pipes and device enqueue should work as of ROCm 2.0, depending on which GPU you have.
