### ISSUE TITLE
Installation Instructions Required

### ISSUE THREAD

**Issue by NickDeBeenSAE** [RadeonOpenCompute/ROCm#2203]
This repo does not contain any instructions to build let alone run this program.

**Comment by saadrahim** [comment]
Please view the documentation at https://rocm.docs.amd.com

**Comment by NickDeBeenSAE** [comment]
That doesn't help a Windows user on WSL2 bud.

**Comment by NickDeBeenSAE** [comment]
There is currently no Windows version of ROCm available, and using WSL2 isn't helping as it does not detect my hardware.

**Comment by saadrahim** [comment]
ROCm is not supported on Windows including WSL2.

**Comment by NickDeBeenSAE** [comment]
Bulls***, because I have it installed, and it successfully ran in TinyGrad.

**Comment by NickDeBeenSAE** [comment]
Obviously there were error's, but that's fine.

The error's where due to myself not specifying an operation to run.

**Comment by satmandu** [comment]
Unsupported configuration does not imply that something won't work in part... It just implies that it should be assumed that any issues with a particular unsupported configuration won't get support.

**Comment by NickDeBeenSAE** [comment]
Its intended to fail if it runs on WSL2.

This is normal.
