### ISSUE TITLE
Create docs/x.y.z branches

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#2212]
- [x] For all ROCm releases from 5.0.0 to 5.5.1, create a docs/x.y.z branch.

- [x] Also create the corresponding RTD build jobs.

- [x] Make just the latest versions visible in the flyout menu via RTD config.

**Comment by samjwu** [comment]
Branches have been created for ROCm repositories with tags in the format below:

tag `rocm-5.x.x` > branch `docs/5.x.x`

**Comment by samjwu** [comment]
Also create the corresponding RTD build jobs.
Make just the latest versions visible in the flyout menu via RTD config.

Done for all repos except rdc (need an admin to activate the GitHub webhook for this repo)

**Comment by samjwu** [comment]
Done for all repos that have tags with the format `rocm-5.x.x`
