### ISSUE TITLE
rocm_agent_enumerator couldnt recognise the GPU

### ISSUE THREAD

**Issue by prasanth09** [RadeonOpenCompute/ROCm#223]
Hi , 

I am trying to run **_/opt/rocm/bin/rocm_agent_enumerator -t GPU_**  and getting the following output : 

**gfx000**

No GPU is being specified. I have tried updating the rocm driver but of no use.

**command** : uname -a 
**output** : Linux prasanth 4.11.0-kfd-compute-rocm-rel-1.6-148 #1 SMP Wed Aug 23 12:00:35 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**command** : /opt/rocm/hcc/bin/hcc --version
**output** : 
HCC clang version 6.0.0  (based on HCC 1.0.17373-bd1f35c-c639ce0-e4adac0 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin

**command** : lspci -v | grep -i amd
**output** : 
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Fiji [Radeon R9 FURY / NANO Series] (rev ca) (prog-if 00 [VGA controller])
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Radeon R9 FURY X / NANO
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aae8
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device aae8

Any inputs ?

**Comment by rhlug** [comment]
With an RX470 (custom bios) and a RX Vega 56 installed, kfd doesnt detect the RX470.   If I take the Vega out of the system, my RX470 works just fine by itself.

$ /opt/rocm/bin/rocm_agent_enumerator -t GPU 
gfx000
gfx900

$ lspci | grep VGA
26:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev cf)
29:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c3)

Here is dmesg with RX470 load failure and Vega56 load success.

[   12.206462] amdgpu 0000:26:00.0: amdgpu_init failed
[   12.314626] [drm] amdgpu: ttm finalized
[   12.314682] amdgpu 0000:26:00.0: Fatal error during GPU init
[   12.314741] [drm] amdgpu: finishing device.
[   12.315117] amdgpu: probe of 0000:26:00.0 failed with error -22
...
...
[   13.426862] kfd kfd: Allocated 3969056 bytes on gart for device 1002:687f
[   13.427797] kfd kfd: Reserved 2 pages for cwsr.
[   13.428086] kfd kfd: added device 1002:687f
[   13.428346] [drm] Initialized amdgpu 3.18.0 20150101 for 0000:29:00.0 on minor 0


Here is with just RX470

$ /opt/rocm/bin/rocm_agent_enumerator -t GPU 
gfx000
gfx803

$ lspci | grep VGA
26:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev cf)

dmesg

[    3.073351] fbcon: amdgpudrmfb (fb0) is primary device
[    3.124616] amdgpu 0000:26:00.0: fb0: amdgpudrmfb frame buffer device
[    3.141330] kfd kfd: Allocated 3969056 bytes on gart for device 1002:67df
[    3.141557] kfd kfd: Reserved 2 pages for cwsr.
[    3.141607] kfd kfd: added device 1002:67df
[    3.141630] [drm] Initialized amdgpu 3.18.0 20150101 for 0000:26:00.0 on minor 0


Thoughts?

**Comment by fxkamd** [comment]
amdgpu driver initialization fails. Can you provide full dmesg output?

**Comment by fxkamd** [comment]
Also, do we have two different issues reported on this thread? @prasanth09 has a single Fiji NANO card. @rhlug has a combination of Vega10 and Polaris10.

**Comment by rhlug** [comment]
@fxkamd its possible they are different issues.   I'll have to set things back up to generate that full dmesg.

**Comment by gstoner** [comment]
@rhlug can you update to ROCm 1.6.4 which was released last night let us know if you continue to see the issue,  we want to trace this down

**Comment by rhlug** [comment]
@gstoner I will get this setup today and tested.

**Comment by prasanth09** [comment]
I updated to latest ROCm and the issue is fixed. I am closing this issue now.

**Comment by rhlug** [comment]
Thats fine, I'll spin off a new BZ once I get the time and all the details sorted.

**Comment by VincentSC** [comment]
Seems this discussion is better than #281 
Second GPU in slot 4, /opt/rocm/bin/rocm_agent_enumerator gives:
> gfx000
gfx900

Second GPU in slot 3, /opt/rocm/bin/rocm_agent_enumerator gives:
> gfx000
gfx803
gfx900

**Comment by psn9** [comment]
But what I did in this case was just updatting ROCm. I was using Rocm 1.5 I suppose and upgrading it to 1.6.4 resolved the issue. 

Now in 1.7 , I end up with "No device" error.
And additionally , in ROCM 1.7 case , the rocm_agent_enumerator is able to recognise GPU unlike the case in this issue. I have mentioned it in [this comment](https://github.com/RadeonOpenCompute/ROCm/issues/281#issuecomment-361578737).

**Comment by VincentSC** [comment]
Possibly ROCm 1.7 reintroduced the problem with PCIx8? The list of VGA-devices from `sudo lspci -vv | grep 'LnkCap\|AMD'` here:
````
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Fiji [Radeon R9 FURY / NANO Series] (rev ca) (prog-if 00 [VGA controller])
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Radeon R9 FURY X / NANO
		LnkCap:	Port #0, Speed 8GT/s, Width x16, ASPM not supported, Exit Latency L0s <64ns, L1 <1us
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 [Radeon Vega Frontier Edition] (prog-if 00 [VGA controller])
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 [Radeon Vega Frontier Edition]
		LnkCap:	Port #0, Speed 8GT/s, Width x16, ASPM L0s L1, Exit Latency L0s <64ns, L1 <1us
````

When at port 4, that one would have had a Width of x8. So if somebody from the ROCm-team could please test with a GPU on a x8 port, to see if this is indeed a problem?

**Comment by gstoner** [comment]
What linux kernel version are you on, it might be the issue

**Comment by psn9** [comment]
Hello @gstoner , 

Can you point me to the right Linux kernel version ie., the output of `uname -a` ?

**Comment by gstoner** [comment]
Step one start with clean ubuntu 16.04 release. We have it running on stock 4.4 kernel and 4.10 kernel.   You have to follow these instructions exactly https://rocm.github.io/ROCmInstall.html.  If your on Intel based  you can use the 4.4, Only Ryzen do  need update Kernel 4.10 in 16.04.3. Soon they will release 4.13 but you want to wait for this one with newer 1.7.1 update we will be releasing.
