### ISSUE TITLE
vopd v_dual_and_b32 first argument problem

### ISSUE THREAD

**Issue by halfminer** [RadeonOpenCompute/ROCm#2230]
v_dual_add_f32 v17, v22, v26 :: v_dual_and_b32 v16, v21, v25 - ok
v_dual_and_b32 v17, v22, v26 :: v_dual_and_b32 v16, v21, v25 - error: invalid instruction

**Comment by b-sumner** [comment]
Unfortunately the set of X opcodes is not the same as the set of Y opcodes.  The assembler is correct to complain.
