### ISSUE TITLE
Differences ROCm packages

### ISSUE THREAD

**Issue by javierox** [RadeonOpenCompute/ROCm#224]
What are the differences between the ROCm package in the AMDGPU-PRO Driver Version 17.30 for Ubuntu 16.04.3 and this repository?.Because I successfully compiled manually and run many samples for rocm without installing any custom kernel, only module. There are some information not updated for ROCm and AMD-GPU PRO?
I do not want to offend anyone, sorry
Is really necessary all this package so complex and immersive? Is not a simple kernel module enough?
 Sorry again for my English.

**Comment by gstoner** [comment]
AMDGPU-Pro has subset of functionality for ROCm in this repo, what you do not understand DKMS package has all the bit on github   There is KFD, Thunk and ROCr runtime API which all the language runtime run on,  and also there are number of firmware enhancement over stock AMDGPU driver
