### ISSUE TITLE
Google search of installer returns old (invalid) documentation site links

### ISSUE THREAD

**Issue by gsitaram** [RadeonOpenCompute/ROCm#2264]
A search for the AMDGPU installer shows links from the old documentation portal. How do we fix google searches to point to the latest documentation
![Screenshot from 2023-06-22 10-45-11](https://github.com/RadeonOpenCompute/ROCm/assets/74741442/4ead3030-882b-4978-8ab1-751fa33b3b13)
?

**Comment by saadrahim** [comment]
Google reindexing should take a few days. Let's check again early next week. I anticipate this will be fixed then.
