### ISSUE TITLE
1.6.4 and 1.7.0 on RX470 : OpenCL image compression application is about half as fast compared to windows

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#228]
Intel i7 + RX 470 4 GB

I don't think this is related to compute, but rather to memory controllers and DMA transfer.

My application performs compression on 8,10 and 12 bit images, It allocates many OpenCL buffers and images, some residing only on device, some  with pinned host buffer for transfer of image data to and from card.

I found on windows that changing the order in which I allocate these buffers has a dramatic effect on performance. One particular order gives about twice as high performance as other orders.

On ROCm, I could get a 10% increase in performance by changing the order of allocation.

Also, interestingly, on ROCm, when I try an 8 bit image rather than 12 bit, my performance doesn't change. But, it should since 8 bit is 8/12 is big as 12 bit. 

So, it looks to me like sub-optimal DMA transfer from host to card.

**Comment by boxerab** [comment]
It would be very useful to understand how the order of buffer allocation affects performance.

**Comment by boxerab** [comment]
Another interesting behaviour: ordering the buffer allocation a certain way will halve performance on windows, but improve performance on ROCm by 20%.

**Comment by gstoner** [comment]
One thing that may be hurting this is your using BLIT kernel right now GFX8 for transfers.  We had shut off SDMA on Polaris and FIJI due firmware bug, we chased down.  Waiting for Firmware developer time to fix it.

**Comment by boxerab** [comment]
Thanks, Greg. Can you please explain what a BLIT kernel is?  The way I transfer data between host and device is mapping an OpenCL image created using CL_MEM_ALLOC_HOST_PTR  i.e. pinned memory.  Image size is around 10 MB typically. 

Also, if there is a POLARIS firmware fix, would this boost performance on windows as well ?  

Is the effect I am seeing perhaps a symptom of this bug ?

**Comment by boxerab** [comment]
So, I guess BLIT is at the driver level - SDMA is faster transfer, but currently disabled.

**Comment by boxerab** [comment]
Playing around with buffer allocation order, best perf I can get on ROCm is : ~50% more time per encoded frame than on windows.

**Comment by boxerab** [comment]
This issue has now been resolved, as of the 2.0 release.
