### ISSUE TITLE
Incorrect Returns for hipSetDevice and hipSetDeviceFlags APIs

### ISSUE THREAD

**Issue by Rmalavally** [RadeonOpenCompute/ROCm#2288]
hipSetDevice and hipSetDeviceFlags APIs return hipErrorInvalidDevice instead of hipErrorNoDevice on a system without a GPU.

This issue is under investigation and will be fixed in a future release.

**Comment by nartmada** [comment]
Hi @Rmalavally, does this issue still exist in latest ROCm 6.0.2?  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as issue has been fixed in ROCm 5.6.
