### ISSUE TITLE
Is Numba with ROCm support already public?

### ISSUE THREAD

**Issue by masahi** [RadeonOpenCompute/ROCm#229]
Hi, I've seen in some places that there is rocm backend support for Numba. For example, [here](https://rocm.github.io/languages.html) and [here](https://groups.google.com/a/continuum.io/d/msg/numba-users/hGMwJoes8N4/y5G4SWEoAgAJ).

But I don't see any rocm related code in numba except their hsa support [here](https://github.com/numba/numba/tree/master/numba/hsa).
Is Numba with Rocm still under development?

I have a working rocm install with r9 nano card. I'd love to try Numba on my nano.

Thanks

**Comment by gstoner** [comment]
Yes it also still under development

**Comment by masahi** [comment]
All right. Looking forward to the release.
