### ISSUE TITLE
Carrizo APU, Ubuntu 14.04, ROCm 1.2, stack trace on boot

### ISSUE THREAD

**Issue by Py0s** [RadeonOpenCompute/ROCm#23]
Hello,

I updated ROCm from 1.1.1 to version 1.2 and upon reboot I get a stack trace which hangs the boot sequence.
A fresh install of Ubuntu did nothing to solve this so it should easily be reproducible, at least on a Aspire E15 with a FX-8800P processor.

I would love to be able to paste the stack trace in this thread but kern.log doesn't show anything related to the 4.4.0-kfd-compute-rocm-rel-1.2-31 kernel and would gladly follow any directions as to provide any additional information. I do have a picture of it below which hopefully will get the idea across.

Would it be possible, as a fast recovery option, to provide ROCm version 1.1 through the apt-get server ?

![img_1211](https://cloud.githubusercontent.com/assets/4035760/17748327/bf54c04c-64b0-11e6-8e87-0b633a3dac20.JPG)

**Comment by jedwards-AMD** [comment]
The old kernel should still be installed on the system; it isn't removed by default and is compatible with the new 1.2 runtime components. I think the easiest solution would be to boot using the 1.1.1-10 kernel. This can be accomplished on boot by holding down the shift key while booting, selecting accessing "Advanced options for Ubuntu" and the selecting the 4.4.0-kfd-compute-rocm-rel-1.1.1-10 kernel.

**Comment by fxkamd** [comment]
There are at least two backtraces here, maybe more that are cut off. Can you get a complete kernel log from /var/log/kern.log? To make sure the log is as complete as possible, remount the root partition (assuming you don't have /var on its own partition) synchronously before rebooting:
    sudo mount -o remount,sync /

Then reboot, wait for it to get stuck, reset the system and grab /var/log/kern.log

If you still don't see anything useful in kern.log, the rsyslog daemon probably gets killed too early during shutdown. You could try commenting out the following line from /etc/init/rsyslog.conf to keep it running as long as possible:
    stop on runlevel [06]

I'm assuming that you're running Ubuntu 14.04 with upstart. If you're on Ubuntu 16.04 with systemd, I'm not as familiar with that.

**Comment by streamhsa** [comment]
Could you try following steps to clean up your old kernel/package completely then install 1.2?

uninstall steps:
==========
sudo apt-get purge $(dpkg -l | grep 'kfd\|rocm' | grep linux | grep -v libc | awk '{print $2}')
sudo  apt-get purge hcc_lc
sudo  apt-get purge hsakmt-rocm-dev
sudo dpkg -r hsakmt-roct-dev
sudo  apt-get purge hcc_hsail
sudo  apt-get purge llvm-amdgpu
sudo  apt-get purge rocm
sudo apt-get autoremove rocm
sudo dpkg -r compute-firmware
sudo dpkg -r hcblas
sudo rm -rf rocm 
sudo update-grub 

Install steps:
========
sudo apt-get clean all
echo fpadmin | sudo -S apt-get update
sudo apt-get install rocm

**Comment by streamhsa** [comment]
Could you try following steps to clean up your old kernel/package completely then install 1.2?

uninstall steps:
==========
sudo apt-get purge $(dpkg -l | grep 'kfd|rocm' | grep linux | grep -v libc | awk '{print $2}')
sudo apt-get purge hcc_lc
sudo apt-get purge hsakmt-rocm-dev
sudo dpkg -r hsakmt-roct-dev
sudo apt-get purge hcc_hsail
sudo apt-get purge llvm-amdgpu
sudo apt-get purge rocm
sudo apt-get autoremove rocm
sudo dpkg -r compute-firmware
sudo dpkg -r hcblas
sudo rm -rf rocm 
sudo update-grub

Install steps:
============
sudo apt-get clean all
sudo apt-get update
sudo apt-get install rocm

**Comment by Py0s** [comment]
Great will try uninstalling once I get back from work. Else I'll remount the root partition.

I doubt the uninstall process will solve the problem tho as I already tried to reinstall the whole system but it might show logs in keen.log again.

**Comment by Py0s** [comment]
After reinstalling the whole ROCm suite, Ubuntu's boot animation did appeared this time but hanged up. It did however had the effect of logging properly in the kern.log which you can find here:
[kern.log.txt](https://github.com/RadeonOpenCompute/ROCm/files/427470/kern.log.txt)

As we can see line 0.773282, the first call trace happens and triggers **AMD-Vi: Unable to write to IOMMU perf counter.**
However this message used to happen in version 1.1.1 and did not affect the execution of vector_copy.

Scrolling down to line 20.736147 is where I believe is the real problem as we get **amdgpu 0000:03:00.0: amdgpu_init failed** message which triggers a series of call trace.

**Comment by fxkamd** [comment]
Looks like Iceland GPU support is broken in our kernel. It fails to initialize and the error handling code seems to have some trouble and printing some warnings including backtraces. The actual protection faults that probably take down the system are later, in unrelated kernel functions. It's possible that faulty error handling in amdgpu is corrupting unrelated kernel data structures and causing problems later on.

Is there a way you can disable the dGPU in your BIOS setup as a workaround?

**Comment by Py0s** [comment]
Unfortunately, Acer BIOS is very limited and barely has any option regarding anything so I can't disable the dGPU.
Is there anyway I could be provided with the latest version of a deb package of ROCm 1.1 suite as a work around ? It seems I am to wait for a patch for HSA to work again and I unfortunately don't have that time as I have to present a working project relatively soon.

**Comment by jedwards-AMD** [comment]
Did you try booting to older kernel, or did you completely remove it?

**Comment by Py0s** [comment]
It is now completely removed. When I tried it before deleting the whole ROCm 1.1 suite it also wouldn't get past initialisation.

**Comment by jedwards-AMD** [comment]
Unfortunately our repo server doesn't archive older versions of the ROCm packages. We are considering enhancing the repo to support that, but it isn't implemented at this time.

**Comment by Py0s** [comment]
Yes I've noticed that which is unfortunate. Wouldn't it be possible to have them sent by mail ?
Or can I expect an update before the end of the month ?

Disabling the dGPU seems impossible on this machine.

**Comment by jedwards-AMD** [comment]
I have placed the kernel debian packages for ROCm 1.1.1 on the package server in a gzip file. You can download it with this command:
wget http://packages.amd.com/rocm/gz/linux-4.4.0-kfd-compute-rocm-rel_1.1.1.tar.gz
.
The ROCm 1.1.1 user-mode debians will not be provided.
