### ISSUE TITLE
slow shutdown/reboot on 16.04 LTS

### ISSUE THREAD

**Issue by rijujohnx** [RadeonOpenCompute/ROCm#230]
I am using the latest version of ROCm kernel and Xubuntu 16.04.  After installing the ROCm kernel I am experiencing very slow shutdown/reboot.  It takes approximately 3-4 minutes after "reached target shutdown"

NOTE: I have 8 amd gpu's connected using amdgpu-pro driver 17.30

**Comment by preda** [comment]
I think you're not supposed to mix ROCm with amdgpu-pro. Choose and keep only one.

**Comment by gstoner** [comment]
Yes your mixing and matching components this is not supported
