### ISSUE TITLE
ROCm 1.6-180 bad codegen? No

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#234]
On Ubuntu 16.04.3, R9-Nano, ROCm 1.6-180,
It seems to me there's a case of bad code generation.

The code is trimmed down from an NTT FFT that I develop (an FFT with modular arithmetic), I prepared a small test case here (with build instructions included):
https://github.com/preda/gpuowl/tree/master/bug

Let me explain why I think there's a problem:

in the kernel, commenting or un-commenting the barrier() right after the shufl() changes the result. IMO, that barrier is not needed and should not affect the result. The different outputs with/without the barrier indicates that at least one of the outputs is wrong.
```
kernel __attribute__((reqd_work_group_size(256, 1, 1))) void bug(global T2 *io, global T2 *trig) {
  local uint lds[8 * 256];
  uint me = get_local_id(0);
  T2 u[8];
  for (int i = 0; i < 8; ++i) { u[i] = io[256 * i + me]; }
  fft8(u);
  shufl(lds, u, 8, 32);

  // Comment or un-comment the next barrier() to observe different behavior.
  // barrier(CLK_LOCAL_MEM_FENCE);

  tabMul(trig, u, 8, 32);
  for (int i = 0; i < 8; ++i) { io[256 * i + me] = u[i]; }  
}
```

Now, for why the barrier() after shufl() isn't needed: after the last write to LDS there is a barrier(). So no thread changes LDS anymore after that.

After the final reading from LDS, each thread uses only what it itself read, thus no need for another barrier() after LDS read.

Please consider this, to me it clearly looks like it's P0 material.

**Comment by gstoner** [comment]
The team is looking at it now.

**Comment by gstoner** [comment]
From Compiler Engineering - With wg size of 256, second loop for some subgroups can start execution before the first finished in all of them. I.e. barrier is necessary.

**Comment by preda** [comment]
Thanks for looking into this so promptly! But why is the barrier necessary?
This is a schematic:
1. write to LDS
2. barrier()
3. read from LDS
4. [barrier()?]
5. use what was read from LDS
Clearly the barrier at step 2 is needed. But is the one at step 4 needed?

Let's assume there is no barrier at step 4, then some subgroups start 5 before all finished 3. But that is correct! because step 5 is not affected by other subgroups having finished or not step 3.

Thank you. I would love to be wrong on this issue, and the problem be only my misunderstanding.

**Comment by preda** [comment]
```
  for (uint i = 0; i < n; ++i) { lds[(m + i * 256 / f) / n * f + m % n * 256 + me % f] = ((T *) (u + i))[0]; }
  barrier(CLK_LOCAL_MEM_FENCE);
  for (uint i = 0; i < n; ++i) { ((T *) (u + i))[0] = lds[i * 256 + me]; }
  barrier(CLK_LOCAL_MEM_FENCE);
  for (uint i = 0; i < n; ++i) { lds[(m + i * 256 / f) / n * f + m % n * 256 + me % f] = ((T *) (u + i))[1]; }
  barrier(CLK_LOCAL_MEM_FENCE);
  for (uint i = 0; i < n; ++i) { ((T *) (u + i))[1] = lds[i * 256 + me]; }

  // barrier(CLK_LOCAL_MEM_FENCE); // Comment or un-comment this barrier() to observe different behavior.

  tabMul(trig, u, 8, 32);
  for (int i = 0; i < 8; ++i) { io[256 * i + me] = u[i]; }
```
I inlined the shufl() loop for clarity.

The only barrier() that I question is the very last one, which is commented out. Do you say that one is needed -- why?

**Comment by boxerab** [comment]
I think you have a bug in the code.

Should it not be:

     for (int i = 0; i < 8; ++i) { io[i + me * 8] = u[i]; }  

?

`256 * i + me` can be out of bounds for the given array size, for example when `i =7` and `me = 256`

**Comment by boxerab** [comment]
It looks like you are allocating 8 ints per work item, but the index you are using to access this data is broken.

**Comment by boxerab** [comment]
Oh, never mind :)

**Comment by preda** [comment]
One more thing, I don't think the problem I see here is "just" a barrier() issue. Putting/removing that barrier() was just a mechanism to express the problem (by getting different outcomes in the two cases), but I think the problem is a bit more profound than just barrier(). In my real code, even with all the barriers added, the code is still malfunctioning.

Maybe Compiler Engineering should have a serious look, rather than dismiss it superficially..

**Comment by preda** [comment]
The barrier() in question isn't actually needed. (and I'd like to hear the argument to the contrary).

The "bug fixing" behavior of the barrier() was due to it also implying a mem_fence(). The weaker mem_fence is enough to workaround as well.

The updated excerpt is:
```
  for (uint i = 0; i < n; ++i) { lds[(m + i * 256 / f) / n * f + m % n * 256 + me % f] = u[i].x; }
  barrier(CLK_LOCAL_MEM_FENCE);
  for (uint i = 0; i < n; ++i) { u[i].x = lds[i * 256 + me]; }
  barrier(CLK_LOCAL_MEM_FENCE);
  for (uint i = 0; i < n; ++i) { lds[(m + i * 256 / f) / n * f + m % n * 256 + me % f] = u[i].y; }
  barrier(CLK_LOCAL_MEM_FENCE);
  for (uint i = 0; i < n; ++i) { u[i].y = lds[i * 256 + me]; }
  
  // mem_fence(CLK_LOCAL_MEM_FENCE); // Comment or un-comment this to observe different behavior.

  tabMul(trig, u, 8, 32);
  for (int i = 0; i < 8; ++i) { io[256 * i + me] = u[i]; }
```

Of course, the question is *why* not putting a mem_fence() in that particular spot produces bad behavior. To me, it still looks like it's on the compiler, but I'm open to an explanation.

In the meantime, I'd propose re-qualifying this bug as valid.

**Comment by preda** [comment]
Ping? please either a confirmation of "invalid" or re-evaluation.

**Comment by gstoner** [comment]
a global barrier is needed, but the barrier is both a fence and execution barrier. The array io can be accessed out of order.

For the kernel above,  what is needed is barrier aspect of it. Memfence technically also needed, but global. Although one can be lucky with fence, it all depends on the behavior in with cache.

I am going to be offline a little bit I am bit under the weather.

**Comment by preda** [comment]
Yes I understand if you're away, please take care and get better.

Clearly I'm not proposing to remove *all* the barriers, only the very last one is in question.

Because of the first barrier (which stays) all the subgroups are done reading from the array io, and done writing what they read to LDS, before any subgroup starts writing to the array io.

So, how does your explanation work, what do you mean "the array io can be access out of order"? because all the subgroups are done reading, before any start writing to that array.

**Comment by preda** [comment]
I updated the sample at https://github.com/preda/gpuowl/tree/master/bug
to use distinct global arrays for input and output. The bug remains.

**Comment by gstoner** [comment]
did you look at this too.  http://rocm-documentation.readthedocs.io/en/latest/GCN_ISA_Manuals/testdocbook.html#testdocbook

**Comment by gstoner** [comment]
I sending to a different part of my compiler team tonight.   I am now really out

**Comment by preda** [comment]
Yes, many times. I've been reading the ISA docs since GCN 1.2 (Fiji), and been waiting with anticipation before the Vega ISA doc was released. (BTW, I've also found many typos and formatting errors in those docs, some persisting).

But, even if I had complete ignorance of the ISA, that would not by itself make this bug invalid.

**Comment by preda** [comment]
Thanks! your help is appreciated.

**Comment by gstoner** [comment]
I do not write the ISA doc,  Vega ISA  web doc if you see the issue it easy to fixes now.   The older documents were written in FrameMaker,  I think they lost skill to use the tools.  

No problem  I see what is in my box when I wake up.

**Comment by boxerab** [comment]
@preda have you tried this with work group size = 64 ? In this case, barriers would be removed by the compiler, as wg size is <= wave front size, so do you get the correct result in this case ?

**Comment by preda** [comment]
Yes, I can repro with WG==64 as well. I updated the bug-case with WG==64, and added a Makefile:
https://github.com/preda/gpuowl/tree/master/bug

**Comment by boxerab** [comment]
@preda  that is strange, because in this case, there should be no barriers.  If you look at disassembly, do you see any?

**Comment by boxerab** [comment]
I suspect the problem is somewhere else, then.

**Comment by boxerab** [comment]
You should really put brackets around different arithmetic operations to make sure you have the right
order. For example % is weaker than *, so put brackets to make sure the index you calculate is correct
and not out of bounds. Can you add checks to make sure the the indexes are always less than 8*256 ?

**Comment by preda** [comment]
With workgroup size == 64 there are no barriers generated in the ISA, as expected.

I didn't say that this is a "barrier bug", I said it's a codegen bug. OTOH somebody from AMD said that it's just programmer error consisting in bad use of barriers by the programmer. Now with WG=64 that explanation becomes moot.

About order of operations ("operator precedence"), the order is well defined according to the C language. In particular, % has the same precedence as * and /, not weaker.
http://en.cppreference.com/w/c/language/operator_precedence

**Comment by preda** [comment]
@gstoner , why is this bug marked "invalid"?
