### ISSUE TITLE
build on kernel error

### ISSUE THREAD

**Issue by reger-men** [RadeonOpenCompute/ROCm#239]
What doest that mean:

```
ERROR (dkms apport): binary package for amdtPwrProf: 6.01 not found
Error! Bad return status for module build on kernel: 4.11.0-kfd-compute-rocm-rel-1.6-180 (x86_64)
```
Is the Kernel build successful?

**Comment by gstoner** [comment]
Are you mixing AMD GPUpro with ROCm components that is only reason you see issue

**Comment by reger-men** [comment]
I uninstalled it with `amdgpu-pro-uninstall`.

**Comment by reger-men** [comment]
When I run test `./HelloWorld`, I get:
```
Failed to find any OpenCL platforms.
Failed to create OpenCL context.
```

**Comment by reger-men** [comment]
I reinstall ubuntu 16.04 and then I install ROCm. Now it work.
