### ISSUE TITLE
User 1001

### ISSUE THREAD

**Issue by VincentSC** [RadeonOpenCompute/ROCm#24]
On Ubuntu 14.04.5 /opt/rocm was owned by user root, but the rest was a non-existing user 1001:1001. As I prefer not to build as root, I'd prefer you create a group "rocm" where I can add the users who should get access to ROCm.

**Comment by jedwards-AMD** [comment]
The user 1001:1001 user issue has been corrected. We are considering your request to add a rocm user, but this may not be available until ROCm 1.3.
