### ISSUE TITLE
Arch Linux Compile

### ISSUE THREAD

**Issue by bladepif** [RadeonOpenCompute/ROCm#245]
Hi, can someone help me compile this under Arch linux, Thanks

**Comment by ubombi** [comment]
I also tried to install but wasted to much time.
Because I couldn't find any complete instructions in READMEs yet.

Would be nice, if you'll maintain `PKGBUILD` files or [AUR](https://aur.archlinux.org/register/) packages. With one `rocm` metapackage which will install full ROCm platform

**Comment by jlgreathouse** [comment]
Looking through our backlog of issues -- this appears to be a duplicate of #294. I understand that this one was opened earlier, but there are more posts over there. So I'm going to close this one and say that the feature request for Arch support should be centralized into #294.
