### ISSUE TITLE
Testing on Ubuntu Mantic 23.10 nightly?

### ISSUE THREAD

**Issue by 2eQTu** [RadeonOpenCompute/ROCm#2453]
Does ROCm have any documentation or pre-release packages to assist in testing under Ubuntu daily images?  (in this case Mantic)

I've got a 7800XT and to the extent I can help find any basic rough edges happy to try things.

**Comment by saadrahim** [comment]
Sorry, we do not have pre-release packages available.

**Comment by johnnynunez** [comment]
Wait for 24.04 in 2024
