### ISSUE TITLE
Praise for ROCm

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#246]
This is not a valid bug :) -- I just want to point out a few things that I personally like about ROCm.

1. Performance: in my observation, the compiler already does a significantly better job at optimization compared to AMDGPU-Pro. My code is about 15% faster on ROCm "just like that". That's great.

2. Inline ASM: being able to insert GCN assembler in the middle of OpenCL source is very powerful, and empowering. You won't believe how much I missed this in the past!

3. Having an actual line of communication with the ROCm team, allowing to report bugs, ask questions etc. Don't be mislead by the high number of public bugs on ROCm compared to AMDGPU-Pro -- in my case it was just that I found no way (or no easy enough way) to report the AMDGPU-Pro bugs.

4. Open-source, github: the open aspect is very important to me; I'm still looking forward to when I'll be able to build and deploy the compiler myself, though.

So, keep up the good work and the speed of improvement!

**Comment by emerth** [comment]
Why I like ROCm in one word: C++.

**Comment by AirSquirrels** [comment]
ROCm was used to provide a record speed verification of the newest largest known prime number using preda’s gpuOwl software on a Vega GPU. Expect the press release imminently. Great job to the ROCm team.

**Comment by preda** [comment]
This issues is getting old, time to close IMO and start a new "praise for 2.0" as needed.
