### ISSUE TITLE
rocminfo problem?

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#249]
Ubuntu 16.04.3, ROCm 1.6-180.
When I try the "rocminfo" from the /opt/rocm/bin/, I always get an error message:

$ /opt/rocm/bin/rocminfo 
Ill-formed call, no flag or invalid flags passed.

(but everything else seems to work fine).

**Comment by gstoner** [comment]
This is being replaced with new version in 1.7,  with expanded fictionality.  This was tool originally to just get the id for the GPU for compiler,  it moving to proper tool to tell you info about your system and how ROCm is configured.

You can see it here.   This tool fictionality is moving into compiler tool.

https://github.com/RadeonOpenCompute/rocminfo

G

On Nov 11, 2017, at 5:33 AM, Mihai Preda <notifications@github.com> wrote:


Ubuntu 16.04.3, ROCm 1.6-180.
When I try the "rocminfo" from the /opt/rocm/bin/, I always get an error message:

$ /opt/rocm/bin/rocminfo
Ill-formed call, no flag or invalid flags passed.

(but everything else seems to work fine).

**Comment by preda** [comment]
OK, thanks, may I close it then?
