### ISSUE TITLE
Understanding vector ALU utilization

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#250]
What is the best tool to analyze VALU utilization in an OpenCL kernel ?  

In my kernel, each work item `i` performs `Ni` passes through its data buffer `Bi`.  So, two work items may diverge while each item is running through its pass, and they also may diverge when they have a different number of passes, when the work item with fewer passes is waiting for the others to finish. 

I would like to understand what factor hurts the utilization the most.

**Comment by preda** [comment]
You could benchmark or run comparative performance analysis. The results may not be portable though (across hardware, or across compiler versions with different optimizations).
