### ISSUE TITLE
When rocm6.0?

### ISSUE THREAD

**Issue by johnnynunez** [RadeonOpenCompute/ROCm#2519]
Support rdna3? 
https://github.com/ROCmSoftwarePlatform/MIOpen/milestone/20

**Comment by erkinalp** [comment]
Should offer support for Ubuntu 22.04 from get go.

**Comment by dsclear-amd** [comment]
The milestones page at https://github.com/ROCmSoftwarePlatform/MIOpen/milestones suggests that ROCm 6.0 is targeted for October 18, 2023.

**Comment by pramenku** [comment]
https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html

RDNA3 support is already enabled. Refer the above GPU support page.
