### ISSUE TITLE
ROCm in the news

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#252]
https://www.anandtech.com/show/12032/amd-announces-wider-epyc-availability-and-rocm-17-with-tensorflow-support

**Comment by gstoner** [comment]
Should have been Tensorflow get MultiGPU support,  ROCm has alway had multigpu support    We working on RCCL.

On Nov 13, 2017, at 6:23 AM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


https://www.anandtech.com/show/12032/amd-announces-wider-epyc-availability-and-rocm-17-with-tensorflow-support

**Comment by boxerab** [comment]
Yes. Usually Anandtech quality is good.  What is RCCL ?
Since they mention 1.7, can you share an ETA for this release ?

**Comment by gstoner** [comment]
Thanks.

Yes. We did scratch re-write MPI/NCCL like Communication Primitive library.

Greg

On Nov 13, 2017, at 7:22 AM, Jason Newton <notifications@github.com<mailto:notifications@github.com>> wrote:


I think anandtech is relatively good to an abysmally bad industry but the homework the benchmark industry puts in doesn't cut it anymore and they're wrong very often... especially on details like this. Which is to say I don't trust anandtech much on CPUs or especially GPUs anymore either.

RCCL.... is that pronounced rickle?

**Comment by oscarbg** [comment]
So ROCM 1.7 is what brings finally also full OpenCL 2.1 support (SPIR-V included) to AMD GPUs under Linux?
also shipped kernel will be updated from current 4.11?
thanks..

**Comment by gstoner** [comment]
@oscarbg  This is early access release of 2.1,  last minute we had to pull pipes and Device enqueue the resource for this feature we pulled on a customer project.   Also, there is no SPIR-V  support part of this release, it is an optional spec for 2.1.    2.1 capability will be final in Q1 2018.

**Comment by mirh** [comment]
Last time I [checked](https://www.khronos.org/registry/OpenCL/specs/opencl-2.1.pdf) SPIR-V as an imperative requirement of core opencl 2.1 was all over the place in spec.

**Comment by oscarbg** [comment]
@mirh I was thinking the same but was afarid to say so as I was not sure enough..

**Comment by jimdowling** [comment]
@gstoner  - looking forward to this. How different is your implementation to the Baidu Collectives library now in contrib in TensorFlow? And what about NCCL2? Will you support Ring-AllReduce with GPU-aware topology (that is, places devices on the same host adjacent to one another in the Ring so that there is only one input n/w link and one output n/w link in the Ring for each host) ?
