### ISSUE TITLE
ROCm 1.7 Availability?

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#254]
Is ROCm 1.7 available for install?

**Comment by madscientist159** [comment]
Still waiting it seems.  Wonder when it's going to drop?  Have idle Vega card that I'm increasingly considering sending back...

**Comment by briansp2020** [comment]
November is almost over... I'd like to know when ROCm 1.7 will be released and whether it will have TensorFlow 1.4. If I can't get TF 1.4 working on my GPU soon, I may have to buy an NVidia GPU...

BTW, can I have both AMD GPU and NVidia GPU working in a single system? If I get an NVidia GPU, I'd like to still have AMD GPU in the same machine so I can do some performance comparison.

**Comment by pacxx** [comment]
For running AMD GPUs alongside Nvidia GPUs that is possible. The Nvidia kernel modules compile well with the ROCm enabled kernel.

**Comment by gstoner** [comment]
We are still working on some DKMS package issue, this our first transition over to DKMS we double checking the functionality.

**Comment by emerth** [comment]
Thanks, Greg! I'm looking forward to it! Double check it by all means, can't be too careful!

**Comment by emerth** [comment]
@Briansp2020  - in a nutshell, install ROCm per instructions then install CUDA. You will still have to deal with getting rid of nouveau - do that after installing ROCm.
I have this scheme running on an Ubuntu 16.04 box with an RX470 and a GTX970.

**Comment by boxerab** [comment]
@emerth may I ask how perf compares between 470 and 970 ?

**Comment by emerth** [comment]
@boxerab I've no information on that: it's not what I've been doing.

**Comment by madscientist159** [comment]
@gstoner A beta / dev branch with the code would definitely be nice.  We've already sent one Vega back and are delaying any further potential purchases into next year over the missing drivers.

**Comment by alexanderkjeldaas** [comment]
Any update on this?

**Comment by hwchong** [comment]
Tempted to reference the Reddit joke about AMD hardware being like fine wine.....

Don't expect to buy AMD GPUs to use today. Maybe tomorrow, but not today.

**Comment by emerth** [comment]
@hwchong et al - have patience, they are doing very good work, ROCm 1.6 is very good. I only asked the question in the first place because I read about 1.7being  described at a trading show. They never said it was being released, just it was being prepared.
