### ISSUE TITLE
Update base kernel?

### ISSUE THREAD

**Issue by madscientist159** [RadeonOpenCompute/ROCm#256]
Would it be possible to get the ROCK kernel updated to use Linux 4.13 as its base?  We need to use POWER9 with ROCm due to the PCIe atomic support, but Linux 4.11 is unusable on our POWER9 boxes.

Thanks!

**Comment by gstoner** [comment]
Next release moves to 4.13 Linux Kerenl

**Comment by madscientist159** [comment]
@gstoner Excellent!  We had to put the Vega card into an old Windows PC to get OpenCL, and it is overall a very poor experience compared to our normal Linux systems (bad enough that without this pending Linux support we'd give up on Vega entirely for the time being).

**Comment by briansp2020** [comment]
@gstoner 
When will ROCm 1.7 come out...
Give it to me now...

BTW, will you release TensorFlow 1.4 along with ROCm 1.7? If not when do you think you will have 1.4?

**Comment by delbabrour** [comment]
+1
Update to at least linux kernel 4.14 or 4.15 rc1 to fix the issue with most Mobo like MSI z270-A Pro or H110 or even h81 i got all errors when booting with custom vBios GPUs RX570

it is identified as bug in linux kernel and need quick update 

Kernel bug  here https://bugs.freedesktop.org/show_bug.cgi?id=100443

**Comment by blisskidd** [comment]
Can we get something for *CURRENT* kernels please?
I'm on 4.14.11.
I can do 4.15 if that helps.
4.13 = dead now.

**Comment by Cyclic3** [comment]
Has there been any movement on this?

**Comment by shimmervoid** [comment]
Kernel 4.16 is here, maybe some movement here?

**Comment by kentrussell** [comment]
The 1.9 release is based on 4.15, so this should help. Let us know (code available on github, apt repo should be updated later today)

**Comment by jlgreathouse** [comment]
ROCm 1.9.0 should with upstream kernels now, so I'm going to close this particular issue. If other problems arise, please start an issue for them specifically. Thanks.
