### ISSUE TITLE
how can I run clinfo after installed rocm, rocm-opencl and rocm-opencl-dev?

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/ROCm#258]
hello. I would be glad if you gave me some advices.
the environment is Ubuntu 16.04.3

I installed rocm and successfully run the sample code of OpenCL provided by this repository.

**Comment by preda** [comment]
/opt/rocm/opencl/bin/x86_64/clinfo

**Comment by smithakihide** [comment]
thank you.
