### ISSUE TITLE
amdgpu 0000:04:00.0: kfd not supported on this ASIC?

### ISSUE THREAD

**Issue by oscarbg** [RadeonOpenCompute/ROCm#259]
Hi,
I'm using propietary AMDGPU Pro with kernel 4.10 support both ROCM OpenCL and included OpenCL binary and it works..
but in Kernel 4.15git I see with dmesg:
[    3.044705] amdgpu 0000:04:00.0: kfd not supported on this ASIC

and of course OpenCL ROCM binaries doesn't work..

on AMDGPU Pro with it's kernel modifications I got something like:
kfd successfully initialized..

of course with Kernel 4.15 git OpenGL and RADV Vulkan is working correctly only fails compute support.. and I think it's because it's kfd that is failing..

seems a regression..

maybe because I have a Nvidia GPU on the system altough not using any driver (nouveau or Nvidia propietary)

lspci get:

01:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GM204 High Definition Audio Controller (rev a1)
02:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1470 (rev c1)
03:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1471
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega [Radeon RX Vega] (rev c1)

**Comment by alexanderkjeldaas** [comment]
I'm getting the same, and I don't have any other GPU.

**Comment by alexanderkjeldaas** [comment]
Same on 4.15rc2

**Comment by alexanderkjeldaas** [comment]
But kfd doesn't work with VEGA on mainline I think.  Not sure if it's a regression as it's documented in https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver#package-contents that the kfd APIs (and semantics, and probably support) are different.

**Comment by oscarbg** [comment]
thanks.. 
hope in next few kernel releases gets sorted out..

**Comment by alexanderkjeldaas** [comment]
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver is the preferred kernel.  It's 4.11 on master and 4.13 on the "next" branch.

**Comment by oscarbg** [comment]
Wait.. there is no “next” branch on this repo.. at least public branch.. should be soon?

**Comment by nerdoc** [comment]
Using Linxu 4.15rc5, exactly the same issue. I somehow had a system with Mesa 7.3 from [Paulo Dias' PPA](https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa), the ubuntu-swat-x stack and the newest amdgpu drivers (17.50), and at least clinfo showed me 1 platform (but 0 devices). But this can't be an issue of the 5.15 kernel, as that one worked at least a bit.
But i wish that this would work yet.

**Comment by gstoner** [comment]
Guy, currently the Linux KFD team is still upstreaming all the capabilities we need for ROCm in the main  Linux kernel.  right if you want to use generic Linux kernel from here https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver   you need to wait up right now looks like 4.17 Linux kernel since not all the bit have made it into 4.16 next yet.

**Comment by nerdoc** [comment]
okay - it's just that THIS bit of information you just gave is nearly impossible do find in official support forume/google/etc. >>Just install amdgpu/rocm and you have a working opencl platform<< just is wrong. Thanks for sharing... to non-technical people like me... ;-)

**Comment by gstoner** [comment]
The official install for ROCm right now is for Ubuntu 16.04 at repo.radeon.com, with the shift to DKMS based install just normal Ubuntu 16.04 release which has a 4.4 Linux kernel. For the cleanest install, i recommend a clean install of Ubuntu 16.04 server and follow the instructions at. https://rocm.github.io/ROCmInstall.html     

Now if you want to build your own kernel you need to get the bits from https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver    It is not for beginning Linux kernel programmer.
