### ISSUE TITLE
ROCm 1.6 on Radeon RX 460

### ISSUE THREAD

**Issue by amansinha-sw** [RadeonOpenCompute/ROCm#264]
I have been trying to install ROCm on myRadeon RX 460 device, but I am finding Number of platforms                               0 in clinfo. 
dnnroot@ubuntu:~$ clinfo
Number of platforms                               0

dnnroot@ubuntu:~$ lspci | grep -i --color 'vga'
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67ef (rev cf)

dnnroot@ubuntu:~$ dpkg --get-selections |grep opencl
ocl-icd-libopencl1:amd64                        install
ocl-icd-opencl-dev:amd64                        install
opencl-headers                                  install
rocm-opencl                                     install
rocm-opencl-dev                                 install

Please help me with this.

**Comment by briansp2020** [comment]
what CPU are you using?

**Comment by smithakihide** [comment]
Although I am not a professional of ROCm.
you should write your environment, for example, Distribution, its version. if there are these information, you can get more helpful suggestion.

I have asked where clinfo of ROCm is  in the past.
[https://github.com/RadeonOpenCompute/ROCm/issues/258](https://github.com/RadeonOpenCompute/ROCm/issues/258)

clinfo of ROCm is in the path of /opt/rocm/opencl/bin/x86_64/clinfo.
I think, you cannot run clinfo with only typing the program name on bash on ROCm.

I guess you have installed another GPU driver before ROCm.  
have you done?

**Comment by amansinha-sw** [comment]
@briansp2020 It is a  Intel(R) Core(TM) i5 CPU. Please let me know if you need further info.

**Comment by amansinha-sw** [comment]
@smithakihide I tried in the path of /opt/rocm/opencl/bin/x86_64/clinfo too and had the below result:

dnnroot@ubuntu:~$ /opt/rocm/opencl/bin/x86_64/clinfo
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

I also haven'tinstalled AMDGPU-PRO drivers before-hand, as seen from the below output for dpkg -l amdgpu-pro:

dnnroot@ubuntu:~$ dpkg -l amdgpu-pro
dpkg-query: no packages found matching amdgpu-pro

I tried the installation on system with below specifications:

dnnroot@ubuntu:~$ sudo lshw -C processor
[sudo] password for dnnroot:
  *-cpu
       description: CPU
       product: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
       vendor: Intel Corp.
       physical id: 4
       bus info: cpu@0
       version: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
       serial: To Be Filled By O.E.M.
       slot: LGA1156
       size: 1200MHz
       capacity: 3800MHz
       width: 64 bits
       clock: 133MHz

dnnroot@ubuntu:~$ uname -a
Linux ubuntu 4.11.0-kfd-compute-rocm-rel-1.6-180 #1 SMP Tue Oct 10 08:15:38 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

dnnroot@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04

Please suggest if you need more information.

**Comment by briansp2020** [comment]
i5 CPU 750 is too old. You should check out the supported hardware list (https://rocm.github.io/install.html). You need Haswell family or newer if you are using Intel processors. If you want to get AMD systems, you need Ryzen.

**Comment by smithakihide** [comment]
although I wondered why the output "clinfo" differ from "/opt/rocm/opencl/bin/x86_64/clinfo", I also think core i5 750 is too old.  maybe it would work, I am not sure because I could not test on the environment.

if you continue to test on that environment, I recommend to make sure the actual path of "clinfo" first. this would be different from "/opt/rocm/opencl/bin/x86_64/clinfo".

note that the environment in core i5 4670 and RX 580 worked well for me.

**Comment by gstoner** [comment]
@amansinha-sw  They are correct, this processor is not supported by ROCm You need Core i3, I5, or I7  that based Haswell base core design or newer.  Please remember you need to put the GPU on PCIe sockets that are PCIe Generation 3 off the main CPU socket.  Since they support PCIe Atomics - aka Atomic Completors
