### ISSUE TITLE
[Issue]: Broken Windows ROCm download link

### ISSUE THREAD

**Issue by Cyberhan123** [RadeonOpenCompute/ROCm#2653]
### Problem Description

![image](https://github.com/RadeonOpenCompute/ROCm/assets/38837039/a68d45c1-de06-446c-a740-c33849931ef8)

 When I click on the download page, it will jump to the home page. https://www.amd.com/en.html

### Operating System

Windows 11

### CPU

7900XTX

### GPU

7900XTX

### ROCm Version

5.7.0

### Output of /opt/rocm/bin/rocminfo --support

NONE

**Comment by 108806** [comment]
Some ppl say that the entire project is dropped, I can confirm that it fails to install on the latest stable drivers, will see what they going to now because this is pretty bad.

**Comment by Cyberhan123** [comment]
Now has fixed
