### ISSUE TITLE
Stoney ridge support

### ISSUE THREAD

**Issue by procedural** [RadeonOpenCompute/ROCm#268]
As Carrizo and [Bristol Ridge](https://github.com/RadeonOpenCompute/ROCm/issues/122) are supported now, what about the same GCN 3rd generation [Stoney Ridge](https://en.wikipedia.org/wiki/Graphics_Core_Next#GCN_3rd_Generation_(Volcanic_Islands)) APUs? WIll they be supported too?

Thanks!

**Comment by procedural** [comment]
[This line](https://github.com/RadeonOpenCompute/ROCm/issues/122#issuecomment-304515796) is interesting:

```
The agent name is gfx801.
```
So Bristol ridge APUs have the same `gfx801` code as Carrizo? I guess all three APUs are the same variations of Carrizo?

**Comment by smithakihide** [comment]
I have seen Carrizo and Bristol Ridge are not supported on ROCm. 
you could read README.md once again.

**Comment by gstoner** [comment]
I know people who had  Bristol Ridge system working with ROCm 1.6.4.  Which you can get on the archive.    The issue for our team is just testing matrix we have a small team so we have to stay focused

**Comment by ROCmSupport** [comment]
Thanks @procedural 
As its very old issue, and no updates for the last 2 years, this issue is going to be closed.
Request to open a new ticket, if you found any.
Thank you.
