### ISSUE TITLE
Cannot install ROCm on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by Barni91** [RadeonOpenCompute/ROCm#277]
Hello,

When trying to install ROCm with the **sudo apt-get install rocm rocm-opencl-dev** command I'm receiving the following error:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rocm

Repo is added, every command was ran successfully.

A week ago this command ran just fine on another rig. What should be done?

**Comment by boxerab** [comment]
Package is now called `rocm-dkms`.  You should review the project README, as the instructions have changed.

**Comment by Barni91** [comment]
I tried this command as well, but I don't see any increase in mining speed. How can I check if ROCm was installed properly?

**Comment by gstoner** [comment]
Did you follow the instructions   https://rocm.github.io/ROCmInstall.html 

With move to upstreaming the KFD driver and the support of DKMS, for all Console aka headless user, you will need to add all your users to the ‘video” group by setting the Unix permissions

sudo usermod -a -G video <username>

Then reboot the system

**Comment by Barni91** [comment]
I tried your suggestions, but now, none of my GPU's are recognized in claymore. Does ROCm install some GPU drivers?

**Comment by gstoner** [comment]
Are you mixing driver,  Yes ROCm 1.7  install a driver if you had AMDGPU driver on your system you have an issue.   You have to install the driver follow these instructions https://rocm.github.io/ROCmInstall.html

**Comment by gstoner** [comment]
You need to run this now 

sudo apt-get update
sudo apt-get install rocm-dkms rocm-opencl-dev
```permisions

With move to upstreaming the KFD driver and the support of DKMS, for all Console aka headless user, you will need to add all your users to the ‘video” group by setting the Unix permissions

```shell
sudo usermod -a -G video <username>

**Comment by Barni91** [comment]
I have tried your suggestions, but even on a clean install and after installing rocm my GPU's are not recognized.

With the original amd-gpu driver all my GPU's are showing up in Claymore.

What would you suggest to do next?

**Comment by Barni91** [comment]
Is there any way to install ROCm 1.6? With the 1.6 version we have several rigs working just fine.

**Comment by CultClassik** [comment]
Same issue, seems totally broken.  All of the docs are out of whack, say different things, say "we recommend doing X at this link" and it links back to itself.  What's going on with this stuff?

**Comment by Barni91** [comment]
I would like an option to install older versions as well. There is not much sense forcing users to the latest version when this is not working. 

I'm not saying that it is broken or something, but as you can see there are others who encounter the same issues as myself.

**Comment by gstoner** [comment]
I am sorry you're having install issues.  We archive all releases on repo.radeon.com.  In the archive directory.

Also, the direction is consistent. But if need more straightforward direction goes to rock.github.com click on documentation tab and you see a link for install instruction.    Also, this is DKMS install which you need to make sure old components are not installed. If your working from anything other then ubuntu 16.04 it's. It is Not tested

We tested the release on large number of system

Ps, we not forcing you to upgrade you choose too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Barni91** [comment]
Thank you gstoner for the archive. Any steps on how to install it?

**Comment by gstoner** [comment]
@CultClassik   To follow ROCm 1.7 follow these instruction https://rocm.github.io/ROCmInstall.html   Again we have many people who have installed it.  

The command use to be 
sudo apt-get install rocm-dkms rocm-opencl-dev
It is now this to install rocm.   Note this is DKMS,  did you check you have the development tool installed since you need this to build the kernel 

sudo apt-get install rocm-dkms rocm-opencl-dev


With move to upstreaming the KFD driver and the support of DKMS, for all Console aka headless user, you will need to add all your users to the ‘video” group by setting the Unix permissions

```shell
sudo usermod -a -G video <username>

**Comment by gstoner** [comment]
You have to download apt_1.6.4.tar.bz2  

Then you have add the package to your package manager 
sudo dpkg -i <name of package>.deb

sudo apt

For 1.6.4 you use the old commands once the packages are added to local package manager in Ubuntu 
sudo apt-get update
sudo apt-get install rocm rocm-opencl-dev

**Comment by gstoner** [comment]
@Barni91  What CPU are you using?

**Comment by gstoner** [comment]
I now realize some people typing in <username> this was place holder for you to replace with your username  here is better command to execute to simplify this, I changed the instructions as well to this 

sudo usermod -a -G video $LOGNAME
