### ISSUE TITLE
Potential rocm 1.7  performance issue in HCC 

### ISSUE THREAD

**Issue by JiniusDnn** [RadeonOpenCompute/ROCm#279]

**Comment by JiniusDnn** [comment]
rocm 1.7   regression bug  with performance down 20% on some mem algo.

after I upgrade to 1.7,    my app recompiled  and found performance lower to 80% of original rocm1.6 system.

There are some upgrade on hcc compiler,    I am pretty sure the regression lower performance is from some of the commits.

**Comment by gstoner** [comment]
Can you isolate it little more than this,  we have nothing to go on to looking into this do you have sample kerne aka test casel to show the issue.    We have not observed performance drops on the  AMD EPYC and Intel Xeon system with MI25 we work on.

**Comment by gstoner** [comment]
Also what hardware are you on Processor, GPU etc.

**Comment by JiniusDnn** [comment]
Sorry for the delayed reply due to this holiday season.  

The hardware is vega 64.

The kernel I use have more than 8K LOC,  I 'll try to simplify it to a test case to demo this regression issue if I can.
