### ISSUE TITLE
rocm 1.7 could not find RX 580s

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/ROCm#283]
I installed ubuntu 16.04.3
then I installed rocm following to the instructions of rocm1.7

here is the commands I executed to make sure there are 2 RX 580s on this system.
```
$lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev c7)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev e7)
```

then I executed some code uses namespace of hc and got the below output
```
$ ./exe
There is no device can be used to do the computation
```

**Comment by gstoner** [comment]
Configure 
Ensure that your user account is a member of the "video" group prior to using the ROCm driver. You can find which groups you are a member of with the following command:

groups
           
To add yourself to the video group you will need the sudo password and can use the following command:

sudo usermod -a -G video $LOGNAME 

You will need to log out and in again to activate this change.

**Comment by smithakihide** [comment]
I am sorry to let you create the duplicated answer.  please refer to [https://github.com/RadeonOpenCompute/ROCm/issues/284](https://github.com/RadeonOpenCompute/ROCm/issues/284)

**Comment by gstoner** [comment]
Ok I think I found the problem for HCC and HIP,   in rocminfo they did not enumerate 67df 

Replace rocm_agent_enumerator file with this one   I fixed this file    https://github.com/RadeonOpenCompute/rocminfo/blob/master/rocm_agent_enumerator

**Comment by streamhsa** [comment]
Hi smithakihide,
can you please run the below command and then check.
sudo chmod 777 /dev/dri/*

**Comment by smithakihide** [comment]
thank you to reply.
here is the result.
```
nico@nico:~$ sudo chmod 777 /dev/dri*
chmod: cannot access '/dev/dri*': No such file or directory
```

**Comment by smithakihide** [comment]
I will try once again when I go back to my country next year. So please wait for a while.

**Comment by gstoner** [comment]
One other thing other have found you might need sudo apt-get install libnuma-dev

**Comment by pacxx** [comment]
We have maybe an related issue with rocm 1.7. 

With rocm 1.6 we had no issus with our AMD FirePro W9100, however, rocm 1.7 does not list the GPU.

`03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT GL [FirePro W9100]`

My user is in the video group and SecureBoot is disabled. 

lsmod reports that all amd kernel modules are loaded. clinfo reports 0 devices and hip executables report that there is no device to do the computation.

Also we installed libnuma-dev without any effects.

**Comment by pacxx** [comment]
FWIW: dmesg shows this during system boot: 

```
[    1.728878] [drm] amdgpu kernel modesetting enabled.
[    1.729764] amdkfd: Unknown symbol amd_iommu_unbind_pasid (err 0)
[    1.729786] amdkfd: Unknown symbol amd_iommu_set_invalidate_ctx_cb (err 0)
[    1.729824] amdkfd: Unknown symbol amd_iommu_free_device (err 0)
[    1.729829] amdkfd: Unknown symbol amd_iommu_init_device (err 0)
[    1.729836] amdkfd: Unknown symbol amd_iommu_set_invalid_ppr_cb (err 0)
[    1.729848] amdkfd: Unknown symbol amd_iommu_bind_pasid (err 0)
```
Kernel version is: 4.13.0-21-generic

**Comment by pacxx** [comment]
Fixed myproblem by switching from` linux-image-generic-edge` to `linux-image-generic-hwe-16.04-edge` kernel packages.

**Comment by seaside1** [comment]
I'm having the same problem.

Have a ASUS Z270P, I have 2 GPUs 1 is detected correctly and working and not the other one.
I can see this in the dmesg:
[    4.702708] kfd kfd: skipped device 1002:67df, PCI rejects atomics

I have enabled PCI 3.0 support on the MB and running the hwe-kernel.

Anyone got an idea?

Would really like to use this driver since it performs bettar then the amdgpu one.

BR

**Comment by gstoner** [comment]
@smithakihide Can you try the beta http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2  It supports 4.13 Linux kernel
