### ISSUE TITLE
eigen is spelled incorrectly

### ISSUE THREAD

**Issue by hungrymonkey** [RadeonOpenCompute/ROCm#285]
https://rocm.github.io/packages.html

as shown in the link.

Egien C++ Math Library with HIP Based GPU Acceleration

should be

Eigen C++ Math Library with HIP Based GPU Acceleration

I would create a pull request, but I do not where is the documentation repo

**Comment by briansp2020** [comment]
I found the repo.
https://github.com/ROCm/ROCm.github.io

**Comment by hungrymonkey** [comment]
https://github.com/ROCm/ROCm.github.io/pull/7
