### ISSUE TITLE
FANTASTIC!

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#291]
I just installed ROCm 1.7 on Ubuntu 16.04 server, followed by ubuntu-desktop meta package. I booted into X running at 4K, and I'm running the HIP-Examples-master tests in an xterm!

Great work, AMD! Thanks very much!

**Comment by emerth** [comment]
Just wanted to say...

**Comment by ws0zzg4569** [comment]
I encounter a python exception when running the example except the MINST, did you modify the tf example code ?

**Comment by emerth** [comment]
Hi George,I did not modify anything‎ in the examples or in hip. The machine was already being used for C++ and Python development, so some obscure  dependency might have been satisified.Do you have a log of the compile and error?Cheers,Eric                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: GeorgeLee_ZhongqiSent: Wednesday, January 3, 2018 7:48 PMTo: RadeonOpenCompute/ROCmReply To: RadeonOpenCompute/ROCmCc: Eric Merth; State changeSubject: Re: [RadeonOpenCompute/ROCm] FANTASTIC! (#291)I encounter a python exception when running the example except the MINST, did you modify the tf example code ?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RadeonOpenCompute/ROCm","title":"RadeonOpenCompute/ROCm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RadeonOpenCompute/ROCm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ws0zzg4569 in #291: I encounter a python exception when running the example except the MINST, did you modify the tf example code ?"}],"action":{"name":"View Issue","url":"https://github.com/RadeonOpenCompute/ROCm/issues/291#issuecomment-355185988"}}}
