### ISSUE TITLE
OpenCL 2.0 device side enqueue

### ISSUE THREAD

**Issue by Moading** [RadeonOpenCompute/ROCm#299]
Hi,
I would like to request the addition of the device side enqueue feature of OpenCL 2.0 as soon as possible. Device side enqueue simplifies the implementation of many algorithms and it is the last thing that is missing to make ROCM complete for me. I encourage other users of ROCM to comment here, to point out the importance of that feature.

Greetings,
Moading

**Comment by gstoner** [comment]
We have Device Side Enqueue  and PIpes underdevelopment for ROCm,  they should be out in the 1.8 by end of Q1/18

**Comment by Moading** [comment]
Hi,
I was just wondering when device side enqueue will be available. Can you give me an estimate?

**Comment by blueberry** [comment]
This is (I hope) the last feature I'm waiting for to be able to try out ROCm instead of closed source drivers. RX Vega 64 sits useless for now, and I have to use old R9 290X :(

I know: first world problems. I don't live in a first world country, though :)
