### ISSUE TITLE
Ethminer not runnning without sudo permissions.

### ISSUE THREAD

**Issue by Xuramaz** [RadeonOpenCompute/ROCm#301]
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: gfx701(OpenCL 1.2 )
DAG  20:04:06.781|ethminer  DAG Generation Failure. Reason: Permission denied
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::ExternalFunctionFailure>'
  what():  std::exception
Aborted (core dumped)

I am running ubuntu 16.04.3, with kernel 4.8.17. When ethminer tries to initialize the gpu, this output occurs, then the program aborts. So far not a great deal, as running ethminer as root with sudo works just fine.
Also great job with this new release of ROCm! Before I got 6mhs on 1.6, but now (At a glance while it runs), I seem to be getting a somewhat better hashrate than amdgpu-pro 17.40!

**Comment by Xuramaz** [comment]
It appears to be no longer doing this

**Comment by briansp2020** [comment]
Did you put the user account into video group?

> sudo usermod -a -G video $LOGNAME 

It sounds like a permission issue. See the install instructions at https://github.com/RadeonOpenCompute/ROCm

**Comment by Xuramaz** [comment]
@briansp2020 I've done everything in the install instruction, and I've placed myself into the video group.
Is it possible though that the video group isn't functioning properly? I had myself in the video group long before installing rocm, as I had myself in it back when I had to use amdgpu-pro drivers.
