### ISSUE TITLE
Is it plan to upload rocm into Debian ?

### ISSUE THREAD

**Issue by picca** [RadeonOpenCompute/ROCm#304]
Hello, it would be great if out of the box peoples could have rocm uploaded into Debian.

So is it plan ?

Thanks

Frederic

**Comment by preda** [comment]
In my case, ROCm 1.7 with OpenCL works fine on Ubuntu 17.10 (which, note, is not the *supported* 16.04). So maybe you could try and see.

**Comment by picca** [comment]
Hello, great, but my question was more about an upload of rocm into Debian main.

**Comment by dblueman** [comment]
rocm-dkms builds fine against Debian 9.4's 4.9 kernel; I get full OpenCL support.

It looks like the last parts needed for upstream kernel support will be upstreamed in 4.17, so the question will be on integrating the userspace.

+1 for ROCm userspace packages in the Debian repos.

**Comment by valeriob01** [comment]
Some issues for Debianization:
1. gpu detection for the installer, to know when to install ROCm
2. requires the package firmware-amd-graphics from the non-free repository

**Comment by mmuehlenhoff** [comment]
The http://repo.radeon.com/rocm/apt/debian/ repository currently only ships the debs, could you also publish the Debian source packages to allow custom builds?

**Comment by ROCmSupport** [comment]
Thanks @picca 
As its very old issue, and no updates for the last 2 years, this issue is going to be closed.
Request to open a new ticket, if you found any.
Thank you.
