### ISSUE TITLE
Unable to locate package rocm, but can install rocm-opencl

### ISSUE THREAD

**Issue by RaymonSHan** [RadeonOpenCompute/ROCm#311]
I add deb, updata & upgrade, following https://rocm.github.io/install.html 
but 

raymon@raymonR7: ~ $ sudo apt-get install rocm-opencl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
rocm-opencl is already the newest version (1.2.0-2017121952).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
raymon@raymonR7:~$ 

raymon@raymonR7: ~ $ sudo apt-get install rocm
[sudo] password for raymon: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rocm

**Comment by gstoner** [comment]
What Distro and which version are you working on.   Also is this being installed on AMDGPUpro driver or you following the install instruction for installing the ROCm driver.   Since the package here are for the ROCm driver

**Comment by gstoner** [comment]
Normally you do sudo apt-get install rocm rocm-opencl-dev at the same time when you do install.

**Comment by RaymonSHan** [comment]
ub16.04.3
I have uninstalled AMDGPU driver, and installed ROCm drvier.

the things happed in this way.
after deb & update, 
sudo apt-get install rocm                         .... it is OK
sudo apt-get install rocm-opencl            ....E: Unable to locate package rocm-opencl

but when i tab the command apt-get remove rocm,    the rocm-opencl is list, while rocm is not
so i
sudo apt-get remove rocm                          ....E: Unable to locate package rocm
sudo apt-get remove rocm-opencl             .... it work , removed

reboot, deb and update again following rocm.github.io/install.html
sudo apt-get install rocm                         ....E: Unable to locate package rocm
sudo apt-get install rocm-opencl            ... it is OK.

i do not know the struct of deb server, but i can install any packet list in
http://repo.radeon.com/rocm/apt/debian/pool/main/r/
but there are not rocm

**Comment by RaymonSHan** [comment]
Maybe it is not the right way, but i almost finish it in following way.

following wiki of rocm , install rocm_dkms and rocm_opencl.  then install AMDGPU-pro. 
i know, it is not the right way, but my hipconfig report hcc & my opencl program is OK after this.

now the only thing left is i meet 'error while loading shared libraries: libCXLActivityLogger.so: cannot open shared object file: No such file or directory"

i found that file in rocm repo, the only thing is which path should i place it.
THANKS

**Comment by ArlasJ** [comment]
Hey RaymonSHan,

I got the same error. Can you help me please with that?
libCXLActivityLogger.so

**Comment by gstoner** [comment]
@RaymonSHan  Can you try the beta http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2  It support 4.13 Linux kernel
