### ISSUE TITLE
Rocm 1.7 cannot initiate multiple GPUS on Kernel 4.15

### ISSUE THREAD

**Issue by dfad44** [RadeonOpenCompute/ROCm#314]
I just installed kernel 4.15 on Ubuntu and could not get more than one Vega Frontier GPU online. 

Anyone with a workaround or more information would be helpful.

Thanks

**Comment by dfad44** [comment]
Seems this is a linux kernel issue and not ROCm.

**Comment by JorgeCeja** [comment]
@dfad44 have you gotten ROCm to work with kernel 4.15 with Vega frontier?

**Comment by gstoner** [comment]
The KCL in DKMS installer for AMDGPU driver that  ROCm 1.7 levering  is not compatible with 4.15,  The linux team is rebasing the driver now to move it forward.

On Feb 24, 2018, at 5:32 PM, Jorge C <notifications@github.com<mailto:notifications@github.com>> wrote:


@dfad44<https://github.com/dfad44> have you gotten ROCm to work with kernel 4.15 with Vega frontier?
