### ISSUE TITLE
No ROCm runtime is found

### ISSUE THREAD

**Issue by xalteropsx** [RadeonOpenCompute/ROCm#3152]
### Description of errors

X:\Nebula\dml\frontend\backend\env\Lib\site-packages\PyInstaller\building\build_main.py:199: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
No ROCm runtime is found, using ROCM_HOME='X:\amdgraphic\amd2025\hip\5.7'

how can i fix it?

**Comment by nartmada** [comment]
@xalteropsx, please fill out the Issue Template properly for this issue.  Thanks.
