### ISSUE TITLE
On AMD Ryzen CPU, OpenCL app runs faster when the CPU is not idle

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#319]
System: Ubuntu 17.10, CPU Ryzen 1700x, Rx Vega64, ROCm 1.7.

case 1: the CPU is idle, save for the OpenCL app which is not using much CPU.
case 2: the CPU is busy, used by mprime https://www.mersenne.org/download/ , which runs with nice -20.

In case 2 (CPU busy), the measured performance of the OpenCL app is about 1.5% faster than in case 1 (CPU idle).

**Comment by psteinb** [comment]
Just seeing this issue. Could the 1.5% be related to noise on the 
system? In other words, did you try repeated measurements (say 20) of 
the app for each case?

**Comment by preda** [comment]
Yes the measures are the total time of 100000 kernel runs. The effect is distinct and reproducible, doesn't look like noise.

I guess a possible explanation is that the CPU enters some sleep mode when not active, and takes a tiny bit of time to wake up when the app needs to do something, and this "wakeup" is not needed when the CPU is "hot".

**Comment by gstoner** [comment]
We found out why this has to do with how long it takes the CPU to come out of deep sleep,  we finding we even have manage C-state during transfers
