### ISSUE TITLE
Compile-away get_local_size() when workgroup size is known at compile time.

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#321]
(OpenCL, ROCm 1.7)

The workgroup size can be fixed at compile-time using: ```__attribute__((reqd_work_group_size(x, y, z)))```

The workgroup size can be queried at runtime using get_local_size().

Expected: for a kernel with compile-time fixed workgroup size, the get_local_size() should be compiled-away to the compile-time constant.

Observed: get_local_size() is kept, reading the size from SGPR values passed to the kernel at runtime.

**Comment by arsenm** [comment]
llvm r332771 implements this. It will be completely eliminated for CL1.2. For CL2.0 you also must specify -cl-uniform-work-group-size, or else only some of the loads will be eliminated.
