### ISSUE TITLE
https://rocm.github.io/install.html vs https://rocm.github.io/ROCmInstall.html 

### ISSUE THREAD

**Issue by Mandrewoid** [RadeonOpenCompute/ROCm#328]
What is the difference, which is correct, and why do both exist?
https://rocm.github.io/install.html
https://rocm.github.io/ROCmInstall.html

**Comment by gstoner** [comment]
Your looking at the source to the  website,  One document superseded the other this. Correct one   https://rocm.github.io/ROCmInstall.html

On Feb 4, 2018, at 10:52 AM, Mandrewoid <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the difference, which is correct, and why do both exist?
https://rocm.github.io/install.html
https://rocm.github.io/ROCmInstall.html

**Comment by Mandrewoid** [comment]
Thank you

**Comment by Mandrewoid** [comment]
@gstoner  I don't know if you changed something, but https://rocm.github.io/install.html is now 404. This is the first google search result for "Rocm website"  It is also still linked to from the "getting started" button

**Comment by gstoner** [comment]
fixed

**Comment by ferlix9o** [comment]
Hi @Mandrewoid 

i red that u manage to use the Vega FE with rocm, would u mind to tell me if it worked straight out of the box ? i am struggling a lot with it, my computecpp_info tell me is missing SPIR support.

sry for the intrusion ! but i would really appreciate a bit of help !

**Comment by gstoner** [comment]
@ferlix9o   SPIR is not supported on ROCm OpenCL currently.   Here is more info on SPIR https://www.khronos.org/spir/ The application you have is compiled to SPIR object.

**Comment by roycewilliams** [comment]
For future searchers, at this writing neither install.html nor ROCmInstall.html exist. Docs have been relocated to:

https://rocm.docs.amd.com/en/latest/

... with Linux-specific steps here:

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/
