### ISSUE TITLE
How to run from Docker container?

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCm#33]
Is it possible to install and run ROCm from a docker container provided that the correct kernel is loaded?

I am running Ubuntu 16.04 and would like to install and use ROCm from a 14.04 container. I've tried using kernel 4.8.0rc8 (built from yakkety master/next) and starting docker container with `docker run -it --device=/dev/kfd <image id>`. `/opt/rocm/bin/rocm-smi -a` sees the GPU. However, vector_copy fails with `Getting a gpu agent failed.`. Debugging shows that it doesn't find any agents.

**Comment by gstoner** [comment]
Yes.. https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/README.md


On Sep 27, 2016, at 2:18 AM, almson <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to install and run ROCm from a docker container provided that the correct kernel is loaded?

**Comment by almson** [comment]
Thank you. I got it to work after building and installing the correct kernel.
