### ISSUE TITLE
Compatibility of opencl binaries with Windows open CL AMD drivers.

### ISSUE THREAD

**Issue by Enoch72** [RadeonOpenCompute/ROCm#332]
It's not clear if a compiled, then exported OpenCL binary in ROCm enviroment  is compatible with the latest OpenCL AMD Windows drivers. (the windows OpenCl program will load it using the OPenCL clCreateProgramWithBinary function).

**Comment by preda** [comment]
Not a definitive answer, but I'd suspect that if the driver accepts the binary, then it's all good.

I did explore binary compatibility between ROCm 1.6 and 1.7 (both on Linux), and there the compiled binary is not accepted.

**Comment by Enoch72** [comment]
Good.
