### ISSUE TITLE
Raven Ridge ROCm support

### ISSUE THREAD

**Issue by ekondis** [RadeonOpenCompute/ROCm#333]
Hello,
Since first Raven ridge desktop APUs are out, I would love to know what is the plan for supporting raven ridge on ROCm. This gets even more important as currently raven ridge seems to be the only affordable way for doing research on Vega GPU compute.

Thanks in advance.

**Comment by zpodlovics** [comment]
Hi,
I am also interested. I would like to also know the support plans, especially for the long support plan including the long term versioning support plan (hint: Kaveri support dropped). I would like to also know the known working or recommended products (eg.: used internally for development something like ASUS A88XM-A for HSA)  and bios versions, as it was really important in the past eg.: https://github.com/HSAFoundation/HSA-Drivers-Linux-AMD/issues/7, https://github.com/HSAFoundation/HSA-Drivers-Linux-AMD/issues/6

It's really hard to enable HSA/ROCm/ROCr software support without affordable and easily available hardware in the market and _stable and long term supported software_.

**Comment by ob7** [comment]
does this mean vega laptops are now available?

**Comment by Unkraut3** [comment]
Vega laptops have been available for some months. Now Raven Ridge Desktop CPUs are out. Unfortunately, Linux support is rather limited. Read: [Phoronix: AMD's Raven Ridge Botchy Linux Support](https://www.phoronix.com/scan.php?page=news_item&px=AMD-Raven-Ridge-Mobo-Linux)

**Comment by gstoner** [comment]
No it not a principle priority for ROCm project  It is not primary target for the project .  There is a AMD driver that supports it.  It is called  AMDGPUPRO for Linux.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ekondis** [comment]
@gstoner , though not a primary target for ROCm, this raises a question regarding the particular statement in the readme file:

> Support for future APUs
> We are well aware of the excitement and anticipation built around using ROCm with an APU system which fully exposes Shared Virtual Memory alongside and cache coherency between the CPU and GPU. To this end, in mid 2017 we plan on testing commercial AM4 motherboards for the Bristol Ridge and Raven Ridge families of APUs. Just like you, we still waiting for access to them! Once we have the first boards in the lab we will detail our experiences via our blog, as well as build a list of motherboard that are qualified for use with ROCm.

So, is supporting contemporary APUs still in the plans? Perhaps this paragraph requires an update.

**Comment by gstoner** [comment]
We love to do day one support for everything, but we still a small team, the first focus is on building a rich in capability, a stable robust foundation for GPU Computing,  RIght now we been focusing on core driver so we can bring more distro support.     Please be patient with the team
