### ISSUE TITLE
linfo

### ISSUE THREAD

**Issue by pcca-matrix** [RadeonOpenCompute/ROCm#334]

**Comment by gstoner** [comment]
@pcca-matrix  ???  what is the issue

**Comment by gstoner** [comment]
@pcca-matrix  can you try this beta. http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2

**Comment by pcca-matrix** [comment]
Sorry i don't let any issues here ?? 
I do not understand what is happening
