### ISSUE TITLE
HIP vs. HC C++ in rocFFT (question)

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#336]
I'd like to know, why rocFFT is implemented in HIP instead of HC C++? is there a reason to prefer one over the other? performance, API maturity?

(I did look here for a discussion of the various ROCm APIs:
http://rocm-documentation.readthedocs.io/en/latest/Programming_Guides/Programming-Guides.html
)

**Comment by ekondis** [comment]
Good question. After all according to docs one should choose HIP only if he requires compatibility with NVidia hardware otherwise choosing HC is the norm. Please comment if I'm wrong.

**Comment by gstoner** [comment]
@ekondis  Can you try this beta http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2
