### ISSUE TITLE
Kernel `4.4.0-kfd-compute-rocm-rel-1.2-31` doesn't have ZFS modules.

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCm#34]
Please build your Ubuntu kernels from Ubuntu kernel sources using Ubuntu configs to be compatible with Ubuntu.

**Comment by gstoner** [comment]
With ROCm 1.3 we moving to Loadable Modules for KFD,  So you use standard linux kernel.


On Sep 27, 2016, at 5:59 AM, almson <notifications@github.com<mailto:notifications@github.com>> wrote:


Please build your Ubuntu kernels from Ubuntu kernel sources using Ubuntu configs to be compatible with Ubuntu.

**Comment by almson** [comment]
That's very good. In the meantime, I wrote up some instructions for porting the Ubuntu patches to your kernel. (Tested on Ubuntu 16.04.)

### Install pre-requisites

	sudo apt-get build-dep linux

### Get sources

	git clone git://kernel.ubuntu.com/ubuntu/linux.git linux-kernel
	git clone --reference linux-kernel https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver.git linux-kernel-roc
	git clone --reference linux-kernel git://kernel.ubuntu.com/ubuntu/ubuntu-xenial.git ubuntu-kernel-xenial

### Push the ROC branch into the Ubuntu tree

	cd linux-kernel-roc
	git checkout roc-1.2.0
	git branch roc
	git remote add ubuntu-kernel-xenial ../ubuntu-kernel-xenial
	git push ubuntu-kernel-xenial roc

### Rebase Ubuntu's changes into ROC sources using what seems like the most appropriate version of Ubuntu's kernel.

	cd ../ubuntu-kernel-xenial
	git checkout Ubuntu-4.4.0-0.10
	git rebase roc

(I chose `Ubuntu-4.4.0-0.10` because it had the same immediate ancestor as `roc-1.2.0`, namely the commit afd2ff9b "Linux 4.4". It might also be possible to first rebase `roc` to a more recent kernel and then apply more recent Ubuntu patches.)

### Fix the config

Here I was a little unsure, because the roc .config doesn't set most of these either. I mostly accepted the defaults (ie, n to everything), except I turned on DRM_AMD_POWERPLAY.
(Note that if you're doing this to a different version of roc, chances are the broken config entries will be different. Proceed to the `updateconfigs` step and see what, if anything, it wants from you)

Edit `debian.master/config/config.common.ubuntu`, and append

	CONFIG_DRM_AMDGPU_GART_DEBUGFS=n
	CONFIG_DRM_AMD_POWERPLAY=y
	CONFIG_DRM_AMD_ACP=n
	CONFIG_DRM_AMD_DAL=n
	CONFIG_SND_SOC_AMD_ACP=n

### Compile

	set AUTOBUILD 1
	fakeroot debian/rules clean
	debian/rules updateconfigs
	fakeroot debian/rules binary

### Install

(Pick which packages to install based on your needs.)

	cd ..
	sudo dpkg -i linux-headers-4.4.0-0_4.4.0-0.10_all.deb linux-tools-4.4.0-0_4.4.0-0.10_amd64.deb  linux-headers-4.4.0-0-lowlatency_4.4.0-0.10_amd64.deb linux-image-4.4.0-0-lowlatency_4.4.0-0.10_amd64.deb linux-tools-4.4.0-0-lowlatency_4.4.0-0.10_amd64.deb

**Comment by almson** [comment]
ROCm 1.3 still doesn't have zfs modules or Ubuntu patches. Nor does it use a standard kernel with dkms as promised.

**Comment by gstoner** [comment]
On Nov 27, 2016, at 11:00 AM, almson <notifications@github.com<mailto:notifications@github.com>> wrote:


ROCm 1.3 still doesn't have zfs modules or Ubuntu patches. Nor does it use a standard kernel with dkms as promised.

**Comment by gstoner** [comment]
We never promised ZFS support,  But I let the lead on DKMS talk you through what is there what is not.  We have been working on it base DKMS support is already there.

**Comment by almson** [comment]
Thank you, looking forward to it. The trick with rebasing the Ubuntu tree onto the ROCm tree isn't working, so a DKMS solution would be great.

**Comment by almson** [comment]
Is ROCm 1.3 compatible with any vanilla 4.8 kernel? When do you foresee standard Linux supporting ROCm?

**Comment by almson** [comment]
@gstoner Any update on how I can compile a module for the Ubuntu kernel?
