### ISSUE TITLE
OpenCL head: "Intrinsic has incorrect return type!"

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#340]
Ubuntu 17.10, Vega 64.
With freshly built opencl, I get this on clGetPlatformIDs() invocation, e.g.:

$ LD_LIBRARY_PATH=/home/preda/rocm/opencl/build/lib clinfo
Intrinsic has incorrect return type!
i8 addrspace(2)* ()* @llvm.amdgcn.dispatch.ptr
Intrinsic has incorrect return type!
i8 addrspace(2)* ()* @llvm.amdgcn.implicitarg.ptr
Intrinsic has incorrect return type!
i8 addrspace(2)* ()* @llvm.amdgcn.implicitarg.ptr
Intrinsic has incorrect return type!
i8 addrspace(2)* ()* @llvm.amdgcn.implicitarg.ptr
Intrinsic has incorrect return type!
i8 addrspace(2)* ()* @llvm.amdgcn.dispatch.ptr
Number of platforms                               0

**Comment by dfukalov** [comment]
fixed in https://github.com/RadeonOpenCompute/ROCm-Device-Libs/commit/0f4a9922bd3b0ce15821257645b026d1b1fc6d4d

**Comment by projenix** [comment]
I have the same problem on 18.04, I think that we'll have to revert to the older driver.

**Comment by kode54** [comment]
I also have the same problem on 18.04, with the padoka PPA.

**Comment by codedcosmos** [comment]
If you are having this issue in ubuntu 18.04
you likely need to install Rocm

https://rocm.github.io/ROCmInstall.html#ubuntu-support---installing-from-a-debian-repository
