### ISSUE TITLE
Ubuntu 16.04 hangs when enabling lightdm on boot

### ISSUE THREAD

**Issue by xiamaz** [RadeonOpenCompute/ROCm#346]
I have just installed rocm on 16.04 LTS using Linux 4.13.0-32.

Unfortunately the boot hangs when starting the system normally showing only a blue or green screen without disk activity or the possibility to login via ssh.

When lightdm is disabled on boot the system starts correctly. Starting lightdm later is possible and all opencl and opengl features are enabled correctly.

Is this a known bug?

**Comment by gstoner** [comment]
I am checking into this, will get back to you

**Comment by gstoner** [comment]
@xiamaz Can you try this beta http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2
