### ISSUE TITLE
Is Caffe the only ML framework that currently supports AMD GPUs ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#349]

**Comment by gstoner** [comment]
No we have Tensorflow 1.0 out refresh is happing soon.

**Comment by boxerab** [comment]
Great. Can't wait! Can you comment on PyTorch ?

**Comment by psteinb** [comment]
How about mxnet as hinted at 
[here](https://github.com/RadeonOpenCompute/hcc/issues/397#issuecomment-358262001)?

**Comment by gstoner** [comment]
@boxerab  @psteinb @perhaad http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2

Can you test this release 

g

**Comment by boxerab** [comment]
Thanks, I am testing it now. Question: how can I test that I have the latest opencl driver from the beta?
When I run `/opt/rocm/opencl/bin/x86_64/clinfo`, it says that driver version is `2576`.  Is this the correct version?

**Comment by gstoner** [comment]
@psteinb MxNet is getting real close

**Comment by psteinb** [comment]
Very cool. Am at a [hackathon 
now](https://gcoe-dresden.de/the-hack-is-on-in-2018/) and will upgrade 
and test it right after. If anyone can share experiences, please do so.
