### ISSUE TITLE
Beta 1.7.1 RC4 does it require Secure Boot required?

### ISSUE THREAD

**Issue by Mandrewoid** [RadeonOpenCompute/ROCm#350]
@gstoner  I saw you asking people to test http://repo.radeon.com/misc/archive/beta/rocm-1.7.1.beta.4.tar.bz2 so I took the liberty of trying.
during the install of the .deb files I got:

Processing triggers for shim-signed (1.32~16.04.1+0.9+1474479173.6c180c6-1ubuntu1) ...
Secure Boot not enabled on this system.
Errors were encountered while processing:
 MIOpen-OpenCL-1.2.1-cf3d051-Linux.deb

**Comment by gstoner** [comment]
thank you

**Comment by gstoner** [comment]
We have not been using secure boot on our servers,

**Comment by gstoner** [comment]
Are you running the server or consumer version of Ubuntu

**Comment by Mandrewoid** [comment]
Ubuntu desktop version yes

**Comment by Mandrewoid** [comment]
Update: The secure boot message might not be the error. I was installing in batch. Attempting to do this:

sudo dpkg -i MIOpen-OpenCL-1.2.1-cf3d051-Linux.deb  On its own gives a different error:

(Reading database ... 284374 files and directories currently installed.)
Preparing to unpack MIOpen-OpenCL-1.2.1-cf3d051-Linux.deb ...
Unpacking miopen-opencl (1.2.1-cf3d051) ...
dpkg: error processing archive MIOpen-OpenCL-1.2.1-cf3d051-Linux.deb (--install):
 trying to overwrite '/opt/rocm/miopen/include/miopen/config.h', which is also in package miopen-hip 1.2.1-cf3d051
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 MIOpen-OpenCL-1.2.1-cf3d051-Linux.deb

**Comment by krrk** [comment]
I believe this is likely just a packaging issue. [MIOpen](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/index.html) is a deep learning library by AMD which has two different backends HIP and OpenCL. Perhaps the headers for the different backends should be installed in separate locations (/opt/rocm/miopen-opencl and /opt/rocm/miopen-hip) or perhaps there are other conflicts with the backends? If there are other conflicts then the packages should explicitly mutually conflict each other.

**Comment by gstoner** [comment]
@krrk  Thank you, this is what i am looking for.  I see if we can get a spin this week out if i can or it be Monday

**Comment by gstoner** [comment]
Are you guys trying to install the OpenCL and HIP version of MIOpen on top of each other,

**Comment by krrk** [comment]
Yes, as I mentioned in #344 without any instructions or install script I decided to `dpkg -i *.deb` for all the deb files you provided. It did not cause any other problem for me, especially since I do not need MIOpen. The DEBIAN control files for these two packages do not mention any conflicts.

**Comment by boxerab** [comment]
@krrk I am also running `dpkg -i *.dev`, get error for MIOpen mackage

**Comment by gstoner** [comment]
The  HIP and MIOpen Package are colliding in the same directory,  we get update instruction prior to release.

**Comment by Mandrewoid** [comment]
Just some side notes, it doesn't require secure boot. The rocm installer at the end of install tells you whether or not secure boot is enabled, but it doesn't seem to impact functionality. As far as I can tell it is only an info message
