### ISSUE TITLE
Beta 4 1.7.1 breaks hiptensorflow

### ISSUE THREAD

**Issue by Mandrewoid** [RadeonOpenCompute/ROCm#351]
1.7.1 installed and verified using the HelloWorld sample from https://rocm.github.io/ROCmInstall.html, no errors.
hipTensorFlow reinstalled from .whl file broken and unable to import "Undefined symbol".
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN8hip_impl18unlock_stream_hip_EP12ihipStream_tPvPKcPN2hc16accelerator_viewE

Failed to load the native TensorFlow runtime.

**Comment by Mandrewoid** [comment]
This seems to have been not fixed from the previous version 1.6:
https://github.com/ROCmSoftwarePlatform/hiptensorflow/issues/28

**Comment by gstoner** [comment]
We working on new version of Tensorflow based on 1.3, working to get it out post 1.7.1 release

**Comment by gstoner** [comment]
The team is working on a patch for 1.0

**Comment by briansp2020** [comment]
Looks like 1.7.1 is out. Do you have ETA for DL frameworks? I'm interested in PyTorch support. I'm currently participating in a Kaggle competition (21st in 2018 Data Science Bowl) and working with TensorFlow/Keras. But it looks like I'll have to switch to PyTorch in order to make further progress. It would be great if I can train my final entry using ROCm & AMD hardware.

**Comment by streamhsa** [comment]
pyTorch is NOT targeted for ROCm1.7.1. It will come soon.

**Comment by briansp2020** [comment]
I tried https://github.com/matterport/Mask_RCNN using ROCm + tensorflow 1.3 on GPUeater.com and it does not run properly. Could someone from ROCm team check it out? train_shapes.ipynb runs in a few minutes on my 1080 GPU. I was hoping Vega FE with 16GB of memory would be able to run it better but it does not seem to run properly at all.

**Comment by briansp2020** [comment]
@Mandrewoid  
That is exactly what I experienced. Watching that thread hoping...
