### ISSUE TITLE
Freezing during OpenCL kernel compilation (ROCm 1.7)

### ISSUE THREAD

**Issue by ekondis** [RadeonOpenCompute/ROCm#352]
I'm maintaining a μ-benchmark suite for GPU memories using OpenCL dubbed _gpumembench_. A particular benchmark (_shmembench-ocl_) freezes during compilation when using _int4_ data type. This even happens with ROCm v1.7.1 beta 4. It seems that the problem is triggered by using an unroll directive before the core loop:

```
#pragma unroll 32
for(...)
```

Removing the directive resolves the problem but there has to be a better solution.

The full source code is provided on [gpumembench page on github](https://github.com/ekondis/gpumembench)

**Comment by gstoner** [comment]
Thank you we start looking at this 

greg

**Comment by tekcomm** [comment]
Ran into this I ended up disabling the watchdog in the kernel.

**Comment by gstoner** [comment]
Fixed in 1.8 and now part of regression suite
