### ISSUE TITLE
1.7.1 beta 4 brings hope for older GPUs

### ISSUE THREAD

**Issue by pmc01** [RadeonOpenCompute/ROCm#353]
My R9 390 (GFX7 Hawaii) works for the first time on 1.7.1 beta 4 (kernel 4.13.0-36-generic). Prior to this version, all of the compute programs would freeze or crash and dmesg would be full of errors like "cp queue timeout". 

The betas are posted at http://repo.radeon.com/misc/archive/beta/. If you have one of these old GPUs, you will need to change the amdgpu boot parameters in grub or modprobe. My grub cmdline is: "amdgpu.dc=0 amdgpu.dpm=1 amdgpu.cik_support=1 amdgpu.si_support=1".

**Comment by preda** [comment]
What do those amdgpu grub arguments do exactly, and how did you find them?

**Comment by gstoner** [comment]
ROCm will only run on W9100 or newer cards
