### ISSUE TITLE
HCC RUNTIME ERROR in hipCaffe

### ISSUE THREAD

**Issue by MAXHAOZHANG** [RadeonOpenCompute/ROCm#354]
Issue summary

./build/test/test_all.testbin

Backtrace:
0x00007f04870cd32e:	Kalmar::CLAMP::DetermineAndGetProgram(Kalmar::KalmarQueue*, unsigned long*, void**) + 0x59e
0x00007f04870cd690:	Kalmar::KalmarBootstrap::KalmarBootstrap() + 0x120
0x00007f04870cd549:	__hcc_shared_library_init + 0x29
0x00007f048a2766ba:	_dl_rtld_di_serinfo + 0x706a
0x00007f048a2767cb:	_dl_rtld_di_serinfo + 0x717b
0x00007f048a266c6a:	+ 0x717b

HCC RUNTIME ERROR: Fail to find compatible kernel at file:mcwamp.cpp line:346

Operating system: Ubuntu 16.04

**Comment by gstoner** [comment]
@MAXHAOZHANG  This information is not enough for us to understand what is going wrong,  
When you report an issue we need the version of the driver your running which version of HCC.

**Comment by parallelo** [comment]
Duplicate issue:  https://github.com/ROCmSoftwarePlatform/hipCaffe/issues/39

**Comment by MAXHAOZHANG** [comment]
The GPU in my server does not support ROCm -v1.7 -- From AMD
AMD Firepro W9100

Thank you!
