### ISSUE TITLE
GCN 1 support

### ISSUE THREAD

**Issue by Johnreidsilver** [RadeonOpenCompute/ROCm#356]
Although I searched for related keyword, apologies if this has already been addressed.

Are there any plans to have GCN 1 support, namely R9 270 aka pitcairn R9 370, etc ?

Thanks

**Comment by gstoner** [comment]
Currently, there are no plans to pull these GPUs in for support, they are missing key hardware capabilities needed for the base driver.

**Comment by Phenom23** [comment]
How about gcn4 gpus like rx580 or gcn3 like r9 380 or gcn5 like vega 64...

**Comment by Phenom23** [comment]
How about gcn4 gpus like rx580 or gcn3 like r9 380 or gcn5 like vega 64...
