### ISSUE TITLE
Debian 9.4 kernel  with rocm 1.7.137: calc_freesync_range and dce110_stream_encoder_dp_blank warnings

### ISSUE THREAD

**Issue by dblueman** [RadeonOpenCompute/ROCm#359]
When running rocm 1.7.137 built against the on the Debian 9.4 kernel 4.9.82-1+deb9u3 with an RX580 connected to an LG 27UD88 monitor via DisplayPort 1.2, I see some freesync and DC register access warnings [1].

Let me know if more debug is useful.

-- [1]

[    0.000000] Linux version 4.9.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)
...
[    2.911377] [drm] Initialized
[    2.915264] amdkcl: loading out-of-tree module taints kernel.
[    2.918501] [drm] Using P2A bridge for configuration
[    2.918503] [drm] AST 2400 detected
[    2.918514] [drm] Analog VGA only
[    2.918526] [drm] dram -1094967296 6 16 01000000
[    2.918570] [TTM] Zone  kernel: Available graphics memory: 65862450 kiB
[    2.918570] [TTM] Zone   dma32: Available graphics memory: 2097152 kiB
[    2.918571] [TTM] Initializing pool allocator
[    2.918573] [TTM] Initializing DMA pool allocator
[    2.921672] checking generic (d0000000 300000) vs hw (a9000000 1000000)
[    3.019125] [drm] amdgpu kernel modesetting enabled.
[    3.025136] kfd kfd: Initialized module
[    3.025291] checking generic (d0000000 300000) vs hw (d0000000 10000000)
[    3.025293] fb: switching to amdgpudrmfb from EFI VGA
[    3.025686] [drm] initializing kernel modesetting (POLARIS10 0x1002:0x67DF 0x1043:0x0521 0xE7).
[    3.025707] [drm] register mmio base: 0xE0E00000
[    3.025708] [drm] register mmio size: 262144
[    3.025726] [drm] probing gen 2 caps for device 8086:2030 = 57a3903/e
[    3.025729] [drm] probing mlw for device 8086:2030 = 57a3903
[    3.025739] [drm] UVD is enabled in VM mode
[    3.025740] [drm] VCE enabled in VM mode
[    3.025951] amdgpu 0000:65:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
[    3.026007] ATOM BIOS: 115-D009PI2-101
[    3.026015] [drm] GPU post is not needed
[    3.026031] [drm] vm size is 512 GB, block size is 15-bit, fragment size is 9-bit
[    3.026999] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_mc.bin
[    3.027007] amdgpu 0000:65:00.0: VRAM: 8192M 0x000000F400000000 - 0x000000F5FFFFFFFF (8192M used)
[    3.027009] amdgpu 0000:65:00.0: GTT: 256M 0x0000000000000000 - 0x000000000FFFFFFF
[    3.027017] [drm] Detected VRAM RAM=8192M, BAR=256M
[    3.027018] [drm] RAM width 256bits GDDR5
[    3.027083] [TTM] Zone  kernel: Available graphics memory: 123492093 kiB
[    3.027084] [TTM] Initializing pool allocator
[    3.027089] [TTM] Initializing DMA pool allocator
[    3.027107] [drm] amdgpu: 8192M of VRAM memory ready
[    3.027108] [drm] amdgpu: 128637M of GTT memory ready.
[    3.027117] [drm] GART: num cpu pages 65536, num gpu pages 65536
[    3.027180] [drm] PCIE GART of 256M enabled (table at 0x000000F400040000).
[    3.027243] amdgpu 0000:65:00.0: amdgpu: using MSI.
[    3.027259] [drm] amdgpu: irq initialized.
[    3.027279] amdgpu: [powerplay] amdgpu: powerplay sw initialized
[    3.027555] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_pfp_2.bin
[    3.027836] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_me_2.bin
[    3.028025] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_ce_2.bin
[    3.028026] [drm] Chained IB support enabled!
[    3.028292] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_rlc.bin
[    3.028900] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_mec_2.bin
[    3.029621] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_mec2_2.bin
[    3.029685] amdgpu 0000:65:00.0: fence driver on ring 0 use gpu addr 0x0000000000400040, cpu addr 0xffffbe954de81040
[    3.029725] amdgpu 0000:65:00.0: fence driver on ring 1 use gpu addr 0x00000000004000c0, cpu addr 0xffffbe954de810c0
[    3.029773] amdgpu 0000:65:00.0: fence driver on ring 2 use gpu addr 0x0000000000400140, cpu addr 0xffffbe954de81140
[    3.029808] amdgpu 0000:65:00.0: fence driver on ring 3 use gpu addr 0x00000000004001c0, cpu addr 0xffffbe954de811c0
[    3.029845] amdgpu 0000:65:00.0: fence driver on ring 4 use gpu addr 0x0000000000400240, cpu addr 0xffffbe954de81240
[    3.029881] amdgpu 0000:65:00.0: fence driver on ring 5 use gpu addr 0x00000000004002c0, cpu addr 0xffffbe954de812c0
[    3.029918] amdgpu 0000:65:00.0: fence driver on ring 6 use gpu addr 0x0000000000400340, cpu addr 0xffffbe954de81340
[    3.029953] amdgpu 0000:65:00.0: fence driver on ring 7 use gpu addr 0x00000000004003c0, cpu addr 0xffffbe954de813c0
[    3.029990] amdgpu 0000:65:00.0: fence driver on ring 8 use gpu addr 0x0000000000400440, cpu addr 0xffffbe954de81440
[    3.030007] amdgpu 0000:65:00.0: fence driver on ring 9 use gpu addr 0x00000000004004e0, cpu addr 0xffffbe954de814e0
[    3.030695] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_sdma.bin
[    3.030913] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_sdma1.bin
[    3.030942] amdgpu 0000:65:00.0: fence driver on ring 10 use gpu addr 0x0000000000400560, cpu addr 0xffffbe954de81560
[    3.030990] amdgpu 0000:65:00.0: fence driver on ring 11 use gpu addr 0x00000000004005e0, cpu addr 0xffffbe954de815e0
[    3.031956] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_uvd.bin
[    3.031960] [drm] Found UVD firmware Version: 1.79 Family ID: 16
[    3.032191] amdgpu 0000:65:00.0: fence driver on ring 12 use gpu addr 0x000000f4001e5420, cpu addr 0xffffbe956025a420
[    3.032688] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_vce.bin
[    3.032691] [drm] Found VCE firmware Version: 52.4 Binary ID: 3
[    3.032760] amdgpu 0000:65:00.0: fence driver on ring 13 use gpu addr 0x00000000004006e0, cpu addr 0xffffbe954de816e0
[    3.032787] amdgpu 0000:65:00.0: fence driver on ring 14 use gpu addr 0x0000000000400760, cpu addr 0xffffbe954de81760
[    3.033491] amdgpu 0000:65:00.0: firmware: direct-loading firmware amdgpu/polaris10_k_smc.bin
[    3.091210] [drm] DAL is enabled
[    3.091337] [drm] DM_PPLIB: values for Engine clock
[    3.091338] [drm] DM_PPLIB:     30000
[    3.091339] [drm] DM_PPLIB:     60000
[    3.091340] [drm] DM_PPLIB:     90000
[    3.091340] [drm] DM_PPLIB:     116200
[    3.091341] [drm] DM_PPLIB:     123300
[    3.091342] [drm] DM_PPLIB:     127500
[    3.091342] [drm] DM_PPLIB:     131900
[    3.091343] [drm] DM_PPLIB:     136000
[    3.091344] [drm] DM_PPLIB: Warning: using default validation clocks!
[    3.091344] [drm] DM_PPLIB: Validation clocks:
[    3.091345] [drm] DM_PPLIB:    engine_max_clock: 72000
[    3.091346] [drm] DM_PPLIB:    memory_max_clock: 80000
[    3.091346] [drm] DM_PPLIB:    level           : 0
[    3.091347] [drm] DM_PPLIB: reducing engine clock level from 8 to 2
[    3.091349] [drm] DM_PPLIB: values for Memory clock
[    3.091350] [drm] DM_PPLIB:     30000
[    3.091350] [drm] DM_PPLIB:     100000
[    3.091351] [drm] DM_PPLIB:     200000
[    3.091370] [drm] DM_PPLIB: Warning: using default validation clocks!
[    3.091370] [drm] DM_PPLIB: Validation clocks:
[    3.091371] [drm] DM_PPLIB:    engine_max_clock: 72000
[    3.091372] [drm] DM_PPLIB:    memory_max_clock: 80000
[    3.091372] [drm] DM_PPLIB:    level           : 0
[    3.091373] [drm] DM_PPLIB: reducing memory clock level from 3 to 1
[    3.091375] [drm] DC: create_links: connectors_num: physical:5, virtual:0
[    3.091380] [drm] Connector[0] description:signal 32
[    3.091384] [drm] Using channel: CHANNEL_ID_DDC2 [2]
[    3.091399] [drm] Connector[1] description:signal 32
[    3.091401] [drm] Using channel: CHANNEL_ID_DDC4 [4]
[    3.091414] [drm] Connector[2] description:signal 4
[    3.091417] [drm] Using channel: CHANNEL_ID_DDC1 [1]
[    3.091430] [drm] Connector[3] description:signal 4
[    3.091433] [drm] Using channel: CHANNEL_ID_DDC3 [3]
[    3.091446] [drm] Connector[4] description:signal 2
[    3.091449] [drm] Using channel: CHANNEL_ID_DDC6 [6]
[    3.102919] [drm] Display Core initialized
[    3.102922] [drm] amdgpu: freesync_module init done ffff9822e2e87e00.
[    3.103051] [drm] link=0, dc_sink_in=          (null) is now Disconnected
[    3.103052] [drm] DCHPD: connector_id=0: dc_sink didn't change.
[    3.119906] [drm] [Detect]    [DP][ConnIdx:1] Rx Caps: 12 14 C4 01 01 00 01 40 02 02 06 00 00 00 00 ^
[    3.144087] [drm] [LKTN]    [DP][ConnIdx:1] HBR2x4 EQ failed VS=2, PE=0^
[    3.157602] [drm] [LKTN]    [DP][ConnIdx:1] HBR2x2 EQ failed VS=2, PE=0^
[    3.170763] [drm] [LKTN]    [DP][ConnIdx:1] HBR2x1 EQ failed VS=2, PE=0^
[    3.176561] [drm] [LKTN]    [DP][ConnIdx:1] HBRx4 pass VS=1, PE=1^
[    3.176850] [drm] [Detect]    [DP][ConnIdx:1] LG Ultra HD: [Block 0] 00 FF FF FF FF FF FF 00 1E 6D 09 5B B3 39 02 00 07 1A 01 04 B5 3C 22 78 9F 30 35 A7 55 4E A3 26 0F 50 54 21 08 00 71 40 81 80 81 C0 A9 C0 D1 C0 81 00 01 01 01 01 4D D0 00 A0 F0 70 3E 80 30 20 65 0C 58 54 21 00 00 1A 28 68 00 A0 F0 70 3E 80 08 90 65 0C 58 54 21 00 00 1A 00 00 00 FD 00 28 3D 87 87 38 01 0A 20 20 20 20 20 20 00 00 00 FC 00 4C 47 20 55 6C 74 72 61 20 48 44 0A 20 01 51 ^
[    3.176861] [drm] [Detect]    [DP][ConnIdx:1] LG Ultra HD: [Block 1] 02 03 11 71 44 90 04 03 01 23 09 07 07 83 01 00 00 02 3A 80 18 71 38 2D 40 58 2C 45 00 58 54 21 00 00 1E 56 5E 00 A0 A0 A0 29 50 30 20 35 00 58 54 21 00 00 1A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 C8 ^
[    3.176863] [drm] dc_link_detect: manufacturer_id = 6D1E, product_id = 5B09, serial_number = 239B3, manufacture_week = 7, manufacture_year = 26, display_name = LG Ultra HD, speaker_flag = 1,
audio_mode_count = 1
[    3.176865] [drm] dc_link_detect: mode number = 0, format_code = 1, channel_count = 1, sample_rate = 7, sample_size = 7
[    3.176866] [drm] link=1, dc_sink_in=ffff9822eeb05400 is now Connected
[    3.176867] [drm] DCHPD: connector_id=1: Old sink=          (null) New sink=ffff9822eeb05400
[    3.177318] [drm] link=2, dc_sink_in=          (null) is now Disconnected
[    3.177319] [drm] DCHPD: connector_id=2: dc_sink didn't change.
[    3.177363] [drm] link=3, dc_sink_in=          (null) is now Disconnected
[    3.177364] [drm] DCHPD: connector_id=3: dc_sink didn't change.
[    3.177407] [drm] link=4, dc_sink_in=          (null) is now Disconnected
[    3.177407] [drm] DCHPD: connector_id=4: dc_sink didn't change.
[    3.177418] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    3.177418] [drm] Driver supports precise vblank timestamp query.
[    3.177419] [drm] KMS initialized.
[    3.178759] [drm] ring test on 0 succeeded in 14 usecs
[    3.179252] [drm] ring test on 9 succeeded in 8 usecs
[    3.179272] [drm] ring test on 1 succeeded in 9 usecs
[    3.179280] [drm] ring test on 2 succeeded in 3 usecs
[    3.179288] [drm] ring test on 3 succeeded in 3 usecs
[    3.179296] [drm] ring test on 4 succeeded in 3 usecs
[    3.179316] [drm] ring test on 5 succeeded in 9 usecs
[    3.179324] [drm] ring test on 6 succeeded in 3 usecs
[    3.179332] [drm] ring test on 7 succeeded in 3 usecs
[    3.179340] [drm] ring test on 8 succeeded in 3 usecs
[    3.179396] [drm] ring test on 10 succeeded in 5 usecs
[    3.179402] [drm] ring test on 11 succeeded in 5 usecs
[    3.206382] [drm] ring test on 12 succeeded in 1 usecs
[    3.206388] [drm] UVD initialized successfully.
[    3.306734] [drm] ring test on 13 succeeded in 5 usecs
[    3.306745] [drm] ring test on 14 succeeded in 2 usecs
[    3.306746] [drm] VCE initialized successfully.
[    3.307008] [drm] ib test on ring 0 succeeded
[    3.307150] [drm] ib test on ring 1 succeeded
[    3.307188] [drm] ib test on ring 2 succeeded
[    3.307225] [drm] ib test on ring 3 succeeded
[    3.307261] [drm] ib test on ring 4 succeeded
[    3.307297] [drm] ib test on ring 5 succeeded
[    3.307333] [drm] ib test on ring 6 succeeded
[    3.307369] [drm] ib test on ring 7 succeeded
[    3.307423] [drm] ib test on ring 8 succeeded
[    3.580751] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    3.593165] Ebtables v2.0 registered
[    3.817573] [drm] ib test on ring 9 succeeded
[    3.817614] [drm] ib test on ring 10 succeeded
[    3.817640] [drm] ib test on ring 11 succeeded
[    3.819286] [drm] ib test on ring 12 succeeded
[    3.819513] [drm] ib test on ring 13 succeeded
[    3.819738] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff9822e92a4c00, err:9, !
[    3.819916] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff9822e92a4c00, err:9, !
[    3.820012] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff9822e92a4c00, err:9, !
[    3.820100] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff9822e92a4c00, err:9, !
[    3.820185] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff9822e92a4c00, err:9, !
[    3.825046] [drm] fb mappable at 0xD03F1000
[    3.825048] [drm] vram apper at 0xD0000000
[    3.825049] [drm] size 33177600
[    3.825050] [drm] fb depth is 24
[    3.825051] [drm]    pitch is 15360
[    3.825198] fbcon: amdgpudrmfb (fb0) is primary device
[    3.825938] [drm] Atomic commit: SET crtc id 0: [ffff9822ecb68000]
[    3.825941] [drm] dc_commit_context: 1 streams
[    3.825945] [drm] core_stream 0xe36b1000: src: 0, 0, 3840, 2160; dst: 0, 0, 3840, 2160, colorSpace:1
[    3.825948] [drm]     pix_clk_khz: 266640, h_total: 4000, v_total: 2222, pixelencoder:1, displaycolorDepth:2
[    3.825950] [drm]     sink name: LG Ultra HD, serial: 145843
[    3.825951] [drm]     link: 1
[    3.839026] [drm] Link: 1 eDP panel mode supported: 0 eDP panel mode enabled: 0
[    3.843850] [drm] [LKTN]    [DP][ConnIdx:1] HBRx4 pass VS=1, PE=1^
[    3.847706] [drm] [Mode]    [DP][ConnIdx:1] {3840x2160, 4000x2222@266640Khz}^
[    3.847708] ------------[ cut here ]------------
[    3.847750] WARNING: CPU: 0 PID: 493 at /var/lib/dkms/rock/1.7.137-ubuntu/build/amd/amdgpu/../display/modules/freesync/freesync.c:434 calc_freesync_range+0x207/0x240 [amdgpu]
[    3.847776] Modules linked in: devlink ebtable_filter ebtables ip6_tables nf_log_ipv4 nf_log_common xt_LOG xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_multiport xt_conntrack nf_conntrack iptable_filter xt_DSCP iptable_mangle amdkfd(O) f2fs amdgpu(O+) amdttm(O) nls_ascii nls_cp437 vfat fat ast ttm amdkcl(O) drm_kms_helper snd_hda_codec_generic drm snd_hda_codec_hdmi i2c_designware_platform i2c_designware_core intel_rapl skx_edac edac_core x86_pkg_temp_thermal intel_powerclamp coretemp idma64 kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel snd_hda_intel snd_hda_codec efi_pstore snd_hda_core snd_hwdep intel_uncore snd_pcm snd_timer joydev serio_raw
snd intel_rapl_perf evdev iTCO_wdt pcspkr efivars soundcore iTCO_vendor_support shpchp mei_me intel_lpss_pci intel_lpss mfd_core
[    3.847802]  mei ioatdma wmi ipmi_si ipmi_msghandler acpi_cpufreq button tcp_bbr sch_fq efivarfs ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto ecb mbcache btrfs raid10 raid456 async_raid6_recov
async_memcpy async_pq async_xor async_tx xor hid_generic hid_apple usbhid hid raid6_pq libcrc32c crc32c_generic raid1 raid0 multipath linear md_mod crc32c_intel aesni_intel aes_x86_64 glue_helper lrw
gf128mul ablk_helper cryptd psmouse nvme nvme_core ahci libahci igb i2c_algo_bit xhci_pci i2c_i801 dca i2c_smbus ptp xhci_hcd pps_core libata scsi_mod usbcore usb_common
[    3.847804] CPU: 0 PID: 493 Comm: systemd-udevd Tainted: G O    4.9.0-6-amd64 #1 Debian 4.9.82-1+deb9u3
[    3.847805] Hardware name: Supermicro Super Server/X11SRA-F, BIOS 1.1a 02/14/2018
[    3.847807]  0000000000000000 ffffffffb392e074 0000000000000000 0000000000000000
[    3.847808]  ffffffffb36776be 0000000000000000 ffff9822e36b1000 00000000017d7840
[    3.847809]  ffff9822eed50010 ffff9822e2e87e00 0000000001fca055 ffffffffc0ad24e7
[    3.847810] Call Trace:
[    3.847815]  [<ffffffffb392e074>] ? dump_stack+0x5c/0x78
[    3.847819]  [<ffffffffb36776be>] ? __warn+0xbe/0xe0
[    3.847851]  [<ffffffffc0ad24e7>] ? calc_freesync_range+0x207/0x240 [amdgpu]
[    3.847880]  [<ffffffffc0ad3aea>] ? mod_freesync_notify_mode_change+0x14a/0x190 [amdgpu]
[    3.847913]  [<ffffffffc0a37396>] ? amdgpu_dm_atomic_commit_tail+0x396/0x9f0 [amdgpu]
[    3.847945]  [<ffffffffc0a35be7>] ? dm_plane_helper_prepare_fb+0x1a7/0x220 [amdgpu]
[    3.847952]  [<ffffffffc079d23c>] ? commit_tail+0x3c/0x60 [drm_kms_helper]
[    3.847955]  [<ffffffffc079d301>] ? drm_atomic_helper_commit+0x91/0xe0 [drm_kms_helper]
[    3.847958]  [<ffffffffc079f97c>] ? restore_fbdev_mode+0x14c/0x280 [drm_kms_helper]
[    3.847970]  [<ffffffffc08c9d00>] ? drm_modeset_lock_all_ctx+0xa0/0xb0 [drm]
[    3.847973]  [<ffffffffc07a14ee>] ? drm_fb_helper_restore_fbdev_mode_unlocked+0x2e/0x70 [drm_kms_helper]
[    3.847976]  [<ffffffffc07a1559>] ? drm_fb_helper_set_par+0x29/0x50 [drm_kms_helper]
[    3.847978]  [<ffffffffb39a5186>] ? fbcon_init+0x576/0x600
[    3.847980]  [<ffffffffb3a2e1f5>] ? visual_init+0xd5/0x130
[    3.847981]  [<ffffffffb3a2f7f5>] ? do_bind_con_driver+0x1d5/0x3c0
[    3.847982]  [<ffffffffb3a2fd13>] ? do_take_over_console+0x113/0x180
[    3.847984]  [<ffffffffb39a10e8>] ? do_fbcon_takeover+0x58/0xb0
[    3.847985]  [<ffffffffb39a5702>] ? fbcon_event_notify+0x102/0x790
[    3.847988]  [<ffffffffb3698737>] ? notifier_call_chain+0x47/0x70
[    3.847990]  [<ffffffffb3698a41>] ? __blocking_notifier_call_chain+0x41/0x60
[    3.847991]  [<ffffffffb39ad512>] ? register_framebuffer+0x212/0x360
[    3.847994]  [<ffffffffc07a182a>] ? drm_fb_helper_initial_config+0x2aa/0x450 [drm_kms_helper]
[    3.848018]  [<ffffffffc093ec9e>] ? amdgpu_fbdev_init+0xce/0x100 [amdgpu]
[    3.848040]  [<ffffffffc0928947>] ? amdgpu_device_init+0xe87/0x13e0 [amdgpu]
[    3.848042]  [<ffffffffb3a7991b>] ? device_add+0x18b/0x620
[    3.848063]  [<ffffffffc092a568>] ? amdgpu_driver_load_kms+0x88/0x280 [amdgpu]
[    3.848069]  [<ffffffffc08b9f83>] ? drm_dev_register+0xa3/0xd0 [drm]
[    3.848090]  [<ffffffffc09234af>] ? amdgpu_pci_probe+0x10f/0x140 [amdgpu]
[    3.848091]  [<ffffffffb397cb64>] ? local_pci_probe+0x44/0xa0
[    3.848092]  [<ffffffffb397dfac>] ? pci_device_probe+0x10c/0x160
[    3.848094]  [<ffffffffb3a7cfb3>] ? driver_probe_device+0x223/0x430
[    3.848095]  [<ffffffffb3a7d29d>] ? __driver_attach+0xdd/0xe0
[    3.848096]  [<ffffffffb3a7d1c0>] ? driver_probe_device+0x430/0x430
[    3.848097]  [<ffffffffb3a7aae9>] ? bus_for_each_dev+0x69/0xb0
[    3.848099]  [<ffffffffb3a7c1ea>] ? bus_add_driver+0x16a/0x260
[    3.848099]  [<ffffffffc0c11000>] ? 0xffffffffc0c11000
[    3.848100]  [<ffffffffb3a7db47>] ? driver_register+0x57/0xc0
[    3.848101]  [<ffffffffc0c11000>] ? 0xffffffffc0c11000
[    3.848102]  [<ffffffffb360218e>] ? do_one_initcall+0x4e/0x180
[    3.848105]  [<ffffffffb37c71ad>] ? __vunmap+0x6d/0xc0
[    3.848106]  [<ffffffffb37c71ad>] ? __vunmap+0x6d/0xc0
[    3.848108]  [<ffffffffb377d621>] ? do_init_module+0x5b/0x1ed
[    3.848110]  [<ffffffffb3701096>] ? load_module+0x2596/0x2ab0
[    3.848111]  [<ffffffffb36fd840>] ? __symbol_put+0x60/0x60
[    3.848112]  [<ffffffffb37017f6>] ? SYSC_finit_module+0xc6/0xf0
[    3.848113]  [<ffffffffb3603b7f>] ? do_syscall_64+0x8f/0xf0
[    3.848117]  [<ffffffffb3c113b8>] ? entry_SYSCALL_64_after_swapgs+0x42/0xb0
[    3.848118] ---[ end trace 65afbe576d8bced5 ]---
[    3.872283] Console: switching to colour frame buffer device 480x135
[    3.934395] amdgpu 0000:65:00.0: fb0: amdgpudrmfb frame buffer device
[    3.935817] kfd kfd: Allocated 3969056 bytes on gart
[    3.935832] Virtual CRAT table created for GPU
[    3.935832] Parsing CRAT table with 1 nodes
[    3.935838] Creating topology SYSFS entries
[    3.935910] Topology: Add dGPU node [0x67df:0x1002]
[    3.935953] kfd kfd: Reserved 2 pages for cwsr.
[    3.935983] kfd kfd: added device 1002:67df
[   13.611502] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff9822e0295c00, err:9, !
...
[ 4354.010205] [drm:dm_logger_write [amdgpu]] *ERROR* Failed validation for stream ffff981f0a45d000, err:9, !
[11207.505923] [drm] Atomic commit: RESET. crtc id 0:[ffff9822ecb68000]
[11207.505925] [drm] dc_commit_context: 0 streams
[11207.539065] [drm:generic_reg_wait [amdgpu]] *ERROR* REG_WAIT timeout 10us * 3000 tries - dce110_stream_encoder_dp_blank line:930
[11207.539066] ------------[ cut here ]------------
[11207.539090] WARNING: CPU: 4 PID: 1146 at /var/lib/dkms/rock/1.7.137-ubuntu/build/amd/amdgpu/../display/dc/dc_helper.c:168 generic_reg_wait+0x145/0x190 [amdgpu]
[11207.539090] Modules linked in: tun fuse devlink ebtable_filter ebtables ip6_tables nf_log_ipv4 nf_log_common xt_LOG xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_multiport xt_conntrack
nf_conntrack iptable_filter xt_DSCP iptable_mangle amdkfd(O) f2fs amdgpu(O) amdttm(O) nls_ascii nls_cp437 vfat fat ast ttm amdkcl(O) drm_kms_helper snd_hda_codec_generic drm snd_hda_codec_hdmi
i2c_designware_platform i2c_designware_core intel_rapl skx_edac edac_core x86_pkg_temp_thermal intel_powerclamp coretemp idma64 kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul
ghash_clmulni_intel snd_hda_intel snd_hda_codec efi_pstore snd_hda_core snd_hwdep intel_uncore snd_pcm snd_timer joydev serio_raw snd intel_rapl_perf evdev iTCO_wdt pcspkr efivars soundcore
iTCO_vendor_support shpchp mei_me intel_lpss_pci intel_lpss
[11207.539115]  mfd_core mei ioatdma wmi ipmi_si ipmi_msghandler acpi_cpufreq button tcp_bbr sch_fq efivarfs ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto ecb mbcache btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor hid_generic hid_apple usbhid hid raid6_pq libcrc32c crc32c_generic raid1 raid0 multipath linear md_mod crc32c_intel aesni_intel aes_x86_64 glue_helper lrw gf128mul ablk_helper cryptd psmouse nvme nvme_core ahci libahci igb i2c_algo_bit xhci_pci i2c_i801 dca i2c_smbus ptp xhci_hcd pps_core libata scsi_mod usbcore usb_common
[11207.539141] CPU: 4 PID: 1146 Comm: Xorg Tainted: G        W  O 4.9.0-6-amd64 #1 Debian 4.9.82-1+deb9u3
[11207.539142] Hardware name: Supermicro Super Server/X11SRA-F, BIOS 1.1a 02/14/2018
[11207.539142]  0000000000000000 ffffffffb392e074 0000000000000000 0000000000000000
[11207.539144]  ffffffffb36776be 0000000000000bb9 000000000000000a 0000000000004da4
[11207.539145]  0000000000000000 ffff9822e93e6900 0000000000010000 ffffffffc0ad2105
[11207.539146] Call Trace:
[11207.539150]  [<ffffffffb392e074>] ? dump_stack+0x5c/0x78
[11207.539153]  [<ffffffffb36776be>] ? __warn+0xbe/0xe0
[11207.539175]  [<ffffffffc0ad2105>] ? generic_reg_wait+0x145/0x190 [amdgpu]
[11207.539194]  [<ffffffffc0a61743>] ? dce110_stream_encoder_dp_blank+0x113/0x200 [amdgpu]
[11207.539213]  [<ffffffffc0ab789d>] ? dce110_disable_stream+0xcd/0x130 [amdgpu]
[11207.539231]  [<ffffffffc0ac8ce2>] ?
core_link_disable_stream+0x52/0x250 [amdgpu]
[11207.539250]  [<ffffffffc0a3cd27>] ? dm_logger_close+0x37/0x70 [amdgpu]
[11207.539268]  [<ffffffffc0ab8563>] ? dce110_reset_hw_ctx_wrap+0xa3/0x1b0 [amdgpu]
[11207.539285]  [<ffffffffc0ab9ec6>] ? dce110_apply_ctx_to_hw+0x56/0x830 [amdgpu]
[11207.539287]  [<ffffffffb36c1612>] ? up+0x12/0x60
[11207.539304]  [<ffffffffc0ad1c8b>] ? generic_reg_get+0x2b/0x70 [amdgpu]
[11207.539321]  [<ffffffffc0ac4e89>] ? dc_commit_context_no_check+0xe9/0x310 [amdgpu]
[11207.539341]  [<ffffffffc0a37220>] ? amdgpu_dm_atomic_commit_tail+0x220/0x9f0 [amdgpu]
[11207.539342]  [<ffffffffb37e335b>] ? kmem_cache_alloc_trace+0xbb/0x530
[11207.539343]  [<ffffffffb36b9704>] ? __wake_up+0x34/0x50
[11207.539348]  [<ffffffffc079cd55>] ? drm_atomic_helper_setup_commit+0x315/0x380 [drm_kms_helper]
[11207.539351]  [<ffffffffc079d23c>] ? commit_tail+0x3c/0x60 [drm_kms_helper]
[11207.539353]  [<ffffffffc079d301>] ? drm_atomic_helper_commit+0x91/0xe0 [drm_kms_helper]
[11207.539356]  [<ffffffffc079bd38>] ? drm_atomic_helper_connector_dpms+0xe8/0x190 [drm_kms_helper]
[11207.539366]  [<ffffffffc08cea34>] ? drm_mode_connector_set_obj_prop+0x64/0x80 [drm]
[11207.539371]  [<ffffffffc08cfd4b>] ? drm_mode_obj_set_property_ioctl+0x11b/0x160 [drm]
[11207.539375]  [<ffffffffc08cea8e>] ? drm_mode_connector_property_set_ioctl+0x3e/0x60 [drm]
[11207.539379]  [<ffffffffc08b6b7d>] ? drm_ioctl+0x1ed/0x470 [drm]
[11207.539384]  [<ffffffffc08cea50>] ? drm_mode_connector_set_obj_prop+0x80/0x80 [drm]
[11207.539385]  [<ffffffffb3805a51>] ? do_readv_writev+0x151/0x240
[11207.539399]  [<ffffffffc0923049>] ? amdgpu_drm_ioctl+0x49/0x80 [amdgpu]
[11207.539401]  [<ffffffffb3819db2>] ? do_vfs_ioctl+0xa2/0x620
[11207.539402]  [<ffffffffb381a3a4>] ? SyS_ioctl+0x74/0x80
[11207.539403]  [<ffffffffb3603b7f>] ? do_syscall_64+0x8f/0xf0
[11207.539405]  [<ffffffffb3c113b8>] ? entry_SYSCALL_64_after_swapgs+0x42/0xb0
[11207.539406] ---[ end trace 65afbe576d8bced6 ]---
[11207.572695] [drm] Atomic commit: RESET. crtc id 0:[ffff9822ecb68000]

**Comment by baryluk** [comment]
rocm 1.7.137?

This is ancient.

Also your kernel is ancient and not supported.

Debian is not supported officially either.

**Comment by streamhsa** [comment]
Hi @dblueman 
As this is very old issue which is >2.5 years old, closing this.
Request you to open a new issue if you still observe the same or any new issue, responses will be faster from **ROCmSupport** team.
Recommend to try with the latest versions of os and ROCm before filing tickets.
Thank you.
