### ISSUE TITLE
Asus STRIX Z270H Gaming, two GPUs is max, right?

### ISSUE THREAD

**Issue by cucub** [RadeonOpenCompute/ROCm#366]
Hi, just to confirm I got it right.
My Asus STRIX Z270H Gaming (consumer) motherboard has following PCIe slots:
one PCIe x16
one PCIe x8
one PCIe x2
three  PCIe x1

From this 6 PCIe slots, only the first two can be used by ROCm/atomics because the other four are less than x8, right? 
There is no "amd_iommu=on iommu=pt" GRUB kernel command line options that can enable any of the other PCIe slots so that more than two GPUs can be used, right?

**Comment by gstoner** [comment]
Currently you should use the x16 and x8 lanes

**Comment by gstoner** [comment]
Now with ROCm 1.8 you can use any slot
