### ISSUE TITLE
1.7.1 beta: which deep learning frameworks are supported ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#369]
Is it still just Caffe ?

**Comment by gstoner** [comment]
No.  Tensorflow 1.3

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boxerab** [comment]
Great. Are there instructions for how to install v. 1.3  on ROCm ?

**Comment by boxerab** [comment]
Ahh, never mind :) Found this:  https://github.com/ROCmSoftwarePlatform/tensorflow

**Comment by boxerab** [comment]
Is there multi-GPU support ? I have two polaris cards : 470s

**Comment by Mandrewoid** [comment]
@boxerab  as far as I know it should work.

**Comment by boxerab** [comment]
Thanks. As it turns out, only one of my cards is on a PCI3 slot, so not an issue.

**Comment by boxerab** [comment]
I was able to get TF 1.3  working on bare metal, with python2.
