### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by GrumpyRaven** [RadeonOpenCompute/ROCm#372]
Is ubuntu 18.04 supported and if not when can support be expected?

**Comment by tekcomm** [comment]
Grumpy

Once it is a lts it will be supported, I have been running it for months. There are no issues. Vega users will have to run the 4.17 kernel or a 4.15 patched with KFD support. As of march 26 the kfd patches for the Vegas an kfd were accepted into the mainline. Ill already have a ubuntu live 18.04 I have been using for months.


https://github.com/RadeonOpenCompute/ROCm/issues/361

Installer for full desktop or server system Fluxbox xinit and xterm, LXDE. Lubuntu Core with the Midori Browser, Lubuntu (standard desktop), Xubuntu, Xubuntu (standard desktop), Ubuntu MATE,Install Ubuntu (standard desktop),Ubuntu Gnome,Kubuntu,Server
**Real-time Priority running example auto start for cloud and or mining

**Comment by chriselrod** [comment]
So, the 4.17 kernel will support Vega + ROCm, contradicting statements on Phoronix?

There was a claim dating from January that it isn't ready yet, repeated just a few days ago:
https://phoronix.com/scan.php?page=news_item&px=AMDKFD-Rest-Of-dGPU-4.17

**Comment by preda** [comment]
It would be nice to have some official statement support from AMD for 18.04. I hope the team does try an install and testrun internally.

**Comment by gstoner** [comment]
We are not allowed by our legal team to make these statements.
