### ISSUE TITLE
Tahiti GCN1.0/GFX6 card support

### ISSUE THREAD

**Issue by xteejx** [RadeonOpenCompute/ROCm#374]
Is there any way to get ROCm working on my R9 280X card, either through ROCm directly or via some other OpenCL "thing"?
I want to use TensorFlow on the GPU I have, and it is still a decent card, I'm surprised that there's not anything more about support for older cards in any documentation. Is that because they're not supported *at all* and I'm supposed to buy a new one ( :( ), or has it just not been tested, or something else?

I know this isn't an issue per se, but if these Southern Island cards (or even just the 280X) are supported, it would be helpful to have something about it in the documentation, or even just some caveats to get it working.

Thank you :)

**Comment by Mandrewoid** [comment]
@xteejx Have you seen Hugh Perkins' tf-coriander? https://github.com/hughperkins/tf-coriander
or https://github.com/plaidml/plaidml
Might be worth a look.
I never tried coriander, but plaidml ran on my radeon HD 7950

**Comment by xteejx** [comment]
Will have a look at those, thanks!

**Comment by l29ah** [comment]
Do GFX6 cards lack some necessary hardware features for amdkfd support?

**Comment by talentoscope** [comment]
This report is closed. Ask a question in a forum or on IRC or something
