### ISSUE TITLE
Rust language supports

### ISSUE THREAD

**Issue by ulinlong** [RadeonOpenCompute/ROCm#375]
Is there any posible to publish a rust crate that can be used safely

**Comment by Hoeze** [comment]
Yes, please!

**Comment by theRippedPug** [comment]
Won't be too hard either. Rust has amazing C FFI and I don't see much c++ here. But I'm still new to ML and I might be wrong but i would love to see a ROCm crate.

**Comment by dishankjj** [comment]
yes please, AMD is making cheap and affordable hardware. And now Apple is moving forward with everything AMD. RCOm make much more sense now.

**Comment by bzm3r** [comment]
How easy/difficult is this? What's involved?

**Comment by omac777** [comment]
https://forums.xilinx.com/t5/Xilinx-Xclusive-Blog/AMD-and-Xilinx-Demonstrate-Converged-ROCm-Runtime-Technology/ba-p/1175091

I would love to see ROCm support Rust-lang via some crates that can empower developers to use the CPU, GPU and FPGA to its fullest extent.  There have been efforts to plunk in Rust-lang within GPU kernels, but very limited in terms of capabilities(no looping nor conditionals, no ability to peer-to-peer share data between CPU, GPU, FPGA-NVM-E storage).

Rust-lang could help make all those capabilities safer, easier and ultimately more performant.

**Comment by ROCmSupport** [comment]
Hi @ulinlong and all,
Currently we are not supporting rust-lang with ROCm.
Please keep checking our documentation for any changes in future.
Thank you.

**Comment by PTFOPlayer** [comment]
Good news everyone, I am working on bindings for Rocm (currently starting with rocm_smi_lib, crate name is the same) for rust.

In future I will also work on hip and other rocm functionalities.

I am also working on making an installer for Rocm, because the current form is annoying
