### ISSUE TITLE
[Feature]: When will support for 6000 series for WSL2 + ROCm?

### ISSUE THREAD

**Issue by hionwi** [RadeonOpenCompute/ROCm#3844]
### Suggestion Description

Will you consider supporting 6000 series?

### Operating System

wsl2

### GPU

6800xt

**Comment by sykez98** [comment]
at this point, never, indie company, no devs, please understand, only 260billion market cap company

**Comment by harkgill-amd** [comment]
Consolidating the ask of additional GPU support on WSL to https://github.com/ROCm/ROCm/issues/3863.
