### ISSUE TITLE
Is my card overheating? amdgpu: [powerplay] GPU over temperature range detected on PCIe 0:0.0!

### ISSUE THREAD

**Issue by Mandrewoid** [RadeonOpenCompute/ROCm#385]
Sorry if I'm posting this in the wrong place. If this a problem with AMDGPU or something else let me know.
I'm running ROCm and tensorflow workloads. rocm-smi reports temperature at  85c, fan speed at 40%. 
I am wondering why it is spamming my logs with ~400 of these warnings in a couple minutes and not ramping up fans to cool itself down.

**Comment by csuji** [comment]
Had the same problem. My solution: apt install fancontrol  and use pwmconfig to
generate /etc/fancontrol:
# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=5
DEVPATH=hwmon0=devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0
DEVNAME=hwmon0=amdgpu
FCTEMPS=hwmon0/pwm1=hwmon0/temp1_input
FCFANS= hwmon0/pwm1=hwmon0/fan1_input
MINTEMP=hwmon0/pwm1=25
MAXTEMP=hwmon0/pwm1=90
MINSTART=hwmon0/pwm1=20
MINSTOP=hwmon0/pwm1=5

**Comment by gstoner** [comment]
@Mandrewoid @csuji  The consumer card has ramp curve programmed in the firmware to keep quiet as possible for the longest time.  When doing heavy compute loads you want to override by pushing your fan speed up.  You can do this is ROCm-smi.   Vega10 and Fiji both showed this in the consumer variants.   We talked the Product manager for Gaming they need to ramp the fans sooner to keep the GPU cooler.
