### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by JacksonFurrier** [RadeonOpenCompute/ROCm#39]
Hello,

are you planning to support Windows platform for the upcoming 1.3 release?

**Comment by jedwards-AMD** [comment]
ROCm 1.3 will not support Windows. Also, ROCm support on the Windows operating system has not been announced in any public road map.

**Comment by vstallins** [comment]
Any date for 1.3? Looking forward to it detecting my GTX 1070 instead of saying no nvidia devices.

**Comment by gstoner** [comment]
I think you have install issue @vstallins  Since we run dual config boxes in houses.

**Comment by gstoner** [comment]
I think your talking about HIP since GTX1070 device would never be support by ROCm Driver.

greg

On Oct 22, 2016, at 12:05 PM, vstallins <notifications@github.com<mailto:notifications@github.com>> wrote:


Any date for 1.3? Looking forward to it detecting my GTX 1070 instead of saying no nvidia devices.

**Comment by gstoner** [comment]
What are you looking for on windows,   HIP and HCC.

greg
On Oct 21, 2016, at 9:41 AM, James Edwards <notifications@github.com<mailto:notifications@github.com>> wrote:


ROCm 1.3 will not support Windows. Also, ROCm support on the Windows operating system has not been announced in any public road map.

**Comment by vstallins** [comment]
I'm using Ubuntu 16.04LTS I have HIP and ROCm installed and HCC as well I think. Just trying to figure things out and get into computing with GPUs. I have a GTX 1070 and 12 R9 390s. So if I need to I can put a 390 in with the 1070. Just wanting to learn as I think this area has a bright future.

**Comment by arodrigx7** [comment]
The HIP layer provides source level compatibility between CUDA and ROCm. That's probably a good place to start reading. Depending on whether you have a CUDA or ROCm enabled system, HIP will compile using either NVCC or HCC (respectively).

Link to the HIP project:
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP

Btw, HIP is automatically installed with ROCm. So if you plug in one of your 390's it should be detected. If you want to use your GTX 1070, you will need to install NVCC and its dependencies. The HIP FAQ should have more information on this.

If you have further questions you can let us know.

**Comment by vstallins** [comment]
Ok thanks. I have all of that stuff installed already. Just new to all of this and trying to learn. If anyone makes tutorial videos, etc. let me know the links as it would help likely or if anyone has free time and feels like teaching I am open to that as well. I think GPU computing has huge potential especially with the next gen SSD GPUs.

**Comment by JacksonFurrier** [comment]
I would need HIP and HCC on Windows, but since its not in the roadmap I can leave it. Thanks for the reply :)

**Comment by dtmoodie** [comment]
Any chance you can compile a binary with hip with  Nvidia and amd code which can be selected at runtime?

**Comment by gstoner** [comment]
Have you look at the documentation on HIP.  

https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md

https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_faq.md

**Comment by dtmoodie** [comment]
Given the FAQ states that the tool does not create a binary for both platform, any ideas around bring around that limitation? Perhaps delay loading different libraries based on detected hardware?

**Comment by gstoner** [comment]
I have one of the lead get back on this

**Comment by HECer** [comment]
I really hope Windows support will come soon, i think the next graphics card will be an nvidia, because of this. It is really sad how amd cannot serve good support for the current software trends like neuronal networks.
I really hope they will change their focus a little more.

**Comment by cmpute** [comment]
+1. I will definitely choose to buy amd graphics cards if it support kernel acceleration tools on Windows!
