### ISSUE TITLE
ROCM Windows support coming soon?!

### ISSUE THREAD

**Issue by oscarbg** [RadeonOpenCompute/ROCm#390]
Hi,
I see comments from Tingxing Dong (which seems to work at AMD):
"https://gpuopen.com/using-rocm-to-leverage-hbm-a-matrix-vector-multiplication-case-study/#comment-12269"
saying last year:
"ROCM on windows will ship in Q4 2017"
"No, we probably add Windows support in 2017 Q4."
will be nice to know if there is still interest to support ROCM on Windows given we are in Q2 2018.. or project has been cancelled..
is this because next ROCM version seems being called 2.0?
thanks..

**Comment by gstoner** [comment]
The current ROCm stack is 100% based  Linux product and sits on customized Linux driver.  We will bring some of the languages over to Windows it was never going to happen in Q4 2017. Also, he should not have commented on a date.

**Comment by gbeatty** [comment]
Translation... "we're never releasing a windows product".
