### ISSUE TITLE
ispc compiler on ROCm + Ryzen

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#393]
Not really a ROCm issue, but not sure where else to post this.
Are there plans to customize the ispc compiler for Ryzen/EPIC chips?
I've heard great things about speedup potential for SPMD on ispc.

https://github.com/ispc/ispc

**Comment by boberfly** [comment]
@boxerab hmm doesn't it just target AVX2 already? Ryzen should support those wide vectors already, embree seems to function fine for instance, maybe I'm mistaken.

**Comment by gstoner** [comment]
Yes it should work via AVX2 path.

**Comment by boxerab** [comment]
cool. thanks guys.
