### ISSUE TITLE
Q: ROCm on Xeon E7 v3

### ISSUE THREAD

**Issue by Bliss3d** [RadeonOpenCompute/ROCm#398]
So, 
I'd like to run OpenCL applications with 2 or more Vega 64's on my Supermicro X10QBI, which is part of Intel's mission critical server line up. In the readme it says: 
Current CPUs which support PCIe Gen3 + PCIe Atomics are:

Intel Xeon E5 v3 or newer CPUs;
Intel Xeon E3 v3 or newer CPUs;
Intel Core i7 v4, Core i5 v4, Core i3 v4 or newer CPUs (i.e. Haswell family or newer).
AMD Ryzen CPUs;

So no Xeon E7 v3 or newer CPUs?
However the Xeon E7 v3 is part of the Haswell family

Could someone or Radeon clarify?

**Comment by gstoner** [comment]
Xeon E7 v3 will work,  we just do not have to many people use this class of system..   We can added to the list.

Greg

On Apr 28, 2018, at 4:01 PM, Bliss3d <notifications@github.com<mailto:notifications@github.com>> wrote:


So,
I'd like to run OpenCL applications with 2 or more Vega 64's on my Supermicro X10QBI, which is part of Intel's mission critical server line up. In the readme it says:
Current CPUs which support PCIe Gen3 + PCIe Atomics are:

Intel Xeon E5 v3 or newer CPUs;
Intel Xeon E3 v3 or newer CPUs;
Intel Core i7 v4, Core i5 v4, Core i3 v4 or newer CPUs (i.e. Haswell family or newer).
AMD Ryzen CPUs;

So no Xeon E7 v3 or newer CPUs?
However the Xeon E7 v3 is part of the Haswell family

Could someone or Radeon clarify?

**Comment by Bliss3d** [comment]
Thanks;
Would be nice to see it on the list - for the 3 people it applies to
Best regards

**Comment by gstoner** [comment]
It was on the hardware list 
https://github.com/ROCm/ROCm.github.io/blob/master/hardware.md

**Comment by Bliss3d** [comment]
Just to add some information - I tested vega 64 & rocm on a Xeon E7-4890V2 and it seems to be work using PCIE 3.0 Atomics
