### ISSUE TITLE
Vega Frontier Edition idle stats a bit too hot?

### ISSUE THREAD

**Issue by boberfly** [RadeonOpenCompute/ROCm#403]
Hi all,

I've been checking rocm-smi on the heat/voltage/clock/fan speeds while the card is idle, and from what I see it seems to default at having the clock at max which sets the average temperature to a whopping 79.0c
```
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  1   79.0c   31.0W    1528Mhz  945Mhz   18.82%   auto      0%       
  0   N/A     N/A      N/A      N/A      0%       N/A       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
```
I'm in Vancouver and it is getting a bit warmer granted, but it seems a little too hot to me... :)

When I run this manually:
```
rocm-smi --setperflevel low
```
I get much better temperatures and average power readouts:
```
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  1   36.0c   3.0W     852Mhz   167Mhz   12.94%   low       0%       
  0   N/A     N/A      N/A      N/A      0%       N/A       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
```
Do I need to do anything special for it to go into this lower profile without doing this manually every time? I use this card as purely a compute device, the display is handled by a Quadro k2000 so nothing should be taxing it that I know of, no GUI/X11 is being displayed out of it.

Cheers!

**Comment by gstoner** [comment]
Is this ROCm 1.8  which Distro  which Linux kernel

**Comment by boberfly** [comment]
Yep I'll be more exact:
ROCm 1.8.0 beta
Ubuntu 18.04 LTS
Kernel 4.13 (from Ubuntu 17.10 using rock-dkms 1.8.0 to build the module)

Cheers

**Comment by gstoner** [comment]
Thank you... this helps

**Comment by gstoner** [comment]
Ok did you make sure you're using the right firmware package?

**Comment by boberfly** [comment]
Doing a quick checksum on vega10_uvd.bin SHA256:
```
519382f062481d5b189a14235f51ec7fbe56830564e5d42cf1d2aee126e51a37
```
vega10_vce.bin SHA256:
```
044f312bdcab9bdb8ef4403127606efc8ec0c3e3a205f1853c175db2b39591f8
```

**Comment by gstoner** [comment]
Sorry I was traveling this week.  We released ROCm 1.8 official release this week.

**Comment by jlgreathouse** [comment]
Hi @boberfly 

With the recent release of ROCm 1.9.1, do you still see this issue? I just checked one of our test boxes with a Vega Frontier Edition, and I see it idling as expected.

If you still see the issue, I can hopefully walk you through some steps to either alleviate or root cause the issue.

**Comment by boberfly** [comment]
@jlgreathouse hi Joseph, actually I think this isn't a problem now for awhile, I do monitor temperatures from time to time and artificially limit it but I think it's because of infinite looped apps like indigo render or blender cycles. Killing them restores power/temps that are idling correctly without the artificial limit.

I think we can safely close this issue then. Cheers!
