### ISSUE TITLE
Installing ROCm in Ubuntu 14.04.5 on Kaveri 7850K APU

### ISSUE THREAD

**Issue by tqta** [RadeonOpenCompute/ROCm#41]
Hi, 

I'm having trouble in installing ROCm in Ubuntu 14.04.5. I did a fresh installation of Ubuntu. I turned off the lightdm to make sure there was no conflict with the driver to be installed. 

I got the error message 'The system is running in low-graphics mode. Your screen, graphics card and input device settings could not be detected correctly'. It seems the driver is not detected. 

I also got a warning "[AMD VI] unable to write to IOMMU perf counter" although I turned on the IOMMU in my bios which is Asus A88X-Pro. 

Has anyone had the same problem before? 

Thank you!

**Comment by briansp2020** [comment]
What version of BIOS are you using?

**Comment by tqta** [comment]
Hi Brian, 

The BIOS version I'm using is 2603 that is the latest version on Asus website.

**Comment by briansp2020** [comment]
I used to use 7850K APU + Asus A88X-Pro with ROCm 1.2. But now I'm using Intel + Fiji setup. Not sure what the problem maybe.

**Comment by arodrigx7** [comment]
What are the actual symptoms of your issue? I.e. what happens when you try to run the vector_copy sample?

Also what is on your full dmesg?

Btw, we are not going out of our way to break Kaveri support, but it is technically an unsupported platform for the current ROCm version. For more info on supported hardware you can look here:
https://radeonopencompute.github.io/hardware.html

**Comment by tqta** [comment]
I couldn't get into the log-in window, and the Ubuntu warned "The system is running in low-graphics mode". I suspect the OS didn't detect the driver correctly. 

Andres, the list does not include APU. Will ROCm support future APUs (Carizzo and later)?

**Comment by emerth** [comment]
@tqta - you are describing a problem almost certainly resulting from not having the Ubuntu default AMD video driver loaded, and that's not a ROCm problem. 

If you are installing ROCm from repo using instructions on page https://github.com/RadeonOpenCompute/ROCm, then just do a new clean Ubuntu install and do not disable stuff, and follow the instructions. Reboot after doing the install.

Compiling/linking like so should work:

hcc `hcc-config --cxxflags` foo.cpp -c -o  foo.o
hcc `hcc-config --ldflags` foo.o --amdgpu-target=AMD:AMDGPU:7:0:0

"[AMD VI] unable to write to IOMMU perf counter" -- I get that too, not 100% why, but it does not seem to cause problems.
