### ISSUE TITLE
2 RX 470s on ROCm 1.8 : OpenCL only sees single device

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#412]
I have one GPU on PCI 3 slot, and one on PCI 2.
But clinfo only reports one device.  
My understanding was that 1.8 removes the PCI 3 restriction.

**Comment by gstoner** [comment]
Aaron, 
     We said this is the case only with Vega10 currently.  Fiji and Polaris right now still need PCIe Gen3 and PCIe Atomics, we looking into this
