### ISSUE TITLE
ROCm 1.8 Profiler not working

### ISSUE THREAD

**Issue by todxx** [RadeonOpenCompute/ROCm#414]
Just update to ROCm 1.8, and I am having troubles getting the profiler to work with the -A option.  So far attempting to run the profiler results in the following error:
```
LLVM ERROR: out of memory
```
This happens on all programs I've tried to profile, and doesn't seem to depend on the GPU that is being used (I've tried on both a Vega and Polaris GPU).  At the time of running this, the system had 15GB of free memory.

The -C option for perf counters seems to work normally.

Let me know if there's any more info I can provide to help reproduce this problem.

**Comment by syifan** [comment]
I am also experiencing similar problems. After upgrading to ROCm 1.8, rocm-profiler always reports "Failed to generate profile result" no matter what argument I use.

**Comment by phani544** [comment]
@todxx & @syifan , can you please post the application and exact steps you used ?

**Comment by chesik-amd** [comment]
Thanks for this report.  We are currently investigating and hope to have a fix soon

**Comment by djygithub** [comment]
Using the public container rocm/tensorflow:rocm1.8.0-v2 with the -A option works just fine.

`/opt/rocm/profiler/bin/rcprof -A -o mm.atp ./MatMul 1000
root@prj47-rack-39:/root# /opt/rocm/profiler/bin/rcprof -A -o mm.atp ./MatMul 1000
Radeon Compute Profiler V5.4.6797 is enabled
------ Matrix Dimensions ------
dims a,b = 1000 , 1000
info: allocate host mem ( 11.44 MB)
info: device  mem ( 11.44 MB)
Filling in 2D arrays a and b
Filling Complete
------- CUDA Parameters -------
NUM_THREADS(  16,  16,   0)
       blks(  63,  63,   0)
-------------------------------

Calling CPU Matrix Multiply

CPU took 0.000000 seconds as computed by gettimeofday() function

CPU Matrix multiplication completed. Time to launch GPU kernel.

GPU took 0.234952 seconds as computed by CudaEvent function

Experiment Done.
-------------------------------
Session output path: /root/mm.atp
root@prj47-rack-39:/root# ls -al mm*
-rw-r--r-- 1 root root 367644 Jun  5 21:15 mm.atp
root@prj47-rack-39:/root#


root@prj47-rack-39:/root# apt show rocm-libs
Package: rocm-libs
Version: 1.8.118
Status: install ok installed
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 1024 B
Depends: rocfft, rocrand, hipblas, rocblas
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Radeon Open Compute (ROCm) Runtime software stack

root@prj47-rack-39:/root#

/opt/rocm/profiler/bin/rcprof --atpfile mm.atp --tracesummary
Generating summary pages...
Parsing API trace file...
root@prj47-rack-39:/root#
root@prj47-rack-39:/root# ls -al *.html
-rw-r--r-- 1 root root 47333 Jun  5 21:22 mm.HSAAPISummary.html
-rw-r--r-- 1 root root 37139 Jun  5 21:22 mm.HSABestPractices.html
-rw-r--r-- 1 root root 35905 Jun  5 21:22 mm.HSAKernelSummary.html
-rw-r--r-- 1 root root 36385 Jun  5 21:22 mm.HSATop10DataTransferSummary.html
-rw-r--r-- 1 root root 35502 Jun  5 21:22 mm.HSATop10KernelSummary.html
root@prj47-rack-39:/root#
`

**Comment by tekcomm** [comment]
I am building right now the other three versions of rippa with codexl  kernel patched and working along with a mesa/amdgpupro and a andgpupro version

**Comment by jlgreathouse** [comment]
Hi all,

Note that we recently released a new profiling framework, [rocprofiler](https://github.com/ROCm-Developer-Tools/rocprofiler). This is a new mechanism that will sit under other profilers to allow them to get access to our GPUs' and runtimes' performance monitoring features. For example, this will allow tools like PAPI to get access to AMD GPU hardware performance counters.

You may also be interested in it because it includes tools for directly gathering counters yourself. Because `rocprofiler` is primarily intended as a framework, these tools may not be as clean and easy to use as things like our CodeXL GUI-based programs. However, if you're interested in performance monitoring on ROCm, you may find it interesting to explore this tool.

#497 includes some extra discussion about this.

**Comment by jlgreathouse** [comment]
Looks like I responded and closed just slightly too quickly.

Please note that with the release of ROCm 2.0 and [RCP 5.6](https://github.com/GPUOpen-Tools/RCP/tree/v5.6), we have now integrated RCP (a.k.a. `rcprof` discussed earlier in this thread) to work by using `rocprofiler`. This integration should have cleared up a number of the previous issues you may have had with profiling GPU kernels on the ROCm software stack. You should be able to install it by installing the `rocm-profiler` package on Ubuntu, CentOS, and RHEL.

Please try it out!
