### ISSUE TITLE
How to get Temperature and Fan speeds wit ROCm driver

### ISSUE THREAD

**Issue by bizlevel** [RadeonOpenCompute/ROCm#417]
Modern GPU cards has a lot control point for temperature and several fan speed.
Maybe it is possible to control fan speed, and LED activity?
And native sensors/lm-sensors - very primitive.
Thanks.

**Comment by gstoner** [comment]
We are working on new System Management API, to update this it what the Linux driver team promoted to access the critical registers

**Comment by gstoner** [comment]
This is where the new library will be placed it has monitoring feature now 
https://github.com/RadeonOpenCompute/rocm_smi_lib
