### ISSUE TITLE
ROCm 1.3

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#42]
I have two RX 470s on my system, and I am really looking forward to the 1.3 release.
Currently, using both 470s causes a race condition on windows 10, and the system often
freezes.  So, I can't use both in production - have to stick with single card for now.

When you do release 1.3, could you please give detailed install instructions for XUbuntu system?
(XUBuntu 16.04)  Last time I tried, I was not able to get AMDGPU-PRO driver working - no cards were
recognized.

Thanks!!

**Comment by gstoner** [comment]
ROCm does not use the AMDGPU-Pro driver foundation it is base off the AMDGPU Open Driver.    1.3 will be released with Ubuntu 16.04 support.



greg
On Oct 30, 2016, at 8:41 AM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


I have two RX 470s on my system, and I am really looking forward to the 1.3 release.
Currently, using both 470s causes a race condition on windows 10, and the system often
freezes. So, I can't use both in production - have to stick with single card for now.

When you do release 1.3, could you please give detailed install instructions for XUbuntu system?
(XUBuntu 16.04) Last time I tried, I was not able to get AMDGPU-PRO driver working - no cards were
recognized.

Thanks!!

**Comment by boxerab** [comment]
Thanks.
