### ISSUE TITLE
ROCm 1.7.1 & 1.8 & 1.9: 16.6% slower than amdgpu-pro 18.10 with sgminer-gm

### ISSUE THREAD

**Issue by grische** [RadeonOpenCompute/ROCm#421]
For both ROCm 1.7.1 and 1.8.0, mining has a huge performance regression relative to amdgpu-pro (almost all versions) of about 20%:

```
GPU:  Radeon RX 470
ROCm      :  20.0 MH/s
amdgpu-pro:  24.0 MH/s
```

Used software:
* Ubuntu 16.04 with Kernel 4.13.0-41
* SGMiner-GM 5.5.5:
 https://github.com/genesismining/sgminer-gm/releases/tag/5.5.5
* OpenCL Kernel: 
 ["ethash-new"](https://github.com/genesismining/sgminer-gm/blob/bc138413d9098d6ed285df1bdebc70b47f69bcac/kernel/ethash-new.cl)
* ROCm 1.8.0 via
 http://repo.radeon.com/rocm/apt/debian/
* amdgpu-pro 18.10
 https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-18.10-572953.tar.xz

sgminer.conf:
```
{
    "pools": [
        {
            "user": "0x1234567890abcdef1234567890abcdef12345678",
            "url": "stratum+tcp://eth-eu1.nanopool.org:9999/",
            "profile": "eth",
            "pass": "x"
        }
    ],
    "profiles": [
        {
            "gpu-threads": "2",
            "name": "eth",
            "xintensity": "1024",
            "algorithm": "ethash-new",
            "worksize": "128"
        }
    ]
}
```

Do you need any more information to address the issue?

**Comment by amdcoffey** [comment]
In ethash-new:

```
#define KECCAK_PROCESS(st, in_size, out_size, isolate)    do { \
    for (int r = 0;r < (23);) { \
        if (isolate) \
            KECCAKF_1600_RND(st, r++, 25); \
    } \
    KECCAKF_1600_RND(st, 23, out_size); \
} while(0)
```

```
 #define KECCAK_PROCESS(st, in_size, out_size, isolate)    do { \
    for (int r = 0;r < (23);) { \
            KECCAKF_1600_RND(st, r++, 25); \
    } \
    KECCAKF_1600_RND(st, 23, out_size); \
} while(0)
```

Can you remove line 190  and see if you still have the performance issue.

**Comment by amdcoffey** [comment]
Adding an unroll on the same loop on ROCm full stack has also improved the rates for me RX 470 and RX 580

**Comment by grische** [comment]
@amdcoffey Neither removing ``if (isolate)`` nor adding a ``_Pragma("unroll")`` nor doing both, does influence the hashrate sufficiently (maybe 1% difference).

**Comment by gstoner** [comment]
Can you try this setting denorms to zero with the compiler flag -cl-denorms-are-zero

Gfx9 and later: denorms on by default; you can turn them off with -cl-denorms-are-zero
Gfx8 and earlier – denorms are off by default

**Comment by grische** [comment]
@gstoner the bug above only appears with Polaris (gfx8). If I understood you correctly, denorms are always zero in gfx8, so I don't think the `-cl-denorms-are-zero` would make any difference?

**Comment by gstoner** [comment]
@grische  I see that now.   Have you tried 18.20 AMDGPUpro

**Comment by gstoner** [comment]
We have compiler fix in for LC https://reviews.llvm.org/D48246

**Comment by grische** [comment]
The situation is unchanged with ROCm 1.9. 

I assume the above (merged) compiler change is not included in the ROCm 1.9 packages?

**Comment by jlgreathouse** [comment]
It's been quite a while -- these changes should have merged in. Are you still seeing this issue as of e.g. ROCm 2.2?

**Comment by ROCmSupport** [comment]
This issue is very old and fixed long back around ROCm 3.x time.
Am closing it now.
Request you to open a new issue if you find any.
Thank you.
