### ISSUE TITLE
Pytorch building instructions?

### ISSUE THREAD

**Issue by victor-felicitas** [RadeonOpenCompute/ROCm#422]
Dear ROCm team, congrats with successful Pytorch integration!
I am eager to try it with my AMD gpu, but could not find any instructions.

In particular, default instruction assumes
_# Add LAPACK support for the GPU
conda install -c pytorch magma-cuda80 # or magma-cuda90 if CUDA 9_

What should I do to install Pytorch with AMD gpu support?

**Comment by gstoner** [comment]
Facebook will post the instruction on their site how to do install   Currently you have to build from Source.
