### ISSUE TITLE
Use ROCm on ubuntu VM hosted on windows ??

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#43]
Is this possible ? Or does ubuntu need to be on bare metal.

**Comment by gstoner** [comment]
Honestly we have not tired it yet on Windows via vm yet.    We been heads down on core features.



Greg

On Oct 30, 2016, at 8:44 AM, Aaron Boxer <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this possible ? Or does ubuntu need to be on bare metal.

**Comment by boxerab** [comment]
Thanks. I will just dual boot windows/linux
