### ISSUE TITLE
Rig with both rx580 and Vega64 cards

### ISSUE THREAD

**Issue by AgentRX** [RadeonOpenCompute/ROCm#431]
I've rig with 3 Vega64 and 3 RX 580 (two of them the same). Here are results of commands:
`lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Device 1902 (rev 06)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev e7)
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c1)
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev e7)
09:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c1)
0c:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 687f (rev c1)
0d:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 67df (rev e7)

clinfo | grep "Device Board"
  Device Board Name (AMD)                         Device 67df
  Device Board Name (AMD)                         Device 687f
  Device Board Name (AMD)                         Device 687f
  Device Board Name (AMD)                         Device 687f
`
As you can see cliinfo doesn't see 2 cards. And as a result TDXMINER see only 4 of 6 devices.

**Comment by rhlug** [comment]
Put 2x Polaris on the x16 slots.  And put 3x vegas on the 1x slots.  You should be able to get 5 cards detected at least.
