### ISSUE TITLE
Unable to install ROCm 1.8.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by nishagandhi** [RadeonOpenCompute/ROCm#445]
Hi, I have been following instructions to install ROCm 1.8.1 (from https://rocm.github.io/ROCmInstall.html), all the instructions prior to **sudo apt-get install rocm-dkms**  were executed successfully. However, its unable to locate the package rocm-dkms :  

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rocm-dkms

**Comment by gstoner** [comment]
Can you look at see what Linux kernel your running 4.15 ??

**Comment by min0ru** [comment]
Are you sure that you added rocm deb repository?

wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
sudo apt update
