### ISSUE TITLE
Request for ISA or preview of upcoming instructions for Vega 20

### ISSUE THREAD

**Issue by nevion** [RadeonOpenCompute/ROCm#448]
In particular I'm interested in fp64 advancements, and math function support but I'd like to know what other new instructions might be arriving.  For example, with vega10 we had cross-lane operations (maybe this was just when rocm made it available, and thereabouts of fiji had?) and fp16 vectorized types.

**Comment by gstoner** [comment]
Nevion,  you know this we can not pre-release information like this.

**Comment by nevion** [comment]
@gstoner I look here: 
https://reviews.llvm.org/search/query/SOt5labuz5hE/#R
http://llvm.org/svn/llvm-project/cfe/trunk/include/clang/Basic/BuiltinsAMDGPU.def

I don't really see a whole lot of new stuff/intrinsics which leads me to believe not all that much is in the works unless you guys are keeping it internal only.

Is there anything marketing et al can clear that is otherwise boring details on upcoming operation types?  Cross-lane operations kind of fit that, for instance.  Even hardware support for fmad/fdiv at double precision would be a great advancement.  If not inline to this topic, maybe you guys can organize and talk about it more properly at gpuopen.com?

**Comment by jlgreathouse** [comment]
We have released the new ISA guide for the Vega 20 GPUs: https://gpuopen.com/wp-content/uploads/2019/11/Vega_7nm_Shader_ISA_26November2019.pdf
