### ISSUE TITLE
Support for new Ubuntu 16.04 hwe kernel version (4.15.0)

### ISSUE THREAD

**Issue by krrk** [RadeonOpenCompute/ROCm#449]
Ubuntu 16.04 was updated today to the 4.15 kernel from 18.04, but there were no updates from rocm-dkms so naturally it failed to build for the new kernel version.

> Processing triggers for linux-image-4.15.0-24-generic (4.15.0-24.26~16.04.1) ...
> /etc/kernel/postinst.d/dkms:
> ERROR (dkms apport): kernel package linux-headers-4.15.0-24-generic is not supported
> Error! Bad return status for module build on kernel: 4.15.0-24-generic (x86_64)
> Consult /var/lib/dkms/amdgpu/1.8-151/build/make.log for more information.

[make.log](https://github.com/RadeonOpenCompute/ROCm/files/2155780/make.log)

I realize that this new kernel release is ahead of the proposed schedule (says Aug. 2018) as can be seen [here](https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Kernel.2FSupport.A16.04.x_Ubuntu_Kernel_Support), but will we seen an update to ROCm soon?

**Comment by preda** [comment]
While you're at it, please also consider verifying that ROCm works with kernel 4.17 (released) and 4.18 (RC). http://kernel.ubuntu.com/~kernel-ppa/mainline/

**Comment by sunway513** [comment]
@krrk , here's the steps you can try to work it around until we have official recommendations:
1. install 4.13 kernel:
`sudo apt update && sudo apt install -y linux-headers-4.13.0-32-generic linux-image-4.13.0-32-generic linux-image-extra-4.13.0-32-generic linux-signed-image-4.13.0-32-generic
`
2. remove 4.15, then reboot:
`sudo apt autoremove -y linux-image-generic-hwe-16.04 linux-image-4.15.0-24-generic linux-headers-4.15 linux-modules-4.15 && sudo reboot
`
3. remove rock-dkms:
`sudo apt autoremove -y rock-dkms
`
4. install rocm-dkms, reboot:
`sudo apt install rocm-dkms && sudo reboot`

**Comment by brian-maher** [comment]
@sunway513 for some of us, the 4.13 kernel is unworkable. The latest release seems to proclaim support for many more egpu configurations, but the vast majority of thunderbolt 3 pci-e enclosures are unusable in 4.13.

Tbh, I'm starting to regret my decisions to bet on amd cards.

**Comment by krrk** [comment]
Thanks @sunway513, I'm sure that your solution would work, but you should definitely select the latest 4.13 kernel version 4.13.0-45 for all the latest security updates. I currently have just set `GRUB_DEFAULT` in `/etc/default/grub` to select a 4.13 kernel. This works for now, but I believe the 4.13 security updates end this month with the end of support for Ubuntu 17.10.

**Comment by 3D-360** [comment]
>Tbh, I'm starting to regret my decisions to bet on amd cards:   brian-maher

I know the feeling, but I'm hanging in there because I see the potential (especially with the APUs).  It sounds like Ubuntu 18.04 and ROCm 1.9 is what we are waiting for.  Imagine how nice it will be once ROCm & 18.04 work out of the box!  I have put my ROCm work on hold while I work on other parts of my project, I hope that you can do the same.

**Comment by sunway513** [comment]
@krrk we are going to officially support Ubuntu16.04 with 4.15 kernel as well as Ubuntu18.04 in the ROCm1.9 release. 
And you can surely stick on different 4.13.x minor kernel releases, what I've suggested above is the one that known-to-work on my personal setup.

**Comment by odellus** [comment]
I'm trying to follow the instructions @sunway513 , and my /opt/rocm folder is empty. Nothing is installed.

**Comment by sunway513** [comment]
@odellus please try to verify if you have added the ROCm apt repository, steps here:
https://github.com/RadeonOpenCompute/ROCm#add-the-rocm-apt-repository

**Comment by odellus** [comment]
Oh yeah u know that I've got rocm in my sources list. I'm *re*-installing

**Comment by odellus** [comment]
The Ubuntu kernel update to 4.15 on 16.04 broke my ROCm

**Comment by odellus** [comment]
This is what I get every, single, time.
```
rocminfo: error while loading shared libraries: libhsa-runtime64.so.1: cannot open shared object file: No such file or directory
```
I've reinstalled rocm-dkms at least a dozen times at this point, trying to figure out what package includes libhsa-runtime64.so.1, trying to make sure it actually sees that package and can load the library above when I'm installing rocminfo.

**Comment by jedwards-AMD** [comment]
Can you look in the /opt/rocm/hsa/lib directory and see if you have that library? Also, can you check that that the runtime is in your ldconfig path:
`ldconfig -p | grep rocm'
.
You should see libhsa-runtime64.so.1 in the list.

**Comment by odellus** [comment]
Okay so whatever I did a baker's dozen was the charm in getting rid of the libhsa-runtime issue. I didn't have the library installed at first, then even after I did it still wouldn't register. 
I think I installed it *before* I installed rocm-dkms. So many times through, hard to be sure at the point. Guess I need a lab notebook.

Now I'm seeing 
```rocminfo: error while loading shared libraries: libhsakmt.so.1: cannot open shared object file: No such file or directory
```
So I'm purging the previously installed hsakmt* packages now. The instructions at https://github.com/RadeonOpenCompute/ROCm#removing-pre-release-packages are out of date. 
`sudo apt purge libhsakmt` doesn't work anymore. Names changed.

**Comment by jedwards-AMD** [comment]
I have updated the instructions to remove the hsakmt-roct package. It looks like you got your driver up. I will close the ticket.

**Comment by sunway513** [comment]
With ROCm1.8.2 released, the Ubuntu 4.15 kernel is now supported by ROCm.

**Comment by odellus** [comment]
Awesome!

**Comment by krrk** [comment]
Thanks!
