### ISSUE TITLE
PCI-E Splitter Support?

### ISSUE THREAD

**Issue by TheKnightCoder** [RadeonOpenCompute/ROCm#450]
Hi, 
I am in the process of switching from windows to Ubuntu linux. The problem I am having is that the ROCm drivers do not work with my 4 in 1 PCI-E splitter. This worked fine with Windows. Is this a known issue? Is there any way to resolve this?

**Comment by gstoner** [comment]
ROCm support PCIe Switches.   It dependent on you  which GPU you are running.  If you running Polaris cards you need PCIe Gen3 base PCIe switch since they need PCIe Atomic support.   Not windows driver does not use PCIe Atomics

**Comment by TheKnightCoder** [comment]
@gstoner hmm it was for Vega 56 in a PCIe 3 slot. I have changed my motherboard now without splitter
