### ISSUE TITLE
ROCm 1.8.2 Beta

### ISSUE THREAD

**Issue by Bengt** [RadeonOpenCompute/ROCm#455]
There are packaged beta repositories for YUM and APT on the repository server:

    http://repo.radeon.com/rocm/misc/beta_1.8.2/

These repositories are intended for Ubuntu 16.04.4 LTS (Xenial Xerus) and RHEL/CentOS 7.4. I would be interested in other users' experience with this release.

**Comment by Bengt** [comment]
Digging through the issues here, I found @tekcomm having this release [running under Ubuntu 18.04 Bionic Beaver](https://github.com/RadeonOpenCompute/ROCm/issues/404#issuecomment-403643132).

**Comment by tekcomm** [comment]
I have it working :) Im posting instructions and howto but the script's online its a custom patched kernel. With the latest patches merged back to 4.16 from freedesktop.orgs git.

**Comment by tekcomm** [comment]
Sure it took about 140 hours but its done :package:

**Comment by Bengt** [comment]
Wow, that would be awesome. I would like to test it and there is also [more interest in such a script or HowTo](https://github.com/RadeonOpenCompute/ROCm/issues/384#issuecomment-403784584).

**Comment by tekcomm** [comment]
***You may have to change the grub boot line im on intel...
Burn it straight to a a usb boot it live and it will include opengl/mesa and amd's codexl V3
DO NOT INSTALL!
sudo add-apt-repository ppa:oibaf/graphics-drivers
apt-get -y update ; apt-get -y upgrade
sudo apt-get install mesa-vdpau-drivers
https://drive.google.com/open?id=1u4Yka0YjRBtyyeHBfkpFpKSCcBCFq8RS
Logout of X
LIBGL_ALWAYS_SOFTWARE=1 glxgears -info
For rocm just download 
https://drive.google.com/file/d/18ccS5X7r8ue71xUZrP6QCwX5KtdPlre_/view?usp=sharing
tar -xzvf lyra-xmr-support.tgz
./setup-lyra
Donations, coffee, tea, or if you would like more kickass software from me ;)
BTC: 1DoctorrNk8rhPGsuSppSVwdkcQ2PnvgDg
LTC: LbmeaZt8oxLuExphJn419C3nGjjj4q19wd
ETH: 0xf10d05cf2751dcea29e060b75bd47c038fd2abc8

**Comment by tekcomm** [comment]
=== Debugging and reporting problems ===== Debugging and reporting problems ===
If you have some problem with the drivers try running the application from the command line and see if there are graphics related warnings. Also type dmesg to see if there are other related informations here.= Then Do not send it to me send it to AMD or Freedestop.org and they will get around to it sometime....If you have a emergency and need a Doctor or are a college student of one of my other students from the past 30 years drop me a line otherwise send crypt or you wont make it past my AI BOT.:)

**Comment by tekcomm** [comment]
https://github.com/tekcomm/linux-image-4.19-wip-generic
Here are the latest vega updates fresh of the cloud compiler :)

**Comment by tekcomm** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=AMD-ROCm-1.8.2-Beta I
patched the 1.8.1 dkms kernel and have been running bionic for a few
months. The 1.8.2 is running on V3 of the live cd along with xmr-stack and
tdx as per a few requests along with on the opengl CodeXL I rewrote part of
the the kernel module to forward patch it.
https://gpuopen.com/compute-product/codexl/ . There is one richard stallman
version thats pure gpu. One thats both gpu and amd and one that is well amd
and amd and amd 2.1 1.2 1.1 and the intel opencl 1.2 amd :)
https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Vega-M-Kernel-Support
It also includes all the pp mask ones to modify the pp tables on the fly
like so. Seems to patch the kernel in the 18.04 of Ubuntu with what's
needed. Install the driver and pass the boot parameter
amdgpu.ppfeaturemask=0xffffffff. You can modify the eight core clock states
like so: echo "s $STATE_INT $MHz $mVOLT">
/sys/class/drm/card0/device/pp_od_clk_voltage The following changes in the
four memory clock states: echo "m $STATE_INT $MHz $mVOLT">
/sys/class/drm/card0/device/pp_od_clk_voltage Then commit your changes:
echo "c" > /sys/class/drm/card0/device/pp_od_clk_voltage A few other useful
tidbits ... this pins your state to the highest (I think): echo "high" >
/sys/class/drm/card0/device/power_dpm_force_performance_level This changes
your fan speed (where $FAN_SPDis an integer from 0 to 255): echo 1 >
/sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable && \ echo $FAN_SPD >
/sys/class/drm/card0/device/hwmon/hwmon0/pwm1 This limits your power draw:
echo $MICROWATTS > /sys/class/drm/card0/device/hwmon/hwmon0/power1_cap
Heres the video of it :) CodeXL https://www.youtube.com/watch?v=qsDAimkuYpc
Heres the existing info and manual with thread and cpu pinning tips. #361
<https://github.com/RadeonOpenCompute/ROCm/issues/361> V3 Is opengl, I
suggest using obiaf's repo if you install it. It is designed to be run
entirely from the ram at 2.2 gigs

https://github.com/tekcomm/linux-image-4.19-wip-generic

**Comment by tekcomm** [comment]
New kernel with patches for the vega is up from the 4.19.wip

**Comment by Bengt** [comment]
[1.8.2 has now left beta](https://github.com/RadeonOpenCompute/ROCm/pull/460), so I am closing this issue.

**Comment by Sayyiditow** [comment]
Does the latest 1.8.2 support vega undervolt?

**Comment by tekcomm** [comment]
see freedesktop.org

**Comment by gstoner** [comment]
Closing since 1.8.2 was released
