### ISSUE TITLE
ROCM 1.8.2 with kernels 4.15+

### ISSUE THREAD

**Issue by witeko** [RadeonOpenCompute/ROCm#461]
Who can tell me if the new ROCM 1.8.2 works with kernels 4.15+? And with ubuntu 18.04?

**Comment by shimmervoid** [comment]
It works

**Comment by witeko** [comment]
omg, my dreams came true

**Comment by sunway513** [comment]
ROCm1.8.2 supports Ubuntu16.04 with the 4.15 kernel.
The official Ubuntu18.04 support will be available in the ROCm1.9 release.
