### ISSUE TITLE
Biostar TB250 MB with USB Risers - Inactive OpenCL GPUs

### ISSUE THREAD

**Issue by G-Kumaran** [RadeonOpenCompute/ROCm#465]
I'm new to linux.
I have a Biostar TB250 MB with Pentium G4400 (supports gen 3 pcie) and 3 Vega 64 connected via USB risers.

Case 1 : Installed ubuntu 16.04 and followed all ROCM install instructions, all 3 vegas are detected, but **Helloworld has no output not even errors** and Tdxminer shows idle on all 3 gpus.
Please help ...

Case 2 : Tried and booted Rippa v3 on 32GB pendrive. But got the **"rc.local failed to list opencl platforms"** error on a black screen
Please help ...

**Comment by gstoner** [comment]
try rocminfo first to see if the driver is even installed.  you can also look in dmesg file to see if there is driver load failure.

**Comment by jlgreathouse** [comment]
I do not have your motherboard around, nor have I tried any GPUs connected through USB risers through PCIE x1 slots such as your motherboard supports.

Could you run the following application and show the output?
`/opt/rocm/bin/rocminfo`

Similarly, could you run the following series of commands to let us see how the PCIe configurations are set up on your system? (Note that you may need to run `sudo apt-get -y install build-essential` to run some of this):

```bash
lspci | grep VGA
```

```bash
mkdir ~/temp_lspci
cd ~/temp_lspci
wget https://mirrors.edge.kernel.org/pub/software/utils/pciutils/pciutils-3.6.1.tar.xz
tar -xf pciutils-3.6.1.tar.xz
cd pciutils-3.6.1
make -j `nproc`
sudo ./lspci -t
```

```bash
cd ~/temp_lspci/pciutils-3.6.1
sudo ./lspci -vv
```

Finally, could you try running the Helloworld test application after running the following command?
`export HSA_ENABLE_SDMA=0`

**Comment by G-Kumaran** [comment]
@gstoner ROCMinfo and CLinfo returns 3 devices and the OpenCL platform works fine.
@jlgreathouse Swapped pcie slots, found that only the x16 slot works..  x1(Gen 3) slots are detected but do not run OpenCL .. Any ways to bypass that restriction, cause i assumed the latest 1.8 supports that config?

"Starting with ROCm 1.8 we have relaxed the use of PCIe Atomics and also PCIe lane choice for Vega10/GFX9 class GPU. So now you can support CPU without PCIe Atomics and also use Gen2 x1 lanes."       -- From the readme

The vega 64s are GFX9 Class GPU and the PCIe slots are Gen 3(Gen 2 also supported) x1.

**Comment by jlgreathouse** [comment]
@G-Kumaran Thank you for the information. Could you try running the tests I described above? It will help me with debugging your issue.

**Comment by jlgreathouse** [comment]
@G-Kumaran Thank you for the added information. I edited your comment to help format the text.

If you execute `export HSA_ENABLE_SDMA=0` and then try to run the example applications, what happens?

**Comment by G-Kumaran** [comment]
@jlgreathouse  Thank you God !!!! :dancer: 

Before **export HSA_ENABLE_SDMA=0**
[2018-07-24 09:12:12] Stats GPU 0 - lyra2z: 6.677Mh/s (6.655Mh/s)  
[2018-07-24 09:12:12] Stats GPU 1 - 
[2018-07-24 09:12:12] Stats GPU 2 - 
[2018-07-24 09:12:12] Stats Total - lyra2z: 6.677Mh/s (6.655Mh/s) 

After **export HSA_ENABLE_SDMA=0**
[2018-07-24 09:14:24] Stats GPU 0 - lyra2z: 6.660Mh/s (6.629Mh/s)  
[2018-07-24 09:14:24] Stats GPU 1 - lyra2z: 6.694Mh/s (6.660Mh/s)  
[2018-07-24 09:14:24] Stats GPU 2 - lyra2z: 6.660Mh/s (6.626Mh/s)  
[2018-07-24 09:14:24] Stats Total - lyra2z: 20.015Mh/s (19.915Mh/s) 

Thank lots !!

**Comment by jlgreathouse** [comment]
Excellent, I'm glad we were able to find a solution for you.

Please note that you will either need to set that environment variable every time you open a shell (e.g. every time you boot to a command line, or in every virtual shell you open from a window manager), or you will need to set it in a script that is run every time you open a prompt, such as in `~/.bashrc`

I recommend the latter solution for your setup.

**Comment by G-Kumaran** [comment]
Sure, I'll set up a bash script for it !! Thx a ton !
