### ISSUE TITLE
Bad symlink to lib/libclang_rt.builtins-@CMAKE_SYSTEM_PROCESSOR@.a

### ISSUE THREAD

**Issue by BryantLam** [RadeonOpenCompute/ROCm#476]
ROCm 1.8.2

There's a bad symlink on lib/libclang_rt.builtins-* that incorrectly expands `CMAKE_SYSTEM_PROCESSOR` using `@x@` instead of `${x}`.

**Comment by b-sumner** [comment]
Hi @BryantLam , could you clarify where you are seeing this and on which release?  Do you have a patch or pull request?

**Comment by BryantLam** [comment]
Sorry. I should have been a bit more clear. This issue affects the ROCm 1.8.2 [RPM packages for CentOS](http://repo.radeon.com/rocm/yum/rpm/).

Specifically, if you go to this path:  `/opt/rocm/lib`, there's a broken symlink
from literal `/opt/rocm/hcc/lib/libclang_rt.bulitins-@CMAKE_SYSTEM_PROCESSOR@.a`
to `libclang_rt.builtins-@CMAKE_SYSTEM_PROCESSOR@.a` (the actual characters).

I assume (but have not confirmed) `@CMAKE_SYSTEM_PROCESSOR@` was supposed to be expanded with `${CMAKE_SYSTEM_PROCESSOR}`, but I haven't dived into looking where in the ROCm code (no patch/PR from me yet).

**Comment by scchan** [comment]
It will be addressed by this: https://github.com/RadeonOpenCompute/hcc/pull/825
