### ISSUE TITLE
Memory alocation rocm-smi

### ISSUE THREAD

**Issue by msabony1966** [RadeonOpenCompute/ROCm#481]
Hi,
any plan to monitor the GPU memory usage with rocm-smi?

Best Regards
Mazda

**Comment by sunway513** [comment]
Hi @msabony1966 , you can use the following script to monitor the memory allocation usages:
[rocm-mem.sh](https://github.com/RadeonOpenCompute/ROCm/files/2241768/rocm-mem.sh.txt)

**Comment by msabony1966** [comment]
thanks Peng
