### ISSUE TITLE
'apt update' failure due to gpg key expiration

### ISSUE THREAD

**Issue by llseek** [RadeonOpenCompute/ROCm#487]
Hi,

There's an 'apt update' failure due to gpg key expiration:

```
$ wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
$ sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
$ sudo apt update
Get:4 http://repo.radeon.com/rocm/apt/debian xenial InRelease [1,816 B]
Err:4 http://repo.radeon.com/rocm/apt/debian xenial InRelease
  The following signatures were invalid: KEYEXPIRED 1533155360  KEYEXPIRED 1533155360  KEYEXPIRED 1533155360
```

```
$ sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   4096R/1A693C5C 2016-08-01 [expired: 2018-08-01]
uid                  James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>
```

Regards,

**Comment by NEELMCW** [comment]
Yep,

I get the same error too 

Err:4 http://repo.radeon.com/rocm/apt/debian xenial InRelease                        
  The following signatures were invalid: KEYEXPIRED 1533155360  KEYEXPIRED 1533155360  KEYEXPIRED 1533155360
Hit:5 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done
W: GPG error: http://repo.radeon.com/rocm/apt/debian xenial InRelease: The following signatures were invalid: KEYEXPIRED 1533155360  KEYEXPIRED 1533155360  KEYEXPIRED 1533155360

**Comment by sunway513** [comment]
We have just renewed the gpg keys, it should work fine now after update it:
`wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -`

**Comment by jlgreathouse** [comment]
Just tested by following the directions given by @sunway513 . Can confirm the new keys work, so closing this ticket.

**Comment by mdPlusPlus** [comment]
Please update your documentation to contain the hash of the new key instead of the old one.

**Comment by sunway513** [comment]
@mdPlusPlus , thanks for the heads up, we have updated the message in the follow two more docs:

https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/InstallGuide.rst#debian-repository-apt-get

https://github.com/RadeonOpenCompute/ROCm/wiki#add-the-rocm-apt-repository

**Comment by jlgreathouse** [comment]
Hi @mdPlusPlus 

Thanks for pointing that out. I've updated the directions there as well.

**Comment by 3lt0nM0rais** [comment]
Hi guys,
The key has expired again, can you update please?
`
pub   rsa4096 2016-08-01 [SC] [expirado: 2019-08-02]
      CA8B B472 7A47 B4D0 9B4E  E896 9386 B48A 1A69 3C5C
uid           [ expirada] James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>

`
`Err:3 http://repo.radeon.com/rocm/apt/debian xenial InRelease
  As seguintes assinaturas eram inválidas: EXPKEYSIG 9386B48A1A693C5C James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>
Atingido:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Atingido:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Lendo listas de pacotes... Pronto                         
W: Erro GPG: http://repo.radeon.com/rocm/apt/debian xenial InRelease: As seguintes assinaturas eram inválidas: EXPKEYSIG 9386B48A1A693C5C James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>
`

Thank you.
