### ISSUE TITLE
Key expired error from ROCm debian repo

### ISSUE THREAD

**Issue by pradeepisro** [RadeonOpenCompute/ROCm#496]
I am getting the following error while doing `apt update`
        W: An error occurred during the signature verification. The repository is not updated and the previous 
        index files will be used. GPG error: http://repo.radeon.com/rocm/apt/debian xenial InRelease: The             following signatures were invalid: KEYEXPIRED [key]  KEYEXPIRED [key]      KEYEXPIRED [key]
        W: Failed to fetch http://repo.radeon.com/rocm/apt/debian/dists/xenial/InRelease  The following     signatures were invalid: KEYEXPIRED [key]  KEYEXPIRED [key]  KEYEXPIRED [key]

Is there any solution to that?

**Comment by jlgreathouse** [comment]
Yes, please try [adding the new GPG keys](https://github.com/RadeonOpenCompute/ROCm#add-the-rocm-apt-repository).

**Comment by pradeepisro** [comment]
Okay. That worked. Thank you
