### ISSUE TITLE
rocm.gpg.key sha1sum doesn't match.

### ISSUE THREAD

**Issue by soulhunter** [RadeonOpenCompute/ROCm#498]
Hello,

As I was installing updates I got a message about expired key.  Decided to fetch the new key:

wget http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key

But sha1sum doesn't match with that document:

f7f8147431c75e505c58a6f3a3548510869357a6  rocm.gpg.key

Documented sha1sum is:

f0d739836a9094004b0a39058d046349aacc1178 rocm.gpg.key

So, either documents are outdated (most likely), or the key is not the one it should be.

Thanks!

**Comment by jlgreathouse** [comment]
As documented on the [main ROCm README page](https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md), the correct sha1sum is `f7f8147431c75e505c58a6f3a3548510869357a6 rocm.gpg.key`.

If you were looking at the listing on the [rocm.github.io installation page](https://rocm.github.io/install.html) or on [the readthedocs site](http://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html#debian-repository-apt), I have updated both of those to include the new, correct, key.

Were you able to find the old key anywhere else? Thanks, and sorry for the difficulties this caused.

**Comment by soulhunter** [comment]
No, just those sites (and I could've sworn it was the old one on the README page as well, but anyway).  Thanks for updating that!
