### ISSUE TITLE
luxmark 3.1 doesn't work with RX Vega on pcie 2.0 platform

### ISSUE THREAD

**Issue by nioroso-x3** [RadeonOpenCompute/ROCm#501]
I'm testing ROCM on a 990FX+AMD FX 8320 platform. The computer has two MSI Vega 56 Airboost in the x16 slots.
Luxmark just shows a black picture as output, and hangs after the 120 second benchmark finishes.

Setting LD_LIBRARY_PROFILE to use the amdgpu-pro 18.20 OpenCL stack works fine.

I can run more tests if needed.

**Comment by jlgreathouse** [comment]
To verify, have you disabled PCIe atomics by running `export HSA_ENABLE_SDMA=0` in your bash prompt before running?

What version of ROCm is this? What OS?

In addition, could you run the following commands and attach their output? I know the list is big, but they'll hopefully help us recreate and or solve your problem, if the above recommendation does not work.

- `lsmod | grep amdgpu`
- `lsmod | grep amdkfd`
- `groups`
- `lspci | grep VGA`
- `lspci -vvv`
- `lspci -tv`
- After a reboot: `dmesg`
- `/opt/rocm/bin/rocminfo`
- `/opt/rocm/opencl/bin/x86_64/clinfo`

Thanks!

**Comment by nioroso-x3** [comment]
It's working now with HSA_ENABLE_SDMA=0. 
Please update the README and add that it is necesary if the platform doesn't support pcie 3.0.
I thought it was disabled automatically if the platform doesnt support atomics.

**Comment by jlgreathouse** [comment]
Can you point to which README you were  using?  The [main ROCm README](https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md) mentions this information twice.

However,  we have a number of different installation direction pages, and I need to work on synchronizing the information on them. Thanks!

**Comment by nioroso-x3** [comment]
This line:

"For Vega10 Users who want to run ROCm without supporting PCIe atomic support must set HSA_ENABLE_SDMA=0"

It should be something like:
"For Vega10 Users who want to run ROCm without supporting PCIe atomic support and also users with platforms with no PCIe atomic support, set HSA_ENABLE_SDMA=0"

I thought it was an option for debugging in platforms with pcie 3.0, not something that must be manually set.

**Comment by jlgreathouse** [comment]
Thank you for the recommendation. I have updated the main ROCm README to hopefully be more precise.

**Comment by rkothako** [comment]
Hi @jlgreathouse @nioroso-x3 
Its no where mentioned in ROCm wiki page https://github.com/RadeonOpenCompute/ROCm/wiki about 
SDMA disable for Vega10 when we keep in PCIe2 lanes.

_Snippet:_
Supported CPUs
Starting with ROCm 1.8 we have relaxed the use of PCIe Atomics and also PCIe lane choice for Vega10/GFX9 class GPU. So now you can support CPU without PCIe Atomics and also use Gen2 x1 lanes.
