### ISSUE TITLE
RHEL/CentOS repo is insecure

### ISSUE THREAD

**Issue by sdh4** [RadeonOpenCompute/ROCm#502]
The installation http://repo.radeon.com/rocm/yum/rpm/ is insecure and vulnerable to man-in-the-middle attacks that could install trojanized software because: 1. It uses http, not https, and 2. gpgcheck is disabled in the .repo file, presumably because the packages are not signed.

**Comment by duckinator** [comment]
It's been over a year since this issue was opened. It'd be really nice to _at least_ have it using HTTPS.

**Comment by ROCmSupport** [comment]
Hi @sdh4 
The changes are done and modified long back.
Request you to follow: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#centos-rhel

Thank you.
