### ISSUE TITLE
ROCm Platform not found error

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#508]
I have installed ROCm on both Debian 9 and Ubuntu 16 and 18. The error is persistent on both systems.

The hardware is:
- Mainboard: Gigabyte H110-D3A
- GPU: Asus Radeon RX580

**Comment by valeriob01** [comment]
I must say that the hardware in question "as configured" works with amdgpu-pro. So I don't think it is a configuration issue.

**Comment by jlgreathouse** [comment]
ROCm has different hardware requirements than amdgpu-pro, so I believe this could still be a configuration issue.

Could you tell me which of the PCIe slots on your motherboard you're using? I see that this is a board with a significnat number of PCIe gen 2 x1 slots: are you using these or the Gen 3 x16 slot?

Could you run the following commands for me?

- `lsmod | grep amdgpu`
- `lsmod | grep amdkfd`
- `groups`
- `lspci | grep VGA`
- `lspci -vvv`
- `lspci -tv`
- `lspci -n`
- After a reboot: `dmesg`
- `/opt/rocm/bin/rocminfo`
- `/opt/rocm/opencl/bin/x86_64/clinfo`

**Comment by valeriob01** [comment]
The five x1 slots are configured as Gen1, they are all used. The x16 slot is empty.
Thank you for helping.

**Comment by jlgreathouse** [comment]
Hi @valeriob01 

Unfortunately, we do not support PCIe gen 1 operation on Radeon RX 580. This is a Polaris (gfx8) class GPU, and the ROCm software stack requires PCIe gen 3 atomic support to work on these GPUs. We support PCIe gen 1 and 2 operation on our Vega (gfx9) GPUs by disabling the SDMA engines, but your device requires PCIe gen 3 with atomics support.

**Comment by valeriob01** [comment]
I will try to configure the hardware as you say with Gen3 and see if it works.

**Comment by jlgreathouse** [comment]
I apologize about the problems, though I should ask: When you say "reset the BIOS to gen 1" does that mean that your previous test was using the same x1 slots, but with a BIOS setting change?

I ask because, according to your motherboard's manual, all of the PCIe x1 slots are only Gen 2 compliant. The only Gen 3 compliant slot is the x16 at the top.

**Comment by valeriob01** [comment]
Yes I changed the bios setting. The bios setting is general for all the slots, there isn't in the bios a setting for every slot, but only one general setting.

**Comment by jlgreathouse** [comment]
Then I suspect that even after changing your BIOS setting, ROCm will not work on your system so long as all of your GPUs are in the x1 slot.

When using a Radeon RX 580, ROCm requires the GPU to be in a PCIe Gen 3 slot. The only PCIe Gen 3 slot in your motherboard (regardless of BIOS settings) is the x16 slot. As such, you will only be able to use at most one GPU -- and only then if it's in the x16 slot.

That said, I haven't tested this motherboard, so I am also not sure if that setting would work. If the motherboard manufacturer put that x16 slot behind a PCIe switch that does not properly forward atomics, ROCm may still not work no your GPU. It's worth testing, however.

**Comment by valeriob01** [comment]
Ok. Then I think I will not be able to use ROCm with this hardware. It is surprising to see so restrictive demands on the hardware. But please contact me when you think I can try again.

**Comment by jlgreathouse** [comment]
Hi @valeriob01 

I apologize that our software stack is unable to run on your hardware. We are working to build up support within ROCm, and with our current resources, we have focused our efforts on particular software domains (machine learning, enterprise computing, HPC, etc.). We want to continue to extend support, but there's only so much time in the day -- not that this reasoning helps you out much. :)

For reference, we require [PCIe Gen 3 atomics](https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/master/Installation_Guide/More-about-how-ROCm-uses-PCIe-Atomics.rst) in an effort to increase the performance of launching work to the GPU and receiving completion signals from the GPU. On supported platforms (such as in the domains we are targeting), this performance benefit can be a big win over more-broadly-supported-but-slower solutions.

That said, we have heard many requests from the crypto-mining community to support PCIe slots without atomics, specifically so folks can put as many GPUs into a box as they can fit. We've heard this, and have added a ROCm operating mode that bypasses this atomic requirement on our Vega 10 GPUs. We are still evaluating this feature on our gfx8 GPUs (such as your Polaris GPU), but we have not had the resources to make the changes and properly validate them at this time.

Thanks for your interest, and I apologize for not being able to meet your needs. If we get the proper support in place, I will try to get in contact.

**Comment by valeriob01** [comment]
I don't do crypto-mining. I do HPC and I am experimentally doing it with a multi GPU mainboard.

**Comment by gmls22** [comment]
@jlgreathouse I'm also on the GFX8 Series and trying to use my GPU for deep learning; 

Is there any ETA on when the completed patches might be released for GFX8 support? 

Is it possible to experiment with atomics disabled (without validation) on a GFX8 card by compiling manually, and if so, what parameters and environment variables would be required for testing?

**Comment by jlgreathouse** [comment]
Hello @gmls22 

With respect to your desire to run gfx8 series GPUs on deep learning workloads, I do want to note that Fiji, Polaris 10, and Polaris 11 (all gfx803) are supported in ROCm so long as your CPU and PCIe connections all support PCIe gen 3 with atomics. We *do* support these platforms, so I just want to make sure there's no confusion about that.

Unfortunately, I am unable to disclose any such roadmap information about supporting these devices without PCIe atomics.

I suspect that you would be unable to run any tests with atomics disabled. PCIe atomics are used for communication between the host and device when putting information into the user-level HSA queues. The command processor is the receiver of these packets, and AMD must modify the firmware running on this processor to be able to deal with user-level queues that will be accessed without PCIe atomics. AMD has made these firmware changes for gfx900 (Vega 10), but the public firmware for gfx803 does not include this.
