### ISSUE TITLE
About ROCM based AI denoiser for raytracing..

### ISSUE THREAD

**Issue by oscarbg** [RadeonOpenCompute/ROCm#514]
Hi I recieved an email around Siggraph week saying:
"AI Rendering: Machine learning with AMD’s ROCm and Radeon™ Pro WX Series GPUs can slash rendering times without sacrificing quality."
can point to more info on "AI rendering" presumably being an AI denoiser for raytracing using ROCM..
will be open sourced?
seeing more and more AMD new software being implemented on ROCM platform hope we see/hear some more news on ROCM/HIP Windows support sometimes this year probably at SC2018..
thanks..

**Comment by boberfly** [comment]
I was snooping about and saw this @oscarbg :
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal/pull/193

**Comment by oscarbg** [comment]
Thanks @boberfly !
Seems opencl based.. closing now..
