### ISSUE TITLE
HBCC Support

### ISSUE THREAD

**Issue by m0nik3r** [RadeonOpenCompute/ROCm#525]
Hi,

I was wondering what the current status of HBCC in the ROCM stack. I would like to enable my kernels to use >16GB memory.

Thanks!

**Comment by gstoner** [comment]
For ROCm we plan on properly supporting Page Migration, in conjunction with SVM, this give access to the full system memory from the GPU,  HBCC was soliton really for graphic for compute was not what was needed.

On Sep 8, 2018, at 10:10 PM, Andrew Hughes <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I was wondering what the current status of HBCC in the ROCM stack. I would like to enable my kernels to use >16GB memory.

Thanks!

**Comment by m0nik3r** [comment]
Thanks for the clarification. Is there a time frame when this feature might be available?

**Comment by ekondis** [comment]
> For ROCm we plan on properly supporting Page Migration, in conjunction with SVM, this gives access to the full system memory from the GPU, HBCC was a solution really for graphics and not for computing. Note the Core Hardware support GFX9 hardware supports paging

Wouldn't that be essentially the same for compute (HBCC functionality in ROCm)?

**Comment by gstoner** [comment]
No..
