### ISSUE TITLE
apt repo: rocm-dkms contains outdated firmware

### ISSUE THREAD

**Issue by marvind** [RadeonOpenCompute/ROCm#527]
The rocm-dkms package (currently ver 1.8.199) in the apt repo contains really old firmware, e.g., VCN version 1.24 for raven ridge (linux-firmware.git is at 1.73). From linux kernel 4.19 onwards, raven ridge fails to boot linux with the old firmware (see https://bugs.freedesktop.org/show_bug.cgi?id=107880).

Best regards
Marvin

**Comment by kentrussell** [comment]
The firmware will be updated in the 1.9 release which should be out later today

**Comment by jlgreathouse** [comment]
Hi @marvind 

ROCm 1.9.0 was released. Could you check and see if this fixes your issue?

**Comment by marvind** [comment]
Hi,

at least for raven the firmware is still the old one. md5sums:
b54c55d3bfe4ae27303012a48a7f1f1b  /usr/src/amdgpu-1.9-211/firmware/amdgpu/raven_vcn.bin
b54c55d3bfe4ae27303012a48a7f1f1b  amdgpu-1.8-199/firmware/amdgpu/raven_vcn.bin

should be (linux-firmware.git):
467978df90449115c306219500c32767  linux-firmware/amdgpu/raven_vcn.bin

**Comment by kentrussell** [comment]
Yep I can confirm that. Some of the firmware didn't get updated, so Raven VCN is still the one from 2017. I'll see if I can sneak it into 1.9.1, if not it'll be 1.9.2 but thanks for pointing this out. We have had some issues aligning some of the firmware through our automated testing and the VCN firmware slipped through the cracks.

**Comment by kentrussell** [comment]
It will have to be 1.9.2. 1.9.1 is already in testing and is very focused on Vega20.

**Comment by jlgreathouse** [comment]
I believe this was fixed as of ROCm 1.9.2, and (checking the md5sums for raven_vcn.bin) it should also be fixed in ROCm 2.0.0.
