### ISSUE TITLE
Does it support the following GPU: Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520]

### ISSUE THREAD

**Issue by Rahulchakwate** [RadeonOpenCompute/ROCm#528]

**Comment by Rahulchakwate** [comment]
I followed all the steps mentioned in the description.
But while running "rocminfo" command, I got the following error
`hsa api call failure at line 900, file: /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.8/rocminfo/rocminfo.cc. Call returned 4104`
Any suggestions what to do further?
My target is to use tensorflow with my GPU.
Thanks

**Comment by kentrussell** [comment]
Sun XT (Hainan) is GFX6, which is not supported in ROCm, We have experimental support for GFX7, but GFX8+ is the only official support for GPUs (see https://rocm.github.io/ROCmInstall.html for more info). The kernel will work, but the runtime (and rocminfo) doesn't have gfx6 support.

**Comment by JMadgwick** [comment]
From what I can see your chip (Sun XT) is first Gen GCN (gfx 6xx) and not supported. Unfortunately there is very little info around on it, but it might be second gen GCN (gfx 7xx) if it is then ROCm can be used but Tensorflow cannot.

I am sure that sadly you can **NOT** use ROCm Tensorflow. To use Tensorflow you need a [gfx 803, 900 or 906 GPU.](https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/tensorflow/core/common_runtime/gpu/gpu_device.cc#L749) No others and supported and if you use something else then Tensorflow will use the CPU instead.

The supported GPU list is meant to be updated at sometime but nobody has done it yet. Also more GPU support [looks like it will or was going to be added](https://github.com/RadeonOpenCompute/hcc/compare/feature_enable_what_rocm_supports) to HC but it's very unlikely this will ever mean Tensorflow working on gfx7xx Chips.
