### ISSUE TITLE
slow download speed

### ISSUE THREAD

**Issue by extraymond** [RadeonOpenCompute/ROCm#54]
It's downloading slow on my 60Mb network, while everything other than this repo is fast in apt-get.

**Comment by gstoner** [comment]
We are addressing this, the repo is on VM that hosted at AMD Datacenter we zero control over the networking stack which needs to be tuned. We are looking to move this new service in new year.

greg
On Dec 17, 2016, at 12:37 AM, extraymond <notifications@github.com<mailto:notifications@github.com>> wrote:


It's downloading slow on my 60Mb network, while everything other than this repo is fast in apt-get.

**Comment by extraymond** [comment]
@gstoner  Thx for your reply! I'm really looking forward to rocm.

**Comment by oscarbg** [comment]
yes please fix it.. spent good part of yesterday to get all the packages in this repo!

**Comment by gstoner** [comment]
Check out the new repo servers
