### ISSUE TITLE
Rocm 1.9: OpenCL 2.0 device side enqueue not working properly

### ISSUE THREAD

**Issue by Moading** [RadeonOpenCompute/ROCm#540]
Hi,
I have an up to date ubuntu 16.04.5 LTS running running Rocm 1.9.
Hardware: Supermicro X10SRA-F, Xeon E5-2680V3, Radeon Pro Duo (polaris, gfx803). The GPU (both ASICs) is recognized by clinfo. clinfo shows two GPUs and reports that device side enqueue is supported.

I am developing a multi GPU program that uses OpenCL 2.0 features like device side enqueue. The program runs fine when using the first GPU. If I start the program on the second GPU, clBuildProgram does not return. Instead, the following output is shown:

"Memory access fault by GPU node-1 (Agent handle: 0x1a25cc90) on address 0xa14dfc000. Reason: Page not present or supervisor privilege.
Aborted"

dmesg shows:
[ 1028.966950] Evicting PASID 32768 queues
[ 1028.966974] Evicting PASID 32768 queues
[ 1029.023599] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023622] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023627] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023632] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023636] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023641] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023646] kfd2kgd: update_invalid_user_pages: Failed to get user pages: -14
[ 1029.023783] Restoring PASID 32768 queues
[ 1029.023788] Restoring PASID 32768 queues
[ 1029.449905] Evicting PASID 32768 queues
[ 1029.449922] Evicting PASID 32768 queues
[ 1029.456686] Restoring PASID 32768 queues
[ 1029.456692] Restoring PASID 32768 queues
[ 1094.640268] amdgpu 0000:05:00.0: GPU fault detected: 147 0x0fe24802
[ 1094.640337] amdgpu 0000:05:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00A161FC
[ 1094.640426] amdgpu 0000:05:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x11048002
[ 1094.640539] amdgpu 0000:05:00.0: VM fault (0x02, vmid 8, pasid 32768) at page 10576380, write from 'TC4' (0x54433400) (72)
[ 1094.640684] Evicting PASID 32768 queues

I tried to write a small program to reproduce the problem. That little program works fine on my develop machine which runs OpenSuse and fglrx. It turns out that the test program does not run on Rocm at all.

Could anyone have a look at this?

Greetings!
[bug.tar.gz](https://github.com/RadeonOpenCompute/ROCm/files/2386903/bug.tar.gz)

**Comment by b-sumner** [comment]
Please note that OpenCL 2.0 device side enqueue is not yet officially supported in ROCm 1.9.

**Comment by Moading** [comment]
@b-sumner 
OK, I hope this repoducer helps to fix the broken parts. Can you tell me when device side enqueue will work? I need to give advice on which hardware to buy.

I have seen other posts where users asked for dates when certain things will work. It is very hard to convince anybody in a professional environment if there is no time line. I have been telling people that things will work in a few week with the next Rocm release but I was proven wrong repeatedly.

**Comment by gstoner** [comment]
It will be part of the Offical OpenCL 2.0 support,  yes this will help.  We were still finalizing this feature.   The goal is ROCm 2.0. for OpenCL 2.0 support.

**Comment by jlgreathouse** [comment]
@Moading I personally think it would also be interesting to get your feedback on the feature in the single-GPU case while it is in this unofficial/preview state. That might not fit into all of your application use-cases, but I know you've been waiting on this feature for a while.

**Comment by Moading** [comment]
Hi, I was just wondering if ROCm 2.0 will be the next release? I'm not even asking for a release date...

**Comment by jlgreathouse** [comment]
ROCm 2.0 is our next major release. I believe we will have a 1.9.2 point release before then, but 2.0 is our next major milestone. There won't be a 1.10.

**Comment by Moading** [comment]
Hi everybody,
I have installed Rocm 2.0 and as far as I can tell, OpenCl 2.0 device side enqueue is still not working. Could someone please try to reproduce the problem with the latest version of Rocm?

**Comment by jlgreathouse** [comment]
Hi @Moading 

I am unable to reproduce this problem on ROCm 2.0.

```
$ clinfo | grep "Driver version:"
  Driver version:                                2783.0 (HSA1.1,LC)
  Driver version:                                2783.0 (HSA1.1,LC)
$ clinfo | grep "Board name:"
  Board name:                                    Vega [Radeon RX Vega]
  Board name:                                    Fiji [Radeon R9 FURY / NANO Series]
$ ./a.out
prob: a clGetDeviceIDs -1
ncpus: 0 ngpus: 2
testing GPU 0
a
b
c
passed
done

testing GPU 1
a
b
c
passed
done

```

```
$ clinfo | grep "Driver version:"
  Driver version:                                2783.0 (HSA1.1,LC)
  Driver version:                                2783.0 (HSA1.1,LC)
$ clinfo | grep "Board name:"
  Board name:                                    Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
  Board name:                                    Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
$ ./a.out
prob: a clGetDeviceIDs -1
ncpus: 0 ngpus: 2
testing GPU 0
a
b
c
passed
done

testing GPU 1
a
b
c
passed
done

```

**Comment by Moading** [comment]
Hi @jlgreathouse

thanks for looking into this!
The reproducer gets stuck after calling clFinish on my system.
The output of "clinfo | grep Driver" is the same as on your system.
The output of "clinfo | grep Board" is "Device 67c4". This looks strange as the format differs from your output. Could this be a board specific problem? Do you have a Radeon Pro Duo to test?

Is there any other information I could post to help tracking down the problem?

**Comment by jlgreathouse** [comment]
Ah, so the error you are seeing has changed. I apologize. You did not say this in your previous post, so I spent the day trying to reproduce the wrong error.

The output of `clinfo | grep Board` will change depending on the [PCI IDs installed on your system](https://linux.101hacks.com/unix/update-pciids/). If you run `sudo update-pciids` you will likely get a more nicely formatted output of the device(s) on your system.

At the moment, I do not have access to a Radeon Pro Duo to test this, nor will I likely have the time in the very near future to find one. I will try to keep you updated if this changes.

**Comment by Moading** [comment]
Hi @jlgreathouse 

after running "sudo update-pciids", the output of "clinfo | grep Board" is "Ellesmere [Radeon Pro WX 7100]". Do you have a Radeon Pro WX 7100 to test? I have a Radeon R9 390 here but there are firware issues with Rocm 2.0. I don't have time for the "build yourself" work around you posted.

I don't see how the error I'm seeing has changed. The reproducer does not complete. By adding output after ever relevant line in the reproducer I found that the program does not return from the call to clFinish.

I will give this another try with a fresh install after the next Rocm release. If you have any other ideas in the mean time, just let me know!

**Comment by Moading** [comment]
Hi @jlgreathouse

could you please tell me what os and kernel you used for the test where the reproducer works?

**Comment by Moading** [comment]
I am closing this issue because there is a new ROCm release now. For me this issue is not fixed yet.
