### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by acowley** [RadeonOpenCompute/ROCm#544]
The README includes broken links to the following "frozen for the rocm-1.9.0 release" repositories: `llvm`, `lld`, and `ROCm-Device-Libs`. Can appropriate revisions be linked if the branches can not be made?

**Comment by jlgreathouse** [comment]
Hi @acowley 

I can confirm that we haven't properly pushed out the ROCm 1.9 source to these repos yet (or haven't marked the release commit, etc.). We're working internally with these teams to get this fixed up. Thanks for the heads up.

**Comment by saipoorna** [comment]
This is fixed now.
