### ISSUE TITLE
Missing info about how to install rocprof

### ISSUE THREAD

**Issue by misos1** [RadeonOpenCompute/ROCm#549]
Rocprof is not installed with rocm-dkms. I was able to get it only after using:
```
sudo apt install rocprofiler-dev
```
And after that the location of rpl_run.sh was not `/opt/rocm/rocprofiler/bin/rpl_run.sh` but `/opt/rocm/bin/rpl_run.sh`.

Seems old rocm-profiler and rocm-gdb are not working anymore as is stated in readme.md (for rocm-profiler).

**Comment by jlgreathouse** [comment]
This information should be up to date in the README now. Thanks for pointing this out.
