### ISSUE TITLE
For an unknown Proprietary application - OpenCL - ROCm LLVM Compiler is spilling registers to  scratch registers where the PAL drivers did not with large performance hit.

### ISSUE THREAD

**Issue by liwoog** [RadeonOpenCompute/ROCm#553]
The PAL drivers used 114 VGPRs. 82 + 2 x 16 (two arrays of 16 floats).

The ROCm 1.9 driver uses scratch space instead and is ~60% slower.
                enable_sgpr_flat_scratch_init = 1
                workitem_vgpr_count = 82

**Comment by gstoner** [comment]
On what workload, I have zero idea where this is happing if we do not know the application you talking about.  Also, we need to understand which Driver version your using with AMDGPUpro

**Comment by liwoog** [comment]
ROCm 1.9 vs AMDGPU 18.30

**Comment by liwoog** [comment]
Proprietary app

**Comment by gstoner** [comment]
Are you doing aggressive inlining is so that would be why you see scratch memory being used, you are spilling your registers.  It is hard to address the issue when there is Zero information about the application.   

If we can not get more info I will have to close this issue

**Comment by gstoner** [comment]
I  am saying we need  reproducible to help sold you problem

**Comment by liwoog** [comment]
I understand the  difficulty. There is no inlining, I cannot post the code here. Please close the issue.

**Comment by liwoog** [comment]
Still begs the question why scratch space is used when enough VGPRs are available.

**Comment by liwoog** [comment]
workitem_private_segment_byte_size = 136

**Comment by gstoner** [comment]
We need to work with you directly and profile the application,  you can just contact me at my email address at amd.  greg "."  stoner
