### ISSUE TITLE
404s for some links to repos in Readme.md

### ISSUE THREAD

**Issue by rwvo** [RadeonOpenCompute/ROCm#56]
I'm getting 404s for the links to the github repositories for HCC, the Assembler stuff, HIP, and HIP examples.

**Comment by gstoner** [comment]
There were few more repo the team were supposed to tag on Friday.  I send note to the team that did not post.
On Dec 17, 2016, at 7:41 PM, René van Oostrum <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm getting 404s for the links to the github repositories for HCC, the Assembler stuff, HIP, and HIP examples.
