### ISSUE TITLE
Some pointers on how to use OpenCL + ROCm

### ISSUE THREAD

**Issue by rjfnobre** [RadeonOpenCompute/ROCm#57]
I just installed the latest version of ROCm and realised that there is no GPU device recognized by the "AMD Accelerated Parallel Processing" OpenCL platform.

I'm aware that there are some changes in relation to the way to use OpenCL with the ROCm driver.

For instance, the following Makefile works perfectly and a binary 'app' is produced.

**Makefile:**
EXECUTABLE := app
CFILES := app.c
OpenCL_SDK=/opt/AMDAPPSDK-3.0
INCLUDE=-I${OpenCL_SDK}/include
LIBPATH=-L${OpenCL_SDK}/lib/x86_64
LIB=-lOpenCL -lm
all:
        gcc -O3 ${INCLUDE} ${LIBPATH} ${CFILES} ${LIB} -o ${EXECUTABLE}
clean:
        rm -f *~ app

**Portion of code from 'app.c' that initializes the OpenCL platform:**
        errcode = clGetPlatformIDs(1, &platform_id, &num_platforms);
        if(errcode == CL_SUCCESS) printf("number of platforms is %d\n",num_platforms);
        else printf("Error getting platform IDs\n");
        errcode = clGetPlatformInfo(platform_id,CL_PLATFORM_NAME, sizeof(str_temp), str_temp,NULL);
        if(errcode == CL_SUCCESS) printf("platform name is %s\n",str_temp);
        else printf("Error getting platform name\n");
        errcode = clGetPlatformInfo(platform_id, CL_PLATFORM_VERSION, sizeof(str_temp), str_temp,NULL);
        if(errcode == CL_SUCCESS) printf("platform version is %s\n",str_temp);
        else printf("Error getting platform version\n");
        errcode = clGetDeviceIDs( platform_id,  CL_DEVICE_TYPE_GPU, 1, &device_id, &num_devices);
        if(errcode == CL_SUCCESS) printf("number of devices is %d\n", num_devices);
        else printf("Error getting device IDs\n");

The call to clGetDeviceIDs() results in an error, which does not surprise me given that the "AMD Accelerated Parallel Processing" OpenCL platform only recognizes the CPU (the GPU is not listed when executing 'clinfo').

The GPU is a R9 Nano (same Fiji core as the Fury X), wich to my undertanding is supported by ROCm.

My question is, how can I compile my OpenCL apps in a machine with ROCm installed?

Thanks in advance!

**Comment by boxerab** [comment]
I have the same question.

**Comment by jedwards-AMD** [comment]
This seems like a configuration or platform issue. Can you run a different type of sample, like a HIP or the vector_copy sample provided with the HSA runtime? Please provided the output of 'dmidecode' and 'uname -a'.

**Comment by boxerab** [comment]
Should I expect the AMD APP SDK samples to run with ROCm platform ?

**Comment by jedwards-AMD** [comment]
Support is currently limited. Images are not supported by the LC compiler, so any sample that requires image support will fail. This is also a developer preview, so other samples requiring special functionality may also encounter issues. The 'clinfo' command should work, and should identify your dGPU, however.

**Comment by rjfnobre** [comment]
**uname -a**
Linux specs-ANTAREX 4.6.0-kfd-compute-rocm-rel-1.4-16 #1 SMP Tue Dec 13 13:14:21 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

**dmidecode**
https://gist.github.com/rjfnobre/4e82c68f22bf6eb58557adc55dcfaee9

**Comment by boxerab** [comment]
@jedwards-AMD  thanks. I will wait for full opencl 1.2 support. Not going to ask you when that will be :)

**Comment by jedwards-AMD** [comment]
Your GPU and CPU look capable, and from the output above I appears your agent is a Fiji GPU. The motherboard also looks good. The failure of the vector_copy HSA sample indicates you don't have a brig file in the same directory as the sample executable, but you can get a device.

Can you run your OpenCL application using strace, like this: 'strace <app_name>` 

Send me the output. I think you have some kind of configuration problem.

**Comment by rjfnobre** [comment]
Strace for the execution of the OpenCL application:
https://gist.github.com/rjfnobre/fdd8bb88bfa111edc575447c8783c4e1

**Comment by rjfnobre** [comment]
Any ideas on what may be the cause?

**Comment by parallelo** [comment]
FYI - This simple example works on my development system.  

Start by installing ROCm and its OpenCL implementation: 

`sudo apt-get install rocm opencl-rocm`

Then, build and run this very simple OCL app..

Grab the HelloWorld sample:  
`wget https://raw.githubusercontent.com/bgaster/opencl-book-samples/master/src/Chapter_2/HelloWorld/HelloWorld.cpp`
`wget https://raw.githubusercontent.com/bgaster/opencl-book-samples/master/src/Chapter_2/HelloWorld/HelloWorld.cl`

Build it using the default ROCm OpenCL include and library locations: 
`g++ -I /opt/rocm/opencl/include/opencl1.2  ./HelloWorld.cpp -o HelloWorld -L /opt/rocm/opencl/lib/x86_64 -lOpenCL`

Run it:
`./HelloWorld 
`

**Comment by rjfnobre** [comment]
Finally OpenCL is working on my machine!

I was missing the 'opencl-rocm' package.
After that I just had to remove the 'AMDAPPSDK-3.0' OpenCL libraries from the $LD_LIBRARY environment variable.

**Comment by parallelo** [comment]
Happy to hear it.  We'll plan to post a simple ROCm OpenCL Quickstart Guide on GPUOpen.com to ensure it is more clear for everyone.

**Comment by boxerab** [comment]
awesome!! Fantastic. OK, can't help myself - any idea on when full OpenCL 1.2 support is coming to ROCm ?
I've got to wait for image support.  Thanks!

**Comment by jedwards-AMD** [comment]
I cannot confirm specific dates, but full support should be available in a summer release.

**Comment by boxerab** [comment]
Great, thank you @jedwards-AMD .  Can't wait!
