### ISSUE TITLE
Ryzen ThreadRipper 2 2990WX - CPU OpenCL

### ISSUE THREAD

**Issue by farhan333** [RadeonOpenCompute/ROCm#574]
I'm working with Ryzen ThreadRipper 2 2990WX and the GPU I'm using is an NVIDIA GPU. I need to run OpenCL Kernels on the CPU. Would it be possible with ROCM or is it not possible to run OpenCL on this CPU?

**Comment by jlgreathouse** [comment]
Hi @farhan333 

The current AMD OpenCL runtimes that are a part of ROCm do not support CPU targets. You may want to look into other runtimes, such as [pocl](http://portablecl.org/).
