### ISSUE TITLE
ROCm 1.9.1 OpenCL subtly broken on kernels 4.18.10+

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#577]
Ubuntu, ROCm 1.9.1 OpenCL-only, two Vega64 GPUs.
hsa-ext-rocr-dev/Ubuntu 16.04,now 1.1.9-9-ge4ab040 amd64 [installed,automatic]
hsa-rocr-dev/Ubuntu 16.04,now 1.1.9-9-ge4ab040 amd64 [installed,automatic]
hsakmt-roct/Ubuntu 16.04,now 1.0.9-8-g238782c amd64 [installed,automatic]
hsakmt-roct-dev/Ubuntu 16.04,now 1.0.9-8-g238782c amd64 [installed,automatic]
rocm-opencl/Ubuntu 16.04,now 1.2.0-2018090737 amd64 [installed]

Testing with GpuOwl, everything works fine on kernel 4.18.8,
but wrong results are produced (easily, systematically) on kernels 4.18.10, 4.18.12, 4.19-rc7 (i.e. any kernel above 4.18.8 that I've tried).

What is interesting is that no error is reported, neither by the OpenCL API, nor by amdgpu in dmesg.

**Comment by ddobreff** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/drivers/gpu/drm/amd/amdkfd/kfd_doorbell.c?id=v4.18.8&id2=v4.18.10
This is the only difference that *may*(not quite sure) cause this.

**Comment by preda** [comment]
I tested kernel 4.19-rc7 with amdgpu-pro 18.30 and it works correctly.

**Comment by ROCmSupport** [comment]
Thanks @preda fr confirming after verifying with the latest kernel.
Hope this issue is no more observed.
Please file a new ticket if you observe the same with the latest kernels.
