### ISSUE TITLE
Please confirm ROCm works on Ubuntu 18.10

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#588]
Does ROCm work on Ubuntu 18.10, which was released on October 18
https://wiki.ubuntu.com/CosmicCuttlefish/ReleaseSchedule

**Comment by 949f45ac** [comment]
I ran it on 18.10 beta (downloaded 2018-10-05) and it worked fine. Installed without dkms.

There hasn’t yet been an amdgpu-pro release for 18.10, however. Just in case you want that too.

**Comment by jlgreathouse** [comment]
I can confirm what @949f45ac says. I've run ROCm 1.9.1 user-land code on top of the default Ubuntu 18.10 kernel and haven't run into any major problems.

That said, Ubuntu 18.10 is not an [officially supported platform](https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available), so we have not rigorously tested all layers of the ROCm stack against it. It _should_ work as far as we know, but it does not go through the same level of pre-released testing as our officially supported distros.

**Comment by shimmervoid** [comment]
Installing and using GCC 7.3 over the default 8.2 may help with any compiler issues.

**Comment by preda** [comment]
Thanks, I confirm I can use ROCm 1.9.1 OpenCL correctly on Ubuntu 18.10 with the default Linux kernel 4.18.0.

As a side note, it would be nice to mention somewhere on ROCm install instructions the udev setup that is needed when installing without dkms:

echo 'SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"' | sudo tee /etc/udev/rules.d/70-kfd.rules

**Comment by jlgreathouse** [comment]
I believe [we do mention that](https://github.com/RadeonOpenCompute/ROCm#rocm-19-is-abi-compatible-with-kfd-in-upstream-linux-kernels) specifically when discussing using upstream kernels with ROCm.

**Comment by preda** [comment]
@jlgreathouse: yes, indeed that is documented, my bad.

**Comment by arigit** [comment]
Just to add for the record - on ubuntu 18.10, ROCM-based OpenCL acceleration for darktable works flawlessly (and a tad faster than with the legacy amdgpu-pro drivers). 
The only package required is rocm-opencl; that, the udev rule above and adding the user to the 'video' group. Thanks @amd folks for making it simple

**Comment by aadibajpai** [comment]
I'm able to install `rocm-dev` without error but the udev command doesn't work.
```
aadibajpai@ubuntu_hydralatest:~$ echo 'SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"' | sudo tee /etc/udev/rules.d/70-kfd.rules
tee: /etc/udev/rules.d/70-kfd.rules: No such file or directory
SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"
```

**Comment by amunozf** [comment]
> I believe [we do mention that](https://github.com/RadeonOpenCompute/ROCm#rocm-19-is-abi-compatible-with-kfd-in-upstream-linux-kernels) specifically when discussing using upstream kernels with ROCm.

The command you mention there is wrong because the character | is missing. The correct one is:

`echo 'SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"' | sudo tee /etc/udev/rules.d/70-kfd.rules`

So please, fix it.
