### ISSUE TITLE
CLOC still requires components to be in the old path

### ISSUE THREAD

**Issue by sunyifan112358** [RadeonOpenCompute/ROCm#6]
I had just installed the ROCm using apt-get a few days ago. I saw the cloc is integrated into the package. However, in cloc.sh and snack.sh, the default path is still pointing to /opt/amd/llvm and /opt/amd/hsa. Should these default paths be updated? Is there a way that we can configure the tools to still make them usable? I did not see a clang in the llvm path, so which clang we can use for now? Can the one in /opt/rocm/hcc-hsail/bin work together with cloc?

**Comment by jedwards-AMD** [comment]
New packages for CLOC have been added to the Debian and RPM repositories. These versions of the tools should correct your problems.
