### ISSUE TITLE
In the future,the platform will run on Windows?

### ISSUE THREAD

**Issue by GhostChild** [RadeonOpenCompute/ROCm#60]
I use AMD GPU, And have interesting with deep learning.
more and more deep learning project run like caffe and other platform.
but it's not friendly for AMD GPU.
more people use windows system. 
I also want more people can use my program.

**Comment by jedwards-AMD** [comment]
Currently there are no plans to support of ROCm on Windows platforms.

**Comment by gstoner** [comment]
@GhostChild We will bring the ROCm tools to Windows,  HCC, HIP, you already have OpenCL.  So you will be able to support the same program on both systems.  We have lot request for this, but right know we focused on getting performant, stable tools on a single platform initially, but have been working on a new foundation for GPU computing on Windows as well with make it easier to support these tools and other tools in the future.
