### ISSUE TITLE
Suggestion: start a ROCm blog

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#600]
Hi, I think I'd like to read a blog related to ROCm, written mainly by ROCm developers.

**Comment by ms178** [comment]
There are some entries on gpuopen.com with a ROCm focus, e.g. https://gpuopen.com/rocm-tensorflow-1-8-release/ 

There could be more posts though. ;)

**Comment by preda** [comment]
This forum with ROCm issues is already a venue for fast communication with the ROCm team, and that's great!

Maybe a solution could be found to allow interested AMD developers to communicate technically (on a blog) without too much legal overhead.

Feel free to close this FR as desired.

**Comment by ROCmSupport** [comment]
Can not serve at present. Not sure about future.
