### ISSUE TITLE
ROCm-1.9.x DKMS module build failed for 14.18.0-amd64 kernel (install from http://repo.radeon.com/rocm/apt/debian/) 

### ISSUE THREAD

**Issue by amore-amore** [RadeonOpenCompute/ROCm#604]
Trying to install from: deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ repository

It seems function vga_switcheroo_set_dynamic_switch(pdev, VGA_SWITCHEROO_OFF);
is deprecated > 14.16 kernels.

# apt install rocm-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 490 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up rock-dkms (1.9-224) ...
Removing old amdgpu-1.9-224 DKMS files...
------------------------------
Deleting module version: 1.9-224
completely from the DKMS tree.
------------------------------
Done.
Loading new amdgpu-1.9-224 DKMS files...
Building for 4.18.0-amd64
Building for architecture amd64
Building initial module for 4.18.0-amd64
Error! Bad return status for module build on kernel: 4.18.0-amd64 (amd64)
Consult /var/lib/dkms/amdgpu/1.9-224/build/make.log for more information.
dpkg: error processing package rock-dkms (--configure):
 installed rock-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of rocm-dkms:
 rocm-dkms depends on rock-dkms; however:
  Package rock-dkms is not configured yet.

dpkg: error processing package rocm-dkms (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 rock-dkms
 rocm-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

# cat make.log
DKMS make.log for amdgpu-1.9-224 for kernel 4.18.0-amd64 (amd64)
Tue Nov  6 05:58:50 EST 2018
make: Entering directory '/usr/src/linux-headers-4.18.0-amd64'
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_drm.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_module.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/lib/chash.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/scheduler/gpu_scheduler.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/main.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_device.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_memory.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/scheduler/sched_fence.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/symbols.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_chardev.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_tt.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_topology.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_fence.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_bo.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_fence_array.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_bo_util.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_kthread.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_device.o
  LD [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/lib/amdchash.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_kms.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_pasid.o
/var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.c: In function ‘amdgpu_pmops_runtime_suspend’:
/var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.c:768:2: error: implicit declaration of function ‘vga_switcheroo_set_dynamic_switch’; did you mean ‘vga_switcheroo_process_delayed_switch’? [-Werror=implicit-function-declaration]
  vga_switcheroo_set_dynamic_switch(pdev, VGA_SWITCHEROO_OFF);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  vga_switcheroo_process_delayed_switch
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_doorbell.o
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.18.0-common/scripts/Makefile.build:322: /var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_io.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_flat_memory.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_mn.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_bo_vm.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_process.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_reservation.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_module.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_drm_global.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_queue.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_object.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_bitmap.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_mqd_manager.o
  LD [M]  /var/lib/dkms/amdgpu/1.9-224/build/scheduler/amd-sched.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_pci.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_lock.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_mqd_manager_cik.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_execbuf_util.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_mqd_manager_vi.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_prime.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_mqd_manager_v9.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_page_alloc.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_kernel_queue.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_bo_manager.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_kernel_queue_cik.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_page_alloc_dma.o
make[3]: *** [/usr/src/linux-headers-4.18.0-common/scripts/Makefile.build:563: /var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_kernel_queue_vi.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_kernel_queue_v9.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/ttm_agp_backend.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_packet_manager.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_process_queue_manager.o
  LD [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/amdkcl.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_device_queue_manager.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_device_queue_manager_cik.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_device_queue_manager_vi.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_device_queue_manager_v9.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_interrupt.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_events.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/cik_event_interrupt.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_int_process_v9.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_dbgdev.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_dbgmgr.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_crat.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_rdma.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_peerdirect.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_ipc.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_iommu.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/kfd_debugfs.o
  LD [M]  /var/lib/dkms/amdgpu/1.9-224/build/ttm/amdttm.o
  LD [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkfd/amdkfd.o
make[2]: *** [/usr/src/linux-headers-4.18.0-common/Makefile:1531: _module_/var/lib/dkms/amdgpu/1.9-224/build] Error 2
make[1]: *** [Makefile:146: sub-make] Error 2
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/usr/src/linux-headers-4.18.0-amd64'

**Comment by rumatadest** [comment]
https://github.com/RadeonOpenCompute/ROCm/issues/473

**Comment by jlgreathouse** [comment]
Closing, as @rumatadest this is a dupe.
