### ISSUE TITLE
Conda ROCm packages

### ISSUE THREAD

**Issue by iamkucuk** [RadeonOpenCompute/ROCm#621]
Hi all. I think we all know conda well. Since it is widely used and it will help the procedure for installing it correctly, conda packages like tensorflow-rocm(conda install -c rocm tensorflow-rocm) would help community a lot!

**Comment by maxcr** [comment]
Uh buddy you're asking for python wrappers in the wrong place. I'm working on getting PKGBUILDs for Arch Linux working. You'll probably need an FFI interface for the binaries to talk to Python.

**Comment by Avatat** [comment]
You can use `pip3 install --user tensorflow-rocm` in Anaconda environment :)

**Comment by isuruf** [comment]
If you want to install ROCM itself with conda, you can use the `conda-forge` channel. Available packages are in https://github.com/conda-forge/staged-recipes/issues/10123. (Other packages will be added as time permits. If you want other packages, send a PR)

**Comment by ROCmSupport** [comment]
We do not have plans to enable ROCm for conda.
You can tweak in your own ways.
Thank you.

**Comment by ROCmSupport** [comment]
**OSError: libamdhip64.so.5: cannot open shared object file: No such file or directory**
Looks like installation did not go well as its not able to find hip runtime, recommend to check rocm installation.
Thank you.
