### ISSUE TITLE
Which public cloud supports VM with AMD GPUs with ROCm support?

### ISSUE THREAD

**Issue by ghostplant** [RadeonOpenCompute/ROCm#632]
Hi,

I'd like to have a try about Tensorflow over ROCm on some cloud VMs.

**Comment by ghostplant** [comment]
I am not sure if I create a VM on some cloud with AMD GPU provided, whether it will support ROCm or just provide 3D graphic display function.

**Comment by ghostplant** [comment]
I am not sure if I create a VM on some cloud with AMD GPU provided, whether it will support ROCm or just provide 3D graphic display function.

**Comment by briansp2020** [comment]
I don't know about VM. But if you want to try ROCm in cloud, https://gpueater.com/ has instances with VEGA FE.

**Comment by ghostplant** [comment]
Thank you.

**Comment by jlgreathouse** [comment]
@briansp2020 has a good answer -- [GPUEater](https://gpueater.com/) does support AMD GPUs. You may also want to look into [Genesis Cloud](https://www.genesiscloud.com/), which also supports AMD GPUs.
