### ISSUE TITLE
Missing sentence in README.md

### ISSUE THREAD

**Issue by delivrance** [RadeonOpenCompute/ROCm#634]
![image](https://user-images.githubusercontent.com/14043624/50060529-7bc87380-0195-11e9-9f95-2489b9c40591.png)

*ROCm is focused on using AMD GPUs to accelerate computational tasks, such as machine learning, engineering workloads, and scientific computing. **In order to focus our development efforts on these domains of interest, ROCm***

ROCm...?

**Comment by jlgreathouse** [comment]
Thanks for the report! This should be fixed with the recent README update as part of the ROCm 2.0 release.
