### ISSUE TITLE
just a suggestion about apu

### ISSUE THREAD

**Issue by halalia** [RadeonOpenCompute/ROCm#635]
leaving raven-ridge apus'  integrated gpus unsupported seems a pity

it could be a nice platform to deploy deep models on apu computers to run the tasks as "evaluate" the models

the compute power of apus' igp is at a unsuited\unmatched level, too strong for office task,  but weak for professional application. Evaluating,(not training) deep learning model might be ok, and i guess this idea is similar to the first apus some 8 years ago

**Comment by nevion** [comment]
aww shucks.  I got a thinkpad a485 coming and romc played a role in that decision as well as some decent opencl support.  I didn't know that raven ridge was in this mostly unsupported state until now.

Support ROCm everywhere, not just the data center, amd.  Us GPU developers have to develop our code somewhere, and if you don't have it on the commodity stuff it doesn't pick up steam on the FOSS side of things. Here I was hoping to add opencl image processing to various astronomy softwares and this just threw a wrench in it.

**Comment by luyatshimbalanga** [comment]
@3D-360 See [this comment](https://github.com/RadeonOpenCompute/ROCm/issues/608#issuecomment-450519762). More works to be done but at least Raven Ridge is supported.

**Comment by chophshiy** [comment]
@nevion 
I'm in the same boat here.  Have you had any luck getting things working since then?

**Comment by ROCmSupport** [comment]
Hi @halalia 
We are not supporting right now. Please stay tuned for the future updates.
Thank you.
