### ISSUE TITLE
GPG key is served insecurely

### ISSUE THREAD

**Issue by anewusername** [RadeonOpenCompute/ROCm#64]
The GPG key for the debian repository is served over an insecure connection (HTTP) and can be trivially changed using a man-in-the-middle attack.

**Comment by victoredwardocallaghan** [comment]
hehe, I was about to post the same issue but figured it would be a duplicate as surely someone noticed this too! ;)

**Comment by victoredwardocallaghan** [comment]
@johnbridgman

**Comment by gstoner** [comment]
We are moving off this server supplied AMD IT,  and will be fixxing this issue.

**Comment by victoredwardocallaghan** [comment]
@gstoner can you please reopen this until it is actually resolved.

**Comment by victoredwardocallaghan** [comment]
@gstoner @johnbridgman  this is seriously egregious that this bug was closed and things were never fixed.
https://instinct.radeon.com/en-us/amd-deep-learning-stack-using-docker/

**Comment by anoother** [comment]
This is probably worth reopening... The key is not available over HTTPS.
