### ISSUE TITLE
ROCm 2.0 DKMS build fails on KDE Neon (derivative of Ubuntu 18.04)

### ISSUE THREAD

**Issue by krrk** [RadeonOpenCompute/ROCm#641]
```
$ sudo dkms install -k 4.15.0-43-generic -m amdgpu/2.0-89

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:

Building module:
cleaning build area...
make -j12 KERNELRELEASE=4.15.0-43-generic -j12 kdir=/lib/modules/4.15.0-43-generic/build -C /lib/modules/4.15.0-43-generic/build M=/var/lib/dkms/amdgpu/2.0-89/build...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-4.15.0-43-generic is not supported
Error! Bad return status for module build on kernel: 4.15.0-43-generic (x86_64)
Consult /var/lib/dkms/amdgpu/2.
[make.log](https://github.com/RadeonOpenCompute/ROCm/files/2699550/make.log)
0-89/build/make.log for more information.
```

[make.log](https://github.com/RadeonOpenCompute/ROCm/files/2699551/make.log)

**Comment by krrk** [comment]
I found the issue. I am running KDE Neon which is based on Ubuntu 18.04. The file `/etc/os-release` is not identical to Ubuntu's so the amdgpu dkms Makefile sets `OS_NAME` to "neon" instead of "ubuntu". This results in incorrect values for `DRM_VER` and `DRM_PATCH` which causes the build to fail.

The contents of `/etc/os-release` from my machine are shown below. I'm not sure if other ubuntu derivatives change the ID in this file, but if they do perhaps a way to fix this is to check ID_LIKE instead of ID and look for debian or ubuntu.

/etc/os-release:
```
NAME="KDE neon"
VERSION="5.14"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.14"
VERSION_ID="18.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by jlgreathouse** [comment]
Thanks for looking into that. I was just coming by to reply that i was able to successfully install ROCm 2.0 on an Ubuntu 18.04.1 box with 4.15.0-43. Glad you were able to hunt down the problem.

That said, I'm not sure we would be able to directly check `ID_LIKE`, since for Ubuntu proper the only value in there is `"debian"`. We do not test directly against Debian, and the Makefile mostly needs to know whether it's on Ubuntu to put in places changes required due to Ubuntu kernel backports. That said, there's probabl ysome logic that could be worked out here. @fxkamd  -- thoughts on maybe doing some more advanced checks in future ROCm releases?

**Comment by krrk** [comment]
Yes I noticed that `ID_LIKE` is just `"debian"` on Ubuntu proper as well, but as you said I'm sure there is a way to modify the logic. At least grepping for "ubuntu" ought to work for both ubuntu proper and ubuntu derivatives or just checking for ubuntu in `ID` and `ID_LIKE`. Also in case you're interested I've been using ROCm since version 1.6 on KDE Neon without any issues.

For now and if anybody else comes by needing a workaround I've hacked the makefile in `/usr/src/amdgpu-2.0-89/Makefile` to change line 8 to `OS_NAME = "$(shell sed -n 's/^ID_LIKE=\(.*\)/\1/p' /etc/os-release | tr -d '\"' | cut -d" " -f1)"` and installation is successful.

**Comment by jlgreathouse** [comment]
Note for anyone else who runs into this issue: after completing the above-mentioned change, you would need to run:

```bash
sudo dkms build amdgpu/2.0-89
sudo dkms install amdgpu/2.0-89
```

**Comment by hameerabbasi** [comment]
I'm using KDE neon and this worked for me.

**Comment by ROCmSupport** [comment]
Thanks @hameerabbasi for confirming that its working for you.
We are also not able to reproduce this problem now with ROCm 4.0.

@krrk, request you to try with the latest ROCm 4.0.
File a new issue if you find any. Thank you.
