### ISSUE TITLE
Merry Christmas!

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#642]
Thanks for ROCm 2.0! Best Christmas surprise ever!

**Comment by jlgreathouse** [comment]
This is always a fun label to get to use. :)

I hope you enjoy the new features & fixes!

**Comment by preda** [comment]
Thanks for the build scripts in Experimental_ROC
https://github.com/RadeonOpenCompute/Experimental_ROC

**Comment by jlgreathouse** [comment]
With the holidays past, I'm going to close this to help clean up the issue tracker. Thanks for the fun ticket. :)
