### ISSUE TITLE
Happy New Year!!

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#645]
OpenCL from ROCm 2.0 appears to work with Raven Ridge!

It ain't hc but it will do!

**Comment by 3D-360** [comment]
GREAT!  One step at a time.  I want to use Raven Ridge’s CPU/GPU shared memory, and ROCm/OpenCL is a viable option.  I hope that the performance is reasonable.

**Comment by jlgreathouse** [comment]
Thanks for the positive feedback. Glad to hear that OpenCL is working on Raven for you.

That said, holidays have gone by so I 'm going to close this issue to help clean up our tracker. Thanks again for the info!
