### ISSUE TITLE
Paths convention within /opt/rocm/ 

### ISSUE THREAD

**Issue by ubombi** [RadeonOpenCompute/ROCm#647]
Can someone fix paths within a framework. 
There are a lot of mess like:
`/opt/rocm/[something]/include` and `/opt/rocm/include/[something]/`
`/opt/rocm/[something]/bin` and `/opt/rocm/bin/[something]/`
They differ per project and always are hardcoded.

It's strange to see [below] in TensorFlow code.
```
   # Add MIOpen headers
   inc_dirs.append("/opt/rocm/miopen/include")	  
    # Add rtg headers
   inc_dirs.append("/opt/rocm/include/migraph")
``` 

Same with build scripts.

**Comment by kentrussell** [comment]
We've managed to get this normalized starting in 2.7. I think the final projects finally got this aligned in 2.9. Please re-open the issue if this is not the case for any of the projects that you see.
