### ISSUE TITLE
ROCm 2.0 performance improvements

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#649]
Nice work on 2.0 !! I just tested my video compression app, and ROCm 2 is around 20% slower than WIndows OpenCL stack for lossless compress, and around 30% faster than Windows OpenCL stack for lossy.  This is a huge improvement from 1.8, the last version I tested.  

Keep up the good work, folks.

**Comment by jlgreathouse** [comment]
Thanks again for the feedback. We really appreciate hearing user experiences with ROCm. To help keep our issue tracker clean, I'm going to close this one for now. Still, I like the opportunity to use this thread label. ;)
