### ISSUE TITLE
ROCm 2.0 OpenCL cross device atomics, how?

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#654]
System: 2x Vega64 GPUs, Asrock Taichi x299 motherboard,  i7-7820X CPU, Ubuntu 18.10 with kernel 4.20, ROCm 2.0.

I would like to synchronize with atomics (e.g. atomic_load_explicit, atomic_store_explicit) across the 2 GPUs (device-to-device), without involving the host.

But clinfo on my system shows:
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No

What should I do? any hint as to why "SVM atomics" is "NO"? -- AFAIK the PCIe in my system is 3.0.
thanks

**Comment by preda** [comment]
I also tested on the same hardware but with Ubuntu 18.04, kernel 4.15, and with rock-dkms installed, clinfo still reports:
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
on both GPUs.

**Comment by preda** [comment]
One GPU is in PCIe Gen3 x16, and the other GPU is in PCIe Gen3 x8. (in the "best" locations on the Asrock Taichi x299 motherboard, without any tricks).

Thus the lack of SVM Atomics does not seem to originate from PCIe or from CPU.
Maybe the team has some insight on why the SVM Atomics is "Off" in this setup. Is it a question of Vega64 hardware not offering it? or ROCm not implementing it yet?

**Comment by ROCmSupport** [comment]
Hi @preda 
Thanks for reaching out.
I just verified with ROCm 4.0 and the same issue is still observed with different variety of hardware.
I will check with OpenCL team and will get back asap on this.
Thank you.

**Comment by preda** [comment]
@ROCmSupport feel free to document if any information becomes available, otherwise the issues can be closed.

**Comment by ROCmSupport** [comment]
Thanks @preda
