### ISSUE TITLE
Q: OpenCL: perf impact of SVM vs. cl_mem buffers

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#655]
I would like to ask: what is the expected performance impact of using SVM (clSVMAlloc) memory vs. "classic" OpenCL buffers (clCreateBuffer).

In particular in this scenario: two GPUs, accessing (read+write) disjoint regions of the same SVM buffer.

In the "high performance" scenario, I'd expect a memory page (4KB?) to be migrated locally to the GPU that's accessing it, and provide high local speed.

In the "low performance" scenario, I imagine the physical memory residing in one place (host or one GPU), and the access being done through PCIe, and that'd be slow.

So, do SVM buffers offer the same performance as "classic" buffers, or should I expect SVM to be slower?
thanks

**Comment by Marc408** [comment]
I have yet to find a specific description of the SVM functionality in any OpenCL documentation. In the OpenCL Spec 2.0 it says the SVM resides in Host Memory "OpenCL extends the global memory region into the host memory region through a shared virtual memory (SVM) mechanism.".

According to this presentation https://youtu.be/H8tCCa9qV4U?t=656 you can expect SVM-implementations to show improved performance. Though I would expect it to be highly dependant on use case. 

If you find anything, please let me know!

**Comment by preda** [comment]
Closing as old. Better information/documentation on SVM in ROCm OpenCL would be nice though.
