### ISSUE TITLE
ROCm 2.0 required upstream Kernel version

### ISSUE THREAD

**Issue by FilipVaverka** [RadeonOpenCompute/ROCm#672]
Which kernel version (and therefore amdgpu and amdkfd) is supposed to work with ROCm 2.0? I've built  ROCT and ROCR from sources (on OpenSUSE) with Kernel 4.19.12 (amdkfd 0.7.2) and tried to run "kfdtest". I got bunch of failed tests and also some "VMC page fault"s in kernel log.

I'm running RX Vega 64 on Ryzen R7 1800X.

**Comment by jlgreathouse** [comment]
Your Radeon RX Vega 64 is a "Vega 10" GPU, and thus requires [at least kernel 4.18](https://github.com/RadeonOpenCompute/ROCm/blob/roc-2.0.0/README.md#rocm-support-in-upstream-linux-kernels). If you boot with that driver (setting aside the thunk and ROCr for a second), do you see the any output from `dmesg | grep amd` and `dmesg | grep kfd`?

Note that, while I have not yet tested OpenSUSE builds, we do have scripts in the [Experimental ROC project](https://github.com/RadeonOpenCompute/Experimental_ROC/tree/roc-2.0.0) that demonstrate how to build the ROCm software stack on other distros. This may be helpful in showing how you can go about building ROCm for your distro.

**Comment by FilipVaverka** [comment]
Yes, amdgpu and amdkfd modules seem to be loaded/running:

dmesg | grep amdgpu
> [    5.759898] [drm] amdgpu kernel modesetting enabled.
[    5.765817] fb: switching to amdgpudrmfb from EFI VGA
[    5.765904] amdgpu 0000:0d:00.0: enabling device (0006 -> 0007)
[    5.766188] amdgpu 0000:0d:00.0: VRAM: 8176M 0x000000F400000000 - 0x000000F5FEFFFFFF (8176M used)
[    5.766189] amdgpu 0000:0d:00.0: GART: 512M 0x000000F600000000 - 0x000000F61FFFFFFF
[    5.766266] [drm] amdgpu: 8176M of VRAM memory ready
[    5.766267] [drm] amdgpu: 8176M of GTT memory ready.
[    6.317848] fbcon: amdgpudrmfb (fb0) is primary device
[    6.317852] amdgpu 0000:0d:00.0: fb0: amdgpudrmfb frame buffer device
[    6.356285] amdgpu 0000:0d:00.0: ring 0(gfx) uses VM inv eng 4 on hub 0
[    6.356287] amdgpu 0000:0d:00.0: ring 1(comp_1.0.0) uses VM inv eng 5 on hub 0
[    6.356289] amdgpu 0000:0d:00.0: ring 2(comp_1.1.0) uses VM inv eng 6 on hub 0
[    6.356290] amdgpu 0000:0d:00.0: ring 3(comp_1.2.0) uses VM inv eng 7 on hub 0
[    6.356291] amdgpu 0000:0d:00.0: ring 4(comp_1.3.0) uses VM inv eng 8 on hub 0
[    6.356293] amdgpu 0000:0d:00.0: ring 5(comp_1.0.1) uses VM inv eng 9 on hub 0
[    6.356294] amdgpu 0000:0d:00.0: ring 6(comp_1.1.1) uses VM inv eng 10 on hub 0
[    6.356295] amdgpu 0000:0d:00.0: ring 7(comp_1.2.1) uses VM inv eng 11 on hub 0
[    6.356297] amdgpu 0000:0d:00.0: ring 8(comp_1.3.1) uses VM inv eng 12 on hub 0
[    6.356298] amdgpu 0000:0d:00.0: ring 9(kiq_2.1.0) uses VM inv eng 13 on hub 0
[    6.356299] amdgpu 0000:0d:00.0: ring 10(sdma0) uses VM inv eng 4 on hub 1
[    6.356301] amdgpu 0000:0d:00.0: ring 11(sdma1) uses VM inv eng 5 on hub 1
[    6.356302] amdgpu 0000:0d:00.0: ring 12(uvd<0>) uses VM inv eng 6 on hub 1
[    6.356303] amdgpu 0000:0d:00.0: ring 13(uvd_enc0<0>) uses VM inv eng 7 on hub 1
[    6.356304] amdgpu 0000:0d:00.0: ring 14(uvd_enc1<0>) uses VM inv eng 8 on hub 1
[    6.356306] amdgpu 0000:0d:00.0: ring 15(vce0) uses VM inv eng 9 on hub 1
[    6.356307] amdgpu 0000:0d:00.0: ring 16(vce1) uses VM inv eng 10 on hub 1
[    6.356308] amdgpu 0000:0d:00.0: ring 17(vce2) uses VM inv eng 11 on hub 1
[    6.357182] [drm] Initialized amdgpu 3.27.0 20150101 for 0000:0d:00.0 on minor 0

dmesg | grep kfd
> [    5.765662] kfd kfd: Initialized module
[    6.313474] kfd kfd: Allocated 3969056 bytes on gart
[    6.313681] kfd kfd: added device 1002:687f

I think at least amdgpu should be in order as I'm able to run accelerated graphics (both OpenGL and Vulkan - be it RadV or AMDVLK). To be clear most of tests in "kfdtest" passed, few failed and then "kfdtest" got stuck (I would assume in some kernel call as I was unable to kill it). I should be able to rerun it and report failed tests (at least until it gets stuck). Any advice on debugging this is welcomed.

**Comment by jlgreathouse** [comment]
Which tests fail, and which test are you stuck on? `kfdtest` is not meant to succeed on all systems in all cases, and a number of the tests it can run are filtered out during our internal testing runs.

**Comment by FilipVaverka** [comment]
I tried `run_kfdtest.sh` again with `-p vg10` and `KFDMemoryTest.BigBufferStressTest` seems to take very long time and I can see occasional black artifacts on the screen (system is still responsive). I'm attaching output of `kfdtest` and `dmesg | grep amdgpu`:
[kfdtest_out.txt](https://github.com/RadeonOpenCompute/ROCm/files/2761206/kfdtest_out.txt)
[dmesg_amdgpu.txt](https://github.com/RadeonOpenCompute/ROCm/files/2761207/dmesg_amdgpu.txt)

**Comment by jlgreathouse** [comment]
That test shows the same thing on my system, so I'd say you can safely ignore it / add it to your filter list.

**Comment by FilipVaverka** [comment]
Thanks. If that is the case I'll go back to HCC in which I tried to get simple saxpy (https://gist.github.com/scchan/540d410456e3e2682dbf018d3c179008) running and failed (all results were wrong and GPU activity LEDs showed 100% even after process exited). So I tried to go to lower level to examine the issue.

**Comment by jlgreathouse** [comment]
I personally recommend trying `rocminfo` first, just to verify that your ROCR and Thunk installations can talk to your GPU properly.

The component build scripts in the Experimental ROC repo above demonstrate an example order for building ROCm that I've found works and can help spot errors during the process. They also point to our official commits that are part of ROCm 2.0 in the various repos.

In addition, if you're getting OpenSUSE working, we would definitely appreciate any PRs into that repo that would allow others to rebuild ROCm on OpenSUSE. :)

**Comment by FilipVaverka** [comment]
Well, `rocminfo` seems to be giving sensible output [rocminfo_out.txt](https://github.com/RadeonOpenCompute/ROCm/files/2774292/rocminfo_out.txt). 

My intention is (in the end) to either modify these scripts or even to create RPMs for OpenSUSE, but first I want to know if it even can work - thats why I took dirty path first (hopefully there aren't many traps when it compiles, but doesn't work).

**Comment by FilipVaverka** [comment]
I got back to this and managed to get ROCm based OpenCL work (at least clinfo and clpeak) and some of HIP samples worked too... I did mostly work along the lines of [Experimental_ROC](https://github.com/RadeonOpenCompute/Experimental_ROC) scripts for Ubuntu (but mostly only basic "cmake" commands are needed). 
So I think we can close this with: ROCm 2.0.1 with OpenSUSE kernel 4.20.10-1 should (at least partially) work.

**Comment by jlgreathouse** [comment]
If you want to submit any PRs to bring OpenSUSE support into the Experimental_ROC repo, I'd be happy to take them. :)
