### ISSUE TITLE
Testing clBLAS with OpenCL produces "error: variables in the local address space can only be declared in the outermost scope of a kernel function"

### ISSUE THREAD

**Issue by WaldemarH** [RadeonOpenCompute/ROCm#674]
1. I've install ROCm on Centos 7.6 where the rocminfo and clinfo execute normally.
2. I've build clBLAS with OpenCL 2.0 and then started test_short which fails with
error: variables in the local address space can only be declared in the outermost scope of a kernel function
        __local float4 ascratch[4*16*4];

And if you check the kernel you will see that ascratch is defined almost at the end of the function.,

Now I have no knowledge on who generates the kernel and how, but I assume that you know and can fix this.

Best regards
Waldemar

[test_short.txt](https://github.com/RadeonOpenCompute/ROCm/files/2765736/test_short.txt)
[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/2765737/clinfo.txt)
[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/2765738/rocminfo.txt)

**Comment by jlgreathouse** [comment]
It appears that you [have opened an issue in the appropriate repo](https://github.com/clMathLibraries/clBLAS/issues/341) (for the library itself). That is the correct place to report the problem you are seeing, as it is a problem with the kernel and not ROCm or our OpenCL compiler.

Said kernel does not follow the [OpenCL C specifications](https://www.khronos.org/registry/OpenCL/specs/opencl-2.0-openclc.pdf) required by OpenCL 2.0. Specifically, in Section 6.5.2, "__local (or local)" and in the section "__local" in [this SDK specification](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/local.html): 
> Variables allocated in the __local address space inside a kernel function must occur at kernel function scope.

**Comment by b-sumner** [comment]
Right, that declaration is inside a for loop and hence not at kernel function scope.

**Comment by WaldemarH** [comment]
Thanks guys.
