### ISSUE TITLE
Vega ISA Document: Poor documentation of ds_swizzle_b32

### ISSUE THREAD

**Issue by dragontamer** [RadeonOpenCompute/ROCm#685]
I don't know where to report documentation issues. But hopefully someone here knows where to forward this issue?

On the 28-July-2017 Vega ISA guide (which exists at https://developer.amd.com/wp-content/resources/Vega_Shader_ISA_28July2017.pdf today), there's virtually no documentation on the ds_swizzle_b32 instruction. Page 161:

```
RETURN_DATA = swizzle(vgpr_data, offset1:offset0).
Dword swizzle, no data is written to LDS memory.
```

Fortunately, the 2016 GCN3 ISA Guide has good documentation for ds_swizzle_b32. Hopefully, the issue can be corrected before the next ISA document is released. Ideally, the Vega ISA guide could be updated as well.

**Comment by preda** [comment]
CLRX has some great GCN documentation, see e.g.
https://github.com/CLRX/CLRX-mirror/wiki/GcnInstrsDs#ds_swizzle_b32

Some information from there, such as instruction timing information, would be a valuable addition to AMD docs.

**Comment by phani544** [comment]
see if this helps https://gpuopen.com/amd-gcn-assembly-cross-lane-operations/

**Comment by dragontamer** [comment]
> see if this helps https://gpuopen.com/amd-gcn-assembly-cross-lane-operations/

Oh yeah, that's how I started down this rabbit hole to begin with!

It feels like the ISA document should be the end-all be-all of documentation. Its a thick 250ish page manual. For it to be "missing" information seems to be a mistake.

**Comment by jlgreathouse** [comment]
Hi @dragontamer 

I've sent this issue to our team that writes the ISA manuals. The fixes for this should be part of the manuals we release for Vega 20 chips.

**Comment by jlgreathouse** [comment]
Hello all. I apologize about the long delay on this. Our team that normally does the ISA manuals was moved around in an organizational shakeup, so getting this released took much longer than we originally hoped. However, the ISA guide for the Vega 7nm has been released. It covers the new instructions in this chip, and has an extended ds_swizzle_b32 description in Section 12.13.1.

https://gpuopen.com/wp-content/uploads/2019/11/Vega_7nm_Shader_ISA_26November2019.pdf

**Comment by preda** [comment]
@jlgreathouse thanks for the ISA document, it's welcome. BTW, the links on Contact Information at the end of page3 don't work (404) (maybe an editor could verify all the links just in case)
