### ISSUE TITLE
Cannot repo sync roc-2.0.0 (MIVisionX)

### ISSUE THREAD

**Issue by seesturm** [RadeonOpenCompute/ROCm#690]
When following the instructions for roc-2.0.0 "repo sync" fails at fetching the MIVisionX repository. In default.xml revision points to "1.0.0", but no such branch exists.

Changing revision to "refs/tags/1.0.0" makes "repo sync" succeed. I'm using repo tool version v1.12.37.

**Comment by jlgreathouse** [comment]
Thanks for catching this! Patch submitted.
