### ISSUE TITLE
binary  compiled with hipcc uses 100% cpu forever

### ISSUE THREAD

**Issue by loreson** [RadeonOpenCompute/ROCm#694]
I have an Ubuntu18.04 System.
 Hardware : Xeon e5 1630-v3 with AMD Firepro W9100.
I installed ROCM according to this guide: https://github.com/ROCm/ROCm.github.io/blob/master/ROCmInstall.md
As all of the example applications would hang indefinitely, and there and the current version seems to be broken for Hawaii GPUS,  uninstalled it and installed the 1.92 version with the distro install script.
Unfortunately this does not work either:
I have a simple hello world.
[hallo.txt](https://github.com/RadeonOpenCompute/ROCm/files/2813197/hallo.txt)
compiled with clang it  works fine, and prints "Hello world".
Compiled with hipcc the resulting binary uses 100% CPU, and seems to never complete.  I have left it overnight and didn't see any output.
rocminfo gives me
[roc.txt](https://github.com/RadeonOpenCompute/ROCm/files/2813229/roc.txt)
and hipconfig --full:
[hipconf.txt](https://github.com/RadeonOpenCompute/ROCm/files/2813232/hipconf.txt)

Any sugesstions?

**Comment by dragontamer** [comment]
> AMD Firepro W9100.

That sounds like a Hawaii card (similar firmware / hardware to the R9 290x and R9 390x).

There have been a lot of issues reported for ROCm 2.0 for Hawaii: https://github.com/RadeonOpenCompute/ROCm/issues/691

**Comment by ROCmSupport** [comment]
Hi All,
Hawaii is no more officially ROCm supported device. Please check for more details:
[https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support](url)
