### ISSUE TITLE
RHEL/Fedora binaries?

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/ROCm#7]
As long as the RHEL/Fedora rpms and contained binaries are not around, where do I find some documentation how to build ROCm from source?

**Comment by jedwards-AMD** [comment]
Each of the components have instructions on building the specific component, so you can go that route if you like. However, there are two features planned in the near future that will aleiviate this issue for you:

1) We are planning on creating a universal build script that will build all the core components from the ROCm repository automatically.
2) We are planning on adding a rpm repository this week.

I will update this item when the rpm repository becomes available.

**Comment by jedwards-AMD** [comment]
The binaries have been posted on the packages.amd.com repository server. Please follow updated instructions for installing.
