### ISSUE TITLE
Cache instructions available on AMD APUs under ROCM platform ? 

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCm#70]
Is there any instruction to flush the cache and invalidate the cache L2 in specific ? The reason for asking is to achieve coherency between CPU and GPU accessing the DRAM in APUs there should be cache flushing action? How is it done , what is the instruction for the same ?

**Comment by nevion** [comment]
@VishwasRao17 don't write a paragraph in the ticket title. If I had the answer, such a move would make me hesitate to answer you.

**Comment by VishwasRao17** [comment]
Ok, I wont . Is there a pointer for my question please.

**Comment by gstoner** [comment]
best place to start on ROCm rocm.github.io documentation Also you can look at HSA Foundation spec for background on the runtime and system architecture for ROCm

**Comment by VishwasRao17** [comment]
@gstoner I was going through the ISA sea islands , this is because AMD Kaveri GPU follows Sea Islands Architecture. There they quote in introduction, page no 1-2 (" invalidate and flush caches on the Sea Islands GPU, and ") . But it was not mentioned in the ISA as a command as such . The statements says when the host tries to offload work to GPU , it should copy the contents to device memory and invalidate the L2 cache . So this must be done in ROCM too while offlading the kernel to device memory.  So I am curious how it is done ? I need to apply something similar in my application.

**Comment by jedwards-AMD** [comment]
Invalidating L2 cache is done using AQL packet commands, using the various hsa_fence_scope_t values in the packet. Refer to the [HSA Runtime specification]( http://www.hsafoundation.com/standards/) for a description of AQL and controlling memory synchronization.
