### ISSUE TITLE
Command to disable the L2 cache or command to invalidate / flush the cache operation on AMD APUs ? 

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCm#71]
I would like to know, when a memory is reserved in the GPU RAM, then when GPU tries to modify it, the data will be put into L2 , L1 cache before going to ALU. My question is can I flush the cache before a third party other than GPU tries to access that memory region? Is there an ISA for the same . I am trying to use AMD GPU for some research. Since ROCM is open source I want to make use of it. OpenCL also runs on top of Rocm, so will make use of the same.

**Comment by gstoner** [comment]
Can you put your request into Descriptions,  Your put this in the title.    When you make your request 

"Is there a command to disable the L2 cache or command to invalidate/flush the cache operation on AMD APUs. Kaveri APU Sea islands based architecture #71"   

Question "Are you doing this on ROCm and what Language"

**Comment by VishwasRao17** [comment]
@gstoner I have updated the description. I am looking into a explicit command which will flush the cache L2 during external device read and invalidate the cache contents during external writes into same memory locations.

**Comment by jedwards-AMD** [comment]
Invalidating L2 cache is done using AQL packet commands, using the various hsa_fence_scope_t values in the packet. Refer to the HSA Runtime specification for a description of AQL and controlling memory synchronization.
