### ISSUE TITLE
GPU disappears when 2nd is added to system

### ISSUE THREAD

**Issue by kpande** [RadeonOpenCompute/ROCm#710]
I have a odd situation. I'm mixing Vega 56 and RX570 on a Threadripper 1900X system.

you can see that I have the amdocl64 and mesa providers enabled:
```
[/home/kash]-[root@fezzik]-[1]-[10050]
[:(] # ls /etc/OpenCL/vendors
amdocl64.icd  mesa.icd
```

disabling mesa by moving it out of the vendor list helps avoid accidentally using Clover.
```
[/home/kash]-[root@fezzik]-[0]-[10051]
[:)] # mv /etc/OpenCL/vendors/mesa.icd ~
[/home/kash]-[root@fezzik]-[0]-[10052]
[:)] # clinfo -l
Platform #0: AMD Accelerated Parallel Processing
 `-- Device #0: gfx900
```

Adding the AMDGPU-PRO stack alongside ROCm doesn't prevent ROCm from "working"
```
[/home/kash]-[root@fezzik]-[0]-[10053]
[:)] # mv ~/amdgpu-pro-* /etc/OpenCL/vendors 
[/home/kash]-[root@fezzik]-[0]-[10054]
[:)] # clinfo -l                            
Platform #0: AMD Accelerated Parallel Processing
 `-- Device #0: gfx900
```

but I don't leave it enabled, it's just to show.

then I take 2nd GPU away from VFIO and pass back to AMDGPU (RX570 8GB in 16x):
```
[/home/kash]-[root@fezzik]-[0]-[10056]
[:)] # virsh nodedev-reattach pci_0000_42_00_0
Device pci_0000_42_00_0 re-attached

[/home/kash]-[root@fezzik]-[0]-[10057]
[:)] # virsh nodedev-reattach pci_0000_42_00_1
Device pci_0000_42_00_1 re-attached

[/home/kash]-[root@fezzik]-[0]-[10059]
[:)] # clinfo -l
[/home/kash]-[root@fezzik]-[0]-[10064]
[:)] # 

```

and then no devices show up.

if I start up Xorg on the ellesmere device, it will show up in `clinfo` output. but the Vega won't show up at the same time.

is it just not possible to mix this way? if I have mesa enabled, both are listed via Clover, but trying to use this hangs Xorg.

**Comment by kpande** [comment]
```
[  195.514593] amdgpu 0000:42:00.0: va above limit (0x042013FF >= 0x04000000)
[  195.514594] kfd2kgd: Failed to allocate pts, err=-22
[  195.514596] Failed to map to gpu 1/2
[  195.711324] amdgpu 0000:42:00.0: va above limit (0x042017FF >= 0x04000000)
[  195.711326] kfd2kgd: Failed to allocate pts, err=-22
[  195.711327] Failed to map to gpu 0/1
```

I do see this as well, can't find any info about the error.

**Comment by jlgreathouse** [comment]
@fxkamd may be a better resource to ask about this.

**Comment by fxkamd** [comment]
Um, there are a lot of variables here:

- Multiple driver stacks installed
- Virtualization
- Mixing GPU genrations

In theory all of that should work. Will need to puzzle apart what's really broken here. The memory allocation failures look like a disagreement between KFD and Thunk about the virtual address space size. This could indicate an incompatibility between kernel and user mode, which makes me wonder whether you're running the wrong kernel driver (from AMDGPU Pro rather than ROCm).

Which ROCm version are you using? How did you install it? DKMS or a monolithic kernel? What does "dkms status" say? A complete dmesg log may also help.

**Comment by kpande** [comment]
I performed the test with both stacks installed, and just the ROCm stack.

I performed tests without any VFIO stubs in use, nothing changes because I've used the card for virtualisation.

The main concern was mixing GPU generations, because I've seen others with >1 vega and they all show up, so long as the MB supports PCIe Atomics on each port, or a suitable PLX  is in use.

I've run `clinfo` via `strace` to determine which OpenCL library it is using, and it is definitely using the rocm libraries. I've completely removed the AMDGPU-PRO files from my system and get the same result.

I'm using ROCm from git:
```
     Installed versions:  9999-r1(12:16:07 AM 2019-02-17)
```
installed via Gentoo portage. it's not trivial to install this stuff anywhere but RH/Debian derivatives, which is a huge pain  point that the project should address. if it were easier to install directly from your trees, I could test it "the way you want it built". as things are now, it's almost impossible to guarantee that the bundled libraries (your own fork of LLVM, really?) are all built and linked properly. see also, the issue I reported earlier about segfaulting: #707 

I'm not using the ROCk bits, because it's not really clear from its github project what to do when I need Linux 4.20.7+ support - so I am using upstream's `amdkfd.ko`.

I don't have DKMS installed at all.

dmesg output: https://termbin.com/5luz
after `clinfo -l`: https://termbin.com/5e5n

strace hints:
```
% strace clinfo -l 2>&1| grep -i OpenCL
openat(AT_FDCWD, "/usr/lib64/OpenCL/vendors/roc/libOpenCL.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/OpenCL/vendors/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/etc/OpenCL/vendors/amdocl64.icd", O_RDONLY) = 4
```

**Comment by fxkamd** [comment]
Does the RX570 work on its own, without the Vega56?

Can you run clinfo with this environment variable: HSAKMT_DEBUG_LEVEL=7. That should provide some more info about the libhsakmt virtual address space initialization.

**Comment by kpande** [comment]
yes, if I `echo 1 > /sys/bus/pci/devices/.../remove` on the Vega so that only the RX570 remains, then Ellesmere shows up in `clinfo -l` and I can run `clpeak` and get expected results.

```
% HSAKMT_DEBUG_LEVEL=7 clinfo -l
acquiring VM for 717d using 11
acquiring VM for ab0d using 10
SVM alt (coherent):    0x1000000 - 0x4000bfffff
SVM (non-coherent): 0x4000c00000 - 0xffffffffff
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPU] address 0x1000000
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1009000 number of nodes 1
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x100b000 number of nodes 1
[hsaKmtAllocMemory] node 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x100d000 number of nodes 2
[hsaKmtAllocMemory] node 3
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x100f000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1011000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1013000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1040000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtRegisterMemoryToNodes] address 0x1015000 number of nodes 1
[hsaKmtMapMemoryToGPU] address 0x1015000
[hsaKmtAllocMemory] node 0
[hsaKmtRegisterMemoryToNodes] address 0x1017000 number of nodes 1
[hsaKmtMapMemoryToGPU] address 0x1017000
[hsaKmtAllocMemory] node 0
[hsaKmtRegisterMemoryToNodes] address 0x1200000 number of nodes 1
[hsaKmtMapMemoryToGPU] address 0x1200000
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1019000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x101b000 number of nodes 2
[hsaKmtAllocMemory] node 2
[hsaKmtMapMemoryToGPUNodes] address 0x4201000000 number of nodes 1
Memory exception on virtual address 0x0, node id 0 : [hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1020000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x101d000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x10c0000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x102e000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1030000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1032000 number of nodes 2
Address does not belong to a known buffer
[hsaKmtAllocMemory] node 1
[hsaKmtQueryPointerInfo] pointer 0x4201300000
[hsaKmtMapMemoryToGPUNodes] address 0x4201300000 number of nodes 2
[hsaKmtUnmapMemoryToGPU] address 0x1020000
[hsaKmtFreeMemory] address 0x1020000
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x101f000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1021000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x2480000 number of nodes 2
[hsaKmtAllocMemory] node 0
[hsaKmtRegisterMemoryToNodes] address 0x1023000 number of nodes 1
[hsaKmtMapMemoryToGPU] address 0x1023000
[hsaKmtAllocMemory] node 0
[hsaKmtRegisterMemoryToNodes] address 0x1088000 number of nodes 1
[hsaKmtMapMemoryToGPU] address 0x1088000
[hsaKmtAllocMemory] node 0
[hsaKmtRegisterMemoryToNodes] address 0x2600000 number of nodes 1
[hsaKmtMapMemoryToGPU] address 0x2600000
[hsaKmtAllocMemory] node 0
[hsaKmtMapMemoryToGPUNodes] address 0x1025000 number of nodes 2
[hsaKmtAllocMemory] node 0
Memory exception on virtual address 0x0, node id 0 : Address does not belong to a known buffer
[hsaKmtMapMemoryToGPUNodes] address 0x1027000 number of nodes 2
[hsaKmtAllocMemory] node 3
[hsaKmtMapMemoryToGPUNodes] address 0x4201600000 number of nodes 1
[hsaKmtFreeMemory] address 0x4201600000
Platform #0: Clover
 +-- Device #0: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.20.7-gentoo, LLVM 7.0.1)
 `-- Device #1: Radeon RX 570 Series (POLARIS10, DRM 3.27.0, 4.20.7-gentoo, LLVM 7.0.1)
```

**Comment by fxkamd** [comment]
The log looks reasonable. The Thunk detects that there is a 64GB virtual address limit because of the RX570. That's consistent with the kernel log messages in your earlier post. And it looks like all the addresses it tries to map are well within that limit. I don't see any evidence of a memory allocation failure.

The messages "Memory exception on virtual address 0x0, node id 0" are harmless, but they have been fixed since ROCm 2.0. Looks like you're using an outdated version of the Thunk, version 1.9 or older. I recommend you upgrade to version 2.1.

**Comment by kpande** [comment]
thunk is from git, too:

```
[I] media-libs/ROCT-Thunk-Interface [1]
     Available versions:  (~)1.7.1-r2 (~)1.8.9999 (~)1.9.9999 (~)9999
     Installed versions:  9999(08:56:44 PM 2019-02-16)
     Homepage:            https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/
     Description:         ROCKT-Thunk-Interface
```

**Comment by kpande** [comment]
is this a valid branch? I can build another:

```
EGIT_BRANCH="fxkamd/drm-next-wip"
```

**Comment by kpande** [comment]
ah, looks like last commit was in March 2018. I'll build `master`.

**Comment by kpande** [comment]
```
# clinfo -l
Platform #0: Clover
 +-- Device #0: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.20.7-gentoo, LLVM 7.0.1)
 `-- Device #1: Radeon RX 570 Series (POLARIS10, DRM 3.27.0, 4.20.7-gentoo, LLVM 7.0.1)
Platform #1: AMD Accelerated Parallel Processing
 +-- Device #0: gfx900
 `-- Device #1: gfx803

```
