### ISSUE TITLE
Bazel version

### ISSUE THREAD

**Issue by baerbock** [RadeonOpenCompute/ROCm#715]
Is bazel 0.22.0 currently supported? Until shortly it wasn't.

**Comment by jlgreathouse** [comment]
Hi @baerbock 

I'm not sure your question has enough details for me to answer it. Is bazel 0.22.0 supported for what?

**Comment by kentrussell** [comment]
We don't build using Bazel. If you want components to build via Bazel, feel free to make the changes yourself and submit them for review. We don't use Bazel internally, and there is no pressure to move to using it, so any support for building the ROCm stack in Bazel will either be coincidental, or by users submitting patches to make it happen.
