### ISSUE TITLE
ROCM memory management support on AMD APUs? 

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCm#72]
Is it possible to reserve few addresses of DRAM as config registers during boot up ? I need to access the same physical address on each boot up . These will be a device config registers for my application research.
Can we modify the MMU for this requirement in ROCM platform ?

**Comment by hthangirala** [comment]
It is not possible since this will bypass important protections provided by ASLR. However, you are welcome to modify the ROCK-Kernel-Driver for local experimentation.
