### ISSUE TITLE
Frameworks supported on AMD Tonga FirePro S7100X?

### ISSUE THREAD

**Issue by smokhov** [RadeonOpenCompute/ROCm#720]
I guess this is partially related to #509.

We have received HPC hardware with 5x GPUs of this model. ROCm does not seem to support it :-( The users are asking for deep learning and related frameworks that could take advantage of such GPUs in our servers... so my question here really is what is supported -- any list of libraries, frameworks, tools, that work right off the bat on these GPUs, or we have to write our own wrappers/shaders/OpenCL code first?

Thanks!

**Comment by jlgreathouse** [comment]
ROCm is neither supported nor enabled on Tonga at this time, nor are any of our ROCm libraries or ROCm-based GPU ML frameworks. Keep an eye on #509 if you would like to wait for potential experimental enablement. At this time, we have no plans for adding official support.

**Comment by smokhov** [comment]
I guess my question is how about non-ROCm, any other set of software supports it out of the box?

**Comment by jlgreathouse** [comment]
You are probably better off asking in other forums e.g. the [AMD community forums](https://community.amd.com/). This issue tracker is for ROCm software specifically, and I do not have enough contacts outside of this group to accurately answer that question.

**Comment by smokhov** [comment]
Clear, thanks!
