### ISSUE TITLE
Is ROCm-Debugger/GDB Deprecated? Any alternatives?

### ISSUE THREAD

**Issue by JMadgwick** [RadeonOpenCompute/ROCm#726]
I was recently looking at how I might easily disassemble a GPU kernel created by a HC Program I have been working on. I found that the view ISA function in CodeXL doesn't support gfx906 yet and then found [ROCm-Debugger which seems to be able to do this.](https://github.com/RadeonOpenCompute/ROCm-Debugger/blob/master/TUTORIAL.md#how-do-i-view-the-gpu-isa-disassembly)
However it hasn't been updated since 2017.
It's instructions state that:
> Note that both rocm-gpudebugsdk and rocm-gdb debian packages are included as part of the ROCm repo install.

But this is **no longer the case**, [others users have discovered this already but their issue has not received any attention.](https://github.com/RadeonOpenCompute/ROCm-Debugger/issues/10)
The [current ROCM documentation states](https://rocm-documentation.readthedocs.io/en/latest/ROCm_Tools/ROCm-Tools.html#rocm-gdb):
> ROCm-GDB
> The ROCm-GDB is being revised to work with the ROCr Debug Agent to support debugging GPU kernels on Radeon Open Compute platforms (ROCm) and will be available in an upcoming release.

This seems unlikely given that development stopped two years ago and had been regular before that.
Are there plans to resurrect ROCm-GDB? **Any other ways to extract and disassemble a kernel from a HC Program?** I will try using the [rocr_debug_agent](https://github.com/ROCm-Developer-Tools/rocr_debug_agent#code-object-saving) but it looks like a step backwards in usability and functionality compared to ROCM-gdb which looked to have had similar usage to gdb.

Also, I think that all the ROCm and GPUOpen repos could use a spring clean more generally, because there seem to be loads of _other_ dead/zombie repos similar to rocm-gdb, where development stopped a while ago or moved elsewhere. However **google still ranks these repos high up in search results** (which is how I found them).
It would be useful if outdated repos were marked as _Deprecated_ so that nobody is confused by why the instructions in them don't work or conflict with the main documentation.

**Comment by jlgreathouse** [comment]
You can ask the HCC compiler to emit assembly code by setting the environment variable  `KMDUMPISA=1` You can control other compile-time mechanisms [using similar environment variables](https://github.com/RadeonOpenCompute/hcc/blob/roc-2.1.0/lib/clamp-device.in#L15). For example, `KMDUMPDIR` lets you configure where these files are saved to.

Set the environment variables before compiling your HCC or HIP kernels.

If you are running OpenCL, you can pass [related flags in at kernel compilation time](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/roc-2.1.0/compiler/lib/utils/OPTIONS.def#L948), or you can set them in the environment variable `AMD_OCL_BUILD_OPTIONS_APPEND`:
- `-save-temps` will save ISA files for your kernels into the current working directory. You can set `-save-temps=foo` to append "foo" to all of the files that are dumped out.
- You can also set `-g` to turn enable debug symbols.

You may want to match assembly lines back to source code lines. Our [debug agent](https://github.com/ROCm-Developer-Tools/rocr_debug_agent/blob/roc-2.1.0/src/HSADebugInfo.cpp#L409) shows how you can use our included `llvm-objdump` to perform this. 

To get your GPUs' graphics generation numbers, you can run:
```bash
`rocminfo | grep "Name:\ \+gfx" | awk {'print $2'}`
```

Then, to get an ISA file annotated with line numbers:
- For OpenCL, run the following command on the .so file generated by `-save-temps`
  - `/opt/rocm/opencl/bin/x86_64/llvm-objdump -mcpu=${GFX_NUM} -source -line-numbers _temp_${N}_${GFX_NUM}.so`
    - Make sure you pass in `-g` when building the kernel. See the above note about `AMD_OCL_BUILD_OPTIONS_APPEND` for an easy way to do that.
    - `${N}` will change depending on how many OpenCL strings were passed into `clBuildProgram`.
    - You should change `${GFX_NUM}` depending on the GPU graphics generation number of your target device.
- For HIP and HCC, run this on the .isabin file generated by `KMDUMPISA`
  - `/opt/rocm/hcc/bin/llvm-objdump -mcpu=${GFX_NUM} -source -line-numbers dump-${GFX_NUM}.isabin`
    - You should build your kernel with `-gline-tables-only` passed in to the HCC compiler.
    - You should change `${GFX_NUM}` depending on the GPU graphics generation number of your target device.

**Comment by JMadgwick** [comment]
Thank you very much for all that info. Those environment variables should be added to the HCC wiki as I never knew anything like that was possible to do so easily. I will definitely be using llvm-objdump. I had naively tried something similar but only found references to 'Kalmar' in the assembly presumably this has something to do with how the ISA is stored in the ELF binary.

I'm guessing then that ROCm gdb has been replaced with rocr_debug_agent for now?

**Comment by dragontamer** [comment]
@jlgreathouse Thanks for the information, that was helpful for me too.

There seems to be a lot of functionality in the environmental-variables of HCC. For example, I've found HCC Profile Mode to be quite helpful for my personal uses (HCC_PROFILE=2: https://scchan.github.io/hcc/md__home_scchan_code_hcc_doc_markdown_hcc_profile.html)

But there doesn't seem to be a centralized location that describes all of these useful environmental variables. Can I suggest that maybe a document be put together that unifies all of these environmental flags to HCC?

**Comment by jlgreathouse** [comment]
Hi @JMadgwick 

For the moment, the ROCr debug agent is our mechanism for accessing such debug information on GPUs within the ROCm stack. We are still in the process of making a new GDB port that uses the ROCr debug agent as its underlying mechanism. While the documentation hasn't been updated recently, rest assured we have engineers hard at work getting a new version of GDB built on this more robust underlying debug layer.

To help avoid confusion, we are going through the process of updating old repos that contain deprecated software, archiving them, and moving them to [ROCmArchive](https://github.com/ROCmArchive/). This should help avoid some problems in the future where folks find old, no-longer-maintained repos and use them even if they've been replaced or no longer maintained.

I'll also note that you can get the code objects run by your application [using the ROCr debug agent](https://github.com/ROCm-Developer-Tools/rocr_debug_agent/blob/roc-2.2.0/README.md#code-object-saving). If you use this mechanism, you no longer need to set any HCC environment variables at compile time. You can instead save off the files at runtime and then run objdump on them later.

**Comment by jlgreathouse** [comment]
@JMadgwick and @dragontamer 

If you have recommendations for documentation or wiki updates for HCC, please feel free to submit them (as either PRs or issues) in the HCC repo. I suspect that the HCC developers may not see such requests in this main repo. :)
