### ISSUE TITLE
Is executable HSACO code runnable on Windows OS?

### ISSUE THREAD

**Issue by ghostplant** [RadeonOpenCompute/ROCm#727]
AMD driver for Windows supports OpenCL 2.1 applications, so I wonder whether HSACO code is compatible bewteen Linux and Windows. Whether it is possible to extract the HSACO code from a Linux ROCm program and import/execute it as an OpenCL kernel code on Windows?

**Comment by jlgreathouse** [comment]
Hi @ghostplant 

No, HSACO code is not directly compatible with Windows. You could try cracking open the hsaco file (it's basically ELF) and pulling out the kernel descriptor and code. However, I do not personally know:
- If the code you pull out of there will work on the Windows OpenCL runtime
- How you would insert such code into a Windows OpenCL program.

You might try asking the ROCm OpenCL project, but as far as ROCm is concerned, code generated on our runtimes runs on our runtimes.
