### ISSUE TITLE
Pytorch / python3

### ISSUE THREAD

**Issue by billwebb** [RadeonOpenCompute/ROCm#728]
I need to run pytorch with python3, as the projects I need to work on are currently python3 based.

I've tried following these instructions (below) which all provide pytorch for python2.  I've made unsuccesful attempts to build pytorch with python3 with no luck.  Any suggestions?

https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html#recommended-install-using-published-pytorch-rocm-docker-image

https://rocm.github.io/pytorch.html

**Comment by iotamudelta** [comment]
@billwebb can you make this issue on ROCmSoftwarePlatform/pytorch so that we can document the process there? It is straightfoward.

**Comment by billwebb** [comment]
Done 

https://github.com/ROCmSoftwarePlatform/pytorch/issues/373
