### ISSUE TITLE
ROCm 2.7: OpenCL device side enqueue not working on Radeon Pro Duo and gfx701

### ISSUE THREAD

**Issue by Moading** [RadeonOpenCompute/ROCm#732]
Hi,

I'm running ROCm 2.2 on ubuntu 16.04.6 with kernel 4.15.0-13-generic. The mainboard is Supermicro X10SRA-F. I have written a minimal program that demonstrates device side enqueue. The program can be found here: #540.

The program hangs on ROCm 2.2. I have tried with a Radeon Pro Duo and a Radeo R390. When using the Radeon Pro Duo, I can kill the program with strg+c. When using the R390 some output is generated in dmesg and a reboot is required.

Please see the output of dmesg for both GPUs.

[dmesg_gfx701.zip](https://github.com/RadeonOpenCompute/ROCm/files/2961324/dmesg_gfx701.zip)
[dmesg_gfx803.zip](https://github.com/RadeonOpenCompute/ROCm/files/2961325/dmesg_gfx803.zip)

It would be fantastic if anyone could have a look at this. Device side enqueue is a core feature of OpenCl 2.0!

Greetings!

**Comment by Moading** [comment]
Hi,
I was wondering if this issue could be caused by the motherboard and the CPU. The GPU is directly connected to the CPU but there is a PCIe switch on the card. dmesg does not contain a warning about PCIe atomics.
I am also wondering why this issue gets zero attention. Is my GPU too old to ever be fully supported in ROCm? If there is nobody working on this now, the fix will not be in the next release. Time flies by and the chance to create a great product is gone.

**Comment by Moading** [comment]
I'll just keep changing the title here...

**Comment by Moading** [comment]
Should I move this issue to 'ROCm-OpenCL-Runtime' or 'ROCm-OpenCL-Driver'? If yes, which one?

**Comment by Moading** [comment]
If anyone cares, this is not working in ROCm 2.7...

**Comment by b-sumner** [comment]
Are you checking that the runtime says the device supports opencl 2.0?  It should not be reporting support for gfx701 since gfx701 simply doesn't have the required capabilities to support device enqueue on ROCm.   Now, it turns out that other 2.0 features can be used, but we don't report 2.0 unless all the 2.0 features work.

**Comment by Moading** [comment]
Thanks for your reply, I would really love to see that someone is following this issue, becasue it has been around for a while.

I used the gfx701 in the beginning to isolate the problem. I have not tested it for a while since I got the impression that the support for that GPU is broken in ROCm. I am only working with Radeon Pro Duo GPUs now.

Please, find the output of clinfo here:

[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/3505902/clinfo.txt)

**Comment by b-sumner** [comment]
Thanks. I have no idea what "Radeon Pro Duo" is, but I see gfx803 and Ellesmere in the clinfo output so I understand what you have now.

gfx803 does have the capability of supporting device enqueue on ROCm, but your system may not.  The OpenCL runtime is supposed to check, and if it does, will report that the device is 2.0.

**Comment by Moading** [comment]
"Radeon Pro Duo" is a dual GPU sold by AMD.

clinfo reports

Device OpenCL C version:			 OpenCL C 2.0 
Version:					 OpenCL 1.2 

This means the device does support device side enqueue, right? The GPU runs other OpenCL 2.0 code without problems. For exmaple the work_group_scan_exclusive_add (also a OpenCL 2.0 feature) worked in ROCm 2.6.
Only the device side enqueue part seems broken to me.

**Comment by b-sumner** [comment]
It does not.  It's saying that the compiler accepts the 2.0 C language (CL_DEVICE_OPENCL_C_VERSION), but that the CL_DEVICE_VERSION is 1.2.   The latter will say OpenCL 2.0 if all 2.0 features are supported.

**Comment by Moading** [comment]
OK, I learned something and the hope to get this working returns!

I can run kernels using device side enqueue on the same hardware in windows 10, therefore I assume it is not a hardware limitation. What is missing in my linux system to get this working? I would be super happy if we could resolve this issue!

**Comment by b-sumner** [comment]
I believe it actually is a hardware limitation.  The mechanisms that are used to implement device enqueue on windows and ROCm are quite different and have different requirements of the device and system hardware.

**Comment by Moading** [comment]
clinfo also reports:
Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes

Reading "https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime" adds to my confusion...

"Developer preview Version 2 of the new
    OpenCL 1.2 compatible language runtime and compiler
    OpenCL 2.0 compatible kernel language support with OpenCL 1.2 compatible runtime"

So ROCm can compile OpenCL 2.0 but the GPU can not run the kernel? This means there is no device side enqueue for any GPU right now?

**Comment by Moading** [comment]
OK, if it is a hardware limitation, can you say which components need to be changed? CPU, mainboard, GPU or all of them?

CPU is Xeon e5-2680 v3
mainboard is Supermicro X10sra-f
GPU is AMD Radeon Pro Duo (Polaris)

**Comment by b-sumner** [comment]
I believe the current support for device enqueue on ROCm is limited to gfx9xx and later.  I cannot make any guarantees, but assuming your board fully supports ROCm, I would expect a gfx9xx device, e.g. gfx900 ("vega10") to work.

**Comment by Moading** [comment]
Can I file a feature request to bring device side enqueue to gfx803?

**Comment by b-sumner** [comment]
For ROCm?  The hardware can't support it.  If you need it on linux, I think you will need to go with linuxpro (which uses a substantially different mechanism and a substantially different kernel driver).

**Comment by Moading** [comment]
Thanks for your effort here. When you say "linuxpro" you mean "AMDGPU-PRO Driver for Linux®" ?
My heart is not tied to ROCm so another driver would be fine for me.

**Comment by b-sumner** [comment]
Yes, that is what I meant.  And I should not have implied that it will definitely work.  I haven't run it myself for a few years.

**Comment by Moading** [comment]
That driver offers OpenCL 1.2 on linux, only the windows version offers OpenCL 2.0. Alright, I'm closing this issue, thanks for your effort!
