### ISSUE TITLE
Error in manifest file for ROCm 2.2

### ISSUE THREAD

**Issue by FinnStokes** [RadeonOpenCompute/ROCm#733]
The contents of default.xml seem to be almost duplicated, causing a parsing error when checking out with repo, when the parser encounters a second xml declaration in the middle of the manifest block:
```
fatal: manifest 'default.xml' not available
fatal: error parsing manifest /home/fstokes/build/ROCm-2.2/.repo/manifests/default.xml: XML or text declaration not at start of entity: line 57, column 0
```

**Comment by jlgreathouse** [comment]
#734 should fix this.
