### ISSUE TITLE
Missing tags for roc-2.2.0 cause repo sync failure

### ISSUE THREAD

**Issue by FinnStokes** [RadeonOpenCompute/ROCm#737]
There is no `roc-2.2.0` tag in the `rocm_bandwidth_test`, `rocm_smi_lib`, and `roctracer`. In addition, revision `7ce124f86d0fa59387462fc09a49b25ccb81f96` doesn't seem to exist in the tree for `clang-ocl` on github. This causes `repo sync` to fail.

**Comment by jlgreathouse** [comment]
Fixed. Just pushed the changes and verified that a full repo sync works. Thanks for the report about this, and sorry about the problems.
