### ISSUE TITLE
Will ROCm 2.2 support PCI 3 x8 slot ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#742]
I have two cards on my system, one on x16 slot and one on x8 slot.

Only the x16 card has been detected by ROCm for OpenCL, although
`rocm-smi` sees both cards. 

Why can `rocm-smi` see both cards, but `clinfo` only detects one ?

And will both cards be usable for OpenCL in the future ?

**Comment by jlgreathouse** [comment]
It depends on [your GPUs, your motherboard, and potentially your CPU](https://github.com/RadeonOpenCompute/Experimental_ROC/blob/master/distro_install_scripts/Ubuntu/common/component_scripts/01_09_hcc.sh).

 - If your GPUs are from the gfx8 generation, they require the ability to access system memory using PCIe atomics in order for the KFD driver to allow ROCm computation kernels to run.
 - Your motherboard may or may not connect the x8 slot to the system with proper PCIe atomics support.
 - Whether your motherboard's PCIe 3.0 x8 slot has working atomics may depend on your CPU. For instance, a Ryzen APU may have fewer working PCIe connections than a Ryzen CPU even if they both use AM4 sockets.

`rocm-smi` can see any GPU that has a working graphics driver. `rocminfo` and `clinfo` require a working KFD compute connection to show the device.

If you run `dmesg | grep kfd` you will probably find that your second GPU does not have a working PCIe atomics connection to the host.

**Comment by boxerab** [comment]
Thanks, @jlgreathouse . Yes, my GPU is a gfx8. I was just hoping that with 2.2 update I wouldn't require atomics to use the card.
