### ISSUE TITLE
ROCm 2.2: is it possible to run applications in CL1.2 compatibility mode?

### ISSUE THREAD

**Issue by vvsteg** [RadeonOpenCompute/ROCm#743]
Is it possible in ROCm 2.2 to run applications in the OpenCL1.2 compatibility mode? 

This question has been raised because of this issue with LAMMPS OpenCL version
https://github.com/lammps/lammps/issues/1368

**Comment by jlgreathouse** [comment]
You can pass in `-cl-std=CL1.2` at compile time, but I see in your bug report that you have already tried that. For anyone finding this issue in the future: you can force this flag into your compile path with the environment variable `AMD_OCL_BUILD_OPTIONS_APPEND` or you can fully replace your OpenCL kernel build options with `AMD_OCL_BUILD_OPTIONS`

Actually, the error you are seeing [was also an error in OpenCL 1.2](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/local.html). To quote, "Variables allocated in the __local address space inside a kernel function must occur at kernel function scope." As such, even if you are building in CL1.2 mode, this error is still valid.
