### ISSUE TITLE
Is it possible to use llvm/clang-8.0.0 to build ROCm?

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/ROCm#749]
Is it possible to use llvm/clang-8.0.0 from llvm.org to build ROCm?

**Comment by jlgreathouse** [comment]
Could you define what you mean by "build ROCm"? Which parts of ROCm are you looking to build, precisely? Is there a particular problem you're running into if you try to do this?

**Comment by justxi** [comment]
There is currently no problem. At least I want to build ROCt-Thunk-Interface, ROCR-Runtime and ROCm-OpenCL-Runtime. Other parts/packages should follow.  
If it is possbile to use llvm/clang from llvm.org, it would not be necessary to install llvm/clang from ROCm additionally (I am trying to help package ROCm for Gentoo Linux). 
So my question is, if it is known to work or if there are changes which are not upstreamed yet, but necessary for building?

**Comment by jlgreathouse** [comment]
So your question is that you want to _build_ ROCm using upstream LLVM, or you want to _use_ upstream LLVM in parts of ROCm (such as for the back-end device compiler for our OpenCL runtime)?

**Comment by justxi** [comment]
The second, I want to use upstream LLVM in parts of ROCM.

**Comment by scchan** [comment]
Most of our compute libraries depend on custom changes that currently only exist in our own branches.  Also, our toolchain and libraries evolve pretty quickly together so it would require the entire stack to be upgraded for every new release.

**Comment by justxi** [comment]
Ok, thank you, that clarifies my question. 
Is it planned to upstream all changes in the long term?

**Comment by scchan** [comment]
yes

**Comment by justxi** [comment]
Ok, then I will wait and postpone splitting the build process.
In the meantime I will use all the software from the ROC repsositories.
Thanks.
