### ISSUE TITLE
Make hsa-ext-rocr-dev as optional deb package to install

### ISSUE THREAD

**Issue by elukey** [RadeonOpenCompute/ROCm#761]
Hi everybody,

thanks a lot for all the efforts to keep this suite as open as possible to the community. I have read in several places (https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/33, https://github.com/RadeonOpenCompute/ROCm/issues/267#issuecomment-422172140) that the only remaining package not open source is `hsa-ext-rocr-dev`, that IIUC, should be optional. The main issue is that in several rocm deb packages it is listed as dependency:
```
apt-cache rdepends hsa-ext-rocr-dev
hsa-ext-rocr-dev
Reverse Depends:
  hsa-rocr-dev
  rocm-dev
  hcc
```

It would be extremely useful if that dependency was removed, so whoever wants to stick with open-source only could deploy rocm without having to mess with dependencies to remove `hsa-ext-rocr-dev`. A quick update of the documentation would resolve any doubt from whoever wants to keep closed sources binaries.

Thanks in advance!

Luca

**Comment by elukey** [comment]
Any comment? :)

**Comment by elukey** [comment]
Re-iterating the question, maybe this time I'll have more luck :)

**Comment by elukey** [comment]
I'd love to get a comment on this, even "we don't know", please :)

**Comment by elukey** [comment]
@jlgreathouse sorry to ping you directly, but would you know how can I follow up on this? I am a fan of ROCm, we'd love at Wikimedia to use a fully open source solution for GPUs but this use case is kinda blocking us. I am available to work on a solution if needed! Thanks in advance..

**Comment by elukey** [comment]
With 2.4 seems to be worse:

```
Reverse Depends:
  hsa-rocr-dev
  rocm-dev
  hsa-rocr-dev
  hcc
  rocm-dev
  hcc
```

**Comment by elukey** [comment]
This could be interesting, even though only for hcc:

https://github.com/RadeonOpenCompute/Experimental_ROC/blob/34c7766472436e729b74d0e2af4748d58d30d931/distro_install_scripts/shared_files/patches/hcc_open_build.patch

**Comment by elukey** [comment]
Gently ping again :)

**Comment by elukey** [comment]
Another ping before giving up..

**Comment by pramenku** [comment]
Hi elukey
Thanks for reporting.
We will see how we can do or what's the best solution and come back. Not promising anything for now.
Please stay tuned. 

Thanks.

**Comment by elukey** [comment]
@pramenku thanks a lot!

**Comment by pramenku** [comment]
Hi elukey,
It looks like in near future, these dependency things will be removed.
When and how, will be known later. Please stay tuned. 
Thanks

**Comment by elukey** [comment]
Any news??

**Comment by pramenku** [comment]
Sorry. Work is in progress but no exact date as of today. It's not straight forward so taking time. 
Thanks for getting the update.

**Comment by elukey** [comment]
Any news?

**Comment by pramenku** [comment]
Hi @elukey 
 hsa-ext-rocr-dev is no more part of rocm packages and entire runtime is now part of hsa-rocr and hsa-rocr-dev.
 
 You can refer https://rocmdocs.amd.com/en/latest/Installation_Guide/Software-Stack-for-AMD-GPU.html
You can close this issue if you get the answer.

**Comment by elukey** [comment]
@pramenku Hi! Thanks a lot for the update. IIUC the content of `hsa-ext-rocr-dev` is not a problem anymore, so ROCm doesn't need to install anymore binary-only packages (all open source). If this is true, great result, you folks are great!

**Comment by pramenku** [comment]
Thanks @elukey for nice comment. :)  Your understanding is correct.
Keep using ROCm and enjoy it.  :) You can close this issue.  :)
