### ISSUE TITLE
Where to find ROCm 2.2

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#769]
Hi, I would like to install ROCm 2.2 from binary packages. Where may I find it?

**Comment by beatboxa** [comment]
See my reply here:
https://github.com/RadeonOpenCompute/ROCm/issues/768#issuecomment-483283444

You are able to follow that tree, and you will eventually come across this:

http://repo.radeon.com/rocm/

**Comment by preda** [comment]
Thanks! adding 
deb [arch=amd64] http://repo.radeon.com/rocm/apt/2.2/ xenial main
to a file under /etc/apt/sources.list.d allows to install ROCm 2.2
