### ISSUE TITLE
ROCm 2.3 can compile blender 2.8 beta cycles kernels, but the performance is pretty bad

### ISSUE THREAD

**Issue by iszotic** [RadeonOpenCompute/ROCm#772]
System: cpu, AMD 1700, gpu Vega 56
Driver: AMDGPUpro 18.50 or ROCm 2.3
Kernel: Linux-4.15.0-47
Operating system: Kubuntu 18.04.2
Blender Version: 2.80, 860a9f979d60, 2018-04-14

With AMDGPUpro drivers it takes only 8secs with CPU+GPU rendering with the default scene
while with ROCm 2.3 it takes 44secs, in fact, this is the time it takes to render a 64x64 tile, because the CPU finishes the rest in few seconds, and the GPU it's doing work because I can see the usage leds in Vega 56 all lighten up

**Comment by advancingu** [comment]
Same for me. See also #402.

**Comment by advancingu** [comment]
Still unchanged with latest ROCm release packages `1.2.0-2019050231` and Blender 2.80 `3dc9da3a74ee`: Kernel eventually compiles but GPU rendering remains many times slower than CPU even for default box scene.

**Comment by ubombi** [comment]
Is it okay, that kernels compile time is 1hour per kernel?
I mean 
```
Kernel compilation of split_bundle finished in 3427.13s.
Kernel compilation of split_shadow_blocked_ao finished in 3427.52s.
Kernel compilation of split_shadow_blocked_dl finished in 3427.56s.
Kernel compilation of split_holdout_emission_blurring_pathtermination_ao finished in 3427.48s.
Kernel compilation of split_lamp_emission finished in 3427.41s.
Kernel compilation of split_indirect_background finished in 3427.30s.
Kernel compilation of split_direct_lighting finished in 3427.36s.
Kernel compilation of split_shader_eval finished in 3427.24s.
```

**Comment by ROCmSupport** [comment]
Hi @iszotic 
This is very old issue and its no more observed.
But we have different issue now and so this can be tracked via #1106 and #1210
