### ISSUE TITLE
rocm-smi (rocm v2.3) error

### ISSUE THREAD

**Issue by WannaBeOCer** [RadeonOpenCompute/ROCm#777]
Was working fine with ROCm v2.2, manually setting the power target to 300w also works fine.

> Traceback (most recent call last):
>   File "/opt/rocm/bin/rocm-smi", line 1910, in <module>
>     setPowerOverDrive(deviceList, args.setpoweroverdrive, args.autorespond)
>   File "/opt/rocm/bin/rocm-smi", line 1396, in setPowerOverDrive
>     power_cap_path = getFilePath(device, 'power1_cap')
>   File "/opt/rocm/bin/rocm-smi", line 130, in getFilePath
>     pathDict = valuePaths[key]
> KeyError: 'power1_cap'

**Comment by kentrussell** [comment]
I fixed this internally but missed the 2.4 fix. All you have to do is edit the SMI and change "power1_cap" to "power_cap" on line 1396. It'll be in 2.5, but that doesn't help right now.

**Comment by WannaBeOCer** [comment]
> I fixed this internally but missed the 2.4 fix. All you have to do is edit the SMI and change "power1_cap" to "power_cap" on line 1396. It'll be in 2.5, but that doesn't help right now.

Thank you!

**Comment by kentrussell** [comment]
This is fixed in 2.5
