### ISSUE TITLE
OpenCL clBuildProgram terminates on invalid -save-temps

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#779]
ROCm 2.2 OpenCL:

when clBuildProgram() is invoked with an invalid path in -save-temps , it terminates the process abruptly after displaying the message:
LLVM ERROR: IO failure on output stream: Bad file descriptor

The expected behavior of clBuildProgram is to return an error code != CL_SUCCESS on error, not to terminate the process.

**Comment by jlgreathouse** [comment]
Please submit this bug to the [ROCm OpenCL project](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues).
