### ISSUE TITLE
Tonga support and numba

### ISSUE THREAD

**Issue by extraymond** [RadeonOpenCompute/ROCm#78]
Hi! I would like to know if hsa on numba is still going to be supported by rocm.
And when will we be able to use tonga with all these cool stuff.
Thx

**Comment by gstoner** [comment]
We are bringing Anaconda/Numba on to ROCm. We moving further with the integration on math libraries as well.

**Comment by extraymond** [comment]
@gstoner  Thx! This is the news of relief!

**Comment by extraymond** [comment]
@gstoner 

Hi! Would like to know the support status of tonga.
It's not answered above so would love to know if I should wait or get newer hardware if it's not gonna get supported in the end.

**Comment by gstoner** [comment]
Tonga technically run with current ROCm 1.6.3 stack, we just tested it on W7100.  But we have not done a lot of testing on it.

**Comment by extraymond** [comment]
I'm on 16.04 and clinfo show me segfault.

Gregory Stoner 於 2017年09月14日 00:30 寫道:

**Comment by extraymond** [comment]
Hi! Is there any updates on this?
