### ISSUE TITLE
NOTICE NOTICE NOTICE NOTICE

### ISSUE THREAD

**Issue by Moading** [RadeonOpenCompute/ROCm#790]
Hi,
after installing ROCm 2.4 the message below appears in the output of dmesg:

[   32.164728] **********************************************************
[   32.164729] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[   32.164730] **                                                      **
[   32.164731] ** trace_printk() being used. Allocating extra memory.  **
[   32.164731] **                                                      **
[   32.164732] ** This means that this is a DEBUG kernel and it is     **
[   32.164733] ** unsafe for production use.                           **
[   32.164734] **                                                      **
[   32.164735] ** If you see this message and you are not debugging    **
[   32.164735] ** the kernel, report this immediately to your vendor!  **
[   32.164736] **                                                      **
[   32.164737] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[   32.164738] **********************************************************

**Comment by Moading** [comment]
first to see this :)

**Comment by thesleort** [comment]
You sure this is related to ROCm? My dmesg is not saying this with 2.4. Just did a reboot to check again, when I saw your issue.

**Comment by Moading** [comment]
You are right, it was something else, sorry for the confusion.
