### ISSUE TITLE
Texture objects?

### ISSUE THREAD

**Issue by szellmann** [RadeonOpenCompute/ROCm#81]
Hi, I'd like to ask if support for texture objects like those introduced with CUDA 6.5 is planned - dedicated access to the HW linear texture filtering routines, and variable texture object count accessible from within kernels. I could findno such thing in the docs, is this somewhere on the roadmap?

**Comment by boxerab** [comment]
I believe these are known as images in opencl land. Images are not supported yet.

**Comment by jedwards-AMD** [comment]
Image support is being planned for the OpenCL LC implementation. Are you referring to OpenCL image support or support in another programming model?

**Comment by boxerab** [comment]
Thanks. What is "OpenCL LC", may I ask ?

**Comment by jedwards-AMD** [comment]
OpenCL LC is AMDs OpenCL implementation that uses what is known as the lightning compiler. It is the only implementation of OpenCL that is supported on ROCm.

**Comment by boxerab** [comment]
Cool. Where can I learn more about this compiler?  Can you comment on stability and performance?

**Comment by jedwards-AMD** [comment]
The compiler is actually distributed as HCC. The OpenCL implementation uses parts of HCC to enable kernel compilation.

**Comment by jedwards-AMD** [comment]
The LC compiler is actually a part of HCC. Please look at this link for details: https://github.com/RadeonOpenCompute/hcc

**Comment by boxerab** [comment]
Great. Thanks for the info.  I have an application that makes heavy use of opencl images, so really looking for this to arrive for ROCm.

**Comment by szellmann** [comment]
Ah sorry, I would maybe better have placed this in the hcc issue tracker. I'm interested in using images with hcc.

CUDA originally had support for textures (their analog to images in OCL), and they were directly related to texture units, i.e. you had to have a static amount of textures. They relaxed this later (I think wirh CUDA 6)  so that you could use texture objects and wouldn't need to (e.g.) pack a dynamic number of images into an atlas. So texture objects (or whatever one would call them in the ROCm world) rather than mere images are what I'm interested in.

**Comment by scchan** [comment]
We are planning to provide image support in a future version of hcc.  Please open a new issue under hcc if you are interested in tracking it.  Thanks,
