### ISSUE TITLE
cant boot with rocm 2.5 and radeon vii

### ISSUE THREAD

**Issue by witeko** [RadeonOpenCompute/ROCm#815]
I've tried ubuntu 18.04.02 and 19.04 with various kernel versions.
I have a threadripper 1920x and 2 x radeon vii and an LG 4k60 monitor on DP.
Looks like my monitor is loosing signal while booting.

**Comment by kentrussell** [comment]
Are you able to ssh into the machine? Is there anything in dmesg to explain the issue? Is the issue present on both cards, or is it limited to the DP output on one card?

**Comment by witeko** [comment]
@kentrussell Did You make any changes that could potentially lead to such a problem? :)
Now I reverted back to 2.4.
If its not easy to pin point the problem than I'm willing to help.

**Comment by kentrussell** [comment]
I didn't personally, but there could be a bug in some of the patches that we brought in from amdgpu/Display team. There shouldn't be anything that's ROCm-specific that caused the issue, but without investigating it's hard to know for sure. If you're happy with 2.4, that's good, but we'd need to do a lot of debugging to figure out what's up, starting with seeing if the machine is just totally not working, or if it's just the display that's not. But without a second machine or a serial connector, that's tougher to do.

**Comment by witeko** [comment]
@kentrussell can You assign someone to this?
There is another similar issue with additional information.

**Comment by witeko** [comment]
@kentrussell is there any progress on the issue/s

**Comment by kentrussell** [comment]
We don't have a radeon vii for me to use unfortunately. Can you ssh into it to get a dmesg from it to give us some insight?

**Comment by Hycdog** [comment]
That's pretty strange. I'm also using radeon vii, and I tried Ubuntu 19.04 , with linux kernel 5.0.0-13, 5.0.0-16, 5.2.0-rc4, and they all worked perfectly well. I'm using rocm 2.5 with KFD that comes with the kernel though, haven't tried to build rocm-dkms module on older kernels.

**Comment by witeko** [comment]
@kentrussell can You check the other issue #818 - its seems its the same as i have.

**Comment by witeko** [comment]
Looks like the monitor just goes "out of range" during the boot with rocm 2.5 (it didnt with 2.4).
I just need to type in my crypto password for my lvm disk while the sceen is "blank" and eventually it boots and the screen turns on.

**Comment by witeko** [comment]
@Hycdog booting with KFD is easy, but if You intend to use it for any compute tasks be prepared to loose a lot of performance. :)

@kentrussell there is nothing in the "failing log", the monitor just goest out of range (no signal) for a while while booting. For most ppl it may not be troublesome, but for me it is (i need to open my luks partition...while the monitor is "blank"). Can You check if the issues is not 100% common to all ppl (but they might not report it).

**Comment by kentrussell** [comment]
We are looking at one issue with a display patch that caused the monitor to fail on 2.5. One of our devs is already working with the Display team to figure out what's happening with it. Hopefully that will address the issue. Once a fix is confirmed, I'll post the code here so that you can try to build the kernel yourself, instead of waiting for 2.6. I'll keep you apprised.

**Comment by witeko** [comment]
@kentrussell thx, I will check tomorrow. :)

**Comment by witeko** [comment]
@kentrussell i doesnt work for me. I need a different solution.

**Comment by witeko** [comment]
@kentrussell I would like to expand my issue.
I order to use rocm 2.5 I need to use kernel 4.18 (it works but has this display issue on boot).
When I want to use 4.15 the dkms driver doesn work at all - i get:
make -j24 KERNELRELEASE=4.15.18-041518-generic -j24 kdir=/lib/modules/4.15.18-041518-generic/build -C /lib/modules/4.15.18-041518-generic/build M=/var/lib/dkms/amdgpu/2.5-27/build....(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-4.15.18-041518-generic is not supported
Error! Bad return status for module build on kernel: 4.15.18-041518-generic (x86_64)
Consult /var/lib/dkms/amdgpu/2.5-27/build/make.log for more information.

And the make.log is:
DKMS make.log for amdgpu-2.5-27 for kernel 4.15.18-041518-generic (x86_64)
czw, 4 lip 2019, 23:22:57 CEST
make: Entering directory '/usr/src/linux-headers-4.15.18-041518-generic'
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_drm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/main.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/symbols.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/scheduler/sched_main.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_fence.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/scheduler/sched_fence.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_fence_array.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_memory.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_tt.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/scheduler/sched_entity.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_kthread.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_bo.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_io.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_bo_util.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_reservation.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_bo_vm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_pci.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_module.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_mn.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_bitmap.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_execbuf_util.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_drv.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_device_cgroup.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_page_alloc.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_bo_manager.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_device.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_page_alloc_dma.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_workqueue.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_agp_backend.o
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_reservation.c:427:1: warning: ‘reservation_object_add_shared_replace’ defined but not used [-Wunused-function]
 reservation_object_add_shared_replace(struct reservation_object *obj,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_reservation.c:375:1: warning: ‘reservation_object_add_shared_inplace’ defined but not used [-Wunused-function]
 reservation_object_add_shared_inplace(struct reservation_object *obj,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_mm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_kms.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_atombios.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/atombios_crtc.o
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_pci.c: In function ‘amdkcl_pci_init’:
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_pci.c:257:83: warning: passing argument 2 of ‘amdkcl_fp_setup’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  _kcl_pcie_link_speed = (const unsigned char *) amdkcl_fp_setup("pcie_link_speed",_kcl_pcie_link_speed_stub);
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_pci.c:3:0:
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/kcl_common.h:22:21: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
 static inline void *amdkcl_fp_setup(const char *symbol, void *fp_stup)
                     ^~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_connectors.o
/var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_memory.c:29:0: warning: "pr_fmt" redefined
 #define pr_fmt(fmt) "[TTM] " fmt
 
In file included from ./include/linux/kernel.h:14:0,
                 from ./include/linux/list.h:9,
                 from ./include/linux/wait.h:7,
                 from ./include/linux/dma-fence.h:25,
                 from /var/lib/dkms/amdgpu/2.5-27/build/include/kcl/kcl_fence.h:12,
                 from /var/lib/dkms/amdgpu/2.5-27/build/ttm/backport/backport.h:5,
                 from <command-line>:0:
./include/linux/printk.h:285:0: note: this is the location of the previous definition
 #define pr_fmt(fmt) fmt
 
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/atom.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_fence.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_ttm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_object.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_gart.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_encoders.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_display.o
  LD [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdkcl/amdkcl.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_i2c.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_fb.o
/var/lib/dkms/amdgpu/2.5-27/build/ttm/ttm_agp_backend.c:33:0: warning: "pr_fmt" redefined
 #define pr_fmt(fmt) "[TTM] " fmt
 
In file included from ./include/linux/kernel.h:14:0,
                 from ./include/linux/list.h:9,
                 from ./include/linux/wait.h:7,
                 from ./include/linux/dma-fence.h:25,
                 from /var/lib/dkms/amdgpu/2.5-27/build/include/kcl/kcl_fence.h:12,
                 from /var/lib/dkms/amdgpu/2.5-27/build/ttm/backport/backport.h:5,
                 from <command-line>:0:
./include/linux/printk.h:285:0: note: this is the location of the previous definition
 #define pr_fmt(fmt) fmt
 
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_gem.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_ring.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_cs.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_bios.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_benchmark.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_test.o
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_device.c: In function ‘amdgpu_device_get_pcie_info’:
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_device.c:3798:2: error: implicit declaration of function ‘pcie_bandwidth_available’; did you mean ‘pci_aer_available’? [-Werror=implicit-function-declaration]
  pcie_bandwidth_available(adev->pdev, NULL,
  ^~~~~~~~~~~~~~~~~~~~~~~~
  pci_aer_available
  LD [M]  /var/lib/dkms/amdgpu/2.5-27/build/scheduler/amd-sched.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_pm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/atombios_dp.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_afmt.o
  LD [M]  /var/lib/dkms/amdgpu/2.5-27/build/ttm/amdttm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_trace_points.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/atombios_encoders.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_sa.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/atombios_i2c.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_dma_buf.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_vm.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_ib.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_pll.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_ucode.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_bo_list.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_ctx.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_sync.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_gtt_mgr.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_vram_mgr.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_virt.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_atomfirmware.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_vf_error.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_sched.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_debugfs.o
  CC [M]  /var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_ids.o
cc1: some warnings being treated as errors
scripts/Makefile.build:324: recipe for target '/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_device.o' failed
make[2]: *** [/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_device.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu/amdgpu_dma_buf.c:144:1: warning: ‘__reservation_object_make_exclusive’ defined but not used [-Wunused-function]
 __reservation_object_make_exclusive(struct reservation_object *obj)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:583: recipe for target '/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu' failed
make[1]: *** [/var/lib/dkms/amdgpu/2.5-27/build/amd/amdgpu] Error 2
Makefile:1529: recipe for target '_module_/var/lib/dkms/amdgpu/2.5-27/build' failed
make: *** [_module_/var/lib/dkms/amdgpu/2.5-27/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.18-041518-generic'

**Comment by kentrussell** [comment]
Peculiar, that issue should be fixed in 2.5 (actually, it got fixed in 2.4). Do you have a requirement of using the DKMS package? There is always the option to compile the kernel from the source code as a monolithic kernel and installing it that way, ensuring that you get the ROCm code without DKMS. I've been using it on 18.04 without issue, though it is based on 5.0-rc1, not 4.15/4.18, so I don't know if that's an issue or not. But I don't know why that would be failing there since we have that fix in the 2.4/2.5 branches, it doesn't make sense since the patch to fix the code is in there. I can try to dig around a bit more, but 2.6 is coming soon as well, so we can always try that if the monolithic kernel isn't working, or isn't an option.

**Comment by witeko** [comment]
@kentrussell thx for reply, can You give me some guidance on "There is always the option to compile the kernel from the source code as a monolithic kernel and installing it that way, ensuring that you get the ROCm code without DKMS"? :)

**Comment by kentrussell** [comment]
Copy arch/x86/configs/rock-rel_defconfig to the top kernel directory and rename it ".config" without the quotes, then do "make bindeb-pkg" to build it. Install the resulting linux-headers and linux-image package and you should be good. You might need to extract the firmware from the dkms package and copy them into /lib/firmware/amdgpu manually, but thats step 2 , after trying the monolithic build. 2.6 should be out this week if you want to wait for that too, as an FYI.

**Comment by witeko** [comment]
@kentrussell TY :)
I will try to check the monolithic approach in my free time. :)
And I will also try the 2.6 : )

**Comment by witeko** [comment]
@kentrussell look like the rocm 2.6 solved my problem. I check only with 4.18 for now.
If You won't close the ticket just yet I can check other kernels, and scenarios. :)
Thank You for your help. :)

**Comment by witeko** [comment]
4.18 kernel is still the only one I can use. but its fine for now. :)
TY :)
