### ISSUE TITLE
ROCm 2.5 cannot boot vega64 ubuntu 19.04

### ISSUE THREAD

**Issue by Bednar87** [RadeonOpenCompute/ROCm#818]
Hi team,

After upgrading to 2.5 I can no longer boot into ubuntu 19.04. Here's dmesg | grep "amd" output:

> [    0.000000] Linux version 5.0.0-16-generic (buildd@lgw01-amd64-060) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)) #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 (Ubuntu 5.0.0-16.17-generic 5.0.8)
> [    3.022945] amdkcl: loading out-of-tree module taints kernel.
> [    3.022964] amdkcl: module verification failed: signature and/or required key missing - tainting kernel
> [    3.163722] [drm:amdgpu_init [amdgpu]] *ERROR* VGACON disables amdgpu kernel modesetting.

Uninstalling rocm fixes the issue.

https://gist.github.com/Bednar87/c7d6827a18895a78734309afdf3a4758

Any ideas? 

Thanks

**Comment by witeko** [comment]
seems like my issue #815 :)

**Comment by streamhsa** [comment]
Hi Bednar87
Are you getting issue with UB18.04.2/16.04.5 with kernel 4.15.  We have below supported OS details and it seems you are using  higher kernel.

Supported Operating Systems - New operating systems available
The ROCm 2.5.x platform supports the following operating systems:

Ubuntu 16.04.x, 18.04.1 and 18.04.2 (Version 16.04.3 and newer or kernels 4.13-4.15)
CentOS 7.4, 7.5, and 7.6 (Using devtoolset-7 runtime support)
RHEL 7.4, 7.5, and 7.6 (Using devtoolset-7 runtime support)

thanks.

**Comment by pramenku** [comment]
Hi Bednar87
Are you getting issue with UB18.04.2/16.04.5 with kernel 4.15. We have below supported OS details and it seems you are using higher kernel.

Supported Operating Systems - New operating systems available
The ROCm 2.5.x platform supports the following operating systems:

Ubuntu 16.04.x, 18.04.1 and 18.04.2 (Version 16.04.3 and newer or kernels 4.13-4.15)
CentOS 7.4, 7.5, and 7.6 (Using devtoolset-7 runtime support)
RHEL 7.4, 7.5, and 7.6 (Using devtoolset-7 runtime support)

thanks.

**Comment by JMadgwick** [comment]
Just thought I'd chime in and say that you really do need to use 4.15. I ran some updates on my machine and Ubuntu kindly installed 4.18 for me. However this caused me to boot to a black screen. The solution is to uninstall ROCm, then remove all 4.18 kernels and reinstall ROCm.

**Comment by Bednar87** [comment]
2.6 boots fine.
