### ISSUE TITLE
Again, OpenCL only works as root

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#823]
A program running as regular user does not start. Error:

ocl.getPlatformIDs returned error=-1001 and 0 platforms

but it starts when run as root.

**Comment by vastech73** [comment]
Valerie,
can you pls let us know what application were you running ?
Moreover, Could you retry installing rocm/OpenCL and check ?

**Comment by valeriob01** [comment]
First, my name is Valerio.
Second, ROCm already installed.
Application: https://github.com/preda/gpuowl

**Comment by vastech73** [comment]
Valerio,
We will come back to you post checking this internally.
Vasu

**Comment by valeriob01** [comment]
Thanks.

**Comment by valeriob01** [comment]
This is a real problem with some batch systems that do not allow jobs to run as root.

**Comment by vastech73** [comment]
Valerio,
Did you add the user to video group by issuing this command : “sudo usermod -a -G video  $LOGNAME” 
Pls confirm. We have checked internally without adding the user to this group and we see the same issue that has been raised.
Thanks,
Vasu

**Comment by valeriob01** [comment]
Yes, I have added all users to the video group. I would not post this issue if it was so simple to resolve.

**Comment by valeriob01** [comment]
I have found how to resolve the issue partially.
The file /etc/OpenCL/vendors/amdocl64.icd has owner root and group root. Assigning this ownership to a regular user makes that user able to run OpenCL applications.

**Comment by valeriob01** [comment]
I am closing this issue because after a full month there is no feedback. Will reopen new issue if needed.
