### ISSUE TITLE
when u mark the rocm 2.5 release  at source code repo ?

### ISSUE THREAD

**Issue by wormwang** [RadeonOpenCompute/ROCm#824]
~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-2.5.0

fatal: Couldn't find remote ref refs/heads/roc-2.5.0

when u mark the rocm 2.5 release ?

**Comment by jlgreathouse** [comment]
I know this is an old issue, but I just successfully repo synced 2.5.0, so I believe we eventually tagged everything correctly. :)
