### ISSUE TITLE
tensorflow-rocm prereleases aren't available on pypi

### ISSUE THREAD

**Issue by abderrahim** [RadeonOpenCompute/ROCm#832]
There are no 2.0beta of tensorflow-rocm on [pypi](https://pypi.org/project/tensorflow-rocm/#history) (stable 1.14 is also missing). It would be nice if all releases were pushed to pypi.

**Comment by sunway513** [comment]
Hi @abderrahim , we'll release TF1.14 and 2.0-b1 whl packages later of the week after ROCm2.6 is out. 
Please watch for the updates in the TF-ROCm project repo:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream

**Comment by sunway513** [comment]
Hi @abderrahim , we have pushed out the whl packages for TF2.0.0b1 and TF1.14.0:
https://pypi.org/project/tensorflow-rocm/#history
Please kindly review those and let us know if you have questions. 
You can create issues specific to TF-ROCm project in the following repo:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream
