### ISSUE TITLE
ROCm 2.5 memory leaks

### ISSUE THREAD

**Issue by ddobreff** [RadeonOpenCompute/ROCm#834]
Putting this as basic info about the issue.
Running rocm 2.5 for about 2 weeks and discovered it has some sort of kmalloc-1024 memory leak.
Tried old success workarounds with disabling audio and dc but it didn't help much. Running same kernel and 2.4 doesn't leak. On request I will provide whatever debug information is required to solve the issue.

Kernel: 4.19.56
ROCm: 2.5-dkms unmodified.

**Comment by nicolaerosia** [comment]
Can you share how you've disabled the display code/audio? I'm interested to know how to use the card only for compute

**Comment by ddobreff** [comment]
Added in grub: amdgpu.dc=0 amdgpu.audio=0

**Comment by ddobreff** [comment]
> 315600 315600 100%    1.00K  19725       16    315600K kmalloc-1024
After just 3h of running. It eventually eats all the mem left.

**Comment by ddobreff** [comment]
Fixed in 2.6
