### ISSUE TITLE
E: Unable to locate package rocm-dkms on Ubuntu 18.04

### ISSUE THREAD

**Issue by TobiasJu** [RadeonOpenCompute/ROCm#836]
So i followed the offical how-to, but failed already during installation:
```
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
OK
```
```
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
```
```
sudo apt update
Hit:1 http://de.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                               
Hit:3 http://de.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                             
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                              
Ign:5 http://repo.radeon.com/rocm/apt/debian xenial InRelease           
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease                                      
Err:7 http://repo.radeon.com/rocm/apt/debian xenial Release                                       
  404  Not Found [IP: 13.82.220.49 80]
Hit:8 http://dl.google.com/linux/chrome/deb stable Release
Reading package lists... Done                      
N: Ignoring file 'rocm' in directory '/etc/apt/sources.list.d/' as it has no filename extension
E: The repository 'http://repo.radeon.com/rocm/apt/debian xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
```
sudo apt-get install rocm-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
N: Ignoring file 'rocm' in directory '/etc/apt/sources.list.d/' as it has no filename extension
E: Unable to locate package rocm-dkms
```
I have new clean installation of Ubuntu 18.04.

**Comment by aaksud** [comment]
Hi,
 Can you try again ? I just tried it on my 18.04 system and am able to download rocm without any issues.

**Comment by TobiasJu** [comment]
Hi aaksud,

well your answer worked, thanks. 
I did exactly the same steps, 3 times. Then reported here, than again a 4th time and then it worked. The more I learn, the less I seem to know about Ubuntu.

**Comment by massimotamos** [comment]
This ROCm project is a mega disaster. Nothing works despite trying out all the info on blogs and documentation. AMD website and documentation is not at the expected quality level.

**Comment by edhemphill** [comment]
So:

```
Need to get 756 B of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 http://repo.radeon.com/rocm/apt/debian xenial/main amd64 rocm-dkms amd64 3.5.1-34
  404  Not Found [IP: 13.82.220.49 80]
E: Failed to fetch http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocm-dkms/rocm-dkms_3.5.1-34_amd64.deb  404  Not Found [IP: 13.82.220.49 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

But here is the thing - there is no `rocm-dkms_3.5.1-34_amd64.deb` at the given path at repo.radeon.com. The latest version there is 3.5.0-30

http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocm-dkms/

So what's up AMD? The issue is not closed. Whoever is supposed to be maintaining the repo is not doing their job. Get it together. Seriously.  CUDA stuff just works.

**Comment by xuhuisheng** [comment]
please try http://repo.radeon.com/rocm/apt/3.5.1/pool/main/r/rocm-dkms/

**Comment by cia05rf** [comment]
If it helps anyone later on searhcing this i found my solution was that i'd missed out `apt` from the path

it was:
`deb [arch=amd64] https://repo.radeon.com/rocm/debian/ xenial main`

it SHOULD have been:
`deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ xenial main`

**Comment by kleyton67** [comment]
The link to gpg key is: http://repo.radeon.com/rocm/rocm.gpg.key

**Comment by NickDeBeenSAE** [comment]
Yeah..... I am having the same exact problems as everyone above.

**Comment by NickDeBeenSAE** [comment]
Huh, ROCm appears to not support consumer GPU's other then a Radeon Vega VII.
