### ISSUE TITLE
Darktable stopped working after recent update

### ISSUE THREAD

**Issue by Aceler** [RadeonOpenCompute/ROCm#846]
Ubuntu 19.04, rocm from PPA. After recent update near 10-11 of july, darktable can't start with opencl enabled.

Console output and Backtrace:
[Console output.txt](https://github.com/RadeonOpenCompute/ROCm/files/3396058/Console.output.txt)
[darktable_bt_W0XY4Z.txt](https://github.com/RadeonOpenCompute/ROCm/files/3396059/darktable_bt_W0XY4Z.txt)

I use upstream kernel driver from kernel 5.0.0, but I also tried rocm driver with kernel 4.15 with the same outcome.

**Comment by sarunasb** [comment]
Confirmed, darktable 2.6, Linux 5.2.0-050200rc6-generic.

[darktable_bt_MDKM5Z.txt](https://github.com/RadeonOpenCompute/ROCm/files/3422569/darktable_bt_MDKM5Z.txt)

**Comment by pramenku** [comment]
Please expect fix in ROCm2.7

**Comment by dahabakuk** [comment]
updated to RCOm2.7 today on debian buster and it darktable works again! thanks guys

**Comment by pramenku** [comment]
Thanks for the update and good to know.
Please close this issue.
