### ISSUE TITLE
Where to find cxlactivitylogger?

### ISSUE THREAD

**Issue by justdanyul** [RadeonOpenCompute/ROCm#849]
I'm messing around with trying to get Tensorflow-rocm running on Arch Linux, I ran into quite a few wrinkles so far, all resolvable, but now, I ran into one I can't seem to resolve.

Long story short, on your official documentation refers to a package called cxlactivitylogger, which I can't use, so, I'll need to build it from source.

However, I can't find it anywhere. How can I go about building this from source?

**Comment by acowley** [comment]
I’ve been using [this recipe](https://github.com/nixos-rocm/nixos-rocm/blob/master/pkgs/development/libraries/cxlactivitylogger/default.nix) for that purpose on NixOS.

**Comment by justdanyul** [comment]
Thanks a lot! I was looking in all the wrong places heh. I was searching for it in RadeonOpenCompute, not GPUOpen-Tools.

**Comment by pramenku** [comment]
If you need compiled Debian, you can get at http://repo.radeon.com/rocm/apt/debian/pool/main/c/cxlactivitylogger/

ROCm Profiler/CXLactivitylogger is an archived and old project as per https://github.com/rocmarchive/ROCm-Profiler

Same has been replaced with https://github.com/GPUOpen-Tools/RCP

If you issue resolved, you can close this issue.
