### ISSUE TITLE
Is HCC supported for Kaveri APUs? Kaveri APU are based on GCN 2.0 architecture, so will the HCC and ROCM provide support for these platforms 

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCm#85]

**Comment by jedwards-AMD** [comment]
THe HCC compiler will not be supported on Kaveri APUs, just as ROCm is not supported on Kaveri APUs. Please see the main ROCm page for a list of supported APUs, CPUs and ASICS.

**Comment by VishwasRao17** [comment]
•We also do not support AMD Carrizo and Kaveri APU as host for compliant dGPU attachments. But it is mentioned that test platform used for testing ROCm drivers is AMD7850K . We are not using discrete GPU, we are using the APU only which has integrated GPU in it. Correct me if I am wrong please.

**Comment by mirh** [comment]
> THe HCC compiler will not be supported on Kaveri APUs, just as ROCm is not supported on Kaveri APUs.

Are you sure? According to [one of your colleagues](https://lists.freedesktop.org/archives/amd-gfx/2017-September/013609.html) Kaveri should be supported. 
Of course not with dedicated gpus (since the cpus even lack PCIe Atomics, afaik), but still.
