### ISSUE TITLE
Repo GPG key expired

### ISSUE THREAD

**Issue by Jenot** [RadeonOpenCompute/ROCm#854]
pub   rsa4096 2016-08-01 [SC] [expired: 2019-08-02]
      CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
uid           James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>
sub   rsa4096 2016-08-01 [E] [expired: 2019-08-02]

**Comment by zhang2amd** [comment]
The public key file has been updated as well as the checksum in the readme. Please re-import the key and try again.
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
sudo apt update
