### ISSUE TITLE
Is BFloat16 supported on radeon7 (non MI-5/60)?

### ISSUE THREAD

**Issue by witeko** [RadeonOpenCompute/ROCm#855]
Is BFloat16 supported on radeon7 (non MI-5/60)?
Can I use mixed precision in rocm-tensorflow?

**Comment by ekuznetsov139** [comment]
As far as I can tell, the native fp16 format used by all modern GPUs (including Radeon 7) is float16, *not* bfloat16. 

The stuff about support of bfloat16 in their docs is mostly about being able to load existing bfloat16 models (they even say that the arithmetic is going to be done in fp32).

If that is what you need, I can't help you. If you want to use mixed precision and for it to be faster than straight up fp32, you need to use tf.float16. Which is supposed to be supported within rocm ( see https://community.amd.com/thread/222479 ).

**Comment by witeko** [comment]
@ekuznetsov139 ok, thanks for the answer. :)

**Comment by IIIBlueberry** [comment]
hmn? but Miopen 2.0.0 just included support for bfloat16? https://github.com/ROCmSoftwarePlatform/MIOpen/releases

**Comment by dagamayank** [comment]
MIOpen supports `bfloat16` on Radeon VII using software emulation. As correctly stated by @ekuznetsov139 Radeon VII does not have native HW acceleration for `bfloat16`.

@witeko  @IIIBlueberry please try out this feature and report any issues you encounter on our TensorFlow [repo](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream).
