### ISSUE TITLE
How To Fix ‘The System Running In Low Graphics Mode’ Error (Linux)

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCm#87]
After installing ROCM on Ubuntu 14.04.3 , I am getting an error "How To Fix ‘The System Running In Low Graphics Mode’ Error (Linux)"

How to resolve this !!

**Comment by jedwards-AMD** [comment]
What is your platform configuration? For examples, are you running with a dGPU or an APU?

**Comment by VishwasRao17** [comment]
We are having APU , A107860K . Sitting on a A88 x pro mother board. So its a APU desktop subsystem.
