### ISSUE TITLE
rocm-smi 2.7 starts with a space (so the first line ends one char to late) - breaks my "feng shui"

### ISSUE THREAD

**Issue by witeko** [RadeonOpenCompute/ROCm#870]
![rocmfeng](https://user-images.githubusercontent.com/34566457/63210344-72f5bc00-c0ed-11e9-9e70-2fe2c064c2fb.png)

bug is bug

**Comment by kentrussell** [comment]
Agreed. I'll get it aligned for 2.8

**Comment by witeko** [comment]
@kentrussell TY :)

**Comment by kentrussell** [comment]
Fixed in 2.8. Sorry for messing up the feng shui. Consider your shui feng'd as of 2.8 :)

**Comment by witeko** [comment]
Thanks Kent, atm I'm having a short "break" in Madrid, Spain, so I'm relaxed. :) -------- Original Message --------Subject: Re: [RadeonOpenCompute/ROCm] rocm-smi 2.7 starts with a space (so the first line ends one char to late) - breaks my "feng shui" (#870)From: Kent Russell To: RadeonOpenCompute/ROCm CC: witeko ,Author Fixed in 2.8. Sorry for messing up the feng shui. Consider your shui feng'd as of 2.8 :)
