### ISSUE TITLE
Intel Haswell + Coruja dGPU  ROCm verifcation

### ISSUE THREAD

**Issue by FalconBsp** [RadeonOpenCompute/ROCm#88]
Hi, 
I try to run ROCm vector_copy on Intel Haswell + Coruja dGPU combination. Vector_copy works fine. But i am suspecting with Virtual CRAT table creation .

Do we need separate BIOS to support CRAT table for Intel Haswell ?

[    4.691934] AMD IOMMUv2 driver by Joerg Roedel <jroedel@suse.de>
[    4.718973] AMD IOMMUv2 functionality not available on this system
[    4.747848] CRAT table not found
[    4.774840] Virtual CRAT table created for CPU
[    4.932931] Parsing CRAT table with 1 nodes
[    4.958942] Creating topology SYSFS entries
[    4.985162] Topology: Add CPU node
[    5.011497] Finished initializing topology
[    5.039518] kfd kfd: Initialized module

**Comment by FalconBsp** [comment]
Does Intel also contain CRAT table or only AMD APU's support CRAT table?

If no CRAT table support in Intel , How the performance impact with Virtual CRAT table ?

**Comment by jedwards-AMD** [comment]
Only AMP APU's require a CRAT table. What makes you suspect that a virtual CRAT was created? Also, if a virtual CRAT table is created it would have no impact on the performance of a Intel CPU/dGPU combination.
