### ISSUE TITLE
rocm 2.8 broken

### ISSUE THREAD

**Issue by CharlyGH** [RadeonOpenCompute/ROCm#896]
I'm using tensorflow-rocm for one year starting with ROCm 1.8. All went well until ROCm 2.7 but after upgrading to ROCm 2.8 **all my keras scripts** using tensorflow-rocm crash with the following message:

2019-09-29 10:17:31.998660: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-29 10:17:32.025349: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3493025000 Hz
2019-09-29 10:17:32.027123: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a791e0 executing computations on platform Host. Devices:
2019-09-29 10:17:32.027143: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-29 10:17:32.027453: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libhip_hcc.so
*** stack smashing detected ***: <unknown> terminated
Abgebrochen (Speicherabzug geschrieben)

I tried to rename /opt/rocm und reinstalled the full ROCm software but got the same effect.

**OS:**
Linux rose 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Devices:**
HSA Agents               
Agent 1                  
  Name:                    AMD Ryzen Threadripper 2950X 16-Core Processor
  Marketing Name:          AMD Ryzen Threadripper 2950X 16-Core Processor
Agent 2                  
  Name:                    gfx803                             
  Marketing Name:          Ellesmere [Radeon RX 470/480/570/570X/580/580X]

Sincerely
Charly

**Comment by witeko** [comment]
Probably You need to use: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/641

**Comment by CharlyGH** [comment]
$ pip3 install tensorflow-upstream
Collecting tensorflow-upstream
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/tensorflow-upstream/

**Comment by eyewy** [comment]
I was using Tensorflow 2 beta v3 with rocm 2.7, and all was good. After updating to rocm 2.8 using apt-get, I am seeing same issue:

 I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libhip_hcc.so
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

Please release a wheel for Tensorflow rc1 or rc2.

**Comment by onur-v** [comment]
I am also experiencing the same issue (identical error with identical setups).

**Comment by sunway513** [comment]
Hi @CharlyGH @onur-v we have released ROCm2.8 compatible whl packages for TF1.14, please use the following option to upgrade, e.g. for python3
`pip3 install --user tensorflow-rocm --upgrade`
Make sure the TF version is 1.14.2:
`python3 -c 'import tensorflow as tf; print(tf.__version__)' # for Python 3`

@eyewy , we are finalizing TF2.0.0 release for ROCm2.8, will update here once that's publicly available.

**Comment by CharlyGH** [comment]
Hi sunway513,
I upgraded to TF 1.4.2 as you suggested and now it works again.
Thank You
