### ISSUE TITLE
Support for Navi based GPU

### ISSUE THREAD

**Issue by Blaxou** [RadeonOpenCompute/ROCm#898]
Hey ! 
I was wondering, is there any chance `ROCm` is going to support Navi GPUs in the future ? I know `AMDGPU` supports it but it currently is kinda broken at least on the 5700 XT.

Thanks, and have a great day ;)

**Comment by WannaBeOCer** [comment]
Already answered in  [#887](https://github.com/RadeonOpenCompute/ROCm/issues/887)

**Comment by Blaxou** [comment]
@WannaBeOCer Alright, didn't see there already was a issue, closing ^^
