### ISSUE TITLE
Unofficial RHEL/CentOS 8.0 support??

### ISSUE THREAD

**Issue by wsphillips** [RadeonOpenCompute/ROCm#904]
I haven't been able to find any open or closed issues asking this:

What's the status of RHEL/CentOS 8.0? Since they natively run kernel 4.18 can we already (or soon) expect support from ROCm kernel drivers?

**Comment by kentrussell** [comment]
The official stance on supported OSes is detailed at the ROCm README (https://github.com/RadeonOpenCompute/ROCm). We don't officially support 8.0 at this time, and there is no specific timeframe promised, as there are always potential issues that can arise but we are working towards supporting it. Unfortunately, I can't guarantee a release for it right now.

**Comment by rkothako** [comment]
Hi @wsphillips 
As per internal distro policy, we will support Cent/RHEL 8.0 from ROCm3.2(around Feb/March time) onwards.

**Comment by wsphillips** [comment]
Thanks for the feedback! Good to know there's planned support in the works. Much appreciated.

**Comment by akostadinov** [comment]
@rkothako, would you share whether there are chances to see this soon? Or should I expect that a longer delay is expected?
