### ISSUE TITLE
OpenCL not initialized without a monitor

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#907]
Using latest ROCm (2.9), Ubuntu 19.10, Linux kernel 5.4.0-rc2, GPUs 2x Radeon VII.
When I boot without any monitor connected:
- the ROCm stack is OK, GPUs detected correctly, rocm-smi works fine, sees both GPUs
- but OpenCL is not initialized, clinfo reports 0 devices.

As soon as a monitor is attached, OpenCL start working correctly, clinfo correctly reports all the devices (without reboot). This are the additional entries that appear in dmesg on monitor being connected:
[   91.028230] [drm] fb mappable at 0xC0785000
[   91.028231] [drm] vram apper at 0xC0000000
[   91.028231] [drm] size 16384000
[   91.028231] [drm] fb depth is 24
[   91.028232] [drm]    pitch is 10240
[   91.028321] fbcon: amdgpudrmfb (fb0) is primary device
[   91.073250] Console: switching to colour frame buffer device 160x50
[   91.087170] amdgpu 0000:06:00.0: fb0: amdgpudrmfb frame buffer device

After this, clinfo reports 2 devices (correct).

Expected behavior: OpenCL does not require a monitor being connected to initialize (similarly to the rest of the ROCm stack, that works fine without a monitor).

**Comment by valeriob01** [comment]
It is different behavior from amdgpu-pro, where opencl works without any monitor. Perhaps they can be aligned in features/performance?

**Comment by Djip007** [comment]
what report:
```
cat /sys/bus/pci/drivers/amdgpu/*/power/control
```

**Comment by preda** [comment]
now when OpenCL is working (i.e. after the attach-monitor):
cat /sys/bus/pci/drivers/amdgpu/*/power/control
on
on

I'll report the other situation (before monitor) when I restart that computer.

**Comment by preda** [comment]
The bug is still present on kernel 5.4.0-050400rc6, and I have some new info:

1. after boot, if I ssh into the machine, I get "Number of devices 0" in clinfo.
2. I connect a monitor, login in the GUI (the default for Ubuntu 19.10), clinfo now reports 2 devices.
3. I logout on the GUI,
4. ssh clinfo now reports 0 devices
5. login on the GUI again, and *remain logged-in* ("lock screen")
6. ssh clinfo now reports 2 devices correctly

**Comment by pettai** [comment]
Just curious;
You run Ubuntu 19.10 + ROCm 2.9 (+working graphics then the monitor is attached).
Did you manage to install rock-dkms/rocm-dkms without this issue ( Ref. https://github.com/RadeonOpenCompute/ROCm/issues/969 ) ?

**Comment by pettai** [comment]
Did you try run clinfo as root vs a regular user (added to the video group)?
clinfo also reports 0 devices for me, but it reports all radean vega cards then I run clinfo as root.
I can also run an opencl application if I run it as root.

**Comment by BloodyIron** [comment]
I'm not having any luck getting ROCM working with 19.10. I've tried 2.9, 2.10 and 3.0. I had 2.9 working before, unsure how I was able to get that working now that I think about it. Was really hoping ROCM 3.0 would work for me, since it supposedly works with Linux 5.3 that's now in 18.04.4.

:(

I'd be open to any keen ideas!

**Comment by preda** [comment]
Closing as old, didn't check recently.
