### ISSUE TITLE
Question: Supported Ryzen motherboard with dual Fiji setup.

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/ROCm#92]
Hi,
I was wondering what motherboard to get for Ryzen 7 1700 + dual Fiji setup for ROCm. Does B350 chipset support dual setup using ROCm? I'm looking at uATX setup and it looks like only B350 chipset is available on uATX form factor.

So far, I found two ASUS Prime B350M-A/CSM and Gigabyte AB350M-D3H. But they are out of stock at the moment. :(

**Comment by gstoner** [comment]
Even we do not have these boards yet.   We just getting your commercial board like you.  We only had internal development boards.   We let you know which one we like.

G
On Mar 2, 2017, at 11:37 AM, Brian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I was wondering what motherboard to get for Ryzen 7 1700 + dual Fiji setup for ROCm. Does B350 chipset support dual setup using ROCm? I'm looking at uATX setup and it looks like only B350 chipset is available on uATX form factor.

So far, I found two ASUS Prime B350M-A/CSM and Gigabyte AB350M-D3H. But they are out of stock at the moment. :(

**Comment by gstoner** [comment]
On the Ryzen CPU it only supports 32 Lane of PCIe Gen3,  for Computing you want your GPU close to the CPU.  you need a motherboard that supports a x16 lane and second x8 lane with full x16 slot
