### ISSUE TITLE
When will the Radeon RX 5700 XT support ROCm

### ISSUE THREAD

**Issue by omerferhatt** [RadeonOpenCompute/ROCm#926]
I purchased the RX 5700 XT and was planning to use it in my ML projects. But I realized that the card has not yet received ROCm support. Is there a scheduled release date? If not, I will return the card back to the store. Hopefully, it will be answered quickly and precisely.

**Comment by seesturm** [comment]
AFAIK the most accurate statement currently available is [this comment](https://github.com/RadeonOpenCompute/ROCm/issues/819#issuecomment-532886041). My interpretation of the comment is that nobody official is willing to give a hint when it will be released. In principle it could even take years before it is supported.

Between the lines it looks like as if they intend to eventually support Navi. But personally I wouldn't buy a Navi card if I want to do ML within the next months.

**Comment by omerferhatt** [comment]
Thank you for your reply. I'm sorry to hear that. I am going to return my card.

**Comment by nuliknol** [comment]
>I am going to return my card.
@omerferhatt 
so why can't you code the kernels of your ML projects with OpenCL ?

**Comment by ashishchoure23** [comment]
Why returning, use plaidML with Keras. It works like charm.
