### ISSUE TITLE
invalid argument to reshape in toy autoencoder

### ISSUE THREAD

**Issue by boldingd** [RadeonOpenCompute/ROCm#931]
Summary of your hardware:
CPU: Ryzen 7 1700x
GPU: Radeon RX Vega 64
Motherboard: ASRock X370 Gaming X

PCIe Information: output of lshw attached

Something is throwing up InvalidArgumentError at a random point during training.

I built a toy autoencoder using keras; at a random point during training, it dies with an error.  My code is never using tf.reshape, so presumably this is something internal.

The failure happens at a random point several epochs in; it's failed as early as the 7th epoc, and its failed after the 100th.

I have attached a minimal program that reproduces the bug, and sample output.

[random crash.py.txt](https://github.com/RadeonOpenCompute/ROCm/files/3823173/random.crash.py.txt)
[error snipped.txt](https://github.com/RadeonOpenCompute/ROCm/files/3823178/error.snipped.txt)

**Comment by boldingd** [comment]
oops, forgot lshw
[hw.txt](https://github.com/RadeonOpenCompute/ROCm/files/3823185/hw.txt)

**Comment by sunway513** [comment]
Hi @boldingd , please refer to the following issue:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/325
We have pushed out a fix in HIP runtime, which will be part of ROCm3.0 release.
Before that, you can use the following docker container:
sunway513/tensorflow:rocm2.9-tf1.15-dev-hipEventRecord-patch
