### ISSUE TITLE
ROCm next release

### ISSUE THREAD

**Issue by omerferhatt** [RadeonOpenCompute/ROCm#933]
When will next release come ? Any updates ?

**Comment by rkothako** [comment]
Hi @omerferhatt 
ROCm 2.10 is going to be released very soon like around a week time.
ROCm 3.0 will be released in next month - December (as per plans).

**Comment by qixiang109** [comment]
what will be the main feature of ROCm 3.0?

**Comment by omerferhatt** [comment]
> Hi @omerferhatt
> ROCm 2.10 is going to be released very soon like around a week time.
> ROCm 3.0 will be released in next month - December (as per plans).

Thank you.
