### ISSUE TITLE
Navi support

### ISSUE THREAD

**Issue by NiklasDallmann** [RadeonOpenCompute/ROCm#942]
Is ROCm support for Navi GPUs planned?

**Comment by smartbitcoin** [comment]
the only plan we know is rocm 3.0 just announced last week.   but not include navi related detail yet.
before official rocm navi ready , you can test navi with HIP  on community build :  https://github.com/smartbitcoin/MyROCm ,  but there are still some well known issue there.

**Comment by ianferreira** [comment]
Hello @ROCmSupport , any ETA when in 2021 we will see support for Navi?

**Comment by xuhuisheng** [comment]
@ianferreira 
As AMD mentioned, maybe 2 or 4 month.
https://github.com/RadeonOpenCompute/ROCm/issues/887#issuecomment-822222885

**Comment by wormwang** [comment]
when support Navi ？ After so many Navi based Radeon pro card released.

**Comment by ROCmSupport** [comment]
Thanks @NiklasDallmann for reaching out.
Please expect support of some version of Navi cards before end of this year. I can not share more details on specific versions due to limitations.
Hope this helps.
Thank you.
