### ISSUE TITLE
Will ROCm support AMD Radeon Pro 5500M?

### ISSUE THREAD

**Issue by cyyeh** [RadeonOpenCompute/ROCm#943]
The latest macbook pro 16-inch has AMD Radeon Pro 5500M. However, I found that it seems that now ROCm doesn't support this GPU? Would ROCm support this GPU in the near future? Thanks!

**Comment by thesyntaxinator** [comment]
What is the answer to this?

**Comment by carteeeltheboss** [comment]
2025 here, any updates on ROCm for MBP 2019 5500M ??
