### ISSUE TITLE
Please clarify OpenCL future support in ROCm

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#951]
I see in the release notes for ROCm 2.10 that ROCm OpenCL Driver is listed as "Deprecated Feature". As an OpenCL developer, I would like some clarification about what it means:

- is there commitment to support OpenCL in ROCm in the future?
- or, am I given the choice ("forced to") choose between the language and the platform?

**Comment by b-sumner** [comment]
@preda that project is merely an old *compiler* driver which we have replaced with the new "Code Object Manager" (COMgr) which includes compilation services.  ROCm itself will continues to provide an OpenCL runtime which supports the OpenCL 2.0 runtime API and either OpenCL 1.2 or 2.0 C source (depending on the device).

**Comment by preda** [comment]
Thank you for the clarification. I'm glad to hear OpenCL will continue to be supported in ROCm.

**Comment by b-sumner** [comment]
You're welcome.  You're not the only one who raised concerns.  I expect the release notes will be improved.
