### ISSUE TITLE
Installation notes typo

### ISSUE THREAD

**Issue by mflai** [RadeonOpenCompute/ROCm#957]
wget -q0 – http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key

should it be "-qO" instead of -q0" ?

**Comment by jonnyli** [comment]
I had the same issue, it looks like it is supposed to be a letter and not a number.

I have a slightly related issue following this part of the installation:
`Warning: apt-key output should not be parsed (stdout is not a terminal)`

Unfortunately I am new to Linux, is there another way to do add this repository?

**Comment by zhang2amd** [comment]
Thanks for raise the issue. It was a typo during readme update. Fixed.
