### ISSUE TITLE
Different branches of llvm-project

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/ROCm#988]
There are currently different repositories and branches to build components of ROCm.

To build ROCm-OpenCL-Runtime "roc-ocl-3.0.0" branch from https://github.com/RadeonOpenCompute/llvm-project (fork) should be used.

To build ROCm-Device-Libs "amd-std-open" branch from https://github.com/RadeonOpenCompute/llvm-project.git (fork) should be used.

And to build AOMP "AOMP-191029" branch from https://github.com/ROCm-Developer-Tools/llvm-project (mirror) is used. According to the clone script, for "ROCm-Device-Libs" "roc-ocl-3.0.x" branch, the same compiler is used.

It seems that building "ROCm-OpenCL-Runtime" and "AOMP" (OpenMP) needs two different branches of compilers(?).

Will this be merged together, to get one repository and one branch to build them all?

**Comment by justxi** [comment]
No comment? =)

**Comment by ronlieb** [comment]
Yes, the two different branches of LLVM are in the process of being merged so that one branch can build(rule) them all.

**Comment by searlmc1** [comment]
@gregrodgers @acmeman925

**Comment by justxi** [comment]
Good to hear =).
