### ISSUE TITLE
Which version of tensorflow is supported in ROCm 3.0 ?

### ISSUE THREAD

**Issue by mk2016a** [RadeonOpenCompute/ROCm#996]
When I upgrade the new ROCm, the old tensorflow 2.0 not work at all.

I think it only supports the newest tensorflow framework.

Thanks for snapshort of the disk.  I rolled back before upgrade.

**Comment by dagamayank** [comment]
@sunway513

**Comment by sunway513** [comment]
Hi @mk2016a , please refer to the following doc on ROCm3.0 compatible tensorflow-rocm pypi packages:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md
In addition, you can use the following command to upgrade the tensorflow-rocm package to the latest available:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md#install-tensorflow-rocm-release-build
