### ISSUE TITLE
ROCm support for gfx1010?

### ISSUE THREAD

**Issue by kalaluthien** [RadeonOpenCompute/ROCm#998]
Is ROCm v3.0 fully support gfx1010? Especially `tensorflow-rocm` (tf2.0).

**Comment by omerferhatt** [comment]
#819 You can check it from "Supported Hardwares" on documentation. For now you can use ROCM like graphic driver, not for computational operations. tensorflow-rocm still don't have any support for gfx1010 (navi) based cards.

**Comment by kalaluthien** [comment]
Thanks for your reply!

**Comment by mritunjaymusale** [comment]
Agreed, I have a 5700xt and I pulled the pytorch docker image and it didn't run the examples

**Comment by Rmalavally** [comment]
Refer the "Hardware and Software Support" section in ROCm Release Notes or documentation. For now, you can use the ROCm-like graphic driver, however, not for computational operations. Tensorflow-rocm does not support gfx1010 (navi)-based cards.
