### ISSUE TITLE
Support R7 M360

### ISSUE THREAD

**Issue by soham-d** [RadeonOpenCompute/ROCm#999]
Can anyone please confirm if GPU AMD Radeon R7 M60 is supported by ROCm?

**Comment by frranck** [comment]
Hi Soham, did you try it? I have a similar card.

**Comment by orrburgel** [comment]
Name	AMD Radeon (TM) R7 360 Series

I think I got the same card, Is it supported?

**Comment by ROCmSupport** [comment]
Hi @soham-d and @frranck 
Thanks for reaching out.
Radeon R7 360 is not officially supported by ROCm as per [https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support](url)

**Comment by ROCmSupport** [comment]
Hi @orrburgel and @frranck 
Cards mentioned by you are not officially supported.
Hope this helps.
Thank you.
